### ISSUE TITLE
Pass character used for thematic break (hr) to render function

### ISSUE THREAD

**Issue by r0the** [markedjs/marked#1031]
## Expectation

Markdown allows to use three different characters (`-`, `*`, or `_`) for thematic breaks (hr). I'd like to customize the output of the `hr()` render function depending on the character used.

I'd expect the following markdown to cause the function calls
- `hr('-')`
- `hr('*')`
- `hr('_')`
```
---
***
___
```

**Comment by Feder1co5oave** [comment]
+1
This could go the right way for extensibility and developer experience @joshbruce

**Comment by joshbruce** [comment]
Closing as not part of the current focus - flagged for possible future consideration. See #1106 and #1216
