### ISSUE TITLE
HTML following between two comments don't get recognized as HTML

### ISSUE THREAD

**Issue by qzhou1607** [markedjs/marked#1032]
```html
<!-- This is a comment -->
<details>
<summary>
    This is the summary.
</summary>
Hello!

hello!

hello!
</details>
<!-- This is a comment -->
``` 

## Expectation

```html
<!-- This is a comment -->
<details>
<summary>
    This is the summary.
</summary>
Hello!

hello!

hello!
</details>
<!-- This is a comment -->
``` 

## Result

```html
<!-- This is a comment -->
<p><details></p>
<p><summary>
    This is the summary.
</summary>
Hello!</p>
<p>hello!</p>
<p>hello!
</details>
<!-- This is a comment --></p>
```

## What was attempted

As shown above, HTML code between two comments are identified as `paragraph`s instead of `html`. Inserting blank lines between the comments and the HTML code in markdown temporarily solved the rendering issue. But the html regex in `marked.js` needs to be modified to recognize HTML both **before** and **after** a comment.

Alternatively, it could just mention in the documentation that blank lines are required between the comments and the HTML code.

https://github.com/chjj/marked/blob/84c330b62beee7dab83764f373eaf80414b2516e/lib/marked.js#L23

**Comment by Feder1co5oave** [comment]
There sure are a lot of `\n` inside the html regex...
Commonmark.js parses this as expected.
I'g flag it or 0.4 and categorize under html (/mixed content ?)

Thanks for reporting this @qzhou1607 !

**Comment by joshbruce** [comment]
Sounds fair. I don't know the specs well enough to understand their stance on comments. Logically it's just part of HTML - but I'm weird when it comes to my Markdown (avoid putting HTML in there like the plague). :)

**Comment by joshbruce** [comment]
#985
