### ISSUE TITLE
Space in code (```) a wrong 

### ISSUE THREAD

**Issue by theGABS** [markedjs/marked#1045]
## Expectation

Space and tabs show as I wrote

## Result

every two space replace with new line

## What was attempted

I try extends 

renderer.code = (code, language) => {
  debugger // code variable already with wrong space
  return `<pre><code class="lang-${language}">${code}</code></pre>`
}

I try use Reveal.js via npm (and React). 
And highlight.js

**Comment by Feder1co5oave** [comment]
This is unclear. I think we should update the issue template to make sure people post actual examples of input, output and expected texts.

**Comment by theGABS** [comment]
Okay, tomorrow I will write better example

**Comment by theGABS** [comment]
So, when I wrote 

```javascript
function fancyAlert(arg) {
  if(arg) {
                $.facebox({div:'#foo'})
  }
}

```
I got
![image](https://user-images.githubusercontent.com/8490641/36031472-91dff9b2-0db3-11e8-9732-7fc3fab1e85f.png)


Instead of correct tab.
Every two space replace with new line.

**Comment by joshbruce** [comment]
#983

**Comment by Feder1co5oave** [comment]
I cannot reproduce this:

```html
$ bin/marked 
	function fancyAlert(arg) {
	  if(arg) {
	                $.facebox({div:'#foo'})
	  }
	}
<pre><code>function fancyAlert(arg) {
  if(arg) {
                $.facebox({div:&#39;#foo&#39;})
  }
}
</code></pre>
```
You're most probably altering either the input or the ouput before/after calling `marked()`
