### ISSUE TITLE
wrong h3 indentation after bullet point

### ISSUE THREAD

**Issue by wischi-chr** [markedjs/marked#1047]
The following markdown is not rendered correctly

```
# Indentation Test

### Header 1
  - Bulletpoint 1
### Header 2 <---
  - Bulletpoint 2
```

On github it looks like this: https://gist.github.com/wischi-chr/dc48d7957e80fb4e2024f7f304489ced
![correct_markdown](https://i.imgur.com/dciJDNV.png)

but it's rendered like that:

![wrong_markdown](https://i.imgur.com/Qfi11b2.png)

**Comment by joshbruce** [comment]
Believe this is related to new lines and possible regex - believe you would see the same behavior from the original Daring Fireball implementation as well. Can you try the following:

```
### Header 1

- Bulletpoint 1

### Header 2

- Bulletpoint 2
```

**Comment by wischi-chr** [comment]
Thanks for the workaround.

Is it considered a bug or is that intentional?

**Comment by joshbruce** [comment]
This is the "proper" way to write Markdown, according to the original definition - this differentiates between block-level elements of different types.

https://daringfireball.net/projects/markdown/basics

Having said that, it looks like the CommonMark spec, it would be classified as a defect.

Do you know if you are using the `pedantic` setting on Marked? Or, the CommonMark or GFM settings?

**Comment by wischi-chr** [comment]
I'm not 100% sure (on mobile right now) but I think I've tried it.

**Comment by joshbruce** [comment]
Pedantic = Original Daring Fireball spec. So, probably should use the blank lines.

Otherwise, we’ve marked it for consideration and further discussion.

**Comment by Feder1co5oave** [comment]
I confirm, marked currently produces

```html
<h1 id="indentation-test">Indentation Test</h1>
<h3 id="header-1">Header 1</h3>
<ul>
  <li>
    Bulletpoint 1
    <h3 id="header-2-">Header 2 &lt;---</h3>
  </li>
  <li>Bulletpoint 2</li>
</ul>
```

whereas commonmark 0.28

```html
<h1>Indentation Test</h1>
<h3>Header 1</h3>
<ul>
  <li>Bulletpoint 1</li>
</ul>
<h3>Header 2 &lt;---</h3>
<ul>
  <li>Bulletpoint 2</li>
</ul>
```

This is most probably relative to the `list` rule.

**Comment by zhuyangbing** [comment]
I have the same problem. Is this issue fixed?

**Comment by joshbruce** [comment]
@zhuyangbing: Feder1co5oave recently stepped away from the project for a while. There's only four of us right now and none of us have the level of knowledge regarding the library that he did. We are also reconsidering our priorities to ensure we don't keep burning out our highest performers.

If you can help solve the problem, we should be able to get it into the next release; otherwise, please be patient as we figure some stuff out. Thank you.

**Comment by UziTech** [comment]
fixed
