### ISSUE TITLE
Customize inline lexer

### ISSUE THREAD

**Issue by ForbesLindesay** [markedjs/marked#105]
I'd like to be able to customize the inline lexer with an additional type (specifically math).  At the moment it's not extendable.  There as an implementation of this in #71 but that request was closed by the OP for some reason.

**Comment by nicbou** [comment]
I second the need for this. I patched the file to include my custom lexer, but it's far from ideal.

**Comment by PeterBocan** [comment]
Any news on this topic? I'd like to see an option to take out "$...$" and "$$...$$" to pass it to MathJax.

**Comment by davitv** [comment]
@PeterBocan , i needed same future, look at this [branch](https://github.com/davitv/marked#adding-new-rules)

**Comment by PeterBocan** [comment]
I'll look at that! Thanks!

**Comment by nisargjhaveri** [comment]
Any news?

**Comment by davitv** [comment]
Look at this [branch](https://github.com/davitv/marked#adding-new-rules)

**Comment by joshbruce** [comment]
Closing. This is not the current focus, see #1106 and #1216. Having said that, we are considering things to include in the 1.x and 2.x versions that allow more extensibility.
