### ISSUE TITLE
If HTML style comments contain headings they do not work

### ISSUE THREAD

**Issue by feinstaub** [markedjs/marked#1050]
This is a Markdown sample which gets rendered unexpectedly. For this...

```
aaa
<!-- test
====
-->
bbb
```

...I would expect this HTML output:
```
aaa
bbb
```

But instead it looks like this:

![grafik](https://user-images.githubusercontent.com/368412/36115270-e373c44e-1032-11e8-8357-53a8fd080a33.png)

**Comment by Feder1co5oave** [comment]
It seems we need to prioritize html blocks before setext headings.

[babelmark](https://johnmacfarlane.net/babelmark2/?normalize=1&text=aaa%0A%3C!--+test%0A%3D%3D%3D%3D%0A--%3E%0Abbb)
