### ISSUE TITLE
MarkedJS org logo

### ISSUE THREAD

**Issue by joshbruce** [markedjs/marked#1057]
We should get a logo for the MarkedJS organization...my marketing brain doesn't like looking at the random image. :)

**Comment by UziTech** [comment]
Just an idea

![image](https://user-images.githubusercontent.com/97994/36323414-7c1883f2-1316-11e8-8b01-b0783c9d4785.png)

**Comment by UziTech** [comment]
![image](https://user-images.githubusercontent.com/97994/36323621-2346daa2-1317-11e8-87b1-e8ae629edbc3.png)

**Comment by joshbruce** [comment]
Here's something interesting - coming off a CommonMark for Markdown itself: https://talk.commonmark.org/t/the-markdown-logo/14

**M**⬇*JS*

**Comment by joshbruce** [comment]
Response to the first: Doesn't indicate Markdown to me.

Response to the second: Seems a bit...phallic??

**Comment by joshbruce** [comment]
M⬇rked

```
M⬇r
ked
```

**Comment by UziTech** [comment]
🤣 @joshbruce good catch didn't see that

**Comment by joshbruce** [comment]
roflmao - Yeah. I learned a lot in design school. I've made a few of those accidentally odd logos myself...still do probably.

**Comment by UziTech** [comment]
Just an modification of the [Markdown Mark](https://talk.commonmark.org/t/the-markdown-logo/14)

![image](https://user-images.githubusercontent.com/97994/36325523-ad5b164e-131d-11e8-8b65-850c6f7c5d1c.png)

**Comment by martinheidegger** [comment]
Just a thought but: the arrow down + js suggests "markdown.js": "M⬆︎rked" in the same style but with ⬆︎ aligned that the arrow "grow" out of the bounding box?

**Comment by UziTech** [comment]
![image](https://user-images.githubusercontent.com/97994/36361201-dd8f0162-14ef-11e8-8714-d3ed81e06a31.png)

![image](https://user-images.githubusercontent.com/97994/36361383-fa6fdcd8-14f0-11e8-9804-ec4f5c68cf53.png)

**Comment by joshbruce** [comment]
Interesting. I've been playing with the arrow thing as well. I also appreciate just having the `marked` as the logotype. Thinking the arrow going down might still be more recognizable as markdown.

<img width="174" alt="screen shot 2018-02-18 at 10 55 47 pm" src="https://user-images.githubusercontent.com/15252830/36363239-0638c7a4-1501-11e8-96e4-dd0d200bab47.png">
<img width="225" alt="screen shot 2018-02-18 at 11 10 08 pm" src="https://user-images.githubusercontent.com/15252830/36363241-064780a0-1501-11e8-874d-ad1a44611e62.png">

Starting with the small square should give a decent foundation for expanding it.

**Comment by carlosvalle** [comment]
**Another option**
![marked-logo](https://user-images.githubusercontent.com/7017869/36363534-f63e07e6-150b-11e8-8163-11dcf0f02479.jpg)

**Comment by Feder1co5oave** [comment]
I'd leave the arrow out of the name... it doesn't look like an A to me.
I kinda like the proposal by @carlosvalle, that E brings some velocity to it.
How about something like
```
MA
RK
ED
```
with that "flaming" E?

Also, I'm not sure we want that extra 'js' in the name, marked is a npm module, so it's javascript by its own nature.

Also, how about some color? :smile:

**Comment by joshbruce** [comment]
@carlosvalle: Digging it. What font family are you using? Definitely appreciating showing the two types (regular + inverted).


@Feder1co5oave: Agree on the JS thing; though for different reasons. I remember hearing somewhere that NPM wasn't just for JS from someone on the NPM team; however, it is kind of becoming a tradition. There's also the difference between the GitHub organization and the packaged itself...maybe remove the JS from the organization??

Color can come later. :)

**Comment by UziTech** [comment]
I think the JS distinguishes marked from other markdown converters in that it was the first _written_ in javascript for the client side.

from the [Philosophy behind marked](https://github.com/markedjs/marked#philosophy-behind-marked):

> It is also now fully compatible with the client-side.

**Comment by carlosvalle** [comment]
@joshbruce: the font family is "Gill Sans"

**Comment by joshbruce** [comment]
<img width="271" alt="screen shot 2018-02-19 at 5 09 41 pm" src="https://user-images.githubusercontent.com/15252830/36400699-4aff483a-1598-11e8-9fcc-5c9d56a7ea2d.png">
<img width="474" alt="screen shot 2018-02-19 at 5 12 45 pm" src="https://user-images.githubusercontent.com/15252830/36400700-4b0e1298-1598-11e8-962a-df28def9c268.png">

**Comment by styfle** [comment]
Can you all edit your submissions so there is only one image per comment?
That way we can properly vote using the 👍 reaction.

**Comment by joshbruce** [comment]
@styfle: Good idea. I think at this point, we should probably go with the ones submitted by @carlosvalle, to be honest.

**Comment by styfle** [comment]
@joshbruce Lets go with it. I would update the org icon but I think I don't have access?

@carlosvalle Can you provide the two colors in two separate files? And maybe providing svg format would be better in case we need to scale it. And congrats on winning our small competition! 🎉

**Comment by joshbruce** [comment]
Sweet!

@carlosvalle: Can we get them in vector format? Just email me. 

@styfle: He and I actually work together. :)

And I got you covered, just give it a bit to settle down around here. It was, after all, one of those Josh days. ;)

**Comment by styfle** [comment]
@joshbruce Were you able to get the logo?

**Comment by joshbruce** [comment]
@styfle: Nah. Can't press per our prioritization and principles re the project. This is something he did out of the kindness of his heart after I mentioned as an aside in our Slack...he's part of the team finally getting to pull something out into the open source community from the work he's been doing on our project. I'm sure you understand.

Having a logo is such a low priority right now compared to other things, I'm going to close this. Maybe when we're ready I'll ask him again...or it will just magically appear on our doorstep...who knows...either, not gonna talk about it with him more than "thank you" I already gave him in person.
