### ISSUE TITLE
Semver 1.0 release

### ISSUE THREAD

**Issue by martinheidegger** [markedjs/marked#1059]
I noticed that `marked` [starts fresh](https://github.com/markedjs/marked/releases/tag/0.3.14) in this year. However this release broke a dependent. Noticing that is 0.3.14, I wonder if it would be in the spirit of "starting fresh" and go for the 1.0 release and in that sense start following semver (breaking change: semver: major)?

**Comment by UziTech** [comment]
Which dependent did `v0.3.14` break? There should not have been any breaking changes.

We have a few [milestones](https://github.com/markedjs/marked/milestones) we want to get done before a  1.0 release

**Comment by martinheidegger** [comment]
https://github.com/firede/msee/issues/58

**Comment by joshbruce** [comment]
@UziTech: Possibly something else we didn’t account for (and not sure we could have really) is that dependents of Marked need to point to the new house and publish an update??

Mine is with SimpleMDE...I will submit a PR there to help them out...??

**Comment by joshbruce** [comment]
Possibly related to #1058 ??

**Comment by Feder1co5oave** [comment]
No, that in unrelated. I is unclear what firede/msee#58 is about, but is seems they were relying on some that broken behavior to do something?

**Comment by UziTech** [comment]
Looks like the breaking change was changing the capturing parentheses on `code`

https://github.com/firede/msee/pull/59

**Comment by joshbruce** [comment]
Sorry, just woke up. NPM doesn't include the vendor name like some other package managers; so, changing the user should have changed anything either.

**Comment by martinheidegger** [comment]
While it is commendable that this is fixed - an 1.0 release would be still awesome. I did find your roadmap to 1.0 nice. But it would make me sleep better if the first major was out.

**Comment by UziTech** [comment]
@martinheidegger I agree but we have a ways to go before 1.0. Once this is completely stable (with automated testing, and making it easier to extend without rewriting the parser) we will get a 1.0 release out. But bringing a project back from the graveyard takes a while.

**Comment by joshbruce** [comment]
@martinheidegger: The first "stable" will probably be considered the 0.4.0 release, as it will be the release prior to architecture changes that will introduce breaking things, should have the specs covered, and all the options still in place.

0.4.0 will probably see some deprecation of options as well as the major architecture changes.
0.5.0 should make it easier for people add whatever options they want to - as @UziTech mentioned.

Just published the 0.3.15 release - let us know if you find something else.
