### ISSUE TITLE
Continuous Integration - and publish to NPM

### ISSUE THREAD

**Issue by joshbruce** [markedjs/marked#1072]
Setting up Circle CI for the first time on a different project...noticed this in one of my references:

```
      - run:
          name: Publish to NPM
          command: |
            npm config set "//registry.npmjs.org/:_authToken=$NPM_TOKEN"
            npm publish
```

Publish the package every time we merge into `master` - seems a bit dangerous, but still. Also thought this might be a good place to chat about all things CI.

@UziTech: Not seeing a way to DM folks in the org. What am I missing there?

**Comment by UziTech** [comment]
start a private discussion at https://github.com/orgs/markedjs/teams/marked/discussions

This is what something like semantic release would take care of. I don't think it is really necessary.

**Comment by joshbruce** [comment]
I tend to agree...just wasn't sure how automated we wanted to make things. I can see some benefit under certain use cases. Something to keep in the back or our minds. Closing.
