### ISSUE TITLE
[Consolidated tools]: List of tools to help improve development of marked

### ISSUE THREAD

**Issue by joshbruce** [markedjs/marked#1074]
Inspired by a conversation in #1058 referencing this tool:

We've been talking about various tools we would like to use to improve quality, stability, and security...thought it might be nice to have a place to consolidate and discuss.

- [x] https://github.com/marketplace/travis-ci
- [ ] https://github.com/NicolaasWeideman/RegexStaticAnalysis

**Comment by Feder1co5oave** [comment]
If we can make this work correctly, we MUST include it in CI!

**Comment by Feder1co5oave** [comment]
I can't find ANY documentation for that tool 😐

**Comment by joshbruce** [comment]
Which on can’t you find documentation on?

Linked because we plan to use it. 😁

This might be a horrible issue to start. Would like to flag all the tool (or methodology) mentions like we’ve been doing the other ones...like the AMD thing.

**Comment by UziTech** [comment]
We could try an eslint plugin for regex security [eslint-plugin-security](https://www.npmjs.com/package/eslint-plugin-security#detect-unsafe-regex)

Never used it but it looks like it might be useful.

**Comment by Feder1co5oave** [comment]
Looks like eslint-plugin-security uses [safe-regex](https://www.npmjs.com/package/safe-regex)

**Comment by joshbruce** [comment]
I like this idea of checking security of regex. Which would be easier to get up on and include with the Travis CI stuff?? Should we consider both as options??

**Comment by joshbruce** [comment]
https://regexper.com - This is intriguing.

**Comment by joshbruce** [comment]
@UziTech: Thinking about closing this one as part of #1120 but there seem to be a couple of tools related to DevOps that we may still want to consider.

**Comment by UziTech** [comment]
We don't need this open to find it
