### ISSUE TITLE
Improved foundation of community standards, project maintenance processes, and tooling

### ISSUE THREAD

**Issue by joshbruce** [markedjs/marked#1078]
Under the new organization, we have a lot more freedom to do things. Thinking once we get to the 1.0 stage it would be nice to have things in place to help new contributors come in and get up and running in short order.

This Issue is for conversation related to ways we can make the operation and maintenance of the project itself easier. Things like README + CONTRIBUTING + templates and so on.

- [ ] Why do we have a Makefile?
- [ ] Are we keeping Bower support up to date?
- [ ] What is the purpose of `component.json`? (Seems like a different type of `package.json` that is out of date.)
- [x] What is the purpose of the `/man` directory and its contents? (Seems like a different type of README this is out of date.) - /man contains the man page that is brought up when you run marked --help.

**Comment by Feder1co5oave** [comment]
Good points. 1,2 and 3 I don't know.

/man contains the man page that is brought up when you run `marked --help`.
I don't know how to edit that, and if it is up to date.

**Comment by joshbruce** [comment]
Closing as relatively complete.
