### ISSUE TITLE
Markdown is broken

### ISSUE THREAD

**Issue by joshbruce** [markedjs/marked#1079]
https://github.com/markedjs/marked/blob/master/doc/broken.md

Just stumbled on this while I was considering something else. Don't when the last time anyone took a look at it, but it seems like one of @chjj's last sort of big contributions. Might be worthwhile to verify relevance against CommonMark and GFM...then remove the `/doc` folder from the project as it doesn't serve a purpose really - beyond this examination.

***
Do we prefer tagging or assignment??

I always liked the idea of me assigning myself (opting in) as opposed to someone assigning me things (too much "You ain't the boss of me" independence going for myself). However, I do appreciate someone tagging me to say, "Hey, you specifically should look at this." So, just curious if there's a preference. I probably won't keep assigning things to people unless that the preference - just feels too weird.

**Comment by Feder1co5oave** [comment]
We get notifications of everything that happens in here, so no tagging needed.
I prefer assigning myself

**Comment by joshbruce** [comment]
That's fair to a point. On the getting notifications about everything...I'm going to write something up about saving yourself from that, which involves tagging. So, please, tag me.

Short version: I have email rules that automatically move messages from GitHub out of my inbox into somewhere else (because I want to "listen", just don't want it to me cluttering the inbox - I review them regularly)...the rules is set to keep messages in which I'm tagged in my inbox though; so, yeah, always feel free to tag me, just in case.

**Comment by joshbruce** [comment]
Closing as legacy documentation.
