### ISSUE TITLE
Coding standards

### ISSUE THREAD

**Issue by joshbruce** [markedjs/marked#1089]
**Marked version:** n/a

**Proposal type:** project operations

## What pain point are you perceiving?

More contributions and a lack of defined and documented coding standards.

See also #1082, #1081, #1083, and a few other conversation areas where we've expressed having this pain point.

## What solution are you suggesting?

1. We have lint checks now.
2. We have Travis now.
3. We have NPM scripts that fix lint issues for us.
4. #1081 has an updated checklist for contributing and a list of our NPM scripts and what they do - not merged yet.

What else do we need or want to help contributors know what is expected in their code?

**Comment by intcreator** [comment]
As a new contributor, should I list a few things here that I don't immediately know?

One of the biggest things is whether or not contributors should use ES6/ES7 features (like arrow functions, object spread, filter, map, reduce, etc.).

I tried hacking the code to customize it a bit and I really have no idea what I'm doing despite having two years of experience working with JavaScript.  Maybe if someone wrote a doc explaining the underlying mechanics of how the library works newcomers could read it and understand the vision better.  This kind of architecture documentation (and indeed an architect who is in charge of the design) is vital to software projects.

**Comment by UziTech** [comment]
No ES6+ until we figure out a transpile build step. We still support older browsers.

**Comment by joshbruce** [comment]
That's a fair question...let's go over to #1096

**Comment by joshbruce** [comment]
Oh! Since you mentioned architecture, check out #746. Get some idea of where we're planning on going. Fortunately, and unfortunately, we have a large user base; so, we're really trying to satisfy the rest of the zero-major promises, before doing anything drastic.

**Comment by UziTech** [comment]
I think eslint covers this pretty well.
