### ISSUE TITLE
Prevent from parsing inside custom elements

### ISSUE THREAD

**Issue by intcreator** [markedjs/marked#1090]
## Expectation

If I have a custom element in my Markdown, the contents should not be parsed:

```
<demo-el>
    <template>
        <script>
            let death = 'backticks';
            console.log(`backticks are ${death}`;
        </script>
    </template>
</demo-el>
```

Should produce `backticks are backticks` in the console and my custom element rendered as normal in the Markdown.

## Result

The following code actually produces `<code>backticks are ${death}</code>` in the rendered Markdown and an error in the console (because it cannot recognize `<`).

## What was attempted

I tried to find which elements are considered block elements in Marked.js to prevent this from happening, but it was not clear how this was decided.

**Comment by Feder1co5oave** [comment]
I can see that this is annoying for you. The inside parsing of html elements was considered often a nice thing to have but it can mess up things.
We're definitely gonna revisit this once we get up to date with commonmark about html blocks.
Thanks for reporting!

#985

**Comment by intcreator** [comment]
It looks like it's a violation of [Example 156](http://spec.commonmark.org/0.28/#example-156) in the Commonmark spec.

What do you mean by everything being up to date?  How long do you think it will be?  Can I help?

**Comment by joshbruce** [comment]
@intcreator: My throwing copper on the "can I help?" - Yes. Absolutely. Always. There aren't a lot of us to go around who actually know marked well enough to contribute code (we're working on discussing how to get there in other issues); so, the more outside contributors who can fix issues with the core, the more the core team of committers, such as it is at the moment, can focus on making it easier to maintain and contribute to for others.

Please see updated [readme](https://github.com/markedjs/marked) and [contributing](https://github.com/markedjs/marked/blob/master/CONTRIBUTING.md) pages.

Let me know if there's something you think could be helpful in the docs.

**Comment by UziTech** [comment]
> How is this behavior decided?

You can read the spec [here](https://spec.commonmark.org/0.28/#html-block). marked doesn't fully comply with the spec yet, but that is where we are heading.

> Can I configure it?

You can [extend](https://marked.js.org/#/USING_PRO.md) the renderer or parser to change the behavior of marked.

**Comment by neilsustc** [comment]
Exactly the answer I need, thanks a lot!
