### ISSUE TITLE
Slack, Discord, other

### ISSUE THREAD

**Issue by joshbruce** [markedjs/marked#1099]
**Marked version:** 0.3.17

**Proposal type:** other (communication and collaboration)

## What pain point are you perceiving?

See [comment](https://github.com/markedjs/marked/issues/1093#issuecomment-369277667) from @intcreator for context.

> If you want a faster, more general team communication platform, you can start a Discord server. If you're not familiar with Discord, it's kind of like Slack except there are unlimited text messages for free (instead of 10k) and unlimited team voice calls.

## What solution are you suggesting?

I tend toward Slack. Not being too concerned about archived things. There are 7 practitioners in [8fold](https://8fold.pro) right now, and have never really needed the history or archives. I think for more static referential things, they should end up on GitHub somehow either as an Issue or PR.

These platforms we be more for rapid communication across all the contributors (anyone willing to register to the group in this case).

**Comment by UziTech** [comment]
Why not use [github discussions](https://github.com/blog/2471-introducing-team-discussions)

- They are free
- No need to sign up for something else
- They integrate with GitHub pretty well

**Comment by joshbruce** [comment]
@UziTech: Are they limited to the committers? 

I didn't have a chance to look into them in depth. Thinking of instances where contributors, who aren't part of the committers (@Feder1co5oave now, @intcreator, and @davisjam, for example) and just want to ask a quick question (that doesn't necessary need to go through the overhead of creating a GitHub issue).

**Comment by intcreator** [comment]
Maybe we can try out GitHub discussions to see what features they offer?

**Comment by UziTech** [comment]
@joshbruce Ya I think it would be limited to markedjs members

**Comment by joshbruce** [comment]
@UziTech: Thanks for the confirmation. Other question is, do we think we have the ability to keep up??

From a product perspective, I think it could go a long way to helping us hear more from users who are interested enough to at least sign up for the group. (That's been a serious pain point for me...how do I increase stakeholder reach out and feedback.)

Maybe something we could start, but not really advertise and go from there. For rationally selfish reasons I would go for Slack - my day job is there, 8fold is there, the design system groups I'm part of, and Vapor...it's nice having one app.

We could even do GitHub integrations. Maybe let some of us unsubscribe from email notifications - this was a pain point expressed by Feder1co5oave and confirmed by others re the updates I was making last week.

Also, hooked him up with the email rules I use to keep my sanity.

***

On the notification front, I don't know what email client you have, but here are my rules for dealing with all things GitHub (it has saved my skin! - and sanity) - subscriptions across the board actually (this is Mail for macOS):

1. I don't have email notifications turned on - I go to it when I want to, not when it gets all up in my face. See Randy Pausch on [Time Management](https://youtu.be/oTugjssqOT0). "Notifications are interruptions" [and I got stuff to do]. 😉 
2. Here's the rule (if all of the following are true):
  - If "from" contains "@github.com" (all the GitHub emails)
  - If "subject" contains "[account]/[repo]" (all the ones from that repo)
  - If "Message content" does NOT contain "@joshbruce" (not explicitly for me, woohoo!)
  - Then "Move message" to mailbox: "[repo specific mailbox]"
3. I have a day where I do most of my planning and whatnot per week, as part of that, I go through and catch up on all the conversations I might have missed that I may or may not want to comment on. See [The Seven Habits of Highly Effective People](https://www.amazon.com/Habits-Highly-Effective-People-Powerful/dp/0743269519) (specifically "sharpening the saw" - but it's a good read - at least I thought so), [Getting Things Done](https://www.amazon.com/Getting-Things-Done-Stress-Free-Productivity/dp/0143126563/ref=asap_bc?ie=UTF8), and [The Pomodoro Technique](https://francescocirillo.com/pages/pomodoro-technique) (I have the PDF for when this was still being market tested before it became a commercial product, if you would like).
