### ISSUE TITLE
Devel: Require updates to 'News' as part of PRs

### ISSUE THREAD

**Issue by davisjam** [markedjs/marked#1108]
**Proposal type:** project operations

## What pain point are you perceiving?

Hard to write changelogs for new releases.

## What solution are you suggesting?

Require PRs to update a "News" file with a changelog-friendly description of the change.
This is what cpython does.
Then generating a changelog is a copy/paste job or could be automated.

**Comment by davisjam** [comment]
@UziTech

**Comment by UziTech** [comment]
The only problem I see with making every PR add their own change to a file is whenever a PR is merged then all other unmerged PRs have a merge conflict.

I don't think the average person/dependent cares what changed and the people who do can easily [compare the commits](https://github.com/markedjs/marked/compare/0.3.15...v0.3.17) between releases

**Comment by joshbruce** [comment]
To be fair, I'm more interested in the PRs that have gone into `master` between releases. I might be able to do the language thing pretty quickly as long as I can see the PRs easily somewhere; so, now I need the education on how to get wherever you got that page from.

I'm not sure I agree that they don't care. We've had a couple of folks talk about semver not letting them know and, from a marketing perspective, it's more about bringing on new users.

**Comment by styfle** [comment]
Changes since our last release:
https://github.com/markedjs/marked/compare/v0.3.17...master

**Comment by joshbruce** [comment]
@styfle: Thanks. I think my ignorance is greater than that. lol 😂 How do I actually get to the point of seeing that page in GitHub? UI sequence?

**Comment by UziTech** [comment]
![image](https://user-images.githubusercontent.com/97994/36917936-d49b4b56-1e1d-11e8-85c6-f99c0baace21.png)

**Comment by davisjam** [comment]
> whenever a PR is merged then all other unmerged PRs have a merge conflict.

Sorry, put them in *distinct* news files. e.g. `2018-03-02-davisjam-PRX-ChangeLog.md`.

**Comment by UziTech** [comment]
https://github.com/motemen/git-pr-release

**Comment by styfle** [comment]
I don't really see the value in this since we are already maintaining the [release notes](https://github.com/markedjs/marked/releases) which can be fetched via GitHub API and any git user can [generate a changelog](https://github.com/markedjs/marked/issues/1108#issuecomment-370025973) from the tags.

Should we close this ticket?

**Comment by joshbruce** [comment]
Tend to agree. I remember some of the conversations that led to this suggestion, namely me trying to make the release notes. This might be something worth revisiting if we ever get to the point of Python and other similar projects doing the same. Until then, the issues template and updating release notes as we merge seems to be working well.
