### ISSUE TITLE
gfm-task-lists

### ISSUE THREAD

**Issue by leeoniya** [markedjs/marked#111]
any interest in supporting gfm-tasks?

https://github.com/blog/1375-task-lists-in-gfm-issues-pulls-comments

```
- [ ] a task list item
- [ ] list syntax required
- [ ] normal **formatting**, @mentions, #1234 refs
- [x] incomplete
- [ ] completed
```
- [ ] a task list item
- [ ] list syntax required
- [ ] normal **formatting**, @mentions, #1234 refs
- [ ] incomplete
- [x] completed

**Comment by jasondavis** [comment]
Is this featured added now?
