### ISSUE TITLE
Minify and commit as part of PR merge to master

### ISSUE THREAD

**Issue by joshbruce** [markedjs/marked#1119]
**Marked version:** 0.3.17

**Proposal type:** project operations

## What pain point are you perceiving?

No real point, just an interesting idea to ponder.

## What solution are you suggesting?

- [ ] We could also do a minify stage that would minify and commit after every master branch commit
- [ ] Update the RELEASING docs.

**Comment by styfle** [comment]
I’m not convinced this is necessary. 
Although we say master should always be releaseae, that’s doesnt mean it is always contains a release. The tags are where you can find the release.

**Comment by joshbruce** [comment]
Having said that, I don't think we're going for a full release here. More like making sure `min` is always up to date, maybe??

When we merge into `master` - and there's a code change - and someone uses master directly...not the NPM package or a release build...would they have to minify themselves?

**Comment by UziTech** [comment]
Ya the idea would be to just automatically commit and build `marked.min.js` so it would always be synced with `marked.js`.

There would still have to be a manual release

**Comment by joshbruce** [comment]
Believe this is covered by the `preversion` script.
