### ISSUE TITLE
Clean up backlog

### ISSUE THREAD

**Issue by joshbruce** [markedjs/marked#1120]
**Marked version:** 0.3.17

**Proposal type:** project operations

## What pain point are you perceiving?

Quick notes to myself and comms to the team while I'm here, sorry if it seems terse or curt.

Backlog of issues and PRs not organized. Causes pain to all involved.

## What solution are you suggesting?

- [x] The consolidation issues should probably be labeled as epics and assigned to the 0.x milestone (not sure what 
- [ ] The vision alignment issues should be left alone for now, I think
- [ ] Close out the consolidation issue in favor of the defibrillator challenge
- [ ] ...

**Comment by styfle** [comment]
@joshbruce Anything else we need for this one? It seems like the backlog is pretty consolidated now.

**Comment by joshbruce** [comment]
@styfle: Would like to do a pass again to deal with the consolidation epics. One of the reasons that made sense back then was because we didn't have a spec-based testing harness in place. Now that we do I believe it's safe to replace those and the related issues with the defibrillator challenge...also wanted to give users a chance to respond to the mass closing we did not too long ago.

**Comment by joshbruce** [comment]
It's getting close. Definitely got sidetracked with all the testing.

**Comment by styfle** [comment]
How's the backlog looking now?

**Comment by joshbruce** [comment]
@styfle: Would like to make some time to kinda go through some of the issues as a double check against consolidation and closure. Thanks for doing a lot of that maintenance as well!

**Comment by styfle** [comment]
@joshbruce I have been going through the backlog and I tagged several bugs that I was able to reproduce on 0.5.0 so that they get noticed. I also commented on the ones I think should be closed (looks like you already closed them now).

What do you mean by checking against consolidation and closure?

**Comment by joshbruce** [comment]
@styfle: Honestly? It's been a while since I looked through the issues and want to reacquaint myself and make sure I didn't miss something before closing this out. I should be able to make some time this weekend, I think. I'm also traveling next week to talk at a conference (very nervous); seems like all the pots are coming together roughly at the same time. :)
