### ISSUE TITLE
[Architecture]: Capture high-level as-is class diagram 

### ISSUE THREAD

**Issue by joshbruce** [markedjs/marked#1130]
**Marked version:** 0.3.17

**Markdown flavor:** n/a

**Proposal type:** other

## What pain point are you perceiving?

1. The code is difficult to read per #1102.
2. #1114 comment from @UziTech recommends "best way" (sorry, knee-jerk reaction whenever someone says "best way" 😆) related to a possible to-be architecture.
3. Related to vision alignment: #965 
3. And more...wasn't planning to spend this long writing this... 😝 

#1089, #1096, #1097

## What solution are you suggesting?

Capture at least a basic (no members or functions necessary) [class diagram](https://en.wikipedia.org/wiki/Class_diagram) (like??) model illustrating Marked's current architecture.

Think @intcreator should get first refusal since he seems most passionate about needing an architecture (and architect) to be able to get up to speed in understanding the code easier. I know you said you've only had a couple year's experience with JS but that'll be fine, that's why we have review.

Let us know?? (No harm, no foul.)

**Comment by joshbruce** [comment]
Huh? Fascinating.

You can tag two projects now. 

Projects is a new-ish feature in GitHub...not sure it's always been able to do that. 

Don't think you can do two milestones though.

**Comment by UziTech** [comment]
If you are looking for marked written in TypeScript you can look at the fork [marked-ts](https://github.com/KostyaTretyak/marked-ts)

**Comment by snowyu** [comment]
I have read it just now, but it is not pretty code. The `RegExp` passed everywhere.

**Comment by snowyu** [comment]
The best way should be inherited from a common tokenizer/Lexer, such as [Moo Tokenizer Generator](https://github.com/no-context/moo) or [PEG.js](https://pegjs.org/).
