### ISSUE TITLE
Create and discuss community guidelines and protocols

### ISSUE THREAD

**Issue by joshbruce** [markedjs/marked#1131]
**Marked version:** 0.3.17

**Markdown flavor:** n/a

**Proposal type:** other

## What pain point are you perceiving?

Long story short: https://github.com/markedjs/marked/pull/1125#issuecomment-370278961

And a couple of slips, including me trying to meet my commitment to the team this morning of the equivalent of 1 test example from CommonMark a day via #1124. Accidentally submitted a PR from my local master to the upstream master...that I then had to close (literally said, "Whoops, I need to slow down")...I mean mistakes happen (::cough:: 260+ ?? ::cough::) but, yeah, we're not ready for people to help without stepping all over everybody.

[edit] And a lot more examples in various comments, issues, and interactions.

## What solution are you suggesting?

- [ ] Let's slow it way day ??
- [ ] Group huddle on all the community documentation ever ??

It's literally my first rodeo going this far and starting from where we were...my only question is do we want to discuss here...or should we pause on all the GitHub activity and maybe have a video chat, conference call, private session in the org team space??

[edit] This is my reference as to why something approaching face-to-face:

[The Manifesto for Agile Software Development](http://agilemanifesto.org/principles.html)

> The most efficient and effective method of 
> conveying information to and within a development 
> team is face-to-face conversation.

**Comment by joshbruce** [comment]
Tagging @markedjs/marked

**Comment by joshbruce** [comment]
ps. @davisjam I finally put 12 and pi together...you and I might actually work together in that way that's only possible in the DMV.

**Comment by joshbruce** [comment]
pps. @styfle correct me if I'm wrong, but I believe there's even a way to freeze a repo for a while...?? Thought I read that somewhere.

**Comment by davisjam** [comment]
> I finally put 12 and pi together...you and I might actually work together in that way only possible in the DMV.

Not sure what you mean. The only way I know to work in the DMV is slowly?

**Comment by joshbruce** [comment]
@davisjam: rofl - Indeed. I’m in VA as well. Contract I’m on also has some folks from IBM on it. Thought I saw that on your profile when I went to find your email addy.

**Comment by davisjam** [comment]
Ahh. Small world.

**Comment by joshbruce** [comment]
Closing as achieved. Believe we've been operating more cohesively as a team and able to easily integrate contributors as well. Well done.

Tagging @davisjam, @styfle, and @UziTech to make it explicitly known.
