### ISSUE TITLE
UTF-8-BOM not supported

### ISSUE THREAD

**Issue by shinpou** [markedjs/marked#1133]
**Marked version:**
0.3.17
**Markdown flavor:**
Ran marked with default settings: 

_marked README.md -o test.html_

## What pain point are you perceiving?

UTF-8-BOM encoding will break markdown on first line but works otherwise normally - if the file begins with a title for example, this will not parse.

Unsure if this counts as a defect, just letting you know, maybe add a note to documentation?

**Comment by UziTech** [comment]
Thanks for reporting. At the moment we are working to get marked up to date since it has been dormant for a while, so it might be a while before we can address this.

@joshbruce what milestone should this go under?

**Comment by joshbruce** [comment]
@UziTech and @shinpou: I agree with your assessment re taking a while. Might have overstretched myself a bit, to be honest. I'm still in assessment mode at the moment. As it stands, this is something of a side project for me to help increase my knowledge and understanding...I see the various potentials and will do what I can to ensure all of them as future possibilities moving forward.

As I have said, I've never made it this far and it was a pretty high-jump for me...I mean, I'm still figuring out how GitHub organizations work. Appreciate the patience.

**Comment by joshbruce** [comment]
Closing as part of future as this support is not specific compared to a specification.
