### ISSUE TITLE
Update refined GitHub README with Safari extension

### ISSUE THREAD

**Issue by joshbruce** [markedjs/marked#1137]
**Marked version:** 0.3.17

**Markdown flavor:** n/a

**Proposal type:** other

## What pain point are you perceiving?

Was recommended I use [refined GitHub](https://github.com/sindresorhus/refined-github), which is a browser extension. I use Safari.

Safari extension not listed in refined-github README. Didn't chase the squirrel beyond [issue 14](https://github.com/sindresorhus/refined-github/issues/14), which states a link to the extension was placed in the README.
 
## What solution are you suggesting?

- [ ] Clone refined GitHub
- [ ] Update README with link to Safari extension
- [ ] Consider the PR describing following content guidelines...this is where I dropped off because I was in the midst of eating and thought this was going to be simple.

**Comment by UziTech** [comment]
Why is this marked issue? Shouldn't this be a refined GitHub issue

**Comment by joshbruce** [comment]
@UziTech: Fair question and point. Was thinking it might be nice of us to do at some point. Probably could have been assigned to me. I blame feeling under the weather and trying a bit too hard to be Helpy McHelperson. ;)
