### ISSUE TITLE
[DevOps]: Node Security

### ISSUE THREAD

**Issue by joshbruce** [markedjs/marked#1158]
**Marked version:** 0.3.18

**Markdown flavor:** n/a

**Proposal type:** other

## What pain point are you perceiving?

None. More of a curiosity.

## What solution are you suggesting?

Was making the rounds to those projects who became dependent on `8fold-marked` to make sure they switched back to latest. Noticed this in their pipeline:

<img width="749" alt="screen shot 2018-03-23 at 11 58 17 am" src="https://user-images.githubusercontent.com/15252830/37839869-f87b899e-2e91-11e8-9ab3-0bd30621888b.png">

Node security... @UziTech what is it, should we have it? (Believe there was a REGEX tool mentioned elsewhere at some point.)

**Comment by UziTech** [comment]
That is [NSP](https://nodesecurity.io/). It is free for OSPs

There is a free [Snyk App](https://github.com/marketplace/snyk) that might be helpful as well.

![image](https://user-images.githubusercontent.com/97994/37843948-54ecaf3a-2e94-11e8-9b17-464fe2b488e1.png)

It would also be nice to enable [Appveyor](https://www.appveyor.com/) for testing on windows.

**Comment by joshbruce** [comment]
Leave it to you, brother. Definitely think Snyk should be a thing since they're the ones nice enough to talk to us. :)

**Comment by styfle** [comment]
I also think we should add the policy to prevent merging PRs without having all the checks pass: 

- CI
- security check
- 2+ approvals

**Comment by davisjam** [comment]
+1

**Comment by joshbruce** [comment]
I'm okay with the 2+ approvals. If this can be done through the GitHub review process, please post a link of a how-to, if you have one handy.

**Comment by styfle** [comment]
Visit "Setting" > "Branches" https://github.com/markedjs/marked/settings/branches

Click "Edit" next to `master`

Then check the boxes for the policies

![image](https://user-images.githubusercontent.com/229881/38878798-cf009c60-422f-11e8-97f6-5d3260ee042a.png)

**Comment by styfle** [comment]
I just enabled that, however I am unable to install Snyk.
I think only @joshbruce can do it: https://github.com/marketplace/snyk

**Comment by joshbruce** [comment]
@UziTech and @styfle: In theory, we don't need this but might good for us to have awareness of just in case for CI: https://snyk.io/docs/using-snyk?utm_campaign=welcome_email&utm_campaign=GitHub%20Onboarding&utm_medium=email&utm_medium=email&utm_source=DocsCommandLine&utm_source=hs_automation&utm_content=61782021&_hsenc=p2ANqtz-9XvrdTanuF8D9kJMUpg6eZIkB6GmW7zFpt02S424C2HJb403WhfIn0PI6e3FpaEN1HrnE1YE86p9-zAqqWsrCa21NpVQ&_hsmi=61782021

**Comment by styfle** [comment]
So it doesnt check every PR?

**Comment by joshbruce** [comment]
If "it" in this context is Snyk, it should be every PR - but they have a CLI to extend it would seem. See #1229

**Comment by styfle** [comment]
It looks like npm@6.0.0 will have this security audit built in.

See the [blog post](https://medium.com/npm-inc/announcing-npm-6-5d0b1799a905#5ffe) for details.

**Comment by UziTech** [comment]
should we add `npm audit` to travis after lint? (once the registry actually allows it)

**Comment by DanielRuf** [comment]
Currently the security check for RegEx fails due to some violations.

**Comment by davisjam** [comment]
@DanielRuf Some fixes in #1226.
