### ISSUE TITLE
Class attribute

### ISSUE THREAD

**Issue by FredericLatour** [markedjs/marked#116]
Is it possible to specify a class attribute value for link? (ie: `<a href="#" class="prettyPhoto">whatever</a>`)

**Comment by julmot** [comment]
@chjj There should be an option available to set custom classes on some elements.

**Comment by developerdizzle** [comment]
In case this helps anyone, for my very specific use-case, I was able to do this:

```js
marked.use({
  renderer: {
    link({ href, text }) {
      return `<a class="link" href="${href}">${text}</a>`;
    },
  },
});
```
