### ISSUE TITLE
Specific character combination not rendered correctly

### ISSUE THREAD

**Issue by daneah** [markedjs/marked#1178]
**Marked version:** 0.3.19

**Markdown flavor:** n/a

## Expectation

`marked('_in_')` would be rendered as `<p><em>in</em></p>`.

## Result

`marked('_in_')` is rendered as `<p>_in_</p>`.

## What was attempted

`marked('_in_')`

Other combinations of `marked('_some string_')` appear to work as expected (certainly didn't run an exhaustive check).

**Comment by UziTech** [comment]
looks like it has to do with the number of characters in between the underscores.

I'm tagging in @Feder1co5oave. Is there any reason <= 2 characters between underscores is not rendered inside `<em>`?

**Comment by daneah** [comment]
Oh jeez, sorry I missed that obvious generalization of the nature of the bug. Just tried out other one/two character combos and I concur that's the issue. Thanks @UziTech !
