### ISSUE TITLE
Breaking changes between v0.3.6 and v0.3.19

### ISSUE THREAD

**Issue by vsemozhetbyt** [markedjs/marked#1179]
Node.js uses marked `v0.3.6` in its [doc tools](https://github.com/nodejs/node/tree/master/tools/doc) for building [docs md sources](https://github.com/nodejs/node/tree/master/doc/api).

I've tried to update marked up to `v0.3.19` and compare results for the same sources set from the master branch. There are many diffs in them. I cannot enumerate and analyze all of them, but there are some I can mention by the first glance.

1. Parsing code inside links with link references:

    **Source**:
    ```md
    [`[[Prototype]]`][prototype-spec]
    ...
    [prototype-spec]: https://tc39.github.io/ecma262/#sec-ordinary-object-internal-methods-and-internal-slots
    ```
    **HTML**:
    ```diff
    -<a href="https://tc39.github.io/ecma262/#sec-ordinary-object-internal-methods-and-internal-slots"><code>[[Prototype]]</code></a>
    +[<code>[[Prototype]]</code>]<a href="https://tc39.github.io/ecma262/#sec-ordinary-object-internal-methods-and-internal-slots">prototype-spec</a>
    ```

2. Node.js uses [doc linking with `@include` directives](https://raw.githubusercontent.com/nodejs/node/master/doc/api/all.md) combining all the docs in `all.html` file. In this file, all the Node.js doc file names are deleted from the relative link URLs, so that cross-document links become intra-document links. In v0.3.19 this deleting is broken:

    **Source**:
    ```md
    [`fs.open()`][]
    ...
    [`fs.open()`]: fs.html#fs_fs_open_path_flags_mode_callback
    ```
    **HTML**:
    ```diff
    -<a href="#fs_fs_open_path_flags_mode_callback"><code>fs.open()</code></a>
    +<a href="fs.html#fs_fs_open_path_flags_mode_callback"><code>fs.open()</code></a>
    ```

[Here is a zip](https://vsemozhetbyt.github.io/test/nodejs-doc-marked-v0.3.06-v0.3.19.zip) with two folders with results if somebody wants to dig into all the diffs.

Sorry if this is not a relevant information concerning zero prerelease.

**Comment by joshbruce** [comment]
@vsemozhetbyt: Gonna go ahead and close this per #1106 and the zero major. We're definitely trying to fix more than we break in the long run. Thank you for the contributions you made along with point this one out. We're getting closer to having a better idea of exactly how of the mark marked is compared to the CommonMark spec (see #1160); so, hopefully a truly stable release is somewhere in the near future (compared to there just not be a release for a while).
