### ISSUE TITLE
Disable header IDs

### ISSUE THREAD

**Issue by joshbruce** [markedjs/marked#1186]
**Marked version:** 0.3.19

**Markdown flavor:** n/a

**Proposal type:** new feature

## What pain point are you perceiving?

Marked always adds an `id` attribute to headers. This feature does not appear to be optional. The `id` being in the header is not part of the CommonMark spec.

## What solution are you suggesting?

Make the generation of `id` in headers optional via setting options.

**Comment by joshbruce** [comment]
See #1190

**Comment by canyoudev** [comment]
@joshbruce I am sorry, but is it implemented or not? I see it merged but I can't find info how to use it. Where is docs?

**Comment by Martii** [comment]
@canyoudev 
Currently at https://github.com/markedjs/marked/blob/master/docs/USING_ADVANCED.md#options

**Comment by joshbruce** [comment]
@canyoudev: It’s available on master and will be published to NPM with the 0.4.0 release. See reference in docs supplied by @martii.
