### ISSUE TITLE
Heading formatting is lost when wrapped in a block-level element

### ISSUE THREAD

**Issue by jackmoore** [markedjs/marked#1187]
**Marked version:** 0.3.19

**Markdown flavor:** default

Using in-browser (Chrome v65)

Example Input:
```
<div>
### Hi
</div>
```

Output:
```
<div>
### Hi
</div>
```

Expected:
```
<div>
<h1>Hi</h1>
</div>
```

**Comment by UziTech** [comment]
That seems to be intended behavior.

Here is [marked](https://marked.js.org/demo/?text=%3Cdiv%3E%0A%23%23%23%20Hi%0A%3C%2Fdiv%3E) and [commonmark](https://spec.commonmark.org/dingus/?text=%3Cdiv%3E%0A%23%23%23%20Hi%0A%3C%2Fdiv%3E) examples

In github it displays:

<div>
### Hi
</div>

**Comment by jackmoore** [comment]
Sure enough, my apologies.
