### ISSUE TITLE
don't work for me 

### ISSUE THREAD

**Issue by Hideer** [markedjs/marked#1189]
**Marked version:**
```
0.3.19
```

when I use zhe marked() method, it's don't work and tips for me :Error: marked(): input parameter is undefined or null

**Comment by joshbruce** [comment]
@Hideer: Could you use the issue template and put the code you used.

## Expectation

```
What you were trying to get.
```

## Result

```
What you got
```

## What was attempted

```
What was sent to marked in the code.
```

**Comment by Hideer** [comment]
## Expectation
```
I want to convert marked grammar into HTML labels.
```
## Result
```
it don't work for me 
tips:Error: marked(): input parameter is undefined or null
```

## What was attempted
```
you can see code：

import marked from 'marked';
 compiledMarkdown(value) {
            return marked(value)
            // return marked("# Marked in the browser\n\nRendered by **marked**.");
        },
```

@joshbruce

**Comment by joshbruce** [comment]
What is `value` in this case? Also, not sure about the import statement. Usually that error only happens if `value` is null.

If you take a look at the tests you can see the way Marked is designed to work.

```js
var marked = require('../../marked.min.js');

it('should run the test', function () {
  expect(marked('Hello World!')).toBe('<p>Hello World!</p>\n');
});
```

**Comment by UziTech** [comment]
@Hideer it looks like somewhere in your code you are calling

```js
compiledMarkdown(null);
```

**Comment by davisjam** [comment]
@Hideer Is this resolved or do you still have questions?

**Comment by joshbruce** [comment]
Closing. @Hideer, please reopen if you find the responses to be unsatisfactory. Thank you.
