### ISSUE TITLE
the option : headerIds is not valid.

### ISSUE THREAD

**Issue by li-xiaojun** [markedjs/marked#1208]
**markd: 0.3.19:**
when i set headerIds: false，but it still generated the ids for per element.

**Comment by UziTech** [comment]
I don't believe the headerIds option was added to a release yet

/cc @joshbruce

**Comment by joshbruce** [comment]
Believe @li-xiaojun is referring to the feature that is already in place. The only change we made was to make it so you could disable it (not part of a release yet). The default behavior is to add header ids. We've always had issues with UTF-8 characters; see #981.

**Comment by styfle** [comment]
Hi @li-xiaojun sorry for the confusion 😄 

Our docs are based off of `master` which includes this new `headerIds` option however it is not released yet. Our next release, 0.4.0 will include it (as the other team members mentioned above).

If you're feeling adventurous, you could try out the code in the master branch before the release.

We'll close this issue when 0.4.0 gets released. Thanks! 👍
