### ISSUE TITLE
Support multibyte character in heading id

### ISSUE THREAD

**Issue by kenchan0130** [markedjs/marked#1209]
**Marked version:**
0.3.18

**Markdown flavor:**
n/a

## Markdown

```md
# これは markdown です
```

## Expectation

```html
<h1 id="これは-markdown-です">これは markdown です</h1>
```

or

```html
<h1 id="これはmarkdownです">これは markdown です</h1>
```

## Result

```html
<h1 id="-markdown-">これは markdown です</h1>
```

## Cause
It seems that multibyte characters have been converted to hyphens in the processing of [this part](https://github.com/markedjs/marked/blob/master/test/index.js#L404).

**Comment by UziTech** [comment]
A PR would be welcome

**Comment by UziTech** [comment]
according to W3C id [spec](https://www.w3.org/TR/html5/dom.html#element-attrdef-global-id):

> The id attribute specifies its element’s unique identifier (ID).
>
> There are no other restrictions on what form an ID can take; in particular, IDs can consist of just digits, start with a digit, start with an underscore, consist of just punctuation, etc.

but this will be a breaking change.

/cc @Feder1co5oave

**Comment by UziTech** [comment]
#981 

I'm going to close this as duplicate. There are many different takes on generating header ids. Some people want hyphens combined when there are multiple in a row, some people don't. Some people want hyphens trimmed when they are at the beginning or end, some people don't.

Header ids are something we are looking at deprecating in the future so people can use there own algorithm to generate them.
