### ISSUE TITLE
GitHub Flavored Markdown Compliance

### ISSUE THREAD

**Issue by joshbruce** [markedjs/marked#1211]
**Marked version:** 0.3.19

**Markdown flavor:** GitHub Flavored Markdown (GFM)

**Proposal type:** other

## What pain point are you perceiving?

See #1202 only focused on the GFM.

## What solution are you suggesting?

PR #1210 looks to run Marked against the GFM extension test cases: no file generated

So far the results show that we are roughly **56% spec-compliant**. 

The spec is divided into sections and each section has a number of test cases. (Counts may be off and are meant to represent estimate percent compliance with each section.)

|Section                     |Count    |Percent   |
|:---------------------------|:-------:|---------:|
|Tables                        |3 of 8  |38%       |
|Task list items             |0 of 2 |0%       |
|Strikethrough                |1 of 3 |33%       |
|Autolinks             |10 of 11 |91%       |
|Disallowed Raw HTML        |0 of 1 |0%       |

**Comment by UziTech** [comment]
My vote is for spec compliance `#2`

Anyone who needs the alignment in css can do:

```js
let html = marked(md, {gfm: true});
html = html.replace(/<(td|th) align="/g, '<$1 style="text-align:');
```

/cc @joshbruce @styfle @davisjam

**Comment by joshbruce** [comment]
Agree with @UziTech. Think the style use was an override of spec-compliance. 

So, abandon decision made in #221...didn't even know that was a decision that was made.

@tomtheisen: To your other question, as a publisher I tend to set the priority (with ample feedback from everyone esle). We've decided, for now, to prioritize security then spec-compliance; so, chances are if there's a debate that can be argued from the spec, the spec will win.

**Comment by joshbruce** [comment]
ps. Thanks to @tomtheisen, thanks for the continued contributions.

**Comment by styfle** [comment]
I agree with GFM spec compliance 👍 

As long as we release this as a breaking change so we make users aware 🥂

**Comment by tomtheisen** [comment]
I created a [PR for GFM table compliance](https://github.com/markedjs/marked/pull/1245).  I don't really know what I'm doing in marked, so feedback is welcome.
