### ISSUE TITLE
Inconsistent application of tildes + great combo badge

### ISSUE THREAD

**Issue by joshbruce** [markedjs/marked#1230]
**Marked version:** 0.3.19

**Markdown flavor:** n/a

**Proposal type:** other

## What pain point are you perceiving?

Working through #1229 and saw something interesting.

## What solution are you suggesting?

CommonMark: The examples from the fenced code blocks section using tildes (~) should pass...89, for example.

GFM: All three of the examples in the strikethrough section should pass...at present, only two do.

`/test/new/gfm_del`: This is a test in the current test bed. It passes. Therefore, some of the logic, at least for strikethrough is in place.

That's what makes this a "great combo" and badge worthy. Similar patterns, resulting in different output, across multiple specifications, and, in theory, there's already groundwork in place. To earn the badge submit a PR that allows us to:

1. Deprecate `/test/new/gfm_del`.
2. Pass all failing tests in GFM.
3. Pass the failing tests in CommonMark that use the tilde.

Just like most fighting games, there will probably be a multiplier depending on what all is hit.

See also #1216

**Comment by styfle** [comment]
@joshbruce Should the badge be awarded to 3 people? There were 3 PRs to compelete this so it’s not really a “combo” by one person but a combo by many people.

**Comment by joshbruce** [comment]
@styfle Sorry, my email rules were not setup in their entirety and I'm catching up. I think the badge can go to all three. Glad to see progress was made!

Many thanks to all who helped.
