### ISSUE TITLE
Cannot read property 'tokenizePlaceholders' of undefined

### ISSUE THREAD

**Issue by mheiland** [markedjs/marked#1234]
**Marked version:**
0.3.0

**Markdown flavor:**
n/a, i'm using reDoc with bundles marked to create MD/HTML pages. I'm using NPM 5.6.0 with Node 8.11.1

## What pain point are you perceiving?
Building markdown fails reproducibly when transforming a specific OpenAPI spec to HTML with ReDoc. ReDoc potentially creates Markdown using markedjs in between.

## Call stack & console log
I'm getting the following stderr output when running ReDoc against a specifc JSON input file:

```
$ wget https://documentation.open-xchange.com/components/facade/1.0.0/openapi.json
$ redoc-cli bundle openapi.json -o my-redoc.html --title hello world
[ReDoc Compatibility mode]: Converting OpenAPI 2.0 to OpenAPI 3.0
Prerendering docs
Cannot read property 'tokenizePlaceholders' of undefined
Please report this to https://github.com/markedjs/marked.
```

**Comment by joshbruce** [comment]
Have tried:

1. Upgrading marked - we are now on 0.3.19 - but I'm not sure you have the authority to do so.
2. Contacting ReDoc re the issue? `tokenizePlaceholders` is not a marked concept to the best of my knowledge.

**Comment by mheiland** [comment]
Thanks for the response. I checked again and noticed that indeed markedjs 0.3.19 is used as a dependency. I'll get in touch with ReDoc next.
