### ISSUE TITLE
GFM doesn't handle escaped pipes in code blocks

### ISSUE THREAD

**Issue by tomtheisen** [markedjs/marked#1237]
**Marked version:** 0.3.19

**Markdown flavor:** GitHub Flavored Markdown

## Expectation

I expect that pipes will be parsed in accordance with the GFM specification, such as [example 193](https://github.github.com/gfm/#example-193).  It's labeled "Include a pipe in a cell’s content by escaping it, including inside other inline spans:".  The example indicates that you can include a pipe in a code block in a table by escaping it with a backslash.

## Result

```
| f\|oo  |
| ------ |
| b `\|` az |
| b **\|** im |
```

When rendering this document with GFM turned on, the pipes in the code blocks actually create new table cells.

**Marked Demo:** https://codepen.io/recursive/pen/yjeBVW - I didn't use marked.js.org because I couldn't see how to turn on GFM from there.

## What was attempted

Here's the code I'm using.

```
let m = "| f\|oo  |\n| ------ |\n| b `\|` az |\n| b **\|** im | \n";
marked.setOptions({gfm: true});
let h = marked(m);
document.getElementById("out").innerHTML = h;
```

**Comment by joshbruce** [comment]
@tomtheisen: Thanks for submitting and including an example from the spec.

Confirmed.

See 'GFM 0.28 Tables' test suite https://github.com/markedjs/marked/blob/master/test/specs/gfm/gfm-spec.js

Note that 193 is a known failure. The most timely solution would be to submit a PR, if you are able.

**Comment by tomtheisen** [comment]
@joshbruce: PR is [here](https://github.com/markedjs/marked/pull/1239)
