### ISSUE TITLE
Error in render function: "TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by ruke318** [markedjs/marked#1238]
Error in render function: "TypeError: Cannot read property 'replace' of undefined

**Comment by UziTech** [comment]
Need more info. Can you tell us what code you used when you got that error?

**Comment by ruke318** [comment]
1. import the marked
```code
import marked from 'marked'
```
2. use it in methods

```javascript
  methods: {
    marked,
  }
```

3. use in html

```html
<mdView :value="marked(xss(item.content))"></mdView>
```

I don't think it's a problem with my use, but the above error

**Comment by ruke318** [comment]
![image](https://user-images.githubusercontent.com/23520969/39227057-1399bfbe-4889-11e8-8828-aed3771f8873.png)
this is a picture with this error

**Comment by ruke318** [comment]
I use a function to prevent xss attacks

**Comment by UziTech** [comment]
The `t.lex` function that is referred to in the error stack trace is marked's `Lexer.lex` function:

https://github.com/markedjs/marked/blob/03876239f5910f4914eeca8164893114bb8a3d05/lib/marked.js#L172-L180

The error is stating that `src` in this function is `undefined`.

My guess is that your `xss` function is not returning a string or vue is trying to optimize marked in a way that makes it fail. Try adding a break point at `marked.js:138` and see what the value of `src` is.

**Comment by ruke318** [comment]
The problem has been solved because of xss error, thank you !
