### ISSUE TITLE
Indented tables are ignored

### ISSUE THREAD

**Issue by wpomier** [markedjs/marked#1246]
**Marked version:** 0.3.19
**Markdown flavor:** GitHub Flavored Markdown
Github commit: [b78deebf](https://github.com/markedjs/marked/commit/b78deebfcf4420427832acd749e8ebecf67c8778)

## Issue Description
When the table is indented (e.g. inside an unordered list), it's ignored.

The following markdown text doesn't work:

```
 * Marked doesn't work with indented tables like this:

  | column1 | column2 |
  |---|---|
  | value1 | value2 |
  | value3 | value4 |
```
See it in the [Marked Demo page](https://marked.js.org/demo/?text=*%20Marked%20doesn%27t%20work%20with%20indented%20tables%20like%20this%3A%0A%0A%20%20%7C%20column1%20%7C%20column2%20%7C%0A%20%20%7C---%7C---%7C%0A%20%20%7C%20value1%20%7C%20value2%20%7C%0A%20%20%7C%20value3%20%7C%20value4%20%7C%0A%0A)

## Result

It should be rendered to:

* Marked doesn't work with indented tables like this:

  | column1 | column2 |
  |---|---|
  | value1 | value2 |
  | value3 | value4 |

## What was attempted
Basic usage.
```
var html = marked(example);
```

**Comment by wpomier** [comment]
After a little of debug, I found [the line](https://github.com/markedjs/marked/blob/37c0324e1d3c37d76f4ab1d8cd6ada1607fa85f0/lib/marked.js#L416) where the table is ignored:
```
    if (top && (cap = this.rules.table.exec(src))) {
```
As the table is nested in the list item, `top === false`, so the table syntax is not considered a table anymore.
In GFM a table can be defined in a non-top level (as demonstrated in my example), so... I think this can be a bug).

**Comment by joshbruce** [comment]
Given this is not an example called out in a spec and can have an issue associated with it I recommend using `marked.json` found here: https://github.com/8fold/marked/blob/1f98424064ee27b59d616e9a1ce707658a06ce79/test/specs/marked/marked.json

That's a broader PR and is only meant to show the test setup. The big thing is referencing the issue number. Don't worry about example numbers, I'll fix mine if necessary.

**Comment by joshbruce** [comment]
ps. `marked-spec.js` and `marked.json` exist in master now.

**Comment by LitileXueZha** [comment]
Same problem, `table` is rendered to `p`.Is there any solution?

**Comment by styfle** [comment]
Hello LittleCoder, would you like to submit a PR to fix this (along with a test)?
