### ISSUE TITLE
Inline code inside of table not detected

### ISSUE THREAD

**Issue by mjbvz** [markedjs/marked#1257]
**Marked version:** 0.3.19, also test on masker

**Markdown flavor:** GitHub Flavored Markdown

 

## Expectation

For the markdown:
```md
| Description |
| ------ |
| `a | b` |
```

Expected a one column table with a cell containing inline code `a | b`

## Result
```
<table>
<thead>
<tr>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr>
<td>`a</td>
<td>b`</td>
</tr>
</tbody>
</table>
```

**Comment by UziTech** [comment]
[demo](https://marked.js.org/demo/?text=%7C%20Description%20%7C%0A%7C%20------%20%7C%0A%7C%20%60a%20%7C%20b%60%20%7C)

**Comment by tomtheisen** [comment]
The second column should be removed.  see https://github.github.com/gfm/#example-197

Also, I think this is already fixed in be922cecdd825350421be969777f7052c4cbc9e9

**Comment by mjbvz** [comment]
Yes 0.4.0 now drops the second column which matches what github does. Markdown-it still renders this as:

```
<table>
<thead>
<tr>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr>
<td><code>a | b</code></td>
</tr>
</tbody>
</table>
```

but based on the [GFM spec](https://github.github.com/gfm/#example-193) the current marked behavior seems correct

**Comment by UziTech** [comment]
in order to achieve the expected result you would need to escape the pipe in code:
```
| Description |
| ------ |
| `a \| b` |
```


[demo](https://marked.js.org/demo/?text=%7C%20Description%20%7C%0A%7C%20------%20%7C%0A%7C%20%60a%20%5C%7C%20b%60%20%7C)
