### ISSUE TITLE
Backslash in GFM table doesn't escape pipes

### ISSUE THREAD

**Issue by robcresswell** [markedjs/marked#1259]
**Marked version:** 0.3.19

**Markdown flavor:** GitHub Flavored Markdown (`gfm: true, tables: true`)

## What pain point are you perceiving?

Using pipe characters within GFM Tables should be possible by escaping them first: `\|`. However, with marked, this also renders the backslash

## What solution are you suggesting?

Implement escaping within GFM Tables.

**Comment by tomtheisen** [comment]
This is fixed in master, but not released yet.

https://github.com/markedjs/marked/issues/1237

**Comment by robcresswell** [comment]
@tomtheisen Ah got it, thanks. Sorry for the duplicate.

**Comment by tomtheisen** [comment]
No problem.  I posted that issue, and I think that was a duplicate as well.
