### ISSUE TITLE
Question: Custom rules

### ISSUE THREAD

**Issue by BenjaminHoegh** [markedjs/marked#1261]
### Short version
How to add new rules in the marked.js file? I try to add rules to lets marked leave the text as it is when its surrounded by `$$`

Example:
```
$$
\begin{matrix}
    a & b \\
    c & d
\end{matrix}
$$
```

---

### Long version

I working on intergrade support for [KaTeX][1], it almost works without any special coding as default.
all [KaTeX][1] code are surrounded by `$$` 

When working with inline [KaTeX][1] code I would look like `$$c = \pm\sqrt{a^2 + b^2}$$` no problem here, [KaTeX][1] and Marked work as it should.

When working with multiple lines you need to tell it by using a "line separator" there look like this `\\` and here we get a problem. Marked as default use `\` to escape characters and here I try to make a rule in Marked to don't escape text between two `$$` But how to do that? can't find any documentation about how the code works.

A second problem is that Marked surround KaTeX with `<p>` tags, this is okay when it comes to inline KaTeX but when using block(multiple lines) [KaTeX][1] it needs to leave it alone as it is.

I do already have a regex there can detect the two types of [KaTeX][1] code

##### Example of inline KaTeX:

`This is some inline math $$E=mc^2$$ and has no idea what it means`

##### Example of block KaTeX:
```
$$
\begin{matrix}
    a & b \\
    c & d
\end{matrix}
$$
```

Thanks 👍 

[1]: https://khan.github.io/KaTeX/

**Comment by jfcere** [comment]
Hi @BenjaminHoegh, have you ever find a way to enable KaTex block using marked.js ?

**Comment by MobeenAshraf** [comment]
Hi,  Is custom rules possible now for achieving this?

**Comment by BenjaminHoegh** [comment]
> Hi @BenjaminHoegh, have you ever find a way to enable KaTex block using marked.js ?

Yes I can post the code there solved it if you wanna see it

**Comment by jfcere** [comment]
@BenjaminHoegh, yes that would be really appreciated 😃
