### ISSUE TITLE
Add source line number to the output result

### ISSUE THREAD

**Issue by duongphuhiep** [markedjs/marked#1267]
**Marked version:** 0.3.19

**Markdown flavor:** n/a

**Proposal type:** new feature

## What pain point are you perceiving?

I want to make a markdown editor with a preview panel capable of highlighting and jumping to the current editing line => it was possible in `commonmark` but not possible in `marked`

## What solution are you suggesting?
```js
var lexed = marked.lexer('# hello world\n* what\n* are\n* you?');
var parsed = marked.parser(lexed);
console.log(parsed);
```
actual result:
```html
<h1 id="hello-world">hello world</h1>
<ul>
<li>what</li>
<li>are</li>
<li>you?</li>
</ul>
```
the result should have the line number of the original source:
```html
<h1 id="hello-world" data-sourcepos=1>hello world</h1>
<ul data-sourcepos=2>
<li data-sourcepos=2>what</li>
<li data-sourcepos=3>are</li>
<li data-sourcepos=4>you?</li>
</ul>
```

If the output has the source line number, we can make a preview panel like this one (impossible today):
![image](https://github.com/duongphuhiep/commonmark-editor/blob/master/commonmark-editor-demo.gif?raw=true)

**Comment by UziTech** [comment]
Sounds like you want to modify the renderer. check out our [usage docs](https://marked.js.org/#/USING_PRO.md#renderer) on how to modify the renderer.

I don't think this is anything we would ever add to marked but if you want to make a wrapper around marked that adds the data attributes, that would be cool.

**Comment by duongphuhiep** [comment]
Modify the render is not enough, the information I need to render (source line number) is not giving by the lexer 

```js
renderer.heading = function (text, level) {
  // I cannot render the source line number here
};
```

what I need maybe
```js
renderer.heading = function (text, level, line) {
  // ok, I can render it now 
};
```
I thnk that no wrapper around mark can do this... 

Please tell me if I'm wrong.. I'm reading the code..

**Comment by LiWeny16** [comment]
Same problem that I need to give up marked js for it's hard to generate line number.
