### ISSUE TITLE
New release tag?

### ISSUE THREAD

**Issue by robcresswell** [markedjs/marked#1271]
Hi!

Are there any plans for a new release soon? There's been a couple of bugfixes landed that I'm personally interested in since the last release, and it'd be great to see the ongoing work published :)

**Comment by joshbruce** [comment]
@robcresswell: Thanks for posting this question. I was hoping to get #1226 included in the next release (0.4.0). However, it appears @davisjam is on vacation; therefore, unless @UziTech and @styfle have an issue with, we'll probably publish soon.

I don't see any reason that we couldn't do the release. (Silence will be consent on this one.)

**Comment by UziTech** [comment]
There have been a lot of changes since 0.3.19 so it would be nice to get a release out, but there are still some redos issues we are trying to fix that will be breaking changes so our next release (after 0.4.0) will most likely also have breaking changes.

I'm not sure if we want to get all the breaking changes into 0.4.0 or release 0.5.0 after that.

I'm good either way.

**Comment by robcresswell** [comment]
No rush / pressure from my side; just a curiosity, certainly don't mean to make demands on open source work.

**Comment by styfle** [comment]
This is the third request (that I've counted)

Previous two:

- #1268 - Link resolution failed
- #1208 - Option headerIds missing

@joshbruce I would say this is pressure to release.
Can you do this or grant me privileges to npm publish? Thanks! 👍

**Comment by robcresswell** [comment]
@joshbruce @styfle Any chance of the release being published to NPM too? 😇

**Comment by joshbruce** [comment]
@styfle: I would call this pull. :)

@robcresswell: Appreciate the consideration of the fact this is an open source project made by volunteers. No pressure felt. Having said that, we do tend to work on pull from the outside; so, knowing folks are waiting and wanting a release is a good thing. Trust me, if it ever feels like pressure, I'll be one of the first to say something. ;)
