### ISSUE TITLE
Follow semver please?

### ISSUE THREAD

**Issue by mrchief** [markedjs/marked#1274]
**Describe the bug**
In the latest release, marked went up from v0.3.18 to v.0.4.0. A minor bump indicates backward compatible changes and most importantly, no breaking changes. Yet the release notes mention several of them:

![image](https://user-images.githubusercontent.com/781818/40312717-ab7202c6-5ce1-11e8-9c94-05a5d5e336d9.png)

This is counterproductive. A seemingly harmless update potentially can break exiting usages. 

Can we please adhere to [semver](https://semver.org/) guidelines?

**Comment by UziTech** [comment]
https://semver.org/#spec-item-4

**Comment by UziTech** [comment]
In pre-1.0 releases the minor version is commonly used for breaking changes which is why npm has [caret ranges](https://docs.npmjs.com/misc/semver#caret-ranges-123-025-004) (i.e ^0.3.0 will match >= 0.3.0 and < 0.4.0)

**Comment by mrchief** [comment]
Oh, didn't see that coming. Is there a planned v1 release anytime soon?

**Comment by mrchief** [comment]
Kickass homepage by the way! :+1:

**Comment by UziTech** [comment]
We are working toward v1.0 but I think we have a long way to go. We have been trying to [resurrect](https://github.com/markedjs/marked/issues/1106) marked from being unmaintained for a while.

Any PRs would be greatly appreciated 😃 👍
