### ISSUE TITLE
Duplicate Heading IDs

### ISSUE THREAD

**Issue by alystair** [markedjs/marked#1280]
**Describe the bug**
In situations where a document has repeated headers, the ID is duplicated which is a big no-no for HTML validations (only one instance of an ID is allowed).

This is extremely common in changelogs where H3 headers are Added/Changed/Removed/Fixed etc. It flat out screws up accessibility as screen readers would likely ignore duplicate IDs and will cause formatting issues when an ID clashes with another outside the scope of the markdown render.

You cannot use IDs unless they are unique, so consider using "class" instead as a quick fix, and consider applying a configurable prefix to avoid clashing ('md-' perhaps).

**To Reproduce**
Create duplicate headers such as in [this demo](https://marked.js.org/demo/?outputType=html&text=%23%20test%20heading%0ASome%20words%0A%23%23%20Subheading%0ABlahblah%0A%23%23%20Subheading
). Then copy rendered HTML into [W3's HTML5 validato](https://validator.w3.org/nu/#textarea)r to see it fail validation

**Expected behavior**
No conflicts/render or screen reader issues.

**Comment by styfle** [comment]
Hi @alystair thanks for the bug report!

Was this behavior working in a previous version of marked and broke in the latest release?

**Comment by alystair** [comment]
I've only started using markedjs in the last month, but and I've always loaded it via your CDN link https://cdn.jsdelivr.net/npm/marked/marked.min.js

Definitely  consider changing the default behaviour.

**Comment by UziTech** [comment]
We are trying to make marked spec compliant so we are most likely going to remove the headers eventually since they are not part of any markdown spec.

**Comment by joshbruce** [comment]
The reason it's `true` by default was to maintain consistency for users. Originally the default for Marked was to have the header ids with no way to turn them off. Making false the default could cause users to need to update their code.

@alystair is correct re id usage in HTML, which was a big reason for wanting to get out of the header id business; thereby, leaving it to developers to implement via extension and work with. I believe @UziTech is also correct in the history and why id is being used and why a post-processor like GitHub uses is probably a more viable approach.

**Comment by canyoudev** [comment]
@styfle why `headerIds: false` doesn't work? I have `"marked": "^0.3.19"`

Why this option is enabled in first place? It make no sense for me.

**Comment by canyoudev** [comment]
Got it, it works with `4`!

**Comment by styfle** [comment]
> Why this option is enabled in first place?

@canyoudev See [this comment](https://github.com/markedjs/marked/issues/1280#issuecomment-392860250).

> why headerIds: false doesn't work?

The feature to disable heading ids wasn't implement until [v4.0.0](https://github.com/markedjs/marked/releases/tag/0.4.0) as you have discovered.

This is also indicted in the [options](https://marked.js.org/#/USING_ADVANCED.md#options) documentation.

**Comment by styfle** [comment]
Good point, I created #1354

**Comment by Martii** [comment]
Outsourcing can be good for this as long as we can do a slower migration path e.g. keep the old style lexer override until we modify each and every comment that has references to existing id's in the DB. This is definitely can be user content breaking across all sites that reference us but I realize that there are quite a few issues with auto "bookmark"ing and it could use some improvement.

@styfle 

> I wanted to get some early feedback on this

I'll see if I have a spare few to test the PR on our dev and see how much content really needs to be modified. Hopefully the outsourcing doesn't change their style output either because one DB traversal for this is enough imho. :)

**Comment by styfle** [comment]
After much discussion in the previous PR, I created a new one to fix this issue: #1401
