### ISSUE TITLE
Dynamic Task Lists based on issue numbers

### ISSUE THREAD

**Issue by modem7** [markedjs/marked#1282]
**Describe the feature**
Currently the task list is manual. I tick/untick and it gets done. 

Would like to see a feature where if there is an issue number, it automatically ticks/unticks as the issue is open/closed.

**Why is this feature necessary?**
In certain circumstances, a compiled list of certain issues that have been opened/closed would be useful, especially if there are 5-10 issues relating to a particular subject, but they are suitable for labels or other filters. 

It would be useful so that we can create dynamic task lists for people who aren't involved in the project, but would like to see updates regarding a certain number of issues in one place.

E.g. 
Issues relating to the colour green in the UX

- [ ] #issue1 - Not green enough
- [x] #issue2 - Too green
- [ ] #issue3 - This is actually blue

**Describe alternatives you've considered**
Currently only alternative is to tick/untick manually as the issues are opened or closed.

**Comment by UziTech** [comment]
marked has nothing to do with github issues. We are a tools used to change markdown into html. That is all we do.

You may want to contact github with this issue.
