### ISSUE TITLE
Linkification misbehaves for URLs inside of parenthesis followed by a period.

### ISSUE THREAD

**Issue by fspinolo** [markedjs/marked#1283]
**Marked version: 0.4.0**

**Markdown flavor:** n/a

Problem statement:

Linkification misbehaves for URLs inside of parenthesis followed by a period. Example text that renders incorrectly:

"Github (http://github.com)."

## Expectation

I expect that "http://github.com" will be linkified.

## Result

**Marked Demo:** [demo](https://marked.js.org/demo/?text=Github%20(http%3A%2F%2Fgithub.com).%0A)

The closing parenthesis is included in the link, breaking the link. So, instead of linking to "http://github.com" it creates a link to "http://github.com)".

## What was attempted

There is nothing fancy required to reproduce this. The problem appears to be in the lexer.

**Comment by Trott** [comment]
I haven't tested but it seems likely that https://github.com/markedjs/marked/pull/1293 would fix this issue.

**Comment by styfle** [comment]
Correct, this was fixed in #1293 and will be available in the next release (likely v0.5.0)
