### ISSUE TITLE
Italics modifier (_) breaks links containing underscores

### ISSUE THREAD

**Issue by RomanHotsiy** [markedjs/marked#1284]
**Describe bug**

When using double underscore in the text the next link containing underscore gets broken. Works fine with commonmark:
```markdown
__ test [test](https://test.com/_)
```

**To Reproduce**
[Marked Demo](https://marked.js.org/demo/?text=__%20test%20%5Btest%5D(https%3A%2F%2Ftest.com%2F_)) - invalid
[CommonMark Demo](https://spec.commonmark.org/dingus/?text=__%20test%20%5Btest%5D(https%3A%2F%2Ftest.com%2F_)) - valid

Github demo:
__ test [test](https://test.com/_)

**Comment by UziTech** [comment]
related to #1410

**Comment by Scrum** [comment]
@UziTech closed in #1641
