### ISSUE TITLE
can it highlight

### ISSUE THREAD

**Issue by thyxsl** [markedjs/marked#1286]
can it highlight

**Comment by UziTech** [comment]
Highlight what?

**Comment by styfle** [comment]
@thyxsl Maybe you're looking for syntax highlighting?
You can use something like `highlight.js`.
See [USING_ADVANCED.md](https://marked.js.org/#/USING_ADVANCED.md) for an example.

**Comment by thyxsl** [comment]
Thank you very much!

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Steven <notifications@github.com>
发送时间: Friday, June 15, 2018 12:48:11 AM
收件人: markedjs/marked
抄送: thyxsl; Mention
主题: Re: [markedjs/marked] can it highlight (#1286)


@thyxsl<https://github.com/thyxsl> Maybe you're looking for syntax highlighting?
You can use something like highlight.js.
See USING_ADVANCED.md<https://marked.js.org/#/USING_ADVANCED.md> for an example.

―

**Comment by thyxsl** [comment]
highlighting

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Tony Brix <notifications@github.com>
发送时间: Friday, June 8, 2018 11:13:51 PM
收件人: markedjs/marked
抄送: Thyxsl; Author
主题: Re: [markedjs/marked] can it highlight (#1286)


Highlight what?

―
