### ISSUE TITLE
Feat: Optional Special Character Escaping

### ISSUE THREAD

**Issue by pzuraq** [markedjs/marked#1291]
**Describe the feature**

Flag or other public API to customize character escaping for special characters (e.g. `<>'"`)

**Why is this feature necessary?**

We're attempting to integrate Markdown with the Ember/Handlebars template compiler in order to make writing documentation with Handlebars templates more ergonomic. Currently the process we have is to first run markdown templates through Marked, and then run them through the Handlebars compiler.

Unfortunately, Marked doesn't recognize various Handlebars helper/component invocations and thus escapes them, causing them to render as plain text when passed into the Handlebars compiler:

```hbs
<!-- Not recognized, quotes are escaped -->
{{helper-func param="param"}}

<!-- Not recognized, angle brackets are escaped -->
<t.head @params={{param}}>
``` 

More generally, any language that is attempting to do a first-pass with Marked/markdown and then compile in a different target will potentially have this problem (`.mdx` for instance). Customizing the Lexer to recognize these different tags in different systems is not an easily maintainable solution, as it requires new cases to be added for each new addition to the templating language (for instance, `<foo.bar>` syntax is a new addition to the Handlebars language).

For most of these systems, the secondary compilers will already deal with special characters, so there is no need to escape anything outside of code blocks. So, having the option to turn off escaping in text blocks altogether would be ideal.

**Describe alternatives you've considered**

Customizing the Lexer to recognize new template helpers/tags. This would be hard to maintain as templating languages evolve, and would require a new Lexer per templating language, which is overkill.

**Comment by styfle** [comment]
> More generally, any language that is attempting to do a first-pass with Marked/markdown and then compile in a different target will potentially have this problem

Could you change the order so that the handlebars processor runs first and then marked?
I'm assuming handlebars will give you HTML output which you can pass into marked.

**Comment by pzuraq** [comment]
Handlebars/Glimmer in Ember actually produces a javascript function that can be used to render and update the template. In some apps now (and all future apps), it compiles to a binary format to minimize template/payload size. I don't think it would be possible to do this in the reverse because of that.
