### ISSUE TITLE
xss vulnerability in demo page

### ISSUE THREAD

**Issue by UziTech** [markedjs/marked#1294]
**Describe the bug**

Our [demo](https://marked.js.org/demo/?text=scenario%201%20-%20%3Cjavascript%3Aalert(1)%3E%0A%0A%5Bscenario%202%5D(javascript%3Aalert(2))%0A%0A%5Bscenario%203%5D%5B1%5D%0A%0A%5Bscenario%204%5D%0A%0A%5B1%5D%3A%20javascript%3Aalert(3)%0A%0A%5BScenario%204%5D%3A%20javascript%3Aalert(4)) page allows xss

We should try to mitigate this similar to commonmark's [demo](https://spec.commonmark.org/dingus/?text=scenario%201%20-%20%3Cjavascript%3Aalert(1)%3E%0A%0A%5Bscenario%202%5D(javascript%3Aalert(2))%0A%0A%5Bscenario%203%5D%5B1%5D%0A%0A%5Bscenario%204%5D%0A%0A%5B1%5D%3A%20javascript%3Aalert(3)%0A%0A%5BScenario%204%5D%3A%20javascript%3Aalert(4)) page

We should also have a disclaimer in our documentation about possible xss vulnerability with displaying unsanitized output

related #1232

**To Reproduce**

1. goto the [demo](https://marked.js.org/demo/?text=scenario%201%20-%20%3Cjavascript%3Aalert(1)%3E%0A%0A%5Bscenario%202%5D(javascript%3Aalert(2))%0A%0A%5Bscenario%203%5D%5B1%5D%0A%0A%5Bscenario%204%5D%0A%0A%5B1%5D%3A%20javascript%3Aalert(3)%0A%0A%5BScenario%204%5D%3A%20javascript%3Aalert(4))
2. click one of the links

**Expected behavior**
Javascript should not execute

**Comment by lirantal** [comment]
@UziTech the report is not disclosed so only you and another person are able to access it.
Will you please also add the security notice to the README?

**Comment by joshbruce** [comment]
@davisjam to @lirantal's point, what is the standard practice regarding reporting this kind of thing? 

This XSS is not on the Marked library - it is on a site we own and provide as a service to users and as a marketing tool. Therefore, we, the committers, are the ones running accept/mitigate/etc. against the vulnerability.

This is also fixed by #1295; so, I don't think we need to update the README - just want to know what the the MO is.

**Comment by UziTech** [comment]
@joshbruce this was reported on hackerone.com and I was invited to review the report. The README notice is to remind people using marked from NPM that marked does not sanitize output by default and that displaying user generated markdown can be dangerous.

**Comment by uk1free** [comment]
M

**Comment by styfle** [comment]
@uk1free Hi Mark Murray, we appreciate that your are following the development of marked but please do not spam our issue tracker :octocat: 

When you reply to the email from GitHub, your message is sent to 400 people watching this repository and it is a waste of time for 400 people to view a message that says "M".

Thanks! 😄
