### ISSUE TITLE
Marked adds excessive newline characters in lists (GFM mode)

### ISSUE THREAD

**Issue by bugy** [markedjs/marked#1296]
**Describe the bug**
When Marked is rendering a list in GFM mode with line breaks enabled, it adds unneeded \n characters after each list element. In GitHub all (even source) newline characters are removed in a list

**To Reproduce**
_JS code:_
`marked('List elements:\n- item1\n- item2', {sanitize: true, gfm: true, breaks: true})`

_Actual output:_ 
`<p>List elements:</p>\n<ul>\n<li>item1</li>\n<li>item2</li>\n</ul>`

_Expected output:_
`<p>List elements:</p><ul><li>item1</li><li>item2</li></ul>`

Expected output is based on HTML code in GitHub preview

**Comment by UziTech** [comment]
Just curious, why is this an issue? I don't believe the specs specify one way or the other

**Comment by bugy** [comment]
Hi @UziTech, for me it causes only a small problem - I can't reliably unit test my corresponding code. But from visual perspective it looks fine.
However \n can be a printable character in html (e.g. with css `white-space: pre`), so I thought, that probably it's worth fixing it. At least if it's not a large change

**Comment by UziTech** [comment]
It seems like GitHub adds the new lines the same as [marked](https://marked.js.org/demo/?outputType=html&text=List%20elements%3A%0A-%20item1%0A-%20item2&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20true%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tables%22%3A%20true%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master) and [commonmark](https://spec.commonmark.org/dingus/?text=List%20elements%3A%0A-%20item1%0A-%20item2) so I don't think we are going to change this.

![image](https://user-images.githubusercontent.com/97994/54131966-656f3400-43e1-11e9-998e-f9e4b4907443.png)
