### ISSUE TITLE
Marked adds extra/unnecessary <p> tags to list elements

### ISSUE THREAD

**Issue by utdrmac** [markedjs/marked#1298]
**Describe the bug**
When using lists with linebreak separation, Marked adds unnecessary &lt;p&gt; tags to list items.

**To Reproduce**
Using CommonMark, the following adds erroneous &lt;p&gt; tags around the BBB, DDD, and EEE elements.
Using MarkedDemo, the following adds &lt;p&gt; tags around AAA (correct) and BBB (incorrect).

```
## Testing

* AAA

* BBB
    * CCC
* DDD
* EEE
```

**Expected behavior**
With the above code, only AAA should have &lt;p&gt; element wrappers.

** Additional Example **
```
## Testing

* AAA
* BBB
    * CCC
* DDD

* EEE
```
Above, CommonMark adds around AAA, BBB, DDD, EEE.
Above, MarkedDemo adds around DDD, and EEE

**Comment by UziTech** [comment]
Why is it incorrect to add `<p>` tags around `BBB`, `DDD`, and `EEE`? Is this in the spec somewhere?

[CommonMark demo](https://spec.commonmark.org/dingus/?text=%23%23%20Testing%0A%0A*%20AAA%0A%0A*%20BBB%0A%20%20%20%20*%20CCC%0A*%20DDD%0A*%20EEE)
[Marked demo](https://marked.js.org/demo/?outputType=html&text=%23%23%20Testing%0A%0A*%20AAA%0A%0A*%20BBB%0A%20%20%20%20*%20CCC%0A*%20DDD%0A*%20EEE)

**Comment by utdrmac** [comment]
Because that doesn't make any sense. I put a new line between AAA and BBB, so why are other list items being affect by this?

**Comment by utdrmac** [comment]
Similar situation: [commonmark](https://spec.commonmark.org/dingus/?text=%23%23%20Testing%0A%0A*%20AAA%0A*%20BBB%0A%20%20%20%20*%20CCC%0A*%20DDD%0A%0A*%20EEE)
There's a line break before EEE, so why are other elements also getting p tags?

**Comment by utdrmac** [comment]
That's very odd. I'd like to see a real-world use case where having a line break on the last element of a list should affect every element that comes before or after it, instead of just affecting 'it'.
