### ISSUE TITLE
Ignore certain rules defined by markdown.

### ISSUE THREAD

**Issue by priyesh-diukar** [markedjs/marked#1302]
I want to convert only bold, italic, underline and link to markdown and ignore other rules mentioned by the lexer.
How do i achieve this?
I could not find a example on the extensibility page.
Can someone help me with this?
I want to ignore all rules except above mentioned four conditions.

**Comment by denisftw** [comment]
It could be really great to have an out-of-the-box solution for this scenario. For the time being, I settled in using the following approach:

```js
const enabled = ['list', 'listitem', 'strong', 'em', 'paragraph', 'br'];
const renderer = new marked.TextRenderer();
const realRenderer = new marked.Renderer();
enabled.forEach((option) => {
  renderer[option] = realRenderer[option];
});
```

**Comment by styfle** [comment]
Related: #420
