### ISSUE TITLE
Restore readme

### ISSUE THREAD

**Issue by rumkin** [markedjs/marked#1309]
Current readme is poor. There is no valuable information.

The [previous version](https://github.com/rumkin/marked) was more useful.

**Comment by styfle** [comment]
Hi rumkin,

The current documentation can be found at http://marked.js.org

I hope this is satisfactory 👍

**Comment by rumkin** [comment]
Thanks for links. I still think it's better to make readme more informative. Or at least provide navigation block in readme to find this sections.

**Comment by styfle** [comment]
Sure! Would you like to create PR to create these links?
