### ISSUE TITLE
npm WARN marked-terminal@1.7.0 requires a peer of marked@^0.3.3 but none is installed.

### ISSUE THREAD

**Issue by samit4me** [markedjs/marked#1313]
Version `0.3.19` was fine, but after upgrading to version `0.4.0` if I run `npm install` I get the following warning:

```
npm WARN marked-terminal@1.7.0 requires a peer of marked@^0.3.3 but none is installed. You must install peer dependencies yourself.
```

Is this expected?

FYI: this does not occur if clean install (e.g. no existing `node_module` folder). If you remove the `node_modules` folder then run `npm install`, then run `npm install` again it will throw the warning on the 2nd `npm install`

**Comment by UziTech** [comment]
You need to update marked-terminal

https://github.com/mikaelbr/marked-terminal/issues/40

**Comment by samit4me** [comment]
Thank you for the response and sorry, it obvious I don't really understand peer dependancies 😕 Is the best way to handle this to add it to `package.json` (e.g. `npm i -S marked-terminal`) so nobody else using the project gets the same error?

**Comment by UziTech** [comment]
Yup that should work
