### ISSUE TITLE
Whitespace in fenced code info string breaks rendering

### ISSUE THREAD

**Issue by camwiegert** [markedjs/marked#1314]
**Describe the bug**

When there is whitespace in the info string of a fenced code block, like so: 
```
```html foo
```
...the block is not parsed as a code block. It appears to be rendered as a paragraph:
```html
<p>```html foo</p>
```

**To Reproduce**

1. Add a whitespace character in the info string of a fenced code block.
2. Render with the default renderer.

**Expected behavior**

When there is whitespace in the info string, GFM appears to use the first word as the language and ignore the rest. (As demonstrated [here](https://gist.github.com/camwiegert/0bfc9921993d22bf29b0b10a1ffda4ff)) I would expect Marked to do the same by default and pass the entire info string to a custom renderer.

Thank you! 👋

**Comment by UziTech** [comment]
comfirmed

[common mark spec example #112](https://spec.commonmark.org/0.28/#example-112)

**Comment by Feder1co5oave** [comment]
#1387 returns this:

~~~~~
bin/marked
```html foo
^D
<pre><code class="language-html"></code></pre>
~~~~~~

which seems correct
