### ISSUE TITLE
markdown keywords not removed after markdownTOhtml conversion

### ISSUE THREAD

**Issue by ilsergente1993** [markedjs/marked#1318]
**Describe the feature**
The feature, like an option, to say to the parser to keep the markdown keywords to not be removed in the html

**Why is this feature necessary?**
The use case I'd like to realize in my application is an editor, basically a `<div>` component with attribute `contenteditable="true"`, with rendered html text obtained from the marked conversion and the markdown keywords in the text to graphically see the markdown effect on the text.

For example, the following code is what I get by the conversion from 
markdown to html:
`<p>I'm a <strong>very beautiful</strong>html</p>`
that could become 
`<p>I'm a <strong>**very beautiful**</strong>html</p>`  to have the rendered html in the div with the markdown code too.

In this way I think I can edit the text in the `div` and immediatly the parser show the result.

[This](https://github.com/sparksuite/simplemde-markdown-editor) plugin support this feature natively.

In my opinion it's simple have the same result with an option like "keepMarkdownKeywords" set to true.

**Describe alternatives you've considered**
nothing

**Comment by UziTech** [comment]
We are in the process of making marked spec compliant and deprecating most options from the core marked library.

This seems like it would be a great extension to marked at could be achieved by [extending](https://marked.js.org/#/USING_PRO.md) the Renderer and adding the syntax back when returning the HTML.

e.g.

```diff
  Renderer.prototype.strong = function(text) {
-   return '<strong>' + text + '</strong>';
+   return '<strong>**' + text + '**</strong>';
  };
```

It would be very difficult to add all of the functionality and edge cases though.

**Comment by ilsergente1993** [comment]
Thank you for your answer @UziTech.
I tried your suggestion and it works quite fine. 

The more I think about your code the more I think should be added an option to enable returning the syntax. Extend the render for all the keywords sounds laborious.

I'm pretty new about this component, do you have an extension directory or something like this?

**Comment by UziTech** [comment]
We do not have a directory of extensions. You could try searching npm for [marked](https://www.npmjs.com/search?q=marked)
