### ISSUE TITLE
In Safari: undefined is not an object (evaluating 't.toLowerCase') 

### ISSUE THREAD

**Issue by flowcl** [markedjs/marked#1319]
The error occurs in Safari, in Chrome it works ok

Something went wrong...
undefined is not an object (evaluating 't.toLowerCase') Please report this to https://github.com/markedjs/marked.

Stack trace

l@https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:22:2488
code@https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:55:37004
parse@https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:55:39401
v@https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:55:42284
extractHeadings@https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:55:13303
addMarkdownItems@https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:111:44448
buildStructure@https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:111:44220
https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:111:34163
e@https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:111:50959
makeStore@https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:117:65930
render@https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:117:66791
Ti@https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:89:62924
fa@https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:89:77381
da@https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:89:77688
Qa@https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:89:81236
Ha@https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:89:80748
Wa@https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:89:80574
za@https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:89:79947
va@https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:89:79179
enqueueSetState@https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:89:54715
setState@https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:81:1528
https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:117:66418
https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:22:2057
a@https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:22:933
promiseReactionJob@[native code]

ReDoc Version: 2.0.0-alpha.34 
Commit: fc31145

See the error in https://www.flow.cl/docs/api.html

**Comment by UziTech** [comment]
Can you give us the input?

Sounds like it may be an issue for [ReDoc](https://github.com/Rebilly/ReDoc)

Looks like they still use marked v0.3.18

**Comment by styfle** [comment]
Closing since there was no response.
