### ISSUE TITLE
marked_1.default is not a function. returns "null" in source

### ISSUE THREAD

**Issue by markmakes** [markedjs/marked#1320]
Looks like Angular Universal's server.js doesn't like something with one of your functions. Getting this on the node server:

ERROR TypeError: marked_1.default is not a function
/dist/server.js:151583:40

### The Component

```
import {Component, Input, OnInit} from '@angular/core';
import {ContentBlock} from '../../../../app/api-modules/FRApi/Models/api-models';
import marked from 'marked';

@Component({
  selector: 'app-textview-block',
  templateUrl: './app-textview-block.component.html',
  styleUrls: ['./app-textview-block.component.scss']
})
export class AppTextviewBlockComponent implements OnInit {

  @Input()
  block: ContentBlock;
  content: any;
  constructor() { }

  ngOnInit() {
    this.content = marked(this.block.content);
  }
}
```

### Server.js line 151583

```
var marked_1 = __webpack_require__(/*! marked */ "marked");
var AppTextviewBlockComponent = /** @class */ (function () {
    function AppTextviewBlockComponent() {
    }
    AppTextviewBlockComponent.prototype.ngOnInit = function () {
        this.content = marked_1.default(this.block.content);
    };
    return AppTextviewBlockComponent;
}());
```

### Our QA site
[https://other98uias-qa.azurewebsites.net/week-1-of-fall-camp-offensive-recap/308/10](https://other98uias-qa.azurewebsites.net/week-1-of-fall-camp-offensive-recap/308/10)

### The HTML 
`<div class="text-view" [innerHTML]="content"></div>`

### The generated source
`<div _ngcontent-sc17="" class="text-view">null</div>`

**Comment by styfle** [comment]
There is no default export because it’s not a ES Module. 

Maybe this will work:

import * as marked from 'marked';

**Comment by markmakes** [comment]
100% right. Everything works perfectly now. 

Appreciate the prompt and working answer!

**Comment by styfle** [comment]
Glad I could help 👍🏼 

We have a proposal to move to ESM but node.js is not ready and there are some debates about should we continue shipping CJS and UMD builds. Follow along here: https://github.com/markedjs/marked/issues/1288
