### ISSUE TITLE
Error rendering "this.renderer.checkbox is not a function"

### ISSUE THREAD

**Issue by Marielk** [markedjs/marked#1323]
Hello 
I am building a node module library, wich has to be able to extract all the links from a .md file (markdown), i am using marked, terminal-marked and chalk as modules, but when i run it on the terminal  (i am using Git Bash with ubuntu) it works as i want, but next it has the following error code: 

TypeError: this.renderer.checkbox is not a function
Please report this to https://github.com/markedjs/marked.

![captura de pantalla de 2018-08-24 12-39-04](https://user-images.githubusercontent.com/38724465/44593835-e5fa7a00-a79a-11e8-9f0f-9486090914f7.png)
![captura de pantalla de 2018-08-24 12-38-59](https://user-images.githubusercontent.com/38724465/44593841-eb57c480-a79a-11e8-918b-1e7bbab56534.png)
![captura de pantalla de 2018-08-24 12-38-50](https://user-images.githubusercontent.com/38724465/44593853-f1e63c00-a79a-11e8-88a2-5b4d86abcefd.png)
![captura de pantalla de 2018-08-24 12-38-41](https://user-images.githubusercontent.com/38724465/44593862-f7dc1d00-a79a-11e8-8db4-e72320439baa.png)

this is my code : 
 console.log('href:' + marked(href), 'file:' + marked(file))

I hope you can tell me how can i fix it, thank you!

**Comment by UziTech** [comment]
looks like this is a problem with marked-terminal.

https://github.com/mikaelbr/marked-terminal/pull/44

**Comment by UziTech** [comment]
The PR has been merged and it should work in the next release of marked-terminal
