### ISSUE TITLE
img tag wrapped in div tag

### ISSUE THREAD

**Issue by jinfagang** [markedjs/marked#1324]
marked is so good, but it parse img into p tag, which is sometimes make img inside p text, and not so convenient make img center , could that be parse inside a div tag so that it becomes a line block and more easy controll the style of img?

**Comment by styfle** [comment]
Can you provide an example?

**Comment by jinfagang** [comment]
@styfle Solved it by using:

```
display: block;
margin-left:auto;
margin-right:auto
```
