### ISSUE TITLE
Nested pre render error

### ISSUE THREAD

**Issue by LitileXueZha** [markedjs/marked#1325]
Here is a [demo](https://marked.js.org/demo/?text=%60%60%60%0A%2F%2F%60%60%60%0A%2F%2F%20const%20a%20%3D%20%27b%27%3B%0A%2F%2F%60%60%60%0A%60%60%60%0A%0A)

Should it be:
```
//```
// const a = 'b';
//```
```

Source md:
```md
    ```
    // ```
    // const a = 'b';
    // ```
    ```
```

**Comment by UziTech** [comment]
[CommonMark demo](https://spec.commonmark.org/dingus/?text=%60%60%60%0A%2F%2F%60%60%60%0A%2F%2F%20const%20a%20%3D%20%27b%27%3B%0A%2F%2F%60%60%60%0A%60%60%60%0A%0A)

The workaround for this is to use more than 3 backticks to start the code block

e.g.
`````
````
//```
// const a = 'b';
//```
````
`````

[demo](https://marked.js.org/demo/?text=%60%60%60%60%0A%2F%2F%60%60%60%0A%2F%2F%20const%20a%20%3D%20%27b%27%3B%0A%2F%2F%60%60%60%0A%60%60%60%60%0A%0A)

**Comment by LitileXueZha** [comment]
ok, thanks

**Comment by UziTech** [comment]
I'm going to reopen this, since it is still a bug, so we can keep track of the issues
