### ISSUE TITLE
Autolink breaks mailto links when wrapped in styling syntax

### ISSUE THREAD

**Issue by destroytoday** [markedjs/marked#1327]
In versions v0.3.14 and up, when wrapping an email address with styling syntax (*, **, _, etc), Marked includes the opening syntax in the email address, which prevents styling. ex: `**me@example.com**` renders `<a href='mailto:**me@example.com'>**me@example.com</a>**`

**Steps to reproduce the behavior:**

1. Install any version of Marked from v0.3.14 until latest (`npm install marked`)
2. Wrap an email address in bold or italic syntax (`**me@example.com**`)
3. Render with Marked (`var marked = require('marked'); marked('**me@example.com**')`)
4. Actual output is `<a href='mailto:**me@example.com'>**me@example.com</a>**`

**Expected behavior**
Marked should properly style the email address and extract it correctly for the mailto link: `<strong><a href='mailto:me@example.com'>me@example.com</a></strong>`

**Comment by UziTech** [comment]
confirmed

[demo](https://marked.js.org/demo/?text=**me%40example.com**)

**Comment by styfle** [comment]
Related #1307
