### ISSUE TITLE
Is there a way to white-list specific HTML tags when sanitize is true?

### ISSUE THREAD

**Issue by chevex** [markedjs/marked#133]
I love the sanitize feature and most markdown libraries don't include it or do it very badly. However, there is one feature that Marked does not have that my previous library did, the ability to white-list specific tags or a default set of tags (see [node-markdown](https://github.com/andris9/node-markdown)). Is it possible to have this added to Marked?

This library is the best javascript markdown library I've seen. The main attraction for me is the ability to use it on the server and on the client so I can generate Markdown previews for the user without making ajax calls or having differences between the client library and the server library. If I can just enable specific tags when sanitize is true that would complete the library for me.

**Comment by markstos** [comment]
+1

**Comment by j127** [comment]
This feature would be very useful.

**Comment by markstos** [comment]
A workaround is to *not* use the sanitize feature of Markdown, but instead pass the resulting HTML through a tool that focuses just on HTML sanitizing, like the `insane` module. It works out being about the same amount of code and configuration, and yes the `insane` module supports custom whitelists both tags and attributes. 

The Markdown spec does not include any notion of HTML sanitizing. Sanitizing is a separate task that is well served by using a separate module.

**Comment by j127** [comment]
@markstos - thanks

**Comment by styfle** [comment]
I think @markstos is correct, using a 3rd party sanitizer is the solution here instead of adding a new feature.

I'm closing this in favor of #1232 which is a discussion about external sanitizers and deprecation of the internal sanitizer.
