### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by joshbruce** [markedjs/marked#1330]
**What pain point are you perceiving?.**

Security vulnerability due to `devDependencies` in `package.json`. It's on `lodash`, which is most likely the dependency of a dependency. While this doesn't negatively effect our users it might cause problems with automatic tracking databases that don't distinguish between dependencies (which Marked has none) and devDependencies (which Marked has a few).
 
**Describe the solution you'd like**

Some type of dependency check protocol we can perform. Maybe on a somewhat rotating basis so one of us doesn't get stuck doing it all the time. Something captured in the contributing documentation; who knows, maybe someone from the community would be willing to step up to make sure we're up to date and whatnot...just spitballing.

**Comment by styfle** [comment]
@joshbruce I actually sent a [private message](https://github.com/orgs/markedjs/teams/marked/discussions/22) about this.

We have a solution...GitHub [tracks dependencies](https://github.com/markedjs/marked/network/dependencies) and shows a notification for these vulnerabilities.

![image](https://user-images.githubusercontent.com/229881/45166224-818ce100-b1c4-11e8-90d0-e4c1b4a425f7.png)

In this case, it looks like @UziTech already forked the unmaintained repo as we discussed. The fork can be found here: https://github.com/markedjs/html-differ

**Comment by joshbruce** [comment]
@styfle: Yeah. I was thinking a way to be a bit more proactive about it and go beyond just security vulnerabilities. Make sure we're using the latest versions. Maybe even check if there's a replacement library that does something better. That sort of thing. Don't want to force it or create more work for us, of course.

**Comment by styfle** [comment]
If you just want some indicator that dependencies are out of date, we could add a badge that checks for this.


![dep](https://badgen.net/david/dep/markedjs/marked) https://badgen.net/david/dep/markedjs/marked

![dev](https://badgen.net/david/dev/markedjs/marked) https://badgen.net/david/dev/markedjs/marked

**Comment by UziTech** [comment]
That wouldn't be a bad thing to add to the readme. I think not having any regular dependencies is one of the benefits of marked.

**Comment by styfle** [comment]
I created PR #1333
