### ISSUE TITLE
Code Syntax Highlighting

### ISSUE THREAD

**Issue by chatelao** [markedjs/marked#1332]
**Describe the feature**
The block comment for source code would be nice with supported coloring for languages.

Triple-Dash + Language example (works in GitHub):

```javascript
function test() {
  console.log("Hello World");
}
```

**Why is this feature necessary?**
Code is more readable if nice colored / formatted.

See this coloring engine, which may be included:
* https://highlightjs.org/

**Describe alternatives you've considered**
Rendering the code outside the "marked" would be an additionnal effort.

**Comment by UziTech** [comment]
Check out the highlight options in the [Advanced Usage Docs](https://marked.js.org/#/USING_ADVANCED.md)

**Comment by chatelao** [comment]
Thank you.

I just used the online sample, which didn't support XML or JavaScript.
