### ISSUE TITLE
SmartyPants Shouldn't Do Typographic Substitutions In <code> Blocks

### ISSUE THREAD

**Issue by richdouglasevans** [markedjs/marked#1334]
When SmartyPants is enabled, Marked is replacing `--` with an en-dash inside `<code>` blocks.

Per the following comment  on [the SmartyPants website](https://daringfireball.net/projects/smartypants/), I don't think it should.

> SmartyPants does not modify characters within `<pre>`, `<code>`, `<kbd>`, or `<script>` tag blocks.

**To Reproduce**

```bash
git clone https://github.com/richdouglasevans/marked-code-issue.git
cd marked-code-issue
npm i
npm test
```

> I am happy to dig into the code and sort this myself; I'm raising an issue so that I can first confirm with you the expected behaviour.
>
> Issue was noticed here: https://github.com/cypress-io/cypress-documentation/issues/923

**Comment by styfle** [comment]
Hi @richdouglasevans thanks for the bug report.

It took me as second to realize that you are using the html <code></code> instead of the backticks.

It looks like a workaround is to use backticks instead like so:

```js
marked('Did you know---this is a emdash. But this is code `--record`', {smartypants: true});
// <p>Did you know—this is a emdash. But this is code <code>--record</code></p>
```

**Comment by richdouglasevans** [comment]
Aye, cheers Steven :+1:

Yep, that works... the `<code>` blocks are being inserted by a component in my toolchain so I either need to rethink the way my toolchain works or solve this issue at source here.

I'll dig in and see if I can sort it here.
