### ISSUE TITLE
Catch-all method for Renderer

### ISSUE THREAD

**Issue by hansy** [markedjs/marked#1336]
I couldn't find this in the docs, but I was wondering if there was a way to set up some sort of catch-all method for HTML tags that don't match any overwritten renderer methods? For example:

    const md = require('marked');
    const renderer = new md.Renderer();

    renderer.heading = (text, level) => // do something with headings;
    renderer.paragraph = text => // do something with paragraphs;

    renderer.all = htmlString => // do something with any element not a header or paragraph

    md(input, { renderer }, (err, result) => console.log(result);

**Comment by UziTech** [comment]
No, any method that is not overwritten is assumed to be using the default implementation

**Comment by styfle** [comment]
It's pretty easy to achieve today without an additional feature.

```js
const marked = require('marked');
const renderer = new marked.Renderer();

// Do something for all methods
const all = (str) => { console.log(str) };

// Magic to wire-up all methods on the renderer
Object.keys(renderer.__proto__).forEach(p => renderer[p] = all);

// Change the methods you want to be different
renderer.heading = (text, level) => { console.log(text, level) }
renderer.paragraph = text => { console.log(text) }
```

**Comment by marco-silva0000** [comment]
is this still the best way to implement a catch-all?

**Comment by UziTech** [comment]
@marco-silva0000 yes

**Comment by UziTech** [comment]
Closing as stale. The workaround provided seems sufficient.
