### ISSUE TITLE
**@user.name** is mistaken for an URL, albeit not being a valid email address

### ISSUE THREAD

**Issue by dasdeck** [markedjs/marked#1342]
edit: Seems like this has been fixed for upcoming 0.6 recently?

**@user.name** is mistaken for an URL, albeit not being a valid email address

https://marked.js.org/demo/?text=**%40user.name**

"@user.name" should be printed bold

Maybe adjust the "url" regex to only match valid emails?
Or give ** priority?

Cheers!

JM

**Comment by UziTech** [comment]
This was fixed in #1338 and will be in the next release
