### ISSUE TITLE
*"Yo"* not outputted correctly

### ISSUE THREAD

**Issue by cloudkite** [markedjs/marked#1358]
**Describe the bug**
Emphasize not working when text contains double quotes

**To Reproduce**

[marked demo](https://marked.js.org/demo/?text=*%22Yo%22*)
[commonmark demo](https://spec.commonmark.org/dingus/?text=*%22Yo%22*)

**Comment by styfle** [comment]
Hi Jonas, thanks for the bug report!

This is indeed a bug in 0.5.1 and also in the latest code on master.

Would you like to submit a PR to fix this?

**Comment by dialex** [comment]
It's been more than a year, and this is still an issue (as reported in https://github.com/docsifyjs/docsify/issues/976 and https://github.com/docsifyjs/docsify/issues/787). Is anyone fixing it? Please prioritise it 🙏

**Comment by UziTech** [comment]
@dialex if you want to submit a PR I would be happy to review it 😁

**Comment by dialex** [comment]
I would if I could, I don't know enough of JS or MarkedJS to be of any help.
I'll ask Santa for Christmas 🎅😁 

**Workaround**: use `_"Yo"_` instead of `*"Yo"*`

**Comment by UziTech** [comment]
This was fixed in #1686 released in v1.1.1
