### ISSUE TITLE
Linebreaks doesn't work correctly

### ISSUE THREAD

**Issue by CDNRocket** [markedjs/marked#1363]
Hi, if I write:

> test1test2
> test3test4

Will be rendered as:

```
<p>test1test2
test3test4</p>
```

For work correctly I need to add two spaces like:

> test1test2
> 
> test3test4

That becomes:
```
<p>test1test2</p>
<p>test3test4</p>
```

What is wrong? I've used in Vue:
`marked(Text);`

**Comment by UziTech** [comment]
That is the way the spec defines a paragraph

https://spec.commonmark.org/0.28/#example-183

**Comment by CDNRocket** [comment]
Thank you, but I see other markdown editors that treat every line as a new paragraph.
What specs do I need to use to archive this? 
It's possible with this package?

**Comment by UziTech** [comment]
If you set the `breaks` and `gfm` options to true it will add a `<br>` on every line break

```js
marked("test1test2" + "\n" + "test3test4", {breaks: true, gfm: true});
// <p>test1test2<br>test3test4</p>
```

[demo](https://marked.js.org/demo/?outputType=html&text=test1%0Atest2&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20true%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tables%22%3A%20true%2C%0A%20%22xhtml%22%3A%20false%0A%7D)
