### ISSUE TITLE
Images with space in the URI don't get parsed

### ISSUE THREAD

**Issue by woodyrew** [markedjs/marked#1369]
Images with spaces in the filepath are no longer being parsed correctly.

**To Reproduce**
Process the following doesn't see match an image.
```![Example image](https://example.com/image space.png)```

See [Marked Demo for example](https://marked.js.org/demo/?text=!%5BExample%20image%5D(https%3A%2F%2Fexample.com%2Fimage%20with%20spaces.png)%0AExpected%20the%20url%20to%20be%20made%20html%20friendly%20by%20replacing%20spaces%20with%20%60%2520%60.%0A%0AE.g.%0A!%5BExample%20image%5D(https%3A%2F%2Fexample.com%2Fimage%2620with%2520spaces.png)%0A&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20true%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20true%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tables%22%3A%20true%2C%0A%20%22xhtml%22%3A%20false%0A%7D)

1. Install marked `npm install --save marked@0.5.1` with the version you are using
2. Run marked with input string and options such as `marked('![Example image](https://example.com/image space.png)', {sanitize: true})`

**Expected behavior**
Expected the url to be made html friendly with the switch `sanitize` by replacing spaces with `%20`.

**Comment by UziTech** [comment]
Looks like it is acting the way it is supposed to.

[common mark demo](https://spec.commonmark.org/dingus/?text=!%5BExample%20image%5D(https%3A%2F%2Fexample.com%2Fimage%20with%20spaces.png)%0AExpected%20the%20url%20to%20be%20made%20html%20friendly%20by%20replacing%20spaces%20with%20%60%2520%60.%0A%0AE.g.%0A!%5BExample%20image%5D(https%3A%2F%2Fexample.com%2Fimage%2620with%2520spaces.png)%0A)

according to the [Common Mark Spec](https://spec.commonmark.org/0.28/#link-destination)

> A link destination consists of either
>
> - a sequence of zero or more characters between an opening `<` and a closing `>` **that contains no spaces**, line breaks, or unescaped `<` or `>` characters, or
>
> - a nonempty sequence of characters **that does not include ASCII space** or control characters, and includes parentheses only if (a) they are backslash-escaped or (b) they are part of a balanced pair of unescaped parentheses. (Implementations may impose limits on parentheses nesting to avoid performance issues, but at least three levels of nesting should be supported.)

**Comment by styfle** [comment]
The workaround is to use url encoding like so `![Example image](https://example.com/image%20space.png)`

Notice that the space character is encoded as `%20`

**Comment by woodyrew** [comment]
I'm aware of the Common Mark Spec and the workaround but it feels within the scope of the `sanitize` switch to address this.

**Comment by UziTech** [comment]
As @styfle mentioned above `sanitize` is meant to prevent [XSS attacks](https://www.owasp.org/index.php/Cross-site_Scripting_(XSS)) not fix typos.

The only way to fix your issue would be to replace the space with `%20` before passing it to marked.
