### ISSUE TITLE
Markdown parser acting funky with raw html

### ISSUE THREAD

**Issue by EtanTheTartan** [markedjs/marked#1370]
Since I see that the markdown renderer is referenced within Panini, I decided to open the issue here, but feel free to tell me I'm wrong here.

I have a markdown file. I went from doing an `<h2>` as `##` to using raw html. IE, I went from this:

```html
##Our Rules
Effective: April 2, 2015
```

To: 

```html
<h2>Our Rules</h2>
Effective: April 2, 2015
```

The very strange thing here is that, when there's no line break in the raw `<html>`, the 2nd option, the markdown doesn't render! Anything subsequent render as a string literal and not as the intended markdown -> tag.

simply adding a line break between `<h2>Our Rules</h2>` and `Effective: April 2, 2015` fixed it. As so:

```html
<h2>Our Rules</h2>

Effective: April 2, 2015
```

**Comment by styfle** [comment]
Try adding a space after the hash.

```
## Our Rules
Effective: April 2, 2015
```

## Our Rules
Effective: April 2, 2015

**Comment by styfle** [comment]
It works fine on the [demo page](https://marked.js.org/demo/?outputType=html&text=%23%23%20Our%20Rules%0AEffective%3A%20April%202%2C%202015&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tables%22%3A%20true%2C%0A%20%22xhtml%22%3A%20false%0A%7D)

**Comment by EtanTheTartan** [comment]
Was that a specific issue within `^0.3.14` @UziTech ?

**Comment by UziTech** [comment]
Not sure, but as @styfle [showed](https://github.com/markedjs/marked/issues/1370#issuecomment-434013852) it seems to work with the latest version.

**Comment by styfle** [comment]
I confirmed that adding a space works from version `0.3.14` all the way to the latest version.

https://jsbin.com/feculaqota/edit?html,output

I don't believe this is an issue with marked.

The bug is likely in panini.
