### ISSUE TITLE
 not all code block highlight by lines

### ISSUE THREAD

**Issue by wqh17101** [markedjs/marked#1372]
there were still something strange.
![image](https://user-images.githubusercontent.com/26429138/47692008-3ecd0f80-dc2f-11e8-9e81-f99ec6217cdd.png)
not all code block highlight by lines

**Comment by styfle** [comment]
Please provide the code to reproduce. Can you make a JS Bin? https://jsbin.com

**Comment by wqh17101** [comment]
the jsx and index is here @styfle 

[Desktop.zip](https://github.com/markedjs/marked/files/2530280/Desktop.zip)

**Comment by UziTech** [comment]
this seems like an issue [highlight.js](https://github.com/highlightjs/highlight.js/issues/new) might be able to better help with.

**Comment by styfle** [comment]
Closing in favor of https://github.com/highlightjs/highlight.js/issues/1896
