### ISSUE TITLE
The vertical bars within backsticks shouldn't be interpreted as table cell delimiter.

### ISSUE THREAD

**Issue by lzl124631x** [markedjs/marked#1375]
**Describe the bug**
```
|**Meaning**|Main axis|
|---|---|
|**Values**|`row | row-reverse | column | column-reverse`|
```
is not correctly rendered as table. The vertical bars within backsticks shouldn't be interpreted as table cell delimiter. Related to https://github.com/markedjs/marked/issues/113

StackEdit (among others) supports it.

![image](https://user-images.githubusercontent.com/5824517/48291344-f8479400-e42a-11e8-9b26-5f60ca822735.png)

**To Reproduce**
[demo](https://marked.js.org/demo/?text=%0A%0A%7C**Meaning**%7CMain%20axis%7C%0A%7C---%7C---%7C%0A%7C**Values**%7C%60row%20%7C%20row-reverse%20%7C%20column%20%7C%20column-reverse%60%7C&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tables%22%3A%20true%2C%0A%20%22xhtml%22%3A%20false%0A%7D)

**Expected behavior**
<table>
<thead>
<tr>
<th><strong>Meaning</strong></th>
<th>Main axis</th>
</tr>
</thead>
<tbody>
<tr>
<td><strong>Values</strong></td>
<td><code>row | row-reverse | column | column-reverse</code></td>
</tr>
</tbody>
</table>

**Comment by UziTech** [comment]
This is a bug but you can fix it by escaping the bars. [demo](https://marked.js.org/demo/?text=%0A%0A%7C**Meaning**%7CMain%20axis%7C%0A%7C---%7C---%7C%0A%7C**Values**%7C%60row%20%5C%7C%20row-reverse%20%5C%7C%20column%20%5C%7C%20column-reverse%60%7C&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tables%22%3A%20true%2C%0A%20%22xhtml%22%3A%20false%0A%7D)

PRs are welcome 😃

**Comment by Feder1co5oave** [comment]
There's no easy way to fix this with regexes

**Comment by UziTech** [comment]
It seems like marked actually renders this the same as GitHub:

```
|**Meaning**|Main axis|
|---|---|
|**Values**|`row | row-reverse | column | column-reverse`|
```

|**Meaning**|Main axis|
|---|---|
|**Values**|`row | row-reverse | column | column-reverse`|

---

GitHub requires the pipes to be escaped

```
|**Meaning**|Main axis|
|---|---|
|**Values**|`row \| row-reverse \| column \| column-reverse`|
```

|**Meaning**|Main axis|
|---|---|
|**Values**|`row \| row-reverse \| column \| column-reverse`|
