### ISSUE TITLE
demo not working: sandboxed iframe, 'allow-scripts' permission is not set

### ISSUE THREAD

**Issue by warren-bank** [markedjs/marked#1379]
just a heads-up..

the [demo](https://marked.js.org/demo/) isn't working for me (Chrome 61)..

error in console:
`Blocked script execution in 'https://marked.js.org/demo/preview.html' because the document's frame is sandboxed and the 'allow-scripts' permission is not set.`

**Comment by warren-bank** [comment]
odd.. the demo just started working.. same browser

**Comment by styfle** [comment]
Try disabling Chrome Extensions `chrome://extensions/`

My adblocker makes it break sometimes.
