### ISSUE TITLE
GFM hard line breaks don't follow spec

### ISSUE THREAD

**Issue by superhawk610** [markedjs/marked#1380]
**Describe the bug**
GFM spec describes the following as a **hard line break**:

```
foo··
bar
```

and should translate to the following HTML

```
<p>foo<br />bar</p>
```

Similarly, the following is a **soft line break** (note the lack of 2 trailing spaces):

```
foo
bar
```

and should translate to the following HTML

```
<p>foo\nbar</p>
```

This spec should be followed when `gfm` and `breaks` are both enabled, however enabling `breaks` will always output the first style (hard line breaks), even when the trailing spaces are omitted.

**To Reproduce**
[RunKit example](https://runkit.com/superhawk610/marked-gfm)

**Expected behavior**
When `gfm` and `breaks` are enabled, the second example (soft line break) should not output a `<br />` tag.

```
foo
bar
```

should output

```
<p>foo\nbar</p>
```

**Comment by superhawk610** [comment]
Relevant GFM spec:
[Hard line breaks](https://github.github.com/gfm/#hard-line-breaks)
[Soft line breaks](https://github.github.com/gfm/#soft-line-breaks)

**Comment by styfle** [comment]
Yes this appears to be a bug.
I'm surprised these are not in our tests.

```js
function testOptions(opts) {
  var md632 = 'foo  \nbaz';
  var md633 = 'foo\\\nbaz';
  var md647 = 'foo\nbaz';
  var md648 = 'foo \n baz';
  console.log(opts);
  console.log(marked(md632, opts));
  console.log(marked(md633, opts));
  console.log(marked(md647, opts));
  console.log(marked(md648, opts));
  console.log('\n');
}

testOptions({gfm: true, breaks: true});
testOptions({gfm: true, breaks: false});
```

@joshbruce Any idea why [gfm.0.2.8.json](https://github.com/markedjs/marked/blob/master/test/specs/gfm/gfm.0.28.json) is missing these tests? How did you acquire this file?

**Comment by UziTech** [comment]
testing
this

**Comment by UziTech** [comment]
The "breaks" option was added to make the "gfm" option function like github (i.e. add `<br>` on single `\n`) https://github.com/markedjs/marked/issues/51

With the "breaks" option off it will follow the spec.

**Comment by UziTech** [comment]
@styfle [gfm.0.28.json](https://github.com/markedjs/marked/blob/master/test/specs/gfm/gfm.0.28.json) only has tests for things that are different between GFM 0.28 and CommonMark 0.28

The hard and soft line breaks are the same in both specs (even though github doesn't follow them)

**Comment by UziTech** [comment]
Looks like the real problem is that our [documentation](https://marked.js.org/#/USING_ADVANCED.md#options) for the "breaks" option is wrong.

**Comment by Feder1co5oave** [comment]
Agree with @UziTech.
How many of those [hard line-breaks](https://github.github.com/gfm/#hard-line-breaks) test cases do pass?

**Comment by UziTech** [comment]
according to the Common Mark spec tests 100% pass. And just testing manually 100% pass with `gfm: true, breaks: false`

https://github.com/markedjs/marked/blob/97be813c267b3d60a1bcef6f0b7ffa6014abc230/test/specs/commonmark/commonmark-spec.js#L53-L54
