### ISSUE TITLE
Test case gfm_code_hr_list is inconsistent

### ISSUE THREAD

**Issue by Feder1co5oave** [markedjs/marked#1386]
**Describe the bug**
[`test/new/gfm_code_hr_list.md`](https://raw.githubusercontent.com/markedjs/marked/master/test/new/gfm_code_hr_list.md) contains a test case for nested lists/blockquotes/code blocks.
I'm going to focus only on the first part of the test, for now.

```markdown
1. bar:

    > - one
        - two
            - three
            - four
            - five
```

Its rendering vary wildly among implementations:
1. [marked latest](https://marked.js.org/demo/?text=1.%20bar%3A%0A%20%20%20%20%3E%20-%20one%0A%20%20%20%20%20%20-%20two%0A%20%20%20%20%20%20%20%20%20%20%20%20-%20three%0A%20%20%20%20%20%20%20%20%20%20%20%20-%20four%0A%20%20%20%20%20%20%20%20%20%20%20%20-%20five%0A%0A%20&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20false%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20fase%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tables%22%3A%20true%2C%0A%20%22xhtml%22%3A%20false%0A%7D)
2. [commonmark latest](https://spec.commonmark.org/dingus/?text=1.%20bar%3A%0A%20%20%20%20%3E%20-%20one%0A%20%20%20%20%20%20-%20two%0A%20%20%20%20%20%20%20%20%20%20%20%20-%20three%0A%20%20%20%20%20%20%20%20%20%20%20%20-%20four%0A%20%20%20%20%20%20%20%20%20%20%20%20-%20five%0A%0A)
3. [others - babelmark2](https://johnmacfarlane.net/babelmark2/?normalize=1&text=1.+bar%3A%0A++++%3E+-+one%0A++++++-+two%0A++++++++++++-+three%0A++++++++++++-+four%0A++++++++++++-+five%0A%0A#results) -- likely outdated
4. [others - babelmark3](https://babelmark.github.io/?text=1.+bar%3A%0A++++%3E+-+one%0A++++++-+two%0A++++++++++++-+three%0A++++++++++++-+four%0A++++++++++++-+five%0A%0A)

I came across this because I was reorganizing the different standard (commonmark) - gfm - pedantic grammars, and this test easily fails whenever the `paragraph` rule gets changed.

What are we gonna do about this? Should we keep it there to be backward compatible? It clearly goes against commonmark. Should we drop it? Modify it to adhere to commonmark?

**Comment by styfle** [comment]
Nice find! Nested lists like this are always a pain.

I would vote for adhering to commonmark. We have been introducing lots of breaking changes in the last few months to comply with commonmar. If the standard specifies this behavior, we should follow it 👍 

/cc @UziTech @joshbruce

**Comment by UziTech** [comment]
This is fixed in the latest release
