### ISSUE TITLE
Italic inside parentheses break

### ISSUE THREAD

**Issue by james4388** [markedjs/marked#1393]
**Describe the bug**
`(_Hello world_)` should render (<em>Hello world</em>) but it not it leave the text as is
GIthub markdown render correctly (_Hello world_)

**To Reproduce**
(_Any text_)

**Expected behavior**
`(_Hello world_)` --> (<em>Hello world</em>)

**Comment by UziTech** [comment]
I think this is fixed in master. Just hasn't been released yet.

**Comment by styfle** [comment]
Confirmed, this is fixed in master. I'll get a release started in the next couple days.

**Comment by UziTech** [comment]
fixed in v0.6.0
