### ISSUE TITLE
BNF

### ISSUE THREAD

**Issue by Jedore** [markedjs/marked#1402]
Does marked support BNF, EBNF ?

**Comment by Jedore** [comment]
Yeah, I use highlight.js, but met a problem.
And I use https://cdnjs.cloudflare.com/ajax/libs/marked/0.5.2/marked.min.js in my Django template file
```js
let renderer = new marked.Renderer();
marked.setOptions({
    renderer: renderer,
    breaks: true,
    smartLists: true,
});
let html =  marked(text);
```
When I use BNF like
>\`\`\`bnf
name ::= identifier
\`\`\`

Marked converts above markdown string to html with class attributes like
```html
<pre><code class="language-bnf">name ::= identifier</code></pre>
```
but without `hljs` it seems to be invalid.
If set `langPrefix` to '', I got
```html
<pre><code class="bnf hljs nginx"><span class="hljs-attribute">name</span> ::= identifier</code></pre>
```
why ?
Then I try set `langPrefix` to default value with null markdown string
>\`\`\`bnf
\`\`\`

and I got
```html
<pre><code class="bnf hljs"></code></pre>
```
So I don't understand ... Thanks @UziTech

**Comment by UziTech** [comment]
> but without hljs it seems to be invalid.

What seems to be invalid, the HTML that is output by marked?

Whatever `hljs` does with the HTML is not controlled by marked. This might be a question for [highlight.js](https://github.com/highlightjs/highlight.js) instead.

**Comment by Jedore** [comment]
uh... You're right, I thought `hljs` is controlled by Marked.
Thanks.
