### ISSUE TITLE
toc

### ISSUE THREAD

**Issue by zoe-cjf** [markedjs/marked#1412]
how to set opthions  if i want to use toc

**Comment by UziTech** [comment]
Here are the available options: https://marked.js.org/#/USING_ADVANCED.md#options

There is no option for easily making a toc but you can make one manually by enabling `headerIds` and creating links at the top of the document.

**Comment by styfle** [comment]
Related issues that might have some additional solutions:

- #334
- #545
- #930
- #940

**Comment by UziTech** [comment]
closing in favor of #545
