### ISSUE TITLE
Image prefix possible?

### ISSUE THREAD

**Issue by jenstornell** [markedjs/marked#1419]
When adding an image `![Alt](image.png)` it outputs `<img src="image.png" alt="Alt">` but in my case the url does not look like that. It looks more like `https://example.com/api/images/path/to/page/image.png`.

I tried to use `baseUrl` without any luck.

```js
$('.preview').innerHTML = marked($('textarea').value, {
   baseUrl: 'test'
});
```

**Comment by UziTech** [comment]
`baseUrl` should work [demo](https://marked.js.org/demo/?outputType=html&text=!%5BAlt%5D(image.png)&options=%7B%0A%20%22baseUrl%22%3A%20%22https%3A%2F%2Fexample.com%2Fapi%2Fimages%2Fpath%2Fto%2Fpage%2F%22%0A%7D)

```js
marked('![Alt](image.png)', {
   baseUrl: 'https://example.com/api/images/path/to/page/'
});

// <p><img src="https://example.com/api/images/path/to/page/image.png" alt="Alt"></p>
```

**Comment by jenstornell** [comment]
Alright. I've made more tests and it does not prefix anything if I just add `test` to `baseUrl`. It needs to be a real url that starts with `http://`, `https://` or `//`. Case closed.

**Comment by nijikokun** [comment]
Note, this will apply to **all** links, not just images.
