### ISSUE TITLE
Add --test option in man page

### ISSUE THREAD

**Issue by roipoussiere** [markedjs/marked#1423]
**Describe the bug**
The `--test` CLI option is not displayed in the man page.

**To Reproduce**

```
man marked
```

This appends in last version and simple to verify by looking at the [man](https://github.com/markedjs/marked/blob/master/man/marked.1) [files](https://github.com/markedjs/marked/blob/master/man/marked.1.txt).

**Expected behavior**

The `--test` CLI option should be displayed in the man page, since it is [a valid option in the marked binary](https://github.com/markedjs/marked/blob/master/bin/marked#L80).

**Comment by x13machine** [comment]
I think, this should be closed

**Comment by styfle** [comment]
Fixed in #1442
