### ISSUE TITLE
Expose cleanUrl for use in custom Renderer

### ISSUE THREAD

**Issue by nalroff** [markedjs/marked#1427]
**Describe the feature**
Just what the title says. Access to `cleanUrl` for use in a custom Renderer.

**Why is this feature necessary?**
I'd like to be able to use the `cleanUrl` function in a custom Renderer instance.

**Describe alternatives you've considered**
Copying the `cleanUrl` function into my own project. Rolling my own.

**Comment by Feder1co5oave** [comment]
It should be easily possible by making it a memeber of `marked.Renderer`, then it would be accessible from the prototype whenever you extend it.

**Comment by styfle** [comment]
We have discussed removing sanitization in #1232

So it's probably best to have your own.

**Comment by nalroff** [comment]
> We have discussed removing sanitization in #1232
> 
> So it's probably best to have your own implementation.

Didn't see that issue. Feel free to close this one if that's the case. I ended up using the default Renderer anyway with a simple replace after the call. I wanted to be able to inject Angular's `routerLink` in place of `href`. This code will probably evolve, but here's what I'm using so far (Typescript; untested):

```ts
const renderer = new marked.Renderer();
const normalLinkRenderer = renderer.link;
renderer.link = (href, title, text) => {
  if (!href || /^(?:[a-z]+:)?\/\//i.test(href)) {
    return normalLinkRenderer(href, title, text);
  } else {
    return normalLinkRenderer(href, title, text).replace(/href="/i, 'routerLink="');
  }
};
```
