### ISSUE TITLE
blockquote rendering  not correctly

### ISSUE THREAD

**Issue by wmgselfblog** [markedjs/marked#1433]
example
md:
![](http://pic.wmgblog.pw/20190304203544.png)

I don't know where I used it incorrectly.
```javascript
const renderMD = new marked.Renderer()

marked.setOptions({
  renderer: renderMD,
  gfm: true,
  tables: true,
  breaks: false,
  pedantic: false,
  sanitize: false,
  smartLists: true,
  smartypants: false
})

marked('# hhh\n>t ss \n`aaaa`\n```java\n111\n```')

```

The result I want is
```html
<h1 id="hhh">hhh</h1>
<blockquote>
<p>t ss 
<code>aaaa</code></p>
</blockquote>
<pre><code class="language-java">111</code></pre>
```
![](http://pic.wmgblog.pw/20190304204015.png)

but Render result is
```html
<h1 id="hhh">hhh</h1>
<blockquote>
<p>t ss 
<code>aaaa</code></p>
<pre><code class="language-java">111</code></pre>
</blockquote>
```
![](http://pic.wmgblog.pw/20190304203238.png)

**Comment by wmgselfblog** [comment]
How can I do it?

**Comment by UziTech** [comment]
add another blank line after the block quote

[demo](https://marked.js.org/demo/?text=%23%20hhh%0A%3Et%20ss%20%0A%0A%60aaaa%60%0A%60%60%60java%0A111%0A%60%60%60&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tables%22%3A%20true%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master)

**Comment by wmgselfblog** [comment]
thanks
