### ISSUE TITLE
Get 'alt' tag when extending the renderer for image elements

### ISSUE THREAD

**Issue by neptunian** [markedjs/marked#1437]
**Describe the feature**

Currently only "ref", "title", and "text" is returned.  I would like access to the "alt" attribute. Or better yet all the attributes and the element itself in case i don't want to make any changes to it.

**Why is this feature necessary?**
Need the alt tag

**Describe alternatives you've considered**
None

**Comment by UziTech** [comment]
the `text` is the alt text

**Comment by neptunian** [comment]
Thanks.  In that case I'll PR to update the types to be called "alt" and not "text".
