### ISSUE TITLE
What would be the correct way to make links open in external window?

### ISSUE THREAD

**Issue by katowulf** [markedjs/marked#144]
Hi gents,

I'm attempting to coerce marked (great lib! thanks for sharing!) into making all links in the markdown content open in external windows.

What would be best practice for this? Can I use the `lexer` to manipulate the tokens in some way that would accomplish this before they go into the parser?

Cheers,

**Comment by mrcoles** [comment]
Thanks for the code block @icoxfog417 — I looked it over a little more and also saw an example from the docs for [overriding renderer methods](https://github.com/chjj/marked#overriding-renderer-methods), and the code can more simply be written as such:

```javascript
var renderer = new marked.Renderer();
renderer.link = function(href, title, text) {
    var link = marked.Renderer.prototype.link.call(this, href, title, text);
    return link.replace("<a","<a target='_blank' ");
};

marked.setOptions({
    renderer: renderer
});
```
