### ISSUE TITLE
change src to data-src

### ISSUE THREAD

**Issue by jerryc127** [markedjs/marked#1443]
**Marked version:**
new

**Markdown flavor:** Markdown.pl|CommonMark|GitHub Flavored Markdown|n/a

 

## Expectation

**CommonMark Demo:** [demo](https://spec.commonmark.org/dingus/)

## Result

**Marked Demo:** [demo](https://marked.js.org/demo/)

## What was attempted

I want to use the lozad function.
so i change the code
![image](https://user-images.githubusercontent.com/16351105/54087958-7bee9e80-4393-11e9-993b-cfbba17da7b3.png)

but when i run it, it show that
![image](https://user-images.githubusercontent.com/16351105/54087975-b22c1e00-4393-11e9-91b6-b0e1195a3625.png)

how to solve?

**Comment by Hideer** [comment]
@jerryc127 Have you solved it

**Comment by Hideer** [comment]
@jerryc127 I directly modified the source code, solved

**Comment by UziTech** [comment]
You can find how to override the renderer in the [docs](https://marked.js.org/#/USING_PRO.md#renderer)
