### ISSUE TITLE
'Url' or 'href' should be also encoded when meeting non-normative characters

### ISSUE THREAD

**Issue by Maledong** [markedjs/marked#1450]
Take this demo：

Mixed with [Non-Lartin Characters in Url](https://marked.js.org/demo/?text=http%3A%2F%2Fwww.baidu.com.%0A%0Ahttp%3A%2F%2Fwww.baidu.com%E3%80%82%0A%0Ahttp%3A%2F%2Fwww.baidu.com%E6%88%91%E3%80%82%0A%0Amailto%3Aabc%40abc.com%E3%80%82%0A%0Amailto%3Aabc%40abc.com%E6%88%91%E3%80%82&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tables%22%3A%20true%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master).

It seems for 'mailto:……', it's right that we don't allow any characters except Lartins (26 English characters), however, this is wrong in Url or href.

Ref：https://github.com/nodejs/nodejs.org/issues/1612

**Comment by UziTech** [comment]
looks like GitHub renders it the same way marked does:

http://www.baidu.com.

http://www.baidu.com。

http://www.baidu.com我。

mailto:abc@abc.com。

mailto:abc@abc.com我。

**Comment by UziTech** [comment]
Where does it say that links should only include latin characters?

**Comment by Maledong** [comment]
@UziTech：What makes me feel puzzled is that for 'mailto', “。”and “我” are seperated from the English characters, compared with this, the url or href link（such as http……）, you now can see “我” and “。” are a part of them. It should be the same as what we see in "mailto".

So I guess, whether url, href or mailto should only allow English characters (or lartain characters)?

**Comment by UziTech** [comment]
according to the [commonmark spec](https://spec.commonmark.org/0.28/#absolute-uri):

> An absolute URI, for these purposes, consists of a scheme followed by a colon (:) followed by zero or more characters other than ASCII whitespace and control characters, <, and >. If the URI includes these characters, they must be percent-encoded (e.g. %20 for a space).

and spec for [email](https://spec.commonmark.org/0.28/#email-autolink)

> An email address, for these purposes, is anything that matches the non-normative regex from the HTML5 spec:
> 
> ```
> /^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?
> (?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$/
> ```

**Comment by UziTech** [comment]
also according to [gfm spec](https://github.github.com/gfm/#extended-autolink-path-validation):

> Trailing punctuation (specifically, `?`, `!`, `.`, `,`, `:`, `*`, `_`, and `~`) will not be considered part of the autolink

**Comment by Maledong** [comment]
OK, @UziTech, thanks!

>An absolute URI, for these purposes, consists of a scheme followed by a colon (:) followed by zero or more characters other than ASCII whitespace and control characters, <, and >. If the URI includes 
these characters, they must be percent-encoded (e.g. %20 for a space).

Then it seems all the Chinese/English characters should be percent-encoded, but now they haven't encoded yet, and I'll change my topic if you are OK with this.

What I mean is:  If you click the demo link I posted in my 1st post, you'll find that the Chinese characters aren't encoded yet (maybe by using `encodeURI` or some function?)

Take this as an example：

>http://www.baidu.com我。

【Expected】
"http://www.baidu.com%E6%88%91%E3%80%82" 
【Actual】
http://www.baidu.com我.

So "我" should be also encoded :)

**Comment by Maledong** [comment]
Should we also use `encodeURI` or `encodeURIComponent` to the non-normative characters like Chinese ones, even if they are in the URL or href？I see that in the parameters we should use it to encode and decode through javascript. If that's OK, I'll change my topic as well.

I mean:

http://www.baidu.com/我

should be converted to："http://www.baidu.com/%E6%88%91"

And take this:
http://www.baidu.com?a=我

should be converted to:
"http://www.baidu.com?a=%E6%88%91"

What do you think of this?

**Comment by Maledong** [comment]
My mistake, I didn't make it clear to you, now I've changed my topic to this: 'Url' or 'href' should be also encoded when meeting non-normative characters. :)

**Comment by UziTech** [comment]
According to the spec only whitespace, control characters, <, and > need to be percent encoding.

**Comment by Maledong** [comment]
Interesting question, feeling curious....

I'm looking at the RFC Resource, it says……

>Octets MUST be encoded if they have no corresponding graphic
   character within the US-ASCII coded character set, if the use of the
   corresponding character is unsafe, or if the corresponding character
   is reserved for some other interpretation within the particular URL
   scheme.

>No corresponding graphic US-ASCII:

>   URLs are written only with the graphic printable characters of the
   US-ASCII coded character set. The octets 80-FF hexadecimal are not
   used in US-ASCII, and the octets 00-1F and 7F hexadecimal represent
   control characters; these must be encoded.

[RFC 1738](https://www.ietf.org/rfc/rfc1738.txt). So which is the standard document for the URL or Href？

**Comment by UziTech** [comment]
We do run urls through encodeURI. It looks like chrome automatically decodes the url when displaying it even though it is encoded

**Comment by Maledong** [comment]
Really？I'll check it with other browsers such as IE or Edge……This is strange....

**Comment by UziTech** [comment]
You can inspect the link to see it encoded

![image](https://user-images.githubusercontent.com/97994/54404978-1e17ca80-46a3-11e9-94a9-0116e550e29b.png)

**Comment by Maledong** [comment]
Ah ha……Thanks!
I'll close this, thanks for your patience!
