### ISSUE TITLE
<br> - bug

### ISSUE THREAD

**Issue by semiromid** [markedjs/marked#1455]
**Describe the bug**

Instead  `<br>` output last element as `\`

**To Reproduce**

**input**
```
test
\
\
\
\
# Header
```
**output**
```
<p>test<br><br><br><br>\</p>
<h1 id="Header">Header</h1>
```
\
\
\
\
**Expected behavior**

**input**
```
test
\
\
\
\
# Header
```
**output**
```
<p>test<br><br><br><br><br></p>
<h1 id="Header">Header</h1>
```

**Comment by UziTech** [comment]
seems to be what is supposed to happen according to commonmark.

[commonmark demo](https://spec.commonmark.org/dingus/?text=test%0A%5C%0A%5C%0A%5C%0A%5C%0A%23%20Header)
[marked demo](https://marked.js.org/demo/?outputType=html&text=test%0A%5C%0A%5C%0A%5C%0A%5C%0A%23%20Header&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tables%22%3A%20true%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master)

**Comment by UziTech** [comment]
If you actually want a paragraph to end on a `<br>` you will have to just write `<br>`

```
test
\
\
\
<br>
# Header
```

**Comment by semiromid** [comment]
@UziTech  Yeah! :(  You are right. I Will be write regular expressions for me. (

Thank you very much for your answer and it library.

Best regards,

**Comment by semiromid** [comment]
@UziTech 
I use option: `sanitize: true`, but thank you for tip.

**Comment by semiromid** [comment]
> If you actually want a paragraph to end on a `<br>` you will have to just write `<br>`
> 
> ```
> test
> \
> \
> \
> <br>
> # Header
> ```
@UziTech 
I use option: `sanitize: true`, but thank you for tip.
