### ISSUE TITLE
baseUrl with relative prefix not working as expected.

### ISSUE THREAD

**Issue by mjhenkes** [markedjs/marked#1466]
**Describe the bug**
For usage in github pages I'd like to use the baseUrl option to add a prefix of the project name for relative links. For instance with a github pages site like ``` matt.github.io/derp``` with ```derp``` being the project name. I'd like relative links to change from ```/link``` to ```/derp/link```.

Marked options
```javascript
const options = {
    baseUrl: '/derp/',
}
```

Markdown
```markdown
![alt text](/favicon.ico "relative")'
```
Output html
```html
<p><img src="/derp/favicon.ico" alt="alt text" title="relative"></p>
```
What is actually happening is:
```html
<p><img src="/derp//favicon.ico" alt="alt text" title="relative"></p>
```

Maybe it is as simple as not inverting rtrim here:
https://github.com/markedjs/marked/blob/master/lib/marked.js#L1417

**To Reproduce**
This code sandbox should show the issue. Check the console
https://codesandbox.io/s/9ql03o5114

I was able to reproduce this in both 0.5.0 and 0.6.2.

**Expected behavior**
I expect html output to look like this:
```html
<p><img src="/derp/favicon.ico" alt="alt text" title="relative"></p>
```

**Comment by UziTech** [comment]
could you remove the slash from the url?

```md
![alt text](favicon.ico "relative")
```

**Comment by mjhenkes** [comment]
Yeah, I think it would work as long as you never use the slash at the start of relative route. Do you know if there is a standard expectation on how to define the relative routes? Is the slash frowned upon? I noticed in my demo it would display the favicon with or without the slash.

**Comment by UziTech** [comment]
I believe most servers treat consecutive slashes as a single slash so it shouldn't affect anything.

**Comment by mjhenkes** [comment]
Good enough for me. Thanks for the response!

**Comment by VitaliyR** [comment]
@UziTech not if the slashes are at the beginning of the line. 

E.g.: 
http://test.com//something/else.jpg -> http://something/else.jpg

**Comment by UziTech** [comment]
@VitaliyR Where does `http://test.com//something/else.jpg` change to `http://something/else.jpg`?

**Comment by VitaliyR** [comment]
@UziTech it would not change if you will just request the website with this URL (like in address bar). But it will change if you will have a resource pointing to such url (e.g. img tag with src containing this url)

**Comment by UziTech** [comment]
@VitaliyR It seems to work for me. If I enter `http://test.com//something/else.jpg` into the address bar it goes to `http://test.com//something/else.jpg` which shows the same content as `http://test.com/something/else.jpg`

**Comment by VitaliyR** [comment]
@UziTech please, try to use it in the actual HTML, not in the address bar. Like having a page with img tag with this url

**Comment by UziTech** [comment]
are you talking about `<img src="//something/else.jpg" />` going to `http://something/else.jpg`?

that doesn't seems to be the issue. marked only adds the extra slash after the base url so it will never starts with two slashes unless two slashes are specified without a base url like `![alt text](//favicon.ico "relative")`

**Comment by VitaliyR** [comment]
```js
const markdown = '![An Image](/images/pic01.jpg)';
const html = marked(markdown, { baseUrl: '/' }); // would be url with two slashes here
```

**Comment by UziTech** [comment]
I see. I guess in that case we should treat `baseUrl: '/'` the same as `baseUrl: null`

**Comment by VitaliyR** [comment]
@UziTech Yeah, great! And also baseUrls could be like '/something/' (please, notice the last slash). I think it would make the issue as well (due to concatenating `baseUrl + url`, not sure - not checked this one)

**Comment by UziTech** [comment]
Ya in that case `![An Image](/images/pic01.jpg)` would be `/something//images/pic01.jpg` which the browser interprets the same as `/something/images/pic01.jpg`.

I guess we could remove the extra slash.

@VitaliyR If you want to create a PR that fixes it I would be happy to review it.

**Comment by VitaliyR** [comment]
@UziTech #1513
