### ISSUE TITLE
Heading immediately following a table is being rendered in the table element

### ISSUE THREAD

**Issue by Thomas-James-Rose** [markedjs/marked#1467]
**Describe the bug**
I have some Markdown that contains a table immediately followed by a heading on a new line. The subsequent heading is being rendered as part of the table. 

**To Reproduce**
Steps to reproduce the behaviour:

Markdown Sample:

```markdown
| Heading | Description |
| ----------- | ----- |
| Heading 1 | Some description | 
| Heading 2 | Some other description |
## A Title that is not a part of the table
```

HTML output:

```html
<table>
  <thead>
    <tr>
      <th>Heading</th>
      <th>Description</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Heading 1</td>
      <td>Some description</td>
    </tr>
    <tr>
      <td>Heading 2</td>
      <td>Some other description</td>
    </tr>
    <tr>
      <td>## A title that is not a part of the table</td>
      <td></td>
    </tr>
  </tbody>
</table>
```

Demo:
[Marked Demo](https://marked.js.org/demo/?text=%7C%20Heading%20%7C%20Description%20%7C%0A%7C%20-----------%20%7C%20-----%20%7C%0A%7C%20Heading%201%20%7C%20Some%20description%20%7C%20%0A%7C%20Heading%202%20%7C%20Some%20other%20description%20%7C%0A%23%23%20A%20title%20that%20is%20not%20a%20part%20of%20the%20table&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tables%22%3A%20true%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master)

**Expected behaviour**
The heading should be rendered separately from the table.

**Comment by UziTech** [comment]
You should add a blank line between then

**Comment by Thomas-James-Rose** [comment]
A usable workaround in a lot of cases but, unfortunately, in our use case the Markdown being parsed is both authored by other people and there is a high volume of it so it is not really viable for us to update and fix things in this way.

**Comment by UziTech** [comment]
You could change the markdown when you parse it

```
const html = marked(markdown.replace(/[^\n]\n#/g, '\n\n#'));
```

This is very low priority for us since there is an easy way to fix it.

PRs are welcome 😁

**Comment by Thomas-James-Rose** [comment]
Thanks! 🙂  I'll try find some time to give it a look. I've noticed a similar issue with lists.

**Comment by Thomas-James-Rose** [comment]
^ I've raised a PR to address this issue.

**Comment by calculuschild** [comment]
Commenting here to note we are running into the same issue but with `<hr>` immediately after tables. GFM spec says this shouldn't happen.

**Comment by UziTech** [comment]
@calculuschild PRs are always welcome. You can look at #1469 as a starting point.
