### ISSUE TITLE
*** behaves different than ___ for links

### ISSUE THREAD

**Issue by donaldpipowitch** [markedjs/marked#1468]
**Describe the bug**
Afaik `***` and `___` should always behave in the same way, but they work differently for links

**To Reproduce**

https://runkit.com/embed/stq0dwxnnsk0

```
var marked = require("marked"); // 0.6.1

console.log(marked(`***[link](https://google.com)***`)); // logs: "<p><strong>*<a href=\"https://google.com\">link</a>*</strong></p>\n"
console.log(marked(`___[link](https://google.com)___`));  // logs: "<p><strong><em><a href=\"https://google.com\">link</a></em></strong></p>\n"
```

**Expected behavior**

``marked(`***[link](https://google.com)***`)`` should return `"<p><strong><em><a href=\"https://google.com\">link</a></em></strong></p>\n"`

**Comment by UziTech** [comment]
Looks like this is fixed in the latest version
