### ISSUE TITLE
Some failed commonmark examples

### ISSUE THREAD

**Issue by Jocs** [markedjs/marked#1474]
We forked a copy of marked code in [Mark Text](https://github.com/marktext/marktext/tree/develop/src/muya/lib/parser/marked) in 2017. After every time marked release a new version, we will update the code of our fork, and we also fix some examples that failed through the [commonmark](https://spec.commonmark.org/0.29/) test. You can see from this [file](https://github.com/marktext/marktext/blob/develop/test/specs/commonMark/compare.marked.md). Some of the issues we fix, if you like, we also hope to help marked to fix these issues.
Finally, thank you again for your unselfish maintenance and return marked to life.

**Comment by UziTech** [comment]
PRs are always welcome 😃👍

**Comment by calculuschild** [comment]
@Jocs is Marked.js still failing these tests for you? There have been a lot of updates in the last two years.

If there are still some cases that you have solved and Marked.js hasn't, we would love your help in fixing them with a PR!

**Comment by Jocs** [comment]
Marked.js has updated a lot, I think you can close this issue now.
