### ISSUE TITLE
I can't parse the list. What's the reason? 

### ISSUE THREAD

**Issue by yuelinghunyu** [markedjs/marked#1479]
| Tables        | Are           | Cool  |
| ------------- |:-------------:| -----:|
| col 3 is      | right-aligned | $1600 |
| col 2 is      | centered      |   $12 |
| zebra stripes | are neat      |    $1 |，

can't parse this， it would parse  “| Tables | Are | Cool | | ------------- |:-------------:| -----:| | col 3 is | right-aligned | $1600 | | col 2 is | centered | $12 | | zebra stripes | are neat | $1 |”

**Comment by UziTech** [comment]
Can you provide the code in a demo? https://marked.js.org/demo/

After entering your code, right click "Permalink" and copy link address, then paste it here.

**Comment by yuelinghunyu** [comment]
thanks，It has been settled.
