### ISSUE TITLE
Add in-side html render

### ISSUE THREAD

**Issue by jinfagang** [markedjs/marked#1481]
Somtimes, I have mark down text which has some html tag inside it:

for example, in order to make github readme image center, I have to using a wrapper:

```
<p align='center'>
<img src='https://s2.ax1x.com/2019/04/23/EAsL2q.md.png'>
</p>
```

It will not render as text:

<p align='center'>
<img src='https://s2.ax1x.com/2019/04/23/EAsL2q.md.png'>
</p>

Does marked.js support this? If so, what options should I open? I can not make it do by default

**Comment by UziTech** [comment]
It will not render as text by default because html tags are valid markdown.

If you are looking to sanitize html tags you can do something like this: https://github.com/markedjs/marked/issues/1232#issuecomment-470704335

**Comment by jinfagang** [comment]
Here is a error case:

![image](https://user-images.githubusercontent.com/21303438/56566817-21796c80-65e6-11e9-846a-389a838de4a2.png)

[link](http://manaai.cn/aicodes_detail3.html?id=28)

As you can see, the html tag were not properly parsed (or maybe not properly showing)

**Comment by UziTech** [comment]
Do you want the html to show as text? or are you trying to let it be html?

**Comment by jinfagang** [comment]
@UziTech I wanna it showing as ....... seems........... formula? It is a wrapper of a fumula which inserted into markdown, But I don't want to show it as text of course.

**Comment by UziTech** [comment]
This demo seems to work just fine. HTML input will stay HTML.

[demo](https://marked.js.org/demo/?text=%3Cp%20align%3D%27center%27%3E%0A%3Cimg%20src%3D%27https%3A%2F%2Fs2.ax1x.com%2F2019%2F04%2F23%2FEAsL2q.md.png%27%3E%0A%3C%2Fp%3E&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tables%22%3A%20true%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master)

**Comment by jinfagang** [comment]
@UziTech  How about this one:


<a href="https://www.codecogs.com/eqnedit.php?latex=C_d&space;=&space;k_jJ_t(d(t))&space;+&space;k_tT&space;+&space;k_dd_1^2" target="_blank"><img src="https://latex.codecogs.com/svg.latex?C_d&space;=&space;k_jJ_t(d(t))&space;+&space;k_tT&space;+&space;k_dd_1^2" title="C_d = k_jJ_t(d(t)) + k_tT + k_dd_1^2" /></a>

**Comment by jinfagang** [comment]
<a href="https://www.codecogs.com/eqnedit.php?latex=C_d&space;=&space;k_jJ_t(d(t))&space;+&space;k_tT&space;+&space;k_dd_1^2" target="_blank"><img src="https://latex.codecogs.com/svg.latex?C_d&space;=&space;k_jJ_t(d(t))&space;+&space;k_tT&space;+&space;k_dd_1^2" title="C_d = k_jJ_t(d(t)) + k_tT + k_dd_1^2" /></a>
