### ISSUE TITLE
Add documentation for Slugger

### ISSUE THREAD

**Issue by ad-si** [markedjs/marked#1484]
Currently the heading token looks like this

```js
{
  type: 'heading', 
  depth: 3, 
  text: 'Chapter 7',
}
```

I think it should also contain the heading id as it is not easy to generate from the text (https://github.com/markedjs/marked/blob/master/lib/marked.js#L1312).

```js
{
  type: 'heading', 
  depth: 3, 
  text: 'Chapter 7',
  id: 'chapter-7',
}
```

An alternative would be to expose the `slug` function via the marked module.

**Comment by UziTech** [comment]
the slug function is exposed https://github.com/markedjs/marked/blob/5d727cb020fd9c748b228066f44f8a34828cc17b/lib/marked.js#L1685

**Comment by UziTech** [comment]
You can get the slug function from

```
const slugger = new marked.Slugger();
slugger.slug(...)
```

**Comment by ad-si** [comment]
Haha, what the heck. I somehow overlooked it in the code. 🙈
I guess when you don't expect to see something you don't see it even when it's there 😅.

Then the questions remains if it should be part of the token already 🤔

**Comment by UziTech** [comment]
I don't think computed properties should be part of the AST

**Comment by ad-si** [comment]
When you say it like this, I guess you're right.
Then let's change the issue to "Add documentation for Slugger"

**Comment by UziTech** [comment]
PRs are welcome

**Comment by calculuschild** [comment]
@UziTech The documentation already talks about the slugger. Do we need to add more info or clarify it somehow? Otherwise we can probably close this issue.

**Comment by UziTech** [comment]
The documentation should say something about `marked.Slugger` being public and show hoe to use it.
