### ISSUE TITLE
Better solution for TOC

### ISSUE THREAD

**Issue by ibreathebsb** [markedjs/marked#1489]
Hi guys!

I have been using `marked` for an doc site recently, `marked` is a good library but when I realize that I need a TOC, it does not work very well.  There are existing solutions like  #545 ,while reading `marked` docs, I found a better(👀maybe?) solution, that is:

### **marked.lexer**

for example, suppose we have the following markdown text

```markdown

# A
> please ignore me 
## B
# C
## D
```

then we use  `marked.lexer(markdownText)` to get the tokens:

```js
[
  {
    "type": "heading",
    "depth": 1,
    "text": "A"
  },
  {
    "type": "blockquote_start"
  },
  {
    "type": "paragraph",
    "text": "please ignore me"
  },
  {
    "type": "blockquote_end"
  },
  {
    "type": "heading",
    "depth": 2,
    "text": "B"
  },
  {
    "type": "heading",
    "depth": 1,
    "text": "C"
  },
  {
    "type": "heading",
    "depth": 2,
    "text": "D"
  }
]
```

wow! that's all we need, right? now we can filter these headings and do whatever we want!

```js

//  tokens is the result returned by marked.lexer()
const headings = tokens.filter(token => token.type === 'heading')
//
DO_WHATEVER_U_WANT(headings)

```

👏  That's all, wish this could help, thanks!

**Comment by UziTech** [comment]
This would probably be better as a comment on #545 

We are trying to consolidate the issues so I am going to close this issue.
