### ISSUE TITLE
remove \n that exists after each closed tag in the rendered html

### ISSUE THREAD

**Issue by oussama-he** [markedjs/marked#1490]
**Marked version: 0.6.2**

**Markdown flavor:** GitHub Flavored Markdown
I would ask if there is an option or a way to remove the `\n` after closing tags in the rendered result.

**Comment by UziTech** [comment]
You would need to override the renderer. You can see how to do that in the [docs](https://marked.js.org/#/USING_PRO.md#renderer).

**Comment by UziTech** [comment]
I'm going to close this to keep the issues clean. If you still think this is an issue we can reopen it.
