### ISSUE TITLE
Uncaught TypeError: Cannot parse `>a\n>>b`

### ISSUE THREAD

**Issue by xovel** [markedjs/marked#1494]
```
>a
>>b
```
cause an error `Uncaught TypeError: Cannot read property 'type' of undefined`.

See: [here](https://marked.js.org/demo/?outputType=html&text=%3Ea%0A%3E%3Eb&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tables%22%3A%20true%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master>)

It works fine in `v0.6.2`.

**Comment by UziTech** [comment]
This is fixed in PR #1495
