### ISSUE TITLE
0.6.1 -> 0.6.2 broke `breaks` option (Regression)

### ISSUE THREAD

**Issue by fdietze** [markedjs/marked#1505]
**Describe the bug**
After updating from `0.6.1` to `0.6.2`, I noticed that my linebreaks got lost.

**To Reproduce**
`0.6.1` with option `breaks` enabled:
```
A
B
```
output:
```
<p>A<br>B</p>
```
(which is correct)

with `0.6.2` it becomes:
```
<p>A
B</p>
```

**Comment by UziTech** [comment]
confirmed:

[v0.6.2 demo](https://marked.js.org/demo/?outputType=html&text=A%0AB&options=%7B%0A%20%22breaks%22%3A%20true%2C%0A%20%22gfm%22%3A%20true%0A%7D&version=0.6.2)
[v0.6.1 demo](https://marked.js.org/demo/?outputType=html&text=A%0AB&options=%7B%0A%20%22breaks%22%3A%20true%2C%0A%20%22gfm%22%3A%20true%0A%7D&version=0.6.1)

**Comment by UziTech** [comment]
looks like it is #1460 that broke this. I will try to find a solution for both to work.

**Comment by UziTech** [comment]
v0.6.3 fixes this [demo](https://marked.js.org/demo/?outputType=html&text=A%0AB&options=%7B%0A%20%22breaks%22%3A%20true%2C%0A%20%22gfm%22%3A%20true%0A%7D&version=0.6.3)
