### ISSUE TITLE
allow CommonMark uncompliant mixing of Markdown in HTML blocks

### ISSUE THREAD

**Issue by NattyNarwhal** [markedjs/marked#1514]
**What pain point are you perceiving?.**

The change to >=0.4 significantly broke expectations for me. Before PR #1135, it was easy to do say, `<p class="foo">*bar*</p>` or indented HTML (for blocks of `<div>`) and have it do as a user, what I expect it to. However, the CommonMark behaviour introduced is unintuitive and it took be a while to figure out what was happening. For me, it's a regression.
 
**Describe the solution you'd like**

Some option to revert to the 0.3.x behaviour. I don't care about CommonMark compliance, and would rather mix markup freely.

**Comment by UziTech** [comment]
Every change breaks someone's [workflow](https://xkcd.com/1172/) 😄

You can pin marked to v0.3.19 to get the old behavior

**Comment by pyromanci** [comment]
There is a solution for this, but needs you do some extra work. That is to override the html() function of the Renderer. This is what I did for div tags. 

```
const _renderer = new marked.Renderer();
				
_renderer.html = function(html) {
	if(_.startsWith(_.trim(html), '<div') && _.endsWith(_.trim(html), '</div>')){
		const openTag = html.substring(0, html.indexOf('>')+1);
		html = html.substring(html.indexOf('>')+1);
		html = html.substring(0, html.lastIndexOf('</div>'));
		return `${openTag} ${marked(html)} </div>`;
	}
	return html;
}
```
