### ISSUE TITLE
Issue: Markdown content from API not rendering

### ISSUE THREAD

**Issue by louiemiranda** [markedjs/marked#1517]
**Describe the bug**
Our team is testing the markdown via API content, however when it is being retrieved via API. It is not being rendered properly by markedjs.

**To Reproduce**
Please use the following editor...

https://stackblitz.com/edit/angular-markdown-directive-jlxm?file=app%2Fapp.component.html

**Expected behavior**
It should render the markdown content from API.

**Comment by UziTech** [comment]
It looks like the markdown being passed to marked in `/app/marked.directive.ts` has the new lines (`\n`) removed.

```js
marked("# header - list item");
```

is parsed very differently then

```js
marked("# header \n\n- list item");
```

**Comment by UziTech** [comment]
I'm going to close this to keep the issues clean. If you still think this is an issue we can reopen it.
