### ISSUE TITLE
Multiple HTML blocks 

### ISSUE THREAD

**Issue by horosgrisa** [markedjs/marked#1523]
**Describe the bug**
Raw HTML with spaces generate multiple lexer html blocks

**To Reproduce**
Go to [online edior](https://marked.js.org/demo/?outputType=lexer&text=%3Cdl%3E%0A%20%20%3Cdt%3EDefinition%20list%3C%2Fdt%3E%0A%20%20%3Cdd%3EIs%20something%20people%20use%20sometimes.%3C%2Fdd%3E%0A%0A%20%20%3Cdt%3EMarkdown%20in%20HTML%3C%2Fdt%3E%0A%20%20%3Cdd%3EDoes%20*not*%20work%20**very**%20well.%20Use%20HTML%20%3Cem%3Etags%3C%2Fem%3E.%3C%2Fdd%3E%0A%3C%2Fdl%3E%0A&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master)

In right part you can see 2 lexer blocks with type `html`

**Expected behavior**
One single `html` block

**Comment by UziTech** [comment]
According to the CommonMark [HTML Blocks spec](https://spec.commonmark.org/0.29/#html-blocks) an html block ends on a new line so you can have markdown inside an html block if it is preceded by a blank line ([demo](https://marked.js.org/demo/?text=%3Cdl%3E%0A%20%20%3Cdt%3EDefinition%20list%3C%2Fdt%3E%0A%20%20%3Cdd%3EIs%20something%20people%20use%20sometimes.%3C%2Fdd%3E%0A%0A%20%20**test**%0A%0A%20%20%3Cdt%3EMarkdown%20in%20HTML%3C%2Fdt%3E%0A%20%20%3Cdd%3EDoes%20*not*%20work%20**very**%20well.%20Use%20HTML%20%3Cem%3Etags%3C%2Fem%3E.%3C%2Fdd%3E%0A%3C%2Fdl%3E%0A&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master)).

Even CommonMark shows that markdown as having two html blocks in their AST (Go to this [demo](https://spec.commonmark.org/dingus/?text=%3Cdl%3E%0A%20%20%3Cdt%3EDefinition%20list%3C%2Fdt%3E%0A%20%20%3Cdd%3EIs%20something%20people%20use%20sometimes.%3C%2Fdd%3E%0A%0A%20%20%3Cdt%3EMarkdown%20in%20HTML%3C%2Fdt%3E%0A%20%20%3Cdd%3EDoes%20*not*%20work%20**very**%20well.%20Use%20HTML%20%3Cem%3Etags%3C%2Fem%3E.%3C%2Fdd%3E%0A%3C%2Fdl%3E%0A) and click on AST. There are two html blocks next to each other.)

**Comment by horosgrisa** [comment]
@UziTech Thanks. I forgot about this use case.
