### ISSUE TITLE
`&` in a url query gets escaped and re-written to `&amp;`

### ISSUE THREAD

**Issue by zeusdeux** [markedjs/marked#1525]
**Describe the bug**
`&` in the query section of a URI gets escaped and re-written to `&amp;` thus breaking the link. 

To be very honest, I am not quite sure this is a bug since `commonmark.js dingus` produces the same result. But, for e.g., GitHub doesn't escape `&`.

More of a question around why and how to handle the change in semantics introduced by the escaping of `&`.

**To Reproduce**
Steps to reproduce the behavior: (both produce the same output so this is more for ease of discovery)

1. [Marked Demo](https://marked.js.org/demo/?outputType=html&text=%5Bsome%20link%5D(https%3A%2F%2Fmudit.xyz%3Fa%3D1%26b%3D2)&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master)
2. [CommonMark Demo](https://spec.commonmark.org/dingus/?text=%5Bsome%20link%5D(https%3A%2F%2Fmudit.xyz%3Fa%3D1%26b%3D2))

**Expected behavior**
`&` in query section of an URI should not be escaped as it changes the semantics of the query params.

**Comment by UziTech** [comment]
> GitHub doesn't escape &.

I'm not sure that is the case. Even though the html output from marked and commonmark has `&amp;` the browser seems to know to translate that as `&` and not `%26` (percent encoding for `&`) so the links in the preview pane of both demos goes to the correct url.

The only way to see GitHub's output html is to inspect the element in dev tools, but If you inspect the links in the demos you will see that the browser has converted the `&amp;` in the link to `&`.

So I'm guessing GitHub follows the common mark spec and the encodes it as `&amp;` as well, it is just getting shown in the dev tools as `&`.

**Comment by zeusdeux** [comment]
Yeah it's what I could see in devtools that threw me off; especially when combined with the browser still treating the links correctly. This is more of a TIL. Thanks @UziTech! Closing.
