### ISSUE TITLE
Slugify special characters (like spanish one)

### ISSUE THREAD

**Issue by jjlmoya** [markedjs/marked#1527]
**Describe the feature**
Slugify special characters (like spanishs/catalans/french ones):
**àáäâèéëêìíïîòóöôùúüûç**

**Why is this feature necessary?**
More languages supported

Just replace or extend slug function with:

```javascript
const stringToSlug = str => {
    str = str.replace(/^\s+|\s+$/g, ''); 
    str = str.toLowerCase();
    let from = "àáäâèéëêìíïîòóöôùúüûñç·/_,:;";
    let to = "aaaaeeeeiiiioooouuuunc------";
    for (var i = 0, l = from.length; i < l; i++) {
        str = str.replace(new RegExp(from.charAt(i), 'g'), to.charAt(i));
    }
    str.replace(/[^a-z0-9 -]/g, '') 
        .replace(/\s+/g, '-') 
        .replace(/-+/g, '-');
    return str;
};
```

**Comment by UziTech** [comment]
We are trying to copy GitHubs slugs and GitHub doesn't replace those characters.

https://github.com/UziTech/test/blob/master/special-chars.md#àáäâèéëêìíïîòóöôùúüûç

**Comment by jjlmoya** [comment]
I understand @UziTech, we (spanish) usually replace these characters but anyways we can extend the functionality in our side too
