### ISSUE TITLE
Marked transformed my template literals incorrectly

### ISSUE THREAD

**Issue by KsRyY** [markedjs/marked#1528]
**Describe the bug**
When I try to use template literals in javascript marked will compile my text into a single \<code\> block.

**To Reproduce**
``` js
marked(`
# h1
`)
```

The output is just like `<pre><code>#h1</code></pre>`

**Expected behavior**
The expected output is `<h1 id="h1">h1</h1>`

**Comment by UziTech** [comment]
I can't reproduce this. Can you share more of your code?

It sounds like you are including the backticks in the string like ``marked("`# h1`")``

**Comment by KsRyY** [comment]
I didn't include backticks, this happens when my template literal changes line.

**Comment by KsRyY** [comment]
https://gist.github.com/KsRyY/b066ff21277906d542811043c8aed7ce

**Comment by KsRyY** [comment]
above is the gist.
when you give it something like
``` js
marked({mdtext:`
# h1

## h2
`})
```
Its output is like
``` html
<pre><code>
# h1

## h2
</code></pre>
```

**Comment by UziTech** [comment]
I still can't reproduce that

```js
// marked.js
const marked = require('marked');
module.exports = function({ mdText }) {
    const transformedHTML = marked(mdText);
    return transformedHTML;
}
```

```js
// test.js
const marked = require("./marked.js");
console.log(marked({mdText:`
# h1

## h2
`}));

```

Output:
```sh
PS C:\Users\tjbrix\Documents\projects\GitHub\marked> node test.js
<h1 id="h1">h1</h1>
<h2 id="h2">h2</h2>
```

**Comment by UziTech** [comment]
are you sure your not doing something like

```js
marked(`${mdText}`);
```

**Comment by UziTech** [comment]
are you parsing a file to get the input?

**Comment by KsRyY** [comment]
nope

**Comment by bravokiloecho** [comment]
@KsRyY Did you resolve this? I'm having the same issue...

**Comment by UziTech** [comment]
@bravokiloecho where are you getting the input from?

**Comment by tinymachine** [comment]
I just had a similar issue; [this comment](https://github.com/markdown-it/markdown-it/issues/384#issuecomment-317071145) in the markdown-it repo helped me realize the culprit was indentation. My code had been indented like so:

```js
    marked(`
    # h1
    `) // renders <pre><code># h1</code></pre>
```

The indentation was being registered as a code block! Removing the indentation fixed the issue:

```js
    marked(`
# h1
    `) // renders <h1>h1</h1>
```

**Comment by einarmagnus** [comment]
I usually make an unindent function for these cases:

`/stringHelpers.ts:`
```typescript
// simplifies some stuff
import R from "remeda"

/**
 * Find the shortest sequence of leading spaces and remove them from the start of every line.
 * Empty lines are ignored
 * @param str the string to remove indentation from
 */
export function unindent(str: string): string;
/**
 * @param prefix replace this string at the start of every line in `str`
 * @param str
 */
export function unindent(prefix: string, str: string): string;
export function unindent(prefix: string, str?: string):string {
    if (R.isNil(str)) {
        // form without prefix was called, rename args
        str = prefix;

        // if there is any uindented line, then just return the string as it is.
        if (str.match(/^\S/m)) { return str };

        // find the shortest indentation
        let ms = [...str.matchAll(/^([ ]+)/gm)];
        prefix = R.firstBy(ms, m => m[1].length)?.[1] ?? "";

        // now we are ready with the correct args for the other form
    }
    return str.replaceAll(new RegExp(`^${prefix}`, "mg"), "");
}
```

Then I can use that to keep my source code tidy:
`otherFile.js:`
```typescript
import { unindent } from "./stringHelpers.ts";

const md = unindent(marked(`
    # h1
`)) // renders <h1>h1</h1>

There are also plenty of packges on npm that'll do this for you
```
