### ISSUE TITLE
write an implementation that uses Deno

### ISSUE THREAD

**Issue by catastrop** [markedjs/marked#1529]

**Comment by UziTech** [comment]
looks like we would need to export marked as an es module in order for it to work with deno

**Comment by UziTech** [comment]
marked was apparently made into a deno module [here](https://github.com/reggi/node-to-deno/blob/master/deno_modules/marked.js).

This just seems to be an example of how to change a node module into a deno module with webpack.

**Comment by UziTech** [comment]
or [here](https://github.com/denolib/marked)

**Comment by UziTech** [comment]
You could also look at [jspm.io](https://github.com/jspm/project/issues/50)
