### ISSUE TITLE
␤ actually becomes a newline when it shouldn't

### ISSUE THREAD

**Issue by sorenbug** [markedjs/marked#1531]
**Describe the bug**
U+2424 becomes a newline

**To Reproduce**
[Try it out in the demo](https://marked.js.org/demo/?text=%E2%90%A4&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master)

**Expected behavior**
The ␤ character actually shows up in text.

According to [Wikipedia](https://en.wikipedia.org/wiki/Newline#Unicode):
> The Unicode characters U+2424 (SYMBOL FOR NEWLINE, ␤), U+23CE (RETURN SYMBOL, ⏎), U+240D (SYMBOL FOR CARRIAGE RETURN, ␍) and U+240A (SYMBOL FOR LINE FEED, ␊) are intended for presenting a user-visible character to the reader of the document, and are thus not recognized themselves as a newline.

**Comment by UziTech** [comment]
confirmed:
[marked demo](https://marked.js.org/demo/?text=foo%E2%90%A4%E2%90%A4bar&options=&version=master)
[commonmark demo](https://spec.commonmark.org/dingus/?text=foo%E2%90%A4%E2%90%A4bar)

**Comment by UziTech** [comment]
It looks like this was introduced to fix "contenteditable" content. #52

Seems to be the same issue with U+00A0 in https://github.com/markedjs/marked/pull/897#issuecomment-451443207

I'm all for removing these substitutions and telling people to substitute these characters in the string before sending it to marked if they need to be substituted.

@styfle @joshbruce should we finally remove these substitutions in v0.8.0?

**Comment by styfle** [comment]
> should we finally remove these substitutions in v0.8.0?

Yes, let's do it 👍 

Using `contenteditable` seems less common than using U+00A0 and ␤ character.
