### ISSUE TITLE
URL automatic linking with single and double quotation is invalid

### ISSUE THREAD

**Issue by kenchan0130** [markedjs/marked#1533]
**Describe the bug**

URL automatic linking with single and double quotation is invalid.

marked version: **0.7.0**

**To Reproduce**

Input:

```md
You can access to "http://example.com".
```

Output:

```html
You can access to &quot;<a href="http://example.com&quot;">http://example.com&quot;</a>.
```

**Expected behavior**

```html
You can access to &quot;<a href="http://example.com">http://example.com</a>&quot;.
```

In the current state, the link is invalid.

**Comment by UziTech** [comment]
confirmed
[marked demo](https://marked.js.org/demo/?text=%22https%3A%2F%2Fexample.com%22&options=%7B%0A%20%22gfm%22%3A%20true%0A%7D&version=master)

A work around would be to use angle brackets (<>) around the link

```markdown
You can access to "<http://example.com>".
```

**Comment by kenchan0130** [comment]
@UziTech 
I understand there is such a workaround.
However, as a markdown use case, I think it is difficult to enforce the workaround because text is composed of existing documents and input from end users.

Therefore, I would say a fundamental solution is necessary.

**Comment by kenchan0130** [comment]
I read https://github.github.com/gfm/#autolinks-extension-.
Maybe it can’t be avoided.

**Comment by UziTech** [comment]
> a fundamental solution is necessary

I agree. We are always happy to accept PRs 😁

**Comment by kenchan0130** [comment]
This is in accordance with the GFM specification.
If the policy was to comply with GFM, I didn't think it was necessary to do so. If it really needs to be fixed, I will send a feedback to GFM (GitHub) We believe that it should be.
