### ISSUE TITLE
`breaks` option doesn't produce line breaks

### ISSUE THREAD

**Issue by maxhallinan** [markedjs/marked#1536]
**Describe the bug**

The breaks option doesn't seem to work. Maybe I have the wrong expectation?

**To Reproduce**

Set `gfm` and `breaks` to `true` in the options map.

```js
marked('# Foo\n', { gfm: true, breaks: true });
```

returns

```js
'<h1 id='foo'>Foo</h1>'
```

but I would expect it to return

```js
'<h1 id='foo'>Foo</h1> <br />'
```

Here's a [demo](https://marked.js.org/demo/?text=%23%20foo%0A&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20true%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master).

**Comment by UziTech** [comment]
The `breaks` option replaces `\n` with `<br>` between inline elements.

A header is a block element so `\n` will not be converted to `<br>`.

```js
marked('line1\nline2', { gfm: true, breaks: true });
// <p>line1<br>line2</p>
```
```js
marked('line1\nline2', { gfm: true, breaks: false});
// <p>line1
// line2</p>
```

**Comment by maxhallinan** [comment]
Ah got it! Thanks.
