### ISSUE TITLE
Cannot  break line well

### ISSUE THREAD

**Issue by hubenchang0515** [markedjs/marked#1537]
**Describe the bug**
Cannot use **(WhiteSpace)(WhiteSpace)(Return)** to break line while only one characher before it. 

And if use special character, it will reset the character count   

**To Reproduce**
Just input "a  \nb".

1. [Marked Demo](https://marked.js.org/demo/?text=Cannot%20use%20**(WhiteSpace)(WhiteSpace)(Return)**%20to%20break%20line%20while%20only%20one%20characher%20before%20it.%20%20%0A%0Aa%20%20%0Acannot%20break%20line%20in%20marked.js%0A%0Aaa%20%20%0Acould%20break%20line%0A%0AAnd%20if%20use%20special%20character%2C%20it%20will%20reset%20the%20character%20count%20%20%20%0Aaaaaaaaaaaaaaa%60%5C%60a%20%20%0Acannot%20break%20line%20in%20marked.js&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master)
2. [CommonMark Demo](https://spec.commonmark.org/dingus/?text=Cannot%20use%20**(WhiteSpace)(WhiteSpace)(Return)**%20to%20break%20line%20while%20only%20one%20characher%20before%20it.%20%20%0A%0Aa%20%20%0Acannot%20break%20line%20in%20marked.js%0A%0Aaa%20%20%0Acould%20break%20line%0A%0AAnd%20if%20use%20special%20character%2C%20it%20will%20reset%20the%20character%20count%20%20%20%0Aaaaaaaaaaaaaaa%60%5C%60a%20%20%0Acannot%20break%20line%20in%20marked.js)  
3. [Marked before 0.6.1 doesn't have this bug](https://marked.js.org/demo/?text=Cannot%20use%20**(WhiteSpace)(WhiteSpace)(Return)**%20to%20break%20line%20while%20only%20one%20characher%20before%20it.%20%20%0A%0Aa%20%20%0Acannot%20break%20line%20in%20marked.js%0A%0Aaa%20%20%0Acould%20break%20line%0A%0AAnd%20if%20use%20special%20character%2C%20it%20will%20reset%20the%20character%20count%20%20%20%0Aaaaaaaaaaaaaaa%60%5C%60a%20%20%0Acannot%20break%20line%20in%20marked.js&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=0.6.1)

**Comment by UziTech** [comment]
I'm going to guess it was #1460 that changed it.

**Comment by hubenchang0515** [comment]
I had fixed this and pull merge request 
Please review at https://github.com/markedjs/marked/pull/1746
