### ISSUE TITLE
Image urls with get variables

### ISSUE THREAD

**Issue by jenstornell** [markedjs/marked#1541]
I'm building a tool where I preview the content with Marked. I have the images in URLs like this:

http://server/api/read/?path=domain.com/images/167424.jpg

Marked will crush this URL because it contains a GET variable. To fix it, I needed to comment out a part of the resolveUrl.

```js
if (!baseUrls[' ' + base]) {
  // we can ignore everything in base after the last slash of its path component,
  // but we might need to add _that_
  // https://tools.ietf.org/html/rfc3986#section-3
  if (/^[^:]+:\/*[^/]*$/.test(base)) {
    baseUrls[' ' + base] = base + '/';
  } else {
    baseUrls[' ' + base] = rtrim(base, '/', true);
  }
}
base = baseUrls[' ' + base];
```

Remove the above, and it works as expected.

To make it work in the long run with URLs like this, maybe make this function less agressive?

**Comment by jenstornell** [comment]
@UziTech Yes, in your example it works.

I have been able to reproduce the issue. In order to do so I needed to involve `baseUrl` as well. The simplest to me was to use jsfiddle, so that's what I did.

https://jsfiddle.net/xLktp30m/2/

**js**

In the console log you will see an image tag without the get variable.

```js
let markdown = '![](domain.com/images/96449.jpg)';
let root = 'https://example.com/api?test=';
let results = marked(markdown, { baseUrl: root });

console.log(results);

document.querySelector('textarea').value = results;
```

**html (optional)**

```html
<textarea></textarea>
```

In conclusion it's the `baseUrl` that is too agressive in my case.

**Comment by joshbruce** [comment]
Sorry. Playing with tags.

**Comment by jenstornell** [comment]
As I use Vue with Vue CLI 3 I don't want to edit the code of the library. Instead, I've come up with a hacky workaround. Maybe someone will find it useful.

```js
const markdown = '# Markdown with images';
const baseUrl = "/fields/markdown/get/image/";

let marked = Marked(markdown, {
  baseUrl: baseUrl
});

marked = marked.replace(
  ' src="' + baseUrl,
  ' src="/fields/markdown/get/image?path='
);

console.log(marked);
```

Basically I search and replace the image baseUrl. You need to set a baseUrl that ends with a slash that you can later replace.

- Does not match image urls with a different baseUrl.
- Does not match external image urls with http, https etc.
- The chance of a conflict is quite low if the `baseUrl` is more specific.

Improvements are welcome.

**Comment by UziTech** [comment]
You could also override the renderer to provide the base url

```js
const marked = require('marked');

const renderer = new marked.Renderer();
const baseUrl = '/fields/markdown/get/image?path=';

const originalRendererLink = renderer.link.bind(renderer);
const originalRendererImage = renderer.image.bind(renderer);

renderer.link = (href, title, text) => {
  href = baseUrl + href;
  return originalRendererLink(href, title, text);
};

renderer.image = (href, title, text) => {
  href = baseUrl + href;
  return originalRendererImage(href, title, text);
};

const md = '![image](/url.png)';
const html = marked(md, { renderer });

console.log(html);
// <p><img src="/fields/markdown/get/image?path=/url.png" alt="image"></p>
```

**Comment by jenstornell** [comment]
@UziTech It's a bit more code, but it should be much more reliable in all cases and not a hack. It works as expected!

Thanks!

**Comment by Hideer** [comment]
@UziTech Can you add data-img attribute dynamically to img

**Comment by UziTech** [comment]
@Hideer You can return whatever you want in the `renderer.image` function

e.g.
```js
renderer.image = (href, title, text) => {
  return `<img src="${href}" data-img="${href}" alt="${text}" title="${title}"/>`;
};
```

**Comment by UziTech** [comment]
closing as stale. I don't think we will change the behavior of baseUrl
