### ISSUE TITLE
cann't support flow grammar

### ISSUE THREAD

**Issue by 2865724220** [markedjs/marked#1544]
``` flow
st=>start: 用户登陆
op=>operation: 登陆操作
cond=>condition: 登陆成功 Yes or No?
e=>end: 进入后台

st->op->cond
cond(yes)->e
cond(no)->op
```
cann't support flow grammar

**Comment by UziTech** [comment]
Can you give us an input and expected output?

**Comment by 2865724220** [comment]
input 
```flow
st=>start: Start
op=>operation: Your Operation
cond=>condition: Yes or No?
e=>end

st->op->cond
cond(yes)->e
cond(no)->op
```
expeact output flow chart

**Comment by UziTech** [comment]
This software it for converting markdown into html not creating flow charts.

**Comment by UziTech** [comment]
seems like you are looking for something like [mermaid](https://mermaidjs.github.io/)

**Comment by timestee** [comment]
Went through the same, can we support mermaid?
