### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by DanielHabenicht** [markedjs/marked#1545]
**What pain point are you perceiving?**
"I am using renovate to update my packages (with auto merging enabled) and a marked update got auto merged because of a `minor` release, which broke things in production. " 
That will be somebody (maybe me) in the future. 

I now that you heavily discussed releasing a `1.0` and this should be a little reminder that not having released one still is an issue for all users of the package. 
 
**Describe the solution you'd like**
What I propose is releasing a `1.0` version as soon as you can and going from thereon. 
A version number says nothing about the matureness of a project (and this has been around for long enough that it is definitely mature enough for being released) its sole purpose is to make it clear to the user what has changed. (e.g. a `major` release beeing a `breaking change`). 
If you have some things in the pipe that will trigger a major release in the future - so be it. Please refrain beeing connected to the aesthetics of the version number and use it for its main purpose. (Sry, if this is a little bit harsh. I really like this package and I know that much of your free time has been detecated towards this project. But this is bugging me. )

In order to make it easier, you might want to check out [semantic-release](https://github.com/semantic-release/semantic-release) which automates the whole process of determining a version number, writing changelogs and releasing a new package version based on the commits. If you have any questions on how to do it or need support setting it up mention me.

**Comment by UziTech** [comment]
The plan is to release v1.0 once all CommonMark and GFM specs are passing.

Right now we follow [semver](https://docs.npmjs.com/misc/semver#caret-ranges-123-025-004) for 0.x.y where `x` is breaking changes and `y` is non-breaking changes.

If you want to help get to v1.0 we have many spec [issues](https://github.com/markedjs/marked/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22L2+-+annoying%22) that could use a PR 😁

**Comment by calculuschild** [comment]
I just ran into this myself. Dependabot tried to auto deploy for me and it broke all of the styling on our documents.

**Comment by DanielHabenicht** [comment]
@UziTech which of the Issues referenced above do you recommend for a beginner in this project?

**Comment by UziTech** [comment]
@DanielHabenicht you can do whichever one you want. I would just pick one and try to work on it.

**Comment by UziTech** [comment]
The easiest way to get marked up to spec would be to look in [/test/specs/commonmark/commonmark.0.29.json](https://github.com/markedjs/marked/blob/master/test/specs/commonmark/commonmark.0.29.json), find a spec with [`"shouldfail": true`](https://github.com/markedjs/marked/blob/4af69d33434f47b85630ea435a0ddeccea244838/test/specs/commonmark/commonmark.0.29.json#L57) and set it to false, then run try to get the tests to pass.

**Comment by DanielHabenicht** [comment]
Mhm, I am sorry but I will also change to [markdown-it](https://github.com/markdown-it/markdown-it#benchmark). Just for versioning purposes, it is not likely that I implement all 100ish test cases. Keep up the good work, this is still the fastest markdown parser around.

**Comment by UziTech** [comment]
Markdown-it is a good library that is very extensible. The markedjs team has been talking about releasing v1.0 sooner since the move to spec compliance has been slower than originally planned. We will release a new plan soon and I think we should be able to release v1.0 in the next couple months.
