### ISSUE TITLE
Provide counters for elements

### ISSUE THREAD

**Issue by jenstornell** [markedjs/marked#1553]
To count elements without parsing the markdown more than one time, something like below is needed.

## Example - Count blockquotes

```js
const renderer = new Marked.Renderer();
const originalRendererBlockquote = renderer.blockquote.bind(renderer);

let blockquote_count = 0;

renderer.blockquote = (blockquote) => {
  blockquote_count++;
  return originalRendererBlockquote(blockquote);
};

console.log(blockquote_count);
```

The only thing the code above does is to put the number of blockquotes in the console log. That code is quite long for that.

Imagine counting all elements in a widget or something. It would be a very long code.

## Shorter dreamcode

The above could be shorter like the example below:

```js
let markdown = ">A blockquote";
let blockquote_count = marked(markdown).count('blockquote');
console.log(blockquote_count);
```

If there is an easier way without sacrifising performance than my first code, feel free to give an example. Thanks!

**Comment by UziTech** [comment]
You can get the [lexer tokens](https://marked.js.org/demo/?outputType=lexer) with `marked.lexer(markdown, options)` and count tokens

```js
let markdown = ">A blockquote";
let tokens = marked.lexer(markdown, options);
let blockquote_count = tokens.reduce((count, token) => {
	return count + (token.type === "blockquote_start" ? 1 : 0);
}, 0);
console.log(blockquote_count);
```

**Comment by jenstornell** [comment]
@UziTech Yes, that works.

Now my problem is that the `marked.parser` does not take my `renderer` as the second argument. It means that I need to do an additional `marked(content, rendererer)` call. Then the content needs to be parsed twice (one for counting stuff and one for generating the html), which is not optimal for long content.

```js
let counters = {};
let tokens = marked.lexer(content);
counters.blockquote = tokens.reduce((count, token) => {
  return count + (token.type === 'blockquote_start' ? 1 : 0);
}, 0);

const html = marked.parser(tokens, renderer); // In the real code the renderer has stuff attached
console.log(html);
```

Maybe you have a solution to this issue as well?

**Comment by jenstornell** [comment]
@UziTech I got back to my original way of doing this. The code length is still managable I think. Also, I do both the counting and rendering at the same time, parsing it only one time.

![elements](https://user-images.githubusercontent.com/927011/65585540-ec9d8700-df82-11e9-95b8-7a5b2f880227.png)

I use this in a Vue project so I've not tested the function below in an isolated environment, but maybe it's helpful as an inspiration for someone.

```js
function render(content, trim) {
  const renderer = new marked.Renderer();
  const baseUrl = '/fields/markdown/get/image?path=';
  const r = {
    link: renderer.link.bind(renderer),
    image: renderer.image.bind(renderer),
    blockquote: renderer.blockquote.bind(renderer),
    heading: renderer.heading.bind(renderer),
    list: renderer.list.bind(renderer),
    paragraph: renderer.paragraph.bind(renderer),
    table: renderer.table.bind(renderer)
  };

  let counters = {
    alt: 0
    blockquotes: 0,
    h1: 0,
    headlines: 0,
    images: 0,
    links: 0,
    lists: 0,
    paragraphs: 0,
    tables: 0,
  };
  
  renderer.blockquote = (blockquote) => {
    counters.blockquotes++;
    return r.blockquote(blockquote);
  };
  
  renderer.image = (href, title, text) => {
    if (text != '') {
      counters.alt++;
    }
    href = baseUrl + trim + href;
    counters.images++;
    return r.image(href, title, text);
  };
  
  renderer.heading = (text, level, raw, slugger) => {
    if (level == 1 && counters.headlines == 0) {
      counters.h1 = raw.length;
    }
    counters.headlines++;
    return r.heading(text, level, raw, slugger);
  };

  renderer.link = (href, title, text) => {
    href = baseUrl + trim + href;
    counters.links++;
    return r.link(href, title, text);
  };

  renderer.list = (body, ordered, start) => {
    counters.lists++;
    return r.list(body, ordered, start);
  };

  renderer.paragraph = (text) => {
    counters.paragraphs++;
    return r.paragraph(text);
  };

  renderer.table = (header, body) => {
    counters.tables++;
    return r.table(header, body);
  };

  const html = marked(content, {
    renderer
  });

  return {
    html: html,
    count: counters
  };
}
```

**Comment by UziTech** [comment]
the parser takes an `options` object as the second parameter so `marked.parser(tokens, {renderer});` should work.

The only thing that won't work when using the lexer tokens is inline elements (bold, italics, etc.) since those are tokenized in the parser.

**Comment by jenstornell** [comment]
@UziTech Thanks! I will still use my current solution because I use it for other things as well (Table of contents etc). I close this now.
