### ISSUE TITLE
Can you support code highlighting？

### ISSUE THREAD

**Issue by wangpanhb** [markedjs/marked#1554]
**Describe the feature**
Can you support code highlighting

**Why is this feature necessary?**
When viewing the code,it can improving Visual Experience

**Comment by UziTech** [comment]
There is a [`highlight` option](https://marked.js.org/#/USING_ADVANCED.md#highlight) so you can use [highlight.js](https://highlightjs.org/) to highlight code snippets.

```js
marked(markdown, {
  highlight: (code) => require('highlight.js').highlightAuto(code).value
});
```
