### ISSUE TITLE
Markdown containing tabs not converted properly to spaces

### ISSUE THREAD

**Issue by ankurnarkhede** [markedjs/marked#1559]
**Describe the bug**
The package converts the tabs in the markdown to 4 spaces every time. It breaks the alignment of the text. It's not how tabs work. The tab indentation of the current tab in a string will be 
`tabsize - ((number of characters occupied in current tab buffer) % tabsize)`

<img width="475" alt="image" src="https://user-images.githubusercontent.com/22790328/66266192-387fe400-e83f-11e9-8f7c-a2640868207f.png">

**To Reproduce**
Steps to reproduce the behaviour:

1. Type any text using tabs.
2. Paste it in [Marked Demo](https://marked.js.org/demo/) for viewing parsed HTML. You will see changes in the alignment.

Below is the text that contains tabs that I am parsing to HTML.
```markdown
# markdown alignment

```
        [FirstName]				=> TEST
        [LastName]				=> TESTIN
        [EmailAddress]			=> TEST
        [CompanyName]			=> Test Company
        [Phone]					=> TEST
```
```

Demo links:
1. [Marked Demo](https://marked.js.org/demo/?text=%23%20markdown%20alignment%0A%0A%60%60%60%0A%20%20%20%20%20%20%20%20%5BFirstName%5D%09%09%09%09%3D%3E%20TEST%0A%20%20%20%20%20%20%20%20%5BLastName%5D%09%09%09%09%3D%3E%20TESTIN%0A%20%20%20%20%20%20%20%20%5BEmailAddress%5D%09%09%09%3D%3E%20TEST%0A%20%20%20%20%20%20%20%20%5BCompanyName%5D%09%09%09%3D%3E%20Test%20Company%0A%20%20%20%20%20%20%20%20%5BPhone%5D%09%09%09%09%09%3D%3E%20TEST%0A%60%60%60&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master)
2. [CommonMark Demo](https://spec.commonmark.org/dingus/?text=%23%20markdown%20alignment%0A%0A%60%60%60%0A%20%20%20%20%20%20%20%20%5BFirstName%5D%09%09%09%09%3D%3E%20TEST%0A%20%20%20%20%20%20%20%20%5BLastName%5D%09%09%09%09%3D%3E%20TESTIN%0A%20%20%20%20%20%20%20%20%5BEmailAddress%5D%09%09%09%3D%3E%20TEST%0A%20%20%20%20%20%20%20%20%5BCompanyName%5D%09%09%09%3D%3E%20Test%20Company%0A%20%20%20%20%20%20%20%20%5BPhone%5D%09%09%09%09%09%3D%3E%20TEST%0A%60%60%60)

The CommonMark was also not able to parse the tabs to appropriate number od spaces.

The [ParseDown](https://packagist.org/packages/erusev/parsedown) PHP package was able to parse the tabs in text to appropriate number of spaces. Its how any user will expect the HTML output to look like. You can paste the above given markdown text in [ParseDown Demo](https://parsedown.org/demo)
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/22790328/66266708-3ec58e80-e846-11e9-9ea4-a3b3a3852442.png">

**Expected behavior**
When I am writing a markdown containing tabs, I will expect it to give the same alignment when converted to HTML. It how any user will expect.

I am using this text:
<img width="470" alt="image" src="https://user-images.githubusercontent.com/22790328/66266753-c01d2100-e846-11e9-95f6-c3e32c4b6f2a.png">

The arrows aren't aligned upon parsing. It gets  parsed to HTML like this:
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/22790328/66266770-14c09c00-e847-11e9-9c32-32ad7e4b0fd0.png">
<img width="525" alt="image" src="https://user-images.githubusercontent.com/22790328/66266779-3457c480-e847-11e9-95da-50a04457725e.png">

While, any user will expect it to be like this:
<img width="500" alt="image" src="https://user-images.githubusercontent.com/22790328/66266794-6ff28e80-e847-11e9-943d-977d652b40d2.png">

**Comment by UziTech** [comment]
Tabs are probably not the best for this type of alignment. For instance your example isn't aligned in my browser because I have tabs set to 2 spaces.

![image](https://user-images.githubusercontent.com/97994/66272015-07e17f80-e82a-11e9-86dc-39643783e2e3.png)

**Comment by smartankur4u** [comment]
@UziTech you are right!
But, that's the reason marked is converting tabs to spaces so as the **output should be consistent in all the browsers**.
Can I get your opinion upon this?

**Comment by UziTech** [comment]
Marked should be more compliant with tabs. I think we should only replace the tabs at the start of a line.

There is still one CommonMark test that is failing for tabs. 
https://github.com/markedjs/marked/blob/4584a8a80b5b2f1773f6d11c31aea62050f7a241/test/specs/commonmark/commonmark.0.29.json#L51-L52

**Comment by smartankur4u** [comment]
@UziTech sounds better!
I will be working upon this.

**Comment by UziTech** [comment]
@smartankur4u I am going to answer your questions here:

> 1. You said [here](https://github.com/markedjs/marked/issues/1559#issuecomment-538762069), that the text was not alligned properly on your browser as you had set tab to 2 spaces. This text was actually indented properly with tabs of size 4. Its obvious that its alignemnt will break with other tab sizes. So isn't this the point why marked converts tabs to spaces to have common view in each device?

Tab characters don't have an inherit size. The size can be set by the user. You choose to have them be size 4, I choose to have them be size 2, I know a developer who prefers them to be size 8.

My point is that just because the input looks aligned with tabs to the user (who can define any size for a tab character) when converting them to spaces we have to pick an arbitrary size (in CommonMark spec that size is 4) so using tabs with that type of alignment never works for everyone. Which is why IMHO tabs should only be used for indentation not alignment.

> 2. Do we need to comply with this rule of CommonMark which breaks the alignment of the text? As users are expecting a the same output in HTML what they wrote in markdown, don't we need to convert tabs to appropriate spaces?

According to the common mark spec only tabs at the beginning of a line (used for indentation) are converted to 4 spaces. All other tabs are left as tab characters.

This does need to be fixed in marked to be spec compliant.

> 3. Can you please comment on the ParseDown PHP package which converts everything properly as user expects. I have added screenshots and links here: https://github.com/markedjs/marked/issues/1559

ParseDown PHP doesn't convert everything as every user expects. If the user doesn't have tab size set to 4 the alignment is off

![image](https://user-images.githubusercontent.com/97994/66706832-b8092980-ecfd-11e9-8f4b-dee4978f6108.png)

> 4. Do you expect the developers facing this issue to write a custom code for converting tabs to spaces before parsing via marked?

Yes, I expect developers to understand their users better than me. If their users will always have tab size set to 4 than they can convert tabs using your [`tab-to-space`](https://www.npmjs.com/package/tab-to-space) package before sending it to marked

```js
const html = marked(tabToSpace(markdown));
```

**Comment by smartankur4u** [comment]
Thanks for the reply @UziTech.
Got your view. I will be working on the issue to convert leading tabs to spaces.
Thanks.

**Comment by jvalrog** [comment]
Hello, my problem is that Marked is actually changing tabs into spaces.

I need tabs to remain as tabs, that's why I put them in there. I can't copy/paste code snippets in markdown because the tabs are gone.

Is there a way to force Marked to stop doing that?

Thanks

**Comment by UziTech** [comment]
@jvalrog not currently. But we are always accepting PRs
