### ISSUE TITLE
marked.Renderer().code invalid params

### ISSUE THREAD

**Issue by deissh** [markedjs/marked#1564]
**Describe the bug**
`marked.Renderer().code` expect function with `code: string, language: string, isEscaped: boolean` params (as in @types/marked) but some times language return `undefinded`.

**To Reproduce**

```ts
renderer.code = (code: string, language: string, isEscaped: boolean) => {
    // `language` some times return undefinded and line below throw exeption
    console.log(language.toLowerCase());
    return `<pre><code>${code}</code></pre>`;
};
```
and markdown
```md
code:

    self.body
```

**Expected behaviour**
Always return a string or change @types/marked.

**Comment by UziTech** [comment]
Yes `language` will be `undefined` for indented code blocks since there is no way to specify a language for indented code blocks.

If your issue is that the types are wrong then you should create an issue in the [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) repo

**Comment by deissh** [comment]
Megred
