### ISSUE TITLE
unknown html tag

### ISSUE THREAD

**Issue by Mizugorou** [markedjs/marked#1565]
**Marked version: 0.7.0**
I try to use marked in vue by using this input, and also try in demo page by this input.

<pre>
&lt;abc&gt;
```
hello
```
&lt;/abc&gt;
</pre>

The input has an unknown html tag covering code block(&#96;&#96;&#96;hello&#96;&#96;&#96;). After using, the result showed as unknown html tag without code block.
I expect to got code block or something like below. 
```html
<pre>
<code>hello</code>
</pre>
```

Is it possible to get result as code block inside an unknown HTML tag or ignore an unknown HTML tag?  Would you please advise.

**Comment by UziTech** [comment]
According to the [CommonMark spec](https://spec.commonmark.org/0.29/#html-blocks):

> An HTML block is a group of lines that is treated as raw HTML (and will not be escaped in HTML output).

If you wanted to create an extension marked that parses certain html tags you will need to override the `Renderer.prototype.html` function and run the contents of the html through marked.

Something like:

```js
const marked = require('marked');
const renderer = new marked.Renderer();

renderer.html= function (html) {
  const startTag = html.match(/^<([^>])+>/)[1];
  const endTag = html.match(/<\/([^>])+>$/)[1];
  const contents = html.replace(/^<[^>]+>|<\/[^>]+>$/g, '');

  return `
<${startTag}>
  ${marked(contents, { renderer: renderer })}          
</${endTag}>
`;
};

console.log(marked(markdown, { renderer: renderer }));
```

Note: this code is not tested and does not handle certain edge cases. But it should be a good starting point.
