### ISSUE TITLE
Link references in nested lists aren't parsed

### ISSUE THREAD

**Issue by nex3** [markedjs/marked#1566]
**Describe the bug**

If a link reference appears in a nested list, it is not parsed correctly and its corresponding link won't render.

**To Reproduce**

1. [Marked Demo](https://marked.js.org/demo/?text=*%20Outer%0A%20%20*%20%5BInner%5D%5B%5D%0A%0A%20%20%20%20%5BInner%5D%3A%20href%0A&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master)
2. [CommonMark Demo](https://spec.commonmark.org/dingus/?text=*%20Outer%0A%20%20*%20%5BInner%5D%5B%5D%0A%0A%20%20%20%20%5BInner%5D%3A%20href%0A)

**Comment by nex3** [comment]
The same is true for link references in blockquotes in lists:

1. [Marked Demo](https://marked.js.org/demo/?text=*%20%3E%20%5BInner%5D%5B%5D%0A%20%20%3E%0A%20%20%3E%20%5BInner%5D%3A%20href%0A&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master)
2. [CommonMark Demo](https://spec.commonmark.org/dingus/?text=*%20%3E%20%5BInner%5D%5B%5D%0A%20%20%3E%0A%20%20%3E%20%5BInner%5D%3A%20href%0A)

**Comment by calculuschild** [comment]
This should be fixed by #2112
