### ISSUE TITLE
Option to disable link-like parsing

### ISSUE THREAD

**Issue by Arteneko** [markedjs/marked#1567]
Right now, the parser transforms a raw text that *looks like* a link.

this is annoying in cases where the markdown document present "dead" links, or invalid links (e.g. in the context of a HTTP-oriented technical article).

I couldn't find a way to disable this behaviour, so I'd like to know if it could be added.

## Current behaviour

```
https://test.abc/this/is/a/fancy
```

Translates to

```
<a href="https://test.abc/this/is/a/fancy">https://test.abc/this/is/a/fancy</a>
```

I'd expect a setting to disable this behaviour and keep the raw link as-is.

**Comment by UziTech** [comment]
You can set the `gfm` option to `false` to disable the [gfm extentions](https://github.github.com/gfm/#autolinks-extension-)

Otherwise you could [override the renderer](https://marked.js.org/#/USING_PRO.md#renderer) to just prevent autolinking.

**Comment by Arteneko** [comment]
Couldn't the gfm extension be configured in a more precise way?

I'd only want to disable auto-linking.

As for overriding the renderer, which type would need to be overridden?

**Comment by UziTech** [comment]
The `gfm` option is only evaluated as `true` or `false`.

You would need to override the `rederer.link` function

**Comment by Arteneko** [comment]
Thanks, I'll take a look into that.

I saw the NFE tag, does that mean that you'd like to see a marked extension for this feature?

**Comment by UziTech** [comment]
The `NFE` tag means that this proposal shouldn't be a change in marked but an extension that will provide this functionality.

We are trying to simplify the code base, remove all unnecessary options, and make it easier to extend marked so we don't have features that are only relevant to a small number of users.
