### ISSUE TITLE
Funding for marked

### ISSUE THREAD

**Issue by chrisvxd** [markedjs/marked#1569]
Hey @UziTech! 👋

Just wanted to reach out about funding your work on `marked`.

@transitive-bullshit and I are both open source maintainers, and we're exploring new ways to make OSS funding a viable source of income.

We're currently looking at building rate-limited SaaS APIs on top of existing OSS libraries, reserving the majority of profits for the original authors. [We've built a few](https://saasify.sh/#/showcase) at this point, but want to keep adding more.

I think it would be awesome to have a `marked` SaaS API for compiling markdown, and I'd love to build one out for you. We'd handle dev, auth, billing and support so you wouldn't have to do anything.

Looking forward to hearing your thoughts! 🙏

**Comment by styfle** [comment]
The core team has discussed funding in the past. We don’t have any expenses at this time so it was never really prioritized. It also brings up problems of who gets the money and when should someone be promoted or demoted to get a piece of the pie so to speak.

**Comment by joshbruce** [comment]
Closing as potential topic to revisit at a later time and clean the issues a bit.
