### ISSUE TITLE
header link in github flavored markdown mode.

### ISSUE THREAD

**Issue by computerphilosopher** [markedjs/marked#1579]
I made a header link that has a hyphen('-') in it. 

markdown code is same as below.

```md
# link to  'part1 - my title'   
[my header link](part1-my-title)
```

but when I make header link in github, I have to write in this way.

```md
# link to  'part1 - my title'   
[my header link](part1---my-title)
```

I think it should work in the same way.

**Comment by styfle** [comment]
This works for me.

Input: `# part1 - my title`
Output: `<h1 id="part1---my-title">part1 - my title</h1>`

https://marked.js.org/demo/?outputType=html&text=%23%20part1%20-%20my%20title&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=0.7.0

**Comment by UziTech** [comment]
@computerphilosopher what version of marked are you using?

**Comment by computerphilosopher** [comment]
I use [docsify](https://github.com/docsifyjs/docsify) for documentation. docsify uses marked 0.7.0. 

maybe it is docsify's issue...

**Comment by UziTech** [comment]
It look like the last release of docsify uses marked v0.5.1 so a new release would fix this.

**Comment by computerphilosopher** [comment]
Thank you for answering
