### ISSUE TITLE
Table: HTML `align` attribute is unsupported in HTML5

### ISSUE THREAD

**Issue by nadirs** [markedjs/marked#158]
In a table like the following:

```
    alpha | beta    | gamma
     ---: | :-----: | ----:
    delta | epsilon | zeta
```

a cell is translated into:

```
    <td align="right"> ...</td>
```

Alignment is accomplished through the use of HTML `align` attribute which is considered obsolete for [HTML5 tables](http://www.w3.org/TR/html-markup/table.html#table-constraints).
CSS is recommended by the W3C.

**Comment by julmot** [comment]
This will not work with images inside tables
