### ISSUE TITLE
`main` field of package.json referred to source code 

### ISSUE THREAD

**Issue by RaoHai** [markedjs/marked#1583]
**Describe the bug**

https://github.com/markedjs/marked/blob/master/package.json#L6

`main` field of package.json referred to source code. 

**Expected behavior**
referred to `/lib` directory as it in 0.7.0 before.

**Comment by UziTech** [comment]
Why do you want the `main` field to point the `/lib/marked.js`?

**Comment by RaoHai** [comment]
If anyone who use `marked` in `react-create-app`, the es6 features in source code will break code optimize by UglifyJS, which not support es6 yet. 

```bash
➜  marked yarn build
yarn run v1.16.0
warning ../../package.json: No license field
$ react-scripts build
Creating an optimized production build...
Failed to compile.

static/js/main.cf6aa3d9.js from UglifyJs
SyntaxError: Unexpected token: operator (>) [./~/marked/src/helpers.js:15,0]

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by styfle** [comment]
It looks like `uglify-js` doesn't support ES6 for some reason. Perhaps you need to use [uglify-es](https://www.npmjs.com/package/uglify-es) instead.

**Comment by UziTech** [comment]
or you can require the es5 version with `require('marked/lib/marked.js')`

**Comment by RaoHai** [comment]
@styfle  @UziTech  In many cases, people do not use `marked`  directly, but use third-party libray such as https://github.com/sparksuite/simplemde-markdown-editor/blob/master/package.json#L26, which directly references the * version. The release of marked from 0.7.0 to 0.8.0  will break their build.

Or would you please release a major version of `marked`?

I am on of the maintainers of alipay internal devOps platform. The past two days we detected that some projects build failed due to this update...  😿

**Comment by UziTech** [comment]
We do follow [`semver`](https://docs.npmjs.com/misc/semver#caret-ranges-123-025-004) for 0.x.y where x is breaking changes and y is non-breaking changes.

If your dependencies are using `*` for the version then you should create PRs to change that to caret versioning (`"marked": "^0.7.0"`) so it won't break when breaking changes are released.

**Comment by UziTech** [comment]
The es6 migration was not the only breaking change in this release and there will most likely be more breaking changes before v1.0.0 so moving `main` back to the es5 version is not a very good solution to the problem. It only prevents one symptom.

**Comment by RaoHai** [comment]
OK. Thanks for reply.
