### ISSUE TITLE
Noob question

### ISSUE THREAD

**Issue by paulocastellano** [markedjs/marked#1586]
Is it possible to use #my-title-h1 instead of # my-title-h1 ?

**Comment by UziTech** [comment]
CommonMark spec requires a space after the `#` but if you set `pedantic: true` option it will use the original [daring fireball spec](https://daringfireball.net/projects/markdown/) which allows a header without a space along with other spec changes.

**Comment by paulocastellano** [comment]
@UziTech 

Thanks!
