### ISSUE TITLE
Error on open marked-0.8.0\docs\index.html

### ISSUE THREAD

**Issue by 0x7d9** [markedjs/marked#1589]
Beginner question:
I downloaded the latest version of Marked, and open marked-0.8.0\docs\index.html with chrome, but it doesn't work:
```
Oops! There was a problem rendering the page.
Failed to fetch
```
I upload docs files to a server and open, also an error occurred:
```
Oops! There was a problem rendering the page.
Error 404: Not Found
```
Does anyone know the reason?

**Comment by UziTech** [comment]
The docs are rendered by marked on the client. Is there an error in the console?

if you want to get to the docs you can view them at https://marked.js.org/

**Comment by 0x7d9** [comment]
Thanks for the answer!

That simple example is work fine
```
<!doctype html>
<html>
<head>
  <meta charset="utf-8"/>
  <title>Marked in the browser</title>
</head>
<body>
  <div id="content"></div>
  <script src="https://cdn.jsdelivr.net/npm/marked/marked.min.js"></script>
  <script>
    document.getElementById('content').innerHTML =
      marked('# Marked in browser\n\nRendered by **marked**.');
  </script>
</body>
</html>
```
My purpose is not to view help, but want to build a similar help system, 
I don't know how to run it in the console...
I also open https://marked.js.org/, save to desktop, but the webpage doesn't open properly

**Comment by styfle** [comment]
If you’re new to web dev and want a quick way to setup documentation, you might try https://docsify.js.org which uses marked under the hood.

**Comment by 0x7d9** [comment]
Thanks for your suggestion.
So these js codes were run on the server side and needed nodejs support. Now I know how to open them locally, Just install nodejs. But the virtual server I use does not have nodejs pre-installed, and I cannot install it myself, so I need to find a solution that does not require nodejs or replace the server.
