### ISSUE TITLE
Closing delimited * incorrect for consecutive ocurrences

### ISSUE THREAD

**Issue by damianon** [markedjs/marked#1594]
**Describe the bug**
When `**` is used consecutively the closing delimiter is recognised incorrectly

**To Reproduce**
`b**o****o**k` turns into `b<strong>o**</strong>o**k`

Interesting enough the Marked Demo Page produces a different result: https://spec.commonmark.org/dingus/?text=b**o****o**k

Version: 0.8.0 (previously 0.7.0 with the same bug)

**Expected behavior**
both o's should get a separate `<strong>`

Tried this online editor and it works correctly: https://dillinger.io/

**Comment by UziTech** [comment]
`*`'s are supposed to only be terminated by the same number of `*`'s.

[marked demo](https://marked.js.org/demo/?outputType=html&text=b**o****o**k&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master)

looks like this has a failing test

https://github.com/markedjs/marked/blob/a42413d4fa29834acea871273f8076cc2bf990b4/test/specs/commonmark/commonmark.0.29.json#L3366-L3374

**Comment by Scrum** [comment]
@UziTech I think this test is quite correct and logical, why do you consider it `failing`
