### ISSUE TITLE
Add ability to read directly a mardown file and include it

### ISSUE THREAD

**Issue by moctardiallo** [markedjs/marked#1595]
**Describe the feature**
Rather than just copying all markdown text from a markdown file and include that text manually into the html, why not provide a direct way of just referring the markdown file and it gets included automatically. 

**Why is this feature necessary?**
It looks to me necessary as it would help automate a lot of manual work: copying and pasting all the time.

**Describe alternatives you've considered**
I think this is the best module i've find for now, it is easy to use and straightforward. So let's keep it and make it even better!

**Comment by UziTech** [comment]
Marked is a client side library as well as a server side library. How you get a file on the client side is much different to how you get a file on the server side.

You could create a package that does this very easily on node:

```js
// file2marked
const marked = require('marked');
const fs = require('fs');

module.exports = function file2marked(file) {
  const markdown = fs.readFileSync(file, {encoding: "utf8"});
  return marked(markdown);
}
```

**Comment by UziTech** [comment]
I'm going to close this since I don't think we will be putting this in marked. If there is something else you want to add we can reopen it.
