### ISSUE TITLE
Stop autolinking hxxp and hxxps

### ISSUE THREAD

**Issue by ajkerzner** [markedjs/marked#1596]
**Describe the feature**
For security reasons, `hxxp://` and `hxxps://` should not be linkified.

**Why is this feature necessary?**
We sometimes need to link malicious sites. However, many applications will linkify things like https://<url> . Using hxxps://<url> is meant to prevent that.

See https://tools.ietf.org/id/draft-salgado-hxxp-01.xml for an explanation of the use case.

**Comment by UziTech** [comment]
auto links should only work with `ftp://`, `http://`, and `https://`

[demo](https://marked.js.org/demo/?text=ftp%3A%2F%2Fexample.com%0A%0Ahttp%3A%2F%2Fexample.com%0A%0Ahttps%3A%2F%2Fexample.com%0A%0Ahxxp%3A%2F%2Fexample.com%0A%0Ahxxps%3A%2F%2Fexample.com%0A&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master)

**Comment by ajkerzner** [comment]
Okay... I apologize. I figured it was marked. I'm closing this issue.
