### ISSUE TITLE
* after spaces don't close properly

### ISSUE THREAD

**Issue by calculuschild** [markedjs/marked#1597]
**Describe the bug**
Any italics/bold with a space before the final asterisk does not seem to recognize the closing asterisk.

**To Reproduce**
[Demo permalink](https://marked.js.org/demo/?text=I%20am%20*italicized%20*!%0A%0AI%20am%20**bolded%20**!%0A%0AI%20am%20***bold%20and%20italicized%20***!&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master)

**Expected behavior**
I would expect whitespaces on the same line to not affect the output. Is this the expected behavior or is it a bug?

**Comment by UziTech** [comment]
That is actually how it is supposed to work according to the spec https://spec.commonmark.org/0.29/#example-365

**Comment by calculuschild** [comment]
I was updating from marked 0.35 to 0.80 and noticed this particular behavior seems to have changed so I wasn't sure. Thanks for the link to the spec; I will close this now.
