### ISSUE TITLE
Converting > into &gt; in code blocks in spite of sanitize: false

### ISSUE THREAD

**Issue by jahio** [markedjs/marked#160]
Hi there,

I'm running into a problem with marked.js where it's rendering markdown correctly except for certain characters in code blocks.

I freely admit that my javascript-fu kinda sucks, so if I'm doing something wrong here or just plain stupid, please let me know so I can go fix it.

The app I'm building is pretty simple - just rendering markdown formatted articles. So the HTML that will come out of the server will _NOT_ have the various symbols - specifically the > sign - escaped. It'll just be totally raw. (I can sanitize/escape it though if that helps, though so far in my testing it's made no difference.)

I might write a post that looks like this (ignore the \ here, I have to escape the markdown syntax inside of markdown on github):

``````

# heading one

paragraph

\```
def foo
  { :foo => "bar" }
end
\```

paragraph
``````

If that's the raw source of my article, everything will be fine except the code block will come off as:

```
def foo
  { :foo =&gt; "bar" }
end
```

Which obviously doesn't work.

I've set sanitize to false in the marked.js settings for the app I'm working on and it's still doing this. I can verify that the raw source of the HTML does _not_ have this already sanitized/escaped, and if I turn off marked.js, the > sign renders correctly (though of course the markdown doesn't).

I've put a small example up on GitHub here:
https://github.com/jaustinhughey/markdownjs-examples/blob/master/markedjs.html

You can see exactly what's going on. Here's a screenshot of what that renders like:
![Screenshot](http://f.cl.ly/items/2i232K1b3X2Z2G0T2y3b/Screen%20Shot%202013-05-21%20at%2011.58.06%20PM.png)

Have I run into a bug here, or am I just missing something?  Thanks guys.

**Comment by mercmobily** [comment]
Sorry to reopen this but... shouldn't this be the default behaviour...?

**Comment by mercmobily** [comment]
Actually I cannot reopen this one... creating a new issue.

**Comment by rezajatnika** [comment]
I had similar issue. Thanks Scott!

**Comment by AeonFr** [comment]
I'm trying to render markdown client-side. After placing the code from [the comment above](https://github.com/chjj/marked/issues/160#issuecomment-18611040)  I'm getting a `content is not defined` error. What does the "content" variable represents and where exactly should I put this code?

**Comment by tbrannt** [comment]
Is there any documentation for features like sanitize? Can't find any

**Comment by semiromid** [comment]
> I'm trying to render markdown client-side. After placing the code from [the comment above](https://github.com/chjj/marked/issues/160#issuecomment-18611040) I'm getting a `content is not defined` error. What does the "content" variable represents and where exactly should I put this code?

Hello! In "content" need code markdown.

**Comment by semiromid** [comment]
> You can modify the tokens between the lexing and parsing to prevent the code blocks from getting encoded:
> 
> ```js
> // Let marked do its normal token generation.
> tokens = marked.lexer( content );
> 
> // Mark all code blocks as already being escaped.
> // This prevents the parser from encoding anything inside code blocks
> tokens.forEach(function( token ) {
>     if ( token.type === "code" ) {
>         token.escaped = true;
>     }
> });
> 
> // Let marked do its normal parsing, but without encoding the code blocks
> parsed = marked.parser( tokens );
> ```

my code has become like a string:

`  var i;for (i=0; i<5; i++) {console.log(i); }`

instead

```
  var i;
  for (i=0; i<5; i++) {
  console.log(i);
  }

```

**Comment by tinmarino** [comment]
(comment not related to markedjs but can help future viewers)

The [above comment](https://github.com/markedjs/marked/issues/160#issuecomment-18611040) worked.

I also had to replace `document.body.innerHTML` by `document.body.textContent` to get the source.

**Comment by thooyork** [comment]
Had a similar problem with marked.parse after an update of the marked version. I am rendering diagrams from code-blocks which then should appear a simages in the application, but after the marked update where interpreted as escaped sourcecode. The solution provided by  @scottgonzalez

```
tokens.forEach(function( token ) {
    if ( token.type === "code" ) {
        token.escaped = true;
    }
});
```

 worked flawlessly ! Thanks !
