### ISSUE TITLE
Convert custom sequences to html

### ISSUE THREAD

**Issue by tvv91** [markedjs/marked#1605]
It's a **question**. Sorry, but I don't know, does it's available to declare custom sequences that will be converting to html tags?
What I mean. For example we have input text

> /This text is now italic./ * And this text is bold. * 

Does it possible (and how if yes) bind "/" and "*" chars to < i > and < b > tags? Output must be:
 _This text is  now italic._ **And this text is bold.**?

**Comment by UziTech** [comment]
You would have to parse the string before you send it to marked or in a render method.

You can see an example of how to do that here: https://github.com/markedjs/marked/issues/1538#issuecomment-526189561
