### ISSUE TITLE
Smartypants outputs wrong quote after emphasis

### ISSUE THREAD

**Issue by rriegs** [markedjs/marked#1606]
**Describe the bug**
With smartypants: true, input with straight quotes immediately after an emphasis marker at the end of a word outputs curly quotes facing the wrong way (i.e. an open quote rather than an end quote).  This occurs for both single and double quotes and both `*` and `_` used singly, doubled, or in combination.

(This is distinct from #1358, which instead concerns emphasis markers *outside* the quotation marks.)

**To Reproduce**
```
"*test*"
```
incorrectly outputs
```
“<em>test</em>“
```
with the trailing quote facing the wrong way.  (Almost invisible in GitHub's font, unfortunately.)

**Expected behavior**
The above should instead output
```
“<em>test</em>”
```
with the trailing quote as an end quote.

**Comment by UziTech** [comment]
This is fixed by using [marked-smartypants](https://www.npmjs.com/package/marked-smartypants) extension
