### ISSUE TITLE
Intra-word emphasis can match the wrong asterisks

### ISSUE THREAD

**Issue by rriegs** [markedjs/marked#1607]
**Describe the bug**
Asterisks may be used to indicate intra-word emphasis, as in `levio*SAH*` for `levio<em>SAH</em>`, however, matching over-aggressively seeks to pair opening asterisks with asterisks at ends of words, sometimes skipping the intended intra-word asterisk.

**To Reproduce**
See this [Marked demo link](https://marked.js.org/demo/?text=It%E2%80%99s%20levi*OH*sa%2C%20not%20levio*SAH.*&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master):
```
It’s levi*OH*sa, not levio*SAH.*
```
yields
```
It’s levi<em>OH<em>sa, not levio</em>SAH.</em>
```
Note the intra-word asterisks are converted to another layer of emphasis, rather than interrupting emphasis as they should.  Another expression of this same bug is [this](https://marked.js.org/demo/?text=*Some*thing%20is%20wrong%20*here*&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master):
```
*Some*thing is wrong *here.*
```
which yields
```
<em>Some*thing is wrong *here</em>
```
leaving unconverted asterisks.

**Expected behavior**
Compare to these [CommonMark Dingus links](https://spec.commonmark.org/dingus/?text=It%E2%80%99s%20levi*OH*sa%2C%20not%20levio*SAH.*), which yield
```
It’s levi<em>OH</em>sa, not levio<em>SAH.</em>
```
[and](https://spec.commonmark.org/dingus/?text=*Some*thing%20is%20wrong%20*here*)
```
<em>Some</em>thing is wrong <em>here</em>
```

**Comment by UziTech** [comment]
see #1522 

There are currently 47 common mark spec tests in the `Emphasis and strong emphasis` category that are not passing.

If you would like to help PRs are always welcome. 😁
