### ISSUE TITLE
"\" encoded to "%5C" makes 404 connection

### ISSUE THREAD

**Issue by Edsuns** [markedjs/marked#1608]
**Describe the bug**
Some markdown image links may have "\\", which will be encoded to "%5C" and lead to a 404 connection.
![2020-02-25 141018.png](http://ww1.sinaimg.cn/large/0072NOVIgy1gc8mbjdpr1j30gt07tq3i.jpg)

**To Reproduce**
Use a image link with "\\"

**I solve it like below**
![2020-02-25 140714.png](http://ww1.sinaimg.cn/large/0072NOVIgy1gc8mi9ux1vj30ed07ymxu.jpg)

**Comment by UziTech** [comment]
A pull request would be more helpful. It will run the tests against your fix to make sure it isn't breaking anything else. Thanks. 😊👍

**Comment by UziTech** [comment]
seems like commonmark also encodes them as %5c so I don't think this is something we will change

[demo](https://spec.commonmark.org/dingus/?text=!%5Bimg%5D(..%5Cimag.png))

**Comment by Edsuns** [comment]
OK, I know that. Thanks.
