### ISSUE TITLE
[Question] About semantic

### ISSUE THREAD

**Issue by DonaldDai** [markedjs/marked#1618]
**What pain point are you perceiving?.**
Hi~ I've used some useful features of Marked in my recent project. It's fast and convenient! But, I was wondering why the **link** and **image** was transformed into type of paragraph instead of link or image. Wouldn't it be more semantic to transform `[...](...)` into link and `![...](...)` into image?
 
**Describe the solution you'd like**
Transforming `[...](...)` into link and `![...](...)` into image seems more semantic.

Look forward to your reply ：D

**Comment by UziTech** [comment]
I'm guessing you are talking about the Lexer using `paragraph` tokens. [demo](https://marked.js.org/demo/?outputType=lexer&text=%5Blink%5D(http%3A%2F%2Fexample.com)%0A%0A!%5Blink%5D(http%3A%2F%2Fexample.com)&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master)

The Lexer only tokenizes block level elements. The [InlineLexer](https://github.com/markedjs/marked/blob/master/src/InlineLexer.js) tokenizes inline elements (like link and image) inside the [Parser](https://github.com/markedjs/marked/blob/master/src/Parser.js).

I'm not sure why it was done that way (probably speed). It would be nice if there was a way to get all tokens including inline before running through the parser.

If you want to work on that I would be happy to review the PR. 😁👍

**Comment by UziTech** [comment]
The Lexer returns all tokens as of v1.0.0
