### ISSUE TITLE
[Question] Can marked return JSON instead of HTML?

### ISSUE THREAD

**Issue by codex-zaydek** [markedjs/marked#1626]
Small question: Can marked.js return JSON instead of HTML?

Thank you.

**Comment by UziTech** [comment]
You can get the block tokens in json by using `marked.lexer(md, options)`. You can see the lexer output in the [demo](https://marked.js.org/demo/?outputType=lexer).

This only shows the block tokens. It does not show the inline tokens inside paragraph tokens.

**Comment by codex-zaydek** [comment]
Thanks! Are there plans to export inline elements to the lexer output as well?

**Comment by UziTech** [comment]
Yes, I am working on that but it might take a while to figure out how to do it without breaking dependencies that work around the current way of doing things.

**Comment by codex-zaydek** [comment]
Ah, thanks! Will close this.
