### ISSUE TITLE
Some way to disable HTML or stop the sanitize warning message..

### ISSUE THREAD

**Issue by cjh9** [markedjs/marked#1628]
Hi! I've been using the `sanitize` option for removing optional HTML, as I'd like the user not be able to input html, only markdown. 

But now It's being deprecated and I get warning messages... How can I disable html and only output the text instead? 

Note I'm not using it for security, I'm using another library, DOMPurify, to actually "sanitize" the output.

**Comment by UziTech** [comment]
you could get the tokens then sanitize the html tokens however you want.

```js
const tokens = marked.lexer(markdown, options);
for (const token of tokens) {
	if (token.type === 'html') {
		token.text = sanitize(token.text);
	}
}
const html = marked.parser(tokens, options);
```

**Comment by UziTech** [comment]
Or you could sanitize in the `text` and `html` renderers

```js
const renderer = new marked.Renderer();
renderer.html = (html) => sanitize(html);
renderer.text = (text) => sanitize(text);
const html = marked(markdown, {renderer});
```

**Comment by styfle** [comment]
There are some other options here: https://github.com/markedjs/marked/issues/1232#issuecomment-414308183

**Comment by cjh9** [comment]
@UziTech Shouldn't there just be a standard option to disable HTML?

**Comment by UziTech** [comment]
HTML is valid markdown according to the [spec](https://spec.commonmark.org/0.29/#html-blocks). We are trying to make marked spec compliant and add more ways to extend marked. There may be a way in the future to have a standard extension that would provide this functionality.

**Comment by cjh9** [comment]
@UziTech Oh I see, thank you for that link. I agree with the approach that https://github.com/markdown-it/markdown-it takes. Disabling HTML and making it safe by default, since that is the way 99% of what the users want. Optionally make HTML work, but then require santizer.

**Comment by mybearworld** [comment]
Sorry for commenting here 4 years later, but:

```js
const preprocess = (markdown) => {
  return markdown
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
};

marked.use({ hooks: { preprocess } });
```

That seems to work for me for disabling HTML.

**Comment by vzakharov** [comment]
> Sorry for commenting here 4 years later, but

Even later to the party, but this solution above will also do the replacement in code blocks, so instead of having them look like

```
<h1>Hello world</h1>
```

you will have

```
&lt;h1&gt;Hello world&lt;/h1&gt;
```

which is of course not what you usually want.

Here’s the solution that worked for me — although I’m still trying to figure out if it’s safe/complete/does not have unwanted side effects:

```js
renderer.html = html => html.replaceAll(/</g, '&lt;')
```

(Note that you don't seem to really need to replace the closing angle bracket, as it alone without a corresponding opening angle bracket won’t render HTML.)

**Comment by Terenfear** [comment]
If someone is still interested, there's another hack: we can override the `html` tokenizer and make it return text tokens.
```
const tokenizer: TokenizerObject = {
  html(src) {
    return {
      type: "text",
      raw: src,
      text: src,
    } as unknown as Tokens.HTML;
  },
};

marked.use({ tokenizer });
```

I've also tried to delegate to the default `text` tokenizer via `marked.defaults.tokenizer.text`, but its result also gets converted to HTML somewhere down the line, no luck.
