### ISSUE TITLE
How format text from commands?

### ISSUE THREAD

**Issue by paulocastellano** [markedjs/marked#1631]
Hi

I want create a toolbar for format text, similar to github issues (here)

<img width="693" alt="Screen Shot 2020-03-26 at 18 06 45" src="https://user-images.githubusercontent.com/265964/77696707-8f63ac00-6f8c-11ea-93bc-42a1bf319c0a.png">

How i can format text?

**Comment by styfle** [comment]
Take a look at the demo page for an example: https://marked.js.org/demo/

The source code is here: https://github.com/markedjs/marked/tree/master/docs/demo

**Comment by UziTech** [comment]
I'm going to close this as answered. If you have any other questions feel free to comment again.

**Comment by bocanhcam** [comment]
@paulocastellano Did you find any solution? I don't see any option for that?
@styfle Am I late? I don't see the demo page has it

**Comment by UziTech** [comment]
@bocanhcam You can change the [renderer](https://marked.js.org/#/USING_PRO.md#renderer) and [tokenizer](https://marked.js.org/#/USING_PRO.md#tokenizer) to do whatever you want.
