### ISSUE TITLE
Link URL With Spaces Does Not Render

### ISSUE THREAD

**Issue by rkever-d** [markedjs/marked#1639]
When a link with spaces in the URL it does render the element as a link.

Examples

- `[My Link](http://somesite.com/my path)`
- `[My Link](http://somesite.com/my file name.pdf)`

When I'm adding the markdown syntax I am now making sure I encode that href url before it gets rendered by marked.

**Comment by UziTech** [comment]
According to the [CommonMark spec](https://spec.commonmark.org/0.29/#example-485):

> The destination can only contain spaces if it is enclosed in pointy brackets

So you would need to use `[My Link](<http://somesite.com/my path>)` or convert spaces to `%20` as `[My Link](http://somesite.com/my%20path)`

**Comment by UziTech** [comment]
It looks like marked doesn't treat pointy brackets correctly in links though so only the percent encoding will work currently.

[demo](https://marked.js.org/demo/?text=%5BMy%20Link%5D(%3Chttp%3A%2F%2Fsomesite.com%2Fmy%20path%3E)&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master)
