### ISSUE TITLE
app crashes after typing ```[Enter]

### ISSUE THREAD

**Issue by lishenyu16** [markedjs/marked#1640]
**0.8.2:**

when I wanted to insert a code block, which should have a format of this:

```js
console.log('sssss');
```

but when after I typed ``` then pressed Enter, app immediately crashes, showing the error message like this: 
'f is not a function...'

![image](https://user-images.githubusercontent.com/16713047/79074424-2032cb00-7ca1-11ea-8b11-b5c9e6303529.png)

could you tell me why, thanks!

**Comment by UziTech** [comment]
What app are you typing that into?

**Comment by lishenyu16** [comment]
> What app are you typing that into?

just a web app using react.

**Comment by UziTech** [comment]
which web app?

**Comment by lishenyu16** [comment]
> which web app?

my own web app that is still under developing, using react

**Comment by lishenyu16** [comment]
do you need more other details, if you want to give it a try I can publish the temp version now

**Comment by UziTech** [comment]
yes, without more details on how you are including marked and using it we cannot know how to help you.

**Comment by lishenyu16** [comment]
marked is a dependency of for-editor-herb package: [https://github.com/HerbertHe/for-editor-herb](url),  and I am using this package for editing markdown

**Comment by UziTech** [comment]
looks like it is an issue in https://github.com/HerbertHe/for-editor-herb/blob/master/src/lib/helpers/marked.ts

This would be a better issue for that repository.

**Comment by lishenyu16** [comment]
I'll look into this, many thanks for pointing out the issue!

**Comment by UziTech** [comment]
I'm going to close this as stale. Feel free to reopen it if you feel we can help.
