### ISSUE TITLE
issue about extend tokenizer and options doc

### ISSUE THREAD

**Issue by hikigaya58** [markedjs/marked#1647]
**Describe the bug**
- The Advanced Usage -> Options in the document has not update to the Extensibility -> Tokenizer chapter, and maybe the lastest release version(v0.8.2) has not support the extend on tokenizer.
- The example code about extend tokenizer to include LaTex maybe have some flaw when `$latex code$` is not the begin of the rest string which has not be processed by Lexer.

**To Reproduce**
- when work with the lastest marked npm release(v0.8.2) to extend tokenizer, there is a error like `Tokenizer() is not a constructor` .
- replace the last line of the example code mentioned above(which is `console.log(marked('$ latex code $', { tokenizer }));`) to this: `console.log(marked('$ latex code $ this is $ latex code $', { tokenizer }));`,you will get a weird result like this:
```
<p><code>latex code</code><code>latex code</code>ex code $</p>
```

**Expected behavior**
release and document will update each other , and the inline `$` pair within other word can lex to proper tokens.

(I download the souce code directly from github, and do below)
In fact, I get a temporary  approach to solve that. At first, I think adding only an anchor `^` will be fine.But after I change the match rule in the example code to `/^\$([^\$\n]+?)\$/`, the output like this:
```
<p><code>latex code</code> this is $ latex code $</p>
```
the second `$` pair is not recognized.
so I read some source code and guess that the text match all rest so `$` pair was recognized as plain text.The rule for inline.text is too complex then I can't understand totally, and  it seems that the `$` has been considered,  maybe something mess the process. And I try to do a tiny change to the inline.text rule, then it works at least partly according to my test.
original:
```
text: /^(`+|[^`])(?:[\s\S]*?(?:(?=[\\<!\[`*]|\b_|$)|[^ ](?= {2,}\n))|(?= {2,}\n))/
```
after change:
```
text: /^(`+|[^`])(?:[\s\S]*?(?:(?=[\\<!\[`*$]|\b_|$)|[^ ](?= {2,}\n))|(?= {2,}\n))/
```
ps: personally I have a suggestion for the `Renderer.codespan(code)` function, maybe give it one more argument `token.raw`. In my case I want give inline latex code surrounded by `$` to katex to render proper math equal, but with current API I can't judge when to use katex or simply embed in `<code>` tag. If raw is given may judge better. **Well, that's my humble opinion, I have not read source code in details so maybe there are other reason like performance or security to be taken in consideration.**

At last, thanks for this amazing project, thanks for all contributer! I am not English native and still not familiar to github so apologize for my possible rude.

**Comment by UziTech** [comment]
The `Tokenizer` was added recently and has not been released yet. The docs will be correct once the `master` branch has been released.

**Comment by UziTech** [comment]
If you want to create a PR to add a `raw` property to the renderer I would be happy to review it.

**Comment by UziTech** [comment]
v1.0 has been released so the docs should be up to date.

**Comment by hikigaya58** [comment]
Thanks for works ! maybe Advanced Usage -> Options  hasn't been updated ?

**Comment by UziTech** [comment]
Nope looks like it hasn't. PRs are welcome 😁
