### ISSUE TITLE
Expose "helper" functions for extensability

### ISSUE THREAD

**Issue by calculuschild** [markedjs/marked#1650]
**Describe the feature**
With the new 1.0.0 update adding extensability, I've noticed that some Tokenizer functions such as `table` also rely on some helper functions (e.g. `splitCells()`) that don't seem to be exposed in any way to the user. I hadn't tested extending those functions until now.

**Why is this feature necessary?**
To easily extend a function (i.e. `Tokenizer.table()`) that currently uses these helper functions without having to copy/paste the helper function into my own sourcecode.

**Describe alternatives you've considered**
The current solution was just to dig into the source here and copy/paste `splitCells()` from the `helper.js` file.

Unless I'm missing some obvious way of accessing those helper functions, in which case it might need to be updated in the docs (there is no mention of the helper.js file in there).

**Comment by UziTech** [comment]
Those helper functions are more for marked to use internally. I don't think we want to expose them because every time we change them we will have to have a major release.

The easiest thing to do is to copy them as you are that way your implementation doesn't rely on anything in marked not changing.

**Comment by baseplate-admin** [comment]
> The easiest thing to do is to copy them as you are that way your implementation doesn't rely on anything in marked not changing.

can we discuss on this?

Currently the only way to add specific `class` to marked rendered elements is to override the default `render` option. 

If `marked` doesn't expose the internal APIs, then it becomes a mess to override add specific attributes to `render` option

**Comment by UziTech** [comment]
Why is it hard to copy markeds internal apis?

**Comment by baseplate-admin** [comment]
> Why is it hard to copy markeds internal apis?

It's not hard per-se, the problem actually lies with code duplication. 

I actually dont have a strong argument against this, but i could say it would make the life of a developer easier.

**Comment by UziTech** [comment]
Easier how? If every change is a breaking change than they would always need to worry about something breaking their code when something changes. If nothing changes than it is no easier for them. I don't see any benefit.
