### ISSUE TITLE
v1.0.0 newlines inside lists

### ISSUE THREAD

**Issue by 9001** [markedjs/marked#1655]
**Describe the bug**
newlines no longer work inside lists; this seems to be the case regardless if you use break:true or add the double-whitespace

**To Reproduce**
https://marked.js.org/demo/?text=-%20a%0A%20%20a&options=%7B%22breaks%22%3Atrue%2C%22gfm%22%3Atrue%7D&version=master

**Expected behavior**
* a
  a

**Comment by styfle** [comment]
I confirmed, this works correctly in 0.8.2 but broke in 1.0.0, thanks!
