### ISSUE TITLE
Support for checkboxes (github markdown upgrade)

### ISSUE THREAD

**Issue by jfstephe** [markedjs/marked#1658]
**Describe the feature**
I'd like the feature supported in the latest version (at least) gfm:
```
- [ ] foo
- [X] foo
```
- [ ] foo
- [X] foo

**Why is this feature necessary?**
Because sometimes you want to indicate the 'ticked off' nature of a list

**Describe alternatives you've considered**
Currently using strikethrough but not as good.

**Comment by UziTech** [comment]
That should already work. [demo](https://marked.js.org/demo/?text=-%20%5B%20%5D%20foo%0A-%20%5BX%5D%20foo&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master)

**Comment by jfstephe** [comment]
My appologies, I was using an old version of marked.

I did look at the [doc pages](https://marked.js.org/#/README.md#README.md) and the versions of the supported specifications (gfm v0.29 etc) and ended up somewhere that implied that it wasn't in that version, but now I can't find the link(!).

Sorry for wasting your time - awesome library BTW! Thanks!!
