### ISSUE TITLE
Underscores don’t turn into emphasis on 1.0.0

### ISSUE THREAD

**Issue by leafac** [markedjs/marked#1659]
**To Reproduce**

1. [CommonMark Demo](https://spec.commonmark.org/dingus/?text=Using%20emphasis%20with%20_underscores_%2C%20like%20Prettier%20formats%20it.)
1. [Marked Demo, version 1.0.0 doesn’t work](https://marked.js.org/demo/?outputType=html&text=Using%20emphasis%20with%20_underscores_%2C%20like%20Prettier%20formats%20it.&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=1.0.0)
2. [Marked Demo, version 0.8.2 works](https://marked.js.org/demo/?outputType=html&text=Using%20emphasis%20with%20_underscores_%2C%20like%20Prettier%20formats%20it.&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=0.8.2)

**Comment by UziTech** [comment]
Looks like it is failing to detect emphasis because of the comma after the second underscore.

it was removed from the puncuation in [#1644](https://github.com/markedjs/marked/pull/1644/files#diff-e1e485869309483077d12d0f82e79856L181) to pass other tests.

**Comment by leafac** [comment]
Thanks for the great work here, @UziTech.

When can I expect to see a release with this fix in npm?

**Comment by UziTech** [comment]
There are a few more things we want to fix before the next release so I would expect it in about a week or two.
