### ISSUE TITLE
Analysis strategy of markedjs(markedjs的解析策略)

### ISSUE THREAD

**Issue by lightstar99** [markedjs/marked#1665]
what is the analysis strategy of markedjs?（markedjs的解析策略是什么？）
What's the difference with the resolution strategy mentioned by the commonmark?
(与commonmark提到的解析策略一样还是有什么不同？)

**Comment by UziTech** [comment]
I'm not exactly sure what you mean by "analysis strategy" marked uses mostly regex rules to parse the markdown.

**Comment by UziTech** [comment]
I'm closing this with no response. feel free to open it again if you have another question.
