### ISSUE TITLE
Broken <strong> after <em>

### ISSUE THREAD

**Issue by zemlanin** [markedjs/marked#1666]
**Describe the bug**
Update to 1.0.0 broke the case of "emphasis, followed by punctuation, followed by strong" if both emphasis and strong are marked by asterisks

For example, `*em*-**strong**` in 0.8.2 correctly rendered `<p><em>em</em>-<strong>strong</strong></p>`, while 1.0.0 renders `<p><em>em<em>-**strong</em></em></p>`

**To Reproduce**

1. [Marked Demo](https://marked.js.org/demo/?text=*em*-**strong**%0A%0A*em*_**strong**%0A%0A*em*%23**strong**%0A%0A*em*%24**strong**%0A%0A---%0A**strong**-*em*%0A%0A**strong**_*em*%0A%0A**strong**%23*em*%0A%0A**strong**%24*em*%0A%0A---%0A_em_%24__strong__%0A%0A__strong__%24_em_%0A%0A_em_%24**strong**%0A%0A*em*%24__strong__&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=1.0.0)
2. [CommonMark Demo](https://spec.commonmark.org/dingus/?text=*em*-**strong**%0A%0A*em*_**strong**%0A%0A*em*%23**strong**%0A%0A*em*%24**strong**%0A%0A---%0A**strong**-*em*%0A%0A**strong**_*em*%0A%0A**strong**%23*em*%0A%0A**strong**%24*em*%0A%0A---%0A_em_%24__strong__%0A%0A__strong__%24_em_%0A%0A_em_%24**strong**%0A%0A*em*%24__strong__)

**Expected behavior**
`*em*-**strong**` should render `<p><em>em</em>-<strong>strong</strong></p>`

**Comment by calculuschild** [comment]
I believe this is fixed now by #1686

**Comment by zemlanin** [comment]
Yep, looks like it

https://marked.js.org/demo/?text=*em*-**strong**%0A%0A*em*_**strong**%0A%0A*em*%23**strong**%0A%0A*em*%24**strong**%0A%0A---%0A**strong**-*em*%0A%0A**strong**_*em*%0A%0A**strong**%23*em*%0A%0A**strong**%24*em*%0A%0A---%0A_em_%24__strong__%0A%0A__strong__%24_em_%0A%0A_em_%24**strong**%0A%0A*em*%24__strong__&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master

**Comment by UziTech** [comment]
We will release a new version of marked soon with this fix.
