### ISSUE TITLE
Bullets before checkbox

### ISSUE THREAD

**Issue by tracyboehrer** [markedjs/marked#1667]
Given: 

```
Items
- [ ] Item 1
- [ ] Item 2
```

The checkboxes are rendered with both a bullet and the checkbox

**Comment by UziTech** [comment]
marked just outputs the html. css styling is the responsibility of the user.

**Comment by Ionaru** [comment]
I could not find a way to do this with CSS.

**Comment by UziTech** [comment]
@Ionaru you can add a class to a task list item with a renderer:

```js
marked.use({
  renderer: {
    listitem(text, task) {
      if (task) {
        return '<li class="task-list-item">' + text + '</li>\n';
      }
      // use original renderer
      return false;
    }
  }
});
```

for more info about the renderer see the [docs](https://marked.js.org/#/USING_PRO.md#renderer)

**Comment by UziTech** [comment]
Looks like you fixed it! 🍻
https://github.com/Ionaru/easy-markdown-editor/commit/890c72589e7f7deab2c3c3f165619814dd4959e6
