### ISSUE TITLE
Code blocks must be left intact

### ISSUE THREAD

**Issue by fredck** [markedjs/marked#1668]
**Describe the bug**  
Code blocks are very controlled content, where the author has intent (and full responsibility) on everything inside it. Right now, tabs inside code blocks are replaced by 4 spaces. This is (probably in most of the cases) semantically incorrect.

**To Reproduce**  

1.  [Marked Demo](https://marked.js.org/demo/?outputType=html&text=%60%60%60%0A%09%20*%0A%09%20*%09%09const%20modelRoot%20%3D%20editor.model.document.getRoot()%3B%0A%09%20*%09%09const%20firstCell%20%3D%20modelRoot.getNodeByPath(%20%5B%200%2C%200%2C%200%20%5D%20)%3B%0A%09%20*%09%09const%20lastCell%20%3D%20modelRoot.getNodeByPath(%20%5B%200%2C%200%2C%201%20%5D%20)%3B%0A%09%20*%0A%09%20*%09%09const%20tableSelection%20%3D%20editor.plugins.get(%20%27TableSelection%27%20)%3B%0A%09%20*%09%09tableSelection.setCellSelection(%20firstCell%2C%20lastCell%20)%3B%0A%09%20*%0A%09%20*%20%40param%20%7Bmodule%3Aengine%2Fmodel%2Felement~Element%7D%20anchorCell%0A%09%20*%20%40param%20%7Bmodule%3Aengine%2Fmodel%2Felement~Element%7D%20targetCell%0A%60%60%60&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master)
2.  [CommonMark Demo](https://spec.commonmark.org/dingus/?text=%60%60%60%0A%09%20*%0A%09%20*%09%09const%20modelRoot%20%3D%20editor.model.document.getRoot()%3B%0A%09%20*%09%09const%20firstCell%20%3D%20modelRoot.getNodeByPath(%20%5B%200%2C%200%2C%200%20%5D%20)%3B%0A%09%20*%09%09const%20lastCell%20%3D%20modelRoot.getNodeByPath(%20%5B%200%2C%200%2C%201%20%5D%20)%3B%0A%09%20*%0A%09%20*%09%09const%20tableSelection%20%3D%20editor.plugins.get(%20%27TableSelection%27%20)%3B%0A%09%20*%09%09tableSelection.setCellSelection(%20firstCell%2C%20lastCell%20)%3B%0A%09%20*%0A%09%20*%20%40param%20%7Bmodule%3Aengine%2Fmodel%2Felement~Element%7D%20anchorCell%0A%09%20*%20%40param%20%7Bmodule%3Aengine%2Fmodel%2Felement~Element%7D%20targetCell%0A%60%60%60)

**Expected behavior**  
The contents of the code block should be left intact (tabs untouched).

---

Many times, code in a document is used as an example or reference to be copied/pasted or used "as is". Marked is not aware of the purpose of the code, so it should not take action on it and leave it intact.

This is a real world example of this problem: ckeditor/github-writer#170. The code block is a suggestion for changes to source code and they can be merged **as the author wrote it**. Marked is changing the code though and, basically, breaking the author contribution.

I can imagine this being a problem on many other contexts as well.

---

I've seen similar issues here for the same problem. Most of them are not clear and mainly closed. I wanted to refresh this problem with this issue.

**Comment by UziTech** [comment]
Similar to #1559

**Comment by azmy60** [comment]
It looks like this has been fixed since 4.0.14

**Comment by UziTech** [comment]
Not completely lines in code blocks that start with tabs are still converted to spaces. [demo](https://marked.js.org/demo/?outputType=html&text=%60%60%60%0A%09this%20line%20should%20start%20with%20a%20tab%0A%60%60%60&options=%7B%0A%20%22async%22%3A%20false%2C%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22extensions%22%3A%20null%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22hooks%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master)
