### ISSUE TITLE
TokensList.type should expect 'list' value

### ISSUE THREAD

**Issue by aSlug** [markedjs/marked#1675]
### Describe the bug
When using `lexer` on a string that contains a markdown list I get an object with `type = 'list'`, but it is not one of the the available values for the returned `TokensList`'s `type` field (which are `list_start`, `list_end`, `list_item_start`, `list_item_end`, etc...)

Due to this, in a js project the IDE does not suggest `list` as a possible value, while in a ts project this does not compile 
```
marked.lexer(issue.body)
    .filter(t => t.type === 'list')
// error "This condition will always return 'false'"
```

(also `@types/marked` is version `v0.7.4`)

### To Reproduce
The following code in js
````
const body = [
    "- [ ] first",
    "- [x] second",
    "- [x] third",
    "- [ ] fourth",
].join("\n")

const tokens = marked.lexer(body, { gfm: true })
console.log(tokens)
````
outputs this
```
[
  {
    type: 'list',
    raw: '- [ ] first\n- [x] second\n- [x] third\n- [ ] fourth',
    ordered: false,
    start: '',
    loose: false,
    items: [ [Object], [Object], [Object], [Object] ]
  },
  links: [Object: null prototype] {}
]
```

### Expected behavior
I would expect 'list' to be one of the available values for `TokenList.type` since it's the value returned at runtime.

**Comment by UziTech** [comment]
marked does not handle the type definitions. That is done by [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped). This issue should be on that repo.
