### ISSUE TITLE
html to Markdown

### ISSUE THREAD

**Issue by juukee** [markedjs/marked#1678]
**Describe the feature**
A clear and concise description of what you would like.

**Why is this feature necessary?**
A clear and concise description of why.
from html to Markdown
**Describe alternatives you've considered**

**Comment by styfle** [comment]
I don't think this is a feature we want to implement in marked because there would be little to no code reuse.

This should probably be a different package that can parse arbitrary HTML, something you [should not do with regex](https://stackoverflow.com/a/1732454/266535).

**Comment by UziTech** [comment]
This is out of scope for marked
