### ISSUE TITLE
Single emphasis on comments is not consistent with double emphasis

### ISSUE THREAD

**Issue by goodhoko** [markedjs/marked#1679]
**Describe the bug**
Wrapping  a `<!-- -->` comment in single `_` or `*` emphasis is not consistent with wrapping a comment in double `__` or `**` emphasis.

**To Reproduce**

| `md` | `html` |
|------|--------|
| `_<!-- foo -->_` | `_<!-- foo -->_` |
| `*<!-- foo -->*` | `*<!-- foo -->*` |
| `__<!-- foo -->__` | `<strong><!-- foo --></strong>` |
| `**<!-- foo -->**` | `<strong><!-- foo --></strong>` |

1. [Marked Demo](https://marked.js.org/demo/?outputType=html&text=_%3C!--%20foo%20--%3E_%0A%0A*%3C!--%20foo%20--%3E*%0A%0A__%3C!--%20foo%20--%3E__%0A%0A**%3C!--%20foo%20--%3E**%0A&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master)
2. [CommonMark Demo](https://spec.commonmark.org/dingus/?text=_%3C!--%20foo%20--%3E_%0A%0A*%3C!--%20foo%20--%3E*%0A%0A__%3C!--%20foo%20--%3E__%0A%0A**%3C!--%20foo%20--%3E**%0A%0A) (they actually got it right)

**Expected behavior**

| `md` | `html` |
|------|--------|
| `_<!-- foo -->_` | `<em><!-- foo --></em>` |
| `*<!-- foo -->*` | `<em><!-- foo --></em>` |
| `__<!-- foo -->__` | `<strong><!-- foo --></strong>` |
| `**<!-- foo -->**` | `<strong><!-- foo --></strong>` |

**Comment by calculuschild** [comment]
I believe this is fixed by #1686

**Comment by UziTech** [comment]
Should be fixed with marked v1.1.1 :tada:

**Comment by goodhoko** [comment]
@UziTech I can confirm. Thanks a lot! 👍 🖤
