### ISSUE TITLE
"<" Escaped

### ISSUE THREAD

**Issue by katray608** [markedjs/marked#1680]
```javascript
var text = document.getElementById("qsdescription").innerHTML;
var html = marked(text);
document.getElementById("qsdescription").innerHTML = html;
```

Source string：
```
\documentclass{article}

\begin{document}
(3)当 $|z_1|<1,|z_2|<1$时，$|\frac{z_1-z_2}{1-\overline{z_1}z_2}|<1$

\end{document}
```

Output：
```
\documentclass{article}

\begin{document}
(3)当 $|z_1|&lt;1,|z_2|&lt;1$时，$|\frac{z_1-z_2}{1-\overline{z_1}z_2}|&lt;1$

\end{document}
```

"<" Escaped，how to solve this problem？

**Comment by UziTech** [comment]
```js
// <div id="qsdescription"><</div>
var text = document.getElementById("qsdescription").innerHTML;
// browser escapes `<` so text === "&lt;"
var html = marked(text);
// html === marked("&lt;") === "&amp;lt;"
document.getElementById("qsdescription").innerHTML = html;
<div id="qsdescription">&amp;lt;</div>
```

The issue is the browser escaping the html when you assign the variable `text`.

**Comment by katray608** [comment]
> ```js
> // <div id="qsdescription"><</div>
> var text = document.getElementById("qsdescription").innerHTML;
> // browser escapes `<` so text === "&lt;"
> var html = marked(text);
> // html === marked("&lt;") === "&amp;lt;"
> document.getElementById("qsdescription").innerHTML = html;
> // <div id="qsdescription">&amp;lt;</div>
> ```
> 
> The issue is the browser escaping the html when you assign the variable `text`.

Thank you. The issue can be solved by unescape `text` ，”&lt;“ unescape to "<"

```js
var text = document.getElementById("qsdescription").innerHTML;
// browser escapes `<` so text === "&lt;"

var escapetext = escape2Html(text);//”&lt;“ unescape to "<"
var html = marked(escapetext);
document.getElementById("qsdescription").innerHTML = html;

function escape2Html(text) {
  var arrEntities={'lt':'<','gt':'>','nbsp':' ','amp':'&','quot':'"'};
  return text.replace(/&(lt|gt|nbsp|amp|quot);/ig,function(all,t){
    return arrEntities[t];
  });
```

**Comment by UziTech** [comment]
Glad you got it to work!

**Comment by styfle** [comment]
Try `var text = document.getElementById("qsdescription").textContent` instead.

https://developer.mozilla.org/en-US/docs/Web/API/Node/textContent
