### ISSUE TITLE
Characters being double escaped within backticks

### ISSUE THREAD

**Issue by alystair** [markedjs/marked#1688]
**Describe the bug**
Whilst writing documentation I discovered that escaped characters such as `<` are being double escaped, resulting in broken visual output.

This is actively disrupting our activity, would love work around...

**To Reproduce**
1. Use the following markdown source: `` `<div id="root">` `` (include backticks)
2. Generate markdown

**Expected behavior**
Output should visually appear as `<div id="root">`
HTML should be `<code>&lt;div id="root"&gt;</code>`

**Actual behavior**
INSTEAD visually appears as: `&lt;div id="root"&gt;`
and HTML generated is `<code>&amp;lt;div id="root"&amp;gt;</code>`

🤢

**Comment by UziTech** [comment]
I don't think this is an issue in marked. According to this [demo](https://marked.js.org/demo/?outputType=html&text=%60%3Cdiv%20id%3D%22root%22%3E%60&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=1.1.0) it outputs the expected html.

Can you provide more of the code you use?

If you are getting the text to pass to marked by calling `.innerHTML` on an element the browser might be escaping it once so the text you are actually sending to marked is `` 
`&lt;div id="root"&gt;` ``

**Comment by alystair** [comment]
Ok I tracked it down internally, we we're using a string escape function before passing it to marked (making `<` into `&lt;`), as the marked site had huge honking warnings that "Marked does not sanitize the output HTML".

Yet If I remove our escaping, the resulting tags vanish entirely. Still have to diagnose why that happens..

**Comment by alystair** [comment]
Going close this for now and re-open if it ends up being Marked related - cheers.
