### ISSUE TITLE
table parse error when columns over 9

### ISSUE THREAD

**Issue by KrisShin** [markedjs/marked#1690]
**Describe the bug**
table will be parsed as ```<p></p>``` when columns of table over 9.
**To Reproduce**
table with 9 columns is ok but 10 will be parsed as tag 'p'

**Expected behavior**
just support more column, Thanks

**Comment by UziTech** [comment]
Can you provide markdown that doesn't work as expected? This [demo](https://marked.js.org/demo/?text=%7C%201%20%7C%202%20%7C%203%20%7C%204%20%7C%205%20%7C%206%20%7C%207%20%7C%208%20%7C%209%20%7C%2010%20%7C%2011%20%7C%2012%20%7C%2013%20%7C%2014%20%7C%2015%20%7C%2016%20%7C%2017%20%7C%2018%20%7C%2019%20%7C%2020%20%7C%0A%7C---%7C---%7C---%7C---%7C---%7C---%7C---%7C---%7C---%7C----%7C----%7C----%7C----%7C----%7C----%7C----%7C----%7C----%7C----%7C----%7C%0A%7C%201%20%7C%202%20%7C%203%20%7C%204%20%7C%205%20%7C%206%20%7C%207%20%7C%208%20%7C%209%20%7C%2010%20%7C%2011%20%7C%2012%20%7C%2013%20%7C%2014%20%7C%2015%20%7C%2016%20%7C%2017%20%7C%2018%20%7C%2019%20%7C%2020%20%7C&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master) has 20 columns and works just fine.

**Comment by KrisShin** [comment]
> Can you provide markdown that doesn't work as expected? This [demo](https://marked.js.org/demo/?text=%7C%201%20%7C%202%20%7C%203%20%7C%204%20%7C%205%20%7C%206%20%7C%207%20%7C%208%20%7C%209%20%7C%2010%20%7C%2011%20%7C%2012%20%7C%2013%20%7C%2014%20%7C%2015%20%7C%2016%20%7C%2017%20%7C%2018%20%7C%2019%20%7C%2020%20%7C%0A%7C---%7C---%7C---%7C---%7C---%7C---%7C---%7C---%7C---%7C----%7C----%7C----%7C----%7C----%7C----%7C----%7C----%7C----%7C----%7C----%7C%0A%7C%201%20%7C%202%20%7C%203%20%7C%204%20%7C%205%20%7C%206%20%7C%207%20%7C%208%20%7C%209%20%7C%2010%20%7C%2011%20%7C%2012%20%7C%2013%20%7C%2014%20%7C%2015%20%7C%2016%20%7C%2017%20%7C%2018%20%7C%2019%20%7C%2020%20%7C&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master) has 20 columns and works just fine.

thanks for your help,
I'll check my code

**Comment by styfle** [comment]
Closing since it is not reproducible
