### ISSUE TITLE
Renderer filter headings - Can't get current slug

### ISSUE THREAD

**Issue by jenstornell** [markedjs/marked#1691]
I filter the headings to create a TOC. I also want to get the slug. I tried to output `slugger`. That gives an object with a full list of slugs, not just the current one.

I can't just use a regex to generate the slug inside the function because there may be multiple headings with the same generated ID and then it would not match.

1. Can this be solved in my code today?
1. Would it be good to provide a fifth argument called `slug`?

```js
var editor.toc = [];

function filterHeadings(renderer) {
  const heading = renderer.heading.bind(renderer);

  renderer.heading = (text, level, raw, slugger) => {
    editor.toc.push({
      level: level,
      text: text,
      slug: slug, // Not possible
    });

    return heading(text, level, raw, slugger);
  };

  return renderer;
}
```

**Comment by UziTech** [comment]
from the [docs](https://marked.js.org/#/USING_PRO.md#renderer):

> slugger has the slug method to create a unique id from value:
>
>     slugger.slug('foo')   // foo
>     slugger.slug('foo')   // foo-1
>     slugger.slug('foo')   // foo-2
>     slugger.slug('foo 1') // foo-1-1
>     slugger.slug('foo-1') // foo-1-2

**Comment by UziTech** [comment]
marked also provides the Slugger class on the marked object so your code could be:

```js
var editor.toc = [];

function filterHeadings(renderer) {
  const tocSlugger = new marked.Slugger();
  const heading = renderer.heading.bind(renderer);

  renderer.heading = (text, level, raw, slugger) => {
    editor.toc.push({
      level: level,
      text: text,
      slug: tocSlugger.slug(text),
    });

    return heading(text, level, raw, slugger);
  };

  return renderer;
}
```

**Comment by UziTech** [comment]
@jenstornell did that help your situation?

**Comment by UziTech** [comment]
If this is still an issue feel free to reopen it.
