### ISSUE TITLE
overwrite Indented code blocks but keep Fenced code blocks

### ISSUE THREAD

**Issue by jackusay** [markedjs/marked#1696]
I would like to overwrite `Indented code blocks` render without overwrite `Fenced code blocks`.
Is that possible in current marked?

Indented code blocks: is some space before text
Fenced code blocks: is ``` before and after your text

I overwrite Indented code blocks via https://github.com/markedjs/marked/issues/1302#issuecomment-401803054

```js
const marked = require('marked');
const renderer = new marked.Renderer();

renderer.code = function (text) {
  return text;
};

console.log(marked(markdownString, { renderer: renderer }));
```

but it also overwrites Fenced code blocks.

---
my situation is 
I write markdown with html, and I always _format_ my html.
So it treats my some html into `<pre><code>...</code></pre>`.
And I only use Fenced code blocks... Indented code blocks kind of useless to me... (_someone really use Indented code blocks?_)

**Comment by UziTech** [comment]
Your best bet would be to override the [tokenizer](https://marked.js.org/#/USING_PRO.md#tokenizer). It has separate tokenizers for code (indented code) and fences (fenced code).

Or you could unformat you code before sending it to marked. Something like:

```js
marked(markdown.replace(/^\s+/gm, ''));
```

**Comment by jackusay** [comment]
It works! thank you!

```js
const marked = require('marked');
const renderer = new marked.Renderer();


// Override function
const tokenizer = {
  code(src, tokens) {
    const cap = this.rules.block.code.exec(src);
    if (cap) {
      const lastToken = tokens[tokens.length - 1];
      // An indented code block cannot interrupt a paragraph.
      if (lastToken && lastToken.type === 'paragraph') {
        return {
          raw: cap[0],
          text: cap[0].trimRight()
        };
      }

      //const text = cap[0].replace(/^ {4}/gm, '');
      return {
        type: 'html',
        raw: cap[0],
        text: cap[0]
      };
    }
  }
};

marked.use({ tokenizer });

var fs = require('fs');
var markdownString = fs.readFileSync('txt.md', 'utf8');

//markdownString = '    ##dsfsf';

console.log(marked(markdownString));
```

ref:
https://github.com/markedjs/marked/blob/master/src/Tokenizer.js#L82

https://github.com/markedjs/marked/blob/04ea199b5377eeab5042723a58e8e8e268beedef/src/rules.js#L10
