### ISSUE TITLE
Markdown not rendered when enter in the markdown

### ISSUE THREAD

**Issue by Maratonec** [markedjs/marked#1697]
**What pain point are you perceiving?.**
I am using SimpleMDE as a editor for markdown, from which it is saved to MySql. Problem is that when user in the editor press enter, the markdown isn't then rendered by marked. But when user type `<br>` in the editor it works.

My code for render:
`marked.setOptions({  gfm: true, breaks: true});
    document.getElementById('render').innerHTML = marked("<?php echo $rows[1]; ?>");`

How it looks in MySgl:

**This is not rendered**
`hello`
`hi`
 **This is rendered**
`hi<br>hello`
**Describe the solution you'd like**
Implement this feature/fix the bug. Or tell me what I am doing wrong

**Comment by UziTech** [comment]
The `breaks: true` option tells marked to use `<br>` instead of `\n` between lines in a paragraph.

**Comment by Maratonec** [comment]
So what should I use to be markdown  rendered?

**Comment by Maratonec** [comment]
So i remove the breaks: true and it still not work, when i have multiplelines.

**Comment by Maratonec** [comment]
Please tell me what can I do. The exact process i did:

I have SimpleMDE with this inside:

#hi testing
**if it works**

Then I get the value of the text field and save it to database. And then I am loading it directly to marked. I want to do it this way because I dont want to render html tags.

**Comment by Maratonec** [comment]
So now I found that hte problem is causing is that I am inserting text with line break to javascript which will not work.

**Comment by Maratonec** [comment]
I found a solution I have to use `.
