### ISSUE TITLE
Two spaces at end of a line do not consistently result in a line-break

### ISSUE THREAD

**Issue by loreanvictor** [markedjs/marked#1699]
**Describe the bug**

According to [common mark spec](https://spec.commonmark.org/0.29/#example-630), two spaces at the end of a line should result in a hard line-break. It seems that styled text (_emphasize_, **strong**), followed by a colon (`:`), followed by two spaces, do not result in a hard-line break.

**To Reproduce**
1. [Marked Demo](https://marked.js.org/demo/?text=first%20%20%0Asecond%0A%0A**first**%20%20%0Asecond%0A%0A_first_%20%20%0Asecond%0A%0Afirst%3A%20%20%0Asecond%0A%0A**first**%3A%20%20%0Asecond%0A%0A_first_%3A%20%20%0Asecond%0A&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master)
2. [CommonMark Demo](https://spec.commonmark.org/dingus/?text=first%20%20%0Asecond%0A%0A**first**%20%20%0Asecond%0A%0A_first_%20%20%0Asecond%0A%0Afirst%3A%20%20%0Asecond%0A%0A**first**%3A%20%20%0Asecond%0A%0A_first_%3A%20%20%0Asecond%0A%0A)

**Expected behavior**

Behavior is in sync with common mark spec (so common mark demo and markedjs demo both yield the same result with given sample text).

**Comment by UziTech** [comment]
It works correctly if you use the `breaks` option but that will also add breaks without two spaces at the end.

**Comment by loreanvictor** [comment]
A simpler work-around for now is adding a `&puncsp;` before or after the colon, which wouldn't have those side-effects as well.

**Comment by grumpygary** [comment]
Also, if an exclamation point is at the end of the line, the two spaces appear to be ignored.

```
marked("Hello  \nworld",{ renderer: new marked.Renderer() });
```

Hello
world


```
marked("Hello!  \nworld",{ renderer: new marked.Renderer() });
```

Hello! world

**Comment by loreanvictor** [comment]
any news on this issue?

**Comment by UziTech** [comment]
According to the [demo](https://marked.js.org/demo/?text=first%20%20%0Asecond%0A%0A**first**%20%20%0Asecond%0A%0A_first_%20%20%0Asecond%0A%0Afirst%3A%20%20%0Asecond%0A%0A**first**%3A%20%20%0Asecond%0A%0A_first_%3A%20%20%0Asecond%0A&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master) this seems to be fixed
