### ISSUE TITLE
TypeError: src.replace is not a function

### ISSUE THREAD

**Issue by dwilches** [markedjs/marked#1705]
**Describe the bug**

When used `marked` I got this error message:

![image](https://user-images.githubusercontent.com/3975401/84523273-e7a57280-ac8c-11ea-9c84-2e208f948c63.png)

**To Reproduce**
I'm using the same code in other places and the error doesn't reproduce, even with the same input, so, I don't know how to reproduce it sorry. I hope the stack trace gives you enough information.

**Expected behavior**
The visual effect is the expected one, so the only unexpected thing is this error popping up in the console.

**Comment by UziTech** [comment]
What version of marked are you using?

**Comment by dwilches** [comment]
Doh, sorry for making this issue. I found out we have pinned marked at this commit: https://github.com/markedjs/marked/commit/1c188ebb55ef512653e03b0a03e60d7209a3bc73

Which is 4 years old. I guess this issue should be fixed by now?

**Comment by UziTech** [comment]
most likely. Try to update marked and see if the issue still exists. There has been quite a bit that has changed in the last 4 years so if you are extending marked in any way and need help upgrading the code to be compatible with newer versions feel free to ask.

**Comment by dwilches** [comment]
Sure. I'll close the issue now, it will take a time upgrading it and checking everything works.
Thanks.
