### ISSUE TITLE
Documentation: how to rewrite src links via marked

### ISSUE THREAD

**Issue by hybridherbst** [markedjs/marked#1707]
**Describe the feature**
I'm not sure if this already works - probably it does - but it's not documented as far as I can see.
How can I rewrite links when parsing a .md with marked? Reason: say I'm fetching the .md from somwhere and want to display it on another host, but rewrite all src attributes that are local on the source to now be absolute (or different) pathes after embedding.

**Why is this feature necessary?**
Sometimes it's necessary to embed markdowns from a different domain but referenced images and local links etc. should still work

**Describe alternatives you've considered**
I think this might (?) be possible using the Lexer, but I couldn't find documentation for it and _think_ this should be a pretty basic thing that requires better documentation.

**Comment by UziTech** [comment]
You will probably need to change the link [renderer]( https://marked.js.org/#/USING_PRO.md#renderer).

**Comment by hybridherbst** [comment]
Thank you, I'll try that!

By the way, directly clicking on the link in the notification mail sent by GitHub gave me a very ironic page:
![image](https://user-images.githubusercontent.com/2693840/84578250-f04c9480-adc3-11ea-90b4-2a580cc86f9e.png)
