### ISSUE TITLE
Website loading speed:

### ISSUE THREAD

**Issue by Ritwik880** [markedjs/marked#1709]
**Describe the bug**
The following requests are returning 404/410 responses. . Either fix the broken links, or remove the references to the non-existent resources. the server will issue 404 "Not found" or 410 "Gone" responses.

**To Reproduce**
Remove the broken links or requests that result in 404/410 errors, avoids wasteful requests.

![Screenshot (30)](https://user-images.githubusercontent.com/54446880/84587220-fb8ed700-ae3a-11ea-82ff-f0018897dab0.png)

**Comment by UziTech** [comment]
Which links are not working?
