### ISSUE TITLE
Punctuation marks are not formatted if they're after a text

### ISSUE THREAD

**Issue by palankid** [markedjs/marked#1713]
**Describe the bug**

Italic style is not applied to punctuation marks. This is not an issue with bold style.

![image](https://user-images.githubusercontent.com/60361973/85281198-dc6ef580-b489-11ea-86d6-96ec8fc6c8e5.png)

**To Reproduce**

[Marked Demo](https://marked.js.org/demo/?outputType=html&text=World_%2C_%0A%0AWorld**%2C**&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master)

**Expected behavior**

`World<em>,</em>`

**Comment by UziTech** [comment]
This actually seems to be an issue with the bold style.

[commonmark demo](https://spec.commonmark.org/dingus/?text=World_%2C_%0A%0AWorld**%2C**)

According to the [spec](https://spec.commonmark.org/0.29/#example-352):

> This is not emphasis, because the opening * is preceded by an alphanumeric and followed by punctuation, and hence not part of a [left-flanking delimiter run](https://spec.commonmark.org/0.29/#left-flanking-delimiter-run)

**Comment by calculuschild** [comment]
These things are all fixed with my PR #1706

**Comment by palankid** [comment]
I get that bold is misbehaving in my example according to the common mark spec, but I don't fully get what's going to be fixed. Would my example work as expected or they will read as 
`World_!_`
`World**!**`
after conversion when your PR is merged?

**Comment by UziTech** [comment]
It will display `World**!**` since that is what the spec says it is supposed to. If you want to make just the exclamation point bold you will have to use HTML like `World<strong>!</strong>`
