### ISSUE TITLE
简体中文（中华人民共和国）：对于require的语法错误

### ISSUE THREAD

**Issue by awathefox** [markedjs/marked#1714]
我尝试在我的网页中加入marked，但出现了以下错误：
Uncaught Error: Module name "Lexer.js" has not been loaded yet for context: _. Use require([])
https://requirejs.org/docs/errors.html#notloaded
    at makeError (require.js:168)
    at Object.localRequire [as require] (require.js:1436)
    at requirejs (require.js:1797)
    at marked.js:2
makeError @ require.js:168
localRequire @ require.js:1436
requirejs @ require.js:1797
(anonymous) @ marked.js:2
这是因为marked.js语法不规范导致的。
希望解决。

**Comment by UziTech** [comment]
Can you provide more code about what version you are using and how you are loading marked?

**Comment by awathefox** [comment]
简体中文（中华人民共和国）：
对于
(Google Translate)您能否提供有关所使用的版本以及如何加载的更多代码？
的回复：
已经将出错代码放置在https://github.com/awathefox/awathefox.github.io/blob/master/res/errors/marked_error_01.rar
。
这是对Node.JS专用的代码吗？如果是，我将关闭issue。

**Comment by UziTech** [comment]
Try using [/lib/marked.js](https://github.com/markedjs/marked/blob/master/lib/marked.js) instead of the files in the /src/ folder. It is bundled to work in browsers. I haven't tested it with RequireJS but it should work.
