### ISSUE TITLE
escape <> while rendering "pre" code blocks

### ISSUE THREAD

**Issue by chendifan** [markedjs/marked#1715]
I report this first in https://github.com/hexojs/hexo-renderer-marked/issues/153

I'm using this:

``` json
{
  "hexo": {
    "version": "4.2.1"
  },
  "dependencies": {
    "hexo": "^4.2.1",
    "hexo-abbrlink": "^2.0.5",
    "hexo-generator-archive": "^1.0.0",
    "hexo-generator-category": "^1.0.0",
    "hexo-generator-feed": "^2.2.0",
    "hexo-generator-index-pin-top": "^0.2.2",
    "hexo-generator-search": "^2.4.0",
    "hexo-generator-searchdb": "^1.3.0",
    "hexo-generator-tag": "^1.0.0",
    "hexo-lazyload": "^1.3.6",
    "hexo-renderer-ejs": "^1.0.0",
    "hexo-renderer-marked": "^2.0.0",
    "hexo-renderer-stylus": "^1.1.0",
    "hexo-server": "^1.0.0"
  }
}
```

> ~~`"hexo-renderer-marked": "^2.0.0"` is using `"marked": "^1.0.0"`~~
> "hexo-renderer-marked": "^2.0.0" is using "marked": "^0.7.0"

I wrote this:

![image](https://user-images.githubusercontent.com/22953986/85310801-0aceee00-b4e7-11ea-9ed0-9402d697a7d0.png)

and Github can render it correctly(as you can see below):

``` xml
<dependency>
    <groupId>com.cdf</groupId>
    <artifactId>meizu</artifactId>
    <version>1.0-SNAPSHOT</version>
</dependency>
```

but I got a rendered HTML with some problems in my generated hexo static pages:

![image](https://user-images.githubusercontent.com/22953986/85310692-e7a43e80-b4e6-11ea-89f6-dc6dad0c489b.png)

> actually we lost both `<` and `/`

**Comment by UziTech** [comment]
This looks like it is an issue with highlighting. marked seems to handle this correctly: [demo](https://marked.js.org/demo/?text=%60%60%60xml%0A%3Cdependency%3E%0A%20%20%20%20%3CgroupId%3Ecom.cdf%3C%2FgroupId%3E%0A%20%20%20%20%3CartifactId%3Emeizu%3C%2FartifactId%3E%0A%20%20%20%20%3Cversion%3E1.0-SNAPSHOT%3C%2Fversion%3E%0A%3C%2Fdependency%3E%0A%60%60%60&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=1.0.0)

**Comment by chendifan** [comment]
sorry, I should correct the claim of version:
**"hexo-renderer-marked": "^2.0.0" is using "marked": "^0.7.0"**

**Comment by chendifan** [comment]
but it also works fine:
![image](https://user-images.githubusercontent.com/22953986/85428832-5b5e4e00-b5b0-11ea-8c0c-207f8b585939.png)

but when I turn off the "highlighting" the issue is still there..😢

**Comment by UziTech** [comment]
I'm not sure what is causing this but unless you can reproduce it in a [demo](https://marked.js.org/demo/) I don't think there is anything we can change in marked to fix it.

**Comment by chendifan** [comment]
UPDATE: the issue gone away after uninstalling `"hexo-lazyload": "^1.3.6"`
