### ISSUE TITLE
Unexpected result with GFM

### ISSUE THREAD

**Issue by irqbank** [markedjs/marked#1717]
**Describe the bug**

Input ```*aa*. *b*``` results in output ```<p><em>aa*. *b</em></p>``` with GFM.

**To Reproduce**

Marked Demo: [demo](https://marked.js.org/demo/?outputType=html&text=*aa*.%20*b*&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master)

**Expected behavior**

Input ```*aa*. *b*``` results in output ```<p><em>aa</em>. <em>b</em></p>``` with GFM. CommonMark Demo: [demo](https://spec.commonmark.org/dingus/?text=*aa*.%20*b*)

**Workaround**

Set ```pedantic``` to true

**Comment by UziTech** [comment]
This should be fixed by #1686

**Comment by calculuschild** [comment]
Can confirm this is fixed now.

**Comment by UziTech** [comment]
Should be fixed with marked v1.1.1 :tada:
