### ISSUE TITLE
Homepage/docs is misleading about CommonMark/GFM "support"

### ISSUE THREAD

**Issue by vassudanagunta** [markedjs/marked#1718]
**Describe the bug**
The [Marked Homepage/README](https://marked.js.org) needs to clarify what it means when it says it "We actively support the features of" CommonMark and GitHub Flavored Markdown. 

No where does it mention that Marked is not in full compliance with either spec, that it is in fact a work in progress.

In case the latter point is in dispute, here are some examples:

- CommonMark compliance #1202 
- Markdown containing tabs not converted properly to spaces #1559
- Code blocks must be left intact #1668

**To Reproduce**

Two of the above issues already include reproduction steps. But here's another:

1. [Marked Demo](https://marked.js.org/demo/?text=0123456789%0A%3E%0A%3E%20%20%20%20%20five%20spaces%0A%3E%09%09two%20tabs%0A%3E%09%20%20one%20tab%20%2B%20two%20spaces%0A%3E%09%20one%20tab%20%2B%20one%20space%0A%3E%09one%20tab%0A&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master)
2. [CommonMark Demo](https://spec.commonmark.org/dingus/?text=0123456789%0A%3E%0A%3E%20%20%20%20%20five%20spaces%0A%3E%09%09two%20tabs%0A%3E%09%20%20one%20tab%20%2B%20two%20spaces%0A%3E%09%20one%20tab%20%2B%20one%20space%0A%3E%09one%20tab%0A)

**Expected behavior**

One of the following:
- Full CommonMark/GFM compliance
- The advertising/documentation is updated to say that compliance is not complete. And it does so *prominently*, otherwise it's dishonest.

**Comment by UziTech** [comment]
PRs are welcome 😁
