### ISSUE TITLE
Marked server utilized for Babelmark 2 is using Marked 0.5.2

### ISSUE THREAD

**Issue by vassudanagunta** [markedjs/marked#1719]
**To Reproduce**

1. Test any Markdown on [Babelmark 2](https://johnmacfarlane.net/babelmark2/?normalize=1&text=0123456789%0A%3E%0A%3E+++++five+spaces%0A%3E%09%09two+tabs%0A%3E%09++one+tab+%2B+two+spaces%0A%3E%09+one+tab+%2B+one+space%0A%3E%09one+tab%0A)
2. Note the version of marked in the left column.

**Comment by UziTech** [comment]
Not sure how we can update that. Seems like an issue for that repo.

**Comment by vassudanagunta** [comment]
Are you saying Marked doesn't provide the server? In any case, if you want people to have an accurate view of Marked, I'd send an email to JGM. See https://johnmacfarlane.net/babelmark2/faq.html#how-can-i-add-my-markdown-implementation-to-babelmark-2

**Comment by UziTech** [comment]
I don't think we provide the server. I have heard of it but have never used it. @styfle @joshbruce @davisjam  @Feder1co5oave Does anyone know where the server is for that?

It looks like there is a [babelmark 3](https://babelmark.github.io/) but marked doesn't seem to be on it 🤔.

Maybe we could provide servers in the `docs` folder.

@vassudanagunta if you want to create a PR for that it would be very helpful 😁.

**Comment by vassudanagunta** [comment]
@UziTech I would if I weren't working on ***TextPlain***, a generalized lightweight markup parser/renderer for which Markdown/CommonMark is just a "configuration". 

The reason I've been looking at Marked is because I've been doing performance comparisons. Marked is faster than CommonMark.js and Markdown-it in a few areas, but when I looked into it I discovered that Marked doesn't fully implement the spec, which might/likely accounts for the speed differences. All those corner cases come at a cost.  In other words [comparative benchmarks that include Marked](https://github.com/commonmark/commonmark.js/blob/master/bench/bench.js) aren't fair a fair comparison.

Now if you have questions about how to implement those corner cases, feel free to ask. TextPlain passes all tests but the `tab` related ones, which I've just deferred to a later dev phase.

**Comment by styfle** [comment]
> Maybe we could provide servers in the docs folder.

Yeah we can do this with Vercel but not GitHub Pages. I’ll create a PR once I’m back to my computer in a couple days.

**Comment by styfle** [comment]
I created PR #1742

**Comment by styfle** [comment]
I sent an email to the Bablemark 2 maintainer as well as the Babelmark 3 maintainer with our official API.

Hopefully we'll hear from them soon and get this updated, thanks!

**Comment by styfle** [comment]
Both have been updated 💯
