### ISSUE TITLE
Indented text gets rendered as codeblock

### ISSUE THREAD

**Issue by Rafi993** [markedjs/marked#1721]
**Describe the bug**
 When you indent text and have newline above and below it. It gets rendered as codeblock

**To Reproduce**
1. Visit  https://marked.js.org/demo/?text=2312313112321%0A%0A%20%20%20%20text%0A%20%20%20%20another%20text%0A%20%20%20%20testing%20again%0A%0A12312312321312&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master
1. Text in the middle renders as code block even though it is not

![code_block](https://user-images.githubusercontent.com/8092120/86756251-e2ef9680-c05f-11ea-80eb-f03cb5def6a2.png)

**Expected behavior**
Should render the indented test should not render as code block

**Comment by UziTech** [comment]
That is working according to the [spec](https://spec.commonmark.org/0.29/#indented-code-blocks)

**Comment by UziTech** [comment]
You can override the code tokenizer to remove the indented code token:

```js
// Create reference instance
const marked = require('marked');

// Override function
const tokenizer = {
  code(src) {
    // return undefined to prevent token creation
  }
};

marked.use({ tokenizer });

// Run marked
console.log(marked(`2312313112321

    text
    another text
    testing again

12312312321312`));

/*
<p>2312313112321</p>
<p>    text
    another text
    testing again</p>
<p>12312312321312</p>
*/
```

**Comment by Rafi993** [comment]
> You can override the `code` tokenizer to remove the indented code token:
> 
> ```js
> // Create reference instance
> const marked = require('marked');
> 
> // Override function
> const tokenizer = {
>   code(src) {
>     // return undefined to prevent token creation
>   }
> };
> 
> marked.use({ tokenizer });
> 
> // Run marked
> console.log(marked(`2312313112321
> 
>     text
>     another text
>     testing again
> 
> 12312312321312`));
> 
> /*
> <p>2312313112321</p>
> <p>    text
>     another text
>     testing again</p>
> <p>12312312321312</p>
> */
> ```

but won't that also remove ```<code>``` tag for things surrounded by backtics

**Comment by UziTech** [comment]
> but won't that also remove `<code>` tag for things surrounded by backtics

no that is handled by the `fences` [tokenizer](https://marked.js.org/#/USING_PRO.md#tokenizer).

**Comment by Rafi993** [comment]
> ```js
> const tokenizer = {
>   code(src) {
>     // return undefined to prevent token creation
>   }
> };
> 
> marked.use({ tokenizer });
> ```

Thanks @UziTech
