### ISSUE TITLE
Markdown `*emphasis* inside a paragraph emits incorrect HTML unless it's on the first or last line

### ISSUE THREAD

**Issue by garybernhardt** [markedjs/marked#1727]
**Describe the bug**
Markdown `*emphasis* inside a paragraph emits incorrect HTML unless it's on the first or last line.

**To Reproduce**
[Here's](https://marked.js.org/demo/?text=This%20line%20has%20an%20*em*%20in%20the%20middle.%0AThis%20line%20has%20an%20em%20at%20the%20*end*.%0AThis%20*line*%20has%20an%20em%20in%20the%20middle.%0AThis%20*line*%20has%20an%20em%20in%20the%20middle%20and%20at%20the%20*end*.%0A&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master) what Marked does. Notice that the middle two lines both have one half of an `<em>` (but different halves!), and in each case one of the `*`s persists in the output. The first and last lines are unaffected.
[Here's](https://spec.commonmark.org/dingus/?text=This%20line%20has%20an%20*em*%20in%20the%20middle.%0AThis%20line%20has%20an%20em%20at%20the%20*end*.%0AThis%20*line*%20has%20an%20em%20in%20the%20middle.%0AThis%20*line*%20has%20an%20em%20in%20the%20middle%20and%20at%20the%20*end*.%0A) what commonmark does, which is correct.

**Expected behavior**
Markdown with `*emphasis*` should always turn into an `<em></em>` tag.

**Details**
At first I thought that this might be related to #1699, but now that seems unlikely. This bug seems to exist for any `*emphasis*` in any paragraph.

**Comment by UziTech** [comment]
looks like this should be fixed by #1686

**Comment by calculuschild** [comment]
Can confirm this is fixed now.

**Comment by UziTech** [comment]
Should be fixed with marked v1.1.1 :tada:

**Comment by garybernhardt** [comment]
Looks good now. Thanks for the fix!
