### ISSUE TITLE
Add Declaration Files

### ISSUE THREAD

**Issue by qiurenbo** [markedjs/marked#1732]
**What pain point are you perceiving?.**
Now I need install @types/marked before using marked in TS.
 
**Describe the solution you'd like**
Package declaration files with marked.

**Comment by DreierF** [comment]
@UziTech Would you be open for PRs adding the declarations?
If so, would you prefer to have the code migrated to Typescript and therefore ensure the types evolve with the code automatically or would you rather prefer to have them separately and hence keep them up-to-date manually?

**Comment by UziTech** [comment]
We are always open to PRs.

I would like to move the code to typescript, the only problem is that we have some places in the code that are not going to be easy to strictly type.

The other issue is speed. We have optimized parts to be fast and the typescript compiler could slow marked down so we will have to watch out for that.

I'm also not sure if including the type definitions without converting to typescript is the right thing to do. DefinitelyTyped has better support for testing and a larger community.

There is a lot of work that will need to go into converting to typescript but if you are willing to do it I think you can go for it.
