### ISSUE TITLE
Gfm Tables Incorrectly Require Newlines Before Table

### ISSUE THREAD

**Issue by chlafreniere** [markedjs/marked#1733]
gfm tables using marked require a line with just whitespace before the table definition:

```
test
|a|b|
|-|-|
```

renders just fine in GitHub:

test
|a|b|
|-|-|

However, marked doesn't like it and doesn't render a table:
[Marked Demo](https://marked.js.org/demo/?text=test%0A%7Ca%7Cb%7C%0A%7C-%7C-%7C&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master)

```
test

|a|b|
|-|-|
```

works just fine both in marked and in GitHub:

test

|a|b|
|-|-|

(above renders table as expected)

**Expected behavior**
marked's lexer is able to identify tables, even when the preceding line contains anything other than whitespace.

**Comment by mainytht** [comment]
me too ,  not resolved . what now 
 there were a "tables: ture" options ever.
but now it disappeared in the new manual ,why?

**Comment by UziTech** [comment]
You can add a blank line before the table to make it work.

**Comment by EmmetZC** [comment]
Hi, guys.

Are you gonna fix this or do you think this is correct behavior?
