### ISSUE TITLE
How to convert tokens to markdown?

### ISSUE THREAD

**Issue by jet10000** [markedjs/marked#1734]
I found markdown parser to tokens, but how to convert back to markdown?

or how to walk tokens and then back to markdown?

**Comment by UziTech** [comment]
You can walk the tokens by using the [walkTokens](https://marked.js.org/#/USING_PRO.md#walk-tokens) options.

```js
const marked = require('marked');

// Overriding heading tokens to start at h2.
const walkTokens = (token) => {
  if (token.type === 'heading') {
    token.depth += 1;
  }
};

marked.use({ walkTokens });

// Run marked
const html = marked('# heading 2\n\n## heading 3');
```

or you can pass the tokens to `marked.parser(tokens)`

```js
const tokens = marked.lexer(md);

// do something with tokens

const html = marked.parser(tokens);
```

**Comment by jet10000** [comment]
I want to batch replace markdown content and then generate markdown content ,not html.

**Comment by UziTech** [comment]
That is not what marked does. marked generates html from markdown content. You could try creating your own [renderer](https://marked.js.org/#/USING_PRO.md#renderer) but I can't promise that will work.

**Comment by jet10000** [comment]
Now, I use turndown convert html back to markdown.

**Comment by rayfoss** [comment]
Related https://github.com/markdown-it/markdown-it/issues/663
