### ISSUE TITLE
Code Block diff

### ISSUE THREAD

**Issue by bpblakely** [markedjs/marked#1741]
**Describe the feature**
Using github markdown you can use a feature in a code block 'diff' to show the changes in lines of code in a code block:
```diff
  Unchanged Line
- Removed Line
+ Added Line
```
However when compiled with marked.js, it either doesn't work or the syntax highlighting doesn't work. 
The markdown result in google colab (in terms of appearance) is
```
  Unchanged Line
- Removed Line
+ Added Line
```

**Why is this feature necessary?**
Having this feature would make it very easy to show what was changed between different runs of a code block in google colab. It is a better looking format than the alternative which I will show below. 

**Describe alternatives you've considered**
The only alternative I can think of which still shows the same information.

``` Unchanged Line ```
~~```Removed Line ```~~
```Added Line```

In github this doesn't look too bad, when markdown is compiled with marked.js it looks a lot less pleasant. 
I read that you don't support syntax highlighting in code blocks, but that's why it's a feature request I suppose.

**Comment by UziTech** [comment]
marked doesn't do code highlighting by default. You can use the [`highlight`](https://marked.js.org/#/USING_ADVANCED.md#options) option to add a highlighter like [highlight.js](https://highlightjs.org/)

I'm not sure if they have a `diff` highlighter but that would be an issue for that library.
