### ISSUE TITLE
Parsing of whitespace prefixed tables broken after upgrade (0.7.0 => 1.1.1)

### ISSUE THREAD

**Issue by tirithen** [markedjs/marked#1747]
I tried upgrading from version 0.7.0 to version 1.1.1 and got problems with the table syntax. If I enter table syntax as below only part of the table gets parsed. I'm running marked without setting any special options.

If I remove the whitespace before the pipe characters the table parses as expected (the first data row seems okay with extra whitespace as that parses okay in either case), should removing whitespace with regex be mandatory for the table to parse? 

It was really handy in version 0.7.0 when that was handled by the parser itself. :)

Version 1.1.1, stops parsing the table after the first data row

    marked(`lorem ipsum\n\n| Tables   |      Are      |  Cool |
                       |-------|----------|------|
                       | col-1-is |  left-aligned | $1600 |
                       | col-2-is |    centered   |   $12 |
                       | col-3-is | right-aligned |    $1 |\n\nlorem ipsum`)

Output (1.1.1):

    "<p>lorem ipsum</p>
    <table>
    <thead>
    <tr>
    <th>Tables</th>
    <th>Are</th>
    <th>Cool</th>
    </tr>
    </thead>
    <tbody><tr>
    <td>col-1-is</td>
    <td>left-aligned</td>
    <td>$1600</td>
    </tr>
    </tbody></table>
    <pre><code>               | col-2-is |    centered   |   $12 |
                   | col-3-is | right-aligned |    $1 |</code></pre>
    <p>

Version 0.7.0 works as expected:

    marked(`lorem ipsum\n\n| Tables   |      Are      |  Cool |
                       |-------|----------|------|
                       | col-1-is |  left-aligned | $1600 |
                       | col-2-is |    centered   |   $12 |
                       | col-3-is | right-aligned |    $1 |\n\nlorem ipsum`)
Output (0.7.0):

    "<p>lorem ipsum</p>
    <table>
    <thead>
    <tr>
    <th>Tables</th>
    <th>Are</th>
    <th>Cool</th>
    </tr>
    </thead>
    <tbody><tr>
    <td>col-1-is</td>
    <td>left-aligned</td>
    <td>$1600</td>
    </tr>
    <tr>
    <td>col-2-is</td>
    <td>centered</td>
    <td>$12</td>
    </tr>
    <tr>
    <td>col-3-is</td>
    <td>right-aligned</td>
    <td>$1</td>
    </tr>
    </tbody></table>
    <p>lorem ipsum</p>
    "

​The same problem is visible at the Marked Demo page:

https://marked.js.org/demo/?text=lorem%20ipsum%0A%0A%7C%20Tables%20%20%20%7C%20%20%20%20%20%20Are%20%20%20%20%20%20%7C%20%20Cool%20%7C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7C-------%7C----------%7C------%7C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%20col-1-is%20%7C%20%20left-aligned%20%7C%20%241600%20%7C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%20col-2-is%20%7C%20%20%20%20centered%20%20%20%7C%20%20%20%2412%20%7C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%20col-3-is%20%7C%20right-aligned%20%7C%20%20%20%20%241%20%7C%0A%0Alorem%20ipsum&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master

I guess that version 0.7.0 would maybe require two new lines (\n\n) before starting a code block (\n{4,})?

**Comment by tirithen** [comment]
I guess that version 0.7.0 would maybe require two new lines (\n\n) before starting a code block (\n{4,})?

**Comment by UziTech** [comment]
lorem ipsum

| Tables   |      Are      |  Cool |
                       |-------|----------|------|
                       | col-1-is |  left-aligned | $1600 |
                       | col-2-is |    centered   |   $12 |
                       | col-3-is | right-aligned |    $1 |

lorem ipsum

---

It seems like that is not a valid table in gfm. I would consider that undefined behavior. If we were to fix it we would make it look like the gfm above not like a table.

**Comment by tirithen** [comment]
I can see that the sudden indenting is a bit off, I guess it just happened to work in version 0.7.0. I think you guys would be better in sorting out if additional whitespace should be ignored or parsed as table/code. When coding "HTML like" \s+ is usually treated as " " so I guess this was my assumption here as well (one space not being enough to enter a code block).

I tend to like the commonmark standard as they try find common ground on all of the variations, but I'm not an expert on what either gfm/commonmark would state in this case. I just found my test cases failing after upgrading.

Feel free to close this issue if you figure that this is not relevant.

I would however expect two \n\n required to switch from a table to a code block, now it accepts the first indented line and then breaks to code block only on the second indented, I guess that could be more clear (but again not expert enough on gfm/commonmark to tell what should happen).

**Comment by UziTech** [comment]
> I would however expect two \n\n required to switch from a table to a code block.

The [GFM Spec](https://github.github.com/gfm/#tables-extension-) states:
> The table is broken at the first empty line, or beginning of another block-level structure.

Since a code block is a block-level structure it would take precedence over table rows.

This should be fixed to follow the spec in #1748
