### ISSUE TITLE
Chinese cannot indent the first line

### ISSUE THREAD

**Issue by chadspring** [markedjs/marked#1753]
Chinese cannot indent the first line.
Although the first line indentation of Chinese can be realized by using symbols, etc., I hope it can be realized automatically.
![w9D0qU.png](https://s1.ax1x.com/2020/09/03/w9D0qU.png)

**Comment by UziTech** [comment]
Indentation is used for [code blocks](https://spec.commonmark.org/0.29/#indented-code-blocks) in markdown. If you want to indent text but not create a code block you will have to use other symbols like `&nbsp;`.

**Comment by chadspring** [comment]
It would be great if the indentation is still indentation when the paragraph is in Chinese. I will use other symbols like &nbsp;. 
 Thanks anyway.

**Comment by UziTech** [comment]
> It would be great if the indentation is still indentation when the paragraph is in Chinese.

To change the spec you would have to create an issue on https://github.com/commonmark/commonmark-spec
