### ISSUE TITLE
marked.setOptions on browser code

### ISSUE THREAD

**Issue by DragonOsman** [markedjs/marked#1756]
I need to use marked on the browser side, on CodePen, for [this](https://www.freecodecamp.org/learn/front-end-libraries/front-end-libraries-projects/build-a-markdown-previewer) project on the FreeCodeCamp front-end libraries projects curriculum. This is the [code](https://codepen.io/DragonOsman/pen/KKzQexZ) I have right now.  How do I get the `const hljs = require('highlight.js');` line to work on the browser?  Or is there an alternative to this that I can use in the browser?  

Any help is appreciated.  Thanks in advance.

**Comment by UziTech** [comment]
On the browser side you will have to get highlight.js with a script tag instead of require. see [highlight.js docs](https://highlightjs.org/usage/)

**Comment by DragonOsman** [comment]
Alright.  Thanks for the reply and headsup.
