### ISSUE TITLE
Showing rendering results in real time?

### ISSUE THREAD

**Issue by DragonOsman** [markedjs/marked#1759]
Hi, everyone.

This probably isn't the right place for this, but I'll try anyway.

I have [this code](https://codepen.io/DragonOsman/pen/KKzQexZ), which is for doing [this project](https://www.freecodecamp.org/learn/front-end-libraries/front-end-libraries-projects/build-a-markdown-previewer) on FreeCodeCamp.  

I have the previewer working somewhat, but I can't get it to render changes to the markdown in the `textarea` element in the previewer as the user types.  What am I doing wrong here?  Can someone tell me?  Thanks.

**Comment by UziTech** [comment]
You are right, this is not the right place for that kind of help. Your best bet is to ask these type of questions on the [FreeCodeCamp forum](https://forum.freecodecamp.org/)
