### ISSUE TITLE
Provide a function to process inline markup only

### ISSUE THREAD

**Issue by Gittenburg** [markedjs/marked#1760]
**Describe the feature**
This was already possible previously with `marked.inlineLexer(markdown, [], options);` as described in #395.
@UziTech apparently removed that API in 2806c4913c4e26b811f58eafbe73a17a9500d6d4 without providing an alternative?

**Why is this feature necessary?**
If you don't need to sanitize the HTML, having to postprocess it to strip away tags is both inefficient and inconvenient.

It's worth noting that the competitor markdown-it [provides a `renderInline` function](https://github.com/markdown-it/markdown-it#simple), I think it would be great if this more lightweight library would again provide the same simple feature, that existed previously.

**Comment by UziTech** [comment]
We could create a `marked.parseInline()` function. PRs are always welcome. 😁👍

Right now you can do it like this:

```js
const marked = require('marked');
const markdown = '**strong** _em_';
const options = {...};
const lexer = new marked.Lexer(options);
const tokens = lexer.inlineTokens(markdown);
const parser = new marked.Parser(options);
const html = parser.parseInline(tokens);
console.log(html);

```
