### ISSUE TITLE
blockquote cannot be rendered

### ISSUE THREAD

**Issue by RanX12** [markedjs/marked#1764]
**Describe the bug**
Hello, blockquote cannot be rendered, what should I do?

thanks

![image](https://user-images.githubusercontent.com/46048444/94280553-1ddad980-ff80-11ea-8533-cd65b09a661f.png)

This is my code structure：

![image](https://user-images.githubusercontent.com/46048444/94280950-9cd01200-ff80-11ea-85c5-37f33376583e.png)

**Comment by UziTech** [comment]
What version of marked are you using? Can you reproduce this in a [demo](https://marked.js.org/demo/)?

**Comment by RanX12** [comment]
1.I am using: "marked": "^0.7.0"
2.I can’t reproduce it in the address you gave me. I can also render in some places in my project, but not in some places.
![image](https://user-images.githubusercontent.com/46048444/94329023-020c1d80-ffea-11ea-84db-2f7d454416da.png)

**Comment by RanX12** [comment]
Oh! I understand, MarkDown content cannot be obtained through element.html(), but only through element.val(), which means it needs to be placed in the value="" of element.

thanks

**Comment by UziTech** [comment]
yes if you get it through element.html() `>` will be `&gt;` and not count as the beginning of a blockquote.

Glad you figured it out.
