### ISSUE TITLE
Using custom Tokenizer disables url rule

### ISSUE THREAD

**Issue by trevorhreed** [markedjs/marked#1766]
**Workaround**
For those coming from Google looking for a resolution, here's a simple solution:

```javascript
const marked = require('marked')

const lexer = new marked.Lexer({
  ...marked.defaults,
  tokenizer: new marked.Tokenizer()
})

console.log(lexer.tokenizer.rules.inline.url)

```

**Describe the bug**
When creating a lexer and passing in a tokenizer (`tokenzier: new marked.Tokenizer()`), the `url` rule gets assigned a value of `{ exec: [Function: noopTest] }`.

**To Reproduce**
See this example on Repl.it: https://repl.it/@trevorhreed/marked-multi-instance#index.js

Here's the minimal example: 

```javascript
const marked = require('marked')

const lexer1 = new marked.Lexer()
console.log(lexer1.tokenizer.rules.inline.url) // Output: /^((?:ftp|https?):\/\/|www\.)(?:[a-zA-Z0-9\-]+\.?)+[^\s<]*|^[A-Za-z0-9._+-]+(@)[a-zA-Z0-9-_]+(?:\.[a-zA-Z0-9-_]*[a-zA-Z0-9])+(?![-_])/i

const lexer2 = new marked.Lexer({
  tokenizer: new marked.Tokenizer()
})
console.log(lexer2.tokenizer.rules.inline.url) // Output: { exec: [Function: noopTest] }
```

**Expected behavior**
I expect the ruleset to be the same regardless of whether or not I pass in a tokenizer that I've instantiated myself or not (assuming all other options passed into the Lexer/Tokenizer are the same).

**Comment by trevorhreed** [comment]
After playing around with the code for a bit, I found the line of code (Lexer.js#L53) that causes this behavior:

https://github.com/markedjs/marked/blob/cdaf80a489ae799c990c40bf97662e0607fb4479/src/Lexer.js#L49-L75

If you pass any option to the lexer constructor, you no longer get the default values. This could easily be fixed by replacing line Lexer.js:53 with the following:

```javascript
this.options = Object.assign(defaults, options)
```

However, this could theoretically break existing implementations. How would the project owners prefer to proceed?

**Comment by UziTech** [comment]
you should use `marke.use(options)` to set the options.

using `Object.assign` in the lexer will slow marked down alot.

**Comment by trevorhreed** [comment]
In my case, I'm trying to use two instances of marked, each with different options, so `marked.use(options)` doesn't work for me (unless there's something I'm unaware of).

**Comment by UziTech** [comment]
You can send all options

```js
new marked.Lexer({
  ...marked.defaults,
  tokenizer: new marked.Tokenizer()
})
```

**Comment by UziTech** [comment]
I think this issue has been solved.
