### ISSUE TITLE
Are such options available? (related to newlines and urls)

### ISSUE THREAD

**Issue by kamran-12** [markedjs/marked#1769]
1. Generating links with shorter urls. For example, currently, `https://github.com` automatically gives a link, but `github.com` does not. I want that automatically become a link, too.
2. Go to new line when using a single "newline" character. Currently, two newlines are needed on editor to go to new line, a single newline gets converted to space.

**Comment by UziTech** [comment]
You can see the current options in our [documentation](https://marked.js.org/using_advanced#options).

1. You will have to change the autolink tokenizer
2. `breaks` option
