### ISSUE TITLE
`` Unicode encoding conversion error between characters

### ISSUE THREAD

**Issue by xxxxnnxxxx** [markedjs/marked#1773]
**Describe the bug**
a string include unicode encoding between two accents(`), marked transformed incorrectly
how to deal with this problem?

**To Reproduce**

```
console.log(marked("10. `<script>\u0061\u006c\u0065\u0072\u0074(10);</script>`<br/>"));
```
the output is :
```
<ol start="10">
<li><code>&lt;script&gt;alert(10);&lt;/script&gt;</code><br/></li>
</ol>
```

**Expected behavior**
The expected output is 
```
<ol start="10">
<li><code>&lt;script&gt;\u0061\u006c\u0065\u0072\u0074(10);&lt;/script&gt;</code><br></li>
</ol>
```

**Comment by UziTech** [comment]
looks like the latest version has correct output. [demo](https://marked.js.org/demo/?outputType=html&text=10.%20%60%3Cscript%3E%5Cu0061%5Cu006c%5Cu0065%5Cu0072%5Cu0074(10)%3B%3C%2Fscript%3E%60%3Cbr%2F%3E&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master)

What version are you using?

**Comment by xxxxnnxxxx** [comment]
```bash
C:\>marked -v
1.2.0
```
the demo is correct ,but i run the code use nodejs incorrectly :(

the code:
```
var marked = require('marked');

console.log(marked("10. `<script>\u0061\u006c\u0065\u0072\u0074(10);</script>`<br/>"));
```
save as a file example.js

run the js

```
PS G:\> node .\example.js
<ol start="10">
<li><code>&lt;script&gt;alert(10);&lt;/script&gt;</code><br/></li>
</ol>
```

**Comment by xxxxnnxxxx** [comment]
```
+ marked@1.2.0
added 1 package from 1 contributor and audited 44 packages in 1.5s
```

**Comment by UziTech** [comment]
So it is working? or is there still something wrong?

**Comment by xxxxnnxxxx** [comment]
still wrong,

i install markd1.2.0 already

**Comment by UziTech** [comment]
What is wrong the output looks correct?

**Comment by UziTech** [comment]
I think I see the issue. You are not escaping the slashes. the code should look like

```js
console.log(marked("10. `<script>\\u0061\\u006c\\u0065\\u0072\\u0074(10);</script>`<br/>"));
```

**Comment by xxxxnnxxxx** [comment]
run the code in nodejs is incorrect 
```
var marked = require('marked');

console.log(marked("10. `<script>\u0061\u006c\u0065\u0072\u0074(10);</script>`<br/>"));
```
```
node .\example.js
```
output:
```
<ol start="10">
<li><code>&lt;script&gt;alert(10);&lt;/script&gt;</code><br/></li>
</ol>
```
**you can run the code in nodejs console** 


the [demo](https://marked.js.org/demo/?outputType=html&text=10.%20%60%3Cscript%3E%5Cu0061%5Cu006c%5Cu0065%5Cu0072%5Cu0074(10)%3B%3C%2Fscript%3E%60%3Cbr%2F%3E&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master) you send to me is correct

**Comment by UziTech** [comment]
node converts `\u0061\u006c\u0065\u0072\u0074` to `alert` before sending it to marked so there is no way marked can know if `a` was sent as `a` or `\u0061`.

**Comment by UziTech** [comment]
if you want the output to be:

```html
<ol start="10">
<li><code>&lt;script&gt;\u0061\u006c\u0065\u0072\u0074(10);&lt;/script&gt;</code><br></li>
</ol>
```

you will have to input:

```
console.log(marked("10. `<script>\\u0061\\u006c\\u0065\\u0072\\u0074(10);</script>`<br/>"));
```

**Comment by xxxxnnxxxx** [comment]
thank you
