### ISSUE TITLE
table can't support `a | b`

### ISSUE THREAD

**Issue by 957739315** [markedjs/marked#1777]
**Marked version:**

**Describe the bug**
want to input `a | b` within a table but the stick is identified as the end of a table's cell

**for example**
```
| Header 1  | Header 2            | Header 3  |
| --------- | ------------------- | --------- |
| Some data |  sdsadas            | Cell 3 `a|b`  test   |
| data      | Some long data here | more data |
```
![image](https://user-images.githubusercontent.com/30749068/95729573-a90ddc00-0caf-11eb-84ea-114bb18f20ff.png)

please how can I deal with this situation?

**Comment by UziTech** [comment]
You must escape any pipe `\|` inside a table with a backslash. [demo](https://marked.js.org/demo/?text=%7C%20Header%201%20%20%7C%20Header%202%20%20%20%20%20%20%20%20%20%20%20%20%7C%20Header%203%20%20%7C%0A%7C%20---------%20%7C%20-------------------%20%7C%20---------%20%7C%0A%7C%20Some%20data%20%7C%20%20sdsadas%20%20%20%20%20%20%20%20%20%20%20%20%7C%20Cell%203%20%60a%5C%7Cb%60%20%20test%20%20%20%7C%0A%7C%20data%20%20%20%20%20%20%7C%20Some%20long%20data%20here%20%7C%20more%20data%20%7C&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master)
