### ISSUE TITLE
About anti-leech

### ISSUE THREAD

**Issue by RanX12** [markedjs/marked#1779]
The user fills in a picture link in markdown, but the address of this link has an anti-theft chain function. Is there a way to bypass this anti-theft chain?

Access address error: access denied

**Comment by UziTech** [comment]
I don't know what an anti-theft chain function is. Can you provide the markdown and resulting html?

**Comment by RanX12** [comment]
[Like this](https://img-blog.csdnimg.cn/20190214154002796.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L2ZlaW5pZmk=,size_16,color_FFFFFF,t_70)

**Comment by UziTech** [comment]
marked just turns markdown into html. It can't help with where ever the link goes.
