### ISSUE TITLE
Avoid HTML escaping

### ISSUE THREAD

**Issue by fylux** [markedjs/marked#1782]
Sometimes, _marked_ might be combined with other libraries (e.g. _lit-hml_) and the escaping might be done by another library. Therefore, is there any way of preventing _marked_ from escaping the text?

**Comment by UziTech** [comment]
you will have to create a [tokenizer](https://marked.js.org/using_pro#tokenizer) and a [renderer](https://marked.js.org/using_pro#renderer) to prevent escaping.
