### ISSUE TITLE
No authors file in code of conduct

### ISSUE THREAD

**Issue by pgcalixto** [markedjs/marked#1795]
**Describe the bug**

While I was reading the code of conduct to submit a new PR, I noticed that the AUTHORS link in the Enforcement section is broken. There is no authors file.

https://github.com/markedjs/marked/blob/master/docs/CODE_OF_CONDUCT.md#enforcement

**Comment by UziTech** [comment]
That link is meant to be clicked from our docs website https://marked.js.org/authors
