### ISSUE TITLE
Link escaping html is deprecated

### ISSUE THREAD

**Issue by calculuschild** [markedjs/marked#1800]
Dumb question:

Is there a special reason the Link renderer uses "escape" on the href? My understanding is this is deprecated and should be replaced with encodeURI?

I noticed this because the Link renderer also calls "cleanURL" which already performs encodeURI. Isn't this also redundant at that point?

Edit: Ah, I see now that you have a custom escape function in helpers.js. However, I can't see what this provides over encodeURI?

**Comment by UziTech** [comment]
That escape method changes some characters (specifically `&<>"'`) to html entities.
