### ISSUE TITLE
Bold "@" in block quote doesn't render correctly

### ISSUE THREAD

**Issue by Hashiphoto** [markedjs/marked#1831]
**Marked version:**
1.1.1 and 1.2.4

**Describe the bug**
We use marked for comments in our app, and having a bold mention in the second line of a block quote doesn't work. 

**To Reproduce**
This input:
```
> Line 1\n> **@person**
```
Produces this HTML:
```html
<blockquote>
    <p>
        Line 1
        <br>
        **@person**
    </p>
</blockquote>
```
I could not repro the bug in the Marked Demo because it does not support newlines/br tags (or I couldn't figure out how to use them). 

**Expected behavior**
The `> **@person**` line should be wrapped in `<strong>` tags, but it instead shows the asterisks. This only repros when the bolded mention is after the first line, is at the beginning of the line, and starts with a `@`.
Expected output
```html
<blockquote>
    <p>
        Line 1
        <br>
        <strong>@person<strong>
    </p>
</blockquote>
```

**Comment by calculuschild** [comment]
According to [the Markdown spec](https://github.github.com/gfm/#hard-line-break), a newline can be triggered by adding two blank spaces or the `\` character, followed by a carriage return like so:

```
> Line 1\
> **@person**
```

However, you are correct that in this case Marked does not seem to properly render the `<strong>` tags.

As a temporary workaround, you can type in the `<br>` directly, which appears to work in [the demo](https://marked.js.org/demo/?outputType=html&text=%3E%20Line%201%20%3Cbr%3E%0A%3E%20**%40person**&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=1.2.3).

**Comment by UziTech** [comment]
If you set the `breaks` option you don't need to escape the new line character.

![image](https://user-images.githubusercontent.com/97994/99341745-13d2aa00-2850-11eb-9993-e20f15d3d88d.png)


[demo](https://marked.js.org/demo/?outputType=html&text=%3E%20Line%201%0A%3E%20**%40person**&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20true%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master)
