### ISSUE TITLE
Wrong `List` type

### ISSUE THREAD

**Issue by munjo5746** [markedjs/marked#1856]
**Marked version:** @types/marked version 1.2.0, marked version 1.2.5

**Describe the bug**
In the type definition, the field `type` in `Tokens.List` is defined as `list_start` but `Tokenizer.list(src)` returns `type` equals to `list`.

**To Reproduce**
-

**Expected behavior**
The `Tokens.List` type definition has to have `type` equals to `list`.

![image](https://user-images.githubusercontent.com/4221101/100689063-b3fcf880-3351-11eb-98b0-f19ad2195057.png)

**Comment by UziTech** [comment]
This issue should be moved to the [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/) repo.
