### ISSUE TITLE
hope have css generator tool for markdown rendered html element

### ISSUE THREAD

**Issue by Ikki-Dai** [markedjs/marked#1857]
**Describe the feature**
hope while markdown rendered in a html page with specific class or element, it will be easier to be recognized by developer 
and to make custom styles.

**Why is this feature necessary?**
develope friendly

**Describe alternatives you've considered**
what if a div or other element with a default class`<div class="marked">` or provide an tool for develop to generate their own stylesheet

**Comment by UziTech** [comment]
If you want classes you will have to create a custom renderer. Or you can use the tags and add classes after generating the html.
