### ISSUE TITLE
preview support copy code

### ISSUE THREAD

**Issue by 957739315** [markedjs/marked#1858]
**Describe the feature**
![image](https://user-images.githubusercontent.com/30749068/100743178-eae91200-3416-11eb-90c3-7d6f02562196.png)

Dear author, hope copy code block that show the "copy" button when mouse hovering into the code block, copy the code block when clicking the button, show the tip "copy success" when copied, hide the "copy" button when mouse out of the code block.

**Why is this feature necessary?**
because i need to choose all when copy the code block. When the code block is too long, choosing all is inconvenient.

becuase our project is using this package and we have this demand, hope it can be supported as son as possible. 

Thank you very much! Best wishes!

**Comment by UziTech** [comment]
You can press <kbd>Ctrl</kbd> + <kbd>A</kbd> (Select All) then <kbd>Ctrl</kbd> + <kbd>C</kbd> (Copy) to easily copy all of the text in any textbox.

PRs are always welcome 😁

**Comment by marcuschem** [comment]
I really need help, can somebody helpme writting by inbox

**Comment by UziTech** [comment]
@marcuschem if you describe your problem we can try to help you.
