### ISSUE TITLE
Cannot convert the '\n'  in textarea correctly.

### ISSUE THREAD

**Issue by KevinZhoutianyi** [markedjs/marked#1859]
**Marked version:**
1.5.2
set break to true

**Describe the bug**
1. In the textarea, I put 'line1\nline2' in it. 
2. ```console.log(marked(mdValue))```,then I get ```<p>line1\nline2</p>```, which is unexpected
3. however, when I ```console.log(marked('line1\nline2))```, I got the expected result ```<p>line1<br>line2</p>```

**Comment by UziTech** [comment]
the `\` character is converted to `\\` by the browser. In order to fix that you will have to replace it before sending it to marked.

example:

```
console.log(marked(mdValue.replace(/\\n/g, '\n')))
```
