### ISSUE TITLE
InlineLexer Type should be deleted

### ISSUE THREAD

**Issue by upupming** [markedjs/marked#1862]
The `InlineLexer` doesn't exist anymore, probably we should change this file: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/marked/index.d.ts#L121

> I have rebased and implemented option 2 from [#1627 (comment)](https://github.com/markedjs/marked/pull/1627#issuecomment-606753680)
> 
> It didn't make sense to keep the `InlineLexer` so I just merged it into the `Lexer`

Hi, since the `InlineLexer` class has been deleted, can you delete the type definitions in `@types/marked` too, thanks!
![image](https://user-images.githubusercontent.com/24741764/101231940-831e1a00-36e9-11eb-888c-651bc71e1eb4.png)

_Originally posted by @upupming in https://github.com/markedjs/marked/pull/1627#issuecomment-739113217_

**Comment by UziTech** [comment]
This issue should be moved to the [https://github.com/DefinitelyTyped/DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) repo.

**Comment by upupming** [comment]
@UziTech Thanks for the suggestion, it seems the `@types/marked` is [contributed by different users](https://github.com/DefinitelyTyped/DefinitelyTyped/commits/master/types/marked/index.d.ts), so I should change the file and make a PR to their repo.
