### ISSUE TITLE
IE11: es6 feature String.prototype[startsWith/endsWith] not support

### ISSUE THREAD

**Issue by LitileXueZha** [markedjs/marked#1870]
**Marked version:** 1.2.5

**Describe the bug**
Crashed when parsing markdown. An error found in console:"Object does not support `startsWith` property or method."

After searched source code, I found it writed at line 561 in `src/Tokenizer.js`:

```javascript
  codespan(src) {
    const cap = this.rules.inline.code.exec(src);
    if (cap) {
      let text = cap[2].replace(/\n/g, ' ');
      const hasNonSpaceChars = /[^ ]/.test(text);
      // not support in IE11
      const hasSpaceCharsOnBothEnds = text.startsWith(' ') && text.endsWith(' ');
      if (hasNonSpaceChars && hasSpaceCharsOnBothEnds) {
        text = text.substring(1, text.length - 1);
      }
```
It seems just delete space at start or end of string...

Here is the compatibility table:
![image](https://user-images.githubusercontent.com/22041474/101787715-57ac8c80-3b3a-11eb-9563-3321f62d1b45.png)

**Comment by UziTech** [comment]
We are going to be dropping support for IE11 soon but if you want to create a PR we could merge it.

**Comment by LitileXueZha** [comment]
Go ahead and feel free for this bug. We‘d like to support dropping IE11. 😀

However here is a suggestion if anyone see this issue:
```javascript
// use polyfill
import 'core-js/es/string/starts-with';
import 'core-js/es/string/ends-with';
```
