### ISSUE TITLE
Some languages cannot be highlighted

### ISSUE THREAD

**Issue by RanX12** [markedjs/marked#1885]
I use: "marked": "^1.2.0", in my system, ```objective-c```,```Visual Basic```, these two languages cannot be highlighted , The rest are ok, I tried ```objc```,```objectivec```,```obj-c```, ```vb```,````vbnet`` `, can not be highlighted, is there any solution?

----------

![image](https://user-images.githubusercontent.com/46048444/102957978-d3cda980-4516-11eb-973a-eac6cf7bc253.png)

----------

![image](https://user-images.githubusercontent.com/46048444/102957664-f14e4380-4515-11eb-8682-c12a2ef2f4c0.png)

----------

![image](https://user-images.githubusercontent.com/46048444/102958011-e7791000-4516-11eb-90da-41e76f26050c.png)

----------

![image](https://user-images.githubusercontent.com/46048444/102958054-05467500-4517-11eb-986a-448fe21ce035.png)

**Comment by RanX12** [comment]
I found the wrong place, sorry

**Comment by Polly9968** [comment]
> I use: "marked": "^1.2.0", in my system, `objective-c`,`Visual Basic`, these two languages cannot be highlighted , The rest are ok, I tried `objc`,`objectivec`,`obj-c`, `vb`,````vbnet`` `, can not be highlighted, is there any solution?
> 
> ![image](https://user-images.githubusercontent.com/46048444/102957978-d3cda980-4516-11eb-973a-eac6cf7bc253.png)
> 
> ![image](https://user-images.githubusercontent.com/46048444/102957664-f14e4380-4515-11eb-8682-c12a2ef2f4c0.png)
> 
> ![image](https://user-images.githubusercontent.com/46048444/102958011-e7791000-4516-11eb-90da-41e76f26050c.png)
> 
> ![image](https://user-images.githubusercontent.com/46048444/102958054-05467500-4517-11eb-986a-448fe21ce035.png)
