### ISSUE TITLE
bug with ** and `

### ISSUE THREAD

**Issue by summivox** [markedjs/marked#189]
Testcase:

```
**a`b**c`d**
```

The middle

```
`b**c`
```

Should really be inline `<code>`, but now marked outputs:

``` html
<p><strong>a`b</strong>c`d**</p>
```

Expected:

``` html
<p><strong>a<code>b**c</code>d</strong></p>
```

**Comment by joshbruce** [comment]
Closing as not part of the current focus and possibly covered by spec compliance work, see also #1106 and #1216.
