### ISSUE TITLE
GFM Double Line-Break not working correctly

### ISSUE THREAD

**Issue by noducks** [markedjs/marked#190]
In these two files:  

**Source** http://github.github.com/github-flavored-markdown/sample_content.html
**Results** https://github.com/mojombo/github-flavored-markdown/issues/1

There is an example (with two spaces after Red):

``` lang
Roses are Red  
Violets are Blue
```

The github flavoured markdown output is:

``` lang
Roses are Red  

Violets are Blue
```

The marked.js output is:

``` lang
Roses are Red  
Violets are Blue
```

As you can see in the output, there is a double carriage return between Red & Violets. In marked.js there is only a single one.

These are the options I have set:

``` lang
    marked.setOptions({
      gfm: true,
      highlight: false,
      tables: false,
      breaks: true,
      pedantic: false,
      sanitize: true,
      smartLists: true,
      smartypants: false,
      langPrefix: false
    });
```

**Comment by davidtrattnig** [comment]
This issue still exists - is there any workaround?

**Comment by Shawson** [comment]
+1- I found this same issue;

```
console.log(marked('I am using __markdown__.\r\n\r\n\r\nhow cool <br>is this', {breaks:true, sanitize:true, gfm:true}));
VM3061:1 <p>I am using <strong>markdown</strong>.</p>
<p>how cool &lt;br&gt;is this</p>
```

**Comment by fabioimpe** [comment]
any update on this? I've the same problem

**Comment by styfle** [comment]
@fabioimpe This is reported from 2013 so it seems like if we changed it today that would be a breaking change, not a bug fix.

@UziTech @Feder1co5oave Thoughts on this one?

**Comment by fabioimpe** [comment]
There wasn’t update of any kind so I asked, anyway is there some way to preserve the empty line when converting to html? Thank you

**Comment by Shawson** [comment]
@styfle Surly it would be the very definition of a bug fix, because it's a bug?

**Comment by fabioimpe** [comment]
@styfle Would be a breaking change add an option to preserve the new lines? 🤔

**Comment by styfle** [comment]
@fabioimpe Are you using `gfm: true`?

It appears to render the same as GitHub when the flag is enable, but it's different when the flag is disabled.

## Actual GitHub

Let's get the whole "linebreak" thing out of the way. The next paragraph contains two phrases separated by a single newline character:

Roses are red
Violets are blue

The next paragraph has the same phrases, but now they are separated by two spaces and a newline character:

Roses are red  
Violets are blue

Oh, and one thing I cannot stand is the mangling of words with multiple underscores in them like perform_complicated_task or do_this_and_do_that_and_another_thing.

## Screenshot of marked w/default

![image](https://user-images.githubusercontent.com/229881/37712356-057cc27e-2cea-11e8-96dd-7b4b180faec3.png)


## Screenshot of marked w/gfm

![image](https://user-images.githubusercontent.com/229881/37712385-131f1828-2cea-11e8-9770-fd821c7262c4.png)

**Comment by fabioimpe** [comment]
@styfle my concern is about the empty lines, I'll try to better explain with an example:

written:

Roses are red
**\n\n**
**\n\n**
Violets are blue

expected:
<p>Roses are red</p>
<br/>
<br/>
<p>Violets are blue</p>

actual:
Roses are red
Violets are blue

In short: I'm expecting a **br** tag for each time I press the enter key...

Am I missing something?

**Comment by joshbruce** [comment]
Something else to keep in mind is the difference between GFM the spec and the way GitHub actually applies and parses Markdown (header IDs are not part of the spec, for example). So, maybe starting with the spec and determining whether marked complies there would be beneficial:

1. https://github.github.com/gfm/#blank-lines - CommonMark + GFM specs
2. https://github.github.com/gfm/#hard-line-breaks
3. https://github.github.com/gfm/#soft-line-breaks

Given these specs, what you're shooting for is not spec compliant behavior and could actually put you in a. weird place:

```
# Hello

My name is:

Josh
```

With what you're looking for we would get this:

```html
<h1>Hello</h1>
<br>
<p>My name is:</p>
<br>
<p>Josh</p>
```

When what is more appropriate/desired is:

```html
<h1>Hello</h1>
<p>My name is:</p>
<p>Josh</p>
```

See hard line breaks: http://spec.commonmark.org/0.28/#hard-line-breaks (as well as the link above).

**Comment by radenkozec** [comment]
This problem is not solved. Forgot specs we need working solution.

**Comment by UziTech** [comment]
@radenkozec what is not working. Can you give an example?

**Comment by radenkozec** [comment]
@UziTech When I have multiple new lines, so when user in editor wants to make blank space and hits enter multiple times


like here to make white space it only converts to 1 <br> instead of multiple <br>

**Comment by UziTech** [comment]
@radenkozec so you want marked to output multiple new lines if there are multiple in the input?

Could you give me if an example of the output you want with the given input?

**Comment by radenkozec** [comment]
@UziTech 
I think I can do similar like Github just style paragraphs with some margin however I wanted
something like this: 

john johnCR|LF
johnCR|LF
john johnCR|LF
CR|LF
CR|LF
CR|LF
CR|LF
john

to output like this

```
<p>john john
<br>
john
<br>
john john
</p>
<br>
<br>
<br>
<br>
<p>john</p>
```

**Comment by UziTech** [comment]
@radenkozec since that isn't in any spec I don't think we will be adding it to marked but you could do that pretty easily by updating the extra `\n` in the input to be `<br>\n` before sending it to marked.

something like:

```js
const marked = require("marked");
let markdown = "a\nb\n\n\n\n\nc"
markdown = markdown.replace(/\n(?=\n)/g, "\n<br>");
console.log(marked(markdown));
```

**Comment by radenkozec** [comment]
@UziTech  After using your method I am getting 
`&lt;br&gt;<br>&lt;br&gt;`
for replaced lines

**Comment by UziTech** [comment]
are you sanitizing the html?

**Comment by radenkozec** [comment]
Yes when I turn off sanitation it works.

**Comment by levy9527** [comment]
alright, with `markdown.replace(/\n(?=\n)/g, "\n<br>")`, problem solved.

but, this is after one-hour try and test、 looking for documentation、 searching with googles and Github.  Finally, after reading this long issue, we get the right answer.

it would be easier if this is an optional feature or just written in the documentation.

**Comment by UziTech** [comment]
We could create a section of documentation for simple hacks. @levy9527 could you create a PR for this?

**Comment by endepointe** [comment]
> @radenkozec since that isn't in any spec I don't think we will be adding it to marked but you could do that pretty easily by updating the extra `\n` in the input to be `<br>\n` before sending it to marked.
> 
> something like:
> 
> ```js
> const marked = require("marked");
> let markdown = "a\nb\n\n\n\n\nc"
> markdown = markdown.replace(/\n(?=\n)/g, "\n<br>");
> console.log(marked(markdown));
> ```

Thank you for the help with regex. The issue I have now solved was I wanted to retain the newlines added after my markdown content. 

The regex you provided did cause some unexpected behavior, mainly all content that followed a list retained the indentation of the first list.

to solve this was really simple:

`  markdown = markdown.replace(/\n(?=\n)/g, "<br/>\n");`

that change retained each list's indentation.

Thanks for making marked.js. you have allowed me to manage content in a safer way before putting it within html.

**Comment by GamerzOH** [comment]
Sorry, I am a bit late, but I had the same problem. Found a work around. 
Pass marked the string by replacing all line breaks with `<br />`.

`marked.parse(yourString.replaceAll(/\r\n|\r|\n/g, '<br />'))`.

This worked fine for me, but set breaks to false as it may clash with this.

**Comment by adithyaakrishna** [comment]
Test <br />asdasd

**Comment by xerenahmed** [comment]
this hacky way is working, set height for margin between, or use another html element
```js
 summary = summary.replace(/(\n){2,}/g, "<svg height='10px'></svg>\n\n")
marked.parse(summary);
```

**Comment by ShadmanAfzal** [comment]
Any updates on this?

I am also facing the same issue

**Comment by iksent** [comment]
I am looking for a solution of multiple lines, because of `markdown.replace(/\n(?=\n)/g, "\n<br>")` breaks the lists:

```
1. firstline
2. secondline

final
```

becomes:

```
<ol>
<li>firstline</li>
<li>secondline<br>
final</li>
</ol>
```

which is not correct and should be:

```
<ol>
<li>firstline</li>
<li>secondline</li>
</ol>
<p>final</p>
```

`"marked": "9.1.6"`

**Comment by DevDuki** [comment]
How can I prevent these new lines from being replaced inside code blocks (3 backticks)? Because in there the new lines are already kept, but now I randomly see `<br>`s in my code blocks.

![image](https://github.com/user-attachments/assets/cdcf1eb5-fce8-4572-9f49-3ae602b19722)

**Comment by Stradivario** [comment]
The issue still exists even in the latest version of markedjs.

Not sure why thread is closed

**Comment by UziTech** [comment]
This is closed because marked follows GitHub and does NOT add multiple `<br>` s for multiple line breaks

If you want marked to not act like GitHub or CommonMark you can create a [custom extension](https://marked.js.org/using_pro#extensions).

If you think this is still an issue please open a new issue with markdown and the expected HTML

**Comment by Stradivario** [comment]
> This is closed because marked follows GitHub and does NOT add multiple `<br>` s for multiple line breaks
> 
> If you want marked to not act like GitHub or CommonMark you can create a [custom extension](https://marked.js.org/using_pro#extensions).
> 
> If you think this is still an issue please open a new issue with markdown and the expected HTML

Gotcha! 
Thank you very much for the answer!
