### ISSUE TITLE
html input string doesn't get any changes.

### ISSUE THREAD

**Issue by arun-honey** [markedjs/marked#1907]
**Marked version: marked@1.2.7**

**Markdown flavor:** Markdown.pl|CommonMark|GitHub Flavored Markdown|n/a

## Expectation

When I input the HTML string in the marked imported method, it,s return the same input string in the output
Like: input ``` ("<div>**test**<div>")```
Expected output: ``` "<div><strong>test</strong><div>"```
Actual output i got:  ``` ("<div>**test**<div>")```

``` 
import marked from "marked/lib/marked.esm.js";

marked("<div>**test**<div>");
result: "<div>**test**<div>"
```

is there any mistake I made.? or any option to be enabled.?

**Comment by calculuschild** [comment]
Keep in mind that any Markdown inside of HTML elements (e.g., your `<div>`) is not parsed, as per the [Commonmark Markdown Spec](https://spec.commonmark.org/0.29/#html-blocks), so this is actually the correct behavior. If you want to allow Markdown inside of HTML elements, you could create a custom [renderer](https://marked.js.org/using_pro#renderer).

**Comment by arun-honey** [comment]
>  you could create a custom [renderer](https://marked.js.org/using_pro#renderer).
but I am getting the almost expected output from the marked.parserInline method for some HTML inputs..

**Comment by UziTech** [comment]
That is because `parseInline` only parses inline tokens. [Inline HTML](https://spec.commonmark.org/0.29/#raw-html) is parsed differently than [Block HTML](https://spec.commonmark.org/0.29/#html-blocks).

**Comment by arun-honey** [comment]
Thanks for your time :smile: (நன்றிகள்).

**Comment by Splaktar** [comment]
Is there any example of a custom renderer like this? or any ideas on where to start? The docs linked to show an example of overriding the `header` rendering function. Which one is needed for rendering HTML in blocks?

Or would a whole new tokenizer and parser be required to be written too?

**Comment by UziTech** [comment]
You could just run the inner html through marked in the `html` renderer.

```js
const marked = require('.');
const renderer = {
  html(html) {
    const match = html.match(/^(<[^>]+>)(.*?)(<\/[^>]+>)$/);
    if (!match) {
      return false;
    }
    const startTag = match[1];
    const endTag = match[3];
    const innerMarkdown = match[2];
    const innerHTML = marked(innerMarkdown);

    return `${startTag}\n${innerHTML}\n${endTag}\n`;
  }
};

marked.use({ renderer });

console.log(marked('<div>\n**bold text**\n</div>'));
```

This doesn't cover all of the edge cases but it should be a good start.

**Comment by LeaVerou** [comment]
Thanks! Yeah, I was thinking about doing something like that, but wondered if there is a better way.
I guess not!
