### ISSUE TITLE
is it possible to support `fuzzyLink` and `fuzzyEmail` like `linkify-it`

### ISSUE THREAD

**Issue by codeStryke** [markedjs/marked#1908]
**Describe the feature**
[markdown-it](https://github.com/markdown-it/markdown-it) which uses [linkify-it](https://github.com/markdown-it/linkify-it) supports `fuzzyLink` and `fuzzyEmail` by [default](https://github.com/markdown-it/linkify-it#new-linkifyitschemas-options).

**Why is this feature necessary?**
Since I'm switching from `markdown-it` to `marked`, I'm missing this feature. I wonder if it's possible to support it.

**Describe alternatives you've considered**
I looked into extending the lexer to use `linkify-it` to determine if text was a link, but was not able to figure out how to integrate it.

**Comment by UziTech** [comment]
By default marked uses [CommonMark spec](https://spec.commonmark.org/0.29/) but you can use [GFM](https://github.github.com/gfm/#autolinks-extension-) with `gfm: true` [option](https://marked.js.org/using_advanced#options).

**Comment by UziTech** [comment]
Just out of curiosity, why are you switching from markdown-it to marked?

**Comment by codeStryke** [comment]
Thank you for your quick response.

`markdown-it` provides an UMD module which is not ideal in our no build-system environment. Specifically running into a conflict when another component that uses AMD is on the page. 
 `marked` has an es6 module which works nicely.

I'm not able to get the `gfm: true` option to work for [these examples](https://marked.js.org/demo/?text=%0Agoogle.com%0A%3Cgoogle.com%3E%0A&options=%7B%0A%20%22gfm%22%3A%20true%2C%0A%20%22smartypants%22%3A%20true%0A%7D&version=master). Also, isn't is `true` by default as per the doc [here](https://marked.js.org/using_advanced#options)

On reading the [GFM](https://github.github.com/gfm/#autolinks-extension-) spec more closely, I think my examples don't qualify as valid. I wonder why `markdown-it` allows it.

**Comment by UziTech** [comment]
Ah, you are correct, `gfm` is `true` by default.

We try to stick to the spec, however you could edit the autolink [tokenizer](https://marked.js.org/using_pro#tokenizer) and use `linkify-it` to check for matches.

Something like:

```js
const marked = require('.');
const linkifyIt = require('linkify-it')();

marked.use({
  tokenizer: {
    autolink(src) {

      // .. check src with linkifyIt here

      return {
        type: 'link',
        raw: raw, // this is the text we are consuming from src
        text,
        href,
        tokens: [
          {
            type: 'text',
            raw: text,
            text
          }
        ]
      };

      // else return false to fallback to regular autolink tokenizer
      return false;
    }
  }
});

marked('google.com <google.com>');

```

**Comment by codeStryke** [comment]
Thank you for taking the time to look into this. I tried this approach out (here)[https://stackblitz.com/edit/marked-with-linkify-it?devtoolsheight=33&file=index.js]. However, I'm running into a problem in the case of `<google.com>`, with the tokenizer identifying `m>` as a separate token.

**Comment by UziTech** [comment]
I just created an extension [marked-linkify-it](https://www.npmjs.com/package/marked-linkify-it). See if that works for you.

**Comment by codeStryke** [comment]
[works great](https://stackblitz.com/edit/marked-with-linkify-it?devtoolsheight=33&file=index.js), thank you!

**Comment by UziTech** [comment]
Glad it works for you! If there are any issues feel free to create an issue on that repo.
