### ISSUE TITLE
when url have a space, the photo can't be shown

### ISSUE THREAD

**Issue by 957739315** [markedjs/marked#1921]
**Marked version:**
v0.3.3
v1.2.8

**Describe the bug**

using version 0.3.3, the image can be shown normally when the url has a space.

![image](https://user-images.githubusercontent.com/30749068/106423311-28136400-649b-11eb-8710-3c60b959c792.png)

using  version 1.2.8, the image can't be shown normally when the url has a space.

![image](https://user-images.githubusercontent.com/30749068/106423553-9bb57100-649b-11eb-98f0-6cad6ad8f4c1.png)

**Expected behavior**
using  version 1.2.8, the image using a url within a space can be shown.

before rendering image, can convert it , such as `encodeURIComponent(url)`.

**Comment by UziTech** [comment]
This is working the way it is supposed to according to the [spec](https://spec.commonmark.org/0.29/#images).

If you want an image with a space you can convert space to `%20` or use angle brackets around the url like `![image](<image with space.png>)`
