### ISSUE TITLE
Sublist behavior change: Sublists with single space are not rendered as sublists

### ISSUE THREAD

**Issue by bwittenberg** [markedjs/marked#1923]
**Marked version:**
v1.2.3

**Describe the bug**
Sublists single indent are not rendered as html sublists.

Why is this significant? To borrow from the github flavored markdown spec: (https://github.github.com/gfm/#why-is-a-spec-needed-)

> How much indentation is needed for a sublist? The spec says that continuation paragraphs need to be indented four spaces, but is not fully explicit about sublists. It is natural to think that they, too, must be indented four spaces, but Markdown.pl does not require that. This is hardly a “corner case,” and divergences between implementations on this issue often lead to surprises for users in real documents.

I upgraded from v0.8.2 to v1.2.5, and some customers relied on sublist indentation of a single space.

It looks like the behavior change shipped in v1.2.3.

Here is a comparison of changes between versions:
https://github.com/markedjs/marked/compare/v1.2.2...v1.2.3#

**To Reproduce**

[v1.2.3 Demo](https://marked.js.org/demo/?text=-%20one%0A%20-%20two&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=1.2.3)

[v1.2.2 Demo](https://marked.js.org/demo/?text=-%20one%0A%20-%20two&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=1.2.2)

**Expected behavior**
I don't know the optimal way to handle this behavior change, and I would appreciate feedback/suggestions. 

Maybe setting `pedantic=true` should render sublists similar to v1.2.2 for the following input?

```md
- one
 - two
```

To see how `markdown.pl` handles the input, visit:
https://daringfireball.net/projects/markdown/dingus

**Comment by UziTech** [comment]
This was fixed in v1.2.3

We are following GFM and CommonMark

[CommonMark demo](https://spec.commonmark.org/dingus/?text=-%20one%0A%20-%20two)

GFM demo:

```markdown
- one
 - two
```

- one
 - two

**Comment by UziTech** [comment]
I suppose we should keep behavior for pedantic

**Comment by bwittenberg** [comment]
@UziTech : Thanks for the quick feedback. 

> I suppose we should keep behavior for pedantic

Is this something you plan on implementing?

**Comment by bwittenberg** [comment]
@UziTech : Whoops, I didn't see the PR above. Looks like you are already working on it. Thank you!
