### ISSUE TITLE
Groups of consecutive underscores in a specific pattern hang/take a long time to convert

### ISSUE THREAD

**Issue by Xegyn** [markedjs/marked#1927]
**Marked version:** 1.2.9

**Describe the bug**
3 or more groups of odd and even-numbered consecutive underscores followed by a character takes a very long time to convert.
Example input: `_______________________________ ____________________ __________________________ a`
If you click on the Marked Demo link below, you will see that this takes a long time to convert (approximately 2 minutes).
The input above is:
31 underscores, 20 underscores, 26 underscores, and an `a`.

Modifying the input in a number of ways changes the conversion time to < 10ms:
- modifying the above input so that the 1st group of underscores is an even number
- modifying the 2nd or 3rd group of underscores to be an odd number
- removing the trailing `a` character.

It seems that the longer the consecutive underscores are in length, the time increasingly gets longer.

**To Reproduce**

1. [Marked Demo](https://marked.js.org/demo/?text=_______________________________%20____________________%20__________________________%20a&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=1.2.9)
2. [CommonMark Demo](https://spec.commonmark.org/dingus/?text=_______________________________%20____________________%20__________________________%20a)

**Expected behavior**
The markdown to html conversion should take roughly the same amount of time as it does as when the above example input is modified such in one of the ways describe above (i.e. < 10ms).

**Comment by UziTech** [comment]
Looks like this was introduced in v1.1.2 (#1762) somehow

[v1.1.1 demo](https://marked.js.org/demo/?text=_______________________________%20____________________%20__________________________%20a&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=1.1.1)
[v1.1.2 demo](https://marked.js.org/demo/?text=_______________________________%20____________________%20__________________________%20a&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=1.1.2)

**Comment by UziTech** [comment]
After some testing it looks like #1864 fixes it. @calculuschild maybe we should release v2 with that fix sooner rather than wait for #1872 and others?

**Comment by calculuschild** [comment]
I'm not opposed to that. I'm kind of at a dead end with #1872 for now anyway.

**Comment by UziTech** [comment]
This should be fixed in v2.0.0

**Comment by Xegyn** [comment]
Thank you so much for the speedy response!! 🙇‍♂️

**Comment by XhmikosR** [comment]
Hey, @UziTech. Note that this was already flagged by https://lgtm.com/projects/g/markedjs/marked/rev/7293251c438e3ee968970f7609f1a27f9007bccd AFAICT

You might want to add LGTM and/or CodeQL which is its successor :)

**Comment by UziTech** [comment]
@XhmikosR CodeQL is already enabled in marked but it show any errors.

**Comment by XhmikosR** [comment]
Oh, then maybe try LGTM. Some of the checks might not be implemented in CodeQL. At least LGTM seems to have caught this a long time ago.

**Comment by UziTech** [comment]
I don't see in your link where it would have caught it. It looks like a lot of false positives since some of our regular expressions are generated at runtime.

![image](https://user-images.githubusercontent.com/97994/107382059-15a9b380-6ab5-11eb-9b55-92a9e85aefad.png)

**Comment by XhmikosR** [comment]
Ah, you are right. I thought it caught the issue, but should have looked closer.

**Comment by julienw** [comment]
Hey !
Do you think it would be possible to have a fix for the v1 branch as well? Some packages like [docsify](https://github.com/docsifyjs/docsify-cli/issues/136) do not seem quick to upgrade :/ Thanks a lot for your work!
