### ISSUE TITLE
Incorrect `code` element boundaries

### ISSUE THREAD

**Issue by Ludar-Pavel** [markedjs/marked#1935]
**Marked version:** latest one in NPM. Most likely master.

**Describe the bug**
The code tag is rendered incorrectly in certain cases.

**To Reproduce**
The following call returns incorrect code tag boundaries:
```marked("`a\n\n    b\n`");```

**Observed behavior**
```
"<p>a</p>
<pre><code>b
</code></pre>
<p></p>
`"
```

Backticks are not processed and a code tag exists; "a" is outside the code tag.

**Expected behavior**

"a" is inside the code tag; either backticks are removed, or the code tag does not appear at all.

I've looked around, and have found no mention of that being the right way of handling in the specification.

**Comment by UziTech** [comment]
It looks like marked handles it the same as commonmark and gfm

[marked demo](https://marked.js.org/demo/?outputType=html&text=%60a%0A%0A%20b%0A%60&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master)
[CommonMark demo](https://spec.commonmark.org/dingus/?text=%60a%0A%0A%20b%0A%60)

**Comment by calculuschild** [comment]
I think this is confusion between a multiline code block and an inline code block. The single backtick code block isn't intended to work with newlines inside.

**Comment by Ludar-Pavel** [comment]
I see. Thank you! Apparently, the code block was created by the indentation, not the backticks. Closing as WAI (albeit very confusing).
