### ISSUE TITLE
\n does not paste to <br>

### ISSUE THREAD

**Issue by clark-97** [markedjs/marked#1960]
**Marked version:** 1.2.5

**Markdown flavor:** i am not sure

```html
<!doctype html>
<html>
<head>
  <meta charset="utf-8" />
  <title>Marked in the browser</title>
  <style>
    blockquote {
      border-left: 6px solid #ccc;
      background-color: #f7f7f7;
      padding: 1em;
      margin: 1em 0;
      position: relative;
    }
  </style>
</head>
<body>
  <div id="content"></div>
  <script src="https://cdn.jsdelivr.net/npm/marked/marked.min.js"></script>
  <script>
    document.getElementById('content').innerHTML =
      marked("*Write a sentence using the given vocabulary word in each of the specified parts of speech.*\n\n> **Example:**\ntarget\n Noun: *The arrow hit the **target**.*\n Verb: *The bully **targeted** the new student.*\n\ndismay\n");
  </script>
</body>
</html>
```

## Expectation
<img width="453" alt="Expectation" src="https://user-images.githubusercontent.com/66821547/109916088-fa197d80-7ced-11eb-8044-b85c19568ba0.png">

## Result
<img width="456" alt="Result" src="https://user-images.githubusercontent.com/66821547/109916131-06053f80-7cee-11eb-9d8d-e0ee81fc954e.png">

**Comment by UziTech** [comment]
You have to use set the `breaks` [option](https://marked.js.org/using_advanced#options) to true.

```js
marked("*Write a sentence using the given vocabulary word in each of the specified parts of speech.*\n\n> **Example:**\ntarget\n Noun: *The arrow hit the **target**.*\n Verb: *The bully **targeted** the new student.*\n\ndismay\n", {breaks: true})
```

[demo with breaks](https://marked.js.org/demo/?text=*Write%20a%20sentence%20using%20the%20given%20vocabulary%20word%20in%20each%20of%20the%20specified%20parts%20of%20speech.*%0A%0A%3E%20**Example%3A**%0Atarget%0A%20Noun%3A%20*The%20arrow%20hit%20the%20**target**.*%0A%20Verb%3A%20*The%20bully%20**targeted**%20the%20new%20student.*%0A%0Adismay%0A&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20true%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master)
[demo without breaks](https://marked.js.org/demo/?text=*Write%20a%20sentence%20using%20the%20given%20vocabulary%20word%20in%20each%20of%20the%20specified%20parts%20of%20speech.*%0A%0A%3E%20**Example%3A**%0Atarget%0A%20Noun%3A%20*The%20arrow%20hit%20the%20**target**.*%0A%20Verb%3A%20*The%20bully%20**targeted**%20the%20new%20student.*%0A%0Adismay%0A&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master)

**Comment by harryghgim** [comment]
I used marked on browser, not on node environment. I did put `{breaks: true}` option as second argument in `marked` function, but it doesn't seem to be working as I expected. Did I miss something? 

```js
const markdownStr = "# I'm header\n\n\n\n## hello\n[I'm a link](https://github.com)\n- unordered list item\n1. ordered item list\n\n![](react.png)\n> That's what they said...\n\nI'm **bold**\n```\nfunction() {\n\tconsole.log('I'm inside code block')\n}\n```\nI'm `inline code`"
const preview = document.getElementById("preview")
preview.innerHTML = marked(markdownStr, {breaks: true})

console.log(preview.innerHTML)
```

I expect three `<br />` after **I'm header**, but neither on console nor on browser it is not rendered correctly.

On console
```
<h1 id="im-header">I'm header</h1>
<h2 id="hello">hello</h2>
<p><a href="https://github.com">I'm a link</a></p>
<ul>
<li>unordered list item</li>
</ul>
<ol>
<li>ordered item list</li>
</ol>
<p><img src="react.png" alt=""></p>
<blockquote>
<p>That's what they said...</p>
</blockquote>
<p>I'm <strong>bold</strong></p>
<pre><code>function() {
    console.log('I'm inside code block')
}
</code></pre>
<p>I'm <code>inline code</code></p>
```

On browser
<img width="485" alt="Screen Shot 2021-04-15 at 4 22 15 PM" src="https://user-images.githubusercontent.com/35060447/114830055-c199b300-9e06-11eb-8772-22fae36b56b8.png">

**Comment by harryghgim** [comment]
> I used marked on browser, not on node environment. I did put `{breaks: true}` option as second argument in `marked` function, but it doesn't seem to be working as I expected. Did I miss something?
> 
> ```js
> const markdownStr = "# I'm header\n\n\n\n## hello\n[I'm a link](https://github.com)\n- unordered list item\n1. ordered item list\n\n![](react.png)\n> That's what they said...\n\nI'm **bold**\n```\nfunction() {\n\tconsole.log('I'm inside code block')\n}\n```\nI'm `inline code`"
> const preview = document.getElementById("preview")
> preview.innerHTML = marked(markdownStr, {breaks: true})
> 
> console.log(preview.innerHTML)
> ```
> 
> I expect three `<br />` after **I'm header**, but neither on console nor on browser it is rendered correctly.
> 
> On console
> 
> ```
> <h1 id="im-header">I'm header</h1>
> <h2 id="hello">hello</h2>
> <p><a href="https://github.com">I'm a link</a></p>
> <ul>
> <li>unordered list item</li>
> </ul>
> <ol>
> <li>ordered item list</li>
> </ol>
> <p><img src="react.png" alt=""></p>
> <blockquote>
> <p>That's what they said...</p>
> </blockquote>
> <p>I'm <strong>bold</strong></p>
> <pre><code>function() {
>     console.log('I'm inside code block')
> }
> </code></pre>
> <p>I'm <code>inline code</code></p>
> ```
> 
> On browser
> <img alt="Screen Shot 2021-04-15 at 4 22 15 PM" width="485" src="https://user-images.githubusercontent.com/35060447/114830055-c199b300-9e06-11eb-8772-22fae36b56b8.png">

Looks like I didn't understand the concept of `\n` in markdown. No matter how many `\n` is inputted, I realised that it will only generate one `<br>`. Sorry to bother.
