### ISSUE TITLE
Incorrect parsing of italic/bold tags

### ISSUE THREAD

**Issue by plegner** [markedjs/marked#1979]
**Marked version:** 2.0.0+

**Describe the bug**
Italic and bold tags spread across multiple lines don't get parsed correctly

**To Reproduce**
1. [Marked Demo](https://marked.js.org/demo/?text=_italic%20**bold**%20italic_%0A_italic%20**bold**%20italic_%0A_italic%20**bold**%20italic_%0A&options=&version=2.0.0)
2. [CommonMark Demo](https://spec.commonmark.org/dingus/?text=_italic%20**bold**%20italic_%0A_italic%20**bold**%20italic_%0A_italic%20**bold**%20italic_%0A)

**Expected behavior**
No _s should appear in the output.

**Comment by UziTech** [comment]
This was fixed in v2.0.7
