### ISSUE TITLE
Render Error

### ISSUE THREAD

**Issue by plotpoi** [markedjs/marked#1984]
Thank you for the wonderful project.

```
*** text!***あ
```

I found that the parse failed in, so I will report it.
It may be related to `!` And double-byte characters(CJK).

*for check
[Demo](https://marked.js.org/demo/?text=Marked%20-%20Markdown%20Parser%0A%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%0A%0A%5BMarked%5D%20lets%20you%20convert%20%5BMarkdown%5D%20into%20***HTML!***%E3%81%82.%20%20&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master)

**Comment by UziTech** [comment]
That is part of the [spec](https://spec.commonmark.org/0.29/#emphasis-and-strong-emphasis). The `*`s on the right cannot be preceded by `!`

[CommonMark demo](https://spec.commonmark.org/dingus/?text=***HTML!***%E3%81%82)
