### ISSUE TITLE
Default heading anchors can become really ugly👾

### ISSUE THREAD

**Issue by alystair** [markedjs/marked#1993]
**Marked version:** 2.0.0

**Describe the bug**
[JSDOC-to-Markdown](https://github.com/jsdoc2md/jsdoc-to-markdown/) generates the following markdown:
```md
#### HOOK.add(dstObj, triggers, fn, [priority]) ⇒ <code>Number</code>
```
which Marked then dutifully transforms into this monstrosity:
```html
<h4 id="md-hookadddstobj-triggers-fn-priority-⇒-number">
```

**To Reproduce**
Equiv. [Marked Demo](https://marked.js.org/demo/?outputType=html&text=%23%23%23%23%20HOOK.add(dstObj%2C%20triggers%2C%20fn%2C%20%5Bpriority%5D)%20%E2%87%92%20%3Ccode%3ENumber%3C%2Fcode%3E%0A%0AOH%20NO%20THE%20HUMANITY!&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master)

**Expected behavior**
Ideally Marked should more intelligently know when 'enough is enough' and stop parsing, in this instance it would be at the starting bracket. At the very least there should be a way to easily modify/replace the native anchor generating behaviour, RegEx being the 'easiest'.

Yes, I know this is a borderline feature request but the idea of linking to such an anchor disturbs me greatly.

**Comment by alystair** [comment]
Another alternative: since I can easily modify JSDOC2MD's output, an alternative would be a way to change header generation so any instance of `# [foo](#md-foo)` would instead add `md-foo` as the header's ID, not actually link it.

**Comment by UziTech** [comment]
The ids are supposed to match GitHubs ids for headers in a readme

It looks like GitHub remove the arrow along with other special characters so it looks like:

`hookadddstobj-triggers-fn-priority--number`

this is a bug.


You can extend the [renderer](https://marked.js.org/using_pro#renderer) to override the id if you don't want it to match GitHub.

**Comment by styfle** [comment]
GitHub has some interesting behavior here. I'm seeing the following:

```
user-content-hookadddstobj-triggers-fn-priority--number
```

According to [Babelmark 3](https://babelmark.github.io/?text=%23%23%23%23+HOOK.add(dstObj%2C+triggers%2C+fn%2C+%5Bpriority%5D)+%E2%87%92+%3Ccode%3ENumber%3C%2Fcode%3E%0A), nearly every implementation has a different algorithm for generating IDs.

**Comment by UziTech** [comment]
Looks like it is not documented anywhere either.

https://github.com/github/markup/issues/1326

**Comment by UziTech** [comment]
It might be nice to use the unicode library to create the regexps like https://github.com/Flet/github-slugger/pull/35.

We would have to watch how much that adds to the minified file size.

**Comment by UziTech** [comment]
The https://github.com/markedjs/marked-gfm-heading-id extension uses github-slugger to create the ids so it should be much closer to github. I think the small implementation we have in marked is good enough for most situations.
