### ISSUE TITLE
Adding a changelog

### ISSUE THREAD

**Issue by Pomax** [markedjs/marked#1995]
**What pain point are you perceiving?.**

Marked went from major version 1.x to 2.x, and there is no information on what that means. As a node package, presumably marked follows the [semver](https://semver.org/) conventions for versioning, so _something_ broke backward compatibility (otherwise it'd be a minor version change), but there is no changelog as far as I can tell, so there's no way to know what got broken =)

**Describe the solution you'd like**

It would be great to add a changelog that explains what changed, so that folks who rely on 1.x know what to look out for when they update to 2.x

**Comment by UziTech** [comment]
We share the changes in the [release notes](https://github.com/markedjs/marked/releases).

**Comment by Pomax** [comment]
Okay, but remember that tooling can't look at a github webpage: an actual changelog file is still super important (heck, even github's dependabot relies on it =)

**Comment by UziTech** [comment]
Dependabot [works](https://github.com/UziTech/notifications/pull/103) with release notes.

**Comment by Pomax** [comment]
well then, I learned something new. Thanks.
