### ISSUE TITLE
Set `type` member for all nodes

### ISSUE THREAD

**Issue by sapristi** [markedjs/marked#2000]
**What pain point are you perceiving?.**

Not all nodes have a `type` member set, namely the `def` (see https://github.com/markedjs/marked/blob/d0f9ffdb2479ec04a1806b5a3bafee5761a5ff72/lib/marked.js#L747

and also in one case for the `space` node: https://github.com/markedjs/marked/blob/d0f9ffdb2479ec04a1806b5a3bafee5761a5ff72/lib/marked.js#L485

Having a defined `type` member would help discriminating them when iterating the markdown tree.
It also seems to be an issue for the https://www.npmjs.com/package/@types/marked packages, where the `Def` interface does't have a `type` member, and thus it is not possible to discriminate node types in typescript (I guess it could be possible to add a type member in the interface, but it would be troublesome if this project later chose a different string).

**Describe the solution you'd like**

Add a `type` member to all nodes of the markdown tree.

**Comment by UziTech** [comment]
If you would like to create a PR to add the type that would be much appreciated.

You should just need to add a `type` property to the `def` tokenizer's return object

https://github.com/markedjs/marked/blob/d0f9ffdb2479ec04a1806b5a3bafee5761a5ff72/src/Tokenizer.js#L344-L356

**Comment by sapristi** [comment]
Ok I will do one. What about the case where the `space` node doesn't define a `type` member ?
