### ISSUE TITLE
Why is the minified build in version control?

### ISSUE THREAD

**Issue by illright** [markedjs/marked#2013]
I noticed that the `marked.min.js` file was updated by a bot a couple of days ago, while the last time it was updated before was 7 years earlier. Could this be a mistake? Maybe this file was never intended to make it into VC?

**Comment by UziTech** [comment]
This is probably something we should remove in the future but it is in version control so people can use it with a script tag.

```html
<script src="https://cdn.jsdelivr.net/gh/markedjs/marked/marked.min.js"></script>
```

**Comment by illright** [comment]
I don't know where jsdelivr takes the files from, but unpkg, for instance, takes them from the npm package, which makes sense and keeps the VC free of build files

**Comment by UziTech** [comment]
jsdelivr can use the [github repo](https://www.jsdelivr.com/?docs=gh) or npm package. We could deprecate building in the repo and only allow the npm package.

**Comment by LeoDog896** [comment]
Marked also uses it in the Demo for referencing certain commits

**Comment by ernstki** [comment]
> jsdelivr can use the [github repo](https://www.jsdelivr.com/?docs=gh) or npm package. We could deprecate building in the repo and only allow the npm package.

What's the recommendation for small projects who _only_ want/need the `marked.min.js` now?

Is this worth a docs PR, since I didn't notice anything in the README?

**Comment by UziTech** [comment]
@ernstki  See https://github.com/markedjs/marked?tab=readme-ov-file#usage

```
<script src="https://cdn.jsdelivr.net/npm/marked/marked.min.js"></script>
```

**Comment by ernstki** [comment]
> <script src="https://cdn.jsdelivr.net/npm/marked@15/lib/marked.umd.js"></script>

That'll work, with the help of `wget`. Thanks!
