### ISSUE TITLE
Demo / release discrepancy for emphasis of special character

### ISSUE THREAD

**Issue by 7r9Jda6Nhx6fZFy** [markedjs/marked#2015]
**Marked version:**
2.0.3

**Describe the bug**
Starting an emphasis before a special character in a word is not rendered in the same way between the demo and my application.

**To Reproduce**
```
<script src="https://cdn.jsdelivr.net/npm/marked/marked.min.js"></script>
<p id="test"></p>
    <script>
        document.getElementById('test').innerHTML = marked("A**\+:**");
    </script>
```
The result is a litteral A**+:**, without bold formatting.

**Expected behavior**
In the demo, the result is rendered as `<p>A<strong>+:</strong></p>`, and is what I want for my application.
https://marked.js.org/demo/?text=A**%5C%2B%3A**&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=2.0.3

**Comment by UziTech** [comment]
It seems like you might have to escape the slash

```js
document.getElementById('test').innerHTML = marked("A**\\+:**")
```

**Comment by 7r9Jda6Nhx6fZFy** [comment]
> It seems like you might have to escape the slash
> 
> ```js
> document.getElementById('test').innerHTML = marked("A**\\+:**")
> ```

It works, thank you. But why is the demo behaving differently ?

**Comment by UziTech** [comment]
The demo isn't behaving differently. Slashes are just automatically escaped when getting them from a textarea instead of setting a string.
