### ISSUE TITLE
Add module field to package.json

### ISSUE THREAD

**Issue by benmccann** [markedjs/marked#2021]
**What pain point are you perceiving?.**
`marked` does not play nicely with unbundled development tools like Snowpack, Vite, and WMR. E.g. https://github.com/snowpackjs/analyze-npm/issues/9. These tools highly prefer working with ESM code, but won't discover that an ESM version is available without the `module` field in `package.json`

**Describe the solution you'd like**
Align the ESM and CJS versions to have the same shape (https://github.com/markedjs/marked/pull/1571#issuecomment-562891963) and then add a `module` field to `package.json`

**Comment by benmccann** [comment]
Actually, there is a named export called `parse`, so even without changing the shape, I can get this to work in SvelteKit simply by by adding the `module` field. However, without the `module` field, I need a workaround:

```
			optimizeDeps: {
				include: ['marked']
			},
```

**Comment by UziTech** [comment]
If you want to create a PR we will be releasing v3 soon so any breaking changes can go into that release.
