### ISSUE TITLE
Link URL ending with `_` is being stripped from the URL

### ISSUE THREAD

**Issue by victor95pc** [markedjs/marked#2024]
**Marked version: master**

**Describe the bug**
URL ending with `_` is being stripped from the URL

**To Reproduce**

1. [Marked Demo](https://marked.js.org/demo/?text=z%0A%0Ahttps%3A%2F%2Fwww.google.com%2Fsearch%3Fq%3Dgoogle_&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master)

**Expected behavior**

To create a URL with the `_` included, [https://www.google.com/search?q=google_](https://www.google.com/search?q=google_) instead https://www.google.com/search?q=google

**Comment by UziTech** [comment]
According to the [gfm spec](https://github.github.com/gfm/#autolinks-extension-):

> Trailing punctuation (specifically, `?`, `!`, `.`, `,`, `:`, `*`, `_`, and `~`) will not be considered part of the autolink, though they may be included in the interior of the link

You can include it in the link by surrounding it in triangle brackets `<https://www.google.com/search?q=google_>`
