### ISSUE TITLE
Consider supporting a simple "sequence of tokens" token type

### ISSUE THREAD

**Issue by mitranim** [markedjs/marked#2032]
First off, thank you for keeping Marked what it is. It has served me quite well for years!

**What pain point are you perceiving?.**

My use case seems to require editing the AST and replacing some tokens with a sequence of other tokens. The current `walkTokens` API passes only a single token to the callback; I'd have to implement custom walk logic to allow splicing multiple tokens in place of a single token. Not only is this complicated, but splicing and shifting elements in JS arrays isn't great for performance.

**Describe the solution you'd like**

This could be much easier if `Parser` supported something like this:

```js
{tokens: []}
```

Given a token without a type, or with some special new type (for example, `'tokens'`), `Parser` would simply traverse its children, invoking `.parse` or `.parseInline` for each token, depending on the context.

My use case could also be solved by making `Parser` more extensible, which is a separate proposal: #2033.

**Comment by UziTech** [comment]
Custom tokenizers and renderer are available in v2.1.0.

see Custom Extensions section in [docs](https://marked.js.org/using_pro)

If that doesn't work for your use case we can reopen this.
