### ISSUE TITLE
The second 'table' does not render properly.

### ISSUE THREAD

**Issue by markofred** [markedjs/marked#2053]
If there are two tables in the `.MD` document, the second "table" cannot be rendered correctly.

**Comment by UziTech** [comment]
Can you provide the markdown that doesn't seem to work?

**Comment by markofred** [comment]
# table1

| a    | b    | c    |
| ---- | ---- | ---- |
| 1    | 2    | 3    |

# table2

| d    | e    | f    |
| ---- | ---- | ---- |
| 4    | 5    | 6    |

**Comment by markofred** [comment]
> 您可以提供似乎无效的降价优惠吗？

# table1

| a    | b    | c    |
| ---- | ---- | ---- |
| 1    | 2    | 3    |

# table2

| d    | e    | f    |
| ---- | ---- | ---- |
| 4    | 5    | 6    |

**Comment by markofred** [comment]
> Can you provide the markdown that doesn't seem to work?

# table1

| a    | b    | c    |
| ---- | ---- | ---- |
| 1    | 2    | 3    |

# table2

| d    | e    | f    |
| ---- | ---- | ---- |
| 4    | 5    | 6    |

**Comment by UziTech** [comment]
Looks like it is working for me [demo](https://marked.js.org/demo/?text=%23%20table1%0A%0A%7Ca%7Cb%7Cc%7C%0A%7C-%7C-%7C-%7C%0A%7C1%7C2%7C3%7C%0A%0A%23%20table2%0A%0A%7Ca%7Cb%7Cc%7C%0A%7C-%7C-%7C-%7C%0A%7C1%7C2%7C3%7C&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master)

**Comment by markofred** [comment]
> Looks like it is working for me [demo](https://marked.js.org/demo/?text=%23%20table1%0A%0A%7Ca%7Cb%7Cc%7C%0A%7C-%7C-%7C-%7C%0A%7C1%7C2%7C3%7C%0A%0A%23%20table2%0A%0A%7Cd%7Ce%7Cf%7C%0A%7C-%7C-%7C-%7C%0A%7C4%7C5%7C6%7C&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master)

Sorry, I just checked that the following problem is not a problem of our product, but the generated HTML (`<table>`) label does not carry ` class= "table"` to make the style not displayed normally. Thank you for your reply. I wish you better and better.

**Comment by markofred** [comment]
> > Looks like it is working for me [demo](https://marked.js.org/demo/?text=%23%20table1%0A%0A%7Ca%7Cb%7Cc%7C%0A%7C-%7C-%7C-%7C%0A%7C1%7C2%7C3%7C%0A%0A%23%20table2%0A%0A%7Cd%7Ce%7Cf%7C%0A%7C-%7C-%7C-%7C%0A%7C4%7C5%7C6%7C&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master)
> 
> Sorry, I just checked that the following problem is not a problem of our product, but the generated HTML (`<table>`) label does not carry ` class= "table"` to make the style not displayed normally. Thank you for your reply. I wish you better and better.

I try to use ` jquery`  
```  jquery
$('table').addClass('table table-hover table-bordered');
```
 The problem is solved.
