### ISSUE TITLE
An exemple about how to us and prevent xss

### ISSUE THREAD

**Issue by iNeoO** [markedjs/marked#2062]
**Describe the feature**
Hi, i would like to know how to setup with a sanitizer and prevent xss with an exemple.

**Why is this feature necessary?**
It s not easy to prevent xss and to know what is the best way to do it with marked.
in #1361 clean is done after sanitize, so it break the code.

Just sanitize let's possible to do this `[some text](javascript:alert('xss'))`

I have done this, but is it the best way ? Did i forget anything ?  (in my case i used, sanitize-html)
```javascript
import marked from 'marked';
import sanitizeHtml from 'sanitize-html';

const blockList = ['http', 'https'];
const sanitized = sanitizeHtml(textToParse, { disallowedTagsMode: 'recursiveEscape' });

marked.use({
  renderer: {
    link: (href, title, text) => {
      if (!blockList.some((p) => href.startsWith(p))) {
        return text;
      }
      let out = `<a href="${href}"`;
      if (title) {
        out += ` title="${title}"`;
      }
      out += `>${text}</a>`;
      return out;
    },
  },
});

marked(sanitized);
```
(> for list doesn't work this way because converted to html character)

**Comment by UziTech** [comment]
The easiest way is to run the output of marked through `sanitizeHTML`.

```js
import marked from 'marked';
import sanitizeHtml from 'sanitize-html';

const dirty = marked(markdown);
const sanitized = sanitizeHtml(dirty);
```

**Comment by iNeoO** [comment]
but this way 
```
> list
> list
> list
```
Doesn't work and markdown generated is vulnerable to `[some text](javascript:alert('xss'))`

**Comment by UziTech** [comment]
seems to work for me: [demo](https://runkit.com/embed/4bvs7c1heewf)

**Comment by iNeoO** [comment]
thx for your time, yeah most of things work this way except image 
`!{](https://www.google.fr/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png)`

**Comment by UziTech** [comment]
There is probably a setting in sanitize-html to leave images.

**Comment by UziTech** [comment]
Sanitize-html has an [example](https://www.npmjs.com/package/sanitize-html#common-use-cases) on their readme to allow img tags.

```js
const clean = sanitizeHtml(dirty, {
  allowedTags: sanitizeHtml.defaults.allowedTags.concat([ 'img' ])
});
```

**Comment by iNeoO** [comment]
ok thx !
