### ISSUE TITLE
How do I convert marked. Lexer (markdown, options) data back to markdown  

### ISSUE THREAD

**Issue by jahnli** [markedjs/marked#2063]
**Marked version:**
last
**Describe the bug**

**To Reproduce**

How do I convert marked. Lexer (markdown, options) data back to markdown

**Comment by UziTech** [comment]
duplicate of #1986

**Comment by jahnli** [comment]
Is turndown the only solution currently used?  Will MarkedJS provide a solution?    @UziTech

**Comment by UziTech** [comment]
No, marked turns markdown into html. we try to do one thing well instead of trying to do everything.

**Comment by jahnli** [comment]
![image](https://user-images.githubusercontent.com/20943608/119087133-3761f180-ba39-11eb-9f7b-ced93b00709d.png)
I try to a form of md to HTML, when I use turndown again to md, | disappear, lead to form failure

**Comment by jahnli** [comment]
@UziTech  
![Uploading image.png…]()

**Comment by jahnli** [comment]
![image](https://user-images.githubusercontent.com/20943608/119087275-74c67f00-ba39-11eb-9060-d345d9a83967.png)
@UziTech

**Comment by UziTech** [comment]
@jahnli You should create an issue on [turndowns](https://github.com/domchristie/turndown) repo

**Comment by jahnli** [comment]
Is it possible to convert the contents of HTML tags in md to lexer

**Comment by UziTech** [comment]
Not with marked
