### ISSUE TITLE
Cannot read property p of undefined type error

### ISSUE THREAD

**Issue by manideepvadla** [markedjs/marked#2064]
TypeError: Cannot read property 'p' of undefined
Please report this to https://github.com/chjj/marked.
Renderer.push../node_modules/react-marked/lib/marked.js.Renderer.paragraph
C:/Users/w10083508/Desktop/Training React/mypractice/node_modules/react-marked/lib/marked.js:792
  789 | 
  790 |    Renderer.prototype.paragraph = function (text) {
  791 |        console.log(text);
> 792 |        return React.DOM.p(null,text);
      | ^  793 |    };
  794 | 
  795 |    Renderer.prototype.table = function (header, body) {
View compiled
Parser.push../node_modules/react-marked/lib/marked.js.Parser.tok
C:/Users/w10083508/Desktop/Training React/mypractice/node_modules/react-marked/lib/marked.js:1044
  1041 | }
  1042 | case 'paragraph':
  1043 | {
> 1044 |     return this.renderer.paragraph(this.inline.output(this.token.text));
       | ^  1045 | }
  1046 | case 'text':
  1047 | {
View compiled
Parser.push../node_modules/react-marked/lib/marked.js.Parser.parse
C:/Users/w10083508/Desktop/Training React/mypractice/node_modules/react-marked/lib/marked.js:891
  888 | 
  889 |        var out = [];
  890 |        while (this.next()) {
> 891 |            out.push(this.tok());
      | ^  892 |        }
  893 | 
  894 |        return out;
View compiled
Function.push../node_modules/react-marked/lib/marked.js.Parser.parse
C:/Users/w10083508/Desktop/Training React/mypractice/node_modules/react-marked/lib/marked.js:878
  875 | 
  876 |    Parser.parse = function (src, options, renderer) {
  877 |        var parser = new Parser(options, renderer);
> 878 |        return parser.parse(src);
      | ^  879 |    };
  880 | 
  881 |    /**
View compiled
marked
C:/Users/w10083508/Desktop/Training React/mypractice/node_modules/react-marked/lib/marked.js:1184
  1181 | }
  1182 | try {
  1183 |     if (opt) opt = merge({}, marked.defaults, opt);
> 1184 |     return Parser.parse(Lexer.lex(src, opt), opt);
       | ^  1185 | } catch (e) {
  1186 |     e.message += '\nPlease report this to https://github.com/chjj/marked.';
  1187 |     if ((opt || marked.defaults).silent) {
View compiled
Markdown.rawMarkup
C:/Users/w10083508/Desktop/Training React/mypractice/src/Markdown.js:81
  78 |         // }
  79 |     })
  80 |     console.log(this.state.content);
> 81 |     var rawMarkup = marked(this.state.content)
     | ^  82 |     return { __html :rawMarkup }
  83 | }
  84 | render() {
View compiled
Markdown.render
C:/Users/w10083508/Desktop/Training React/mypractice/src/Markdown.js:95
  92 |   </div>
  93 |   <div className="form-group col-md-6" id="output">
  94 |     <label>Output</label>
> 95 |     <div id="outputText" dangerouslySetInnerHTML={this.rawMarkup()} ></div>
     | ^  96 |   </div>
  97 | </div>
  98 |         </div>
View compiled
finishClassComponent
C:/Users/w10083508/Desktop/Training React/mypractice/node_modules/react-dom/cjs/react-dom.development.js:17485
  17482 | } else {
  17483 |   {
  17484 |     setIsRendering(true);
> 17485 |     nextChildren = instance.render();
        | ^  17486 | 
  17487 |     if ( workInProgress.mode & StrictMode) {
  17488 |       disableLogs();
View compiled
updateClassComponent
C:/Users/w10083508/Desktop/Training React/mypractice/node_modules/react-dom/cjs/react-dom.development.js:17435
  17432 |   shouldUpdate = updateClassInstance(current, workInProgress, Component, nextProps, renderLanes);
  17433 | }
  17434 | 
> 17435 | var nextUnitOfWork = finishClassComponent(current, workInProgress, Component, shouldUpdate, hasContext, renderLanes);
        | ^  17436 | 
  17437 | {
  17438 |   var inst = workInProgress.stateNode;
View compiled
beginWork
C:/Users/w10083508/Desktop/Training React/mypractice/node_modules/react-dom/cjs/react-dom.development.js:19073
  19070 | 
  19071 |     var _resolvedProps = workInProgress.elementType === _Component2 ? _unresolvedProps : resolveDefaultProps(_Component2, _unresolvedProps);
  19072 | 
> 19073 |     return updateClassComponent(current, workInProgress, _Component2, _resolvedProps, renderLanes);
        | ^  19074 |   }
  19075 | 
  19076 | case HostRoot:
View compiled
HTMLUnknownElement.callCallback
C:/Users/w10083508/Desktop/Training React/mypractice/node_modules/react-dom/cjs/react-dom.development.js:3945
  3942 | function callCallback() {
  3943 |   didCall = true;
  3944 |   restoreAfterDispatch();
> 3945 |   func.apply(context, funcArgs);
       | ^  3946 |   didError = false;
  3947 | } // Create a global error event handler. We use this to capture the value
  3948 | // that was thrown. It's possible that this error handler will fire more
View compiled
invokeGuardedCallbackDev
C:/Users/w10083508/Desktop/Training React/mypractice/node_modules/react-dom/cjs/react-dom.development.js:3994
  3991 | // errors, it will trigger our global error handler.
  3992 | 
  3993 | evt.initEvent(evtType, false, false);
> 3994 | fakeNode.dispatchEvent(evt);
       | ^  3995 | 
  3996 | if (windowEventDescriptor) {
  3997 |   Object.defineProperty(window, 'event', windowEventDescriptor);
View compiled
invokeGuardedCallback
C:/Users/w10083508/Desktop/Training React/mypractice/node_modules/react-dom/cjs/react-dom.development.js:4056
  4053 | function invokeGuardedCallback(name, func, context, a, b, c, d, e, f) {
  4054 |   hasError = false;
  4055 |   caughtError = null;
> 4056 |   invokeGuardedCallbackImpl$1.apply(reporter, arguments);
  4057 | }
  4058 | /**
  4059 |  * Same as invokeGuardedCallback, but instead of returning an error, it stores
View compiled
beginWork$1
C:/Users/w10083508/Desktop/Training React/mypractice/node_modules/react-dom/cjs/react-dom.development.js:23964
  23961 | } // Run beginWork again.
  23962 | 
  23963 | 
> 23964 | invokeGuardedCallback(null, beginWork, null, current, unitOfWork, lanes);
        | ^  23965 | 
  23966 | if (hasCaughtError()) {
  23967 |   var replayError = clearCaughtError(); // `invokeGuardedCallback` sometimes sets an expando `_suppressLogging`.
View compiled
performUnitOfWork
C:/Users/w10083508/Desktop/Training React/mypractice/node_modules/react-dom/cjs/react-dom.development.js:22776
  22773 | 
  22774 | if ( (unitOfWork.mode & ProfileMode) !== NoMode) {
  22775 |   startProfilerTimer(unitOfWork);
> 22776 |   next = beginWork$1(current, unitOfWork, subtreeRenderLanes);
        | ^  22777 |   stopProfilerTimerIfRunningAndRecordDelta(unitOfWork, true);
  22778 | } else {
  22779 |   next = beginWork$1(current, unitOfWork, subtreeRenderLanes);
View compiled
workLoopSync
C:/Users/w10083508/Desktop/Training React/mypractice/node_modules/react-dom/cjs/react-dom.development.js:22707
  22704 | function workLoopSync() {
  22705 |   // Already timed out, so perform work without checking if we need to yield.
  22706 |   while (workInProgress !== null) {
> 22707 |     performUnitOfWork(workInProgress);
  22708 |   }
  22709 | }
  22710 | 
View compiled
renderRootSync
C:/Users/w10083508/Desktop/Training React/mypractice/node_modules/react-dom/cjs/react-dom.development.js:22670
  22667 | 
  22668 | do {
  22669 |   try {
> 22670 |     workLoopSync();
        | ^  22671 |     break;
  22672 |   } catch (thrownValue) {
  22673 |     handleError(root, thrownValue);
View compiled
performSyncWorkOnRoot
C:/Users/w10083508/Desktop/Training React/mypractice/node_modules/react-dom/cjs/react-dom.development.js:22293
  22290 |   }
  22291 | } else {
  22292 |   lanes = getNextLanes(root, NoLanes);
> 22293 |   exitStatus = renderRootSync(root, lanes);
        | ^  22294 | }
  22295 | 
  22296 | if (root.tag !== LegacyRoot && exitStatus === RootErrored) {
View compiled
(anonymous function)
C:/Users/w10083508/Desktop/Training React/mypractice/node_modules/react-dom/cjs/react-dom.development.js:11327
  11324 |     var callback = _queue[i];
  11325 | 
  11326 |     do {
> 11327 |       callback = callback(_isSync2);
        | ^  11328 |     } while (callback !== null);
  11329 |   }
  11330 | });
View compiled
unstable_runWithPriority
C:/Users/w10083508/Desktop/Training React/mypractice/node_modules/scheduler/cjs/scheduler.development.js:468
  465 | currentPriorityLevel = priorityLevel;
  466 | 
  467 | try {
> 468 |   return eventHandler();
      | ^  469 | } finally {
  470 |   currentPriorityLevel = previousPriorityLevel;
  471 | }
View compiled
runWithPriority$1
C:/Users/w10083508/Desktop/Training React/mypractice/node_modules/react-dom/cjs/react-dom.development.js:11276
  11273 | 
  11274 | function runWithPriority$1(reactPriorityLevel, fn) {
  11275 |   var priorityLevel = reactPriorityToSchedulerPriority(reactPriorityLevel);
> 11276 |   return Scheduler_runWithPriority(priorityLevel, fn);
  11277 | }
  11278 | function scheduleCallback(reactPriorityLevel, callback, options) {
  11279 |   var priorityLevel = reactPriorityToSchedulerPriority(reactPriorityLevel);
View compiled
flushSyncCallbackQueueImpl
C:/Users/w10083508/Desktop/Training React/mypractice/node_modules/react-dom/cjs/react-dom.development.js:11322
  11319 | try {
  11320 |   var _isSync2 = true;
  11321 |   var _queue = syncQueue;
> 11322 |   runWithPriority$1(ImmediatePriority$1, function () {
        | ^  11323 |     for (; i < _queue.length; i++) {
  11324 |       var callback = _queue[i];
  11325 | 
View compiled
flushSyncCallbackQueue
C:/Users/w10083508/Desktop/Training React/mypractice/node_modules/react-dom/cjs/react-dom.development.js:11309
  11306 |     Scheduler_cancelCallback(node);
  11307 |   }
  11308 | 
> 11309 |   flushSyncCallbackQueueImpl();
  11310 | }
  11311 | 
  11312 | function flushSyncCallbackQueueImpl() {
View compiled
flushPendingDiscreteUpdates
C:/Users/w10083508/Desktop/Training React/mypractice/node_modules/react-dom/cjs/react-dom.development.js:22372
  22369 |   } // Now flush the immediate queue.
  22370 | 
  22371 | 
> 22372 |   flushSyncCallbackQueue();
  22373 | }
  22374 | 
  22375 | function batchedUpdates$1(fn, a) {
View compiled
flushDiscreteUpdates
C:/Users/w10083508/Desktop/Training React/mypractice/node_modules/react-dom/cjs/react-dom.development.js:22353
  22350 |   return;
  22351 | }
  22352 | 
> 22353 | flushPendingDiscreteUpdates(); // If the discrete updates scheduled passive effects, flush them now so that
        | ^  22354 | // they fire before the next serial event.
  22355 | 
  22356 | flushPassiveEffects();
View compiled
finishEventHandler
C:/Users/w10083508/Desktop/Training React/mypractice/node_modules/react-dom/cjs/react-dom.development.js:3714
  3711 |     // If a controlled event was fired, we may need to restore the state of
  3712 |     // the DOM node back to the controlled value. This is necessary when React
  3713 |     // bails out of the update without touching the DOM.
> 3714 |     flushDiscreteUpdatesImpl();
  3715 |     restoreStateIfNeeded();
  3716 |   }
  3717 | }
View compiled
batchedEventUpdates
C:/Users/w10083508/Desktop/Training React/mypractice/node_modules/react-dom/cjs/react-dom.development.js:3748
  3745 |     return batchedEventUpdatesImpl(fn, a, b);
  3746 |   } finally {
  3747 |     isBatchingEventUpdates = false;
> 3748 |     finishEventHandler();
  3749 |   }
  3750 | }
  3751 | function discreteUpdates(fn, a, b, c, d) {
View compiled
dispatchEventForPluginEventSystem
C:/Users/w10083508/Desktop/Training React/mypractice/node_modules/react-dom/cjs/react-dom.development.js:8507
  8504 |     }
  8505 |   }
  8506 | 
> 8507 |   batchedEventUpdates(function () {
  8508 |     return dispatchEventsForPlugins(domEventName, eventSystemFlags, nativeEvent, ancestorInst);
  8509 |   });
  8510 | }
View compiled
attemptToDispatchEvent
C:/Users/w10083508/Desktop/Training React/mypractice/node_modules/react-dom/cjs/react-dom.development.js:6005
  6002 |     }
  6003 |   }
  6004 | 
> 6005 |   dispatchEventForPluginEventSystem(domEventName, eventSystemFlags, nativeEvent, targetInst, targetContainer); // We're not blocked on anything.
  6006 | 
  6007 |   return null;
  6008 | }
View compiled
dispatchEvent
C:/Users/w10083508/Desktop/Training React/mypractice/node_modules/react-dom/cjs/react-dom.development.js:5924
  5921 |   return;
  5922 | }
  5923 | 
> 5924 | var blockedOn = attemptToDispatchEvent(domEventName, eventSystemFlags, targetContainer, nativeEvent);
       | ^  5925 | 
  5926 | if (blockedOn === null) {
  5927 |   // We successfully dispatched this event.
View compiled
unstable_runWithPriority
C:/Users/w10083508/Desktop/Training React/mypractice/node_modules/scheduler/cjs/scheduler.development.js:468
  465 | currentPriorityLevel = priorityLevel;
  466 | 
  467 | try {
> 468 |   return eventHandler();
      | ^  469 | } finally {
  470 |   currentPriorityLevel = previousPriorityLevel;
  471 | }
View compiled
runWithPriority$1
C:/Users/w10083508/Desktop/Training React/mypractice/node_modules/react-dom/cjs/react-dom.development.js:11276
  11273 | 
  11274 | function runWithPriority$1(reactPriorityLevel, fn) {
  11275 |   var priorityLevel = reactPriorityToSchedulerPriority(reactPriorityLevel);
> 11276 |   return Scheduler_runWithPriority(priorityLevel, fn);
  11277 | }
  11278 | function scheduleCallback(reactPriorityLevel, callback, options) {
  11279 |   var priorityLevel = reactPriorityToSchedulerPriority(reactPriorityLevel);
View compiled
discreteUpdates$1
C:/Users/w10083508/Desktop/Training React/mypractice/node_modules/react-dom/cjs/react-dom.development.js:22413
  22410 | 
  22411 | {
  22412 |   try {
> 22413 |     return runWithPriority$1(UserBlockingPriority$2, fn.bind(null, a, b, c, d));
        | ^  22414 |   } finally {
  22415 |     executionContext = prevExecutionContext;
  22416 | 
View compiled
discreteUpdates
C:/Users/w10083508/Desktop/Training React/mypractice/node_modules/react-dom/cjs/react-dom.development.js:3756
  3753 | isInsideEventHandler = true;
  3754 | 
  3755 | try {
> 3756 |   return discreteUpdatesImpl(fn, a, b, c, d);
       | ^  3757 | } finally {
  3758 |   isInsideEventHandler = prevIsInsideEventHandler;
  3759 | 
View compiled
dispatchDiscreteEvent
C:/Users/w10083508/Desktop/Training React/mypractice/node_modules/react-dom/cjs/react-dom.development.js:5889
  5886 |     flushDiscreteUpdatesIfNeeded(nativeEvent.timeStamp);
  5887 |   }
  5888 | 
> 5889 |   discreteUpdates(dispatchEvent, domEventName, eventSystemFlags, container, nativeEvent);
  5890 | }
  5891 | 
  5892 | function dispatchUserBlockingUpdate(domEventName, eventSystemFlags, container, nativeEvent) {
View compiled

**Comment by UziTech** [comment]
This is an issue in react-marked. You should create an issue on their repo with this information.

Looks like React.DOM is undefined.
