### ISSUE TITLE
ordered lists or unordered lists can't render number identification

### ISSUE THREAD

**Issue by 957739315** [markedjs/marked#2091]
**Marked version:** 2.0.7

**Describe the bug**
For ordered lists or unordered lists, the serial number identification cannot be rendered normally.

**my render**
![image](https://user-images.githubusercontent.com/30749068/120996052-8e492400-c7b8-11eb-9d27-dd7aa1380876.png)

![image](https://user-images.githubusercontent.com/30749068/120996147-a620a800-c7b8-11eb-9b3a-03cb9e8640c0.png)

**from official demo**
![image](https://user-images.githubusercontent.com/30749068/120996286-c3ee0d00-c7b8-11eb-895b-3b05fdda7a17.png)

![image](https://user-images.githubusercontent.com/30749068/120996335-ce100b80-c7b8-11eb-81c3-93e760e0e8d6.png)

what can i do to fix it to render nomally?

**Comment by capndave** [comment]
@957739315 this was closed without any notes but doesn't appear to have been fixed. The numbers of my list items don't appear if I copy/paste rendered markdown into another window. Opening a new issue.
