### ISSUE TITLE
Hightlight Function Not Being Called

### ISSUE THREAD

**Issue by Alien10123** [markedjs/marked#2098]
**Marked version: 2.0.7**

**Describe the bug**
I have some markdown with code snippets and in the ```marked.setOptions``` function I made a highlight function that uses prism js to highlight the code and then return it, but when I convert markdown to HTML it doesn't seem to call the function.

**To Reproduce**
Steps to reproduce the behaviour:

Make some markdown code with code snippets like:
````markdown
# hi
this is markdown
```html
<h1>hi</h1>
```
```css
hi {
    color: red;
}
```
````

Then import marked js (I am using vite so I use esm and I installed it from npm and not using a script tag):
```javascript
import marked from 'marked'
```

And after that set the options for marked like:
```javascript
marked.setOptions({
    highlight: function (code, lang) {
        console.log(1);
        return Prism.highlight(
             code,
              Prism.languages[lang],
               lang
           );
    },
});
```

And then try and convert the markdown you created before to html.

**Expected behaviour**
It should highlight the code snippets and log 1 to the console.

Does dose anyone know why this doesn't work?
Thanks in advance!

**Comment by UziTech** [comment]
It seems to work fine for me. can you share what output you get and how you call marked?

**Comment by Alien10123** [comment]
I was importing the string from a json file, but when I hard code it seems to work. I don't know why. This is what it would look like in the json file:
```
# hi\rthis is markdown\r```html\r<h1>hi</h1>\r```\r```css\rhi { \r    color: red;\t}r``\r
```

Cloud this be the problem? And also I need to think of a way to convert the lang value that the highlight function to the prism object and string.

**Comment by UziTech** [comment]
There are no new line characters (`\n`) in that markdown so there are no code blocks.

**Comment by Alien10123** [comment]
> There are no new line characters (`\n`) in that markdown so there are no code blocks.

Well, then how do I make a new line in markdown? ```<br />``` works, but when I want to do a code snippet if I can't put ```<br />``` in it. So what can I use?

**Comment by UziTech** [comment]
The json markdown should be
````markdown
# hi\n\nthis is markdown\n\n```html\n<h1>hi</h1>\n```\n\n```css\nhi {\n    color: red;\n}\n```\n
````

Then the output will be like this [demo](https://marked.js.org/demo/?text=%23%20hi%0A%0Athis%20is%20markdown%0A%0A%60%60%60html%0A%3Ch1%3Ehi%3C%2Fh1%3E%0A%60%60%60%0A%0A%60%60%60css%0Ahi%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%7D%0A%60%60%60%0A&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master) and highlight will be called twice.

**Comment by Alien10123** [comment]
> The json markdown should be
> 
> ```
> # hi\n\nthis is markdown\n\n```html\n<h1>hi</h1>\n```\n\n```css\nhi {\n    color: red;\n}\n```\n
> ```
> 
> Then the output will be like this [demo](https://marked.js.org/demo/?text=%23%20hi%0A%0Athis%20is%20markdown%0A%0A%60%60%60html%0A%3Ch1%3Ehi%3C%2Fh1%3E%0A%60%60%60%0A%0A%60%60%60css%0Ahi%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%7D%0A%60%60%60%0A&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master) and highlight will be called twice.
> 
> Those `\n` in the string are [newline characters](http://jennifermadden.com/javascript/lineBreaks.html) in javascript. `` ``` `` without a new line character before it is the start of an inline code block which does not get highlighted.

Thank! It works now!
