### ISSUE TITLE
const prevRenderer = extensions.renderers?.[ext.name];

### ISSUE THREAD

**Issue by Bielykh-Artem** [markedjs/marked#2110]
const prevRenderer = extensions.renderers?.[ext.name];
SyntaxError: Unexpected token '.'

**Comment by Bulkman** [comment]
Package semantic-release broke cuz of this. They are having "marked": "^2.0.0" in package.json.
Requesting update as soon as possible

**Comment by Bulkman** [comment]
> Package semantic-release broke cuz of this. They are having "marked": "^2.0.0" in package.json.
> Requesting update as soon as possible

Though more reasonable would be requesting update in semantic-release doc to drop Node < 14

**Comment by Aggtaa** [comment]
protobufjs via jsdoc broke because of this

**Comment by UziTech** [comment]
Duplicate of #2106
