### ISSUE TITLE
can't get a complete LaTeX

### ISSUE THREAD

**Issue by zhugexinxin** [markedjs/marked#2127]
**Marked version:2.1.3**

**Describe the bug**
```
Renderer = {
  text(text) {
    console.log(text)
  }
}

input: $\left\{a_n\right\}$
output: $\left
output: {
output: a_n\right
output: }
output: $
```

I expect to get complete, I don't know how to solve

![image](https://user-images.githubusercontent.com/42615243/124342598-8d5cb400-dbf7-11eb-87f6-b31edc1f1090.png)
![image](https://user-images.githubusercontent.com/42615243/124342600-93529500-dbf7-11eb-9f7b-9e7611a30857.png)

**Comment by UziTech** [comment]
LaTeX isn't supported by marked. You can try creating an [extension](https://marked.js.org/using_pro#extensions) that makes it work.

You can also look at https://github.com/markedjs/marked/issues/1538#issuecomment-575838181 for more information.
