### ISSUE TITLE
Tables don't work with smartypants

### ISSUE THREAD

**Issue by nidoro** [markedjs/marked#2140]
**Marked version:** 2.1.2

Tables are not properly tokenized by the lexer when smartypants is on.
```JS
let source = `
| Table Heading | Center align  | Right align   |
|---------------|:-------------:|--------------:|
| Item 1        | Item 2        | Item 3        |
| Item 1        | Item 2        | Item 3        |
| Item 1        | Item 2        | Item 3        |
`;

marked.lexer(source, {smartypants: true});

// Output:
[
  {type: "paragraph", raw: "| Table Heading | Center align...", ...}
]
```

If smartypants is off it returns a table rather than a paragraph, as expected. Weirdly, if I call `marked(source, {smartypants: true})` directly, it properly renders the table.

I also noted that if I **explicitly** disable smartypants with `marked.lexer(source, {smartypants: false})`, the result is the same as if it was enabled. But if I pass no `options` to the call, i.e. `marked.lexer(source)`, it works fine. `marked.lexer(source, {})` also returns incorrect results, as when smartypants is true.

**Comment by UziTech** [comment]
The `lexer` and `parser` assume all options are passed into it. so `{smartypants: true}` is the same as `{smartypants: true, gfm: undefined}`. Since tables are only defined in the gfm spec not the CommonMark spec it will not create a table token.

You could set smartypants as a default:

```js
marked.use({smartypants: true});
marked.lexer(source);
```

or include the defaults in the options object:

```js
marked.lexer(source, {
  ...marked.getDefaults(),
  smartypants: true
});
```

**Comment by nidoro** [comment]
Ah, I see. Thanks for the help! `marked.use({smartypants: true})` worked perfectly.
