### ISSUE TITLE
Custom Extensions example (description, descriptionlist extensions) doesn't work

### ISSUE THREAD

**Issue by hrbigelow** [markedjs/marked#2144]
**Marked version:**
1.2.9

**Describe the bug**
The demo at [https://marked.js.org/using_pro#extensions](https://marked.js.org/using_pro#extensions) doesn't work.

**To Reproduce**
Cut and paste the entire contents of the code  in the 'Custom Extensions' into 'node'.  It produces:

```html
<p>A Description List:
:   Topic 1   :  Description 1
: <strong>Topic 2</strong> : <em>Description 2</em></p>
```

rather than what the example shows:

```html
<p>A Description List:</p>
<dl>
<dt>Topic 1</dt><dd>Description 1</dd>
<dt><strong>Topic 2 walked</strong></dt><dd><em>Description 2</em></dd>
</dl>
```

**Expected behavior**

**Comment by calculuschild** [comment]
Extensions were introduced in v 2.1.0.  Update to the latest version of Marked and it should work like a charm!

**Comment by hrbigelow** [comment]
Works!  Thank you calculuschild.

**Comment by hrbigelow** [comment]
Hi, so I tried the following block-level extension, but it does some strange things.

```javascript
marked = require('marked');

const dmath_block = {
  name: 'dmath_block',
  level: 'block',
  start(src) { return src.match(/\$\n\\begin/)?.index; },
  tokenizer(src, tokens) {
    const rule = /^\$(\n\\begin{aligned}\n.+\\end{aligned}\n)\$\n/ms;
    const match = rule.exec(src);
    if (match) {
      // console.log(match);
      return {
        type: 'dmath_block',
        raw: match[0],
        text: match[1]
      };
    }
  },
  renderer(token) {
    return `<d-math block>\n{@html \`${token.text}\`}\n</d-math>\n`;
  }
};

md = '# Heading 1 \n\n$\n\\begin{aligned}\nk_j\n\\end{aligned}\n$\n\n'
console.log(md)
# Heading 1 

$
\begin{aligned}
k_j
\end{aligned}
$

console.log(marked(md))
<d-math block>
{@html `
\begin{aligned}
k_j
\end{aligned}
`}
</d-math>
<p>nd{aligned}
$</p>
```

You can see in the output that the `nd{aligned}\n$` is left over.  However, the documentation says that the 'raw' field specifies the part of the input to be consumed, which includes everything between the `$` pair.  Am I doing something wrong?

Thanks in advance!

**Comment by hrbigelow** [comment]
This turned out to be due to the presence of multiple of the same parser, and also an error in the regexp.  It is not a bug.
