### ISSUE TITLE
calling marked.use({ extensions: [ my_extension ] }) twice results in duplicate extensions registered

### ISSUE THREAD

**Issue by hrbigelow** [markedjs/marked#2145]
**Marked version:**
2.1.0

**Describe the bug**
While developing in nodejs, I frequently will update my source, then reload it with:

```javascript
import(`mymodule.js#${Math.random()}`).then(module => { pp = module });
```

I was trying to then update marked extension with:

```javascript
marked.use({ extensions: [ pp.my_extension ] });
```

However, this development cycle does not work.  The first time `marked.use()` is called, things work as expected.  But subsequent calls do not seem to replace the previously registered extension with the new one, even though they have the same `name:` field.

Is this intended behavior, or is there a way to clear marked, without having to restart nodejs?

**To Reproduce**
Steps to reproduce the behavior:  see abovef

**Comment by UziTech** [comment]
You can reset marked settings by calling `marked.setOptions(marked.getDefaults());`

Allowing multiple extensions with the same name is intended. That way you can have overlapping extensions and if one returns `false` it will fall back to the previous one.

**Comment by hrbigelow** [comment]
Thanks very much UziTech!
