### ISSUE TITLE
Ordered list items don't include numbers

### ISSUE THREAD

**Issue by capndave** [markedjs/marked#2150]
**Marked version:**
2.1.3

**Describe the bug**
The numbers of my list items don't appear if I copy/paste rendered markdown into another window. This probably has something to do with rendered `<li>` tags not including the number associated with them in markdown. [This issue](https://github.com/markedjs/marked/issues/2091) was opened for the same but appears to have been closed without any fix or documentation, for some reason. 

**To Reproduce**
- See  [this issue](https://github.com/markedjs/marked/issues/2091) OR
- parse the following markdown with marked, check whether rendered `li` items include numbers
```markdown
1. this
2. is
3. an example
```

**Expected behavior**
Numbers to appear in list items

**Comment by calculuschild** [comment]
This works just fine in my personal project. Do you by chance have some custom CSS or something that would cause the `display` type of your lists to not be `display: list-item`  ?

As far as I understand, whether `::marker` appears or not is entirely dependent on your CSS stylesheet.

**Comment by UziTech** [comment]
The HTML renderer (the browser) displays the numbers in an ordered list. They do not need to be present in the HTML rendered by marked.
