### ISSUE TITLE
emStrong is not working well in specific case

### ISSUE THREAD

**Issue by 3jins** [markedjs/marked#2154]
**Marked version:** 2.1.3

**Describe the bug**
emStrong doesn't work when a string wrapped with `*` ends with a special character and another string follows without space.

**To Reproduce**
[reproduction demo](https://marked.js.org/demo/?text=**%5Bbug%5D**emStrong%20is%20not%20working%20well&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22extensions%22%3A%20null%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=2.1.3)

**Expected behavior**
- markdown String given: `**[bug]**emStrong is not working well`
- expected result: `<strong>[bug]</strong>emStrong is not working well`
- real result: `**[bug]**emStrong is not working well` (not rendered)

It can be regarded as a very insignificant issue because it's so rare case in English, but not in many other languages. For example, case like this can be easily found in Korean: `가수 **이지은(29)**이 Lilac 앨범을 발표했다.` And Chinese doesn't even use space in the sentence.

**Comment by UziTech** [comment]
The actual result actually follows the [spec](https://spec.commonmark.org/dingus/?text=**%5Bbug%5D**emStrong%20is%20not%20working%20well) an ending `**` or `*` must be followed by a punctuation or space character.

**Comment by 3jins** [comment]
Ok, I understood.
It can be inappropriate to fix marked.js since the spec is different from my expectation. But for users like me, I've written tokenizer code solving the issue above. All I did is to copy the original tokenizer code and just remove the code checking `rules.inline.punctuation`.

```typescript
const tokenizer: Tokenizer = {
  // @ts-ignore
  emStrong(src, maskedSrc, prevChar = '') {
    const rules = {
      lDelim: /^(?:\*+(?:([_])|[^\s*]))|^_+(?:([*])|([^\s_]))/,
      rDelimAst: /__[^_*]*?\*[^_*]*?__|[_](\*+)(?=[\s]|$)|[^*_\s](\*+)(?=[_\s]|$)|[_\s](\*+)(?=[^*_\s])|[\s](\*+)(?=[_])|[_](\*+)(?=[_])|[^*_\s](\*+)(?=[^*_\s])/, // eslint-disable-line max-len
      rDelimUnd: /\*\*[^_*]*?_[^_*]*?\*\*|[*](_+)(?=[\s]|$)|[^*_\s](_+)(?=[*\s]|$)|[*\s](_+)(?=[^*_\s])|[\s](_+)(?=[*])|[*](_+)(?=[*])/, // eslint-disable-line max-len
    };

    let match = rules.lDelim.exec(src);
    if (!match) return;

    // _ can't be between two alphanumerics. \p{L}\p{N} includes non-english alphabet/numbers as well
    if (match[3] && prevChar.match(/[\p{L}\p{N}]/u)) return;

    const nextChar = match[1] || match[2] || '';

    if (!nextChar || (nextChar && (prevChar === ''))) {
      const lLength = match[0].length - 1;
      let rDelim, rLength, delimTotal = lLength, midDelimTotal = 0;

      const endReg = match[0][0] === '*' ? rules.rDelimAst : rules.rDelimUnd;
      endReg.lastIndex = 0;

      // Clip maskedSrc to same section of string as src (move to lexer?)
      maskedSrc = maskedSrc.slice(-1 * src.length + lLength);

      while ((match = endReg.exec(maskedSrc)) != null) {
        rDelim = match[1] || match[2] || match[3] || match[4] || match[5] || match[6];

        if (!rDelim) continue; // skip single * in __abc*abc__

        rLength = rDelim.length;

        if (match[3] || match[4]) { // found another Left Delim
          delimTotal += rLength;
          continue;
        } else if (match[5] || match[6]) { // either Left or Right Delim
          if (lLength % 3 && !((lLength + rLength) % 3)) {
            midDelimTotal += rLength;
            continue; // CommonMark Emphasis Rules 9-10
          }
        }

        delimTotal -= rLength;

        if (delimTotal > 0) continue; // Haven't found enough closing delimiters

        // Remove extra characters. *a*** -> *a*
        rLength = Math.min(rLength, rLength + delimTotal + midDelimTotal);

        // Create `em` if smallest delimiter has odd char count. *a***
        if (Math.min(lLength, rLength) % 2) {
          return {
            type: 'em',
            raw: src.slice(0, lLength + match.index + rLength + 1),
            text: src.slice(1, lLength + match.index + rLength),
          };
        }

        // Create 'strong' if smallest delimiter has even char count. **a***
        return {
          type: 'strong',
          raw: src.slice(0, lLength + match.index + rLength + 1),
          text: src.slice(2, lLength + match.index + rLength - 1),
        };
      }
    }
  },
};

marked.use({ tokenizer });
```

I'd like to suggest carefully to add an option for not checking ending punctuation rule if you don't mind it.

**Comment by UziTech** [comment]
You can create an extension with this fix then anyone who wants to use is can just install your dependency as an extension and use it like:

```
const marked = require('marked');
const marked_extensions_em_without_punctuation = require('marked_extensions_em_without_punctuation');
marked.use(marked_extensions_em_without_punctuation);
```

**Comment by 3jins** [comment]
Hmm.. I think creating an extension npm module only to fix this single issue isn't good idea because users should manage an additional dependency and investigate what does my unfamous extension library really do before they use it.
Anyway, I found the solution of my problem, and I feel grateful for your explanations!
