### ISSUE TITLE
Some Markdown elements do not render

### ISSUE THREAD

**Issue by Ha0ran2001** [markedjs/marked#2155]
Marked version:
^2.1.3
Describe the bug
Some Markdown elements do not render in vite such as the title.

To Reproduce
`const renderer = new marked.Renderer();
marked.setOptions({
renderer: renderer,
gfm: true,
pedantic: false,
sanitize: false,
tables: true,
breaks: false,
smartLists: true,
smartypants: false,
highlight: function (code, lang) {
const hljs = require('highlight.js');
const language = hljs.getLanguage(lang) ? lang : 'plaintext';
return hljs.highlight(code, { language }).value;
},
});

const html = marked('# hello')`

![image](https://user-images.githubusercontent.com/73927445/127736050-647746e1-0cac-4c2d-90b8-89cb563fcff1.png)

Expected behavior
All Markdown elements should be rendered.

**Comment by calculuschild** [comment]
Can you clarify which elements are not rendering? From your screenshot it looks like your `# header` is indeed correctly rendering as an `<h1>` tag.

**Comment by Ha0ran2001** [comment]
> Can you clarify which elements are not rendering? From your screenshot it looks like your `# hello` is indeed correctly rendering as an `<h1>` tag.

Yeah, it is rendered as `<h1>` tag in Elements we can see. But in the innerHtml it is not rendered.

**Comment by UziTech** [comment]
`hello`is rendered in the innerHTML. What do you think is supposed to be rendered?

**Comment by Ha0ran2001** [comment]
> `hello`is rendered in the innerHTML. What do you think is supposed to be rendered?
I changed the code to this：
<div
            dangerouslySetInnerHTML={{ __html: marked('# hello\n' + '## hello') }}
          >

          </div>
and it rendered as
![image](https://user-images.githubusercontent.com/73927445/127847698-ca57a664-0303-450a-a7d3-e32c0fe168fe.png)
They looks the same and none of them have the effect of a title.

**Comment by UziTech** [comment]
Marked does not provide the css to make elements look a certain way. You have to create that yourself.

**Comment by Ha0ran2001** [comment]
> Marked does not provide the css to make elements look a certain way. You have to create that yourself.
@UziTech Thanks，I known that is my personal problem.
