### ISSUE TITLE
italic html incorrectly rendered?

### ISSUE THREAD

**Issue by fyears** [markedjs/marked#216]
I don't know whether it should be considered a bug or a feature.

I've enabled gfm while using the `marked` function.

When the markdown text is:

```
abc_def ghi

abc_def ghi_
```

the html text rendered by marked is

```
<p>abc_def ghi</p><p>abc<em>def ghi</em></p>
```

But, I think the "correct" html should be:

```
<p>abc_def ghi</p><p>abc_def ghi_</p>
```

It's a conflict caused by gfm and original markdown syntax. Maybe you guys (developers of marked) should consider which result is "more correct". :-)

**Comment by joshbruce** [comment]
Closing as stale. SEe #956

**Comment by Feder1co5oave** [comment]
This is still all too real, unfortunately:

~~~
bin/marked 
abc_def ghi

abc_def ghi_
^D

<p>abc_def ghi</p>
<p>abc<em>def ghi</em></p>

**Comment by joshbruce** [comment]
Closing as covered by CommonMark compliance. See #1106 and #1216.
