### ISSUE TITLE
Custom Render as json

### ISSUE THREAD

**Issue by simonh1000** [markedjs/marked#2164]
**Describe the feature**
I'd like to use a custom renderer to return json, e.g.

```
const renderer = {
    heading(text, level) {
        return {"_rmx_type": "dom_text", "props": {"value": text}}
    }
};
marked.use({ renderer });
```

**Why is this feature necessary?**
I have a custom html renderer that expects json data, but I want to be able to create the custom data directly from markdown

**Describe alternatives you've considered**
It looks like I could do it by returning a json string, and then passing that to `JSON.parse` but that would be inefficient

https://github.com/MoOx/markdown-to-json provides that functionality but is small project

**Comment by UziTech** [comment]
You can get lexer tokens with `marked.lexer(markdown, options)`

Otherwise you could use a custom renderer to add tokens to an object.

Something like:

```js
const tokens = []
const renderer = {
    heading(text, level) {
				tokens.push({"_rmx_type": "dom_text", "props": {"value": text}});
				return "";
    }
};
marked.use({ renderer });
```

**Comment by simonh1000** [comment]
Thanks for the suggestions :-)
