### ISSUE TITLE
custom extension example from docs does not work (for me)

### ISSUE THREAD

**Issue by Steve-Mcl** [markedjs/marked#2172]
**Marked version: 2.1.3**

**Describe the bug**
I tried adapting the example extension  (that you provide in your docs) in my project and failed. So, using JSFiddle and a CDN of V2.1.3, I pasted a direct copy of the example extension from your docs (https://marked.js.org/using_pro#extensions) but it seems not to work either.

I have tried may things but cannot for the life of me get this going.

My sincere apologies up front if this is my error - but could use a leg up please?

Thanks, Steve.

<br>

**To Reproduce**
Steps to reproduce the behavior:  Demo here: http://jsfiddle.net/r6e25pdj/16/

<br>

**Expected behavior**
To work as per the example.

**Comment by UziTech** [comment]
The docs are actually for v3 which hasn't been released yet (but should be soon). The line `this.lexer.inline(text, tokens)` should be `const tokens = this.inlineTokens(text)` for v2.

**Comment by calculuschild** [comment]
Are doc changes for unreleased versions being sent to the live docs? Is that something we can change so they only update with official version releases?

**Comment by UziTech** [comment]
The docs are live from master branch. Usually they get released at the same time as an update but this is an unusual situation since we are waiting to release the next major version.

**Comment by Steve-Mcl** [comment]
Hi @UziTech thanks for the info. Based on what you said, I found the solution under the 2.1.3 tag

For anyone else reading - the demo code for V2.1.x is here: https://github.com/markedjs/marked/blob/v2.1.3/docs/USING_PRO.md 

Keep up the amazing work - very much appreciated.

---

PS, is it feasible to provide a dropdown list of versioned docs? similar to how node-js does documentation ...

![image](https://user-images.githubusercontent.com/44235289/129469759-d7b71fc2-770d-46aa-aecb-e7b95af0ccf8.png)

**Comment by UziTech** [comment]
v3 has been released so the docs should be correct again. If you would like to create a PR with versioned docs we would gladly review it. :+1:
