### ISSUE TITLE
Extra lines at start makes the text pre coded...

### ISSUE THREAD

**Issue by sayantan300** [markedjs/marked#2179]
To reproduce, here's the online url: [link](https://marked.js.org/demo/?outputType=html&text=%20%20%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20%20%20Hello%0A%20%20%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20%20%20How%20is%20this%20happening&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=0.6.1)

(Do note I have extra blanks at start)

**Comment by calculuschild** [comment]
This is correct behavior, part of the Commonmark Specification

You can see here for more details
https://spec.commonmark.org/0.30/#indented-code-blocks

**Comment by sayantan300** [comment]
Oh ok, GitHub even follows this
