### ISSUE TITLE
Single Whitespace in line after table definition leads to error

### ISSUE THREAD

**Issue by kozi** [markedjs/marked#2187]
**Marked version: 3.0.1**

**Describe the bug**
A line with a single whitespace after a table definition leads to the following error!

**To Reproduce**

* [Demo](https://bit.ly/3mugXoi)

```bash
TypeError: can't access property "trim", cells[(cells.length - 1)] is undefined
```

There is a single whitespace in the line after the table.

```markdown
# Whitespace breaks table generation

| A    | B    |
|------|------|
| A1   | B1   |
| A2   | B2   |
 

## B

abc
```

**Expected behavior**

Ignore the whitespace and render the markdown content.

**Comment by calculuschild** [comment]
@UziTech @styfle pretty sure the error is in line 165 or `src/helpers.js` we need to check that `cells.length` has any cells left after 164 has popped off the last cell.

Can't make a PR since I'm away from my computer but should be a quick fix if one of you wants to make it.

**Comment by UziTech** [comment]
@calculuschild I went the direction of changing the table regex instead to stop at lines with only whitespace. Changing splitcells would have required a lot of logic to set the correct raw value for the token but the regex change was only a few characters.
