### ISSUE TITLE
Add Dompurify feature as built-in

### ISSUE THREAD

**Issue by AhmedElTabarani** [markedjs/marked#2207]
When I use this library, I used extra package with it like `dompurify`
like this
```js
const marked = require('marked');
const createDomPurify = require('dompurify');
const { JSDOM } = require('jsdom');
const dompurify = createDomPurify(new JSDOM().window);
const fs = require('fs');

module.exports = (path) => {
  const data = fs.readFileSync(path, 'utf-8');

  return dompurify.sanitize(marked(data));
};
```

## if you don't know what is Dompurify, 
```DOMPurify sanitizes HTML and prevents XSS attacks. You can feed DOMPurify with string full of dirty HTML and it will return a string (unless configured otherwise) with clean HTML. DOMPurify will strip out everything that contains dangerous HTML and thereby prevent XSS attacks and other nastiness. It's also damn bloody fast. We use the technologies the browser provides and turn them into an XSS filter. The faster your browser, the faster DOMPurify will be.```

So can we have `dompurify` as the built-in in `marked` ? Or as a function ? 
Or is `marked` doing `dompurify` already, and I don't know ? 😅

**Comment by UziTech** [comment]
Marked doesn't have any dependencies it would not be helpful to add it to this library because someone might want to use a different library to sanitize HTML and it would not be beneficial to force people to use dompurify
