### ISSUE TITLE
Smartypants outputs wrong quote after HTML element

### ISSUE THREAD

**Issue by crystalfp** [markedjs/marked#2219]
**Marked version:**
3.0.4

**Describe the bug**
quotes (single and double) that appears after a HTML tag are rendered the wrong direction.

**To Reproduce**
Look at the result of:
```
marked(`<span style="background-color: #8dd3c7">nell</span>'ambito`, {smartypants: true})
```
The quote before `ambito` is in the wrong direction.
Removing the span (I don't know other ways to color highlight a word in CommonMark) gives the quote the right direction.
The problem is similar to #1606.

**Expected behavior**
Emphasis or html element should be ignored in determining the quote direction.

**Comment by crystalfp** [comment]
Just FYI. I fixed the problem adding the following on the marked output:
```
		.replaceAll("span>‘", "span>’")
		.replaceAll("span>”", "span>“")
```

**Comment by UziTech** [comment]
It actually looks like this is expected

![image](https://user-images.githubusercontent.com/97994/135784509-290457ce-2abf-4032-b5aa-28132a7dbbc9.png)

https://daringfireball.net/projects/markdown/dingus

**Comment by crystalfp** [comment]
In Word and in books it is:
![image](https://user-images.githubusercontent.com/865866/135786643-d9f00e19-b9c0-4a0f-ad0d-9c3dbf2200ec.png)
So I respectfully dissent that dingus is correct.

**Comment by UziTech** [comment]
Word and books do not have a span tag between the words.

I think this is one of those edge cases where using a `’` as apposed to a `'` is the correct way to make it work.

We try to follow the spec so changing it to not match the dingus would probably break more peoples code than it would help.

**Comment by crystalfp** [comment]
OK, I understand. In any case this is a very specific case for one application in which I need to highlight certain words in different colors, so I can live with two replaceAll() calls after marked().

**Comment by crystalfp** [comment]
FYI, this is my call:
```
const out = markdown
		.replaceAll(" ->", " →");

const html = marked(out, {smartypants: true, headerIds: false})
		.replaceAll(/span>‘([ !,.:;<?])/g, "span>’$1")
		.replaceAll(/span>“([ !,.:;<?])/g, "span>”$1");
```
