### ISSUE TITLE
marked__WEBPACK_IMPORTED_MODULE_4___default(...) is not a function

### ISSUE THREAD

**Issue by donthijackthegit** [markedjs/marked#2229]
**Marked version:**
3.0.6
**Describe the bug**
I tried to use this library on vuejs 2, it shows ```marked__WEBPACK_IMPORTED_MODULE_4___default(...) is not a function``` when calling marked(...).

I rollback to 3.0.5 it worked flawlessly.

**To Reproduce**

1. Install marked `npm install --save marked@3.0.6` with the version you are using
2. Call marked(...) inside vue component computed block
3. Shows "marked__WEBPACK_IMPORTED_MODULE_4___default(...) is not a function"

**Expected behavior**
Not showing error and can parse markdown text successfully.

**Comment by osvaldasvalutis** [comment]
Same in `react-create-app`.

**Comment by RomanHotsiy** [comment]
Caused by https://github.com/markedjs/marked/issues/2228

**Comment by sankhaKarunasekara** [comment]
This issue is still coming up in 4.0.0

**Comment by UziTech** [comment]
@sankhaKarunasekara v4 removed the default import. You will have to change the import call to `import { marked } from 'marked'`

**Comment by safwendr** [comment]
> @sankhaKarunasekara v4 removed the default import. You will have to change the import call to `import { marked } from 'marked'`

Thanks, that solved the problem.

**Comment by Noibisjunior** [comment]
wow, it solved the problem. The good use of the import make the markdown file passed successfully.
Thanks man

**Comment by neogmanish99** [comment]
thanks , it solved

**Comment by emilyjstroud** [comment]
This helped me too! Always with the curly brackets..
