### ISSUE TITLE
Export `use` so that it's easier to import

### ISSUE THREAD

**Issue by dtzxporter** [markedjs/marked#2232]
**Marked version:**
3.x.x

**Describe the bug**

Right now, `import {use} from "markedjs"` does not work, this worked in 2.x.x.

**To Reproduce**

Install & import it.
The `DefinitelyTyped` definitions also mark this incorrectly as being supported still.

A workaround is importing one of the structures that `use` is defined on like `parse` and calling `parse.use()`. This seems convoluted.

**Expected behavior**

`use` should be exported so we can import it directly.

**Comment by simonhaenisch** [comment]
Looks like that's merged, so this can be closed?

**Comment by UziTech** [comment]
Yes, thanks!
