### ISSUE TITLE
custom extension example for simple inline tag

### ISSUE THREAD

**Issue by oskude** [markedjs/marked#2234]
**Describe the feature**
i would like to add an inline extension (without any further-nested inline tokens) to convert:

```
foo {bar} zap
```

to:

```
<p>foo <kbd>bar</kbd> zap</p>
```

and i thought this would do it:

```javascript
const Md = require("marked")

const kbd = {
	name: "kbd",
	level: "inline",
	start(src) {
		return src.match(/{/)?.index
	},
	tokenizer(src, tokens) {
		const rule = /{([^}]+)(?:})/
		const match = rule.exec(src)
		if (match) {
			console.debug("MATCH0:", match[0])
			console.debug("MATCH1:", match[1])
			return {
				type: "kbd",
				raw: match[0],
				kbd: match[1]
			}
		}
	},
	renderer(token) {
		return `<kbd>${token.kbd}</kbd>`
	}
}

Md.use({extensions:[kbd]})

console.log("OUTPUT:", Md("foo {bar} zap"))
```

but it outputs:

```
MATCH0: {bar}
MATCH1: bar
OUTPUT: <p><kbd>bar</kbd>bar} zap</p>
```

and i can't figure out why it's not working...

- why is `foo` gone from OUTPUT?
- why is MATCH0 not completely removed from OUTPUT?

**Why is this feature necessary?**
at least i could not figure out from the `dl` example (or descriptions of the functions) at https://marked.js.org/using_pro on how to implement this. And once this example works, another example on how to add support for further-nested inline tokens would nicely show how this thing works, i guess...

**Comment by UziTech** [comment]
```diff
- const rule = /{([^}]+)(?:})/
+ const rule = /^{([^}]+)(?:})/
```
