### ISSUE TITLE
Custom Extensions in Documentation aren't working

### ISSUE THREAD

**Issue by WhimsicalWhale** [markedjs/marked#2250]
**Marked version:**
3.0.7

**Describe the bug**
I'm new at using marked, and was attempting to modify the demo to use a custom extension. I figured I'd just use the ones in the example first to make sure I was calling everything in the appropriate location before trying to write my own extension. I was loading marked via CDN, just like in the example, then immediately adding the custom extensions (literally copied and pasted code) with the "use" method. When the output didn't appear as expected, I examined the marked object with the browser's debugger and saw that while both "descriptionList" and "description" were added in the object (marked object -> default -> extensions -> found objects here), they weren't being used to parse the output.

**To Reproduce**
Add the custom extensions provided as a documentation example in the markdown demo page (work.js, right after line 119, assuming you don't make any other changes to worker.js)

**Expected behavior**
I would expect the output on the html tab of the demo to match what the documentation says the expected output should be, in this case
"A Description List:
:   Topic 1   :  Description 1
: **Topic 2** : *Description 2*"
should output
"<p>A Description List:</p>
<dl>
<dt>Topic 1</dt><dd>Description 1</dd>
<dt><strong>Topic 2 walked</strong></dt><dd><em>Description 2</em></dd>
</dl>"

**Comment by WhimsicalWhale** [comment]
I added it in the worker.js file. The two extensions themselves are defined at the bottom of worker.js, I just copied and pasted the javascript from the docs. I add them with the "use" method right after marked is loaded, line 120 of marked.js

**Comment by UziTech** [comment]
It doesn't seem to work the way you include it in the demo. try it in something like [runkit](https://npm.runkit.com/marked)

**Comment by UziTech** [comment]
It works in this [demo](https://runkit.com/embed/si8qejkbeyry)
