### ISSUE TITLE
Add support for NextJS Image

### ISSUE THREAD

**Issue by junerockwell** [markedjs/marked#2252]
**Describe the feature**
Please add the support for NextJS Image https://nextjs.org/docs/api-reference/next/image

**Why is this feature necessary?**
`marked` is easily integrated into NextJS when rendering Markdown files. Since anyone can add images to markdown files, it would very convenient for developers to use the `next/image` because it already has lazy loading and many image optimization. And by supporting `next/image`, we'd be following compatible practices with NextJS standards.

This should be optional, of course. But just like `marked` supports `prismjs` (https://prismjs.com/), we should be able to optionally use `next/image` as well.

Suggested example using NextJS Image:
```
import marked from "marked";
import Image from 'next/image';
...
const renderer = new marked.Renderer();

renderer.image = function(href, title, text) {
    return `<Image src="/images/${href}" alt="${text}" layout="fill" />`
};

marked.setOptions({
  renderer,
});
```
But any other way to optionally use `next/image` would be great!

**Comment by sibiraj-s** [comment]
I am not familiar with nextjs. May be [marked-react](https://www.npmjs.com/package/marked-react)?

```jsx
import Markdown from "marked-react";
import Image from 'next/image';

const renderer = {
  image: function(href, title, text)  => {
    return <Image src="/images/${href}" alt="${text}" layout="fill" />
  },
};

<Markdown value={markdown} renderer={renderer} />
```

**Comment by UziTech** [comment]
That is awesome @sibiraj-s I didn't know about that package.

I am closing this as using marked-react seems to be the correct solution.
