### ISSUE TITLE
Invisible/unprintable character appended to result

### ISSUE THREAD

**Issue by paddotk** [markedjs/marked#2266]
**Marked version:**
3.0.8

**Describe the bug**
*Note: Not tried with 4.0.0 since I'm running into another blocking [issue](https://github.com/markedjs/marked/issues/2265) there, but since I can't find any issues or changelogs addressing this bug, I assume the issue hasn't been resolved yet.*

When parsing a string with marked(), the returned string has an invisible character at the end. This makes some of my unit tests fail unless I .trim() it first.

**To Reproduce**
Use marked() on any string.
You can see there is an invisible character by checking the length of the output string:
``` javascript
const str = 'Hello there';
console.log(utils.parseMarkdown(str).length); // 19
console.log(utils.parseMarkdown(str).trim().length); // 18
console.log(utils.parseMarkdown(str)[18]); // 
```

**Comment by UziTech** [comment]
yes marked renderers add a newline character (`\n`) at the end of the markdown. That is by design.
