### ISSUE TITLE
More than one extension causing problems

### ISSUE THREAD

**Issue by rachana15** [markedjs/marked#2267]
1. I have more than one extension, say - ext1, ext2, ext3. I am calling them separately at different places in same file like 
`marked.use({renderer})`
`marked.use({extensions: [ext1]})`
`marked.use({extensions: [ext2]})`
`marked.use({extensions: [ext2]})`

But my data goes to all the extensions and it gets messed up. Is there a way to just use only renderer or extension at a point of time?

**Comment by UziTech** [comment]
similar to #907 

Marked makes the defaults global so you would have to reset the default options by using

```js
marked.setOptions(marked.getDefaults());
```
