### ISSUE TITLE
Typescript and Jest Compatibility with v4.0.0

### ISSUE THREAD

**Issue by webstech** [markedjs/marked#2274]
**Marked and @types version:**
4.0.0

Seeking advice on how to get past an error with the new version on a typescript
repo using jest for testing.

Sample repo:
https://github.com/webstech/markedjest

## Expectation
Jest runs.
## Result

```
    Jest encountered an unexpected token
...
    Details:
  ...\markedjest\node_modules\marked\lib\marked.esm.js:2667
    export { Lexer, Parser, Renderer, Slugger, TextRenderer, Tokenizer, defaults, getDefaults, lexer, marked, options, parse, parseInline, parser, setOptions, use, walkTokens };
    ^^^^^^

    SyntaxError: Unexpected token 'export'
```
## What was attempted

Tried jest config options:

- transformIgnorePatterns
-     "transform": {
      "\\.esm.js$": "<rootDir>/jest/fauxTransform.js",

My searches did not find a resolution.  Sorry if I missed something obvious.  If there is an answer it may be useful to have it with this repo.

thanks for any suggestions.

**Comment by UziTech** [comment]
If your app is not an ES Module (i.e. you are using `require('marked')`) you will need to require the non-es module form of marked by using `require('marked/lib/marked.cjs')` in your tests.

I'm not sure if this is a jest specific bug or why exactly it is happening because `require('marked')` works in the code but not in the tests.

**Comment by webstech** [comment]
Thanks for looking at this.

After a bit of tracing in jest and playing with the marked `package.json`, I found that setting `"main": "./lib/marked.cjs",` works with jest.  Looking at the node doc it suggests `main` should be pointing at the common JS entry.  Was there a reason it was changed in the ESM conversion?  `npm test` does not fail with `main` pointing to the `.cjs` file.  I can open a PR to change this if you think it is okay.

btw, some of the tests fail on windows due to `\r\n` vs `\n` in the expectations.

**Comment by webstech** [comment]
Ran a test with the modified `package.json` in a repo with modules.  marked loaded okay running from node and running with jest.

For reference, to enable modules (ie import) in jest, the babel config must specify:
```
"presets": ["@babel/preset-env"]
```
This is not installed as part of jest so it will need to be done separately.

**Comment by UziTech** [comment]
If you want to open a PR you can
