### ISSUE TITLE
Part of token output in the rendered html with custom extension

### ISSUE THREAD

**Issue by krezovic** [markedjs/marked#2275]
**Marked version:**

4.0.0

**Describe the bug**

I want to write a custom extension that supports embedding video into output HTML. It's as simple as writing `::video[**embed-url**]`. But something is wrong and I get unwanted result.

**To Reproduce**

. The extension code is as follows, based as much as possible from https://marked.js.org/using_pro#extensions

```
const VIDEO_TAG_REGEXP = new RegExp(/^::video\[(.*)\]$/);

const videoExtension = {
  name: 'videoExt',
  level: 'inline',
  start: (src: string) => {
    const m = src.match(/^::video/) as RegExpMatchArray;

    if (m) {
      return m.index;
    }
  },
  tokenizer: function(this: TokenizerThis, src: string) {
    const match = VIDEO_TAG_REGEXP.exec(src);

    if (match) {
      return {
        type: 'videoExt',
        raw: match[1],
        text: match[1].trim(),
        tokens: []
      };
    }
  },
  renderer: function(this: RendererThis, token: Tokens.Generic) {
    // @ts-ignore (until typings are up to date)
    const url = token.text;

    return `
      <iframe width="480" height="360" src="${url}"
              title="Video Playback" frameborder="0"
              allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
              allowfullscreen></iframe>
    `;
  }
};

  marked.use({ gfm: false, extensions: [videoExtension] });

  console.log(marked.parse('::video[https://www.youtube.com/embed/Sh5S3OxiE-s]'));
```

**Expected behavior**

I expect to only get the iframe block, but for some reason I get additional text that is part of the token itself.

![image](https://user-images.githubusercontent.com/19533104/140903823-41938f40-12bc-4f71-92fe-fcc1cf68fffd.png)

As you can see, it writes `S3OxiE-s]` which is the second half of the `::video` tag definition.

Please let me know if I can provide more info.

**Comment by UziTech** [comment]
`raw` is essentially the string that you want to remove from the markdown before moving to the next token

you have it set to `match[1]` so it will only be the url (`https://www.youtube.com/embed/Sh5S3OxiE-s`) but you actually want it to be `match[0]` (`::video[https://www.youtube.com/embed/Sh5S3OxiE-s]`) so marked knows to remove the whole line before moving to the next token.

```js
const VIDEO_TAG_REGEXP = new RegExp(/^::video\[(.*)\]$/);

const videoExtension = {
  name: 'videoExt',
  level: 'inline',
  start: (src: string) => {
    const m = src.match(/^::video/) as RegExpMatchArray;

    if (m) {
      return m.index;
    }
  },
  tokenizer: function(this: TokenizerThis, src: string) {
    const match = VIDEO_TAG_REGEXP.exec(src);

    if (match) {
      return {
        type: 'videoExt',
        raw: match[0],
        text: match[1].trim(),
        tokens: []
      };
    }
  },
  renderer: function(this: RendererThis, token: Tokens.Generic) {
    // @ts-ignore (until typings are up to date)
    const url = token.text;

    return `
      <iframe width="480" height="360" src="${url}"
              title="Video Playback" frameborder="0"
              allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
              allowfullscreen></iframe>
    `;
  }
};

  marked.use({ gfm: false, extensions: [videoExtension] });

  console.log(marked.parse('::video[https://www.youtube.com/embed/Sh5S3OxiE-s]'));
```

**Comment by krezovic** [comment]
Hi @UziTech. Thanks for the prompt reply. Your example works for me as I'd expect it. I must have missed the part where the "raw" is the string to remove from markdown.
