### ISSUE TITLE
Can Marked keep original input text with markdown marks?

### ISSUE THREAD

**Issue by Bohooslav** [markedjs/marked#2279]
**What pain point are you perceiving?.**
I want to make markdown notepad where you write down plain text in markdown format and it is instantly formatted right in the input.
Example:
Input: `This is *italic* text`
Output: `<p>This is *<i>italic</i>* text</p>`

I want something like in Discord when you type something, and it instantly formatted right in the input.

**Describe the solution you'd like**
I just want the original text with markdown marks to be kept, being wrapped in relevant HTML tags.

**Comment by UziTech** [comment]
marked is for converting markdown to html you will have to do the rest yourself.
