### ISSUE TITLE
4.0.2 broke current functionality

### ISSUE THREAD

**Issue by blackfalcon** [markedjs/marked#2282]
**Marked version:** 4.0.2

**Describe the bug**
With the release of `v4.0.2` I now get this error

```
Uncaught ReferenceError: exports is not defined
    at unpkg.com/marked@4.0.2/marked.min.js:6
```

With `v4.0.1` the same code has no error. 

**To Reproduce**

```js
      fetch('/demo/demo.md')
        .then((response) => response.text())
        .then((text) => {
          const rawHtml = marked.parse(text);
          document.querySelector('main').innerHTML = rawHtml;
          Prism.highlightAll();
        });
```

**Expected behavior**

A patch update not to break the previous version.

**Comment by fu-sen** [comment]
I also had a project that worked with `v4.0.0-4.0.1` but now` v4.0.2` doesn't work.
I once had to revert to the Marked v4.0.1 source.
https://github.com/fu-sen/strapdown
https://github.com/fu-sen/strapdown.js

**Comment by fu-sen** [comment]
I was able to confirm that `v4.0.3` works. I will reflect that in the project.
