### ISSUE TITLE
markd.min.js replacing native window.escape

### ISSUE THREAD

**Issue by ingydotnet** [markedjs/marked#2286]
**Marked version:**

**Describe the bug**

Loading `<script src="https://cdn.jsdelivr.net/npm/marked/marked.min.js"></script>` replaces `window.escape` with another function.

This started happening today, and there was a release 13 hours ago.

**Comment by ingydotnet** [comment]
Using https://unpkg.com/marked@4.0.0/marked.min.js as a workaround.

**Comment by UziTech** [comment]
this was fixed in v4.0.3
