### ISSUE TITLE
The problem with parsing newline characters

### ISSUE THREAD

**Issue by lete114** [markedjs/marked#2296]
input: 
![image](https://user-images.githubusercontent.com/48512251/142817278-0a7f4a99-5632-45c1-93c6-8513cf185fd8.png)

actual output: 
![image](https://user-images.githubusercontent.com/48512251/142817311-b329e7af-adae-4547-b36b-182618ed8e4f.png)

I hope output: 
![image](https://user-images.githubusercontent.com/48512251/142817340-f6c48633-b1eb-43a0-b018-23d1418f9ccd.png)
> I could have done that with an extra newline character, but I don't want to
![image](https://user-images.githubusercontent.com/48512251/142817841-f1eee694-adc4-471c-9b18-5db64619c5b5.png)

https://marked.js.org/demo/?text=Marked%0Anewline

**Comment by UziTech** [comment]
This is according to the common mark and GFM spec. You can set the `breaks` option to true to allow single line breaks as long as `gfm` is true.

[demo](https://marked.js.org/demo/?text=Marked%0Anewline&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20true%2C%0A%20%22extensions%22%3A%20null%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master)
