### ISSUE TITLE
Sub-list items which are multiples of 3 are wrapped with pre/code blocks in version 4.0.6

### ISSUE THREAD

**Issue by udara28** [markedjs/marked#2314]
**Marked version:**
4.0.6

**Describe the bug**
Every sublist item which is a multiple of 3 is wrapped with a ```<pre><code></code></pre>``` block. This issue is present in the 4.0.6(latest) version but not in 4.0.5.

**To Reproduce**
A hosted test case to reproduce this issue can be found in [this CodePen Demo](https://codepen.io/udara28/pen/qBPNbMb)

Example markdown text to reproduce the bug:
```
1. list item one
    1. sublist item one
    2. sublist item two

2. list item two
    1. sublist item one
    2. sublist item two

3. list item three
    1. sublist item one
    2. sublist item two

4. list item four
    1. sublist item one
    2. sublist item two
```

**Expected behavior**
```<pre><code></code></pre>``` should not appear in the sub list items.

**Comment by UziTech** [comment]
confirmed [demo](https://marked.js.org/demo/?text=1.%20list%20item%20one%0A%20%20%20%201.%20sublist%20item%20one%0A%20%20%20%202.%20sublist%20item%20two%0A%0A2.%20list%20item%20two%0A%20%20%20%201.%20sublist%20item%20one%0A%20%20%20%202.%20sublist%20item%20two%0A%0A3.%20list%20item%20three%0A%20%20%20%201.%20sublist%20item%20one%0A%20%20%20%202.%20sublist%20item%20two%0A%0A4.%20list%20item%20four%0A%20%20%20%201.%20sublist%20item%20one%0A%20%20%20%202.%20sublist%20item%20two&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22extensions%22%3A%20null%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master)

**Comment by calculuschild** [comment]
I think I know where the error is.
