### ISSUE TITLE
Add a way to get the plain text from the input will all of the markdown characters stripped out

### ISSUE THREAD

**Issue by edazpotato** [markedjs/marked#2320]
**Describe the feature**
Add a way to get the plain text from the input will all of the markdown characters stripped out

**Why is this feature necessary?**
For blog post previews in the description meta tag where neither markdown or html are supported

**Describe alternatives you've considered**
Using a regex. This works but it's difficult to cover all edge cases and given that marked already parses everything it should be relatively simple to add an option to output plain text

**Comment by UziTech** [comment]
You can create a renderer that does that. The default marked renderer outputs html but it shouldn't be difficult to create a renderer that only outputs the text.

**Comment by edazpotato** [comment]
Thanks for the tip! I made a package that implements the behaviour I was looking for.
Here's the link for anyone who finds this thread in the future looking for something like this: https://github.com/edazpotato/marked-render-to-text

**Comment by sergei-dyshel** [comment]
There's also [marked-extensions/packages/plaintify at main · bent10/marked-extensions](https://github.com/bent10/marked-extensions/tree/main/packages/plaintify)
