### ISSUE TITLE
Triple backticks are considered a codespan if on the same line, perhaps make this configurable

### ISSUE THREAD

**Issue by dtzxporter** [markedjs/marked#2326]
Some markdown implementations allow triple backticks on the same line to render as a full code block. It would be nice to make this configurable.

Currently:
```
```test``` -> `test`
```

**Comment by UziTech** [comment]
We follow Common Mark and GFM. Those implementations don't render full blocks so I don't think we will implement that. If you wanted to create an extension you can.
