### ISSUE TITLE
Unordered list not supported

### ISSUE THREAD

**Issue by winedk** [markedjs/marked#2327]
**Marked version:*4.0.7*

**Describe the bug*Unordered list not supported*
![image](https://user-images.githubusercontent.com/52094020/145930740-53175f97-0e4e-427a-bb5d-c7c7f539dbdc.png)
![image](https://user-images.githubusercontent.com/52094020/145930783-6eaefb81-e263-4c22-8c7b-9c89bce9f6cb.png)

What configuration is required

**Comment by UziTech** [comment]
no configuration required. [demo](https://marked.js.org/demo/?text=-%20item1%0A-%20item2%0A-%20item3&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22extensions%22%3A%20null%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master)

**Comment by winedk** [comment]
康康：您好，您发给我的信件已经收到。谢谢~

**Comment by winedk** [comment]
康康：您好，您发给我的信件已经收到。谢谢~
