### ISSUE TITLE
Underlining text not supported

### ISSUE THREAD

**Issue by Saswat689** [markedjs/marked#2328]
## I want to underline text with marked but I can't do it.
 
I think its _better_ to use underline tags in some places rather than italics or bold texts. It grabs the attention of the user (slight).

I **did not found** this anywhere on the docs or the demo. Please tell me if I can achieve this using marked.

**Comment by UziTech** [comment]
There is no underlining support in the [Common Mark spec](https://spec.commonmark.org/0.30/). You can create an [extension](https://marked.js.org/using_pro#extensions) if you would like to add it to marked.

**Comment by Saswat689** [comment]
@UziTech Got it. I will try to use them now.

**Comment by Saswat689** [comment]
@UziTech  I am not sure how to do this correctly. I want to generate an **underline** tag when someone types _(:)_ around the text like _: this is underlined :_ Here's what I tried:

**Comment by Saswat689** [comment]
@UziTech I am not sure how to do this correctly. I want to generate an underline tag when someone types (:) around the text like : this is underlined : Here's what I tried: 


const underline = {
  name: 'underline',
  level: 'inline',                                     // Is this a block-level or inline-level tokenizer?
  start(src) { return src.match(/:[^:\n]/)?.index; }, // Hint to Marked.js to stop and check for a match
  tokenizer(src, tokens) {
    const rule = /^(?::[^:\n]+:[^:\n]*(?:\n|$))+/;    // Regex for the complete token
    const match = rule.exec(src);
    if (match) {
      const token = {                                 // Token to generate
        type: 'underline',                      // Should match "name" above
        raw: match[0],                                // Text to consume from the source
        text: match[0].trim(),                        // Additional custom properties
        tokens: []                                    // Array where child inline tokens will be generated
      };
      this.lexer.inline(token.text, token.tokens);    // Queue this data to be processed for inline tokens
      return token;
    }
  },
  renderer(token) {
    return `<ul>${this.parser.parseInline(token.tokens)}\n</ul>`; // parseInline to turn child tokens into HTML
  }
};

marked.use({ extensions: [underline] });`

Didn't work. (Again I can be stupid here).

How can I achieve that?

**Comment by UziTech** [comment]
`<ul>` is an unordered list not underline, I think you want `<u>` and it looks like your regex rule requires two colons at the beginning.
