### ISSUE TITLE
Readme: List of tools for simple-page creation.

### ISSUE THREAD

**Issue by cameronelliott** [markedjs/marked#2337]
**What pain point are you perceiving?.**
I want a comprehensive list of tools that build on Markedjs for creating webpages.

I have found the following:

http://strapdownjs.com/
https://zerodevx.github.io/zero-md/

**Describe the solution you'd like**
If anyone knows of other tools like strapdownjs, or zero-md, please add a comment.

Maybe such tools should be added to the Readme?

**Comment by 201B153** [comment]
<b>can I take it?</b>

And please tell me, where on README.md or docs it has to be added??

**Comment by UziTech** [comment]
Probably best to just add it to the front page of the docs (https://github.com/markedjs/marked/blob/master/docs/INDEX.md)

**Comment by 201B153** [comment]
ok on it!!

**Comment by 201B153** [comment]
I have just added what I can find on the web with proper functionality in single-page creation. Please tell me what else could be added.
