### ISSUE TITLE
Alternative to unicode property escapes regular expression?

### ISSUE THREAD

**Issue by rfgamaral** [markedjs/marked#2339]
Hi there 👋

We started to use `marked` in one of our products, and one of our users mentioned that our product stopped working for them very recently. They are on an older Firefox version (with some enterprise policy in place preventing them from upgrading) which does not have support for [RegExp: Unicode property escapes](https://caniuse.com/mdn-javascript_builtins_regexp_property_escapes), which in turn is being used here:

https://github.com/markedjs/marked/blob/939689641817659998f63ce61ae76f0e57343268/src/Tokenizer.js?rgh-link-date=2021-12-25T18%3A04%3A41Z#L571-L572

I'm not familiar with this RegExp feature, and if there are any viable alternatives to this, so that `marked` could support older browser versions (assuming that you care about supporting browser versions that old). So, I guess my question is, is this something that we could, eventually, expect a fix for, or should we see this as one of those "won't fix" issues?

Have an awesome 2022 everyone 🎉

**Comment by UziTech** [comment]
I don't think we are interested in supporting old versions of browsers. You can extend marked and provide your own `emStrong` tokenizer.

**Comment by rfgamaral** [comment]
Thanks for the suggestion, @UziTech, but I don't think that will work. Replacing the tokenizer does not prevent the original `emStrong` from being bundled, and based on my testing, Firefox breaks just by parsing that RegExp (even if it's never used). In other words, as long as any `.js` file is loaded with that RegExp, Firefox breaks and shows a blank page.

**Comment by rfgamaral** [comment]
FYI, we found a workaround by loading the UMD version instead of the ESM one, which does not include the `\p{...}` syntax:

https://github.com/markedjs/marked/blob/939689641817659998f63ce61ae76f0e57343268/lib/marked.umd.js#L967

**Comment by tylfin** [comment]
For folks who don't want to go the umd route, we had a similar issue and ensured backwards compatibility by using babel `preset-env` with webpack (you'll see [here](https://github.com/tc39/proposals/blob/main/finished-proposals.md) that it includes RegExp Unicode Property Escapes).

Our webpack configuration looks like:

```
...
      {
        test: /\.js$/,
        loader: 'babel-loader',
        include: [
          resolve('src'),
          resolve('test'),
          resolve('node_modules/marked'),
        ],
        options: {
          presets: ['@babel/preset-env']
        }
...
```

Confirmed working with older versions of Firefox via WebDriver/Selenium tests but YMMV
