### ISSUE TITLE
Add an option to produce valid XHTML

### ISSUE THREAD

**Issue by lpinca** [markedjs/marked#234]
As discussed on IRC i would like to have an option to produce XHTML output for tags with empty elements (e.g. `<br/>`).
This is the default behaviour of `Markdown.pl`.
By default marked will render to modern HTML and will use the empty element syntax only when the option is `true` (`xhtml: true`).
If i'm not mistaken there are only 3 tags involved (`<br>`, `<hr>` and `<img>`).
This feature will allow me to add marked's output in a xml document which will be invalid otherwise.
Unfortunately CDATA does not work in my case, but luckily HTML entities are not a problem.

**Comment by attilavago** [comment]
@chjj , unfortunately you're wrong. XHTML is so not dead. The .epub ebook format uses it extensively.

**Comment by jimmywarting** [comment]
I'm digging into the code an see this xhtml support... is it really needed still doe? feels so old

**Comment by UziTech** [comment]
If someone wants to create an extension that renders xhtml I think we could remove the option.
