### ISSUE TITLE
highlight add parameters

### ISSUE THREAD

**Issue by chenyulun** [markedjs/marked#2342]
**Describe the feature**
A clear and concise description of what you would like.
Add code parsing parameters

\`\`\`html | preview
\<h1\>111111\</h1\>
\`\`\`
</code>
**Why is this feature necessary?**
A clear and concise description of why.

I want to show code or render code

**Describe alternatives you've considered**

```js
marked.setOptions({
  renderer: new marked.Renderer(),
  highlight(code, lang, params) {
console.log(params) // '| preview'
  }
})
```

**Comment by chenyulun** [comment]
Markdown it support
```js
highlight(str, lang, attrs) {
         console.log(
          '🚀 ~ file: vite.config.ts ~ line 20 ~ highlight ~ attrs',
              attrs
    )
}
```

**Comment by chenyulun** [comment]
The following code can be used instead

\`\`\`ts | pre
const a = 1;
\`\`\`
```js
marked.use({
  renderer: {
    code(code, infostring: string, escaped) {
      const [lang, ...attrsString] = infostring.split(' | ')
      console.log('lang', lang) // ts
      console.log(attrsString) // [ 'pre' ]
      const language = hljs.getLanguage(lang) ? lang : 'plaintext'
      return `<pre><code class="hljs language-${lang}">${
        hljs.highlight(code, { language }).value
      }</code></pre>`
    }
  }
})
```

**Comment by panchalkalpesh** [comment]
Syntax Highlighting is a part of Markdown Extended: 
https://www.markdownguide.org/extended-syntax/#syntax-highlighting
