### ISSUE TITLE
Create Changelog

### ISSUE THREAD

**Issue by GeorgeTailor** [markedjs/marked#2357]
**What pain point are you perceiving?.**
I'm not sure what has changed in marked and automatic deps update tells me to update marked, for example from `2.1.3` to `4.0.10`

**Describe the solution you'd like**
Maintaining a changelog with a clear description what has changed.

**Comment by GeorgeTailor** [comment]
Oh, actually, there is a changelog her https://github.com/markedjs/marked/releases

**Comment by coolaj86** [comment]
In particular:

- v2 Breaking changes: https://github.com/markedjs/marked/releases/tag/v2.0.0
- v3 Breaking changes: https://github.com/markedjs/marked/releases/tag/v3.0.0
- v4 Breaking changes: https://github.com/markedjs/marked/releases/tag/v4.0.0

Migrating from v1 to v4:

```diff
- let marked = require('marked');
+ let marked = require('marked').marked;
- marked(mkdnText);
+ marked.parse(mkdnText);
```

The entire codebase was refactored and a few tag parsers have been merged - such as `<em>` and `<strong>` - but it's mostly internal changes that won't affect general parsing with normal markdown files.
