### ISSUE TITLE
Argument of type 'Renderer<never>' is not assignable to parameter of type 'RendererThis'

### ISSUE THREAD

**Issue by jfcere** [markedjs/marked#2358]
**Marked version:**

4.0.10

**Describe the bug**

Using marked 2.0 with TypeScript I was able to override the `link` token with `renderer` and call back the original `link` function on the prototype like this:

```typescript
import { Renderer } from 'marked';

const renderer = new Renderer();

renderer.link = (href: string, title: string, text: string) => {
  return Renderer.prototype.link.call(renderer, normalizeExternalUrl(href), title, text) as string;
};
```

After updating from marked 2.0 to 4.0 I am trying to migrate the code above but I am getting an error telling me that the parameter `this` is not of the expected type `RendererThis`.

Of course, this must be something I am doing wrong but can't get around it...

![image](https://user-images.githubusercontent.com/6987084/149675272-2c8257cc-4db7-447a-b6c1-d1f0b9ac0d34.png)

> Note that the `normalizeExternalUrl` function return type is `string`, it is only to handle relative links

Thanks in advance for your help and the awesome library!

**Comment by jfstephe** [comment]
FYI I cast to 'this as unknown as marked.RendererThis' and for my use case all was well.

**Comment by UziTech** [comment]
marked types are hosted at https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/marked If you have an issue with them it is best to create an issue in that repository.

**Comment by jfcere** [comment]
Hi @UziTech,

Of course, I will create an issue there, I took a shot here because you are the one who created the typings for the v4 😁
I thought you would have a deep understanding of the issue and could probably resolve this in a jiffy!

![image](https://user-images.githubusercontent.com/6987084/150040511-cebe1642-1ca4-406a-bd4f-b27cfe21474d.png)

**Comment by jfcere** [comment]
I opened a discussion on the DefinitelyTyped repository: https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/58301

**Comment by dr-suhadalishaheed** [comment]
Hi

**Comment by dr-suhadalishaheed** [comment]
في أربعاء، ١٩ كانون الثاني، ٢٠٢٢ في ٩:٤٥ ص، كتب Dr.Suhad Ali Shaheed <
***@***.***>:

**Comment by dr-suhadalishaheed** [comment]
#2359 #2360 #2361 #2362 #2363 
be save

**Comment by dyllan-to-you** [comment]
Hi! I'm currently getting the same error while trying to do something similar:
```
class DecoratedRenderer extends marked.Renderer {
  codespan(code: string): string {
      // @ts-expect-error
      return super.codespan(code);
  }
}

const renderer = new DecoratedRenderer();
```

Having a bit of trouble following the proposed solution and the thread in the DefinitelyTyped repo, and was wondering if the proposed solution covers this usecase. 

Thanks in advance!

**Comment by jfcere** [comment]
Hi @dyllan-to-you, 

Yes, the proposed solution in the discussion linked in my previous post does cover your use case.

I've submitted a pull request to adjust the @types/marked typings to fix this issue, now we just need a little wait for it to be reviewed and merged before it is available.

**Comment by jfcere** [comment]
The fix has been deployed as part of @types/marked 4.0.2.

Issue as been resolved, thanks again to @UziTech for his help and this awesome library!
