### ISSUE TITLE
Importing 4.0.10 in TypeScript makes TypeScript wonder its existence and where the files are

### ISSUE THREAD

**Issue by Coreusa** [markedjs/marked#2364]
**Marked version:** 4.0.10

**Describe the bug**
Used 4.0.0 before and that worked. Upgraded to 4.0.10 and ship went sideways - _fast_. I'm using TypeScript for this, btw.

[Looking at the differences between 4.0.0 and 4.0.10](https://github.com/markedjs/marked/compare/v4.0.0...v4.0.10) it's not clear what changed, but something sure as crepes did, because trying to run the same import statement with 4.0.0 and 4.0.10 does not yield the same result. 4.0.0 worked, but updating to 4.0.10 yields error.

**To Reproduce**
[Follow the docs for basic usage](https://marked.js.org/#installation):

`yarn add marked@4.0.0`

**Editor:**
![image](https://user-images.githubusercontent.com/706874/150773532-7b880063-6f82-4f44-9629-2727a4745b1f.png)

Works fine.

---
Now change to 4.0.10

`yarn add marked@4.0.10`

**Editor:**
![image](https://user-images.githubusercontent.com/706874/150773644-39f0b17c-c21c-4438-bcd6-b9c4aa04d746.png)

**Expected behavior**
I expect the module to be found, dammit!

**You should fix this!**

**Comment by Coreusa** [comment]
After a long debug hunt, seems this is need to fix the issue when using Marked with Typescript: yarn add @types/marked

You must add this info to the docs!

**Comment by ghulamyazdani** [comment]
The same issue is with me its not able to find the module at first but when It suggests installing `@types/marked` when I installed it, It is getting the module from `@types/marked` not `marked`
Before installing `@types/markded`
![image](https://user-images.githubusercontent.com/55938346/151161570-944eb4ae-ae7b-4db8-986c-9e059473520b.png)
Afer installing `@types/markded`
![image](https://user-images.githubusercontent.com/55938346/151160898-2b5bc13b-0bab-4fe2-ac5c-eaac92bb455c.png)

*Note : I have already installed `"marked": "^4.0.10"`

**Comment by cwillwer** [comment]
The failure looks like it occurred between versions `4.0.0` and `4.0.1`, which should make it a bit easier to locate. It builds fine when only `4.0.0` is installed, but as soon as `4.0.1` or higher is installed you must also install `@types/marked` as mentioned above.
