### ISSUE TITLE
Copy to clipboard button for code blocks

### ISSUE THREAD

**Issue by amahajan02** [markedjs/marked#2365]
**What pain point are you perceiving?.**
For a code block, specially large code blocks, it is tedious to copy the code by scrolling down and selecting the entire code section.

**Describe the solution you'd like**
Inside a code block it would be helpful if there is a "Copy" button. User can click this button and get the entire code copied to clipboard present in that section.

**Comment by UziTech** [comment]
We only provide the html you can add any JavaScript and css you want.
