### ISSUE TITLE
Directly accessing the parser with a custom renderer does not use the custom renderer.

### ISSUE THREAD

**Issue by DoctorBracewell** [markedjs/marked#2374]
**Marked version:**
4.0.12

**Describe the bug**
Creating a custom renderer but using it directly with `marked.parser` and an array of tokens does not make the parser use the custom renderer.

**To Reproduce**
```javascript
import { marked } from "marked";

const exampleToken = [{ type: "text", text: "This is the example text.", raw: "This is the example text." }];

const renderer = new Renderer();
renderer.text = (text) => {
  return "This text should replace the text from the token.";
};

console.log(
  marked.parser(exampleToken, {
    renderer,
  })
); // <p>This is the example text.<p>
```

Here we see that when accessing the parser directly with `marked.parser`, it does **not** use the custom renderer we provide in the parameters - the result from the final `console.log` seems to be using the default renderer.

An example of a custom renderer working as intended is if we use `marked.parse` with a string of text to run through the whole pipeline:
```javascript
// Keeping our previous renderer setup from last time

console.log(
  marked.parse("This is the example text.", {
    renderer,
  })
); // <p>This text should replace the text from the token.<p>
```

**Expected behavior**
The expected behaviour is that when you access the parser directly using `marked.parser(...)`, the array of tokens you provide **should** be rendered with any custom renderer you provide in the second `options` parameter.

**Comment by DoctorBracewell** [comment]
Done a bit more fiddling about and here's what I've found:

One way to fix this is changing the `parser` call to something like this:
```javascript
  marked.parser(exampleToken, {
    extensions: {
      renderers: renderer
    }
  })
```
To make the custom renderer an extension - however this syntax is not documented anywhere and technically invalid in the typings - I assume this is because extensions are intended to be provided with `marked.use(...)`, but any extensions provided there don't seem to be applied when directly accessing the parser (maybe another issue?)

So I went deeper into why the parser isn't using the custom renderer passed in as an option, and took a look at line 185 in the `parse` method of a `Parser` instance:
```javascript
body = token.tokens ? this.parseInline(token.tokens) : token.text;
```
This is the case for when parsing a token of type `text` - if the text has any additional tokens inside it, these will all be parsed correctly using the `parseInline` function (which does use any custom renderers provided to the parser), but if the token is **just** a single string of text it won't use a custom renderer.

A potential fix for this is to change line 185 to something like:
```javascript
body = token.tokens ? this.parseInline(token.tokens) : this.parseInline([token.text]);
```
or:
```javascript
body = token.tokens ? this.parseInline(token.tokens) : this.renderer.text(token.text);
```

Which I can't really think of a reason not to do? - assuming that the intended functionality is any tokens of type `text` to be correctly rendered by any `text(...)` functions in a custom renderer.

**Comment by UziTech** [comment]
The parser expects the tokens array to contain block tokens. The tokens array you are sending in contains inline tokens. That is why line 185 looks the way it does.

I don't think there is any reason for us to create a breaking change to allow badly formatted block tokens to be passed in.
