### ISSUE TITLE
Lexer omits valid html tag

### ISSUE THREAD

**Issue by mihaeu** [markedjs/marked#2381]
**Marked version:** 4.0.12

**Describe the bug**
The lexer doesn't pick up an HTML tag correctly and instead thinks it's two separate tags. I noticed this in newer versions of `marked`. Older versions handled this scenario correctly.

**To Reproduce**

I checked out the repository and wrote a working test that displays the (in my opinion) broken functionality. Instead of creating 3 HTML tokens, the third HTML token misses the closing tag and the closing tag becomes a separate token.

```js
    it('should do things better', () => {
      const md = `<details>
<summary>Short Summary</summary>
More elaborate text \`with other things like monospace\`
</details>

<details>
Short Details without Summary
</details>

<details>
<summary>more in detail</summary>

...

</details>`;
      expectTokens({
        md: md,
        tokens: [
          {
            type: 'html',
            raw: `<details>
<summary>Short Summary</summary>
More elaborate text \`with other things like monospace\`
</details>

`,
            pre: false,
            text: `<details>
<summary>Short Summary</summary>
More elaborate text \`with other things like monospace\`
</details>

`
          },
          {
            type: 'html',
            raw: `<details>
Short Details without Summary
</details>

`,
            pre: false,
            text: `<details>
Short Details without Summary
</details>

`
          },
          {
            type: 'html',
            raw: `<details>
<summary>more in detail</summary>

`,
            pre: false,
            text: `<details>
<summary>more in detail</summary>

`
          },
          {
            type: 'paragraph',
            raw: '...',
            text: '...',
            tokens: [
              {
                type: 'text',
                raw: '...',
                text: '...'
              }
            ]
          },
          {
            type: 'space',
            raw: `

`
          },
          {
            type: 'html',
            raw: '</details>',
            pre: false,
            text: '</details>'
          }
        ]
      });
    });
```

**Expected behavior**

I would expect all three `<details>` tags to be picked up, because it's valid HTML. `marked` used to handle this scenario correctly. I have not investigated in which version it broke.

Thank you for your work :heart:

**Comment by UziTech** [comment]
According to the [spec](https://spec.commonmark.org/0.30/#html-blocks) html blocks end at the first blank line.

**Comment by mihaeu** [comment]
Thank you so much for clarifying this and pointing me to the spec 🥰

So this means CommonMark, at least with the default renderer, will have
problems with details tags which are supported by most VCS hosts' markdown
renderers.

Couldn't find a donate button on GitHub, but would've loved to. Keep up the
good work 💪
