### ISSUE TITLE
email with special characters breaking up the text also displaying as a link 

### ISSUE THREAD

**Issue by ravipenugonda** [markedjs/marked#2397]
"marked": "^2.1.3",

when email text doesn't have <> it shouldn't be a link and 
When email contains * (which is valid for certain domains) markdown doesn't render properly even though I tried to escape the special character with backslash.

**To Reproduce**
issue can be seen here
https://marked.js.org/demo/?text=%0A%0AThese%20shouldn%27t%20be%20a%20link%20as%20per%20markdown%20specs%20because%20they%20are%20not%20in%20less%20than%20and%20greater%20than%20symbols%20https%3A%2F%2Fwww.markdownguide.org%2Fbasic-syntax%2F%23urls-and-email-addresses%0A%0A%0Ajohn*doe%40domain.com%20%0A%0Amarkdown%20not%20working%20with%20the%20escape%20character%20(still%20email%20breaking)%0A%0Ajohn%5C*doe%40domain.com%0A%0AJohn%5C*%5C*doe%40domain.com%0A%0AWorking%20as%20expected%20with%20less%20than%20and%20greater%20than%20symbols%20%0A%3Cjohn*doe%40domain.com%3E%0A%0APlease%20provide%20the%20work%20around.%0A%0A%0A%0A&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master

**Expected behavior**
when escape character is used it 

Please provide the work around. Thanks

**Comment by UziTech** [comment]
This seems to be exactly how GitHub renders it so it is working as intended.

---

These shouldn't be a link as per markdown specs because they are not in less than and greater than symbols https://www.markdownguide.org/basic-syntax/#urls-and-email-addresses


john*doe@domain.com 

markdown not working with the escape character (still email breaking)

john\*doe@domain.com

John\*\*doe@domain.com

Working as expected with less than and greater than symbols 
<john*doe@domain.com>

Please provide the work around.

**Comment by UziTech** [comment]
You can set the `gfm` option to `false` if you don't want urls to automatically turn to links

**Comment by ravipenugonda** [comment]
OK So another issue I am facing even though I tried to escape * with backslash it's not working.markdown still not escaping this character and adding tag <em></em>

**Comment by UziTech** [comment]
Can you try creating a demo at https://spec.commonmark.org/dingus/

**Comment by UziTech** [comment]
Also it looks like you are using marked v2 there have been some major updates to em tags since than so you should try updating to v4
