### ISSUE TITLE
The 'this' context of type 'Tokenizer<never>' is not assignable to method's 'this' of type 'TokenizerThis'.

### ISSUE THREAD

**Issue by MykSto** [markedjs/marked#2403]
**Marked version:** ^4.0.12
**Marked Typying version:** "@types/marked": "^4.0.2",

**Proposal type:** typing adjustment

## What pain point are you perceiving?
Typing issue from before [Renderer](https://github.com/markedjs/marked/issues/2358)
The same typing issue is now observed with [Tokenizer]

## What solution are you suggesting?
Add `this: Tokenizer | TokenizerThis` type to `class Tokenizer<T = never>` methods

## What was attempted

Code example:
```js
class CustomTokenizer extends Tokenizer {
  inlineText(...args: Parameters<Tokenizer['inlineText']>) {
    const p = super.inlineText(...args)

    return p
  }
}
```

## Call stack & console log

```js
The 'this' context of type 'Tokenizer<never>' is not assignable to method's 'this' of type 'TokenizerThis'.
Property 'lexer' is missing in type 'Tokenizer<never>' but required in type 'TokenizerThis'.

const p = super.inlineText(...args)
          ~~~~~

node_modules/@types/marked/index.d.ts:459:9
     lexer: Lexer;
     ~~~~~
    'lexer' is declared here.
  ```

**Comment by UziTech** [comment]
You can create a PR similar to https://github.com/DefinitelyTyped/DefinitelyTyped/pull/58495 for the tokenizer in the [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) repo

**Comment by MykSto** [comment]
Alright, will do :muscle:
