### ISSUE TITLE
Image inside table not rendering

### ISSUE THREAD

**Issue by stevenjoezhang** [markedjs/marked#2404]
**Marked version: 3.0.0 or later**

**Describe the bug**
Image inside table not rendering. The source code like `![img][src]` is output as is, no HTML `<img>` element is generated.

**To Reproduce**

1. [Marked Demo version 3.0.0](https://marked.js.org/demo/?text=%7C%20Tomorrow%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%20Tomorrow%20Night%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%20Tomorrow%20Night%20Eighties%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%0A%7C%20%3A-----------------------%3A%20%7C%20%3A-----------------------------%3A%20%7C%20%3A-------------------------------------------------%3A%20%7C%0A%7C%20!%5BTomorrow%5D%5BTomorrow%5D%20%20%20%20%20%7C%20!%5BTomorrow%20Night%5D%5B%5D%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%20!%5BTomorrow%20Night%20Eighties%5D%5BTomorrow%20Night%20Eighties%5D%20%7C%0A%0A%7C%20Tomorrow%20Night%20Blue%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%20Tomorrow%20Night%20Bright%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%20Default%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%0A%7C%20%3A-----------------------------------------%3A%20%7C%20%3A---------------------------------------------%3A%20%7C%20%3A----------------------%3A%20%7C%0A%7C%20!%5BTomorrow%20Night%20Blue%5D%5BTomorrow%20Night%20Blue%5D%20%7C%20!%5BTomorrow%20Night%20Bright%5D%5BTomorrow%20Night%20Bright%5D%20%7C%20!%5BDefault%5D%5BDefault%5D%20%20%20%20%20%20%7C%0A%0A%5BTomorrow%5D%3A%20%2Fimages%2Ftomorrow.svg%0A%5BTomorrow%20Night%5D%3A%20%2Fimages%2Ftomorrow-night.svg%0A%5BTomorrow%20Night%20Eighties%5D%3A%20%2Fimages%2Ftomorrow-night-eighties.svg%0A%5BTomorrow%20Night%20Blue%5D%3A%20%2Fimages%2Ftomorrow-night-blue.svg%0A%5BTomorrow%20Night%20Bright%5D%3A%20%2Fimages%2Ftomorrow-night-bright.svg%0A%5BDefault%5D%3A%20%2Fimages%2Fdefault.svg&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22extensions%22%3A%20null%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=3.0.0)
2. [Marked Demo version 2.1.3](https://marked.js.org/demo/?text=%7C%20Tomorrow%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%20Tomorrow%20Night%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%20Tomorrow%20Night%20Eighties%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%0A%7C%20%3A-----------------------%3A%20%7C%20%3A-----------------------------%3A%20%7C%20%3A-------------------------------------------------%3A%20%7C%0A%7C%20!%5BTomorrow%5D%5BTomorrow%5D%20%20%20%20%20%7C%20!%5BTomorrow%20Night%5D%5B%5D%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%20!%5BTomorrow%20Night%20Eighties%5D%5BTomorrow%20Night%20Eighties%5D%20%7C%0A%0A%7C%20Tomorrow%20Night%20Blue%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%20Tomorrow%20Night%20Bright%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%20Default%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%0A%7C%20%3A-----------------------------------------%3A%20%7C%20%3A---------------------------------------------%3A%20%7C%20%3A----------------------%3A%20%7C%0A%7C%20!%5BTomorrow%20Night%20Blue%5D%5BTomorrow%20Night%20Blue%5D%20%7C%20!%5BTomorrow%20Night%20Bright%5D%5BTomorrow%20Night%20Bright%5D%20%7C%20!%5BDefault%5D%5BDefault%5D%20%20%20%20%20%20%7C%0A%0A%5BTomorrow%5D%3A%20%2Fimages%2Ftomorrow.svg%0A%5BTomorrow%20Night%5D%3A%20%2Fimages%2Ftomorrow-night.svg%0A%5BTomorrow%20Night%20Eighties%5D%3A%20%2Fimages%2Ftomorrow-night-eighties.svg%0A%5BTomorrow%20Night%20Blue%5D%3A%20%2Fimages%2Ftomorrow-night-blue.svg%0A%5BTomorrow%20Night%20Bright%5D%3A%20%2Fimages%2Ftomorrow-night-bright.svg%0A%5BDefault%5D%3A%20%2Fimages%2Fdefault.svg&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22extensions%22%3A%20null%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=2.1.3)
3. The CommonMark Demo is not applicable because `gfm` option is enabled. You can test the following markdown source code on GitHub:

```md
| Tomorrow                  | Tomorrow Night                  | Tomorrow Night Eighties                             |
| :-----------------------: | :-----------------------------: | :-------------------------------------------------: |
| ![Tomorrow][Tomorrow]     | ![Tomorrow Night][]             | ![Tomorrow Night Eighties][Tomorrow Night Eighties] |

| Tomorrow Night Blue                         | Tomorrow Night Bright                           | Default                  |
| :-----------------------------------------: | :---------------------------------------------: | :----------------------: |
| ![Tomorrow Night Blue][Tomorrow Night Blue] | ![Tomorrow Night Bright][Tomorrow Night Bright] | ![Default][Default]      |

[Tomorrow]: /images/tomorrow.svg
[Tomorrow Night]: /images/tomorrow-night.svg
[Tomorrow Night Eighties]: /images/tomorrow-night-eighties.svg
[Tomorrow Night Blue]: /images/tomorrow-night-blue.svg
[Tomorrow Night Bright]: /images/tomorrow-night-bright.svg
[Default]: /images/default.svg
```

| Tomorrow                  | Tomorrow Night                  | Tomorrow Night Eighties                             |
| :-----------------------: | :-----------------------------: | :-------------------------------------------------: |
| ![Tomorrow][Tomorrow]     | ![Tomorrow Night][]             | ![Tomorrow Night Eighties][Tomorrow Night Eighties] |

| Tomorrow Night Blue                         | Tomorrow Night Bright                           | Default                  |
| :-----------------------------------------: | :---------------------------------------------: | :----------------------: |
| ![Tomorrow Night Blue][Tomorrow Night Blue] | ![Tomorrow Night Bright][Tomorrow Night Bright] | ![Default][Default]      |

[Tomorrow]: /images/tomorrow.svg
[Tomorrow Night]: /images/tomorrow-night.svg
[Tomorrow Night Eighties]: /images/tomorrow-night-eighties.svg
[Tomorrow Night Blue]: /images/tomorrow-night-blue.svg
[Tomorrow Night Bright]: /images/tomorrow-night-bright.svg
[Default]: /images/default.svg

**Expected behavior**
The rendering result of marked version 3.0.0 or later should be the same as version 2.1.3 (and GitHub Flavored Markdown)

**Comment by UziTech** [comment]
duplicate of #2217
