### ISSUE TITLE
Having Trouble to Understand the Extension Example

### ISSUE THREAD

**Issue by centigrade-julian-lang** [markedjs/marked#2414]
I'm new to marked and I would like to create an own extension. I have trouble understanding and migrating the example (https://marked.js.org/using_pro#extensions) to my needs. IMHO the documentation is a bit short on explanations, especially in essential parts of the code.

It seems that the most central part of the extensions are the regular expression matches in start and tokenize.
I have trouble understanding what exactly they are doing and why they need to be written the way they are in order to work for marked.js

When I tried to create my own extension with a much easier regex, my extension ended up consuming and replacing the whole text body instead only the desired syntax pattern. So there must be something crucial that I am missing.

Could you please help me out with this by explaining the essential bits of extensions more thorough? Maybe it's also a good idea to improve the current docs a bit as well.

Thanks for your help and great work :)

**Comment by calculuschild** [comment]
If you can give us an example of what you have tried and what you are designing your extension to do, we could point you in the right direction. Then once you have your extension working and understand the process, feel free to send us specific changes you would like to see in the docs for future users.

**Comment by centigrade-julian-lang** [comment]
I wanted to create some syntax like `some text :123 some other text`, where ":123" is my special syntax for a internal link:

~~~ts
import { marked } from "marked";
import { MarkdownExtension } from "./types";

export const InternalLink: MarkdownExtension = {
  name: "internal-link",
  level: "inline",
  start(src: string) {
    const start = src.match(/\:(\d+)/)?.index!;
    return start;
  },
  tokenizer(src: string, tokens: any[]) {
    const rule = /\:(\d+))/; // Regex for the complete token
    const match = rule.exec(src);

    if (match) {
      const token = {
        type: "internal-link", // Should match "name" above
        raw: match[0], // Text to consume from the source
        text: this.lexer.inlineTokens(match[1].trim(), []), // Additional custom properties
      };

      return token;
    }

    return;
  },
  renderer(token: marked.Tokens.Generic) {
    return `\n<u>${this.parser.parseInline(token.text, null!)}</u>`;
  },
};
~~~

results in:
<img width="136" alt="image" src="https://user-images.githubusercontent.com/17612352/159155049-e6e1a607-0642-4260-aaa6-677c85470d20.png">

**Comment by UziTech** [comment]
Your rule should match the pattern at the start of the string

```diff
- const rule = /\:(\d+))/;
+ const rule = /^\:(\d+))/;
```

**Comment by centigrade-julian-lang** [comment]
Aaah thanks, that's working :)

**Comment by calculuschild** [comment]
Now that it's working, do you have any specific suggestion to make the docs more clear?

**Comment by centigrade-julian-lang** [comment]
I guess emphasizing on what exactly these regex should target. I didn't know or realize that it's important that the regex needs to target the beginning of the token; especiall because the docs have a comment saying "// regex of the whole token" or similar, not mentioning that the start needs to be anchored as well.
