### ISSUE TITLE
Marked throws away all HTML content

### ISSUE THREAD

**Issue by llee454** [markedjs/marked#2423]
**Marked version:**

**Describe the bug**
When processing a string that contains HTML, Marked throws away all of the HTML tags.

**To Reproduce**
Pass a string to marked.parse that contains any HTML tags

**Expected behavior**
Given a string like:

```
  # Normal Markdown Header
  <span>DONT DELETE THESE TAGS</span>
```

I expect to get back:

```
<h1>Normal Markdown Header</h1>
<span>DONT DELETE THESE TAGS</span>
```

**Comment by calculuschild** [comment]
What behavior do you get?

The [demo page](https://marked.js.org/demo/?text=%23%20Normal%20Markdown%20Header%0D%0A%3Cspan%3EDONT%20DELETE%20THESE%20TAGS%3C%2Fspan%3E&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22extensions%22%3A%20null%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master) shows that TAGS are indeed preserved.

**Comment by llee454** [comment]
Thank @calculuschild. I figured out the cause of the problem in my original code. The issue was not with Marked.
