### ISSUE TITLE
Invalid em + strong rendering

### ISSUE THREAD

**Issue by reorx** [markedjs/marked#2440]
**Marked version:** master

**Describe the bug**

`a***\[1\]***b` is rendered `a***[1]***b`

**To Reproduce**

[Demo page](https://marked.js.org/demo/?outputType=html&text=a***%5C%5B1%5C%5D***b%0A%0Aa***1***b&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22extensions%22%3A%20null%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master)

**Expected behavior**

It should be rendered as `a</strong></em>[1]</strong></em>b`, like [Example 425](https://github.github.com/gfm/#example-425) in CommonMark spec.

**Comment by UziTech** [comment]
Looks like that is the way it is supposed to work according to [commonmark](https://spec.commonmark.org/dingus/?text=a***%5C%5B1%5C%5D***b%0A%0Aa***1***b)

**Comment by UziTech** [comment]
Maybe but we follow their lead so if you want it changed you will have to fix it on their [repo](https://github.com/commonmark/commonmark-spec)

**Comment by reorx** [comment]
Agree, I will submit an issue to CommonMark first, and will reopen if a conclusion is made.
