### ISSUE TITLE
ESM modules inside html tag of markup file are not loading in chrome

### ISSUE THREAD

**Issue by vellala2000** [markedjs/marked#2444]
**Marked version:**
4.0.14
**Describe the bug**
Tring to load swagger UI using html tag inside .md file. html has references to ESM modules from unpkg.com

Generated html code seems to have references to the unpkg.com as expected, however chrome browser not making a call for the esm modules.

swagger UI static site: https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/installation.md

**To Reproduce**
[marked demo link](https://marked.js.org/demo/?text=%3Chtml%20lang%3D%22en%22%3E%0A%20%20%3Chead%3E%0A%20%20%20%20%3Cmeta%20charset%3D%22utf-8%22%20%2F%3E%0A%20%20%20%20%3Cmeta%20name%3D%22viewport%22%20content%3D%22width%3Ddevice-width%2C%20initial-scale%3D1%22%20%2F%3E%0A%20%20%20%20%3Cmeta%0A%20%20%20%20%20%20name%3D%22description%22%0A%20%20%20%20%20%20content%3D%22SwaggerIU%22%0A%20%20%20%20%2F%3E%0A%20%20%20%20%3Ctitle%3ESwaggerUI%3C%2Ftitle%3E%0A%20%20%20%20%3Clink%20rel%3D%22stylesheet%22%20href%3D%22https%3A%2F%2Funpkg.com%2Fswagger-ui-dist%404.5.0%2Fswagger-ui.css%22%20%2F%3E%0A%20%20%3C%2Fhead%3E%0A%20%20%3Cbody%3E%0A%20%20%3Cdiv%20id%3D%22swagger-ui%22%3E%3C%2Fdiv%3E%0A%20%20%3Cscript%20src%3D%22https%3A%2F%2Funpkg.com%2Fswagger-ui-dist%404.5.0%2Fswagger-ui-bundle.js%22%20crossorigin%3E%3C%2Fscript%3E%0A%20%20%3Cscript%20src%3D%22https%3A%2F%2Funpkg.com%2Fswagger-ui-dist%404.5.0%2Fswagger-ui-standalone-preset.js%22%20crossorigin%3E%3C%2Fscript%3E%0A%20%20%3Cscript%3E%0A%20%20%20%20window.onload%20%3D%20()%20%3D%3E%20%7B%0A%20%20%20%20%20%20window.ui%20%3D%20SwaggerUIBundle(%7B%0A%20%20%20%20%20%20%20%20url%3A%20%27https%3A%2F%2Fpetstore3.swagger.io%2Fapi%2Fv3%2Fopenapi.json%27%2C%0A%20%20%20%20%20%20%20%20dom_id%3A%20%27%23swagger-ui%27%2C%0A%20%20%20%20%20%20%20%20presets%3A%20%5B%0A%20%20%20%20%20%20%20%20%20%20SwaggerUIBundle.presets.apis%2C%0A%20%20%20%20%20%20%20%20%20%20SwaggerUIStandalonePreset%0A%20%20%20%20%20%20%20%20%5D%2C%0A%20%20%20%20%20%20%20%20layout%3A%20%22StandaloneLayout%22%2C%0A%20%20%20%20%20%20%7D)%3B%0A%20%20%20%20%7D%3B%0A%20%20%3C%2Fscript%3E%0A%20%20%3C%2Fbody%3E%0A%3C%2Fhtml%3E&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22extensions%22%3A%20null%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master)

I grabbed the generated iframe code and tryed it w3schools it works okay. not sure what am i missing here..

**Expected behavior**
Chrome trigger calls to unpkg modules and render swagger UI static site

**Comment by UziTech** [comment]
What does this have to do with marked? This seems to be an issue with swagger.

**Comment by vellala2000** [comment]
Its working okay with markdown preview in visual studio code. However when I used docsify and marked to generate a static website its not working as expected. Same thing is replicated in marked demo as well. 

So just wanted to check if there are any restrictions in marked implementation or something preventing esm java scrips from importing

**Comment by UziTech** [comment]
Marked only converts markdown to html. Marked does not load or import anything. The browser rendering the HTML will be responsible for importing.

The demo explicitly will not run or load scripts to prevent xss.

**Comment by vellala2000** [comment]
Thank you for the information. docsify probably a better place for this issue. Thank you.
