### ISSUE TITLE
Inline extension doesn't care about start index

### ISSUE THREAD

**Issue by PaulSchult** [markedjs/marked#2470]
**What pain point are you perceiving?.**
I'm creating a new inline extension. When the tokenizer is called I match it with a regex and return `raw` as match[0] which represents the whole text of the extension which should be removed.

This is my `src`:
`dummyText\n@link(entityId="45861b89-fd94-4010-8a32-fc97439df913", entityIcon="fas fa-user", recordId="bf30a130-9a48-4064-8a17-79cdcfbfa585")`

MarkedJS then does a src.substring(token.raw.length). The resulting src is wrong. It doesn't take the start index of the start function into account. Thats why the result is cut into wrong pieces.

code excerpt:
```
start(src) {
    return src.match(/@link/)?.index;
},
tokenizer(src) {
    const match = src.match(/^@link\(entityId="(.*)", entityIcon="(.*)", recordId="(.*)"\)/m);
    if (match) {
      return {
        type: 'recordLink',
        raw: match[0],
        entityId: match[1],
        entityIcon: match[2],
        recordId: match[3],
      };
   }
},
```

**Describe the solution you'd like**
Ideally marked does something like `src = src.substring(token.index, token.raw.length + token.index);`. It should take the index of the found token into account. This way marked only cuts out the real part of the extension.

**Comment by PaulSchult** [comment]
Thanks for the quick reply!

The content of the `tokenizer` is already in the inital post. I'm returning the first match as `raw`, as seen in the docs. With the given `src` of the initial post, the `match[0]` is `@link(entityId="45861b89-fd94-4010-8a32-fc97439df913", entityIcon="fas fa-user", recordId="bf30a130-9a48-4064-8a17-79cdcfbfa585")`.

The actual html that is returned by marked is similiar to this: 
```html
<p>
 <record-link entityid="99a07d20-2e1c-4c00-9a62-ffcef15f783a" entityicon="fas fa-boxes" recordid="569addf3-35c7-48d2-ac3b-98581abf76b9">
   <span class="one-link">
      <span class="fa-boxes fas"></span> 
      OpenSource
   </span>
 </record-link>
 1abf76b9")
</p>
```

I already tried debugging it. I landed in the inlineBlock function where my own extension is executed and there the `src = src.substring(token.raw.length)` was executed. And because the index wasn't accounted for the "dummyText" of the initial src, it was also used when building a substring.  Which in return results in the above html where my own extension is rendered but the last symbols of it are also shown (which are the exact length oft the "dummyText" string preceding my token).

As far as I can tell the start function was never really called and the index was never really taken care of. I am not sure if it's a configuration issue on my side or if it's a bug on your side. 

If you need any more information let me know :)

**Comment by PaulSchult** [comment]
Thanks for the quick reply!

The content of the `tokenizer` is already in the inital post. I'm returning the first match as `raw`, as seen in the docs. With the given `src` of the initial post, the `match[0]` is `@link(entityId="45861b89-fd94-4010-8a32-fc97439df913", entityIcon="fas fa-user", recordId="bf30a130-9a48-4064-8a17-79cdcfbfa585")`.

The actual html that is returned by marked is similiar to this: 
```html
<p>
 <record-link entityid="99a07d20-2e1c-4c00-9a62-ffcef15f783a" entityicon="fas fa-boxes" recordid="569addf3-35c7-48d2-ac3b-98581abf76b9">
   <span class="one-link">
      <span class="fa-boxes fas"></span> 
      OpenSource
   </span>
 </record-link>
 1abf76b9")
</p>
```

I already tried debugging it. I landed in the inlineBlock function where my own extension is executed and there the `src = src.substring(token.raw.length)` was executed. And because the index wasn't accounted for the "dummyText" of the initial src, it was also used when building a substring.  Which in return results in the above html where my own extension is rendered but the last symbols of it are also shown (which are the exact length oft the "dummyText" string preceding my token).

As far as I can tell the start function was never really called and the index was never really taken care of. I am not sure if it's a configuration issue on my side or if it's a bug on your side. 

If you need any more information let me know :)

**Comment by calculuschild** [comment]
@PaulSchult 

Ah, your tokenizer `match` uses the `/m` multiline tag. This may be causing issues, since this changes the `^` to match the start of a line, rather than the start of the string. So your match is no longer enforced to start at the string start, but instead can start anywhere in your input string as long as `@` is at the beginning of a line. Thus the Regex includes your dummy text as part of its input string, but only captures your token partway through the string. This is probably what is throwing it off.

**Comment by PaulSchult** [comment]
@calculuschild Thanks for the help, I appreciate it! The `/m` was indeed leading to the faulty rendering.
