### ISSUE TITLE
weird behavior on link

### ISSUE THREAD

**Issue by ropoko** [markedjs/marked#2512]
**Marked version: 4.0.17**

**Describe the bug**
when parsing an markdown like this: `[some random text](https://linkforrandomtext.com)`, the tag `<a>` gets the height of the paragraph (`<p>`)

![image](https://user-images.githubusercontent.com/49417432/174664436-9477a4a6-f942-4cc6-8080-ce666584ce72.png)

In the image above, the white space below the link represents the height it gets proportional to the height of the paragraph

**To Reproduce**

in the markdown file: 
```md
 text text text text text text [link](http://some-random-link.com)
```

in the component that renders the md: 
```tsx
<div
	dangerouslySetInnerHTML={{
		__html: marked(post.content, {
			gfm: true,
			mangle: true,
			smartLists: true,
			smartypants: true,
		}),
	}}
></div>
```

**Expected behavior**
the link should appear like this:
![image](https://user-images.githubusercontent.com/49417432/174665230-b81799df-6e4c-4107-948c-258801c58471.png)

**Comment by calculuschild** [comment]
This looks like a result of CSS styling on your `<a>` tags. Marked.js does not apply any CSS.

**Comment by ropoko** [comment]
for some reason this only show when the tag p is with the `display: flex`, but anyway, I don't even know why I was using a flex there, so the error was in my code.
After removing that display, I got the expected behavior.
