### ISSUE TITLE
Breaking change of leading tab in unordered list

### ISSUE THREAD

**Issue by ErazerBrecht** [markedjs/marked#2516]
**What pain point are you perceiving?.**
When using 2 leading tabs in a list it starts seeing it as a code block. Which could make sense
But starting from 4.0.15 it also places them on another level which I really can't explain.

Marked has introduced this breaking change between version 4.0.13 & 4.0.14, and 4.0.15 makes it even worse.
Caused by #2434 

[Working example 4.0.13](https://marked.js.org/demo/?text=%23%23%23%20%E2%9A%A0%EF%B8%8F%20Hello%20World%20%E2%9A%A0%EF%B8%8F%0A%0A-%20A%0A-%20%20%20B%0A-%09C%0A-%09D%0A-%09E%0A-%09F&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22extensions%22%3A%20null%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=4.0.13)
[Broken example 4.0.14](https://marked.js.org/demo/?text=%23%23%23%20%E2%9A%A0%EF%B8%8F%20Hello%20World%20%E2%9A%A0%EF%B8%8F%0A%0A-%20A%0A-%20%20%20B%0A-%09C%0A-%09D%0A-%09E%0A-%09F&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22extensions%22%3A%20null%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=4.0.14)
[Even more broken example 4.0.15](https://marked.js.org/demo/?text=%23%23%23%20%E2%9A%A0%EF%B8%8F%20Hello%20World%20%E2%9A%A0%EF%B8%8F%0A%0A-%20A%0A-%20%20%20B%0A-%09C%0A-%09D%0A-%09E%0A-%09F&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22extensions%22%3A%20null%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=4.0.15)

**Describe the solution you'd like**
A solution where it keeps working as it used to. I checked GitHub and they seem to ignore the tabs.
[CommonMark](https://spec.commonmark.org/dingus/?text=%23%23%23%20%E2%9A%A0%EF%B8%8F%20Hello%20World%20%E2%9A%A0%EF%B8%8F%0A%0A-%20A%0A-%20%20%20B%0A-%09C%0A-%09D%0A-%09E%0A-%09F) seems to agree this is wrong. Dillinger also ignores it.

**Comment by lasmil** [comment]
Hi @ErazerBrecht . I played with the example you provided and (I might be wrong) I found that if you use the option: pedantic = true, then you will get the expected response.

I created a PR as well which should add an example of pedantic being false or true with your example (I think it will be useful for anybody who encounters this scenario).

**Comment by ErazerBrecht** [comment]
Hi @lasmil thx for that idea.
I'll see if I can test that option!

Sincerely,
Brecht
