### ISSUE TITLE
Link is not rendered when a HTML tag is present one line above

### ISSUE THREAD

**Issue by blikblum** [markedjs/marked#2517]
**Marked version:**
4.0.17 or master

**Describe the bug**
When a html tag (tested with `br` and `hr`) is followed by a line with link [](), the link is rendered as is (not converted to `a` tag)

**To Reproduce**

Marked: https://marked.js.org/demo/?text=%23%20Hello%0A%0AText%0A%0A%3Cbr%3E%0AHello%20%5Blink%5D(https%3A%2F%2Fmarked.js.org%2F)%20%0A&options=%7B%0A%20%0A%7D&version=master

Dingus: https://spec.commonmark.org/dingus/?text=%23%20Hello%0A%0AText%0A%0A%3Cbr%3E%0AHello%20%5Blink%5D(https%3A%2F%2Fmarked.js.org%2F)%20%0A%0A

Showdow: http://demo.showdownjs.com/#!/%23%20Hello%0A%0AText%0A%0A%3Cbr%3E%0AHello%20%5Blink%5D(https%3A%2F%2Fmarked.js.org%2F)

**Expected behavior**
The markdown link should be rendered as html

While dingus also not renders, this is not expected as a user POV. 
Showdown renders as html

**Comment by UziTech** [comment]
Marked follows CommonMark. Markdown inside an html block is rendered as html not markdown. If you add a blank line below the html tag it will work.

**Comment by blikblum** [comment]
Thanks

**Comment by blikblum** [comment]
Created an issue in the editor that created the markdown: https://github.com/nhn/tui.editor/issues/2586
