### ISSUE TITLE
Comments Within Fenced Code Blocks Within Unordered Lists Are Parsed As Headings

### ISSUE THREAD

**Issue by Kurt-von-Laven** [markedjs/marked#2518]
**Marked version:** 4.0.17

**Describe the bug**
It appears that marked gets confused by the presence of `#` within a fenced code block within an unordered list, mistaking comments for headings, and failing to detect actual headings after the fenced code block.

**To Reproduce**

1. [Marked Demo](https://marked.js.org/demo/?text=%23%20test%0A%0A%23%23%20before%0A%0A-%20unordered%20list%0A%0A%20%20%60%60%60bash%0A%20%20%23%20Fenced%20code%20block%20containing%20a%20comment%0A%20%20%60%60%60%0A%0A%23%23%20after&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22extensions%22%3A%20null%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=4.0.17)
2. [CommonMark Demo](https://spec.commonmark.org/dingus/?text=%23%20test%0A%0A%23%23%20before%0A%0A-%20unordered%20list%0A%0A%20%20%60%60%60bash%0A%20%20%23%20Fenced%20code%20block%20containing%20a%20comment%0A%20%20%60%60%60%0A%0A%23%23%20after)

**Expected behavior**
I expected the renderer to call `heading` for each heading, not only the ones preceding the fenced code block in question. I did not expect the renderer to call `heading` for the comments within the fenced code block. This issue may be related to #2483 as it does not appear in marked 4.0.16.

**Comment by UziTech** [comment]
Looks like this is something that broke in the last release
