### ISSUE TITLE
compression

### ISSUE THREAD

**Issue by adius** [markedjs/marked#252]
Why is there no option to print out compressed html?
I think that's definitely a "must have" feature!

**Comment by rudolfschmidt** [comment]
If you compress your regular html it would be nice if the html output from markdown would be also compressed. I agree, its a must have feature. Some workaround already?

**Comment by joshbruce** [comment]
Was going to mark this as stale, but I'm curious if this is still a desired feature for folks actively using marked.

I see what @jonathanong is saying. I also think there are issues that come with interspersing Markdown *and* HTML. In some cases, it's better to just pick HTML. Or, compile and inject. With template string literals this could be pretty straightforward. But, I'm new around here still; so, I'll have to use pseudo-code.

If your markdown is coming from a database query, it shouldn't have HTML, in my opinion.

```js
let markdown = 'Hello, World!`;
let html = marked.toHtml(markdown);
let final = `<div style="inline-block">${html}</div>`
```

That HTML is definitely strange but, looking at the broader point, knowing what the output is and the possible side-effects of that...anyway....

See #956

**Comment by adius** [comment]
Still desired.

**Comment by joshbruce** [comment]
The drawback I see is the potential cost-benefit of doing something like this. For `<code><pre></pre></code>` we need to maintain whitespace. I don't know what the overhead would for stripping whitespace, on the fly, while ignoring the triple-backtick case.

**Comment by adius** [comment]
I'd implement the easy solution first. i.e. strip all whitespace between adjacent tags with no content in between. 

```html
<div>
  <p>  Test  </p>
</div>
```
becomes

```html
<div><p>  Test  </p></div>
```
This shouldn't break anything and be easy to implement

**Comment by UziTech** [comment]
This can easily be done with other tools after getting the uncompressed output from marked.

```js
const minify = require('html-minifier').minify;
const marked= require('marked').minify;

const md = "some markdown";

const result = minify(marked(md));

// result is now minified html
```

**Comment by mccraveiro** [comment]
I agree with @UziTech! There are better tools for the job and we should leave this out of marked. 

The "dumb" way of implementing this feature would be to just add `html-minifier` in the bundle. However, this would just add complexity and size to the library. 

I would go with adding @UziTech's example to the readme as an "official" solution for the problem.

**Comment by UziTech** [comment]
I'm going to close this since we will not be adding it to core but will most likely create an extension for it.
