### ISSUE TITLE
marked import error

### ISSUE THREAD

**Issue by yaldram** [markedjs/marked#2521]
**Marked version:** 4.0.17

**Describe the bug**
I am using react with `create-react-app, webpack version 5`. When I import marked like - `import { marked } from "marked";`  I get the following error : - 

<img width="850" alt="image" src="https://user-images.githubusercontent.com/13429535/177109390-fbeb215f-2274-435d-907e-47842c7defba.png">

**To Reproduce**
- Clone the repository - https://github.com/appsmithorg/appsmith.
- Run `cd app/client`.
- Run `git checkout dependentbot-updates`
- Run `yarn install`
- Run `yarn start`

**Expected behavior**

**Comment by yaldram** [comment]
I had to import marked using commonjs like so - `const { marked } = require("marked")`.

**Comment by yaldram** [comment]
When I import `const { marked } = require('marked')` I get a runtime error saying - `marked is not a function`. I am unable to use  version 4.0 and above due to the above error. Can you please suggest a workaround sir @UziTech, thanks.

**Comment by UziTech** [comment]
What do you get when you log the output of `require('marked')`?

**Comment by yaldram** [comment]
@UziTech sir, using `const { marked } = require('marked')` returns `undefined`. 
Using `const marked = require('marked')` returns ` /static/media/marked.af4dd239aa577a4f71e4.cjs`.

**Comment by UziTech** [comment]
I tried with a new cra app and `import { marked } from 'marked'` seems to work fine. Can you create a minimal repo that reproduces it?

**Comment by yaldram** [comment]
@UziTech thanks a lot, i tried with a create-react-app and it is working as expected, I will check with webpack config. Thanks for your time.

**Comment by yaldram** [comment]
@UziTech sir, don't you think the `commonjs` import should work I create a new create-react-app even there I get the output as mentioned above, but importing other libraries using `commonjs` syntax works as expected.

**Comment by UziTech** [comment]
`commonjs` import seems to work for me ([demo](https://runkit.com/uzitech/62d87f4db413f20008acddc6)). It looks like the issue is somewhere in create-react-app.

**Comment by yaldram** [comment]
Yes there is some issue with `create-react-app`. We have finally resolved this error by adding this babel helper `@babel/helper-create-regexp-features-plugin` as a devDependency.
