### ISSUE TITLE
Option to not  wrap custom elements in a <p>

### ISSUE THREAD

**Issue by amundo** [markedjs/marked#2547]
**Describe the feature**
GitHub flavored markdown wraps custom elements (with hyphens in their names) in a `<p>` tag, like this:

https://github.github.com/gfm/#example-636

```
<responsive-image src="foo.jpg" />
```

Becomes:

```html
<p><responsive-image src="foo.jpg" /></p>
```

I think it would be helpful if there were a way to specify that the output should be:

```html
<responsive-image src="foo.jpg" />
```

**Why is this feature necessary?**

Some custom elements aren’t designed to be nested inside `<p>` tags. 

**Describe alternatives you've considered**

Pandoc has a `raw_attribute` plugin that does this; if there is such an option in marked I haven’t been able to find it.

https://github.com/jgm/pandoc/issues/5903

Thanks for this cool project.

**Comment by UziTech** [comment]
Marked doesnt't wrap any html elements with `<p>` tags. [demo](https://marked.js.org/demo/?outputType=html&text=%3Cresponsive-image%20src%3D%22foo.jpg%22%20%2F%3E&options=%7B%0A%20%22gfm%22%3A%20true%0A%7D&version=master)

This works according to the [spec](https://spec.commonmark.org/0.30/#raw-html)

**Comment by amundo** [comment]
It seems that no `<p>` is added if the custom element is self-closing, but one is added if there is a closing tag:

[demo](https://marked.js.org/demo/?outputType=html&text=%3Cresponsive-image%20src%3D%22foo.jpg%22%3E%3C%2Fresponsive-image%3E&options=%7B%0A%20%22gfm%22%3A%20true%0A%7D&version=master)

Although I see now that the commonmark dingus behaves the [same way](https://spec.commonmark.org/dingus/?text=Foo%20%3Cresponsive-image%20src%3D%22foo.jpg%22%20%2F%3E%0A).

**Comment by UziTech** [comment]
Yes if you want to change the way HTML is handled in marked you will need to create a [custom extension](https://marked.js.org/using_pro#extensions).

**Comment by amundo** [comment]
Ok, thanks, I might try that. Still not sure I understand why that behavior is part of the spec, it strikes me as strange, but I guess it’s external to marked itself. Thanks for your help. 🤷🏻
