### ISSUE TITLE
TypeScript and/or Documentation issue

### ISSUE THREAD

**Issue by sernaferna** [markedjs/marked#2551]
**Marked version:** 4.0.18
**@types/marked version:** 4.0.3

**Describe the bug**
I've followed the documentation for creating a [custom extension](https://marked.js.org/using_pro#extensions), but TypeScript complains about the `lexer.inlineTokens()` and `parser.parseInline()` methods. The sample extension in the documentation has one param for each, but TypeScript feels there should be two.

**To Reproduce**
Here's a sample extension, that replaces `==highlighted text==` with `<mark>highlighted text</mark>`: 

```typescript
import { marked } from 'marked';

export const highlightExtension: marked.TokenizerExtension | marked.RendererExtension = {
  name: 'highlightExtension',
  level: 'inline',
  start(src) {
    return src.match(/==/)?.index || -1;
  },
  tokenizer(src, tokens) {
    const rule = /^==([^=]+)==/;
    const match = rule.exec(src);
    if (!match) {
      return;
    }

    const token = {
      type: 'highlightExtension',
      raw: match[0],
      // documentation had only one param; can be fixed with an empty array
      markText: this.lexer.inlineTokens(match[1], []),
    };
    return token;
  },
  renderer(token) {
    // documentation has only one param for parseInline, too, but TS won't compile and I can't figure
    // out what the second should be
    return `<mark>${this.parser.parseInline(token.markText)}</mark>`;
  },
};
```

**Expected behavior**
I'm not sure if this is a problem with the documentation, with the `@types/marked`, or something else. For the life of me, however, I can't figure out what to use for the second parameter of the `parseInline()` method...

For now, I can skip the inline tokens / parse inline tokens for this particular extension, but for other extensions I want to write I'll definitely need to go a level deeper and parse the content of the text I'm passing through...

**Comment by UziTech** [comment]
The second parameter of `parseInline()` is a renderer. This is so we can pass in a text renderer for some calls.

For both of those calls the second parameter should be optional. This looks like an issue in [@types/marked](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/marked)

**Comment by sernaferna** [comment]
Aha! Confirmed! I hacked the types into my own code instead of importing from `@types/marked` and made the params optional, and it now works.

I'll submit a bit at DefinitelyTyped.

**Comment by sernaferna** [comment]
Not that it matters, but I updated the code above to use `lexer.inline` instead of `lexer.inlineTokens` because of a huge performance boost; wouldn't want anyone to see the code above and do it the "slow" way. 🙂
