### ISSUE TITLE
The base url  should also affect  the image url  for  raw html content in md file

### ISSUE THREAD

**Issue by ychao1983** [markedjs/marked#2553]
**Describe the bug**
The base url  should also affect  the image url  for   native html content in md file

**To Reproduce**
if  this conten  is in md file,  the  base url  will not work,  the  img src will not change.
```
<div align=center>"
<img src="./img/xxx.png" width = "70%" />
</div>
```

**Expected behavior**
I hope the base url also work for  html in md file.

**Comment by UziTech** [comment]
We don't parse raw html so there is no way for marked to know that is a URL.
