### ISSUE TITLE
Type errors when following documented extension usage

### ISSUE THREAD

**Issue by spenserblack** [markedjs/marked#2556]
**Marked version:** 4.0.18
**`@types/marked` version:** 4.0.3

**Describe the bug**
When following the [documented example](https://marked.js.org/using_pro#extensions) for writing an extension, type errors are produced. The return type of `start` *must* be a number, so the maybe-undefined value of `match?.index` causes an error. `this.parser.parseInline` and `this.lexer.inlineTokens` both expect *2* arguments instead of 1, yet it seems that actual behavior does support 1 argument. The type definitions for `RendererExtension` and `TokenizerExtension` probably need to be updated.

**To Reproduce**

1. Install `marked@4.0.18` and `@types/marked@4.0.3`
2. Use a snippet of the documented example, with a bit of modification for type definitions
   ```typescript
   import { marked } from 'marked';

   type Extension = NonNullable<marked.MarkedExtension['extensions']>[number];

   const description: Extension = {
     name: 'description',
     level: 'inline',
     // type error: number | undefined is not assignable to number
     start(src: string) { return src.match(/:/)?.index; },
     tokenizer(src: string) {
       const rule = /^:([^:\n]+):([^:\n]*)(?:\n|$)/;
       const match = rule.exec(src);
       if (match) {
         return {
           type: 'description',
           raw: match[0],
           // expected 2 arguments, got 1
           dt: this.lexer.inlineTokens(match[1].trim()),
           dd: this.lexer.inlineTokens(match[2].trim())
         };
       }
     },
     renderer(token: any) {
       // expected 2 arguments, got 1
       return `\n<dt>${this.parser.parseInline(token.dt)}</dt><dd>${this.parser.parseInline(token.dd)}</dd>`;
     },
     childTokens: ['dt', 'dd'],
   }

   marked.use({ extensions: [description] });
   ```

**Expected behavior**
The documented example should not raise any type errors

******

I'm happy to make a PR to resolve this, but just wanted to get the OK from the markedjs team first.

**Comment by UziTech** [comment]
This is being discussed at https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/61664#discussioncomment-3376571

A PR to update the types would be great 👍

**Comment by spenserblack** [comment]
Thanks for pointing out that discussion! For my specific issue I think only the types themselves need to be updated (e.g. making `RenderThis['parser']` a different type than `Parser`), but I'll try to dig into marked's source code to make sure that's true.

Would it be preferred to resolve this issue by also addressing https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/61664#discussioncomment-3376571, and refactoring marked itself as well?

**Comment by UziTech** [comment]
The marked part already has a PR https://github.com/markedjs/marked/pull/2552

**Comment by spenserblack** [comment]
Looks like a PR for `@types` was made https://github.com/DefinitelyTyped/DefinitelyTyped/pull/61755

**Comment by spenserblack** [comment]
Made https://github.com/DefinitelyTyped/DefinitelyTyped/pull/61791 to update the return type for `extension.start`.

**Comment by spenserblack** [comment]
Those 2 PRs should resolve this, so closing
