### ISSUE TITLE
Content of <script> tags is escaped when they are inside html tags and 'sanitize: false'

### ISSUE THREAD

**Issue by andreyvolokitin** [markedjs/marked#257]
If for example we have this html in our markdown:

``` html
<div>
    <script>if (5 > 4) {}</script>
</div>
```

then content of `<script>` will be escaped. But content remains unescaped if `<script>` is not surrounded with html:

``` html
<script>if (5 > 4) {}</script>
```

If [here](https://github.com/chjj/marked/blob/master/lib/marked.js#L357) we just set `pre: true` then content of `<script>` within html will not be escaped as expected. Is it a bug or a feature, and how can I force marked.js to not escape content of `<script>` within html?

**Comment by pixelkritzel** [comment]
+1

**Comment by pixelkritzel** [comment]
And hopefully I found a solution for my case. I have to see, if there will be some unforseen consequences. But I set the `pedantic` option to true.
