### ISSUE TITLE
a bug when I import katex into the marked using tokenizer

### ISSUE THREAD

**Issue by dongrixinyu** [markedjs/marked#2574]
**Marked version:**
- 4.1.0

**Describe the bug**

I try to import katex into marked using tokenizer extension like this:

```
const katex = require('katex');

const tokenizer = {
    codespan(src: string) {
        const match = src.match(/\$+([^$\n]+?)\$+/);
        let trim_text: string;
        let kx_text: string;

        if (match) {

            console.log('#############');
            console.log(src);
            console.log(match);
            trim_text = match[1].trim();
            console.log(trim_text);

            kx_text = katex.renderToString(trim_text, {
                throwOnError: false,
                displayMode: true
            })
            // console.log(kx_text);
            return {
                type: 'codespan',
                raw: match[0],
                text: kx_text
            };
        }

        // return false to use original codespan tokenizer
        return false;
    }
};

marked.use({ tokenizer });
```
- and my markdown text is like this:
```
- I try to calculate this $c = \pm\sqrt{a^2 + b^2}$ equation but can not get the correct results.

$\large [w_{b1}, w_{b2}, ..., w_{bL}]$

$f\relax{x} = \int_{-\infty}^\infty f\hat\xi\,e^{2 \pi i \xi x}$

```
- in some lines, the latex formula is located in the middle of text. In other lines, the latex formula is located in the beginning of the text.
- But I get the following results:
    - If the formula does not exist in the beginning of one line, then the rendering of marked will be wrong.
![image](https://user-images.githubusercontent.com/27001062/188872261-3f194b3d-a7a3-4b51-a3a0-cb4213d74eae.png)

I find that this tokenizer could only process those text lines match the regular expression from the start.
But I wanna search these info inside text lines like the example above.
So, could you please give an example to show how to render the latex format equation inside texts?

Besides, I also noticed that the `codespan` tokenizer will add `<p>` to the latex text like the example in documentations
![image](https://user-images.githubusercontent.com/27001062/188877433-b70e2bc3-449e-4f4c-b8de-07cd0725a664.png)

- However , I dont want `<p>` tag , only `<code>` would be perfect.

**To Reproduce**

**Expected behavior**

**Comment by dongrixinyu** [comment]
I really appreciated that you help me a lot. Thank you!

**Comment by UziTech** [comment]
Katex has been something people have been asking for for a while so I just created an extension and published it to npm. [marked-katex-extension](https://www.npmjs.com/package/marked-katex-extension)

**Comment by dongrixinyu** [comment]
OK, I stared this repository.
