### ISSUE TITLE
How to avoid 4 spaces being converted into code blocks

### ISSUE THREAD

**Issue by rover95** [markedjs/marked#2575]
I just want to paste plain text code，

 ```
public class Test {
 
   public static void main(String args[]){
      int x = 10;
 
      if( x < 20 ){
         System.out.print(" if ");
      }
   }
}
```

but， parts are converted into code blocks
![image](https://user-images.githubusercontent.com/28331870/189344579-639fd7f3-1efa-4d42-bb6b-c1fcbbe069da.png)

Is there any way I can skip this rule？

**Comment by UziTech** [comment]
You can put it in a code block by putting ` ``` ` around the code:

````
```
public class Test {

  public static void main(String args[]){
     int x = 10;

     if( x < 20 ){
        System.out.print(" if ");
     }
  }
}
```
````

**Comment by rover95** [comment]
> You can put it in a code block by putting `` ``` `` around the code:
> 
> ```
> ```
> public class Test {
> 
>   public static void main(String args[]){
>      int x = 10;
> 
>      if( x < 20 ){
>         System.out.print(" if ");
>      }
>   }
> }
> ```
> ```

but I just want simple text, not code blocks

**Comment by UziTech** [comment]
You can disable the `code` tokenizer. There could be some issues with this since most tokenizers assume more than 3 spaces at the beginning will be a code block.

```js
import {marked} from "marked"

const tokenizer = {
  code() {
    // return undefined to prevent indented code blocks
  }
}
marked.use({tokenizer})

const md = `
public class Test {

  public static void main(String args[]){
     int x = 10;

     if( x < 20 ){
        System.out.print(" if ");
     }
  }
}
`

marked.parse(md)
```

Since that is a fundamental part of markdown the best way to write code is with a fenced code block.
