### ISSUE TITLE
`smartLists` option does not do anything

### ISSUE THREAD

**Issue by Snack-X** [markedjs/marked#2582]
**Marked version:** since v3.0.0

**Describe the bug**
`smartLists` option exists on the documentation, but it actually does nothing.

#2112 removed usage of this option.

**Expected behavior**
Remove references to `smartLists` from code and documentation.

**Comment by UziTech** [comment]
Nice catch! Since it has been gone since v3 and no one has complained I agree that we should just remove it. If you want to create a PR for that it would be very much appreciated 😁👍

**Comment by SSK-14** [comment]
#2594

**Comment by 201B153** [comment]
Can I take it?

**Comment by UziTech** [comment]
@201B153 sounds good
