### ISSUE TITLE
custom pipeline

### ISSUE THREAD

**Issue by UziTech** [markedjs/marked#2595]
> Right now though I'm unsure which `raw` components we'd even want to add up though... because it's not as simple as "ignore the parent, always add up the children" or anything (at a glance), say taking the example:
> 
> ```
> > require('marked').lexer('> I am using marked.')
> [
>   {
>     type: "blockquote",
>     raw: "> I am using marked.",
>     tokens: [
>       {
>         type: "paragraph",
>         raw: "I am using marked.",
>         text: "I am using marked.",
>         tokens: [
>           {
>             type: "text",
>             raw: "I am using marked.",
>             text: "I am using marked."
>           }
>         ]
>       }
>     ]
>   },
>   links: {}
> ]
> ```
> 
> The same content "I am using marked." is repeated 3 times in `raw`... and the top-most node also includes the prefix `"> "` for the block quote... we'd need to know that block quote started at index `0` and that paragraph started at position `2` (or 3, etc, it would depend in the whitespace I imagine)...
> 
> I mean I suppose we could try to write handlers for each type of token on our side... so that we analyze the `>...` prefix ourselves, then increment the index accordingly before we jump into the children... I think I was hoping it might be easier than that... the big benefit would be if we could leverage `marked` with just some very simple glue code. As soon as we have to build a whole in-between analyzer... the benefits start to disappear fast.
> 
> Might be time to dig into the lexer source and poke around.

It's really a problem, and I have no idea how to put the `lex` result back to content, what I am focusing on will only be the parts which are not code, rather than get a result of everything.
Even `lex` can result all information we needed to handle the content, to get the certain part of content, I have to execute the render for many times, it definitely will affect the rendering performance and slow the site.

@UziTech Is there any way we can custom the pipeline like step-by-step process the content? The best will be that we can even custom the jobs order in pipeline:
````
```code```\n\n<!-- commnents --> here\n\n```<!-- commnents -->```\n# <!-- commnents --> in heading `code`\n
marked(content, [
'code',
'custom1',
'heading',
'custom2',
]);
````
1. Code step(Should only use code rules to handling content):
```
<pre><code>code</pre></code>\n\n<!-- commnents --> here\n\n<pre></code><!-- commnents --><pre></code>\n# <!-- commnents --> in heading <code>code</code>\n
```
2. custom parser – Comment Replacer
(can use Marked's render or render content as you wish)

```
// Replace '<!-- custom commnents -->' into 'text'(ignore the code block):
<pre><code>code</pre></code>\n\ntext here\n\n<pre></code><!-- commnents --><pre></code>\n# text in heading <code>code</code>\n
```
4. heading step
```
<pre><code>code</pre></code>\n\ntext here\n\n<pre></code><!-- commnents --><pre></code>\n<h1>text in heading <code>code</code></h1>\n
```
5. custom parser – Add links to heading
```
<pre><code>code</pre></code>\n\ntext here\n\n<pre></code><!-- commnents --><pre></code>\n<h1 href='#text-1024'>text in heading <code>code</code></h1>\n
```
6. return result

I don't think I need to open a new issue for what I said about, if you pefer me to do that, let me know.

_Originally posted by @scruel in https://github.com/markedjs/marked/issues/2443#issuecomment-1259037699_

**Comment by UziTech** [comment]
@scruel I moved the question to a new issue so we don't take over the other thread.

The marked lexer works by consuming tokens in the beginning of the source. I think what you are proposing would require rewriting the lexer and parser.

**Comment by scruel** [comment]
> @scruel I moved the question to a new issue so we don't take over the other thread.
> 
> The marked lexer works by consuming tokens in the beginning of the source. I think what you are proposing would require rewriting the lexer and parser.

Ok, I reviewed some code of your project, what you said is correct, and I think it won't be such easy, thanks for your reply.

**Comment by scruel** [comment]
Fixed some typo, you can copy&paste the content again, sorry for the inconvenience caused :)

**Comment by scruel** [comment]
Corrected some typos, you can copy&paste the content again, sorry for the inconvenience caused :)
