### ISSUE TITLE
Can't use extensions from CLI

### ISSUE THREAD

**Issue by abdullahkhalids** [markedjs/marked#2617]
**Describe the feature**
I would like the ability to use extensions from the CLI version of the marked. It might already be possible, but there is no documentation to this effect in the CLI help.

**Why is this feature necessary?**
Extensions can be used in the other ways of calling marked. They should also be usable from the CLI.

**Describe alternatives you've considered**
N/A

**Comment by abdullahkhalids** [comment]
My particular use case is that I am developing on python. While, I could conceivably create a boiler plate script to run node and then call it from python, it would be much easier to just call the marked cli in a line and be done with it.

But I understand if this is low priority. Thanks in any case.

**Comment by UziTech** [comment]
Considering that you would have to write the extensions in nodejs anyway I don't think it would be much harder to just do it programmatically. I think it would be too much to maintain to send npm packages to the cli and have it try to download and import them correctly in every situation.

**Comment by abdullahkhalids** [comment]
Thanks
