### ISSUE TITLE
no line of table

### ISSUE THREAD

**Issue by sofencyXiao** [markedjs/marked#2633]
**Marked version:**
/**
 * marked - a markdown parser
 * Copyright (c) 2011-2022, Christopher Jeffrey. (MIT Licensed)
 * https://github.com/markedjs/marked
 */
no version
**Describe the bug**
<img width="367" alt="image" src="https://user-images.githubusercontent.com/48281891/198942027-7d13e615-e465-4f17-b09e-b87fc120f9c6.png">
 no line of table

**Comment by UziTech** [comment]
marked does not provide css only html. You will have to provide your own css to add table cell borders.

**Comment by sofencyXiao** [comment]
thanks

**Comment by reza-ebrahimi** [comment]
@sofencyXiao Check out this [demo](https://marked.js.org/demo/?text=%3Cstyle%3E%0Atable%20%7B%0A%20%20border-collapse%3A%20collapse%3B%0A%7D%0Ath%2C%20td%20%7B%0A%20%20border%3A%201px%20solid%20%23000%3B%0A%20%20padding%3A%205px%3B%0A%7D%0A%3C%2Fstyle%3E%0A%0A%7C%20Month%20%20%20%20%7C%20Savings%20%7C%0A%7C%20--------%20%7C%20-------%20%7C%0A%7C%20January%20%20%7C%20%24250%20%20%20%20%7C%0A%7C%20February%20%7C%20%2480%20%20%20%20%20%7C%0A%7C%20March%20%20%20%20%7C%20%24420%20%20%20%20%7C&options=%7B%0A%20%22async%22%3A%20false%2C%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22extensions%22%3A%20null%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22hooks%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master).
