### ISSUE TITLE
Parser.parse extension to be able to change tokens as a whole

### ISSUE THREAD

**Issue by kapouer** [markedjs/marked#2639]
**Describe the feature**
Ability to get the "root" tokens list before rendering - either through a Parser.parse extension, or another mecanism.

**Why is this feature necessary?**
I need my extension to be able to prepend a default (depth 1) heading token when one is missing.

**Describe alternatives you've considered**
```js
const defaultParse = Parser.parse;
Parser.parse = (tokens, options) => {
	const [{ type, depth }] = tokens;
	if (type != "heading" || depth != 1) {
		tokens.unshift({
			type: 'heading',
			depth: 1,
			tokens: []
		});
	}
	return defaultParse.call(Parser, tokens, options);
};
```
but i hate monkey-patching.

**Comment by calculuschild** [comment]
The [walkTokens](https://marked.js.org/using_pro#walk-tokens) function might be what you are looking for. It lets you modify the token tree before being sent to the final HTML renderer.

**Comment by kapouer** [comment]
Yes, but (unless I'm mistaken) it's not possible to know if the token is the first token of the document.
I tried setting a flag, but that fails when using marked as a library.

**Comment by UziTech** [comment]
If all you need are the root tokens you can get the array from `marked.lexer`

```js
const tokens = marked.lexer(markdown, options);
const [{ type, depth }] = tokens;
if (type != "heading" || depth != 1) {
  tokens.unshift({
    type: 'heading',
    depth: 1,
    tokens: []
  });
}
marked.parser(tokens, options);
```

There isn't currently an easy way to make this into an extension. For that we may need to implement [hooks](https://github.com/markedjs/marked/pull/1878).
