### ISSUE TITLE
Pass token to renderer methods ?

### ISSUE THREAD

**Issue by kapouer** [markedjs/marked#2640]
**Describe the feature**
Currently renderer methods get arguments cooked by marked ~Renderer~ Parser, as in `code(code, infostring, escaped)`.
On the other hand, extensions rendered methods get a `token` parameter with all its properties.
I request that all renderer methods get a token.

**Why is this feature necessary?**
For example this.renderer.list won't know if the list is loose.

**Describe alternatives you've considered**
I could have asked for this.renderer.list to get a `(body, ordered, start, loose)` signature.
But passing the token around systematically seems to be much simpler.

**Comment by UziTech** [comment]
I would love this. It would make certain things so much easier. Unfortunately this would be a huge breaking change to most marked renderers. If we could do this in a way that would allow the tokens and deprecate the old way first I would be on board.

**Comment by kapouer** [comment]
Ideas, in my order of preference:
1. "opt-in" with a `legacyRenderer: true` flag
2. `this.renderer.token = token` before each call (considering that renderers are sync functions)
3. add a extensions.renderer catch-all method

**Comment by calculuschild** [comment]
@UziTech Is this something we can add along with #2805 for the next major version?

**Comment by UziTech** [comment]
Ya this would be nice
