### ISSUE TITLE
Encouraging a plugins ecosystem

### ISSUE THREAD

**Issue by simonhaenisch** [markedjs/marked#2642]
**What pain point are you perceiving?**

I can't find any published plugins/extensions.

**Describe the solution you'd like**

I believe there's a somewhat unspoken norm about authoring plugins for tooling in the Node.js ecosystem by following a `<tool>-plugin-<plugin-name>` naming scheme. IMO it would be great to see the same for `marked` as well!

The main "solution" for me would be to add a guide to either https://marked.js.org/using_pro#extensions or https://marked.js.org/contributing, or maybe a new "Plugins" section, with some instructions for:

- Authoring plugins (how to name the package, which tags to add, how to export)
- Using plugins (kinda there already but just an example of an imported plugin instead of a custom extension)
- List of existing (curated) plugins (once there are some, unless I just couldn't find them?)

Bonus: auto-loading of plugins that use the `marked-plugin-` prefix 🤓  (not sure about this but with Prettier it's pretty nice)

**Additional info**

I'm the maintainer of [md-to-pdf](https://github.com/simonhaenisch/md-to-pdf) which uses Marked, and I have two plugin ideas already (`marked-plugin-highlightjs` and `marked-plugin-emoji`) that I and someone else already have the code for, so this space wouldn't start completely empty.

I'm also willing to write up a PR for the documentation, but I would definitely want some feedback from the maintainers first whether this aligns with Marked's roadmap? I think it definitely aligns with the "open/closed" design principle:

https://github.com/markedjs/marked/blob/48e28e7c4a9ca2e14e16d3770d55cdb7c49b22f1/docs/CONTRIBUTING.md?plain=1#L18

**Comment by UziTech** [comment]
There is a [Known Extensions](https://marked.js.org/using_advanced#extensions) list in the docs. There is also [List of Tools Using Marked](https://marked.js.org/#tools)

**Comment by simonhaenisch** [comment]
Oh ok, somehow I completely missed this section 🙈 🙏 Maybe having this list under "Extensibility" (right under "marked.use()") makes more sense? Anyway, I still think there could be a whole "Plugins" chapter to encourage publishing extensions as packages (with some guidelines), and moving the sections "Extensibility > Custom Extensions" and "Advanced Usage > Known Extensions" there?

**Comment by UziTech** [comment]
I don't think we should move around the headings too much so we don't have broken links, but we could add a note below the marked.use senction pointing to the list of extensions.
