### ISSUE TITLE
Wrong parser data for auto links with ampersand

### ISSUE THREAD

**Issue by vdebergue** [markedjs/marked#2648]
**Marked version:** 4.2.2

**Describe the bug**
Auto links containing ampersand: `&` will produce wrong lexer data: href contains an escaped `&`

**To Reproduce**

[See example](https://marked.js.org/demo/?outputType=lexer&text=http%3A%2F%2Fexample.com%2F%3Ffoo%3D1%26bar%3D2%0A%0A%5Bfoo%5D%28http%3A%2F%2Fexample.com%2F%3Ffoo%3D1%26bar%3D2%29%0A%0A&options=%7B%0A+%22async%22%3A+false%2C%0A+%22baseUrl%22%3A+null%2C%0A+%22breaks%22%3A+false%2C%0A+%22extensions%22%3A+null%2C%0A+%22gfm%22%3A+true%2C%0A+%22headerIds%22%3A+true%2C%0A+%22headerPrefix%22%3A+%22%22%2C%0A+%22highlight%22%3A+null%2C%0A+%22langPrefix%22%3A+%22language-%22%2C%0A+%22mangle%22%3A+true%2C%0A+%22pedantic%22%3A+false%2C%0A+%22sanitize%22%3A+false%2C%0A+%22sanitizer%22%3A+null%2C%0A+%22silent%22%3A+false%2C%0A+%22smartypants%22%3A+false%2C%0A+%22tokenizer%22%3A+null%2C%0A+%22walkTokens%22%3A+null%2C%0A+%22xhtml%22%3A+false%0A%7D&version=4.2.2)

- compare the href in the lexer data from the autolink => `http://example.com/?foo=1&amp;bar=2`
- to the other link => `http://example.com/?foo=1&bar=2`
- (in the preview, the link is correct despite the extra `amp;`)

**Expected behavior**

Lexer data for the first link should get a `href` value to `http://example.com/?foo=1&bar=2`

**Comment by UziTech** [comment]
Marked seems to follow [CommonMark](https://spec.commonmark.org/dingus/?text=http%3A%2F%2Fexample.com%2F%3Ffoo%3D1%26bar%3D2%0A%0A%5Bfoo%5D(http%3A%2F%2Fexample.com%2F%3Ffoo%3D1%26bar%3D2)%0A%0A) on this so I think this is working as intended.
