### ISSUE TITLE
Opening Chat Archives: Uncaught TypeError:Failed to Execute

### ISSUE THREAD

**Issue by GCSmith-07** [markedjs/marked#2653]
Uncaught TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
[Detected 3 packages: plutonium, lib-wrapper, df-chat-enhance]
    at DFChatArchiveViewer.bringToTop (foundry.js:5443:36)
    at 🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:507:22)
    at DFChatArchiveViewer._lw_Application_prototype_bringToTop (PopoutSheet.js:28:15)
    at 🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:616:16)
    at 🎁Application.prototype.bringToTop#0 (libWrapper-wrapper.js:189:20)
    at HTMLAnchorElement.<anonymous> (DFChatArchiveManager.ts:43:46)
    at HTMLAnchorElement.dispatch (jquery.min.js:2:43064)
    at y.handle (jquery.min.js:2:41048)

**Comment by UziTech** [comment]
This doesn't seems to be an error in marked. We don't call getComputedStyle.

**Comment by GCSmith-07** [comment]
> This doesn't seems to be an error in marked. We don't call getComputedStyle

Could you tell me based off that console output what would be so I can look into getting it fixed?

**Comment by UziTech** [comment]
> Could you tell me based off that console output what would be so I can look into getting it fixed?

Not without more info about what the code was that was running at the time. All I know from that error is that it "Failed to execute 'getComputedStyle' on 'Window'".

**Comment by GCSmith-07** [comment]
> > Could you tell me based off that console output what would be so I can look into getting it fixed?
> 
> Not without more info about what the code was that was running at the time. All I know from that error is that it "Failed to execute 'getComputedStyle' on 'Window'" because "parameter 1 is not of type 'Element'".

Here is the full error log I get
![image](https://user-images.githubusercontent.com/100705086/201506291-70126743-471f-4521-956c-cc2576f9d126.png)

![image](https://user-images.githubusercontent.com/100705086/201506300-7e16e886-bf53-4fe9-adf6-4d7322dd2938.png)

**Comment by UziTech** [comment]
That doesn't help much. If you have a way I can reproduce the error I can help. Is there a website I can go to to see the error? or a set of steps to take to see the error?

Just curious, what made you think this was an issue with marked?

**Comment by GCSmith-07** [comment]
> That doesn't help much. If you have a way I can reproduce the error I can help. Is there a website I can go to to see the error? or a set of steps to take to see the error?
> 
> Just curious, what made you think this was an issue with marked?

I must have posted this on the wrong thread. So sorry to waste your time. Mistake on my end.
