### ISSUE TITLE
Feature request: Table column width

### ISSUE THREAD

**Issue by iegik** [markedjs/marked#266]
So, we have columns, for example:

```
| Some | text | and number
| ---- | -------- | ----
| some | long text | 1
| awesome | another text | 1
```

| Some | text | and number |
| --- | --- | --- |
| some | long text | 1 |
| awesome | another text | 1 |

Now, I need, that second column will be larger and last - smaller. Obviously, that we look at line that goes after headers: if shorter stroke - shorter column.

Solution:
So, count the dashes (with space and column separator) and use percentage width's by the ratio!
For example `table { width:100%;}` (Total: 24chars), `<th style="width:29.17%">` (first column - 7chars),  `<th style="width:45.83%">` (second column - 11chars),  and leve last without width's. http://jsfiddle.net/iegik/3D2Fb/

**Comment by crifan** [comment]
+1 expect can designated table column width, by dash count or something else

**Comment by joshbruce** [comment]
I'm with @kuba-kubula on this one, I think - also @ghost before deleting the first line.

1. Want to keep Marked light and out of the "template engine" business; adding attributes to the markup feel more like template engine (or CSS) business. (I don't know of a Markdown spec that allows for sizing of table columns.)
2. From a UX perspective mobile becomes an interesting problem space - especially if we're using percentages.
3. @jondlm also raises a good point regarding making an extension or override to handle the use case as it's not really markdown in the strictest sense. (Column spanning might be something worth pursuing - don't remember if the Multi-Markdown or CommonMark specs cover that.)

Going to leave this and PR open for now, but not feeling this as being a problem space to pursue solving with Marked (see #956).

**Comment by UziTech** [comment]
This is not part of any spec so it will have to be an extension

**Comment by maor-rosenfeld** [comment]
For anyone facing this issue, just use a &nbsp-s (non breaking space) to extend the header of the column you want to make wider. You can copy it from here: " ".

**Comment by iegik** [comment]
What if i want make short column, where header is wider?

| I want make this column with that long text in header shorter then next column | Long column &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; |
| - | - |
| 1 | 2 |

**Comment by maor-rosenfeld** [comment]
You can add nbsps to the other columns, that's all I've got.

| I want make this column with that long text in header shorter then next column |                                                                                         Long column                                                                          
|--|--|
| 1 | 2 |

**Comment by ZHUI** [comment]
> You can add nbsps to the other columns, that's all I've got.
> 
> I want make this column with that long text in header shorter then next column	                                                         Long column                                                                          
> 1	2

can you give some example source code,  that fix the width table in the github readme.md or just like you replied in this issue

<img width="902" alt="image" src="https://user-images.githubusercontent.com/16911935/187375065-9dcf7762-0ab1-4a14-a79d-895f6bac2b98.png">

**Comment by jdgamble555** [comment]
For me I was able to get around this by adding:
```html
| <div style="width:150px" /> Header Text | Some other header longer |
```
to the header column. I didn't put the div around the text, because for my app the SSR to Client hydration would rehydrate the inner text twice.  This did the trick though.

J
