### ISSUE TITLE
Pandoc css markup

### ISSUE THREAD

**Issue by BeeFox-sys** [markedjs/marked#2664]
**Describe the feature**
I would like a config option that allows for pandoc style css; for example 
```
[This is red,]{.red} [and this is blue!]{#blue}
```
would generate
```
<span class="red">This is red,</span> <span id="blue">and this is blue!</span>
```

**Why is this feature necessary?**
Pandoc's css markdown is really nice to use and allows you to focus on content rather then code when writing markdown

**Describe alternatives you've considered**
I presume a way to implement this via the tokeniser would be possible but i am not sure how to do that, and having it built in would be nice

**Comment by UziTech** [comment]
Is there a link to a spec for pandoc css so someone can know if it is working how it is supposed to?

**Comment by UziTech** [comment]
Looks like this custom extension should work. It probably won't catch all of the edge cases but it should be easy to change to get it to work.

```js
import { marked } from 'marked';

const pandoc = {
  extensions: [{
    name: 'pandoc',
    level: 'inline',
    start: (src) => src.indexOf('['),
    tokenizer(src) {
      const match = /^\[(.+?)\]\{([.#]\w+)\}/.exec(src);

      if (!match) return;

      const attrType = match[2].substring(0, 1);
      const attrValue = match[2].substring(1);

      return {
        type: 'pandoc',
        raw: match[0],
        text: match[1],
        attrName: attrType === '.' ? 'class' : 'id',
        attrValue,
        tokens: this.lexer.inline(match[1])
      };
    },
    renderer(token) {
      return `<span ${token.attrName}="${token.attrValue}">${this.parser.parseInline(token.tokens)}</span>`;
    }
}]
};

const md = '[This is red,]{.red} [and this is blue!]{#blue}';

marked.use(pandoc);

console.log(marked.parse(md));
// <p><span class="red">This is red,</span> <span id="blue">and this is blue!</span></p>
```

**Comment by BeeFox-sys** [comment]
there's a bunch of stuff in this; but mainly im looking at the attribute stuff. basically you can attach {.class #id attr=example} to the end of an element, be that a fenced codeblock, a heading, an image, etc etc. (the [example]{.class} shows how to do it to a span of text), and it will attach those attributes/class/id to the element when creating the html
https://garrettgman.github.io/rmarkdown/authoring_pandoc_markdown.html

**Comment by UziTech** [comment]
Looks like a full extension would take a lot more work but it should be possible with a custom extension.

**Comment by BeeFox-sys** [comment]
```js
const pandoc = {
    extensions: [{
      name: 'pandoc',
      level: 'inline',
      start: (src) => src.indexOf('['),
      tokenizer(src) {
        const match = /^\[(?<text>.+?)\]\{(?<attr>.*)\}/.exec(src);
  
        if (!match) return;
  
        const attrMatch = /[.#][a-z\-0-9]*|[a-z\-0-9]*="[a-z\-0-9]*"/g

        let classes = []
        let ids = []
        let attrs = []

        match.groups.attr.match(attrMatch).forEach((str)=>{
            const attrType = str.substring(0, 1);
            switch (attrType){
                case ".": 
                    classes.push(str.substring(1));
                    break;
                case "#":
                    ids.push(str.substring(1));
                    break;
                default:
                    attrs.push(str)
            }
        })

        return {
          type: 'pandoc',
          raw: match[0],
          text: match[1],
          classes, ids, attrs,
          tokens: this.lexer.inline(match[1])
        };
      },
      renderer(token) {
        return `<span ${token.classes.length ? "class="+token.classes.join(" "):""} ${token.ids.length ? "id="+token.ids.join(" "):""} ${token.attrs.join(" ")}>${this.parser.parseInline(token.tokens)}</span>`;
      }
  }]
};
```

just adding this here for anyone who comes looking, this is much closer to pandocs useage as it allows for multiple things in the attributes. I am now working on getting it to know it is by another token but that is yet to come.
