### ISSUE TITLE
Discrepancy between custom extensions and `marked.use()` docs

### ISSUE THREAD

**Issue by simonhaenisch** [markedjs/marked#2669]
In the [known extensions](https://marked.js.org/using_advanced#extensions) docs, there's a list of extensions and an instruction to use them via `marked.use(extension)`. However, I looked at the source of some of them, and it looks like they do not export a Marked extension but a Tokenizer or Renderer extension. This is also how it's stated to be done in the [custom extensions](https://marked.js.org/using_pro#extensions) docs.

Therefore I think the instruction should be to use them as `marked.use({ extensions: [/* ... */] })` instead.

BTW I find it very confusing that there's this naming ambiguity for the word "extension". The differentiation is vague in the docs, the only thing I could find about the difference of `marked.use({ renderer })` vs `marked.use({ extensions: [{ renderer }] })` is that the latter runs the extension renderer as a preprocessing, whereas the former one merges with the existing renderer (?)

Would be nice if the extensions API gets a bit more straightforward (:

**Comment by UziTech** [comment]
`marked.use({ extensions: [/* ... */] })` is for adding custom tokenizers and renderers. If you are changing existing tokenizers/renderers you don't need to put them in the extensions array.

I agree it would be nice to have a unified way to do things. The reason there is two ways for existing tokenizers is so we don't break older extensions.

It would be very helpful if you would create a PR with the changes to the document that you would like to see.

**Comment by AdditionAddict** [comment]
Read and reread the docs and I'm still lost on this point. Great library but this is a pain point

**Comment by calculuschild** [comment]
> I agree it would be nice to have a unified way to do things. The reason there is two ways for existing tokenizers is so we don't break older extensions.

Perhaps unifying this could be a target for v6.0.0

**Comment by UziTech** [comment]
I don't know if there is really anything to unify. This is more of a documentation issue.
- `marked.use({renderer})` is for changing existing renderers.
- `marked.use({extensions: [{renderer}]})` is for adding new renderers.

I think we just need to make it clear in the documentation that even though they use the same word they are different.

**Comment by aaronsolomon98** [comment]
Hello @UziTech! I'm looking to make my first open source contribution and was wondering if there's still a need to update the [render option documentation](https://github.com/markedjs/marked/blob/master/docs/USING_PRO.md#the-renderer--renderer)? If so I can create a PR.

**Comment by UziTech** [comment]
@aaronsolomon98 ya it would be great if you could update the docs.

**Comment by simonhaenisch** [comment]
Just a few thoughts while reading through the thread again...

> * `marked.use({renderer})` is for changing existing renderers.
> * `marked.use({extensions: [{renderer}]})` is for adding new renderers.

Looking at the example in https://marked.js.org/using_pro#renderer, let's say I have this renderer:

```ts
const renderer = {
  link(string href, string title, string text) { /* ... */ }
}
```

From my understanding, if I do `marked.use({ renderer })`, I overwrite the `link` method of the default renderer. If I do `extensions: [{ renderer }]`, my renderer gets executed first, meaning the default renderer won't have any links to process anymore? So the result will be the same.

> The reason there is two ways for existing tokenizers is so we don't break older extensions.

Would you say one way is recommended over the other? If so, maybe we should note that in the docs, and could even think about saying the other one is deprecated?

**Comment by UziTech** [comment]
With that renderer object `marked.use({ extensions: [{ renderer }] })` wouldn't work.

It would need to be

```js
marked.use({
 extensions: [{
    name: 'link',
    renderer(token) {
      return /* ... */
    }
  }]
})
```

Which is technically creating a new renderer for the link token, not over writing the existing one. For example returning false in the extension renderer wouldn't fall back to the original renderer.
