### ISSUE TITLE
Ignore whitespaces between delimiters

### ISSUE THREAD

**Issue by Tigriz** [markedjs/marked#2680]
Related is #1597

In my use case, users tend to add spaces after opening or before closing delimiters and it doesn't render which can be bothering for them to check.
Is there a way to make Marked render them even if whitespaces are present? Or add an option to do it?

**Comment by UziTech** [comment]
You can create a [custom extension](https://marked.js.org/using_pro#extensions) to change the tokenizer.

```js
const descriptionList = {
  name: 'emStrong',
  level: 'inline',
  start(src) { return src.match(/[*_]/)?.index; },
  tokenizer(src) {
    // change tokenizer to allow space.
  }
};
```
