### ISSUE TITLE
code {{var}} will be replace with '', how to solve it.

### ISSUE THREAD

**Issue by yihchu** [markedjs/marked#2682]
**Describe the feature**
A code:
```
{
    "key": "{{val}}"
}
```
it will be converted to
{
"key": ""
}
**Why is this feature necessary?**
I want to know how to avoid to replace {{}}. and have you provided a way to stop it ?

**Describe alternatives you've considered**

**Comment by UziTech** [comment]
If you put it in a code block marked won't change it. [demo](https://marked.js.org/demo/?text=%60%60%60%0A%7B%0A%20%20%20%20%22key%22%3A%20%22%7B%7Bval%7D%7D%22%0A%7D%0A%60%60%60&options=%7B%0A%20%22async%22%3A%20false%2C%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22extensions%22%3A%20null%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master)

Could you provide some code on how you are calling marked?
