### ISSUE TITLE
URI is stripped from baseUrl with URI

### ISSUE THREAD

**Issue by webketje** [markedjs/marked#2691]
**Marked version:** 4.2.4

**Describe the bug**
The URI in a baseUrl with a URI part (eg `'https://root.domain/subsite'`) is stripped from links resulting in incorrect links. This is an important use case where a static site deploy is done in a subfolder of the root domain (or remapped with server software/ front-end history API).

**To Reproduce**
Run marked with `baseUrl: 'https://root.domain/subsite'`. The expected output of a markdown string `'[First post](posts/first/)'` is `<a href="https://root.domain/subsite/posts/first/">First post</a>`  but instead marked outputs `<a href="https://root.domain/posts/first/">First post</a>` *(without the URI given in the baseUrl option: subsite)*.

Demo:
[Marked Demo](https://marked.js.org/demo/?outputType=html&text=%5BFirst%20post%5D(%2Ffirst%2Fpost%2F)%20%20%0A%5BFirst%20post%5D(.%2Ffirst%2Fpost)%20%20%0A%5BFirst%20post%5D(first%2Fpost)&options=%7B%0A%20%22async%22%3A%20false%2C%0A%20%22baseUrl%22%3A%20%22https%3A%2F%2Froot.domain%2Fsubsite%22%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22extensions%22%3A%20null%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master)

**Expected behavior**
The expected output of a markdown string `'[First post](posts/first/)'` is `<a href="https://root.domain/subsite/posts/first/">First post</a>`  The expectation applies to all link notations whether relative (`posts/first/`), explicitly relative (`./posts/first/`), or root-relative (`/posts/first`)

**Comment by UziTech** [comment]
If you end the `baseUrl` with a slash it works as expected [demo](https://marked.js.org/demo/?outputType=html&text=%5BFirst%20post%5D(%2Ffirst%2Fpost%2F)%20%20%0A%5BFirst%20post%5D(.%2Ffirst%2Fpost)%20%20%0A%5BFirst%20post%5D(first%2Fpost)&options=%7B%0A%20%22async%22%3A%20false%2C%0A%20%22baseUrl%22%3A%20%22https%3A%2F%2Froot.domain%2Fsubsite%2F%22%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22extensions%22%3A%20null%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master)

see https://github.com/markedjs/marked/issues/1541#issuecomment-525397937
