### ISSUE TITLE
Confused by gfm emoji syntax not rendered as character

### ISSUE THREAD

**Issue by crystalfp** [markedjs/marked#2692]
**Marked version:**
4.2.4

**Describe the bug**
Using GFM syntax for emoji (like `:warning:`). I expect marked convert it to the corresponding character ⚠️. Instead the syntax is passed to output untouched.

**To Reproduce**
Run the following code:
```javascript
const marked = require("marked")
const md = "Warning :warning: here"
console.log(marked.parse(md, {smartypants: true, gfm: true}));
```
The output is:
```html
<p>Warning :warning: here</p>
```

**Expected behavior**
I think the output should be:
```html
<p>Warning ⚠️ here</p>
```
Confused.

**Comment by UziTech** [comment]
It isn't in the [GFM spec](https://github.github.com/gfm/). If you would like to create an [extension](https://marked.js.org/using_pro#extensions) that does that people could use it in marked.

**Comment by crystalfp** [comment]
You are right, it is not in the specs. Anyway, thanks for the suggestion. If someone is interested, here is my solution, for now with only two emoji defined:
```
// This table should be enlarged, and a way to have the user add entries should be added
emojiTable = new Map([
	["warning", "⚠"],
	["sad", "😩"]
]);

// The extension
const emoji = {
  name: 'emoji',
  level: 'inline', 
  start(src) { return src.match(/:/)?.index; },
  tokenizer(src, tokens) {
    const rule = /^:([^: \n]+):/;
    const match = rule.exec(src);
    if(match) {
      return {                  // Token to generate
        type: 'emoji',          // Should match "name" above
        raw: match[0],          // Text to consume from the source
        name: match[1].trim(),  // The emoji name
      };
    }
  },
  renderer(token) {
    return emojiTable.get(token.name) ?? `:${token.name}:`;
  }
};

// Load the extension
marked.use({extensions: [emoji]});

// Test it
console.log(marked.parse('Beware :warning: otherwise you will be :sad:'));
```

**Comment by UziTech** [comment]
I created [marked-emoji](https://www.npmjs.com/package/marked-emoji) so people can easily install it.
