### ISSUE TITLE
[Marked CLI] ^C causes manpage error

### ISSUE THREAD

**Issue by LeoDog896** [markedjs/marked#2706]
**Marked version:**
`master` branch. Tested on commit [`d28cc87`](https://github.com/markedjs/marked/commit/d28cc87da7fede45a3925f6ba42b19cd82041713), but is also reproducible on the stable `4.2.5` version.

**Describe the bug**
The CTRL + C signal is never sent to the `man` command, causing the following error:

```
OAman: command exited with status 1: sed -e '/^[[:space:]]*$/{ N; /^[[:space:]]*\n[[:space:]]*$/D; }' | LESS=-ix8RmPm Manual page marked\.1 ?ltline %lt?L/%L.:byte %bB?s/%s..?e (END):?pB %pB\%.. (press h for help or q to quit)$PM Manual page marked\.1 ?ltline %lt?L/%L.:byte %bB?s/%s..?e (END):?pB %pB\%.. (press h for help or q to quit)$ MAN_PN=marked\.1 pager

bash: OA: command not found
```

**To Reproduce**
Run `marked --help`, and once the manpage opens, press CTRL + C (^C).

**Expected behavior**
Marked CLI should either:
- Let `man` handle SIGINT (tested locally, if it does this then it safely exits without a newline printed)
- Don't accept SIGINT at all (man pages are *supposed* to not exit when a SIGINT signal is sent whatsoever.)

By the way, I'm fully open to fixing it, but I'm unsure about which one of the two behaviors above (or some other behavior) would be preferred.

**Comment by UziTech** [comment]
I'm ok with either. Option 1 sounds right to me. Where did you get the information that `man pages are supposed to not exit when a SIGINT signal is sent whatsoever.`?

**Comment by LeoDog896** [comment]
I actually don't know where I got that from [(unixexchange question)](https://unix.stackexchange.com/questions/731422/why-does-the-man-command-not-handle-sigint-or-sigquit?noredirect=1#comment1387670_731422), but the `man` command uses `less` in the background, which requires an explicit flag to listen to `CTRL + C`: [`--quit-on-intr`](https://manpages.debian.org/stretch/less/less.1.en.html)
