### ISSUE TITLE
Support for sub- & superscript, without using html tags

### ISSUE THREAD

**Issue by PeterHagen** [markedjs/marked#2709]
**Describe the feature**
Currently marked.js doesn't seem to have support for sub- & superscript, without using html tags. This would be possible by using `E=MC^2^` and `log 2~a~` as examples

**Why is this feature necessary?**
It would compliment the overal usability of marked.js, which would make reading and writing the markdown much cleaner instead of using html in the text.

**Describe alternatives you've considered**
As described on [subscript-in-markdown](https://www.javatpoint.com/subscript-in-markdown), and I'm not sure if this is documented anywhere else, using `E=MC^2^` would result in superscript, while `log 2~a~` would result in subscript. Unfortunately, GitHub also doesn't support it.

**Comment by UziTech** [comment]
Also `~this is strike through~`

~this is strike through~

So which one would override the other for GitHub?

**Comment by PeterHagen** [comment]
The subscript method should not allow spaces in the text and I guess it’s only valid when written against a character or word. Something like `CO~2~`. In some markdown parsers, strike through requires 2 ~ I noticed.

**Comment by UziTech** [comment]
You could create an extension for these something like:

```js
// superscript.js
export default {
  name: 'superscript',
  level: 'inline',
  start(src) { return src.indexOf('^'); },
  tokenizer(src) {
    const match = src.match(/^\^(\w+)\^/);

    if (!match) {
      return;
    }

    return {
      type: 'superscript',
      raw: match[0],
      text: match[1]
    };
  },
  renderer(token) {
    return `<sup>${token.text}</sup>`;
  }
};
```

```js
// subscript.js
export default {
  name: 'subscript',
  level: 'inline',
  start(src) { return src.indexOf('~'); },
  tokenizer(src) {
    const match = src.match(/^~(\w+)~/);

    if (!match) {
      return;
    }

    return {
      type: 'subscript',
      raw: match[0],
      text: match[1]
    };
  },
  renderer(token) {
    return `<sub>${token.text}</sub>`;
  }
};
```

```js
import superscript from './superscript.js';
import subscript from './subscript.js';
import { marked } from 'marked';

marked.use({
  extensions: [
    superscript,
    subscript
  ]
};

console.log(marked.parse('test^superscript^ test~subscript~'));
// <p>test<sup>superscript</sup> test<sub>subscript</sub></p>
```
