### ISSUE TITLE
Not properly parsing new line character

### ISSUE THREAD

**Issue by PaulDotSH** [markedjs/marked#2715]
**Marked version:** Latest from CDN
**Markdown flavor:** Browser

## Expectation
Marked properly parsing text.
## Result
Marked not outputing new lines as <br> or as a new line in the p tag
## What was attempted
```
# This
## Is
### A
#### Test
foobar
#foo
bar
```

![image](https://user-images.githubusercontent.com/84643540/212931890-bd1f7b97-ad76-42cf-a1af-cedb1f8638cd.png)

**Comment by UziTech** [comment]
That is actually exactly how it is supposed to work according to the commonmark spec. [demo](https://spec.commonmark.org/dingus/?text=%23%20This%0A%23%23%20Is%0A%23%23%23%20A%0A%23%23%23%23%20Test%0Afoobar%0A%23foo%0Abar)
