### ISSUE TITLE
Does Marked support ESM browser module imports?

### ISSUE THREAD

**Issue by jessejohnson** [markedjs/marked#2719]
There doesn't seem to be any documentation for this, as the official docs [here](https://marked.js.org/#installation) only show to import with NPM: `npm install marked`

**Comment by UziTech** [comment]
Yes, you can use a cdn to load marked's esm build.

```html
<script src="https://cdn.jsdelivr.net/npm/marked/lib/marked.esm.js" type="module"></script>
```

**Comment by theVJagrawal** [comment]
Can I work on this one? I am pretty new to this

**Comment by UziTech** [comment]
@theVJagrawal sounds good

**Comment by jorjun** [comment]
This package refuses to work under deno deploy the error: The deployment failed: npm: specifiers are not yet supported on Deno Deploy

**Comment by UziTech** [comment]
@jorjun I have not used deno yet but I don't think it would be too hard to get it to work. If you could try to get it working and create a PR with any changes needed, that would be much appreciated.

**Comment by jorjun** [comment]
I'm only busy at the app level, and found an alternative, almost drop-in which got me moving again.

If I do get into this Deno compatibility arena and can help this project, will assist. Thanks for communication.
