### ISSUE TITLE
Marked escapes HTML characters by  code fence content

### ISSUE THREAD

**Issue by cike09** [markedjs/marked#2727]
**Marked version:**
current
**Describe the bug**
Marked escapes HTML characters by  code fence content

**To Reproduce**
marked.parse(' 
```
#Lamabda expression
(name)=>{ print(name)} 
```
'); 

becomes (name)=&gt;{ print(name)} 

Expected behavior
Ideally the code fence content is not escaped from the output ,but displayed as the correct letters i.e. (name)=>{ print(name)}   becomes

**Comment by UziTech** [comment]
seems to work just fine in the [demo](https://marked.js.org/demo/?text=%20%20%20%20%23Lamabda%20expression%0A%20%20%20%20(name)%3D%3E%7B%20print(name)%7D%20&options=%7B%0A%20%22async%22%3A%20false%2C%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22extensions%22%3A%20null%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master)

Can you provide a repo or demo link that is showing the error?

**Comment by UziTech** [comment]
I see what you mean now. the `>` gets turned into `&gt;` in the html. [demo](https://marked.js.org/demo/?outputType=html&text=%20%20%20%20%23Lamabda%20expression%0A%20%20%20%20(name)%3D%3E%7B%20print(name)%7D%20&options=%7B%0A%20%22async%22%3A%20false%2C%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22extensions%22%3A%20null%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master)

This works according to the common mark [spec](https://spec.commonmark.org/0.30/#indented-code-blocks). If you want it changed you will have to change it there or create an [extension](https://marked.js.org/using_pro#extensions) to change it.
