### ISSUE TITLE
Ability to change URL's during parse/render

### ISSUE THREAD

**Issue by lloydjatkinson** [markedjs/marked#2733]
**Describe the feature**
When parsing/rendering markdown that contains images, allow the consumer the ability to transform URLs. It's very common for markdown to contain relative URLs such as `/public/images/something.jpg` however it would be very useful be given a callback allowing us to transform this URL and return a new value.

**Why is this feature necessary?**
There are two use cases, the first being why I created this issue, but I am sure others will also have a need for this.

- This is virtually a requirement when creating RSS feeds. It is known that RSS is a poorly implemented specification, and creating HTML for it is always a difficult process. Some readers will require absolute URLs to render images such as `https://www.example.com/public/images/something.jpg` while others are happy to work with `/public/images/something.jpg`.
- Image optimisation and caching. It's very common to take advantage of cloud based image optimisation, CDNs, caching etc. Such as https://cloudinary.com/documentation/media_optimization.

If Marked allows for URLs to be transformed these two use cases would be solved.

**Describe alternatives you've considered**

- Using Marked to manually walk the AST
  - Powerful but complex for a fairly common task
  - Like to lead to bugs in consumer code
- String search/regex
  - Yuck
- Putting absolute URLs in markdown
  - Not a realistic or feasible option as URLs are going to be different between environments, CMS's that produce markdown don't insert absolute URLs, does not truly solve the problem anyway.

**Comment by UziTech** [comment]
You can do this with walkTokens pretty easily.

```js
function walkTokens(token) {
  if (token.type === 'image' || token.type === 'link') {
    token.href = baseUrl + token.href;
  }
}

marked.use({ walkTokens });
```

**Comment by lloydjatkinson** [comment]
That's great, thanks!
