### ISSUE TITLE
React build fails after upgrading to node 18 + react-scripts 5 (webpack 5)

### ISSUE THREAD

**Issue by jsperezg** [markedjs/marked#2736]
**Marked version:**
4.2.12

**Describe the bug**
After bumping node and react scripts the build process has started failing:

```
$ react-scripts build
Creating an optimized production build...
Failed to compile.

TypeError: admin-portal/node_modules/marked/lib/marked.esm.js: symbol.charCodeAt is not a function
```

**To Reproduce**

**Expected behavior**
It should build

**Comment by UziTech** [comment]
What extensions and options are you using? Can you create a repo with code that reproduce this error?

Most likely something is returning a Symbol when it should return a String.

**Comment by jsperezg** [comment]
@UziTech that error occurred while bumping the node version for a project. I don't know exactly what happened, the thing is that after removing yarn.lock and node_modules and reinstalling the dependencies it has started working.

Sorry for the noise.
