### ISSUE TITLE
Building an extension but it doesn't act as excepted.

### ISSUE THREAD

**Issue by Antonio225t** [markedjs/marked#2737]
**Marked version:** 4.2.12

**Markdown flavor:** n/a (?)

I tried to add an extension like this:
```javascript
marked.use({
  extensions: [
    {
      name: "underline",
      level: "inline",
      start: (src) => {
        return src.match(/__(.*?)__/)?.index;
      },
      tokenizer(src, tokens) {
        var match = src.match(/__(.*?)__/);
        if (match) {
          var token = {
            type: "underline",
            raw: match[0],
            text: this.lexer.inlineTokens(match[1].trim(), [])
          };
          return token;
        }
      },
      renderer(token) {
        return `<u>${this.parser.parseInline(token.text, null)}</u>`;
      },
    }
  ]
});

var md = `
# Header
**This** is a normal text writted in \`JavaScript\` for \`Marked\`.
__test__
`;
marked.parse(md);
```
 For supporting underline in Marked. But for some reasons it didn't work. Can someone explain what I did wrong? Thanks.

## Expectation
```html
<h1>Header</h1>
<p><strong>This</strong> is a normal text writted in <code>JavaScript</code> for <code>Marked</code>.
<u>test</u></p>
```

## Result
```html
<h1>Header</h1>
<p><u>test</u><u>test</u><u>test</u><u>test</u><u>test</u><u>test</u><u>test</u><u>test</u><u>test</u></p>
```

## What was attempted
Before making this issue I attempt to looking some source codes of other extensions of Marked but it did not help. Plus I took a look at the documentation but still no luck. I tried fixing the RegEx in [RegExR](https://regexr.com/) but it seems good. I probably didn't understand something and did a mistake in the `tokenizer` section but I don't know what it is, can someone help me please? Thanks in advance 👍.

**Comment by calculuschild** [comment]
One common mistake: you need to add a `^` to the start of your Tokenizer match regex (but not the "start" match regex).

Otherwise the Tokenizer will start finding your underline tokens way out in the middle of your document before handling other tokens first, and your resulting output is out of order or duplicated.

**Comment by Antonio225t** [comment]
Thank you, I'll try it now

**Comment by Antonio225t** [comment]
This worked. Thank you so much!
