### ISSUE TITLE
 Code block ignores newlines

### ISSUE THREAD

**Issue by NMIFUN** [markedjs/marked#2741]
**Marked version:** 4.2.12

**Describe the bug**
Line break is ignored in code block.
with parseInline()

**To Reproduce**
\```
// Example of code
console.log("Hello world!");
\```

converted to
\<code>// Example of code console.log(&quot;Hello world!&quot;);\</code>

**Expected behavior**
\<code>// Example of code
console.log(&quot;Hello world!&quot;);\</code>

**Comment by calculuschild** [comment]
Are you using `parseInline()` in a custom extension? In general, `parseInline()` only handles single lines of content. If you want to parse the whole code block including line breaks, use `parse()`.

**Comment by NMIFUN** [comment]
I am using parseInline().
I need to output only these tags:
<b>
<i>
<u>
<s>
<del>
<a>
<code>

**Comment by NMIFUN** [comment]
just use parseInline ;)

**Comment by UziTech** [comment]
As @calculuschild said parseInline is for inline content only. Fenced code block are block content. This looks like it is working as expected.

**Comment by NMIFUN** [comment]
ok, how can get output with only specified tags?

**Comment by UziTech** [comment]
You can create a tokenizer that is a noop for any tokens you don't want.

Something like:

```js
const tokenizer = {
  heading() {},
  hr() {},
  blockquote() {},
  list() {},
  table() {},
  lheading() {}
};
marked.use({tokenizer});
```

**Comment by NMIFUN** [comment]
I passed like that 
```
    fences() {},
    heading() {},
    hr() {},
    blockquote() {},
    list() {},
    def() {},
    table() {},
    lheading() {},
    paragraph() {}
```
this helped, but how to remove the <p> at the beginning and end?

**Comment by UziTech** [comment]
If you are parsing as block tokens every token has to be in a block token. The easiest way to remove them is just to remove them after running through marked.

```js
const html = marked.parse(markdown);
html = html.replace(/^\s*<p>([^]*)<\/p>\s*$/, "$1");
```

Keep in mind that html is valid markdown so if you actually do want to allow someone to output <p> tags you will have to use some other library like dompurify to remove them.
