### ISSUE TITLE
non breaking space (U+00A0) and possibly others not treated as whitespace OR word characters

### ISSUE THREAD

**Issue by gardnerjr** [markedjs/marked#2744]
**Marked version:** 
4.2.12
(noticed on 4.0.10, tried upgrading to see if it helps)

**Describe the bug**
Invisible non-breaking space characters, like in this block right here, (inline as code and content)

```
## h2
### h3
[link](destination)
### anotherh3
```

### h3
[link](destination)
### anotherh3

are not always treated as whitespace, so things like headers, tables, etc don't get formatted and are left as markdown syntax.

**To Reproduce**

1. [Marked broken](https://marked.js.org/demo/?text=%23%23%C2%A0h2%0A%23%23%23%C2%A0h3%0A%5Blink%5D(destination)%0A%23%23%23%C2%A0anotherh3%0A&options=%7B%0A%20%22async%22%3A%20false%2C%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22extensions%22%3A%20null%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master)

    marked will create headers for the first few elements but then stop.  adding extra newlines OR replacing the nonbreaking space characters seems to fix it?

2. [CommonMark broken worse](https://spec.commonmark.org/dingus/?text=%23%23%C2%A0h2%0A%23%23%23%C2%A0h3%0A%5Blink%5D(destination)%0A%23%23%23%C2%A0anotherh3%0A)

    commonmark doesn't create them at all, you have to replace the nonbreaking spaces

3. DaringFireball's site seems to do "best", the headers are properly replaced AND the nonbreaking space stays intact?

**Expected behavior**
Best, I'd expect all the headers to be generated, keeping the nonbreaking space intact and without extra newlines/spacing (we're moving from one platform to another and have a ton of existing and customer markdown content that we don't control and can't convert).

**Comment by UziTech** [comment]
I think you are looking for the `pedantic: true` option. [demo](https://marked.js.org/demo/?text=%23%23%C2%A0h2%0A%23%23%23%C2%A0h3%0A%5Blink%5D(destination)%0A%23%23%23%C2%A0anotherh3%0A&options=%7B%0A%20%22pedantic%22%3A%20true%0A%7D&version=master)

That will make marked work more like the original markdown spec instead of CommonMark.

**Comment by gardnerjr** [comment]
@UziTech yes but, `pedantic: true` means that tables no longer work, since it isn't in the original spec.

so right now we're in a case where if there's non-breaking spaces, and tables, you can't have both.

**Comment by UziTech** [comment]
Ya you have to pick one spec or the other. Your other option is to create your own tokenizer that breaks with the spec.
