### ISSUE TITLE
Underscore not detected at end of link

### ISSUE THREAD

**Issue by Dsinghbailey** [markedjs/marked#2757]
**Marked version:**
^4.2.12

**Describe the bug**
Marked doesn't detect ending underscores in links

https://twitter.com/madebynelson_ is detected as "https://twitter.com/madebynelson"

**To Reproduce**
marked.parse(DOMPurify.sanitize('https://twitter.com/madebynelson_')

**Expected behavior**
I expect link to render with ending underscore, especially if there are no previous underscores

**Comment by UziTech** [comment]
This is the way it is supposed to work to follow the [GFM spec](https://github.github.com/gfm/#autolinks-extension-):

> Trailing punctuation (specifically, ?, !, ., ,, :, *, _, and ~) will not be considered part of the autolink, though they may be included in the interior of the link

**Comment by UziTech** [comment]
And just so you know, you should sanitize the output of marked not the input.

```diff
- marked.parse(DOMPurify.sanitize('https://twitter.com/madebynelson_'))
+ DOMPurify.sanitize(marked.parse('https://twitter.com/madebynelson_'))
```

**Comment by Dsinghbailey** [comment]
Thanks
