### ISSUE TITLE
Lexer does not recognizes task if it is the last thing

### ISSUE THREAD

**Issue by trusz** [markedjs/marked#2769]
**Marked version:** 4.3.0

**Describe the bug**
The lexer does not recognizes a `- [ ]` as task if:
- it is the last thing in the file
- it does not has any char following it e.g.:
  - `- [ ]`: the char `]` is the last in the line => won't get recognised
  - `- [ ] `: a space follows the `]` => it will be recognised

**To Reproduce**
- [Stackblitz link with a test ↗](https://stackblitz.com/edit/vitest-dev-vitest-qdkxk8?file=test/marked.test.ts)
- [Marked Permalink ↗](https://marked.js.org/demo/?text=%23%23%20Subtitle%201%0A%0A-%20%5B%20%5D%20Task%201%0A%0A%23%23%20Subtitle%202%0A%0A-%20%5B%20%5D%20%0A%0A%23%23%20Subtitle%203%0A%0A-%20%5B%20%5D&options=%7B%0A%20%22async%22%3A%20false%2C%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22extensions%22%3A%20null%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22hooks%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master)

**Expected behavior**
I would expect that even if a task does not have any char it will be recognised as an empty task, but I am not sure what does the specification says about that.

**Comment by UziTech** [comment]
We try to make it look like it would in GitHub. As you can see this is working as intended.

This how GitHub renders `- [ ]`

- [ ]

**Comment by trusz** [comment]
I see. Thanks for the answer!
