### ISSUE TITLE
can not parse a link with ) normally

### ISSUE THREAD

**Issue by zindler323** [markedjs/marked#2781]
**Marked version:**

**Describe the bug**
When I pass the  string 'Hello, I'm zindler(https://www.google.com/)nice to meet you!' to marked.parse(), the character ) and words after it are all put into the href attribute of a tag. 

**To Reproduce**

**Expected behavior**

**Comment by UziTech** [comment]
We follow the [GFM spec](https://github.github.com/gfm/#autolinks-extension-). As you can see in your example GitHub does the same thing so this is working as expected.

**Comment by UziTech** [comment]
If you add angle brackets around the link you can specify exactly which part is the link.

[Demo link](https://marked.js.org/demo/?text=Hello%2C%20I%27m%20zindler(%3Chttps%3A%2F%2Fwww.google.com%2F%3E)nice%20to%20meet%20you!&options=%7B%0A%20%22async%22%3A%20false%2C%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22extensions%22%3A%20null%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22hooks%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master)

Hello, I'm zindler(<https://www.google.com/>)nice to meet you!

**Comment by zindler323** [comment]
ok, thanks.



---Original---
From: "Tony ***@***.***&gt;
Date: Tue, Apr 18, 2023 20:41 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [markedjs/marked] can not parse a link with ) normally (Issue#2781)




 
If you add angle brackets around the link you can specify exactly which part is the link.
 
Demo link
 
Hello, I'm zindler(https://www.google.com/)nice to meet you!
