### ISSUE TITLE
Use only subset of supported MD features

### ISSUE THREAD

**Issue by michaltaberski** [markedjs/marked#2782]
**Describe the feature**
I am looking for an option to limit number of supported MD features. In particular I would like to have a whitelist of supported features like `bold`, `italic`, `links` - so no `h1`, `lists` or whatever else normally is possible with MD.

**Why is this feature necessary?**
I want to use super tinny subset of md features in comments feature of my project. I want users to be able to bold text and perhaps embed links, but nothing beyond that. 

**Describe alternatives you've considered**
Write a small custom, regex based implementation.

**Comment by UziTech** [comment]
You can create a [renderer](https://marked.js.org/using_pro#renderer) and [tokenizer](https://marked.js.org/using_pro#tokenizer) to remove the tokens you don't want. You can also use [`marked.parseInline(...)`](https://marked.js.org/using_advanced#inline) to only use the inline parser to remove all block tokens.
