### ISSUE TITLE
5.0 in bugs

### ISSUE THREAD

**Issue by jiayouzl** [markedjs/marked#2792]
marked.parse('# Marked in the browser\n\nRendered by **marked**.');

There are clearly 2 line breaks, but only 1 line break effect is rendered in reality.

**Comment by UziTech** [comment]
That is working according to the [spec](https://spec.commonmark.org/0.30/#blank-lines)

**Comment by jiayouzl** [comment]
> That is working according to the [spec](https://spec.commonmark.org/0.30/#blank-lines)

I see, thank you.
