### ISSUE TITLE
Cannot use marked-highlight with marked version 5

### ISSUE THREAD

**Issue by mrdaniellewis** [markedjs/marked#2794]
**Marked version:** 5

**Describe the bug**

Version 5 upgrade instructions ask you to use `marked-highlight` as a replaced to the highlight option, however `marked-highlight` required marked version `^4.3.0`.

**To Reproduce**

Try to installed marked version 5 and the latest `marked-highlight`

**Expected behavior**

You can install the libraries and they work together.

**Actual behavior**

NPM cannot resolve the dependency due to the version conflict.

**Comment by UziTech** [comment]
Thank you for reporting this! 💯

We just released a new version that should support marked v5
