### ISSUE TITLE
How to set "mangle" option if installed globally?

### ISSUE THREAD

**Issue by danielkrajnik** [markedjs/marked#2810]
using marked as a globally installed module gives you a warning that asks you to set mangle option to false.

How do you do that? Is there a config file to change such options?

Sorry, if it's a noob question...

**Comment by danielkrajnik** [comment]
I took a wild guess that you can edit marked.js in bin directory based on [this piece from the official documentation](https://marked.js.org/using_advanced#options):

`
// Set options
marked.use({
  mangle: false,
  headerIds: false,
});
`

If someone could please confirm that this is a supported operation and it won't be wiped out on the next update that would be really helpful.

**Comment by UziTech** [comment]
The easiest way to set defaults is to create an alias `alias my_marked='marked --no-mangle --no-heading-ids'`

Of you can create a node script that calls marked and create an alias that calls marked `alias my_marked='node ~/my_marked.js'`
