### ISSUE TITLE
Render table incorrectly

### ISSUE THREAD

**Issue by KaizOffical** [markedjs/marked#2815]
I just have a test with markdown table like below
```md
| Month    | Savings |
| -------- | ------- |
| January  | $250    |
| February | $80     |
| March    | $420    |
```
it should be looked smt like this
| Month    | Savings |
| -------- | ------- |
| January  | $250    |
| February | $80     |
| March    | $420    |

however, it rendered only the text but there wasn't any borders and the spacing wasn't good

![result](https://media.discordapp.net/attachments/994835302235504650/1110589005260668978/image.png?width=190&height=140)
even I tried to change the background color
![result](https://media.discordapp.net/attachments/994835302235504650/1110589005520707695/image.png?width=239&height=146)

**Comment by UziTech** [comment]
Marked does not provide any css for border or spacing. You will need to provide that yourself.

**Comment by KaizOffical** [comment]
> Marked does not provide any css for border or spacing. You will need to provide that yourself.

I added style for the md file, however when it rendered, the style css part just like text part
![result](https://media.discordapp.net/attachments/994835302235504650/1110749785662685356/image.png?width=427&height=45)
```md
<div style="color:green">green text</div>
```

**Comment by KaizOffical** [comment]
> You should add css with `<style>` tags ([demo](https://marked.js.org/demo/?text=%3Cstyle%3E%0Atable%20%7B%0A%20%20border-collapse%3A%20collapse%3B%0A%7D%0Ath%2C%20td%20%7B%0A%20%20border%3A%201px%20solid%20%23000%3B%0A%20%20padding%3A%205px%3B%0A%7D%0A%3C%2Fstyle%3E%0A%0A%7C%20Month%20%20%20%20%7C%20Savings%20%7C%0A%7C%20--------%20%7C%20-------%20%7C%0A%7C%20January%20%20%7C%20%24250%20%20%20%20%7C%0A%7C%20February%20%7C%20%2480%20%20%20%20%20%7C%0A%7C%20March%20%20%20%20%7C%20%24420%20%20%20%20%7C&options=%7B%0A%20%22async%22%3A%20false%2C%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22extensions%22%3A%20null%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22hooks%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master)). HTML doesn't get parsed as markdown according to the [spec](https://spec.commonmark.org/0.30/#html-blocks).

Still not working
![result](https://media.discordapp.net/attachments/994835302235504650/1110785097021538415/image.png?width=930&height=47)
It rendered the text

**Comment by UziTech** [comment]
Works in this [demo](https://marked.js.org/demo/?text=%3Cstyle%3E%0Atable%20%7B%0A%20%20border-collapse%3A%20collapse%3B%0A%7D%0Ath%2C%20td%20%7B%0A%20%20border%3A%201px%20solid%20%23000%3B%0A%20%20padding%3A%205px%3B%0A%7D%0A%3C%2Fstyle%3E%0A%0A%7C%20Month%20%20%20%20%7C%20Savings%20%7C%0A%7C%20--------%20%7C%20-------%20%7C%0A%7C%20January%20%20%7C%20%24250%20%20%20%20%7C%0A%7C%20February%20%7C%20%2480%20%20%20%20%20%7C%0A%7C%20March%20%20%20%20%7C%20%24420%20%20%20%20%7C&options=%7B%0A%20%22async%22%3A%20false%2C%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22extensions%22%3A%20null%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22hooks%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master)
