### ISSUE TITLE
Codeblock does not render with styles

### ISSUE THREAD

**Issue by KaizOffical** [markedjs/marked#2827]
**What pain point are you perceiving?.**
Well, I'm making website to make wiki for my coding package. So I need to put code inside the markdown but when I use codeblock to render, it just render a simple text with background

**Describe the solution you'd like**
Add styling for codeblock

**Comment by calculuschild** [comment]
Marked does not provide any CSS for Codeblocks. You will have to provide that yourself.

A similar question was asked a few days ago here that may have some answers for you: https://github.com/markedjs/marked/issues/2815
