### ISSUE TITLE
XML escaping option

### ISSUE THREAD

**Issue by mikhail-rush** [markedjs/marked#2828]
**Describe the feature**
XML attribute values don't allow some characters, such as: `&`, `<`, `>`, `"`, `'`. Link that have an ampersand `&` in the query string make the `<a href...>` node invalid XML.

**Why is this feature necessary?**
I'm using `marked` to convert Markdown to XHTML so I can create pages in Confluence in it's [storage format](https://confluence.atlassian.com/doc/confluence-storage-format-790796544.html). However if hrefs have an ampersand that are not escaped, saving a page fails.

**Describe alternatives you've considered**
I'm using https://github.com/markedjs/marked-xhtml but it's not escaping urls.
Ended up creating a custom link rendered:

```ts
function cleanUrl(href: string) {
  try {
    href = encodeURI(href).replace(/%25/g, '%').replace(/&/g, '&amp;');
  } catch (e) {
    return null;
  }
  return href;
}

const xmlLinkRenderer = {
  link(href: string, title: string, text: string) {
    const cleanHref = cleanUrl(href);
    if (cleanHref === null) {
      return text;
    }
    let out = '<a href="' + cleanHref + '"';
    if (title) {
      out += ' title="' + title + '"';
    }
    out += '>' + text + '</a>';
    return out;
  }
};

marked.use({ renderer: xmlLinkRenderer });
```

**Comment by UziTech** [comment]
You can make that into an extension so others can use it. 😁👍
