### ISSUE TITLE
Wanted to preserve new line character characters while parsing the markdown 

### ISSUE THREAD

**Issue by ShadmanAfzal** [markedjs/marked#2842]
**Describe the feature**
Wanted to have a way though which I can preserve any new line character present in the markup

Or anyone knows a way around

**Comment by UziTech** [comment]
You can try the `breaks` option.

If that is not what you want than you will need to create an extension that keeps track of the line breaks and renders `<br>` for them.

Or you can see some of the hacks that people came up with in #190

**Comment by ShadmanAfzal** [comment]
Is there any correct way of doing it? The "hacky" way, not always gave the desired result.

**Comment by UziTech** [comment]
Does the `breaks` option work for you? That is meant to act like GitHub comments where a new line character will add a line break without needing 2 spaces at the end of the line.
