### ISSUE TITLE
Marked@5.1.0 crashes in Hermes (React Native) environment

### ISSUE THREAD

**Issue by birdofpreyru** [markedjs/marked#2843]
**Marked version:** 5.1.0

**Describe the bug**
When `marked` module is loaded, the following line gets called with `regex` equal ``^((?![*_])[\s\p{P}$+<=>`|~])``, which is deemed to be an invalid regular expression by Hermes engine (namely, it calls the error "_Invalid escape_", not giving more specific details), thus it throws on this line crashing the host app 
https://github.com/markedjs/marked/blob/a26f002d1819462c6cae75bb0c26dc064e17b4db/src/helpers.js#L66

It did not happen in the previous, v5.0.5 of `marked`.

**To Reproduce**

**Expected behavior**

**Comment by UziTech** [comment]
This sounds like a bug in Hermes. Unicode escapes have been in JavaScript [since ES 2018](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Regular_expressions/Unicode_character_class_escape#browser_compatibility).

**Comment by UziTech** [comment]
One option is to use [babel-plugin-transform-unicode-escapes](https://babeljs.io/docs/babel-plugin-transform-unicode-escapes) and compile marked yourself to use older browser engines

**Comment by birdofpreyru** [comment]
Thanks @UziTech , I double-checked it indeed fails on `\p{P}`, and reported the bug in Hermes repo (https://github.com/facebook/hermes/issues/1027).

**Comment by djMax** [comment]
How is this solved (real question, not snark)? I just tried a fresh project with latest and hermes still breaks on the regex.

**Comment by UziTech** [comment]
This is an issue in Hermes not marked see https://github.com/facebook/hermes/issues/1027

**Comment by unitythemaker** [comment]
https://github.com/facebook/hermes/issues/1027 seems to be closed. Anyone found a solution? I am still getting the error.

**Comment by UziTech** [comment]
You should open another issue on that repo if you are still getting an error. It looks like it should have been fixed in https://github.com/facebook/hermes/pull/1295. Make sure you are using an updated version of hermes
