### ISSUE TITLE
Strikethrough and Subscript has mixed up

### ISSUE THREAD

**Issue by mehedimi** [markedjs/marked#2850]
**Marked version:**
5.1.0
**Describe the bug**
[Strikethrough](https://www.markdownguide.org/extended-syntax/#strikethrough) and [Subscript](https://www.markdownguide.org/extended-syntax/#subscript) has mixed up

**Demo**
[Demo Link](https://marked.js.org/demo/?text=I%20am%20~superscript~%0AI%20am%20~~strikethrough~~&options=%7B%0A%20%22async%22%3A%20false%2C%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22extensions%22%3A%20null%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22hooks%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master
)

**Expected behavior**
Single `~` is represented to subscript and double `~~` is represented to strikethrough

**Comment by UziTech** [comment]
According to [GFM spec](https://github.github.com/gfm/#strikethrough-extension-)

> Strikethrough text is any text wrapped in a matching pair of one or two tildes (~).

If you want to follow a different spec you will have to update the tokenizer.
