### ISSUE TITLE
Link parsing incorrect

### ISSUE THREAD

**Issue by zhao-xiaohu** [markedjs/marked#2864]
**Marked version:**

5.1.0

**Describe the bug**

Link end recognition error, ']' was determined as part of the link

**To Reproduce**

[Marked Demo](https://marked.js.org/demo/?text=text%5Bhttps%3A%2F%2Fmarked.js.org%2F%5Dtext&options=%7B%0A%20%22async%22%3A%20false%2C%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22extensions%22%3A%20null%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22hooks%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=5.1.0)

**Expected behavior**

Like VSCode:
![image](https://github.com/markedjs/marked/assets/34085364/173e7058-70bf-4efc-a808-0e13709369f6)

**Comment by UziTech** [comment]
This is actually working as expected. The [GFM spec](https://github.github.com/gfm/#autolinks-extension-) says:

> Trailing punctuation (specifically, `?`, `!`, `.`, `,`, `:`, `*`, `_`, and `~`) will not be considered part of the autolink

Notice how `]` is not in that list.

This is how GitHub parses that link:

https://marked.js.org/]text

**Comment by UziTech** [comment]
If you want to exclude the `]` you can use angle brackets around the link

```
text[<https://marked.js.org/>]text
```

**Comment by zhao-xiaohu** [comment]
thanks, i had set 'gfm: false' to turns off automatic resolution of links

**Comment by zhao-xiaohu** [comment]
The [marked-linkify-it](https://github.com/UziTech/marked-linkify-it) extensions has helped me

```js
import { marked } from 'marked';
import markedLinkifyIt from 'marked-linkify-it';

marked.use(markedLinkifyIt());
```
