### ISSUE TITLE
Improper emoji rendering with v5.1.0

### ISSUE THREAD

**Issue by davidsandoz** [markedjs/marked#2865]
**Marked version:** v5.1.0

**Describe the bug**
Emoji rendering fails if located at the beginning or the end of a bold text.

I don't know if this is specific to the bold markup or if the issue happens with other markup.

**To Reproduce**

Here's a markdown text to reproduce the issue:
```markdown
Situations where it fails:

**test 💁**

**💁 test**

**🤓 test**

**🏖️ test**

Situations where it works:

**💁 **

**⚠️ test**

Here, the emoji rendering works, but the text doesn't get rendered in italic.

*💁 test*
```

The text above [on Markded Demo](https://marked.js.org/demo/?text=Situations%20where%20it%20fails%3A%0A%0A**test%20%F0%9F%92%81**%0A%0A**%F0%9F%92%81%20test**%0A%0A**%F0%9F%A4%93%20test**%0A%0A**%F0%9F%8F%96%EF%B8%8F%20test**%0A%0ASituations%20where%20it%20works%3A%0A%0A**%F0%9F%92%81%20**%0A%0A**%E2%9A%A0%EF%B8%8F%20test**%0A%0AHere%2C%20the%20emoji%20rendering%20works%2C%20but%20the%20text%20doesn%27t%20get%20rendered%20in%20italic.%0A%0A*%F0%9F%92%81%20test*%0A%0A&options=%7B%0A%20%22async%22%3A%20false%2C%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22extensions%22%3A%20null%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22hooks%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=5.1.0) and [on CommonMark Demo](https://spec.commonmark.org/dingus/?text=Situations%20where%20it%20fails%3A%0A%0A**test%20%F0%9F%92%81**%0A%0A**%F0%9F%92%81%20test**%0A%0A**%F0%9F%A4%93%20test**%0A%0A**%F0%9F%8F%96%EF%B8%8F%20test**%0A%0ASituations%20where%20it%20works%3A%0A%0A**%F0%9F%92%81%20**%0A%0A**%E2%9A%A0%EF%B8%8F%20test**%0A%0AHere%2C%20the%20emoji%20rendering%20works%2C%20but%20the%20text%20doesn%27t%20get%20rendered%20in%20italic.%0A%0A*%F0%9F%92%81%20test*%0A%0A)

Screenshot of the rendering on Marked Demo:
![Screenshot 2023-07-03 at 17 33 19](https://github.com/markedjs/marked/assets/1535702/6b2f83c2-76a1-46a7-b701-a70cd09a77e7)

**Expected behavior**

What is rendered on CommonMark Demo:
![Screenshot 2023-07-03 at 17 37 48](https://github.com/markedjs/marked/assets/1535702/fddf966a-7037-4651-af20-07d50b0c7712)

**Comment by davidsandoz** [comment]
Additional note: It works well with v5.0.5, so this got introduced with v5.1.0.

**Comment by UziTech** [comment]
@calculuschild Looks like this might have been broken by #2841

**Comment by calculuschild** [comment]
Are emojis considered punctuation or ?

**Comment by UziTech** [comment]
I don't think these emoji are in `\p{P}`. It looks like it is not all emoji that are the problem. This is only happening to certain emoji.

**Comment by UziTech** [comment]
@calculuschild I've been trying to get this to work with `\p{P}` but I don't know if we can. I think the best fix is to revert #2841.
What do you think?

**Comment by calculuschild** [comment]
We can revert if needed, but it fixed several other cases too so we would lose those fixed.

Are emojis meant to be punctuation as far as Commonmark specs go?

**Comment by UziTech** [comment]
> What I meant by this is are emojis meant to be treated as punctuation according to the Commonmark spec?

I don't think so
