### ISSUE TITLE
Each line is surrounded by p tags when ignoring the list

### ISSUE THREAD

**Issue by kokeman** [markedjs/marked#2869]
**Marked version:** 5.1.0

## What I have tried
- I want to ignore list conversions.
- I set it to ignore list conversion by referring to [this](https://github.com/markedjs/marked/issues/420#issuecomment-1210799497) post.

## What is problem
- Instead of enclosing the entire list with p tags, each line is wrapped with p tags.

## Question
- Why is this happening?
- Is it possible to set the entire list part to be enclosed in p tags without changing the issue_text?

## Demo
https://jsfiddle.net/9wxLgvuo/3/

**Comment by UziTech** [comment]
I think this is becuase the paragraph rule by default stops at a list. You will need to change the paragraph rule as well to get it working how you want.

**Comment by kokeman** [comment]
I solved it by removing the list regex from the paragraph regex. Thank you very match.
