### ISSUE TITLE
Linebreak within table cell not correctly rendered

### ISSUE THREAD

**Issue by markusvorraber** [markedjs/marked#2871]
**Marked version:** 5.1.0

**Describe the bug**
If I want a linkbreak within a table cell, it is rendered as a new table row instead.

**To Reproduce**
Just put a new line inside of a table cell.
[Demo link](https://marked.js.org/demo/?text=%0AHere%20without%20linebreak%3A%0A%0ACol1%7C%20Col2%20%7C%20Col3%0A---%20%7C%20---%20%7C%20---%0Aa1%20%7C%20b1%20text%20%7C%20c1%0Aa2%20%7C%20b2%20%7C%20c2%0A%0A%0A%0AHere%20with%20linebreak%2C%20but%20not%20working%3A%0A%0ACol1%7C%20Col2%20%7C%20Col3%0A---%20%7C%20---%20%7C%20---%0Aa1%20%7C%20b1%20%5C%0Atext%20%7C%20c1%0Aa2%20%7C%20b2%20%7C%20c2%0A%0A%0A&options=%7B%0A%20%22async%22%3A%20false%2C%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22extensions%22%3A%20null%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22hooks%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master)

**Expected behavior**
A br element should be rendered instead of a new tr
In Pandoc, this is correctly rendered, see [Demo link](https://pandoc.org/try/?params=%7B%22text%22%3A%22%5CnHere+without+linebreak%3A%5Cn%5CnCol1%7C+Col2+%7C+Col3%5Cn---+%7C+---+%7C+---%5Cna1+%7C+b1+text+%7C+c1%5Cna2+%7C+b2+%7C+c2%5Cn%5Cn%5Cn%5CnHere+with+linebreak%2C+but+not+working%3A%5Cn%5CnCol1%7C+Col2+%7C+Col3%5Cn---+%7C+---+%7C+---%5Cna1+%7C+b1+%5C%5C%5Cntext+%7C+c1%5Cna2+%7C+b2+%7C+c2%5Cn%5Cn%5Cn%22%2C%22to%22%3A%22html5%22%2C%22from%22%3A%22markdown%22%2C%22standalone%22%3Afalse%2C%22embed-resources%22%3Afalse%2C%22table-of-contents%22%3Afalse%2C%22number-sections%22%3Afalse%2C%22citeproc%22%3Afalse%2C%22html-math-method%22%3A%22plain%22%2C%22wrap%22%3A%22auto%22%2C%22highlight-style%22%3Anull%2C%22files%22%3A%7B%7D%2C%22template%22%3Anull%7D)

**Comment by UziTech** [comment]
We follow the [GFM spec](https://github.github.com/gfm/#tables-extension-) which renders it like this:

---

Here without linebreak:

Col1| Col2 | Col3
--- | --- | ---
a1 | b1 text | c1
a2 | b2 | c2

Here with linebreak, but not working:

Col1| Col2 | Col3
--- | --- | ---
a1 | b1 \
text | c1
a2 | b2 | c2

---

If you want to render it differently than GitHub you will need to create an [extension](https://marked.js.org/using_pro#extensions).

**Comment by calculuschild** [comment]
@markusvorraber you could instead use `<br>` to get the line break. That works inside table cells
