### ISSUE TITLE
"What is assembly?" The console said.

### ISSUE THREAD

**Issue by huangyuzhe1121** [markedjs/marked#2877]
_（This is my first issue and I cannot use English well...So if there was something wrong in it,please forgive me...）_
In fact,I am not the developer of the website whitch sent this error,so I cannot get much infomation...
The BUG appeared on a mirror site of ChatGPT,When I ask ChatGPT to write Assembly programs,the error will be throw out on the console and the website will become empty...
The website whitch influenced by this error: [www.forchangeai.com](https://www.forchangeai.com)
When I open console,the error information told me to feedback on github...
The information:
```
Uncaught Error: Unknown language: "assembly"
Please report this to https://github.com/markedjs/marked.
    at u (index.19042c37.js:114:53459)
    at Object.c [as highlight] (index.19042c37.js:114:50282)
    at Object.highlightCode [as highlight] (index.19042c37.js:145:69904)
    at Renderer.code (index.19042c37.js:140:37866)
    at Parser.parse (index.19042c37.js:140:41109)
    at Parser.parse (index.19042c37.js:140:40381)
    at marked (index.19042c37.js:140:44871)
    at index.19042c37.js:145:71845
    at index.19042c37.js:145:72857
    at Array.map (<anonymous>)
    at Conversation (index.19042c37.js:145:71993)
    at Xh (index.19042c37.js:21:65855)
    at dj$1 (index.19042c37.js:21:77958)
    at Wk (index.19042c37.js:21:124872)
    at Vk (index.19042c37.js:21:115248)
    at Uk$1 (index.19042c37.js:21:115171)
    at Jk (index.19042c37.js:21:115020)
    at Ok$1 (index.19042c37.js:21:111263)
    at Hk (index.19042c37.js:21:110191)
    at v (index.19042c37.js:11:1374)
    at MessagePort.O (index.19042c37.js:11:1906)
u @ index.19042c37.js:114
c @ index.19042c37.js:114
highlightCode @ index.19042c37.js:145
code @ index.19042c37.js:140
parse @ index.19042c37.js:140
parse @ index.19042c37.js:140
marked @ index.19042c37.js:140
(匿名) @ index.19042c37.js:145
(匿名) @ index.19042c37.js:145
Conversation @ index.19042c37.js:145
Xh @ index.19042c37.js:21
dj$1 @ index.19042c37.js:21
Wk @ index.19042c37.js:21
Vk @ index.19042c37.js:21
Uk$1 @ index.19042c37.js:21
Jk @ index.19042c37.js:21
Ok$1 @ index.19042c37.js:21
Hk @ index.19042c37.js:21
v @ index.19042c37.js:11
O @ index.19042c37.js:11
```
**The following is a repetition in Chinese to above in addition to the error message, specially attached to prevent misunderstandings (you may not need to read it).**
这个错误出现在一个ChatGPT的镜像源中，网址：[www.forchangeai.com](https://www.forchangeai.com),当我要求GPT写汇编程序时，网站将会整个白屏并且控制台投出了错误信息，并且在错误信息中，有一条告诉我可以在这里反馈错误。。。

**Comment by UziTech** [comment]
It looks like the website uses highlight js to highlight code and assembly is a programming language that highlight js doesn't support

https://github.com/highlightjs/highlight.js/blob/main/SUPPORTED_LANGUAGES.md

**Comment by huangyuzhe1121** [comment]
So...is a mistake made by the developer of the website...Sorry for bothering...But thanks for your reply and patience! :)
&nbsp;


黄黄
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Tony ***@***.***&gt;; 
发送时间: 2023年7月12日(星期三) 晚上10:43
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [markedjs/marked] &quot;What is assembly?&quot; The console said. (Issue #2877)





 
It looks like the website uses highlight js to highlight code and assembly is a programming language that highlight js doesn't support
 
https://github.com/highlightjs/highlight.js/blob/main/SUPPORTED_LANGUAGES.md
