### ISSUE TITLE
Backslashes are wrongly rendered in some cases

### ISSUE THREAD

**Issue by btnguyen2k** [markedjs/marked#2910]
**Marked version:**

5.1.1

**Describe the bug**

```
const input1 = '\$a';
const input2 = '\\$a';
```

The two inputs above resulted the same output: `<p>$a</p>\n`

**To Reproduce**

Use the two inputs provided above, with or without enabling Katex extension.

**Expected behavior**

The second input should produce `<p>\$a</p>\n`

More info:
with the 1st input, tokenizer produced the following token `{ type: 'text', raw: '$a', text: '$a' }`
while the 2nd input resulted in the following token `{ type: 'escape', raw: '\\$', text: '$' }` ==> the `text` in this case should be `\$`.

**Comment by UziTech** [comment]
This is working according to commonmark spec

https://spec.commonmark.org/dingus/?text=%5C%24a
