### ISSUE TITLE
Table without external | symbols and empty rows is not parsed correctly

### ISSUE THREAD

**Issue by tubignat** [markedjs/marked#2912]
**Marked version:** 4.3.0

**Describe the bug**
When I try to render the following markdown:

```
Column 1 | Column 2 
---------|---------
  Data1  |   Data2
         |
  Data4  |   Data5  
```

I get:

![image](https://github.com/markedjs/marked/assets/30076197/b95cf29f-2f87-40fb-9b16-74a894ad7c07)

It works fine if I remove the empty row, also it works fine if I put '|' symbols on the outside of the table, like this:

```
 | Column 1 | Column 2 |
 |----------|--------- |
 |  Data1.  |   Data2  |
 |          |          |
 | Data4    |   Data5  |  
```

**To Reproduce**

Parse the following:

```
Column 1 | Column 2 
---------|---------
  Data1  |   Data2
         |
  Data4  |   Data5  
```

**Expected behavior**

The expected behavior is a rendered table with three rows, one of which is empty

**Comment by UziTech** [comment]
We try to match what the same markdown looks like in GitHub. Here is what that markdown looks like on GitHub:

Column 1 | Column 2 
---------|---------
  Data1  |   Data2
         |
  Data4  |   Data5  

So this is correctly rendered.
