### ISSUE TITLE
renderer.* to vue3 component

### ISSUE THREAD

**Issue by doroved** [markedjs/marked#2915]
**Describe the feature**
Make it possible to render tokens using vue 3 components.

**App.vue**
```vue
<script setup lang="ts">
import { ref, h } from 'vue'
import { marked } from 'marked'

const content = ref(`
1. [Apple](https://apple.com/)
2. [Google](https://google.com/)
3. [Amazon](https://amazon.com/)
`)

const renderer = new marked.Renderer()
renderer.link = (href, title, text) => {
  return h('CustomLink', { href, text }) // Return a component instead of an HTML string
}

marked.use({ renderer })
</script>

<template>
<div v-html="marked.parse(content)"></div>
</template>
```

**CustomLink.vue**
```vue
<script setup lang="ts">
const props = defineProps({
  href: {
    type: String,
    required: true,
    default: () => ''
  },
  text: {
    type: String,
    required: true,
    default: () => ''
  }
})
</script>

<template>
  <a :href="props.href" target="_blank" class="text-red-500">{{ props.text }}</a>
</template>
```
**Why is this feature necessary?**
In vue 3 you need to render code,link etc from a component so that you can set @click events etc for elements inside the component. 

**Describe alternatives you've considered**
I used this code, it works, but the registered events inside the component will not work as we are only returning the HTML code of the component, not the component itself.

```vue
<script setup lang="ts">
import { ref, h } from 'vue'
import { marked } from 'marked'

const content = ref(`
1. [Apple](https://apple.com/)
2. [Google](https://google.com/)
3. [Amazon](https://amazon.com/)
`)

const renderer = new marked.Renderer()
renderer.link = (href, title, text) => {
  // Create vnode
  const vnode = h(CustomLink, {
    href: href!,
    text: text!
  })

  // Create a container for rendering on the client
  const container = document.createElement('div')

  // Convert vnode to a string
  render(vnode, container)
  return container.innerHTML
}

marked.use({ renderer })
</script>

<template>
<div v-html="marked.parse(content)"></div>
</template>
```

**Comment by UziTech** [comment]
You will have to create your own Parser. The marked parser concats the output of the renderers as strings.

**Comment by UziTech** [comment]
You can copy the marked [Parser](https://github.com/markedjs/marked/blob/master/src/Parser.ts) and run it on the lexer tokens.

```js
marked.use({renderer});
const tokens = marked.lexer(markdown);
const vueComponent = myParser(tokens);
```

**Comment by nanmu42** [comment]
Following hints from https://github.com/markedjs/marked/issues/2915#issuecomment-1663308425, I managed to implement a markdown-to-vue-component parser. Here is some gists:

Take the [source code](https://github.com/markedjs/marked/tree/master/src) of Marked and put them into your object - It's well structured and has no external dependency.

Start with [`parseInline()`](https://github.com/markedjs/marked/blob/9514a93794511d4422e0982f89e4a5161069858f/src/Parser.ts#L198) and change its signature:

```ts
  /**
   * Parse Inline Tokens
   */
  parseInline(tokens: Token[], renderer?: _Renderer): (VNode | string)[] {
    renderer = renderer || this.renderer
    const out: (VNode | string)[] = []
```

where `VNode` is from Vue. 

Now follow the type error to amend the `Renderer.ts`, e.g.:

```ts
  list(body: (VNode | string)[], ordered: boolean, start: number | ''): VNode {
    const type = ordered ? 'ol' : 'ul'
    const startatt = ordered && start !== 1 ? { start: start } : {}
    return h(type, startatt, body)
  }

  listitem(text: (VNode | string)[]): VNode {
    return h('li', {}, text)
  }

  checkbox(checked: boolean): VNode {
    interface Props {
      type: string
      disabled: boolean
      checked?: ''
    }

    const props: Props = {
      type: 'checkbox',
      disabled: true,
    }
    if (checked) {
      props['checked'] = ''
    }

    return h('input', props)
  }
```

You may import and use your Vue component in the [`h()` function](https://vuejs.org/guide/extras/render-function.html).

Repeat the process for [`parse()`](https://github.com/markedjs/marked/blob/9514a93794511d4422e0982f89e4a5161069858f/src/Parser.ts#L44):

```ts
  /**
   * Parse Loop
   */
  parse(tokens: Token[], top = true): (VNode | string)[] {
    const out: (VNode | string)[] = []
```

Follow the type errors to modify `marked.ts`, `Instance.ts`, etc.

Also usages of [`escape()`](https://github.com/markedjs/marked/blob/9514a93794511d4422e0982f89e4a5161069858f/src/helpers.ts#L17) functions should be modified to avoid unwanted HTML escape.

Finally, a [​functional components](https://vuejs.org/guide/extras/render-function.html#functional-components) is going to consume `marked.parse`.

Good luck.

---

Many thanks to the authors of Marked, the project is compact and well-structured. I really enjoy the code reading and hacking process. Cheers! :beers:

**Comment by L422Y** [comment]
I'm working on this, might be of help, still very much a WIP and I honestly am not incredibly sure I have a great handle on everything yet, but it mostly works:

https://github.com/L422Y/nuxt-content-lite/tree/main/src/runtime/src/vueMarked

**Comment by marvindinges** [comment]
I just have [rewritten](https://github.com/marvindinges/marked-VNode) the library(v15.0.0) for use with Vue's VNodes.
But it is untested atm and I'm also inexperienced with JavaScript & TypeScript so be careful when you use it.
It would also be nice if someone could review the code and check if it has any flaws that need to be addressed.

**Comment by UziTech** [comment]
With the `provideParser` hook this could be made into an extension so others can use it.

```js
// marked-vue-parser

export default function markedVueParser() {
  return {
    hooks: {
      provideParser() {
        return vueParser
      },
    },
    renderer: vueRenderer,
  };
}
```

```js
import { Marked } from 'marked';
import markedVueParser from 'marked-vue-parser';

const marked = new Marked();
marked.use(markedVueParser());

const vue = marked.parser(markdown);
```

**Comment by NyaomiDEV** [comment]
> With the `provideParser` hook this could be made into an extension so others can use it.

@UziTech I am trying to just do that, however there isn't a clear way to just provide parsers _this_ custom as TypeScript will complain that the original Marked parsers/renderers only return strings whereas we return VNodes. This, plus it's unclear how I should treat compatibility with other extensions as of yet.

Also, we don't have access to some utility functions and RegExp's that needed to be copied over.

The problem at heart is that we can't turn VNodes into plain strings, as I've understood.

**Comment by UziTech** [comment]
Ya that won't be compatible with any extensions that add it change renderers.

The regexps and other helper functions should only be needed for the tokenizers, and they are not public because we change them often to fix bugs and don't want to have to release a major version every time they change. It's best just to copy them from the marked code base.

Typescript will be a problem. We may need a way to add some generic types to marked. If you want to work on a PR for that it would be very appreciated. 

My thought is that since html is valid markdown you will need an html renderer that turns an html string into vue components, so why not just turn the output html string from marked into vue components?

**Comment by UziTech** [comment]
I created an HTML element renderer extension at https://github.com/UziTech/marked-html-renderer but I have not published it yet since it has a big issue with inline html.
 
 Since `<div>text</div>` is 3 separate tokens the output is `<div></div>text` because `<div>` is a valid html div with nothing inside it but `</div>` is not. Then the text node `text` comes after the div element.

 I think this is a fundamental difference between CommonMark output and HTML that can't be easily solved.

The only solution I can think of is just to remove inline HTML from valid markdown when using this extension. I'm guessing any vue or react output would have the same problems.

**Comment by UziTech** [comment]
I think I got around it by creating a new tokenizer for block and inline html. The html will need to be valid HTML or it will just render as text.

I released [marked-html-renderer](https://www.npmjs.com/package/marked-html-renderer) 🎉
