### ISSUE TITLE
Webpack build result broken in Safari 14.1

### ISSUE THREAD

**Issue by cary-hu** [markedjs/marked#2925]
**Marked version:**
7.0.1

**Describe the bug**
My app broken in safari 14.1, error is :
unexpected token '='. expected an opening '(' before a method's parameter list

Have tried this, but not take effect:
https://stackoverflow.com/questions/60026651/safari-unexpected-token-expected-an-opening-before-a-methods-paramet

webconfig:
```
module.exports = {
  ...
  module: {
    rules: [
      ...
      {
        test: /\.js$/,
        use: {
          loader: 'babel-loader',
          options: {
            presets: ['@babel/preset-env'],
          },
        },
        exclude: /node_modules/,
      },
      ...
    ],
  },
  ...
};

```

tsconfig:
```
{
  "compilerOptions": {
    "module": "ES2022",
    "target": "es5",
    "outDir": "dist/",
    "jsx": "react",
    "jsxFactory": "h",
    "lib": [
      "ESNext",
      "DOM",
      "WebWorker"
    ],
    "baseUrl": "./src",
    "allowJs": true,
    "noImplicitReturns": true,
    "moduleResolution": "node",
    "paths": {
      "@/*": [
        "*"
      ]
    },
    "esModuleInterop": true
  },
  "exclude": [
    "node_modules",
    "demos"
  ]
}
```

Should I update something? Or how can I fix this, thanks a lot your time.

**Comment by UziTech** [comment]
It looks like you will have to use `@babel/plugin-proposal-class-properties` and include marked in the `babel-loader` to remove class methods from marked

**Comment by cary-hu** [comment]
Have tried add babel.config.json
```
{
  "plugins": ["@babel/plugin-proposal-class-properties"]
}
```

and update webconfig
```
module.exports = {
  ...
  module: {
    rules: [
      ...
      {
        test: /\.js$/,
        use: {
          loader: 'babel-loader',
          options: {
            presets: ['@babel/preset-env'],
          },
        },
        exclude: /node_modules/,
        include(path) {
          if(path.includes("marked")) {
            return true
          }
          return false
        }
      },
      ...
    ],
  },
  ...
};
```

but not take effect.

**Comment by UziTech** [comment]
This sounds like a question for webpack

**Comment by cary-hu** [comment]
Thanks a lot, I have fixed this issue by update my webpack config, here is an demo.
[webpack-test.zip](https://github.com/markedjs/marked/files/12287229/webpack-test.zip)
