### ISSUE TITLE
Angular import marked error

### ISSUE THREAD

**Issue by unsky559** [markedjs/marked#2926]
**Marked version:** 7.0.1

**Describe the bug**
When I trying to add Marked into my Angular project I got that errors:

```
Error: node_modules/marked/lib/marked.d.ts:449:5 - error TS1383: Only named e
xports may use 'export type'.

449     export type * from "MarkedOptions";
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/marked/lib/marked.d.ts:450:5 - error TS1383: Only named e
xports may use 'export type'.

450     export type * from "rules";
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/marked/lib/marked.d.ts:451:5 - error TS1383: Only named e
xports may use 'export type'.

451     export type * from "Tokens";
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

```

Here is my component`s code fragments:
```
import {marked} from "marked";
```
```
updateNode(update: HTMLParagraphElement){
    this.node.content = update.innerText;

    this.parsedContent = marked.parse(update.innerText);
  }
```

**Comment by UziTech** [comment]
Seems like it is probably something to do with your tsconfig. Can you create a minimal repo so I can try to recreate this error?

**Comment by unsky559** [comment]
Shure! There it is: https://github.com/unsky559/t012
See the `Editable` component in `src\app\editable\editable.component.ts`
Please, use `ng serve` or `npm run start` for start local server

**Comment by UziTech** [comment]
looks like this was fixed in typescript v5 https://github.com/microsoft/TypeScript/issues/37238

**Comment by mcdurdin** [comment]
Yes, these types were [introduced in 7.0.1](https://github.com/markedjs/marked/compare/v7.0.0...v7.0.1#diff-32d87a2bc59f429470ccf7afc8ae8818914d4d45c3f7c5b1767c6a0a240b55c9R449-R451). This forces dependents to be on Typescript 5.0+ in order to use Marked 7.0.1+, which is unfortunate.

**Comment by unsky559** [comment]
Thank you all. I have updated my Typescript and Angular version so that solved my issue.
