### ISSUE TITLE
Safari under v15 doesn’t recognise #method 

### ISSUE THREAD

**Issue by tluyben** [markedjs/marked#2930]
In the latest version, older versions of safari complain about not being able to parse #parseMarkdown and #onError and such. Is there a setting for poly fills or something I need to use? I wouldn’t know exactly how that works, but it seems to fail on any version under 15.

The error is;

SyntaxError: Unexpected private name #parseMarkdown. Cannot parse class method with private name.

**Comment by UziTech** [comment]
See #2925
