### ISSUE TITLE
Allow `escape` function to be imported by external modules

### ISSUE THREAD

**Issue by baseplate-admin** [markedjs/marked#2933]
**What pain point are you perceiving?.**
I want to override this block : 

https://github.com/markedjs/marked/blob/f10fc84b80299c78f8ee044067d12d808dd0d902/src/Renderer.ts#L18-L42

But the `escape` function is not exported from `marked` : 
https://github.com/markedjs/marked/blob/f10fc84b80299c78f8ee044067d12d808dd0d902/lib/marked.cjs#L61-L73

**Describe the solution you'd like**
I want marked to export the `escape` function in it's output

**Comment by UziTech** [comment]
See https://github.com/markedjs/marked/issues/1650#issuecomment-617429229
