### ISSUE TITLE
marked.use isn't respecting the postprocess option

### ISSUE THREAD

**Issue by audiodude** [markedjs/marked#2939]
**Marked version:**
4.3.0

**Describe the bug**
The code `marked.use({postprocess: ...})` doesn't seem to work.

**To Reproduce**
```
import { marked } from 'marked';

marked.use({ postprocess: () => '' });

const md = 'This is markdown';
console.log(marked.parse(md));
```

Expected output: `''` (empty string)
Actual output: `'<p>This is markdown</p>\n'`

**Comment by UziTech** [comment]
`postprocess` should be in the `hooks` option. It should be:

```js
marked.use({ hooks: { postprocess: () => '' } });
```

**Comment by audiodude** [comment]
Thanks so much!

I think the documentation is a bit unclear:

```
marked.use({ hooks });
```

Looks too similar to:

```
marked.use(hooks);
```

Which is what I was doing.
