### ISSUE TITLE
Documentation: Missing documentation for options to marked.lexer and marked.parser

### ISSUE THREAD

**Issue by audiodude** [markedjs/marked#2945]
**Marked version:**
4.3.0

**Describe the bug**
The documentation at https://marked.js.org/using_pro#lexer demonstrates that `marked.lexer` and `marked.parser` both take an `options` parameter, but there is no documentation that I could find on what those options are. Looking through the code for these options is difficult.

**To Reproduce**
https://marked.js.org/using_pro#lexer

**Expected behavior**
The available options should be documented.

**Comment by UziTech** [comment]
The options are documented at https://marked.js.org/using_advanced#options

**Comment by audiodude** [comment]
I guess it's not clear from the documentation, as written, that these options are the same as the `marked.use` options. Thanks!
