### ISSUE TITLE
Preserve original text and position in lexer tokens and de-coupling parsing from HTML generation

### ISSUE THREAD

**Issue by bjeanes** [markedjs/marked#296]
Marked is really well written and has quite an approachable codebase. I'd like to leverage what's here for lexing and parsing markdown, but not outputting to HTML. However, as it is, I can't quite do so. 

I'm trying to do something akin to syntax highlighting or syntax checking. That is, I want to lex/parse markdown to get metadata about it, but apply that knowledge back to the original source (as opposed to using it to build a separate text of, say, HTML). I'm not actually building syntax highlighter, but it's a pretty close analog in terms of technical requirements.

Right now, the parser is pretty coupled to outputting HTML (instead of, say, outputting an AST and having a separate piece responsible for HTML output) and the lexer does not preserve the original text nor its location:

``` javascript
marked.lexer("* hi")
// =>
[
  {"type":"list_start","ordered":false},
  {"type":"list_item_start"},
  {"type":"text","text":"hi"}, // no attribute with "* hi"
  {"type":"list_item_end"},
  {"type":"list_end"}
] 
```

Without a way to re-build the original source text or determine its position, the metadata from the awesome lexer is only useful to HTML generation.

What do you think about including more attributes in the lexer and possibly de-coupling HTML generation from the parser?

**Comment by bpasero** [comment]
+1 for this, my use case is similar. I would like to build an AST over the markdown source code I have. Ideally I can use marked to give me semantic information about the parsed nodes in the source (e.g. all headings). I can do this today, but I cannot map the information back to the original sourcecode because linenumbers and columns are lost.

**Comment by joshbruce** [comment]
Closing for not but flagging. We're focusing on getting Marked to deliver on its promises. See #1106 and #1216.
