### ISSUE TITLE
Code block ignores Table

### ISSUE THREAD

**Issue by coderCooper** [markedjs/marked#2972]
**Marked version:8.0.0

**Describe the bug**
Table is ignored in code block.

**To Reproduce**

```
|  header   | header  |
|  ----  | ----  |
| col  | col |
| col  | col |
```

converted to
<code>
|  header   | header  |
|  ----  | ----  |
| col  | col |
| col  | col |
</code>

**Expected behavior**

<code>
<table>...</table>
</code>

**Comment by UziTech** [comment]
Oh I think I see what you are saying. You want a table rendered inside a code block.

You want
````
```
|  header   | header  |
|  ----  | ----  |
| col  | col |
| col  | col |
```
````

To be a table. But as you can see in your comment above, it isn't rendered as a table in GitHub.

Code blocks wont render the content as markdown.
