### ISSUE TITLE
Any text followed by “\n-” is parsed as a heading

### ISSUE THREAD

**Issue by Bieguni101** [markedjs/marked#2974]
**Marked version:**4.3.0、8.0.0

**Describe the bug**
Content in a special format is incorrectly processed into heading type. 
Any text followed by “\n-” is parsed as a heading.
If the input is `paragraph text\n-`, the output is parsed as `<h2 id="paragraph text">paragraph text</h2>`

**To Reproduce**
Input: paragraph text\n-
Usage:
```
import {marked} from 'marked';

const text = 'paragraph text\n-';
const html = marked.parse(text);
dom.innerHTML = html;

// the error html is <h2 id="paragraph text">paragraph text</h2>
``` 

**Expected behavior**
The expected output should not be parsed as a heading.

**Comment by calculuschild** [comment]
This is the correct behavior according to the Commonmark spec: https://spec.commonmark.org/0.30/#setext-heading

Notice how your example in GitHub is also being rendered as an H2 Header.
