### ISSUE TITLE
[9.0.0] marked.min.js does not exist.

### ISSUE THREAD

**Issue by fu-sen** [markedjs/marked#2975]
**Marked version:**
9.0.0

**Describe the bug**
marked.min.js is not output. Probably something is failing in the build operation.

**To Reproduce**
Just look at the source. There is no `marked.min.js` there.

https://cdn.jsdelivr.net/npm/marked/marked.min.js

This is maintained at Marked 8.0.1.

**Expected behavior**
`marked.min.js` should be present in the source.

**Comment by UziTech** [comment]
https://cdn.jsdelivr.net/npm/marked@9.0.0/marked.min.js seems to work

**Comment by UziTech** [comment]
And you can see the file in the npm package https://www.npmjs.com/package/marked?activeTab=code

**Comment by fu-sen** [comment]
> https://cdn.jsdelivr.net/npm/marked@9.0.0/marked.min.js seems to work

It has lost the comments that existed in previous versions. Is this output correct?

Also, this is not a solution regarding the issue `marked.min.js` in the source, which is a problem for other developers as well. I would need to keep this issues up.

**Comment by UziTech** [comment]
what is not a solution? we removed the marked.min.js in v9.0.0 on purpose see https://github.com/markedjs/marked/releases/tag/v9.0.0

I will fix the comment

**Comment by fu-sen** [comment]
> what is not a solution? we removed the marked.min.js in v9.0.0 on purpose see https://github.com/markedjs/marked/releases/tag/v9.0.0
> 
> I will fix the comment

```
/**
 * marked v8.0.1 - a markdown parser
 * Copyright (c) 2011-2023, Christopher Jeffrey. (MIT Licensed)
 * https://github.com/markedjs/marked
 */
```

There are clearly problems with this.

**Comment by UziTech** [comment]
That seems like a problem with jsdelivr. probably just cached and will fix itself in a little bit. There is nothing we can do about that.

**Comment by UziTech** [comment]
According to jsdelivr it can take a week to purge the cache unless you do it manually at https://www.jsdelivr.com/tools/purge

**Comment by UziTech** [comment]
looks like it worked.

**Comment by fu-sen** [comment]
Yeah, jsDelivr currently incurs up to 24 hours of caching. This will just have to wait.
So I needed another way to distribute the latest marked.min.js. It used to be ideal to include in GitHub sources. Marked 9.0.0 is losing it. So I take issue with that. A fundamental solution is needed.

**Comment by UziTech** [comment]
host your own version and have a lower cache time?

**Comment by fu-sen** [comment]
Hmm... If you're happy with it, you can close this issue, but I'm still dissatisfied with this response. This is because we are completely changing the way Marked has been distributed so far. This may cause trouble later on in other projects.

**Comment by UziTech** [comment]
That is why it is a major version bump
