### ISSUE TITLE
Italics failing under certain cases

### ISSUE THREAD

**Issue by AmarPrabhu** [markedjs/marked#298]
Italics fails under many conditions:
- The markdown `this is a simple _italics _without space <br>` should yield HTML:

`<p>this is a simple <em>italics </em>without space <br></p>` 

(as per http://daringfireball.net/projects/markdown/dingus)

instead marked gives me: `<p>this is a simple _italics _without space <br></p>`
- Another example of the same happening:
  Markdown: `this is another _italics_without space`
  Exp result: `<p>this is another <em>italics</em>without space<br></p>`
  Marked result: `<p>this is another _italics_without space<br></p>`
- Sometimes the parsing is completely broken:
  Markdown:

`this is a simple _italics _without space <br>
this is another _italics_without space<br>
this is yet another _italics_ with space<br>`

should yield:

```
<p>this is a simple <em>italics </em>without space <br>
this is another <em>italics</em>without space<br>
this is yet another <em>italics</em> with space<br></p>
```

Marked yields:

```
<p>this is a simple <em>italics _without space <br>
this is another _italics_without space<br>
this is yet another _italics</em> with space<br></p>
```

**Comment by joshbruce** [comment]
Closing as most likely covered by CommonMark compliance. See also #1106 and #1216
