### ISSUE TITLE
Docs: Slugger doesn't seem to be exposed anymore

### ISSUE THREAD

**Issue by rschristian** [markedjs/marked#2983]
**Marked version:**
9.0.0

**Describe the bug**
Following [the docs](https://marked.js.org/using_pro#renderer), a user should be able to do the following:

```js
import { marked } from 'marked'
const slugger = new marked.Slugger()
```

However, `Slugger` doesn't seem to be exposed anymore.

**To Reproduce**
See above

**Expected behavior**
Docs should reflect current state of lib, ideally.

**Comment by UziTech** [comment]
It is not since we removed the deprecated options. We recommend using [github-slugger](https://www.npmjs.com/package/github-slugger) instead.

**Comment by UziTech** [comment]
It looks like we need to update the docs.
