### ISSUE TITLE
Move from `terser` to `esbuild`

### ISSUE THREAD

**Issue by baseplate-admin** [markedjs/marked#2987]
**What pain point are you perceiving?.**
it seems that `marked` is using terser for bundling 

https://github.com/markedjs/marked/blob/de85e706e6dd3b3c4b2f836abc7ad8f206640045/rollup.config.js#L2

https://github.com/markedjs/marked/blob/de85e706e6dd3b3c4b2f836abc7ad8f206640045/rollup.config.js#L44

But terser is slower ( [about 10x](https://www.mehulkar.com/blog/2021/08/terser-vs-esbuild-ember-app-case-study/) ) than esbuild.

**Describe the solution you'd like**
It would be better if `marked` moved to `esbuild` + `rollup` ( or maybe `vite` ) for it's bundling process.

Rollup has : [`rollup-plugin-esbuild`](https://www.npmjs.com/package/rollup-plugin-esbuild)

Vite natively [supports esbuild](https://vitejs.dev/guide/why.html)

**Comment by UziTech** [comment]
I don't feel like our build times are a problem. They are only a couple seconds currently. I went with terser because the plugin is developed by rollup and more likely to continue being supported than a plugin created by a lone developer.

I'm ok with either. It should be easy to switch in the future if needed.

**Comment by baseplate-admin** [comment]
> I went with terser because the plugin is developed by rollup and more likely to continue being supported than a plugin created by a lone developer.

Then why not switch to [`vite`](https://vitejs.dev/)?

**Comment by UziTech** [comment]
I've never used vite, but I'm all for learning new things. Are you talking about replacing our docs with vite?

**Comment by baseplate-admin** [comment]
> I've never used vite, but I'm all for learning new things

That's something i rarely see. Most of the people are impervious to change.

> Are you talking about replacing our docs with vite?

I was talking about replacing `rollup` with `vite`

**Comment by UziTech** [comment]
Sure

**Comment by UziTech** [comment]
If it can reduces the size of the npm package I think it would be worth it. The gzip size grew dramatically after switching to typescript. Mainly because we now have to include source maps for each file.

**Comment by UziTech** [comment]
Going to close this as stale. If someone wants to create a PR and show benefits of changing we can but I don't think this is a priority.
