### ISSUE TITLE
Bold text with two * symbols causes one to be visible after parsing and removes space

### ISSUE THREAD

**Issue by iKingNinja** [markedjs/marked#2988]
**Marked version: v9.0.1**

**Describe the bug**
Writing bold text with two * symbols results in the last symbol being visible and also removes the space between the last * symbol and the next character.

**To Reproduce**
- Use marked from jsdelivr

```html
<script src="https://cdn.jsdelivr.net/npm/marked/marked.min.js"></script>
<script>
    marked.parse("**🤖┃bot-commands** hello") // Output: <p><strong>🤖┃bot-commands*</strong>hello</p> | rendered: 🤖┃bot-commands*hello
</script>
```

**Expected behavior**
The parser should not include the last * symbol in the output which means the result should be `<p><strong>🤖┃bot-commands</strong> hello</p>`

**Comment by calculuschild** [comment]
Possibly related to #2865

**Comment by iKingNinja** [comment]
@UziTech This issue is happening again when the text is a hyper link:

**[🤖┃bot-commands]((https://discord.com/channels/870575002536280074/981392899012980796)**

![immagine](https://github.com/markedjs/marked/assets/83887130/963532bf-df83-4bed-97fb-d0af209ff67c)

**Comment by iKingNinja** [comment]
> @iKingNinja can you create a new issue so we can track it? Thanks!

https://github.com/markedjs/marked/issues/3069#issue-1971022636
