### ISSUE TITLE
marked\man\marked.1.txt: No such directorynode

### ISSUE THREAD

**Issue by liudonghua123** [markedjs/marked#2990]
**Marked version: 9.0.2

**Describe the bug**
I installed the latest 9.0.2 version of marked globally on windows. Then I tried to execute `marked --help`.

```
C:\Users\Liu.D.H>marked --help
marked: output to C:\Users\Liu.D.H\AppData\Roaming\npm\node_modules\marked\man\marked.1.txt: No such directorynode:internal/errors:496
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "chunk" argument must be of type string or an instance of Buffer or Uint8Array. Received an instance of Error
    at new NodeError (node:internal/errors:405:5)
    at _write (node:internal/streams/writable:322:13)
    at Writable.write (node:internal/streams/writable:344:10)
    at main (file:///C:/Users/Liu.D.H/AppData/Roaming/npm/node_modules/marked/bin/main.js:267:24) {
  code: 'ERR_INVALID_ARG_TYPE'
}

Node.js v20.3.0

C:\Users\Liu.D.H>
```

![image](https://github.com/markedjs/marked/assets/2276718/f3536860-5131-4511-969a-9115141ef418)

**To Reproduce**

1. npm i -g marked
2. marked --help

**Expected behavior**

Show the help correctly.

**Comment by liudonghua123** [comment]
I went through the code and found the error came from here.

https://github.com/markedjs/marked/blob/5d836978efda871a5468f248a5b94087711f3a01/bin/main.js#L24-L45

And from the build script, I found man file generated, no txt.

https://github.com/markedjs/marked/blob/5d836978efda871a5468f248a5b94087711f3a01/package.json#L80-L99

**Comment by UziTech** [comment]
Nice catch! we changed it to `marked.1.md` in v9

**Comment by liudonghua123** [comment]
Thanks for the quick response and nice work. 😄
