### ISSUE TITLE
better typing  for node16 TSC

### ISSUE THREAD

**Issue by Yimiprod** [markedjs/marked#2997]
I have this error spawning when i put `module` with the value `Node16` and `moduleResolution` to `Node16`
Given this typescript configuration:

```jsonc
{
  "compilerOptions": {
    "target": "ES2022",
    "module": "Node16",
    "moduleResolution": "Node16",
    "lib": ["ES2022"],
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,
    "types": ["node", "jest"]
  },
  "ts-node": {
    "transpileOnly": true,
    "require": ["typescript-transform-paths/register"]
  },
  "exclude": ["node_modules"],
  "include": ["src"]
}
```

with this import
```ts
import { marked } from 'marked';
```

Here's the message received.
<img width="744" alt="image" src="https://github.com/markedjs/marked/assets/2227867/d5eb33da-2b36-4ed5-8d67-3537342e7459">

I have installed @types/marked as said in the documentation.

**Comment by UziTech** [comment]
`@types/marked` isn't needed any more. We need to update our docs.

**Comment by Yimiprod** [comment]
I know it has been closed but, after uninstalling `@types/marked` we still having the error at compile and in VSCode
