### ISSUE TITLE
Feature Request - Convert ==text like this== to <mark>text like this</mark>

### ISSUE THREAD

**Issue by eliabexp** [markedjs/marked#3001]
## Feature Request

Hi there! First of all, I want to express my appreciation for the fantastic work you've done with the Marked library. It's been an incredibly useful tool for converting Markdown to HTML, and I've been enjoying using it.

However, I'd like to suggest a new feature that I believe would be a valuable addition to the library. I've often encountered the need to convert text enclosed in double equal signs (==like this==) into HTML `<mark>` elements (e.g., <mark>like this</mark>).

This feature would be especially helpful for highlighting and emphasizing specific content within a document when translating Markdown to HTML. It could enhance the library's versatility and usability.

I would greatly appreciate it if you could consider implementing this feature in a future release. If you have any questions or need further clarification, please feel free to reach out. 

Thank you for your hard work on Marked, and I look forward to your response!

Thank you!

**Comment by UziTech** [comment]
We keep core marked focused on following the [GFM](https://github.github.com/gfm/) and [CommonMark](https://spec.commonmark.org/0.30/) specs, but this would be a good idea for an [extension](https://marked.js.org/using_pro#extensions).
