### ISSUE TITLE
Support GFM Alerts

### ISSUE THREAD

**Issue by lacymorrow** [markedjs/marked#3010]
**Describe the feature**
[Github has added support for markdown alerts](https://github.com/orgs/community/discussions/16925). Is it possible for marked to support these as well?

> [!NOTE]  
> Like this

> [!IMPORTANT]  
> OR THIS!

> [!WARNING]  
> (...or this)

**Comment by UziTech** [comment]
Ya that should be easy to support as an extension. The problem with most of those GFM features is that they are not in the [GFM spec](https://github.github.com/gfm/) so edge cases are difficult to figure out what it is supposed to act like especially when they conflict with other things in the spec. If it is an extension I stead of in core marked that is a way for people to opt into those conflicts.

**Comment by bent10** [comment]
You might want to give the [`marked-alert`](https://github.com/bent10/marked-extensions/tree/main/packages/alert) extension a try 🚀

**Comment by UziTech** [comment]
Thanks @bent10 for the great extensions.

**Comment by bent10** [comment]
You're very welcome, dude! 💯😊

**Comment by lacymorrow** [comment]
Awesome, Thanks @bent10

**Comment by sbrl** [comment]
Is it possible to use `marked-alerts` via the CLI only?

**Comment by UziTech** [comment]
See https://marked.js.org/using_advanced#cli-extensions
