### ISSUE TITLE
Consider nominating @UziTech for a GitHub Star

### ISSUE THREAD

**Issue by styfle** [markedjs/marked#3011]
**What pain point are you perceiving?.**

For those of you that don't know, @UziTech has been working on Marked with little to no recognition for 5+ years taking it through 9 semver major releases.

https://github.com/markedjs/marked/graphs/contributors

**Describe the solution you'd like**

To the 389 people watching this repo, and the 1+ million people that depend on Marked, you can nominate @UziTech here:

https://stars.github.com/nominate/

Thanks! 🎉

**Comment by UziTech** [comment]
Thank you! I really appreciate it. I am glad we have a great team.

**Comment by vraj79** [comment]
Done
