### ISSUE TITLE
Removing existing options in favor of the renderer

### ISSUE THREAD

**Issue by chjj** [markedjs/marked#302]
We have the opportunity to remove:
- highlight
- langPrefix
- headerPrefix
- heading IDs

In favor of the new renderer.

The downside to this (at least for 3 of them): lack of backward compatibility, and less convenience for users used to marked. While I did merge the renderer, I'm **tentatively** reimplementing a few of these options. I think the removal of these features should be discussed in another issue because it is a big decision.

cc @lepture

**Comment by birendra-ideas2it** [comment]
how to give blockquote regular expression like slack?
