### ISSUE TITLE
Proposal:  a `data` feature for sharing information across extensions

### ISSUE THREAD

**Issue by bent10** [markedjs/marked#3039]
**What pain point are you perceiving?**

The objective of this proposal is to introduce a `data` feature that allows us to share information across extensions using a key-value pairs object.

**Describe the solution you'd like**

- Introduce a `data` object that can be accessed within any extension

- The `data` is essentially a key-value pairs object where extensions can set and retrieve data

- Extensions can use a simple API to set and retrieve data in the `data` object through the `walkTokens`, pre/post hooks, and custom `extensions` fields (specifically, `tokenizer` and `renderer`)
  
  An extension can set data like this:

  ```js
  this.setData('foo', 'bar')
  ```
  
  Then we can retrieve the data set:

  ```js
  this.getData()  // returns {foo: 'bar'}
  this.getData('foo')  // returns 'bar'
  ```

- The `data` will be scoped to the current Marked instance to prevent conflicts between extensions in different instances

**Benefits:**

- Enhanced Collaboration
- Access and utilize data from other extensions (Extensibility)
- Ability to pass context or configuration data among different extensions

**Comment by UziTech** [comment]
All of those benefits seem possible without marked being the holder of this data object. For example the marked-gfm-heading-id extension provides a list of the headings for a table of contents extension to use.

What is the benefit of marked holding this information if marked isn't using any of it?
