### ISSUE TITLE
Hashtags should be removed from output

### ISSUE THREAD

**Issue by elmeister** [markedjs/marked#3048]
**Marked version:**
9.1.2

**Describe the bug**
The following content
```
Hashtags test
####
End of test
```
Is being parsed as
```html
<p>Hashtags test<br>####<br>End of test</p>
```

Every other Markdown parser I tested will not output hashtags, so something like this is expected
```html
<p>Hashtags test<br><br>End of test</p>
```

**To Reproduce**
```typescript
marked.parse('Hashtags test\n####\nEnd of test')
```

[Marked Demo](https://marked.js.org/demo/?text=Hashtags%20test%0A%23%23%23%23%0AEnd%20of%20test%0A&options=%7B%0A%20%22async%22%3A%20false%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22extensions%22%3A%20null%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22hooks%22%3A%20null%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%0A%7D&version=9.1.2)

**Expected behavior**
Expected output is one that is produced by [commonmark.js](https://spec.commonmark.org/dingus/)
```
Hashtags test

End of test
```

**Comment by UziTech** [comment]
[CommonMark](https://spec.commonmark.org/dingus/?text=Hashtags%20test%0A%23%23%23%23%0AEnd%20of%20test%0A) outputs `<p>Hashtags test</p><h4></h4><p>End of test</p>`. It is seen as an empty heading.

You can fix it in marked by adding a blank line before it or a space after the hashtags. [demo](https://marked.js.org/demo/?text=Hashtags%20test%0A%23%23%23%23%0AEnd%20of%20test%0A%0AHashtags%20test%0A%0A%23%23%23%23%0AEnd%20of%20test%0A%0AHashtags%20test%0A%23%23%23%23%20%0AEnd%20of%20test%0A&options=%7B%0A%20%22async%22%3A%20false%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22extensions%22%3A%20null%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22hooks%22%3A%20null%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%0A%7D&version=9.1.2)

**Comment by elmeister** [comment]
Thank you for the advice @UziTech 
Unfortunately it's AI-generated content and adding another parser before the marked one doesn't look promising

**Comment by UziTech** [comment]
This looks like it should be easy to fix in marked. I'll release a fix soon.
