### ISSUE TITLE
Unexpected token: punc (.)

### ISSUE THREAD

**Issue by kubasanitrak** [markedjs/marked#3049]
**Marked version:**9.1.0

**Describe the bug**
Wnen trying to build react project by running 'yarn build' I get the following error:
/Users/me/Git-projects/project-folder/node_modules/marked/lib/marked.umd.js: Unexpected token: punc (.)

**Expected behavior**
I would like to know, what to do to remove this error and be able to build the project

**Comment by UziTech** [comment]
Looks like you have an extension that is causing the error. What extensions are you using? Can you create a minimal repo that reproduces this error?

**Comment by kubasanitrak** [comment]
Hello, here's link to public repo that should do: [https://github.com/kubasanitrak/minimal-repo](url)

**Comment by UziTech** [comment]
Seems like this is an issue with uglifyjs not marked. I don't know why it lists marked.umd.js as the file when line 1633 is a comment

https://www.google.com/search?q=Unexpected+token%3A+punc+(.)

**Comment by UziTech** [comment]
Probably has something to do with marked using [optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) (`?.`) which is a new feature uglifyjs doesn't know how to handle.

**Comment by UziTech** [comment]
Looks like the error actually comes from terser `/node_modules/terser/dist/bundle.min.js:1:525`

**Comment by kubasanitrak** [comment]
Oh, that's uhm surprising. I am sorry for the inconvenience and thank you for letting me know.
