### ISSUE TITLE
Weird table doesn't render like github markdown file preview

### ISSUE THREAD

**Issue by Kuinox** [markedjs/marked#3057]
**Marked version: 9.1.2**

**Describe the bug**
I redacted this thinking it was a marked bug, but the result markdown of the issue surprised me...  
For some reason, github render
```
---
layout: post
title:  "When to send a command or call a method?"
date:   2023-01-22 17:00:00 +0100
categories: api design
---
```
Into a table here: https://github.com/Kuinox/Blog/blob/master/_posts/2023-01-22-command-or-method.markdown  
But only in this markdown file, not in the issues.  
Any insight why ?  
I'm trying to use marked to extract this table content in JS.

**Comment by UziTech** [comment]
GitHub renders markdown files differently than comments. For example a single line break in a comment is on a new line but in a markdown file it is not.

**Comment by Kuinox** [comment]
Is there a way to get the rendering like GitHub files ?

**Comment by Kuinox** [comment]
Is there a way to get the rendering like GitHub files ?
