### ISSUE TITLE
Output with `--gfm` flag is same as without the flag

### ISSUE THREAD

**Issue by banool** [markedjs/marked#3062]
**Marked version:**
9.1.3

**Describe the bug**
It seems like the `--gfm` flag doesn't do anything.

**To Reproduce**
Install marked:
```
npm install -g marked
```

Run marked without `--gfm`:
```
marked input.md -o output.html
```

Run marked with `--gfm`:
```
marked --gfm input.md -o output-gfm.html
```

See that the files are identical:
```
$ diff output.html output-gfm.html
$
```

The input file in question: https://gist.github.com/banool/bdf4ee28ac1ee0de17b67be054d4d165.

**Expected behavior**
The GFM version should look roughly like how GitHub renders md files as HTML.

**Comment by UziTech** [comment]
GFM is on by default. You can turn it of with `--no-gfm`. GFM and CommonMark (no GFM) are very similar so their output will mostly look the same with a few differences.

**Comment by banool** [comment]
Oh I see, I was expecting --gfm would introduce a stylesheet to make the HTML look GitHub-like. Is that not the case? If so feel free to close this out!

**Comment by UziTech** [comment]
No marked does not provide any stylesheets just the html
