### ISSUE TITLE
Heading doesn't contain the `id`

### ISSUE THREAD

**Issue by Arpita-Jaiswal** [markedjs/marked#3067]
**Marked version:** 9.1.4

**Describe the bug**
The markdown heading gets converted into relevant heading tag in html but it doesn't add `id` attribute which it used to do earlier in `marked v5.1.1`.

**To Reproduce**

```html
<!doctype html>
<html>
<head>
  <meta charset="utf-8"/>
  <title>Marked in the browser</title>
</head>
<body>
  <div id="content"></div>
  <script src="https://cdn.jsdelivr.net/npm/marked/marked.min.js"></script>
  <script>
    document.getElementById('content').innerHTML =
      marked.parse('# Marked in the browser');
  </script>
</body>
</html>
```

The above code generates 
```html
<h1>Marked in the browser</h1>
```

**Expected behavior**
In marked v5.1.1, it used to generate:
```html
<h1 id="marked-in-the-browser">Marked in the browser</h1>
```

**Comment by UziTech** [comment]
You have to use the extension [marked-gfm-heading-id](https://github.com/markedjs/marked-gfm-heading-id)

**Comment by Arpita-Jaiswal** [comment]
@UziTech This is working. Thanks.
