### ISSUE TITLE
Issue to convert markdown if there are html tags before markdown

### ISSUE THREAD

**Issue by ValWitco** [markedjs/marked#3068]
**Marked version:**
9.1.2

**Describe the bug**
Given this input:
"\<h1\>test\</h1\>
\*\*test\*\*"

the markdown still contains the * but it should format the text instead

here's the example [Marked Demo](https://marked.js.org/demo/?text=%3Ch1%3Etest%3C%2Fh1%3E%0A**test**%0A%0A%3Ch1%3Etest%3C%2Fh1%3E%0A%0A**test**&options=%7B%0A%20%22async%22%3A%20false%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22extensions%22%3A%20null%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22hooks%22%3A%20null%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%0A%7D&version=9.1.4)

**Comment by UziTech** [comment]
This matches CommonMark output [demo](https://spec.commonmark.org/dingus/?text=%3Ch1%3Etest%3C%2Fh1%3E%0A**test**%0A%0A%3Ch1%3Etest%3C%2Fh1%3E%0A%0A**test**)

Block html tokens don't get parsed as markdown and don't end until there is a new line according to the [spec](https://spec.commonmark.org/0.30/#html-blocks).
