### ISSUE TITLE
Parsing error when running eslint

### ISSUE THREAD

**Issue by hipkiss91** [markedjs/marked#3071]
**Marked version:**

**Describe the bug**
```
Error while parsing C:\project_name\node_modules\marked\lib\marked.esm.js
Line 2015, column 29: Unexpected token =
```
`Parse errors in imported module 'marked': Unexpected token = (2015:29)  import/namespace`
Imported into my Vue component as `import { marked } from 'marked';`
Version: `"marked": "^9.1.4",`

Used as:
```
  const renderer = new marked.Renderer();

  renderer.link = (href, title, text) => {
    return `<span>${text}</span>`;
  };

  const html = marked(data, { renderer, });
```

I had a look at the `marked.esm.js` file and it seems that the `marked` project isn't setting up its classes correctly? I do not have this issue with any other package import in the project.

Eslint config:
```
module.exports = {
  root: true,
  extends: [
    '@nuxt/eslint-config',
    'plugin:vue/vue3-recommended',
    '@nuxtjs',
  ],
  ignorePatterns: [
    '.nuxt/**',
    '.output/**',
    '.public/**',
    'dist/**',
    'node_modules/**/*',
  ],
  rules: {

  },
};
```

**To Reproduce**
Run `npm run lint`
`"lint": "eslint .",`

**Expected behavior**
No error to be presented when running the linter.

**Comment by UziTech** [comment]
Sounds like an issue with eslint or the vue plugin. If you run`npm run lint` from our repo it works fine.

**Comment by hipkiss91** [comment]
Still having this issue, with updated nuxt config and upgraded packages. Is anyone else seeing this issue?

**Comment by UziTech** [comment]
Maybe you can ask in the next or eslint repo
