### ISSUE TITLE
strong tag invalid when it contains %

### ISSUE THREAD

**Issue by hqqxxf** [markedjs/marked#3072]
**Marked version:**
9.1.4
**Describe the bug**
```
inputStr = '**3%**test'
//expect 
output = "<p><strong>3%</strong>test</p>"
//but actually 
output = "<p>**3%**test</p>"
```

**To Reproduce**
[demo](https://marked.js.org/demo/?text=**3%25**test&options=%7B%0A%20%22async%22%3A%20false%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22extensions%22%3A%20null%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22hooks%22%3A%20null%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%0A%7D&version=9.1.4)

**Comment by UziTech** [comment]
marked renders the same as CommonMark. [demo](https://spec.commonmark.org/dingus/?text=**3%25**test)

If you add a space before `test` it will work
