### ISSUE TITLE
Using blobs with walkTokens results in stripped img src

### ISSUE THREAD

**Issue by jblyberg** [markedjs/marked#3085]
**Marked version:**
9.1.5

**Describe the bug**
Using blobs with walkTokens results in the img src being stripped from the rendered output

**To Reproduce**
```
const walkTokens = (token) => {
    if (token.type === 'image') {
        token.href = "blob:http://mysite/75647557-f25e-43ab-bd42-02263748f3ed" // provided this blob exists
    }
};

marked.use({walkTokens});
```

**Expected behavior**
Rendered output should include `src="blob:http://mysite/75647557-f25e-43ab-bd42-02263748f3ed"`. No src attribute is present.

**Comment by UziTech** [comment]
Seems to work for me. Can you create a repo that will reproduce this?

```js
import { marked } from "marked";

const walkTokens = (token) => {
    if (token.type === 'image') {
        token.href = "blob:http://mysite/75647557-f25e-43ab-bd42-02263748f3ed" // provided this blob exists
    }
};

marked.use({walkTokens});

marked.parse("![image](http://image)");
```

```html
<p><img src="blob:http://mysite/75647557-f25e-43ab-bd42-02263748f3ed" alt="image"></p>
```

**Comment by jblyberg** [comment]
I'm still experiencing this issue within our app where the marked instantiation is isolated from everything else, but I will plan  to recreate in a separate repo when I get a few moments.

**Comment by UziTech** [comment]
It sounds to me like you have some sanitization going on. Marked returns the img with blob in src then your sanitizer removes the src attribute.

**Comment by jblyberg** [comment]
That's exactly what happened. Thanks for helping me figure it out!
