### ISSUE TITLE
Won't load on safari

### ISSUE THREAD

**Issue by McBen** [markedjs/marked#3086]
Marked can't be loaded on Safari.

looks like static class fields are not supported, 'cause this line
https://github.com/markedjs/marked/blob/dc484fe30a1aa1e2bd111ed6f9f540f2b999eb9a/src/Hooks.ts#L11
will create an error message
(I'm not running an apple system by myself but was able to repdroduce it on an emulator)

see also:
https://medium.com/@francesca.dreith/refactoring-class-fields-out-for-safari-compatibility-112c100fb5ea

**Comment by UziTech** [comment]
Looks like it has been supported since safari 14. https://caniuse.com/mdn-javascript_classes_static_class_fields

If you need to support older browsers you can use Babel to transpile marked.

**Comment by McBen** [comment]
yes, your right. my emulator only runs safari 13 (2020).
It was my approach to reproduce a bug report from one of my users (uses Safari 14).

It all started when upgrading from marked v4.3.0 to v5.0.4.
(rolled back to v4.3, then upgrade to v8, but looks like v4.3 is the last one working)

now I'm lost. I'll downgrad again and hope it will work.
