### ISSUE TITLE
marked.parseInline() returns string | Promise<string> even when { async: false }

### ISSUE THREAD

**Issue by cprcrack** [markedjs/marked#3101]
**Marked version:** 10.0.0

**Describe the bug**
`marked.parseInline("markdown", { async: false })` returns a `string | Promise<string>`.

**Expected behavior**
`marked.parseInline("markdown", { async: false })` should return a `string`. This is already the case with `marked.parse("markdown", { async: false })`

**Comment by cprcrack** [comment]
I only use this `parseInline()` method because `parse()` adds surrounding <p> tags to the output, which I don't want. I don't use any extension and it's a pain in the ass constantly having to write `as string`.

Why doesn't `parse()` suffer from the same issue? Does that method not support extensions? Shouldn't maybe an extension fail if you specify `async: false` and the extension cannot run synchronously? Not being able to predict the return type for the most basic usage of the method without any extensions seems a little bit poor regarding Typescript support.

Any other workaround to not have to do unsafe `as string` casting? Or any other way I can help?

**Comment by UziTech** [comment]
Parse does the same thing. I think the types are wrong there. Unfortunately typescript isn't smart enough to know if an extension sets `async: true`.

The way that typescript recommends using typescript in this situation is to use `as string` if you know there are no async extensions or always await the output (will work even for string)

**Comment by cprcrack** [comment]
Got it, it's a shame that Typescript cannot figure it out. I hoped that it may be something that could be easily fixed.

Thanks for the tip, didn't thought I could await a regular string, but that works and I prefer it to having unsafe castings. That way if I add an extension in the future (whatever those are for 😆) it will continue to work.
