### ISSUE TITLE
Code block inside code block

### ISSUE THREAD

**Issue by JustDoItSascha** [markedjs/marked#3102]
**Marked version: 10.0.0**

**Describe the bug**
When I have markdown code inside a markdown code block, it's getting rendered wrong. Maybe I'm stupid, but I have no idea how to fix it and searched the whole documentation and the issues here. Please ignore the backslashes \ in my demo, otherwise it wouldn't even work here in github. Maybe it's a general markdown problem. But I just thought if there is a way to fix that?

**To Reproduce**

```markdown
\```markdown
  blah blah blah
  
  ```bash
   do this, do that
  \```

  Conclusion
\```
```

**Expected behavior**
To render it like in the example, but without the backslashes.

**Comment by UziTech** [comment]
You can use 4 backticks if you need 3 backticks in the markdown [demo](https://marked.js.org/demo/?text=%60%60%60%60markdown%0A%20%20blah%20blah%20blah%0A%20%20%0A%20%20%60%60%60bash%0A%20%20%20do%20this%2C%20do%20that%0A%20%20%60%60%60%0A%0A%20%20Conclusion%0A%60%60%60%60&options=%7B%0A%20%22async%22%3A%20false%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22extensions%22%3A%20null%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22hooks%22%3A%20null%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%0A%7D&version=10.0.0) [spec](https://spec.commonmark.org/0.30/#fenced-code-blocks)

`````markdown
````markdown
  blah blah blah
  
  ```bash
   do this, do that
  ```

  Conclusion
````
`````
