### ISSUE TITLE
id disapear after markdown parsing 

### ISSUE THREAD

**Issue by alcaidio** [markedjs/marked#3104]
Describe the feature
Enable the addition of IDs to Markdown elements for unique identification.
`"# heading {#custom-id}"
`
Why is this feature necessary?
Facilitates easier linking and referencing within Markdown documents, especially useful for larger documents and technical writing.

**Describe alternatives you've considered**
Use html in markdown, but i dont know why id disappear.

**Comment by UziTech** [comment]
You can use the [marked-custom-heading-id](https://www.npmjs.com/package/marked-custom-heading-id) extension to do this.
