### ISSUE TITLE
use <br> with CRLF line endings wrong output

### ISSUE THREAD

**Issue by Nothing-Works** [markedjs/marked#3105]
**Marked version:** ^10.0.0

**Describe the bug**
when using CRLF line endings `\r\n`, with `<br>` it has wrong output.

**To Reproduce**
```js
const { marked } = require("marked");

const rn = marked.parse("<br>\r\n#### Introduced\r\n\r\n5.0.5.1\r\n");
const n = marked.parse("<br>\n\n#### Introduced\n\n5.0.5.1\n");

console.log(rn);
console.log(n);

```
![image](https://github.com/markedjs/marked/assets/18606648/91a6e5c7-4c69-42db-adbd-b7d66585d09e)

**Expected behavior**
As the pic shows, the one with `<br>\r\n` did not render `<h4>` it has #### Introduced instead. I've also tried `markdown-it` which I believe is the underlying library to parse markdown, and that library does not have the problem.

---
This is when I tried `markdown-it`.

```js
var MarkdownIt = require("markdown-it"),
    md = new MarkdownIt();
var rn = md.render("<br>\r\n#### Introduced\r\n\r\n5.0.5.1\r\n");
var n = md.render("<br>\n\n#### Introduced\n\n5.0.5.1\n");

console.log(rn);
console.log(n);
```

And here is the output.
![image](https://github.com/markedjs/marked/assets/18606648/21376741-8950-43c1-b723-9f4fa17c2f13)

**Comment by UziTech** [comment]
Marked tries to follow the [commonmark spec](https://spec.commonmark.org/0.24/#html-blocks)

The heading and <br> do not have a blank line between them with crlf so the heading is actually part of the html block. Markdown-it does not follow commonmark by default.

**Comment by Nothing-Works** [comment]
@UziTech `<br>` is not on the list tho

**Comment by Nothing-Works** [comment]
@UziTech you mean my example is within type 6 right? and it needs a blank line to finish but `<br>` is not on the list tho.
![image](https://github.com/markedjs/marked/assets/18606648/3aaa1715-7421-4b11-98bc-2a409e4bcd7b)

**Comment by UziTech** [comment]
No `<br>` would be a type 7 since it is not in the type 6 list

**Comment by Nothing-Works** [comment]
@UziTech one more question, 
```js
const result = marked.parse("Andy\r\n<br>");
```
this output is `<p>Andy<br></p>`, with two `\r\n\r\n` it works, so start condition also needs a blank line?

**Comment by Nothing-Works** [comment]
@UziTech and it seems like it's only a problem when it's a <p> tag

so when I have 
```js
const result = marked.parse("### Andy\r\n<br>");
```
the result is
```html
<h4>Andy</h4>
<br>
```

**Comment by UziTech** [comment]
Yes, that is intended behavior because an HTML block can't break a paragraph. [CommonMark demo](https://spec.commonmark.org/dingus/?text=Andy%0D%0A%3Cbr%3E)

**Comment by Nothing-Works** [comment]
@UziTech so this is just spec?

**Comment by UziTech** [comment]
yes

**Comment by Nothing-Works** [comment]
@UziTech ok, thanks very much, so to summarise, if I have `<p>` tags both before and after `<br>` then I have to make sure that I have blank lines before and after `<br>`, am I correct?

**Comment by UziTech** [comment]
In order to be well formatted markdown, you should have a blank line before and after every block level element. There are exceptions for historical reasons but different markdown parsers could parse it differently.

**Comment by Nothing-Works** [comment]
@UziTech ok, thanks.

**Comment by Nothing-Works** [comment]
@UziTech so a `<br>` is not a block level element, but when it has a blank line blow then it becomes a HTML block, would it be a block level emelemnt?

**Comment by UziTech** [comment]
There is an html block element and an html tag (inline) element. You can read about them more in the spec.
