### ISSUE TITLE
Parsing error when using highlight.js

### ISSUE THREAD

**Issue by dyzdyz010** [markedjs/marked#311]
I'm using `marked` with `Angular.js`. When I create a code block, if I type the language wrong like this: 

``````
```wrongLanguage
print "Hello"
```
``````

Then an error will occur:

![2013-12-17 17 02 39](https://f.cloud.github.com/assets/1324420/1762640/39b50db8-66fa-11e3-8799-d1d84302bb4c.png)

**Comment by shuhei** [comment]
I had to write `!!(lang && hljs.getLanguage(lang))` for the condition with highlight.js 8.8.0 because it no longer has `LANGUAGES` property.

**Comment by JimmyLv** [comment]
@shuhei Cool~  Thanks very much!
