### ISSUE TITLE
Proposal: mark-down html element

### ISSUE THREAD

**Issue by lnsy-dev** [markedjs/marked#3125]
I have written an html element that uses the marked library: 

https://github.com/lnsy-dev/markdown-component

A demo: https://lnsy-dev.github.io/markdown-component/

It's code is very simple: 

```js
class MarkdownComponent extends HTMLElement {
  connectedCallback(){
    this.src = this.getAttribute('src'); 

    if(this.src === null){
      const content = this.innerHTML; 
      this.innerHTML = marked.parse(content);
    } else {
      fetch(this.src)
        .then(res => res.text())
        .then(res => {
          this.innerHTML = marked.parse(res);
        });
    }
  }
}

customElements.define('mark-down', MarkdownComponent);
```

Would this feature be beneficial to this project? 

I'm not sure, if I wanted to contribute to this project, where this code would live or what standards you need for a PR. Would love your advice!

**Comment by UziTech** [comment]
It would be great for that to be a separate package. If you want to release it on npm we can add something to our docs about it.
