### ISSUE TITLE
MiniProgramError SyntaxError: Invalid regular expression: /[\p{L}\p{N}]/: Invalid property name in character class

### ISSUE THREAD

**Issue by seepine** [markedjs/marked#3133]
**Marked version:**
4.3.0

**Describe the bug**
In Android wechat miniprogram has some error, iOS is work

MiniProgramError SyntaxError: Invalid regular expression: /[\p{L}\p{N 
<img width="398" alt="image" src="https://github.com/markedjs/marked/assets/93666053/9054c3e4-f875-4664-bce2-9419a909dcd2">

**To Reproduce**
import { marked } from 'marked'
<img width="1081" alt="image" src="https://github.com/markedjs/marked/assets/93666053/68b95ff7-8634-40a8-b14f-8d6253fc3a62">

**Expected behavior**
can work

**Comment by UziTech** [comment]
Looks like that browser doesn't support unicode properties in regex. You will need to transpile marked with Babel and https://babeljs.io/docs/babel-plugin-transform-unicode-property-regex to get it to work in that browser.

**Comment by AdonLee** [comment]
> Looks like that browser doesn't support unicode properties in regex. You will need to transpile marked with Babel and https://babeljs.io/docs/babel-plugin-transform-unicode-property-regex to get it to work in that browser.

@UziTech i have a similar problem in the latest V12.0.2， it seems that this plugin does not recognize the pattern that should be precompiled because the regexp is assembly dynamically

see in [src/rules.ts:](https://github.com/markedjs/marked/blob/master/src/rules.ts#L173)
```js
const _punctuation = '\\p{P}\\p{S}';
const punctuation = edit(/^((?![*_])[\spunctuation])/, 'u')
  .replace(/punctuation/g, _punctuation).getRegex();
```

**Comment by rento666** [comment]
把版本降到`v3.0.8`即可。
