### ISSUE TITLE
Rendering not as expected when using custom elements

### ISSUE THREAD

**Issue by mantou132** [markedjs/marked#3134]
**Marked version:**

v11.0

**Describe the bug**

When using custom elements, attribute line break causes the element to be forcibly closed

**To Reproduce**

[demo](https://marked.js.org/demo/?outputType=html&text=%3Cgbp-example%0Atitle%3D%22dy-avatar-group%22%3E%0A%0A%3C%2Fgbp-example%3E%0A%0A%0A%3Cdetails%0Atitle%3D%22dy-avatar-group%22%3E%0A%0A%3C%2Fdetails%3E&options=%7B%0A%20%22async%22%3A%20false%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22extensions%22%3A%20null%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22hooks%22%3A%20null%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%0A%7D&version=11.0.0)

**Expected behavior**

```html
<gbp-example
title="dy-avatar-group">
</gbp-example>


<details
title="dy-avatar-group">

</details>
```

https://github.com/commonmark/commonmark-spec/issues/758

**Comment by UziTech** [comment]
This works according to the [spec](https://spec.commonmark.org/0.30/#html-blocks). If you successfully change the spec we can reopen this.

Alternatively you can create an extension that tokenizes html blocks different than the spec.
