### ISSUE TITLE
Issue: `tokens.links` cannot be modified before rendering

### ISSUE THREAD

**Issue by tipiirai** [markedjs/marked#3135]
Is it possible to provide custom reflinks without defining them on the page? LIke for example:

``` md
Click [here][mylink]
``` 
Where `mylink` is somehow provided externally?

Thanks for the great project!

**Comment by calculuschild** [comment]
Defined where externally? Just on a different page?

**Comment by tipiirai** [comment]
I tried to modify `tokens.links` property returned by the lexer before rendering the page, but couldn't get it to work. Just trying to find _any_ means to provide the links before rendering. Could be on a different page or given as a configuration option.

**Comment by UziTech** [comment]
You can add the reflinks to the markdown in a `preprocess` hook.

Something like:

```js
marked.use({
  hooks: {
    preprocess(markdown) {
      return markdown + '\n\n[mylink]: https://example.com/mylink';
    }
  }
});
```

**Comment by tipiirai** [comment]
The hook is not called with `marked.parser(tokens)` where the tokens are generated with `marked.lexer()`

**Comment by UziTech** [comment]
No. It is called by marked.parse(). If you are using marked.lexer you can just append the reflinks to the markdown that you pass in

**Comment by tipiirai** [comment]
Gotcha. So there is no way to parse Markdown into an abstract syntax tree, then modify the tree (links specifically), and finally render it to HTML. Like parsing & rendering usually works.

**Comment by UziTech** [comment]
Sure there are many ways you can do that, it just depends on how much you want to recreate what marked.parse does for you.

One way you can do it is to use Lexer.blockTokens to create block tokens then update links before creating inline tokens.

As you can see that isn't quite as simple as just appending reflinks to the markdown.

**Comment by tipiirai** [comment]
`Lexer.blockTokens` sounds good! How exactly I can use that for updating the links? Some sample code would be helpful. Doesn't have to work. I can work my way out from there. Thanks!

**Comment by UziTech** [comment]
You will have to essentially copy the code from Lexer.lex and add in whatever changes you want.

https://github.com/markedjs/marked/blob/0d3e9e72603d31720b6754f640eb27a672ff1d0e/src/Lexer.ts#L86

**Comment by tipiirai** [comment]
Sorry. I have no idea how to use the `blockTokens()` function.  Is it available as an API method at all?

**Comment by UziTech** [comment]
You can access the Lexer API by creating a new Lexer

```js
import { Lexer, marked} from 'marked';

const lexer = new Lexer();
const tokens = lexer.blockTokens(markdown);
// update tokens.links
...
```

**Comment by tipiirai** [comment]
Thanks. But the issue is that updating `tokens.links` has no effect. For example by setting:

```
tokens.links.foo = { href: 'bar.com }
```

And `[test][foo]` is still rendered as `[test][foo]`

**Comment by UziTech** [comment]
Can you share your whole code? It should work since that is exactly what marked does.

**Comment by tipiirai** [comment]
Here's the code:

``` js
import { marked } from 'marked'

const md = `
[This works][works]

[This doesn't][test]

[works]: works.com
`
const tokens = marked.lexer(md)

tokens.links.test = { href: 'doesnt.com'}

console.info(marked.parser(tokens))
```

And the output is

``` HTML
<p><a href="works.com">This works</a></p>
<p>[This doesn’t][test]</p>
```

**Comment by UziTech** [comment]
You aren't calling blockTokens at all?

**Comment by tipiirai** [comment]
I have no idea how to use the undocumented blockTokens method. I tried this now:

``` js
import { marked, Lexer } from 'marked'

const md = `
[This works][works]

[This doesn't][test]

[works]: works.com
`

const lexer = new Lexer()
const tokens = lexer.blockTokens(md)

tokens.links.test = { href: 'doesnt.com'}
```

But the last sentence threw an error:

``` 
TypeError: undefined is not an object (evaluating 'tokens.links.test = { href: "doesnt.com" }')
```

Can you share a code that correctly updates the links before rendering? Thanks.

**Comment by UziTech** [comment]
It seems like just appending reflinks to the markdown would be the best way to do it. If you get it working with blockTokens it could be hard to update it if we ever change the Lexer methods.

**Comment by tipiirai** [comment]
it seems appending reflinks to the markdown is the _only way_ to do this, because there is no way to modify the abstract syntax tree before rendering as I originally stated.

**Comment by UziTech** [comment]
Adding a hook between block tokens and inline tokens is something we were thinking about doing. If you wanted to create a PR for that it would be very helpful.

**Comment by UziTech** [comment]
This is one way you can currently do it with Lexer and Parser

```js
import { Marked, Lexer, Parser } from 'marked';

const marked = new Marked();

marked.use(
  // extensions
);

const markdown = `
[This works][works]

[This does too][test]

[works]: works.com
`;

const lexer = new Lexer(marked.defaults);

lexer.tokens.links.test = { href: 'doesToo.com' };

const tokens = lexer.lex(markdown);

const parser = new Parser(marked.defaults);

console.log(parser.parse(tokens));
```

But this also works and is a lot simpler:

```js
console.log(marked.parse(markdown + '\n\n[test]: doesAlso.com'));
```

**Comment by tipiirai** [comment]
Cool. I got that working. 

I agree, the JavaScript API for providing links in the AST phase is quite messy and not too user-friendly. Thre is no clear parse & render phases in Marked, which is unfortunate. I would like to do something like this (pseudocode):

``` js
import { parse, render } from 'node:marked'

// build AST
const ast = marked.parse(markdown)

// modify it
ast.doSomething()
ast.doSomethingElse()

// render with rendering options
const html = render(ast, { renderers, hooks, ... })
```

**Comment by tipiirai** [comment]
Actually the issue on the title still remains. There is no way to update the links _after_ parsing the AST, but before rendering. ie. the following does not work

``` javascript
// parse tokens (AST)
const tokens = lexer.lex(markdown);

// update tokens
tokens.links.test = { href: 'doesToo.com' };

// this doesn't work
console.log(parser.parse(tokens));
```

**Comment by UziTech** [comment]
That doesn't work because it is not supposed to work like that. The url is resolved when creating the link tokens. It would be redundant, and a waste of time, to resolve it again on parsing. I'm going to close this since there is a way to do this even if it isn't the way that you want.

**Comment by UziTech** [comment]
Also this does work

```js
import { marked } from 'marked'

// build AST
const ast = marked.lex(markdown)

// modify it
doSomething(ast)
doSomethingElse(ast)

// render with rendering options
const html = marked.parser(ast)
```

we just don't provide the `doSomething` and `doSomethingElse` functions.

If you would want to create a package that provides convenient methods for stuff to do with the ast you can.

**Comment by tipiirai** [comment]
I was about to make such convenient methods but then realized that it's impossible with the current design of Marked, which does not have a clear and modifiable syntax tree. The parsed tree is somehow "resolved" and cannot be altered.
