### ISSUE TITLE
Multiple list with sublist - <p> tag inserts seems not quite right

### ISSUE THREAD

**Issue by vvilp** [markedjs/marked#3157]
**Marked version: 11.1.1**

**Describe the bug**
Multiple List with sublist. <p> tag is added to the parent not the whole parent and sub list

**To Reproduce**
use the following 
```
- first
  + sub 1
  + sub 2

- second

- third
```

Github editor as below
- first
  + sub 1
  + sub 2

- second

- third

marked render as below
<img width="149" alt="image" src="https://github.com/markedjs/marked/assets/1350908/cd92a171-9bad-4a80-b64c-c6ea2ec70b40">
<img width="181" alt="image" src="https://github.com/markedjs/marked/assets/1350908/51e9c5db-3651-4ade-8c1f-57ddd0668b6c">

**Comment by UziTech** [comment]
This seems to be working as intended.

Our [demo](https://marked.js.org/demo/?outputType=html&text=-%20first%0A%20%20%2B%20sub%201%0A%20%20%2B%20sub%202%0A%0A-%20second%0A%0A-%20third&options=%7B%0A%20%22async%22%3A%20false%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22extensions%22%3A%20null%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22hooks%22%3A%20null%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%0A%7D&version=11.1.1) seems to output the same as [CommonMark demo](https://spec.commonmark.org/dingus/?text=-%20first%0A%20%20%2B%20sub%201%0A%20%20%2B%20sub%202%0A%0A-%20second%0A%0A-%20third)

It looks like GitHub does the same it just adds css to remove the space above the nested list.
