### ISSUE TITLE
marked parse mathematical formula error

### ISSUE THREAD

**Issue by swanfly** [markedjs/marked#3158]
**Marked version:**
v11.1.1
**Describe the bug**
marked parse mathematical formula error

**To Reproduce** 
let markdown2 = `$\\begin{matrix}
\t1 & x & x^2 \\\\
\t1 & y & y^2 \\\\
\t1 & z & z^23 \\\\
\\end{matrix}$`;
let html = marked.parse(markdown2);
console.log(html);

**console log**
<p>$\begin{matrix}
    1 &amp; x &amp; x^2 \
    1 &amp; y &amp; y^2 \
    1 &amp; z &amp; z^23 \
\end{matrix}$</p>

**should output**
<p>$\begin{matrix}
    1 &amp; x &amp; x^2 \\
    1 &amp; y &amp; y^2 \\
    1 &amp; z &amp; z^23 \\
\end{matrix}$</p>

**Comment by swanfly** [comment]
<img width="367" alt="image" src="https://github.com/markedjs/marked/assets/5317370/719c6e26-088e-40c0-8ae8-c0cd21ca9744">
<img width="230" alt="image" src="https://github.com/markedjs/marked/assets/5317370/66a38c2b-1cb0-4b64-b67d-a16ce0f4587d">

**Comment by UziTech** [comment]
Looks like you are just logging a string. What does this have to do with marked?

**Comment by UziTech** [comment]
I see you are wondering why marked removes the backslash from an escaped character. See the [CommonMark spec](https://spec.commonmark.org/0.30/#example-15)

**Comment by swanfly** [comment]
If there is a Latex formula in the markdown text, it will not be parsed correctly. Can we avoid deleting backslashes in the Latex formula string?

**Comment by UziTech** [comment]
Your can use a code block to tell markdown to not do anything to the text.

````
```
$\\begin{matrix}
 \t1 & x & x^2 \\\\
 \t1 & y & y^2 \\\\
 \t1 & z & z^23 \\\\
 \\end{matrix}$;
```
````

**Comment by swanfly** [comment]
> Looks like you are just logging a string. What does this have to do with marked?
Because this Latex formula string is within the Markdown text, if it is marked → parsed, the Latex formula string will not be able to display the formula properly.

Please refer to the following diagram
<img width="1422" alt="image" src="https://github.com/markedjs/marked/assets/5317370/1ebf2aed-59c3-4664-b354-f4d31df81710">

**Comment by joshbruce** [comment]
Latex is a different plain text format and syntax than Markdown. 

Marked parses Markdown, not Latex. 

There could be an interesting module or extension. GitHub Markdown does have a code block syntax specific to mathematical formula: https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/writing-mathematical-expressions

**Comment by swanfly** [comment]
> Your can use a code block to tell markdown to not do anything to the text.
> 
> ```
> ```
> $\\begin{matrix}
>  \t1 & x & x^2 \\\\
>  \t1 & y & y^2 \\\\
>  \t1 & z & z^23 \\\\
>  \\end{matrix}$;
> ```
> ```

You can learn about this website, it is written directly here
https://stackedit.io/app#
<img width="1351" alt="image" src="https://github.com/markedjs/marked/assets/5317370/e921f5fd-6c07-44b5-bfe4-f4943333220c">

**Comment by swanfly** [comment]
> Latex is a different plain text format and syntax than Markdown.
> 
> Marked parses Markdown, not Latex.
> 
> There could be an interesting module or extension. GitHub Markdown does have a code block syntax specific to mathematical formula: https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/writing-mathematical-expressions

Because the Latex formula may be within Markdown text, after parsing, the original content of the Latex formula should not be destroyed.

**Comment by joshbruce** [comment]
@swanfly: If you scroll down on the default content, it uses Katex - https://khan.github.io/KaTeX/ - to render Latex.

KaTeX is not part of Marked. The dollar sign ($$) is an extension of the supported spec Marked used (CommonMark).

Marked should be flexible enough to use KaTeX along with Marked. (@UziTech correct me if I'm wrong?)

**Comment by joshbruce** [comment]
@swanfly: To be sure I'm hearing you, the problem isn't that the formula is ignored?

**Comment by UziTech** [comment]
There is a katex [extension](https://marked.js.org/using_advanced#extensions) called marked-katex-extension

**Comment by swanfly** [comment]
> @swanfly: To be sure I'm hearing you, the problem isn't that the formula is ignored?

I also understand what you mean. Thank you for your answer

**Comment by swanfly** [comment]
> There is a katex [extension](https://marked.js.org/using_advanced#extensions) called marked-katex-extension

Thank you, I'll study it

**Comment by chenjiangui** [comment]
> $\\begin{matrix} \t1 & x & x^2 \\\\ \t1 & y & y^2 \\\\ \t1 & z & z^23 \\\\ \\end{matrix}$



> I see you are wondering why marked removes the backslash from an escaped character. See the [CommonMark spec](https://spec.commonmark.org/0.30/#example-15)

![image](https://github.com/user-attachments/assets/94656f09-c877-4b96-99c0-100e313d108b)
I tested it under CommonMark, and it works normally. It does not remove all escape characters.
