### ISSUE TITLE
Images? ![]()

### ISSUE THREAD

**Issue by henrysheehy** [markedjs/marked#3164]
Hello, thank you for the beautiful software! Are there plans to include image rendering?

**Comment by calculuschild** [comment]
Image syntax is already included!

[Demo](https://marked.js.org/demo/?text=!%5Bcat%5D(https%3A%2F%2Fimages.pexels.com%2Fphotos%2F45201%2Fkitty-cat-kitten-pet-45201.jpeg%3Fauto%3Dcompress%26cs%3Dtinysrgb%26w%3D1260%26h%3D750%26dpr%3D2)&options=%7B%0A%20%22async%22%3A%20false%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22extensions%22%3A%20null%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22hooks%22%3A%20null%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%0A%7D&version=11.1.1)

**Comment by henrysheehy** [comment]
That's excellent, thank you! 

I don't suppose there is any way to include local images (i.e. in the same directory structure as the index.html)?

**Comment by henrysheehy** [comment]
Ah, I see how to do it. I wasn't able to, as I am running client side js, with a flask server. Now I have to look into either using Node.js, or (better) use flask to deliver the image. Thanks again!
