### ISSUE TITLE
Token with "strong" type was not found

### ISSUE THREAD

**Issue by whalemare** [markedjs/marked#3188]
**Marked version:**
12.0.0

**Describe the bug**
When you try use `strong` instead `heading` type (like in [docs](https://marked.js.org/using_pro#walk-tokens)) marked is crashed

**To Reproduce**

```ts
  const markdown = `# Head 1`.trim()

  await marked.parse(markdown, {
    async: true,
    walkTokens: token => {
      // replace all headings with bold text
      if (token.type === 'heading') {
        token.type = 'strong'
      }
    },
  })
```

Error:
Token with "strong" type was not found.
Please report this to https://github.com/markedjs/marked.

**Expected behavior**
Expected output like:

```
<strong>Head 1</strong>
```

**Comment by UziTech** [comment]
This is because `strong` is an inline token and `heading` is a block token.

**Comment by preslavmihaylov** [comment]
Hey @UziTech how are we supposed to workaround this once it happens? 

We can't prevent users from sending markdown headers in their messages

**Comment by UziTech** [comment]
If you want to change a heading to a strong you chould change the heading to a paragraph token, then add a strong token to the tokens property on the paragraph token.

Or you can change the heading renderer to output a strong tag instead of a heading tag with the heading token.
