### ISSUE TITLE
Unexpected token = on static passThroughHooks = new Set() with Next.js

### ISSUE THREAD

**Issue by trevorwhealy** [markedjs/marked#3194]
**Marked version:**
^4.3.0

**Describe the bug**
Starting February 4, we started getting Sentry errors for `Unexpected token =`

We are using the basic and latest version of Next.js with Typescript.

<img width="321" alt="Screenshot 2024-02-12 at 1 53 30 PM" src="https://github.com/markedjs/marked/assets/14946478/b353ad5d-27c5-4947-a26a-f758a3376360">

**To Reproduce**
This appears to be coming from the `marked` node_module
<img width="499" alt="Screenshot 2024-02-12 at 1 53 48 PM" src="https://github.com/markedjs/marked/assets/14946478/a2690795-aabf-4093-83bf-feb1a7ad2a7f">

Due to this line in particular: 
`static passThroughHooks = new Set([`

We use it in a very normal way `import { marked } from "marked"` as far as I can tell.

**Expected behavior**
I assume this is a bug because a major version was pushed 9 days ago February 3 when we started getting errors.

<img width="818" alt="Screenshot 2024-02-12 at 1 57 59 PM" src="https://github.com/markedjs/marked/assets/14946478/d4e99bac-f9c4-4bdd-95b8-0b5bbbadbd67">

**Comment by UziTech** [comment]
If you are using marked ^4.3.0 you shouldn't be affected by a major release
