### ISSUE TITLE
Incorrect handling of valid HTML

### ISSUE THREAD

**Issue by kpripper** [markedjs/marked#3196]
**Marked version:**

"^11.1.1"

**Describe the bug**
```js
const { marked } = require("marked")

let message = `
    <h2>Що таке ліцензія і чому вона важлива?</h2>`

function markedMessage(message) {
  message = marked(message)
  console.log("marked message", message) 
//<pre><code>&lt;h2&gt;Що таке ліцензія і чому вона важлива?&lt;/h2&gt;</code></pre>
}

markedMessage(message)
```

**Expected behavior**
The correct option would be to return the string unchanged
`<h2>Що таке ліцензія і чому вона важлива?</h2>`

**Comment by UziTech** [comment]
You have 4 spaces in front of the html so it is an [indented code block](https://spec.commonmark.org/0.31.2/#indented-code-blocks).

If you remove the spaces it will work as expected.

**Comment by kpripper** [comment]
Thank you!

**Comment by kpripper** [comment]
Thank you!
