### ISSUE TITLE
Incorrect handling of multi-line code block

### ISSUE THREAD

**Issue by rschristian** [markedjs/marked#3199]
**Marked version:** 12.0.0

**Describe the bug**
Multi-line code blocks that contain an empty line will, for some reason, have a paragraph tag inserted into them, breaking the code block and causing the browser to fallback and handle this now malformed HTML.

Without the blank line, this works as expected.

**To Reproduce**

1. [Marked Demo](https://marked.js.org/demo/?text=%3Cdiv%3E%0A%20%20%20%20%3Cpre%20repl%3D%22false%22%3E%3Ccode%20class%3D%22lang-jsx%22%3E%0Aimport%20TodoList%20from%20%27.%2Ftodo-list%27%3B%0A%0Arender(%26lt%3BTodoList%20%2F%26gt%3B%2C%20document.body)%3B%0A%20%20%20%20%3C%2Fcode%3E%3C%2Fpre%3E%0A%3C%2Fdiv%3E&options=%7B%0A%20%22async%22%3A%20false%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22extensions%22%3A%20null%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22hooks%22%3A%20null%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%0A%7D&version=12.0.0)

> input
```html
<div>
    <pre repl="false"><code class="lang-jsx">
import TodoList from './todo-list';

render(&lt;TodoList /&gt;, document.body);
    </code></pre>
</div>
```

>output
```html
<div>
    <pre repl="false"><code class="lang-jsx">
import TodoList from './todo-list';

<p>render(&lt;TodoList /&gt;, document.body);
    </code></pre></p>
</div>
```

**Expected behavior**
This extraneous paragraph tag should not be inserted.

> expected output diffed
```diff
<div>
    <pre repl="false"><code class="lang-jsx">
import TodoList from './todo-list';

-<p>render(&lt;TodoList /&gt;, document.body);
-    </code></pre></p>
+render(&lt;TodoList /&gt;, document.body);
+    </code></pre>
</div>
```

**Comment by UziTech** [comment]
This is working as intended [CommonMark demo](https://spec.commonmark.org/dingus/?text=%3Cdiv%3E%0A%20%20%20%20%3Cpre%20repl%3D%22false%22%3E%3Ccode%20class%3D%22lang-jsx%22%3E%0Aimport%20TodoList%20from%20%27.%2Ftodo-list%27%3B%0A%0Arender(%26lt%3BTodoList%20%2F%26gt%3B%2C%20document.body)%3B%0A%20%20%20%20%3C%2Fcode%3E%3C%2Fpre%3E%0A%3C%2Fdiv%3E)

An HTML block in markdown ends with a blank line account to the [spec](https://spec.commonmark.org/0.31.2/#html-blocks).

**Comment by rschristian** [comment]
Please forgive my ignorance, but I'm a bit baffled that this could be working as intended given the HTML output is totally invalid and requires the browser to insert additional tags to make sense of it.

Do you have any suggestions for what users are meant to do instead? Insert zero-width spaces into the "blank" lines?

I suppose I'm looking for valid HTML compiling, not purity to the a spec (though I totally understand that focus and this isn't meant as a criticism).

**Comment by UziTech** [comment]
I would suggest only parsing the parts as markdown that you want to follow the markdown spec.

You can extend marked with a custom extension if you want it to work differently.

**Comment by rschristian** [comment]
Cheers, will look into that!

Sorry for the issue.
