### ISSUE TITLE
Equals sign in code block breaks it

### ISSUE THREAD

**Issue by charpeni** [markedjs/marked#3208]
**Marked version:**
0.12.0

**Describe the bug**
Having an equals sign in a code block breaks the markdown, but only if a blank line doesn't precede the code block.

Sorry, I can't really put up good examples because code blocks are being formatted as markdown.

**To Reproduce**
📚 [Marked Demo](https://marked.js.org/demo/?text=A%20markdown%20is%20perfectly%20fine%20like%20this%0A%0A%60%60%60%0A%3D%0A%60%60%60%0A%0ABut%20as%20soon%20as%20we%20don%27t%20have%20a%20blank%20line%20before%20the%20code%20block%2C%20it%20breaks%0A%60%60%60%0A%3D%0A%5E%20This%20is%20the%20faulty%20character%0A%0A%60%60%60%0A&options=%7B%0A%20%22async%22%3A%20false%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22extensions%22%3A%20null%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22hooks%22%3A%20null%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%0A%7D&version=12.0.0)

<img width="400" alt="Screenshot 2024-03-01 at 2 11 58 PM" src="https://github.com/markedjs/marked/assets/7189823/b486060c-3ffa-4b66-82f4-e85275b06acb">

**Expected behavior**
📚 [CommonMark Demo](https://spec.commonmark.org/dingus/?text=A%20markdown%20is%20perfectly%20fine%20like%20this%0A%0A%60%60%60%0A%3D%0A%60%60%60%0A%0ABut%20as%20soon%20as%20we%20don%27t%20have%20a%20blank%20line%20before%20the%20code%20block%2C%20it%20breaks%0A%60%60%60%0A%3D%0A%5EThis%20is%20the%20faulty%20character%0A%0A%60%60%60%0A)

<img width="400" alt="Screenshot 2024-03-01 at 2 11 44 PM" src="https://github.com/markedjs/marked/assets/7189823/87272f7d-bea3-4264-934a-5f310a5b7637">

**Comment by UziTech** [comment]
Seems like that is because it thinks it should be a [setext heading](https://spec.commonmark.org/0.31.2/#setext-headings).
