### ISSUE TITLE
URL.canParse is not a function on Brave Browser

### ISSUE THREAD

**Issue by HexaField** [markedjs/marked#3218]
**Marked version:**

N/A

**Describe the bug**

I went to this URL https://app.radicle.xyz/nodes/seed.radicle.garden/rad:z3gqcJUoA1n9HaHKufZs5FCSGazv5 and got this error
![Screenshot from 2024-03-11 18-12-05](https://github.com/markedjs/marked/assets/10372036/157a40ab-b713-4f80-b9c9-e0a9420f73ff) on Brave Browser v1.59.124

**To Reproduce**

**Expected behavior**

**Comment by UziTech** [comment]
Looks like they are using an extension that doesn't work properly.
