### ISSUE TITLE
Add Support for Customizable Tab Handling in Markdown Code Blocks

### ISSUE THREAD

**Issue by ArfaNada** [markedjs/marked#3224]
### Description
 Marked.js currently lacks support for customizable tab handling within Markdown code blocks. This feature would allow users to specify tab width and customize tab behavior within code blocks, enhancing the flexibility and usability of Marked.js for Markdown parsing.

**_Why is this feature necessary?_**
 The ability to customize tab handling is essential for users who work with Markdown documents containing code blocks. Different projects and coding styles may require varying tab widths and behaviors, and providing this customization option would improve the overall experience of using Marked.js for Markdown rendering.
@daniel-santos 
@timabbott
@zulip (https://github.com/zulip/zulip/issues/29044)

**_Proposal_**
 I propose extending Marked.js to support the parsing of Markdown code blocks with customizable tab handling. This enhancement would involve adding functionality to interpret additional parameters within code blocks, such as specifying the tab width using a syntax like ts=<n>.
**_Implementation Details_**
To implement this feature, the following steps could be taken:

1. 	Extend the parser to recognize and interpret the ts=<n> syntax within fenced code blocks.
2. 	Implement logic to adjust the tab width based on the specified parameter <n>.
3. 	Ensure that the parsing of code blocks remains efficient and compatible with existing Markdown syntax.

**_Benefits_**
•	Provides users with greater control over tab handling within code blocks, accommodating projects that still use tabs for indentation.
•	Enhances the versatility and usability of Marked.js for a wider range of Markdown formatting requirements.

**_Alternatives Considered_**
 Alternative solutions might include using external Markdown rendering libraries or manually processing Markdown documents to customize tab behavior. However, these approaches are less efficient and would require additional effort from users.

By adding support for customizable tab handling in Markdown code blocks, Marked.js can better align with established Markdown specifications and meet the diverse needs of its user base.

**Comment by UziTech** [comment]
> Marked.js can better align with established Markdown specifications and meet the diverse needs of its user base.

I'm curious which markdown specifications include this?

**Comment by bent10** [comment]
It can be done with [`marked-directive`](https://www.npmjs.com/package/marked-directive):

```ts
// code-group-directive.ts
import attrsParser from 'attributes-parser'
import type { Tokens } from 'marked'
import type { DirectiveConfig } from 'marked-directive'

const codeGroup: DirectiveConfig = {
  level: 'container',
  marker: ':::',
  renderer(token) {
    if (token.meta.name === 'code-group') {
      const { id = 'tab-' + String(Math.random()).slice(2) } =
        token.attrs || ({} as NonNullable<typeof token.attrs>)

      const items = [...(token.tokens || [])]
        ?.filter(token => 'lang' in token)
        .map(token => {
          Object.assign(token, {
            attrs: attrsParser('lang' in token ? token.lang : '')
          })
          return token
        }) as Array<Tokens.Code & { attrs: { [key: string]: string } }>

      // assuming we use Bootstrap CSS
      let html = '<div class="code-group border rounded">\n'

      // build nav
      html += `<ul class="nav nav-underline px-4 pt-2 border-bottom" id="${id}" role="tablist">\n`
      items.forEach((item, idx) => {
        const { title } = item.attrs
        const itemId = `${String(Math.random()).slice(2)}-tab`
        const target = `${itemId}-pane`
        const defaultActive = idx === 0

        Object.assign(item.attrs, {
          itemId,
          target,
          defaultActive,
          idx
        })

        html += '<li class="nav-item" role="presentation">\n'
        html += `<button class="nav-link${defaultActive ? ' active' : ''}" id="${itemId}" data-bs-toggle="tab" data-bs-target="#${target}" type="button" role="tab" aria-controls="${target}" aria-selected="${defaultActive}">${title}</button>`
        html += '</li>\n'
      })
      html += '</ul>\n'

      // build tab-content
      html += `<div class="tab-content" id="${id}-content">\n`
      for (const item of items) {
        const { itemId, target, defaultActive, idx } = item.attrs
        html += `<div class="tab-pane${defaultActive ? ' show active' : ''}" id="${target}" role="tabpanel" aria-labelledby="${itemId}" tabindex="${idx}">\n`
        html += item.text
        html += '</div>\n'
      }
      html += '</div>\n'

      // end wrapper
      html += '</div>\n'

      return html
    }

    return false
  }
}

export default codeGroup
```

**Usage:**

```ts
import { Marked } from 'marked'
import { createDirectives, presetDirectiveConfigs } from 'marked-directive'
import codeGroup from './code-group-directive.js'

const content = '...' // see the markdown code below
const processor = new Marked({ async: true, gfm: true }).use(
  createDirectives([...presetDirectiveConfigs, codeGroup])
)
const html = await processor.parse(content)

console.log(content)
```

The `content` value:

````md
Install `marked-directive` using either npm or yarn:

:::code-group

```bash title="NPM"
npm install marked-directive
```

```bash title="YARN"
yarn add marked-directive
```

:::
````

**Result:**

![image](https://github.com/markedjs/marked/assets/3231506/32d0f31d-c682-4277-a28b-d9c73dd981e5)
