### ISSUE TITLE
Issues with various Markdown aspects

### ISSUE THREAD

**Issue by xpple** [markedjs/marked#3227]
**Marked version:** 12.0.1

**Describe the bug**
I cannot seem to use headings, lists, or code blocks, etc. I am able to use things like bold and italics as well as inline code.

**To Reproduce**
I cannot reproduce this (as you probably expected) on the demo page. But you can try it out on the website I am developing which uses Marked.js: [wiskundewoordenboek.nl/woord/click-voorbeeld-to-test/](https://wiskundewoordenboek.nl/woord/click-voorbeeld-to-test/). Try to enter `# Heading` for example (click on "Voorbeeld" to generate a preview). Notice how it doesn't produce a heading. Notice how `**bold**` does work.

**Expected behaviour**
I expect the various aspects to render.

**Comment by UziTech** [comment]
Can you share the code used to parse the markdown? It looks like `parseInline` is used to only parse inline tokens.

**Comment by xpple** [comment]
Ah, of course! I used `parseInline` because I didn't want to have the surrounding `<p>` tags, but I didn't realise it would stop parsing block elements. Thank you!
