### ISSUE TITLE
Nested pre-formatted text block are not handled properly 

### ISSUE THREAD

**Issue by d0ctr** [markedjs/marked#3231]
**Marked version:**
11.2.0

**Describe the bug**
Marked closes the pre-formatted text block at the first appearance of a \`\`\` on a new line.

**To Reproduce**

Include a pre-formatted block in side another pre-formatted block.

\`\`\`markdown
\# Header
\`\`\`bash
// some code
\`\`\`
\`\`\`

1. [Marked Demo](https://marked.js.org/demo/?text=%60%60%60markdown%0A%23%20Header%0A%0ASome%20text%20here.%0A%0A1.%20Item%201%20with%20example%0A%0A%60%60%60bash%0Arm%20-rf%20%2F%0A%60%60%60%0A%0A2.%20Item%202%0A%0A%60%60%60&options=%7B%0A%20%22async%22%3A%20false%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22extensions%22%3A%20null%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22hooks%22%3A%20null%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%0A%7D&version=12.0.1)
2. [CommonMark Demo](https://spec.commonmark.org/dingus/?text=%60%60%60markdown%0A%23%20Header%0A%0ASome%20text%20here.%0A%0A1.%20Item%201%20with%20example%0A%0A%60%60%60bash%0Arm%20-rf%20%2F%0A%60%60%60%0A%0A2.%20Item%202%0A%0A%60%60%60)

**Expected behavior**
```html
<pre><code language=“markdown”>
# Header
```bash
// some code
```</code></pre>
```

**Comment by calculuschild** [comment]
This is the correct behavior according yo the spec. You can see that Marked has the same output as Commonmark. 

If you want to nest code fences like this, you can increase the number of backticks in the outer layers:

`````
````markdown
# Header

Some text here.

1. Item 1 with example

```bash
rm -rf /
```

2. Item 2

````
`````

**Comment by d0ctr** [comment]
My use case is transforming LLM’s output and they don’t tend to that way of nesting.Well if this is according to the design, then it seems nothing can be done. On 17. Mar 2024, at 15:40, Trevor Buckner ***@***.***> wrote:﻿
This is the correct behavior according yo the spec. You can see that Marked has the same output as Commonmark.
If you want to nest code fences like this, you can increase the number of backticks in the outer layers:
````markdown
# Header

Some text here.

1. Item 1 with example

```bash
rm -rf /
```

2. Item 2

````
