### ISSUE TITLE
When both bold and normal fonts appear in a line of text, if there is no space after the bold double asterisk, it cannot be parsed normally.

### ISSUE THREAD

**Issue by unclepei** [markedjs/marked#3237]
**Marked version:**
marked v12.0.1 - a markdown parser

**Describe the bug**
When both bold and normal fonts appear in a line of text, if there is no space after the bold double asterisk, it cannot be parsed normally.
pls try
- **Preview:**A live display of the generated HTML as it would render in a browser.
- **Preview:** A live display of the generated HTML as it would render in a browser.

**Comment by calculuschild** [comment]
This is correct behavior according the commonmark spec: https://spec.commonmark.org/0.31.2/#example-392

Specifically it is the presence of the punctuation mark `:` which creates the restriction.
