### ISSUE TITLE
Text rendered in h2 heading title

### ISSUE THREAD

**Issue by Al-phonsio** [markedjs/marked#3238]
**Marked version:** 12.0.1

**Describe the bug**
A text without # is rendered in `<h2>` tags. 

**To Reproduce**

Render this markdown:

``` md
Here's the calculation:

456
+456
------
912
```

1. [Marked Demo](https://marked.js.org/demo/?text=Here%27s%20the%20calculation%3A%0A%0A456%0A%2B456%0A------%0A912&options=%7B%0A%20%22async%22%3A%20false%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22extensions%22%3A%20null%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22hooks%22%3A%20null%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%0A%7D&version=12.0.1)

**Expected behavior**

This expected output is something similar to the input, without `<h2>` tags.

**Comment by UziTech** [comment]
That is called a [setext heading](https://spec.commonmark.org/0.31.2/#setext-headings) in markdown. As you can see by the [CommonMark demo](https://spec.commonmark.org/dingus/?text=Here%27s%20the%20calculation%3A%0A%0A456%0A%2B456%0A------%0A912) that is intended behavior.

If you want to prevent the markdown from parsing as markdown you can wrap it in a code fence.

````md
Here's the calculation:

```
456
+456
------
912
```
````

**Comment by Al-phonsio** [comment]
Thank you, and sorry for the issue. 
One last question : what is the best option to disable `Setext heading` in marked.

**Comment by UziTech** [comment]
You can create an `lheading` [tokenizer](https://marked.js.org/using_pro#tokenizer) that never returns a token.

```js
marked.use({
  tokenizer: {
    lheading() {}
  }
});
```
