### ISSUE TITLE
Link and tilde symbol parsing issues detected.

### ISSUE THREAD

**Issue by tom-style** [markedjs/marked#3246]
Marked version: marked v12.0.1 

Example 1：
`marked.parse('test test http://www.test.com。test test');`

Output：
`'<p>test test <a href="http://www.test.com%E3%80%82test">http://www.test.com。test</a> test</p>\n'`

Expected Output：
`'<p>test test <a href="http://www.test.com">http://www.test.com</a>。test test</p>\n'`

Example 2：
`marked.parse('test test 11:10~23:23 test test, test test 11:10~23:23 test test');`

Output：
`'<p>test test 11:10<del>23:23 test test, test test 11:10</del>23:23 test test</p>\n'`

Expected Output：
`'<p>test test 11:10~23:23 test test, test test 11:10~23:23 test test</p>\n'`

**Comment by UziTech** [comment]
As you can see marked renders the same as github with gfm option on by default:

```md
test test http://www.test.com/。test test
```

test test http://www.test.com/。test test

```md
test test 11:10~23:23 test test, test test 11:10~23:23 test test
```

test test 11:10~23:23 test test, test test 11:10~23:23 test test

---

You can try setting `gfm: false` in the options to not use GFM extensions.
