### ISSUE TITLE
marked v12 with webpack 5.9x

### ISSUE THREAD

**Issue by Aetherinox** [markedjs/marked#3263]
**Marked version:**
[12.0.1](https://www.npmjs.com/package/marked/v/12.0.1)

**Describe the bug**
Originally, we utilized Marked v2.x, which worked fine. We recently decided to upgrade our dependencies and introduce marked v12 along with webpack v5.9x.

When loading the app, webpack throws the error:
```
export 'marked' (imported as 'marked') was not found in 'marked' (module has no exports)
```

In the webpack file with marked v2, we used:
```
  alias: {
      marked: devMode ? 'marked/lib/marked.js' : 'marked/marked.min.js',
```

With this error, we decided to downgrade and test our versions, and marked v3 works fine. But the issue starts to occur with marked > v4.x. When I tracked the changes, it appears you added the `exports` declarations inside `package.json`, and got rid of the `marked.js` file and only have the `min.js` file now. So I changed the paths over to the new file and just used that for testing.

```
marked: 'marked/marked.min.js',
```

which is what returns the webpack error above. Also tried out the other files in `marked/lib` just for giggles and those refuse to work as well; which don't find marked at all. The `marked.min.js` just complains about the `package.json` exports being incorrect.

I went searching around on numerous forums, and the issue appears to occur depending on the developer of the package and how they have the exports in the `package.json` configured.

In the actual file where marked is utilized, I changed over from the old imports to the new:

old:
```
import marked from 'marked';
```

new:
```
import { marked } from 'marked';
```

**To Reproduce**

- Test environment with webpack `5.91.0`
- Add marked > v4.x as a `resolve.alias` to the `webpack.config.js`

**Expected behavior**
When launching, webpack should include the minified mark js in the bundled assets

**Comment by UziTech** [comment]
Can you create a minimal repo that can reproduce this?

**Comment by UziTech** [comment]
Seems to work for me in https://github.com/UziTech/test-marked-3263

must be something in your webpack configuration that makes it not work.

**Comment by Aetherinox** [comment]
Interesting. I was looking at a way to create a minified version, but there's a lot of stuff in our app that needs to be stripped. If I revert back to v3, works great, But anything over v3 just refuses to load up.

Also, with our implementation, we're using the loader within webpack.config.js.

```json
        progress: false,
        resolve: {
            modules: [
                path.join(rootDir, 'app/scripts'),
                path.join(rootDir, 'app/styles'),
                path.join(rootDir, 'node_modules')
            ],
            alias: {
                'babel-helpers': path.join(rootDir, 'app/lib/babel-helpers.js'),
                jquery: `jquery/dist/jquery${devMode ? '' : '.min'}.js`,
                qrcode: `jsqrcode/dist/qrcode${devMode ? '' : '.min'}.js`,
                marked: 'marked/marked.min.js',
                dompurify: `dompurify/dist/purify${devMode ? '' : '.min'}.js`,
                hbs: 'handlebars/runtime.js'
            },
```

The other odd thing is that I can actually get the error to stop and get it to work, if I replace the js file with `require('marked');`

```json
            alias: {
                'babel-helpers': path.join(rootDir, 'app/lib/babel-helpers.js'),
                jquery: `jquery/dist/jquery${devMode ? '' : '.min'}.js`,
                qrcode: `jsqrcode/dist/qrcode${devMode ? '' : '.min'}.js`,
                argon2: 'argon2-browser/dist/argon2.js',
                marked: require('marked'),
                dompurify: `dompurify/dist/purify${devMode ? '' : '.min'}.js`,
                hbs: 'handlebars/runtime.js'
            },
```

**Comment by UziTech** [comment]
this seems like it might be a better question for the webpack repo than marked. I haven't used webpack in a while so I don't know much about it.

**Comment by Aetherinox** [comment]
Another update. I've been flipping between dozens of Google pages, and the code.

I manually edited your package.json file, and someone mentioned something as what I could classify as not even needed, but I tried it anyway.

If I remove
```
  "type": "module",
```

from your package.json, no errors, and the package works fine. Makes zero sense.
