### ISSUE TITLE
Block level extension not rendering correctly

### ISSUE THREAD

**Issue by arfianadam** [markedjs/marked#3272]
**Marked version: 12.0.2**

I tried to write an extension that also stores image's width, but despite following the example, I couldn't make it to output what I expected.

**To Reproduce**

[Codesandbox.io](https://codesandbox.io/p/sandbox/marked-try-s2nrnc?file=%2Fsrc%2Findex.ts%3A43%2C21&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clvkm4os100062v6l2hb2ectr%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clvkm4os100022v6li49rbsdr%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clvkm4os100032v6liwi4p1o8%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clvkm4os100052v6lra1vpavp%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clvkm4os100022v6li49rbsdr%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clvkm4os000012v6lbabk5q1m%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.ts%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A43%252C%2522startColumn%2522%253A21%252C%2522endLineNumber%2522%253A43%252C%2522endColumn%2522%253A21%257D%255D%257D%255D%252C%2522id%2522%253A%2522clvkm4os100022v6li49rbsdr%2522%252C%2522activeTabId%2522%253A%2522clvkm4os000012v6lbabk5q1m%2522%257D%252C%2522clvkm4os100052v6lra1vpavp%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clvkm4os100042v6lo5r4pl7u%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clvkm4os100052v6lra1vpavp%2522%252C%2522activeTabId%2522%253A%2522clvkm4os100042v6lo5r4pl7u%2522%257D%252C%2522clvkm4os100032v6liwi4p1o8%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clvkm4os100032v6liwi4p1o8%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

```ts
marked.use({
  extensions: [
    {
      name: "customImage",
      level: "block",
      start: (source: string) => {
        return source.match(/!\[/)?.index;
      },
      tokenizer(source, tokens) {
        const rule = /!\[\]\((.+?)\){: width=(\d+?) }/;
        const match = rule.exec(source);
        if (match) {
          const token = {
            type: "customImage",
            raw: match[0],
            src: match[1],
            width: match[2],
          };
          return token;
        }
        return undefined;
      },
      renderer(token) {
        return `<img src="${token.src}" data-width="${token.width}" />`;
      },
    },
  ],
});

const rawText = `aaa

![](imagelink){: width=50 }

ccc`;
const parsedText = marked.parse(rawText);
```
outputs
```html
<img src="imagelink" data-width="50" /><p>=50 }</p>
<p>ccc</p>
```

**Expected behavior**
```html
<p>aaa</p>
<p><img src="imagelink" data-width="50" /></p>
<p>bbb</p>
```

Thank you in advance.

**Comment by UziTech** [comment]
It looks like your `rule` searches for a pattern anywhere in the `source`. It should only look for tokens at the beginning. Try adding `^` at the beginning of the regexp

**Comment by UziTech** [comment]
It also looks like you are setting it as a `block` level token which won't be inside a `<p>` tag. You can change it to `inline` to parse it as an inline token.

```js
import { Marked } from "marked";

import "./styles.css";

document.getElementById("app").innerHTML = `
<h1>Hello Vanilla!</h1>
<div>
  We use the same configuration as Parcel to bundle this sandbox, you can find more
  info about Parcel 
  <a href="https://parceljs.org" target="_blank" rel="noopener noreferrer">here</a>.
</div>`;
const marked = new Marked();
marked.use({
  extensions: [
    {
      name: "customImage",
      level: "inline",
      start: (source: string) => {
        return source.match(/!\[/)?.index;
      },
      tokenizer(source, tokens) {
        const rule = /^!\[\]\((.+?)\){: width=(\d+?) }/;
        const match = rule.exec(source);
        if (match) {
          const token = {
            type: "customImage",
            raw: match[0],
            src: match[1],
            width: match[2],
          };
          return token;
        }
        return undefined;
      },
      renderer(token) {
        return `<img src="${token.src}" data-width="${token.width}" />`;
      },
    },
  ],
});

const rawText = `aaa

inline ![](imagelink){: width=50 }

ccc`;
const parsedText = marked.parse(rawText);

console.log(parsedText);
```
