### ISSUE TITLE
Emphasis cannot be rendered

### ISSUE THREAD

**Issue by Stonewuu** [markedjs/marked#3278]
**Marked version:**
12.0.2
**Describe the bug**
it may not be effective due to the symbols used inside the emphasis, but versions before 5.0.3 are normal

**To Reproduce**

```
* **text**text   (correct)

* **text2：**text   (wrong)

```

https://marked.js.org/demo/?text=%0A%0A*%20**text**text%0A%0A*%20**text2%EF%BC%9A**text%0A%0A&options=%7B%0A%20%22async%22%3A%20false%2C%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22extensions%22%3A%20null%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=12.0.2

https://marked.js.org/demo/?text=%0A%0A*%20**text**text%0A%0A*%20**text2%EF%BC%9A**text%0A%0A&options=%7B%0A%20%22async%22%3A%20false%2C%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22extensions%22%3A%20null%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=5.0.3

**Expected behavior**
Correct rendering emphasis

**Comment by DophinL** [comment]
same question

**Comment by Stonewuu** [comment]
It seems that this result is in line with Markdown specifications, so can only try to avoid this usage @DophinL

**Comment by DophinL** [comment]
> It seems that this result is in line with Markdown specifications, so can only try to avoid this usage @DophinL

Thank you! I'm going to replace the Chinese quotation marks, haha. @Stonewuu
