### ISSUE TITLE
problem when inserting a picture

### ISSUE THREAD

**Issue by crocodileDaniil** [markedjs/marked#3286]
**Marked version:**
latest
**Describe the bug**
*code problem: *
too much recursion
Please report this to https://github.com/markedjs/marked.
LP.prototype.output@https://ssl.gstatic.com/colaboratory-static/common/3c7944983d550bf43476281924e4eba5/external_binary_l10n__ru.js:2761:266
QP@https://ssl.gstatic.com/colaboratory-static/common/3c7944983d550bf43476281924e4eba5/external_binary_l10n__ru.js:2772:283
IP.prototype.parse@https://ssl.gstatic.com/colaboratory-static/common/3c7944983d550bf43476281924e4eba5/external_binary_l10n__ru.js:2768:237
PP@https://ssl.gstatic.com/colaboratory-static/common/3c7944983d550bf43476281924e4eba5/external_binary_l10n__ru.js:2768:36
JP@https://ssl.gstatic.com/colaboratory-static/common/3c7944983d550bf43476281924e4eba5/external_binary_l10n__ru.js:2775:311
XSa@https://ssl.gstatic.com/colaboratory-static/common/3c7944983d550bf43476281924e4eba5/external_binary_l10n__ru.js:2826:362
WSa@https://ssl.gstatic.com/colaboratory-static/common/3c7944983d550bf43476281924e4eba5/external_binary_l10n__ru.js:2813:52
g.updateSectionHeader@https://ssl.gstatic.com/colaboratory-static/common/3c7944983d550bf43476281924e4eba5/external_binary_l10n__ru.js:5039:323
r_@https://ssl.gstatic.com/colaboratory-static/common/3c7944983d550bf43476281924e4eba5/external_binary_l10n__ru.js:5036:385
C_@https://ssl.gstatic.com/colaboratory-static/common/3c7944983d550bf43476281924e4eba5/external_binary_l10n__ru.js:5079:540
g.enterDocument@https://ssl.gstatic.com/colaboratory-static/common/3c7944983d550bf43476281924e4eba5/external_binary_l10n__ru.js:7009:500
g.enterDocument@https://ssl.gstatic.com/colaboratory-static/common/3c7944983d550bf43476281924e4eba5/external_binary_l10n__ru.js:8364:66
yn@https://ssl.gstatic.com/colaboratory-static/common/3c7944983d550bf43476281924e4eba5/external_binary_l10n__ru.js:553:379
g.render@https://ssl.gstatic.com/colaboratory-static/common/3c7944983d550bf43476281924e4eba5/external_binary_l10n__ru.js:553:93
c8a/<@https://ssl.gstatic.com/colaboratory-static/common/3c7944983d550bf43476281924e4eba5/external_binary_l10n__ru.js:4224:99
Aa@https://ssl.gstatic.com/colaboratory-static/common/3c7944983d550bf43476281924e4eba5/external_binary_l10n__ru.js:16:57
va.prototype.next_@https://ssl.gstatic.com/colaboratory-static/common/3c7944983d550bf43476281924e4eba5/external_binary_l10n__ru.js:14:195
kaa/this.next@https://ssl.gstatic.com/colaboratory-static/common/3c7944983d550bf43476281924e4eba5/external_binary_l10n__ru.js:17:48
b@https://ssl.gstatic.com/colaboratory-static/common/3c7944983d550bf43476281924e4eba5/external_binary_l10n__ru.js:17:309

**To Reproduce**

1. in the text clicked insert image
2. chose the necessary
3. pressed open
4. nothing happened. I thought I clicked past. made the insert again
5. снова ничего не произошло. перезагрузил страницу и полцчил такой результат

**Expected behavior**
The picture should have been inserted.
Is it possible to recover data yourself? or roll back to some save.

**Comment by UziTech** [comment]
Can you share your code or a minimal repo so we can reproduce this? Sounds like an issue in an extension.
