### ISSUE TITLE
[Question] lexer - a `space` betwen two lists

### ISSUE THREAD

**Issue by Bistard** [markedjs/marked#3299]
**Marked version:** 12.0.2

**Describe the bug**
Given the following plain text:
```md
- list 1
   - list item I
      - list item II
         - list item III
   - list item I.I





- list 2
   - list item I
      - list item II
         - list item III
   - list item I.I
```
> Notice that the new lines between two lists have no spaces, they are just plain new lines.

The following data is the lexing result:
 - There are a total of 2 tokens: the (1) is the token of the 1st list, the (2) is the token of the 2nd list.
![image](https://github.com/markedjs/marked/assets/38385498/f20f5b08-5f02-444c-a077-2aa4117625d6)

**Question**: Why the `space` token is considered as an item of the 1st list, instead of considered as 3 tokens: [list1, space, list2]?

**Comment by UziTech** [comment]
> Why the space token is considered as an item of the 1st list, instead of considered as 3 tokens: [list1, space, list2]?

Why not? Mostly because everyone's use case is different and there is no spec for tokens.

**Comment by masawik** [comment]
Intuitively, it seems that if you want to put several lines in one list item, you should place the content of this item with the indent. Like this

```
1. To do the job
    It's a complicated job
2. rest
```

But when the user makes several line breaks after the list, obviously he wants to make it clear that the list is over
