### ISSUE TITLE
Fail to parse image tag under specific input. 

### ISSUE THREAD

**Issue by Lucascuibu** [markedjs/marked#3307]
**Marked version:** 12.0.2

**Describe the bug**
Such link can not be correctly parsed. 
```
![Sets as Euler Diagram (1)](./Sets as Euler Diagram (1).svg)
```
However, if I removed some chars from the link, it suddenly works. And I can not locate 
```
![Sets as Euler Diagram (1)](SetsasEulervg)               -------works
![Sets as Euler Diagram (1)](etas Euler Diagram)       -------fails
![Sets as Euler Diagram (1)](./Sets_as_Euler_Diagram_(1).svg)   ------works
![Sets as Euler Diagram (1)]( Sets.asEulerDiagram(1).    svg. )  ------works
```

**To Reproduce**
I first tried locally, but then found the online demo also fail on this case. 

One thing I can try is remove the trailing spaces at the beginning and the end. But the last line I provided above indicates that the space in between is allowed.  Also a blank link or simply some spaces is allowed. 
```
![Sets as Euler Diagram (1)](  xx    ) -------works
![Sets as Euler Diagram (1)]() -------works
![Sets as Euler Diagram (1)](  x x    ) -------fails
```
Am I supposed to remove all the in between spaces?

**Comment by UziTech** [comment]
This is working as intended. You can wrap angle brackets (`<>`) around the url if it contains spaces

[commonmark demo](https://spec.commonmark.org/dingus/?text=!%5BSets%20as%20Euler%20Diagram%20(1)%5D(.%2FSets%20as%20Euler%20Diagram%20(1).svg))

**Comment by Lucascuibu** [comment]
> This is working as intended. You can wrap angle brackets (`<>`) around the url if it contains spaces
> 
> [commonmark demo](https://spec.commonmark.org/dingus/?text=!%5BSets%20as%20Euler%20Diagram%20(1)%5D(.%2FSets%20as%20Euler%20Diagram%20(1).svg))

Thank you. I use typora to write markdown thus follow its syntax before. Seems that I need another parser. Thank you for the help!
