### ISSUE TITLE
Feature request: footnotes

### ISSUE THREAD

**Issue by grepsuzette** [markedjs/marked#3309]
**Marked version:**
marked v12.0.2

**Describe the bug**
"footnotes" seem unsupported.

**To Reproduce**
Having bottom-notes such[^1] as[^2] this[^3] kind[^4] will have them on a continuous line, missing some `<br />` probably (edit: actually not a bug, it's currently unsupported!).

[^1]: in github
[^2]: those are rendered one
[^3]: per line, 
[^4]: but not with markedjs (it's shown on one line).

[Demo is here](https://marked.js.org/demo/?text=Marked%20-%20Markdown%20Parser%0A%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%0A%0Afootnotes%20such%5B%5E1%5D%20as%5B%5E2%5D%20this%5B%5E3%5D%20kind%5B%5E4%5D%20will%20have%20them%20on%20a%20continuous%20line%2C%20they%20are%20not%20supported%20apparently.%0A%0A%5B%5E1%5D%3A%20in%20github%0A%5B%5E2%5D%3A%20those%20are%20rendered%20one%0A%5B%5E3%5D%3A%20per%20line%2C%20%0A%5B%5E4%5D%3A%20but%20not%20with%20markedjs%20(it%27s%20shown%20on%20one%20line).%0A&options=%7B%0A%20%22async%22%3A%20false%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22extensions%22%3A%20null%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22hooks%22%3A%20null%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%0A%7D&version=12.0.2)

Commonmark does not have them either. It may just be a github thing. 
Would you have it if PR?

**Comment by UziTech** [comment]
Unfortunately GitHub still doesn't have footnotes in their [spec](https://github.github.com/gfm/) which makes it very difficult to know how to handle edge cases.

There is already an extension that works to add them to marked: https://github.com/bent10/marked-extensions/tree/main/packages/footnote
