### ISSUE TITLE
**xx** -> strong label, There is a problem 

### ISSUE THREAD

**Issue by luckykun** [markedjs/marked#3310]
**Marked version:**
11.2.0

**Describe the bug**
**xx** -> strong label, There is a problem

**To Reproduce**
https://spec.commonmark.org/dingus/?text=**%E4%BF%AE%E5%A4%8D%E5%BB%BA%E8%AE%AE%EF%BC%9A**%0A%0A1.%20**%E7%AB%8B%E5%8D%B3%E9%9A%94%E7%A6%BB%E4%B8%8E%E5%91%8A%E8%AD%A6%E7%9B%B8%E5%85%B3%E7%9A%84%E5%AD%90%E8%BF%9B%E7%A8%8B%EF%BC%9A**%E9%9A%94%E7%A6%BB%E5%B9%B6%E5%88%86%E6%9E%90%E5%AD%90%E8%BF%9B%E7%A8%8B%60b8056bda78a98fe1778f8bbf80d6e825%60%EF%BC%8C%E4%BB%A5%E7%A1%AE%E4%BF%9D%E5%AE%83%E4%B8%8D%E4%BC%9A%E7%BB%A7%E7%BB%AD%E6%89%A7%E8%A1%8C%E4%BB%BB%E4%BD%95%E6%81%B6%E6%84%8F%E6%93%8D%E4%BD%9C%E3%80%82%0A%0A2.%20**%E5%AE%A1%E8%AE%A1%E7%B3%BB%E7%BB%9F%E6%97%A5%E5%BF%97%EF%BC%9A**%E4%BB%94%E7%BB%86%E6%A3%80%E6%9F%A5%E7%B3%BB%E7%BB%9F%E6%97%A5%E5%BF%97%EF%BC%8C%E5%AF%BB%E6%89%BE%E4%BB%BB%E4%BD%95%E4%B8%8E%E8%BF%9C%E7%A8%8B%E6%9C%8D%E5%8A%A1%E5%99%A8%E5%8F%AF%E7%96%91%E4%BA%A4%E4%BA%92%E7%9A%84%E8%BF%B9%E8%B1%A1%EF%BC%8C%E8%BF%99%E5%8F%AF%E8%83%BD%E5%B8%AE%E5%8A%A9%E5%8F%91%E7%8E%B0%E5%85%B6%E4%BB%96%E5%8F%AF%E8%83%BD%E8%A2%AB%E5%BF%BD%E8%A7%86%E7%9A%84%E6%81%B6%E6%84%8F%E6%B4%BB%E5%8A%A8%E3%80%82%0A%0A3.%20**%E6%9B%B4%E6%96%B0%E5%92%8C%E4%BF%AE%E8%A1%A5%EF%BC%9A**%E6%9F%A5%E7%9C%8B%E6%BC%8F%E6%B4%9E%E7%AE%A1%E7%90%86%E9%A1%B5%E9%9D%A2%EF%BC%8C%E6%A3%80%E6%9F%A5%E5%B9%B6%E5%BA%94%E7%94%A8%E4%BB%BB%E4%BD%95Java%E7%8E%AF%E5%A2%83%E3%80%81Web%E5%BA%94%E7%94%A8%E5%8F%8A%E5%85%B6%E7%9B%B8%E5%85%B3%E7%BB%84%E4%BB%B6%E7%9A%84%E6%9C%80%E6%96%B0%E5%AE%89%E5%85%A8%E8%A1%A5%E4%B8%81%E3%80%82&smart=1

![Uploading image.png…]()
Not converted to strong tag

**Comment by UziTech** [comment]
You linked to commonmark. That is how it is supposed to work.

See the [commonmark spec](https://spec.commonmark.org/0.31.2/#emphasis-and-strong-emphasis)
