### ISSUE TITLE
compiled code，named # t and # e, which may cause errors in some versions of the browser. 

### ISSUE THREAD

**Issue by heheping** [markedjs/marked#3324]
In the compiled code, there are two methods named # t and # e, which may cause errors in some versions of the browser. I tried changing these two methods to regular method names (such as Cht and Che) to solve this problem. I hope to fix this bug in future versions.

**Comment by heheping** [comment]
change two methods name can solve this problem

**Comment by UziTech** [comment]
Those are private methods that work in all major browsers.
