### ISSUE TITLE
Types for `this.parser` don't match notes of v13 release because `parser` is omitted

### ISSUE THREAD

**Issue by cascornelissen** [markedjs/marked#3326]
**Marked version:**
13.0.0

**Describe the bug**

**To Reproduce**
Trying to migrate an extension by following the notes of the release results in code that's incompatible with the TypeScript types. The cause seems to be that `RendererObject` refers to `RendererApi` which is defined as `Omit<_Renderer, "constructor" | "options" | "parser">` so `parser` is being omitted?

```ts
const extension: MarkedExtension = { // Added the explicit type here
  useNewRenderer: true,
  renderer: {
    heading(token) {
      // increase depth by 1
      const text = this.parser.parseInline(token.tokens);
      const level = token.depth;
      return `<h${level + 1}>${text}</h${level + 1}>`;
    }
  }
};

marked.use(extension);
```

<img width="775" alt="image" src="https://github.com/markedjs/marked/assets/1304939/a709568b-a2fd-457f-b379-5deab2234e64">

**Expected behavior**
The example works as expected.

**Comment by cascornelissen** [comment]
Based on the `works as intended` I assume not, but is it not possible to type `this` correctly on the side of marked?

**Comment by UziTech** [comment]
You are creating the function so you need to type it correctly. The function signature I provided is the way you would create the correctly typed function.
