### ISSUE TITLE
Incompatible/inconsistent types with `MarkedExtension`

### ISSUE THREAD

**Issue by jblyberg** [markedjs/marked#3334]
**Marked version:**

13.0.0

**Describe the bug**
Incompatible/inconsistent types with `MarkedExtension` causes a typescript error when using `renderer` to define extensions.

**To Reproduce**

Using the renderer example from the docs:

```
// Create reference instance
import { marked } from 'marked';

// Override function
const renderer = {
  heading(text, depth) {
    const escapedText = text.toLowerCase().replace(/[^\w]+/g, '-');

    return `
            <h${depth}>
              <a name="${escapedText}" class="anchor" href="#${escapedText}">
                <span class="header-link"></span>
              </a>
              ${text}
            </h${depth}>`;
  }
};

marked.use({ renderer });
```

Produces the following error:

```
Argument of type '{ renderer: { heading(text: string, depth: number): string; }; }' is not assignable to parameter of type 'MarkedExtension'. ts (2345)
```

**Expected behavior**
No error

**Comment by jblyberg** [comment]
Found my answer here: https://github.com/markedjs/marked/issues/3326

But I'd like to just provide a gentle suggestion to update the documentation--especially when there are breaking changes.

**Comment by UziTech** [comment]
> But I'd like to just provide a gentle suggestion to update the documentation--especially when there are breaking changes.

You mean like [this documentation](https://github.com/markedjs/marked/releases/tag/v13.0.0)?

**Comment by jblyberg** [comment]
Yes, thank you! I was looking on the website.
