### ISSUE TITLE
Possible bug with Renderer.link()

### ISSUE THREAD

**Issue by brenc** [markedjs/marked#3336]
**Marked version:** 13.0.0

**Describe the bug**
I'm doing this to get links formatted so they open in a new window:
```Typescript
const renderer = new marked.Renderer();
renderer.link = (href, title, text): string => {
  return `<a target="_blank" rel="noopener noreferrer" href="${href}" title="${
    title ?? text
  }">${text}</a>`;
  return '';
};
marked.use({ renderer });
```
Looks like this was changed in 13 to:
```typescript
renderer.link = ({ href, title, tokens }): string => {
  logger.debug('%O, %O, %O', href, title, tokens);
  // return `<a target="_blank" rel="noopener noreferrer" href="${href}" title="${
  //   title ?? text
  // }">${text}</a>`;
  return '';
};
```
Yet what gets logged above is `undefined, undefined, undefined`. If I change it to:
```typescript
renderer.link = (link): string => {
  logger.debug('%O', link);
  // logger.debug('%O, %O, %O', href, title, tokens);
  // return `<a target="_blank" rel="noopener noreferrer" href="${href}" title="${
  //   title ?? text
  // }">${text}</a>`;
  return '';
};
```
`link` is a string that contains the raw URL itself, _not_ destructured elements of `Tokens.Link` as expected.

The Typescript definition is `link({ href, title, tokens }: Tokens.Link): string;` so that first updated version should work unless there is something very obvious here I am missing. I've gone through the release notes, the PR that changed this, etc.

**To Reproduce**
See above.

**Expected behavior**
For `{ href, title, tokens }` to get passed into `renderer.link()`.

**Comment by UziTech** [comment]
Try `marked.use({ renderer, useNewRenderer: true });` for the first example.

This new option is a temporary option to allow opting in to the new renderer style.

**Comment by brenc** [comment]
I see. That appears to work, thanks. I did see mention of that option but was confused as to how we're meant to use it. Plus TS shows compilation errors when using the old style as the definitions have been updated to the new style. The current definition is technically incorrect as w/o `useNewRenderer` it's still `link(href: string, title: string | null | undefined, text: string): string;`
