### ISSUE TITLE
text in single ~ will be render del，but normally only text in ~~ should be render del

### ISSUE THREAD

**Issue by ys0817** [markedjs/marked#3337]
markdown content： age(1~3), hight(80~100)

rendered: age(1<del>3), hight(80</del>100)

but we need: age(1~3), hight(80~100)

**Comment by UziTech** [comment]
looks like marked [demo](https://marked.js.org/demo/?text=markdown%20content%EF%BC%9A%20age(1~3)%2C%20hight(80~100)%0A%0Arendered%3A%20age(1%3Cdel%3E3)%2C%20hight(80%3C%2Fdel%3E100)%0A%0Abut%20we%20need%3A%20age(1~3)%2C%20hight(80~100)&options=%7B%0A%20%22async%22%3A%20false%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22extensions%22%3A%20null%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22hooks%22%3A%20null%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%0A%7D&version=13.0.0) does exactly the same thing as GitHub.

so what is the problem?

**Comment by akaQiang** [comment]
How to solve the problem of del caused by being wrapped by a single wavy line

**Comment by akaQiang** [comment]
like this markdown content： age(1~3), hight(80~100)。  Expected no del, actually there is

**Comment by UziTech** [comment]
escape the tilde:  `age(1\~3), hight(80~100)`

age(1\~3), hight(80~100)

**Comment by akaQiang** [comment]
Why is the deletion line only displayed when wrapped with double wavy lines in editors similar to vscode

**Comment by UziTech** [comment]
They don't follow the [GFM spec](https://github.github.com/gfm/#strikethrough-extension-)

> Strikethrough text is any text wrapped in a matching pair of one or two tildes (~)

**Comment by akaQiang** [comment]
ok thanks
