### ISSUE TITLE
Renderer extension documentation seems incorrect?

### ISSUE THREAD

**Issue by nicojs** [markedjs/marked#3338]
**Marked version:**

13.0.0

**Describe the bug**

When implementing a [renderer plugin](https://marked.js.org/using_pro#renderer) the types seem to be incorrect. They are specified to be of type `Tokens.Thing`, but they seem to be strings in practise. See animated gif below:

![marked-types](https://github.com/markedjs/marked/assets/1828233/15dbdac1-c916-4c66-835a-097ba6524c45)

**To Reproduce**

```
mkdir tmp
cd tmp
npm init --yes
npm i marked
touch main.js
```

```js
// @ts-check
import { marked } from "marked";
marked.use({
  renderer: {
    code(code) {
      return `<pre><code class="language-">${code}</code></pre>`;
    },
    html(token) {
        return token.raw;
    }
  },
});

console.log(
  marked(`
    # hello world

    \`\`\`js
    console.log('hello world');
    \`\`\`

<test>

test

</test>
`)
);

```
**Expected behavior**

Correct type inference

**Comment by UziTech** [comment]
The new rendering style requires `useNewRenderer: true` so old extensions can opt in.

```
marked.use({
  useNewRenderer: true,
  renderer: {
    code(code) {
      return `<pre><code class="language-">${code}</code></pre>`;
    },
    html(token) {
        return token.raw;
    }
  },
});
```
