### ISSUE TITLE
Integrate with Google OSS-Fuzz

### ISSUE THREAD

**Issue by LeoDog896** [markedjs/marked#3352]
**Describe the feature**

Add fuzzing to the core parser to help protect against availability attacks and constantly run them with Google's [OSS-Fuzz](https://github.com/google/oss-fuzz).

**Why is this feature necessary?**

`markedjs` has had a [few ReDoS vulnerabilities](https://github.com/markedjs/marked/security), which impact availability. If there are any other ReDoS vulnerabilities (or other availability-hindering vulnerabilities) that this repository doesn't know yet that can be caught using fuzzing, that can help secure dependents of this library.

If approved, I'll send a request to Google for integration.

**Comment by UziTech** [comment]
Sounds good to me. 👍

**Comment by LeoDog896** [comment]
Closed until https://github.com/google/oss-fuzz/issues/11652
