### ISSUE TITLE
html symbol rendering issue

### ISSUE THREAD

**Issue by the-dev-adonis** [markedjs/marked#3369]
**Marked version:**
12.0.0

**Describe the bug**
after escaping string value rendering direct html unicode instead of html symbol, ex - \u2265 ( need to render ≥ ).

**Expected behavior**
Render html symbols

**Comment by UziTech** [comment]
Seems to work be just typing `≥` [demo](https://marked.js.org/demo/?text=%E2%89%A5&options=%7B%0A%20%22async%22%3A%20false%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22extensions%22%3A%20null%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22hooks%22%3A%20null%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%0A%7D&version=13.0.2)

I don't think html usually converts the string `\u2265` a symbol.

**Comment by the-dev-adonis** [comment]
I think if converted the unicode to hexacode it will work ( ex:- `&#x2265;`  instead of `\u2265` )

**Comment by UziTech** [comment]
Yup that should work [demo](https://marked.js.org/demo/?text=%26%23x2265%3B&options=%7B%0A%20%22async%22%3A%20false%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22extensions%22%3A%20null%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22hooks%22%3A%20null%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%0A%7D&version=13.0.2)
