### ISSUE TITLE
Marked Renderer Not Showing OrderList Tags

### ISSUE THREAD

**Issue by Tzion0** [markedjs/marked#3372]
**Marked version: 13.0.0**

**Markdown flavor:** CommonMark

**Proposal type:** Question

## What pain point are you perceiving?
May I ask is there a feature for [Renderer](https://marked.js.org/using_pro#renderer) to deal with OrderList `<ol>`?

### Example Markdown file
```
1. Coffe
2. Tea
3. Milk
```

**CommonMark Demo:** [demo](https://spec.commonmark.org/dingus/?text=%23%23%20Try%20CommonMark%0A%0AYou%20can%20try%20CommonMark%20here.%20%20This%20dingus%20is%20powered%20by%0A%5Bcommonmark.js%5D(https%3A%2F%2Fgithub.com%2Fcommonmark%2Fcommonmark.js)%2C%20the%0AJavaScript%20reference%20implementation.%0A%0A1.%20First%0A%20%20%20%20-%20ul%20first%0A2.%20Second%0A%20%20%20%20-%20ul%20second%0A3.%20Third%0A%20%20%20%20-%20ul%20third%0A%0A)

### HTML Output Expected
```
<ol>
  <li>Coffee</li>
  <li>Tea</li>
  <li>Milk</li>
</ol>
```

**Marked Demo:** [demo](https://marked.js.org/demo/)

## What was attempted
When attempting in Marked Demo it seems correct, I think could be the implementation of my custom extended version of marked gone wrong. I have something like below, is that the reason the OrderList tag `<ol>` doesn't occurs because I overwritten it?
```js
const marked = require('marked');

// Override function
const renderer = {
    heading(text, depth) {
        return `
            <h${depth} class="font-bold text-black dark:text-white font-xl sm:text-2xl lg:text-xl xl:text-2xl leading-tight sm:leading-tight lg:leading-tight xl:leading-tight mb-10">
              ${text}
            </h${depth}>`;
    },
    list(listText){
        return `
            <ul class="list-disc list-inside text-body-color mb-10">
              ${listText}
            </ul>`;
    },
    listitem(ListItem){
        return `
            <li class="font-medium text-body-color text-base sm:text-lg lg:text-base xl:text-lg mb-2">
              ${ListItem.text}
            </li>`;
    }
};

marked.use({ renderer });
```
If it is, may I ask how to make a custom extended of Marked (Actually I just want to add some custom CSS on top of default tag Marked provided for my website) without affecting the original functionality?

**Comment by UziTech** [comment]
You can run it through the original renderers then add classes like:

```js
import { marked } from 'marked';

// Override function
const renderer = {
  heading(...args) {
    const html = marked.Renderer.prototype.heading.call(this, ...args);
    return html.replace(/^<(h\d)/, '<$1 class="font-bold text-black dark:text-white font-xl sm:text-2xl lg:text-xl xl:text-2xl leading-tight sm:leading-tight lg:leading-tight xl:leading-tight mb-10"');
  },
  list(...args) {
    const html = marked.Renderer.prototype.list.call(this, ...args);
    return html.replace(/^<([uo]l)/, '<$1 class="list-disc list-inside text-body-color mb-10"');
  },
  listitem(...args) {
    const html = marked.Renderer.prototype.listitem.call(this, ...args);
    return html.replace(/^<li/, '<li class="font-medium text-body-color text-base sm:text-lg lg:text-base xl:text-lg mb-2"');
  },
};

marked.use({ renderer, useNewRenderer: true });

console.log(marked.parse(`
1. Item 1
2. Item 2
3. Item 3
`));
```

**Comment by Tzion0** [comment]
Thanks so much! I found out the root issue is my tailwind CSS... But your solution does provide me the hint to look deeper! Thanks again!
