### ISSUE TITLE
How to use the out of box rendered result of pre versions on v13.

### ISSUE THREAD

**Issue by Koooooo-7** [markedjs/marked#3373]
> Sorry for delete the issue template since it seems no a suitable place to put in.

Currently, we are doing the v13 adaption from v12.0.2 to v13.0.2.
AFAK, in the v13 changes the renderer to pass the `Token` directly.
Hence there is no sweet default rendered result to use now. such as  the `list`.
Before the v13, we could use the `body` directly and it already resolved the list items.
```js
  (renderer.list = (body, ordered, start) => { 
    // body with resolved list items
}

```
> It has auto resolved in marked.

```js
    body += this.listitem({
              type: 'list_item',
              raw: itemBody,
              text: itemBody,
              task,
              checked: !!checked,
              loose,
              tokens: item.tokens
            });
          }
```

---
But now, it only has the `raw` content and we have to render the `list items` in the `renderer.list` manually, although it is literally the same behavior as the default renderer.

```js
(renderer.list = function (token) {
    const ordered = token.ordered;
    const start = token.start;
    // manually get the body now
    let body = '';
    for (let j = 0; j < token.items.length; j++) {
      const item = token.items[j];
      body += this.listitem?.(item);
    }
  // now , the body is back
  if (.../.test(body)){
   
}

```

I found there has a `useNewRenderer` config for compatibility but it seems gonna be removed in #3342 
Is there other way to gain the  `body` same to the versions before v13 without copying the default renderer behaviors?

Thx a lot!

**Comment by UziTech** [comment]
short answer, no.

In v13 we moved the logic to render the body from the parser to the renderer functions so users have more control over what data is received in the renderers.

The new renderer style is an opt-in so extensions have time to update. In v14 the old renderers will be removed completely.

**Comment by Koooooo-7** [comment]
> short answer, no.
> 
> In v13 we moved the logic to render the body from the parser to the renderer functions so users have more control over what data is received in the renderers.
> 
> The new renderer style is an opt-in so extensions have time to update. In v14 the old renderers will be removed completely.

I see.
So in v13+,  it gonna bring more flexibilities to let user fully controls the Tokens as a pure `Visitor` and remove the  old renderers. If I wanna the behavior (output) align to old versions, I do need do the implementation by myself in v13 and further versions.

Thx!
