### ISSUE TITLE
How to ignore delimiters like '\\[' .. '\\]', '\\(' ..'\\)' which I need for post processing Math equations like MathJax and KaTex javascrips  

### ISSUE THREAD

**Issue by sabawi** [markedjs/marked#3375]
**Marked version:**
marked v13.0.2 - a markdown parser
**Describe the bug**
the output from markdown.parser() changes the delimiters for math equations needed for postprocessing by math rendering libraries
**To Reproduce**
simply render plain text containing both markdown and KaTex delimites in any sequence, I start with MD first then KaTex as in this code:
           // Get unprocessed text and render it in the same section
            newContent.innerHTML = marked.parse(newContent.innerHTML)
            console.log("text with MD :"+newContent.innerHTML);

            renderMathInElement(newContent, {
                delimiters: [
                    {left: "$$", right: "$$", display: true},
                    {left: "$", right: "$", display: false},
                    {left: "\\(", right: "\\)", display: false},
                    {left: "\\[", right: "\\]", display: true}
                ]
            });
The math post processing stops working after MD processing.  But if you use math processing on the plain text, it works fine 

**Expected behavior**

**Comment by sabawi** [comment]
To add to the above, I was hoping for something like:
` marked.parse(text).ignoreDelimiters(
             [
                {left: "$$", right: "$$", display: true},
                {left: "$", right: "$", display: false},
                {left: "\\(", right: "\\)", display: false},
                {left: "\\[", right: "\\]", display: true}
            ]
`

**Comment by UziTech** [comment]
You can create a [custom extension](https://marked.js.org/using_pro#extensions) that just renders them as text so you can do post processing. 

Or you can create a custom extension that does the processing while parsing markdown. For an example you can look at [marked-katex-extension](https://github.com/UziTech/marked-katex-extension), or other [known extensions](https://marked.js.org/using_advanced#extensions).
