### ISSUE TITLE
Can not convert from Markdown syntax to HTML link

### ISSUE THREAD

**Issue by ABCbum** [markedjs/marked#3381]
**Marked version:** 13.0.2

**Describe the bug**
Marked could not convert from Markdown link to HTML link.

**To Reproduce**
The behaviour is reproduced in this [Marked demo link](https://marked.js.org/demo/?text=%3Cabc%3E%0A%3C%2Fabc%3E%0AFirst%20%5Bfoo%20bar%20bas%5D(%231123)%0A%0ASecond%20%5Bfoo%20bar%20bas%5D(%23123).&options=%7B%0A%20%22async%22%3A%20false%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22extensions%22%3A%20null%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22hooks%22%3A%20null%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%0A%7D&version=13.0.2), the text used was:
```
<abc>
</abc>
First [foo bar bas](#1123)

Second [foo bar bas](#123).
```

Issue:
- The first link is NOT converted to HTML link.
- While the second one does.

I also tried [CommonMark](https://spec.commonmark.org/dingus/) and it has the same error. But https://markdowntohtml.com/ works well.

**Expected behavior**
The first Markdown link `First [foo bar bas](#1123)` should be converted to HTML link.

Is this behaviour expected? Thanks for the help.

**Comment by UziTech** [comment]
According to the [common mark spec](https://spec.commonmark.org/0.31.2/#html-blocks) an html element ends at the first blank line. So the first link is part of the`<abc>` element.

**Comment by ABCbum** [comment]
ah, got it. Thanks! @UziTech
