### ISSUE TITLE
Cannot use a custom renderer to override the link renderer.

### ISSUE THREAD

**Issue by creeper-0910** [markedjs/marked#3388]
**Marked version:**
v13.0.3
**Describe the bug**

**To Reproduce**
Override the link renderer with the following code.
```js
const marked = new Marked();
const originalRenderer = new Renderer();
originalRenderer.parser = new Parser();

marked.use({
  breaks: true,
  useNewRenderer: true,
  renderer: {
    link({tokens, href, text}) {
      console.log(`${tokens}`);
      return `<a target="_blank" href="${href}">${text}</a>`;
    },
  },
});
```

**Expected behavior**
The link renderer is overridden and target="_blank" is added to the html.

**Comment by creeper-0910** [comment]
It seems to work fine in v12, so I assume this problem is due to the new renderer.

**Comment by sernaferna** [comment]
I'm having the same issue and it seems to have come up recently. My implementation was pretty much exactly the same as what's listed above, but for troubleshooting purposes I tried this (TypeScript):

```TypeScript
export const LinksInNewWindow: Partial<Omit<Renderer, 'options'>> = {
  link(tokens) {
    const { href, raw, text, type, title } = tokens;
    console.log('typeof tokens:', typeof tokens);
    console.log('tokens:', tokens);
    console.log('tokens.tokens:', tokens.tokens);
    console.log('href:', href);
    console.log('raw:', raw);
    console.log('text:', text);
    console.log('type:', type);
    console.log('title:', title);
    return `<a href="${href}" title="${title}" target="_blank">${text}</a>`;
  },
};
```

Here's what I saw at the console, when using markdown like this: `[click here](https://www.google.ca)`:

```
typeof tokens: string
tokens: https://www.google.ca
tokens.tokens: undefined
href: undefined
raw: undefined
text: undefined
type: undefined
title: undefined
```

**Comment by UziTech** [comment]
Have you tried using the parser to parse the text as shown in [the docs](https://github.com/markedjs/marked/releases/tag/v13.0.0)?

**Comment by creeper-0910** [comment]
> Have you tried using the parser to parse the text as shown in [the docs](https://github.com/markedjs/marked/releases/tag/v13.0.0)?

Is the code you provided as an example not enough?
The heading renderer, can be successfully overridden with the same code, but only the link renderer seems to be unable to be successfully overridden.

**Comment by UziTech** [comment]
```js
import { Marked, Renderer, Parser } from 'marked';

const marked = new Marked();
const originalRenderer = new Renderer();
originalRenderer.parser = new Parser();

marked.use({
  breaks: true,
  useNewRenderer: true,
  renderer: {
    link({ tokens, href, text }) {
      return `<a target="_blank" href="${href}">${text}</a>`;
    },
  },
});

console.log(marked.parse('[link](https://example.com)'));
// <p><a target="_blank" href="https://example.com">link</a></p>
```

seems to work for me. But if you want markdown formatting in the text you will need to use the parser like in the docs

```
return `<a target="_blank" href="${href}">${this.parser.parseInline(tokens);}</a>`;
```

**Comment by creeper-0910** [comment]
Apparently, it does not work correctly when using link in a bulleted list.

**Comment by sevenc-nanashi** [comment]
I think the problem is that `text` uses `originalRenderer`, in other words, renderer without custom `link` to generate htmls inside.

It would be good to have a way to do `super` somehow.

**Comment by UziTech** [comment]
> There seems to be a problem with the code you are currently using...

That is the same code from your first example.

> If I override renderer.text and renderer.link and then use bullet points and links together, it does not seem to work correctly.

That is because you are not using `parseInline` for the text like the docs show.

**Comment by UziTech** [comment]
> It would be good to have a way to do super somehow

 @sevenc-nanashi if you can create a PR that would be great 😃 👍

**Comment by creeper-0910** [comment]
> > There seems to be a problem with the code you are currently using...
> 
> That is the same code from your first example.
> 
> > If I override renderer.text and renderer.link and then use bullet points and links together, it does not seem to work correctly.
> 
> That is because you are not using `parseInline` for the text like the docs show.
If parseInline is used, the output will look like the following and cannot be used because bullets will not work.
```
<budoux-ja>- </budoux-ja><a target="_blank" href="https://example.com/">link</a>
```
![image](https://github.com/user-attachments/assets/dbde65b3-cad0-4994-811a-3255543bc51e)

**Comment by UziTech** [comment]
Have you tried using parseInline?

**Comment by UziTech** [comment]
> if parseInline is used, the output will look like the following and cannot be used because bullets will not work.

No using parseInline in the renderer functions like the docs show not marked.parseinline

**Comment by creeper-0910** [comment]
> > if parseInline is used, the output will look like the following and cannot be used because bullets will not work.
> 
> No using this.parser.parseInline in the renderer functions like the docs show not marked.parseinline

I am using marked.perseinline, is this not the correct way?

**Comment by UziTech** [comment]
No because list is a block element. Marked.parseInline only parses inline elements.

**Comment by creeper-0910** [comment]
> No because list is a block element. Marked.parseInline only parses inline elements.

So what should we do if we want to parse both elements...?

**Comment by UziTech** [comment]
marked.parse will parse both

**Comment by creeper-0910** [comment]
So how can I use marked.parser to parse correctly when using renderer.text and renderer.link...?
An example would be great.
This may be a little too difficult for me.

**Comment by woss** [comment]
I've spent 1h today moving from 9->13 and the link override doesn't work. When I run the override functions and console log input params they are all undefined

**Comment by UziTech** [comment]
@creeper-0910  @woss To be able to help I will need to know
1. what extensions and versions you are using
2. What options you use
3. What is the input markdown 
4. What is the expected html

**Comment by creeper-0910** [comment]
1.marked: 13.0.3,No extensions are used.
2.
```js
marked.use({
  breaks: true,
  useNewRenderer: true,
  renderer: {
    // headingを一段階下げる
    heading({ text, depth }) {
      return `<h${depth + 1}>${text}</h${depth + 1}>`;
    },
    // budouxを適用する
    text(token) {
      const html = originalRenderer.text(token);
      return `<budoux-ja>${html}</budoux-ja>`;
    },
    link({ tokens, href, text }) {
      return `<a target="_blank" href="${href}">${text}</a>`;
    },
  },
});
```
3.`- [link](https://example.com)`
4.
```html
<budoux-ja>
     <ul>
          <li><a target="_blank" href="https://example.com/">link</a></li>
     </ul>
</budoux-ja>
```

**Comment by UziTech** [comment]
@creeper-0910 this should work. mostly changing `text` renderer for `list` renderer.

```js
import { Marked, Renderer } from 'marked';

const marked = new Marked();
const originalRenderer = new Renderer();

marked.use({
  breaks: true,
  useNewRenderer: true,
  renderer: {
    // headingを一段階下げる
    heading({ tokens, depth }) {
      const text = this.parser.parseInline(tokens);
      return `<h${depth + 1}>${text}</h${depth + 1}>`;
    },
    // budouxを適用する
    list(token) {
      const html = originalRenderer.list.call(this, token);
      return `<budoux-ja>${html}</budoux-ja>`;
    },
    link({ tokens, href }) {
      const text = this.parser.parseInline(tokens);
      return `<a target="_blank" href="${href}">${text}</a>`;
    },
  },
});

console.log(marked.parse("- [link](https://example.com)"));

```

**Comment by horizoncarlo** [comment]
Any roadmap plans to have `automatically adding target="_blank" to links` as a toggleable option? As I think that's a lot of the use cases for a custom link renderer.

Also is `useNewRenderer` a stopgap param that will be removed eventually? Would prefer to not have to make changes in my app constantly over a supporting package like this.

**Comment by UziTech** [comment]
@horizoncarlo you could make an extension that adds that 😁👍

**Comment by horizoncarlo** [comment]
Wow v13 didn't last long before v14. Guess I'll do another update in my project after just getting this issue fixed from going to v13
