### ISSUE TITLE
How to use marked for react?

### ISSUE THREAD

**Issue by Thecode764** [markedjs/marked#3400]
Hi i using typescript, react and next.js. how to use marked for react?

**Comment by UziTech** [comment]
https://www.npmjs.com/package/marked-react

**Comment by Thecode764** [comment]
@UziTech Thank you

**Comment by punkpeye** [comment]
Having issue with marked-react compatibility with other extensions

https://github.com/bent10/marked-extensions/issues/107

**Comment by UziTech** [comment]
The tokenizer extensions should work but any renderer extensions will need a renderer that outputs react instead of an html string.
