### ISSUE TITLE
`block` and `inline` are declared to TypeScript as exported, but are never exported

### ISSUE THREAD

**Issue by darkuranium** [markedjs/marked#3426]
**Marked version:** 14.0.0

**Describe the bug**
`marked.d.ts` marks both `block` and `inline` as `export declare const ...`, implying they are available for import. However, neither symbol is actually available (in neither CJS, ESM, *or* UMD form).

Note `marked.d.ts` declares both as exported:
```typescript
export declare const block: {
...
export declare const inline: {
...
```

But `marked.esm.js` (or `.cjs` & `.umd.js` files) do *not* in fact export it:
```javascript
export { _Hooks as Hooks, _Lexer as Lexer, Marked, _Parser as Parser, _Renderer as Renderer, _TextRenderer as TextRenderer, _Tokenizer as Tokenizer, _defaults as defaults, _getDefaults as getDefaults, lexer, marked, options, parse, parseInline, parser, setOptions, use, walkTokens };
```

**To Reproduce**
Simply install `marked@14.0.0`, and write the following (TypeScript!) file:
```typescript
// Okay as per TypeScript/tsc, but we get a runtime error: `SyntaxError: The requested module 'marked' does not provide an export named 'block'`
import { block, inline } from 'marked';
console.log(block, inline); // is *not* available
```

**Expected behavior**
The type declarations should match the actual exports --- either `marked.d.ts` should *not* declare those types as `export`, *or* (ideally) `block` & `inline` should actually be exported.

**Comment by UziTech** [comment]
Nice catch! 💯 

I don't think those should be exported since they are an implementation detail and they can change without releasing a major version.

**Comment by darkuranium** [comment]
For what it's worth, the reason I need these is to be able to hook into every single renderer, to output a token tree instead of HTML. Can you think of a better way of doing that?

**Comment by UziTech** [comment]
`marked.lexer(src, options)` will return a token tree.

Yes, `hooks.processAllTokens` is the way to get access to the output of `marked.lexer` before it goes to `walkTokens` then to `marked.parser` to be converted to html.
