### ISSUE TITLE
Emphasis and underscores in the middle of a word

### ISSUE THREAD

**Issue by silentvick** [markedjs/marked#343]
I'm using _marked.js_ v.0.3.1 with default settings.
Seems it breaks with underscores in the middle of word if there is also emphasis block in the same paragraph.

For example, this:

```
just_a_few_underscores
```

becomes this

```
just_a_few_underscores
```

as expected.

But this:

```
just_a_few_underscores. And here is the _emphasis_.
```

becomes:
justa __few_underscores. And here is emphasis._

Output html:

``` html
<p>just<em>a_few_underscores. And here is _emphasis</em>.</p>
```

**Comment by santhosh-tekuri** [comment]
+1

**Comment by suzanshakya** [comment]
+1

**Comment by joshbruce** [comment]
Closing as covered by CommonMark compliance. See also #1106 and #1216
