### ISSUE TITLE
Strong Tag Parsing Issue in Marked

### ISSUE THREAD

**Issue by JieAISmarties** [markedjs/marked#3433]
**Marked version:**
"marked": "12.0.1" and "marked": "14.0.0",

**Describe the bug**
Strong text cannot be parsed in certain strings.

**To Reproduce**

```
import { marked } from 'marked'

const text =  ' - 教育软件中**虚拟和增强现实**的应用增加\n   - **STEAM（科学学）**相关解决方案的扩展\n   - 整合**区块链技术**以实现安全的证书和成绩单管理'

  <div
    dangerouslySetInnerHTML={{
      __html: DOMPurify.sanitize(
        marked.parser(marked.lexer(text)), // 12.0.1 
      ),
    }}
  /> 
```

[The issue can be directly reproduced on the Marked Demo. You can click to visit it](https://marked.js.org/demo/?text=-%20%E6%95%99%E8%82%B2%E8%BD%AF%E4%BB%B6%E4%B8%AD**%E8%99%9A%E6%8B%9F%E5%92%8C%E5%A2%9E%E5%BC%BA%E7%8E%B0%E5%AE%9E**%E7%9A%84%E5%BA%94%E7%94%A8%E5%A2%9E%E5%8A%A0%20%20%0A-%20**STEAM%EF%BC%88%E7%A7%91%E5%AD%A6%E5%AD%A6%EF%BC%89**%E7%9B%B8%E5%85%B3%E8%A7%A3%E5%86%B3%E6%96%B9%E6%A1%88%E7%9A%84%E6%89%A9%E5%B1%95%0A-%20%E6%95%B4%E5%90%88**%E5%8C%BA%E5%9D%97%E9%93%BE%E6%8A%80%E6%9C%AF**%E4%BB%A5%E5%AE%9E%E7%8E%B0%E5%AE%89%E5%85%A8%E7%9A%84%E8%AF%81%E4%B9%A6%E5%92%8C%E6%88%90%E7%BB%A9%E5%8D%95%E7%AE%A1%E7%90%86%0A&options=%7B%0A%20%22async%22%3A%20false%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22extensions%22%3A%20null%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22hooks%22%3A%20null%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%0A%7D&version=12.0.1)

**Expected behavior**

The text "STEAM（科学学）" should be **bold** and wrapped in \<strong\> tags.

![image](https://github.com/user-attachments/assets/fdd7da73-e7db-42bc-bcf4-51dc485d35ba)

**Comment by UziTech** [comment]
Duplicate of #3410
