### ISSUE TITLE
Heading IDs?

### ISSUE THREAD

**Issue by benallfree** [markedjs/marked#3436]
I'm curious if marked can be modified to create heading IDs for linking.

Prior art:
* https://github.com/markedjs/marked/issues/207
* https://github.com/markedjs/marked/pull/199
* https://github.com/markedjs/marked/pull/181
* https://github.com/markedjs/marked/pull/117
* https://github.com/markedjs/marked/issues/1993
* https://github.com/markedjs/marked-custom-heading-id

This seems to work:

```js
  marked.use({
    useNewRenderer: true,
    renderer: {
      heading({ tokens, depth }) {
        const id = tokens[0].text
          .toLowerCase() // Convert to lowercase
          .trim() // Remove leading/trailing spaces
          .replace(/[^a-z0-9\-_ ]/g, '') // Remove invalid characters
          .replace(/\s+/g, '-') // Replace spaces with hyphens
          .replace(/^-+|-+$/g, '') // Remove leading/trailing hyphens
        return `<h${depth} id="${id}">${this.parser.parseInline(tokens)}</h${depth}>\n`
      },
    },
  })
```

**Comment by UziTech** [comment]
See [known extensions](https://marked.js.org/using_advanced#extensions)

[GFM heading ids](https://www.npmjs.com/package/marked-gfm-heading-id) or [Custom heading ids](https://www.npmjs.com/package/marked-custom-heading-id) should work.
