### ISSUE TITLE
HTML tag immediately after list item, bug or working as expected?

### ISSUE THREAD

**Issue by DarrenXu94** [markedjs/marked#3437]
**Marked version:** 
14

**Describe the bug**
When using a html tag immediately after a list item without a new line, the rendered HTML is invalid

**To Reproduce**
[marked demo](https://marked.js.org/demo/?outputType=html&text=-%20list%20item%0A-%20list%20item%0A%3Cdiv%20class%3D%22some-class%22%3E%0A%0AContent%0A%0A%3C%2Fdiv%3E%0A-%20list%20item&options=%7B%0A%20%22async%22%3A%20false%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22extensions%22%3A%20null%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22hooks%22%3A%20null%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%0A%7D&version=14.1.0)

```
- list item
- list item
<div class="some-class">

Content

</div>
- list item
```

generates 
```
<ul>
<li>list item</li>
<li>list item<div class="some-class"></li>
</ul>
<p>Content</p>
</div>
- list item
```

As you can see here the `<div>` tag is closed by the `</li>` before the closing div tag

**Expected behavior**
Here is a demo from the marked-it lib. Still doesn't do everything perfectly but at least generates valid html?

[marked-it demo](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22-%20list%20item%5Cn-%20list%20item%5Cn%3Cdiv%20class%3D%5C%22some-class%5C%22%3E%5Cn%5CnContent%5Cn%5Cn%3C%2Fdiv%3E%5Cn-%20list%20item%22%2C%22defaults%22%3A%7B%22html%22%3Atrue%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22src%22%7D%7D)

**Comment by UziTech** [comment]
This doesn't follow the [common mark demo](https://spec.commonmark.org/dingus/?text=-%20list%20item%0A-%20list%20item%0A%3Cdiv%20class%3D%22some-class%22%3E%0A%0AContent%0A%0A%3C%2Fdiv%3E%0A-%20list%20item) which is what we should be following. But honestly that is just really bad markdown so I am going to say that falls under garbage in garbage out.
