### ISSUE TITLE
newline char `\n` doesn't works

### ISSUE THREAD

**Issue by satyajitnayk** [markedjs/marked#3450]
**Marked version:**

**Describe the bug**
- newline char `\n` doesn't works , in demo as well as code(`# Marked in the browser\n\nRendered by **marked**.`)
<img width="1368" alt="image" src="https://github.com/user-attachments/assets/00917a67-9cbc-4390-8595-1b628987da9e">

- Only `<br>` tag works(`# Marked in the browser<br><br>Rendered by **marked**.`)
<img width="1363" alt="image" src="https://github.com/user-attachments/assets/62e0921b-9c51-4286-a418-50bab215c7bc">

**To Reproduce**

**Expected behavior**

**Comment by UziTech** [comment]
You have to actually put a new line. Putting `\n` in the demo is like adding `\\n`

[demo](https://marked.js.org/demo/?text=%23%20Marked%20in%20the%20browser%0A%0ARendered%20by%20**marked**.%0A&options=%7B%0A%20%22async%22%3A%20false%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22extensions%22%3A%20null%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22hooks%22%3A%20null%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%0A%7D&version=14.1.2)

**Comment by satyajitnayk** [comment]
sorry, my mistake! 
It works in code as well
<img width="868" alt="image" src="https://github.com/user-attachments/assets/9282c50b-48d5-433b-84bc-22e5e4f7b22c">
