### ISSUE TITLE
[question] Can embed tldraw and mermaid in marked content?

### ISSUE THREAD

**Issue by moonshineBoy** [markedjs/marked#3458]
Hi,

Is it possible to embed tldraw and mermaid content in the marked content?

the html can show markdown and custom drawing.

**Comment by UziTech** [comment]
They can be added by creating an extension similar to how we can add [katex](https://www.npmjs.com/package/marked-katex-extension) to marked. I don't see any existing extensions in our [known extensions](https://marked.js.org/using_advanced#extensions). If you would like to create them I would be happy to help.

**Comment by liaodalin19903** [comment]
> They can be added by creating an extension similar to how we can add [katex](https://www.npmjs.com/package/marked-katex-extension) to marked. I don't see any existing extensions in our [known extensions](https://marked.js.org/using_advanced#extensions). If you would like to create them I would be happy to help.

I will try. Whether need to keep the issue？

**Comment by UziTech** [comment]
Our official documentation or the code are the only reference material that I know of.

I'm going to close this as it isn't something the markedjs team will be working on. If you need help creating the extensions feel free to open a new issue or discussion. And please add the extensions to our[ known extensions](https://marked.js.org/using_advanced#extensions) if you create them.
