### ISSUE TITLE
Incorrect parsing of bold emphasis when immediately followed by non space character

### ISSUE THREAD

**Issue by terryyin** [markedjs/marked#3459]
**Describe the bug**

When parsing Markdown input where bold emphasis (`**`) wraps a character and is immediately followed by an alphanumeric character without any spaces (e.g., `**~**a`), Marked does not correctly render the emphasis. Instead of recognizing the bold syntax, it treats the asterisks as plain text.

**To Reproduce**

1. Use the following code to parse the Markdown input:

   ```javascript
   const marked = require('marked');
   const markdown = '**~**a';
   const html = marked.parse(markdown);
   console.log(html);
   ```

3. **Actual output:**

   ```html
   <p>**~**a</p>
   ```

4. **Expected output:**

   ```html
   <p><strong>~</strong>a</p>
   ```

**Comparison with Other Parsers:**

- **CommonMark Dingus**: [Link to CommonMark Demo](https://spec.commonmark.org/dingus/?text=**~**a)

  - **Output:**

    ```html
    <p><strong>~</strong>a</p>
    ```

**Expected behavior**

Marked should parse `**~**a` and correctly recognize the bold emphasis, even when immediately followed by an alphanumeric character. The expected HTML output is:

```html
<p><strong>~</strong>a</p>
```

This behavior aligns with the [CommonMark specification](https://spec.commonmark.org/0.30/#example-392), which allows emphasis delimiters to be followed by alphanumeric characters without spaces.

**Comment by UziTech** [comment]
Your [Link to CommonMark Demo](https://spec.commonmark.org/dingus/?text=**~**a) shows it outputs the same as marked.
