### ISSUE TITLE
Is there a mdx compiler based on marked.js?

### ISSUE THREAD

**Issue by mathedu4all** [markedjs/marked#3465]
**What pain point are you perceiving?.**
I've customized some syntax to markdown. but existing mdx compiler's markdown renderer can not be overrieded.

**Describe the solution you'd like**
Is it possible to mod @mdx-js/mdx to achieve this?

**Comment by UziTech** [comment]
You will have to ask on the @mdx-js/mdx repo if you want to be able to override their renderer. I have not heard of mdx-js until now so I don't know much about it.

If you would like to add components to marked you can create a [custom extension](https://marked.js.org/using_pro#extensions).
