### ISSUE TITLE
Preserve every single new line

### ISSUE THREAD

**Issue by DevDuki** [markedjs/marked#3466]
**Marked version:**
14.0.0

**Describe the bug**
I want to preserve every single new line as a `<br/>` in html.

I tried the `breaks` option together with `gfm`, but this only preserves 1 line break in form of a `<p>`'s margin.

I additionally tried this strange workaround from this issue comment: https://github.com/markedjs/marked/issues/190#issuecomment-865303317
But that messes with the code blocks
![image](https://github.com/user-attachments/assets/f4ec9181-2977-4744-9b99-b35c665b394b)

I can achieve my exact desired result, if I use `parseInline` with `breaks: true`, but then my code blocks are no more blocks, but inline code instead.
```javascript
marked.parseInline(markdownText, { async: false, breaks: true })
```
How can I exclude block code from being parsed inline too? If there is an easier workaround for this, then maybe that's the better way to do it.

**To Reproduce**
https://marked.js.org/demo/?text=Line%201%0ALine%202%0A%0ALine%204%0A%0A%0ALine%207%0A%0A%0A%0A%0A%0Aline%2013%0A&options=%7B%0A%20"async"%3A%20false%2C%0A%20"breaks"%3A%20true%2C%0A%20"extensions"%3A%20null%2C%0A%20"gfm"%3A%20true%2C%0A%20"hooks"%3A%20null%2C%0A%20"pedantic"%3A%20false%2C%0A%20"silent"%3A%20false%2C%0A%20"tokenizer"%3A%20null%2C%0A%20"walkTokens"%3A%20null%0A%7D&version=14.1.2

**Expected behavior**
A simple option, where every single line breaks is preserved as a `<br/>`. (except in code blocks)

**Comment by UziTech** [comment]
Since that is not is not how markdown is supposed to work you will have to create a [custom extension](https://marked.js.org/using_pro#extensions) for that.

The extension can just have a tokenizer that looks for newline characters and a renderer that outputs `<br/>` for that token.

**Comment by DevDuki** [comment]
But won't that also replace new lines in code blocks and replace them with `<br/>`? Which will end up in the same issue as in the screenshot?

**Comment by UziTech** [comment]
It shouldn't since it is just looking for the next newline. The code block will find the backticks and consume the whole code block before the custom extension finds a new line

**Comment by DevDuki** [comment]
I can't get it to work. It somehow swallows line with only one new line and sometimes completely ignores new lines. I think I somehow have to prevent each new line being converted into a `<p>` too, don't I?

This is what I got so far.
```javascript
export const newlineExtension: TokenizerAndRendererExtension = {
  name: 'newLine',
  level: 'inline',
  renderer(token) {
    console.log('renderer', token);
    return '<br/>';
  },
  tokenizer(src: string) {
    console.log('src in my etxtension', src);
    const newline = /^([\r\n])/;
    const cap = newline.exec(src);

    console.log(cap);
    if (cap) {
      return {
        type: 'newLine',
        raw: src,
      };
    }
  }
};
```

**Comment by UziTech** [comment]
Ya I don't think this will be an easy thing. You may have to rewrite existing tokenizers and renderers

**Comment by UziTech** [comment]
Something like this seems to work:

```js
import { Marked} from 'marked';

const newlineBreaks = {
  extensions: [
    {
      name: 'newlineBreaks',
      level: 'block',
      tokenizer(src) {
        const match = src.match(/^\n+/);
        if (match) {
          return {
            type: 'newlineBreaks',
            raw: match[0],
            text: match[0],
          };
        }
      },
      renderer(token) {
        return token.text.replace(/\n/g, '<br>\n');
      },
    },
  ],
};

const marked = new Marked(newlineBreaks);

console.log(marked.parse(`
line 1
line 2

line 4





line 10
`));
/*
<br>
<p>line 1
line 2</p>
<br>
<br>
<p>line 4</p>
<br>
<br>
<br>
<br>
<br>
<br>
<p>line 10</p>
<br>
*/
```

**Comment by DevDuki** [comment]
You're a hero! Thank you very much!

What I had to do additionally is to override the default `<p>` element style and make it `display: inline;`. It looks exactly how I wanted now!

**Comment by DevDuki** [comment]
(Reopening since you tagged it as a new feature)

**Comment by UziTech** [comment]
We'll close the NFE tag is just so we can keep track of extensions people have wanted over the years.
