### ISSUE TITLE
ANSI escape sequence rendering?

### ISSUE THREAD

**Issue by unphased** [markedjs/marked#3477]
**Describe the feature**
I would like to show colored terminal output in blog posts that I write in markdown.

**Why is this feature necessary?**
ansi escape codes are a kind of language, and should be possible to embed as a type of code block for markdown.

**Describe alternatives you've considered**
screenshots. Awful.

The question of how to best render ANSI styling to HTML is a bit thorny and isn't often asked. I am not surprised to find no mention of ansi escape sequences in the Marked repo so far.

Should be a good fit as a Marked extension. If no such already exists I'll attempt it. I'm looking at https://github.com/drudru/ansi_up for now for the implementation.

**Comment by unphased** [comment]
Cool. I have looked over the extension documentation page and it makes no mention of CSS. Is there any mechanism with extensions/`use` to manipulate CSS or is that sort of thing entirely outside of scope for Marked?

**Comment by UziTech** [comment]
Marked does not do anything with css. However you can use the postprocess hook to add whatever html you want. So you could prepend a link tag with the path to a css file

**Comment by unphased** [comment]
Thanks. I reviewed the doc but it's not clear to me how to most simply implement the handling for a new type of language. I would want to enable fenced code blocks, so the assumption i want to make now which i cannot easily confirm is there ought to be a way to specify it without creating tokenizer override code of at least two types to make this work. 

I did find this repo https://github.com/markedjs/marked-extension-template but i can't tell if it is relevant. Do you have an example, ideally the simplest possible functioning example, of how to handle an additional language in a code block and get it passed into a function which will render out HTML?

**Comment by unphased** [comment]
It looks like providing a tokenizer override (`return false to fall back to the previous override`) for `code(src: string)` should be my ticket. But it isn't clear what a markdown token is and how I should think about it. Though that might be on me for skipping straight to the extension documentation page "for pros".

**Comment by unphased** [comment]
Nope, see i was wrong. i think i just need to make a code **renderer**, as the existing code tokenizer should do what I need. Only if it fails to consume escape sequences somehow would i need to also provide a **tokenizer**. Alright I don't think there is anything obvious that could be improved with the doc. the only thing lacking is my intelligence.

**Comment by UziTech** [comment]
It sounds like you just want code highlighting. You can use https://www.npmjs.com/package/marked-highlight to make that easy and just run the code through [drudru/ansi_up](https://github.com/drudru/ansi_up) if it is the right language.

**Comment by UziTech** [comment]
Can you give me an example of a markdown file and the output html that you would like to see?

**Comment by unphased** [comment]
I already got it working. sorry i forgot to update here promptly. the code to make it work as intended is hilariously terse

```typescript
marked.use({ renderer: {
  code: ({ lang, text }) => lang === 'ansi' && ansi_up.ansi_to_html(text)
}});
```

**Comment by unphased** [comment]
I'm back! So, it is (just a little) more complex than this. 

The input token obtained in the renderer has `text` and `raw`. 

`text` is HTML encoded and excludes the code fence delimiters. This is very sensible default.

But I really need the non HTML encoded text. `raw` does provide me that, but I don't want the delimiters. I guess that's okay. 

So I can feed raw into the ansi_to_html and I am off to the races now.

**Comment by UziTech** [comment]
The `text` param shouldn't be escaped once it gets to that renderer. It is only escaped in the original renderer.

**Comment by unphased** [comment]
Hmm. that's mildly concerning. Any suggestions for how to troubleshoot that?

**Comment by UziTech** [comment]
If you console.log the text param you should see that nothing is escaped

```js
import { Marked } from 'marked';

const renderer = {
  code(token) {
    console.log(token.text);
    return `<pre><code>${token.text}</code></pre>`;
  },
};

const marked = new Marked({ renderer });

console.log(marked.parse(`
\`\`\`
<
&
>
\`\`\`
`));
```

output:

```
<
&
>
<pre><code><
&
></code></pre>
```

**Comment by unphased** [comment]
Great minimal starting point. I got it to do this escaping by adopting just the marked-highlight. 

```javascript
import { Marked } from 'marked';
import { markedHighlight } from "marked-highlight";
import hljs from 'highlight.js';

const renderer = {
  code(token) {
    console.log(token.text);
    return `<pre><code>${token.text}</code></pre>`;
  },
};

const marked = new Marked(
  markedHighlight({
    langPrefix: 'hljs language-',
    highlight(code, lang, info) {
      const language = hljs.getLanguage(lang) ? lang : 'plaintext';
      return hljs.highlight(code, { language }).value;
    }
  })
)
marked.use({ renderer });
marked.use({ async: true, gfm: true });

console.log(await marked.parse(`
\`\`\`
<
&
>
\`\`\`
`));
```

**Comment by UziTech** [comment]
If you are using marked-highlight you can just do the rendering in that function. `code` will be unescaped.

```js
import { Marked } from 'marked';
import { markedHighlight } from 'marked-highlight';
import hljs from 'highlight.js';
import ansi_up from 'ansi_up';

const marked = new Marked(
  markedHighlight({
    langPrefix: 'hljs language-',
    highlight(code, lang, info) {
      if (lang === 'ansi') {
        return `<pre><code>${ansi_up.ansi_to_html(code)}</code></pre>`;
      }

      const language = hljs.getLanguage(lang) ? lang : 'plaintext';
      return hljs.highlight(code, { language }).value;
    },
  }),
);
marked.use({ async: true, gfm: true });

console.log(await marked.parse(`
\`\`\`
<
&
>
\`\`\`
`));

```

**Comment by unphased** [comment]
Neato. But what it means though is if marked-highlight is in play, it introduces a change to extension interface? Isn't that still potentially a bug?

I'll def take your suggestion and implement it that way for now as it will allow me to avoid relying on the above quirk brought in by marked-highlight.

**Comment by unphased** [comment]
So to help me understand, basically when I implemented markedHighlight per documentation, it overrides how all code blocks are rendered, so i'm already receiving in as `text` to my ansi renderer a string that's **already been sent through `hljs.highlight(<<payload>>, { language: "ansi" }).value`?**

**Comment by UziTech** [comment]
The way marked-highlight [works](https://github.com/markedjs/marked-highlight/blob/main/src/index.js), it actually does the highlighting in `walkTokens` instead of in the renderer so it can be async. We could probably add something to that extension to use different renderers based on `lang`.

**Comment by unphased** [comment]
Doesn't that `highlight` function still function as the entry point for hljs? so if I set `highlight()` not to make the `hljs.highlight()` call upon finding an unsupported language, instead of specifying `plaintext`, wouldn't it do what I want? Then I'd be able to independently introduce my ansi extension to keep it cleanly separated. 

I was imagining this extensions works quite like express/koa middleware and it's intuitive for me. but i may be misunderstanding this. I have not dug into how tokenization works yet.

**Comment by UziTech** [comment]
Ya if you just return from the highlight function it shouldn't change the token

```js
import { Marked } from 'marked';
import { markedHighlight } from 'marked-highlight';
import hljs from 'highlight.js';

const renderer = {
  code(token) {
    console.log(token);
    return `<pre><code>${token.text}</code></pre>`;
  },
};

const marked = new Marked(
  markedHighlight({
    langPrefix: 'hljs language-',
    highlight(code, lang, info) {
      if (lang === 'ansi') {
        return;
      }

      const language = hljs.getLanguage(lang) ? lang : 'plaintext';
      return hljs.highlight(code, { language }).value;
    },
  }),
);
marked.use({ renderer });

console.log(marked.parse(`
\`\`\`ansi
<
&
>
\`\`\`
\`<&>\`
`));

```

**Comment by UziTech** [comment]
It looks like the inline [`codespan`](https://github.com/markedjs/marked/blob/master/src/Tokenizer.ts#L769) tokenizer does escape `text` before the renderer. That may be something we could fix.

**Comment by unphased** [comment]
Thank you! OK I am glad there is a falsy return value relief valve there. That means I can control that aspect of hljs processing.

I know this might be hljs specific, but I feel like it may be marked-highlight specific. Let me post in that repo.
