### ISSUE TITLE
In the following scenario, the distance between rows will increase

### ISSUE THREAD

**Issue by swanfly** [markedjs/marked#3486]
step1, input:
```
- 123
- 123
```

step2, input:
```
- 123
- 123

- 2
```

the spacing between rows increases

<img width="1017" alt="image" src="https://github.com/user-attachments/assets/a0f378c1-3745-4913-8890-0935ba9a7a34">

<img width="1218" alt="image" src="https://github.com/user-attachments/assets/3985a6b5-23dc-4c3f-b5c5-432f0999a3d4">

**Comment by UziTech** [comment]
That is called a [loose list](https://spec.commonmark.org/0.31.2/#loose).

**Comment by swanfly** [comment]
i got it, thank you
