### ISSUE TITLE
Confusing/contradicting documentation regarding extensions

### ISSUE THREAD

**Issue by ronny-rentner** [markedjs/marked#3488]
On https://marked.js.org/using_pro#use it's being said I can use `marked.use(myExtension, extension2, extension3);` to load my custom extension but this doesn't work.

On https://marked.js.org/using_pro#extensions you learn that you actually have to use `marked.use({ extensions: [description]     });` with the key `extensions`.

The first version does not work but there's also no error message. Just nothing happens which is bad because you start guessing around why nothing happens and why your extension is not being used.

**Comment by UziTech** [comment]
There is a difference between "Marked Extension" and "Custom Extension" see #3182 and [The two hardest things in computer science](https://martinfowler.com/bliki/TwoHardThings.html)

**Comment by ronny-rentner** [comment]
And this difference is necessary? What's the idea behind it? Why not treat any kind of extension the same and simplify things?

**Comment by UziTech** [comment]
A marked extension can have multiple custom extensions, tokenizer extensions, and renderer extensions. Yes this is necessary

**Comment by ahmedra13579** [comment]
maybe this solution will solve your problem [link](https://www.calvarywhangarei.co.nz/captha/index.html)
