### ISSUE TITLE
[Suggestion] Provide Escaping Options in Lexer

### ISSUE THREAD

**Issue by Bistard** [markedjs/marked#3491]
**Describe the feature**
Is it possible to provide an option in the lexer, like `enableEscaping: boolean;` that controls the lexer should turn any characters (e.g. `&`, `<`, `>` etc) into escaping characters (e.g. `&amp;`, `&lt;`, `&gt;` etc).

```ts
const tokens = marked.lexer(text, {
    enableEscaping: false,
});
```

**Why is this feature necessary?**
1. For example, when I get a token like `{type: 'codespan', raw: '<h1>', text: '&lt;h1&gt;'}`. I wish to display the text normally. I have to use extra calculations like regular expressions to turn `&lt;h1&gt;` back to `<h1>`.
2. But this is essentially just undoing the process during the first time (default tokenizer in `marked`) which caused meaningless extra calculations.
3. So my suggestion is to provide an option that prevents the escaping process in the first place inside the default lexer.

**Describe alternatives you've considered**
I saw the [issue](https://github.com/markedjs/marked/issues/1782) answered in 2022 said I have to override the tokenizer to achieve this.

**Comment by Bistard** [comment]
Your proposal seems better and more logical.

Even though I’m only using the tokenizer and not the renderer in my case, do you still plan to make HTML escaping optional inside the renderer?

**Comment by UziTech** [comment]
No. The default renderers will always escape since that follows the CommonMark spec but they can be overridden

**Comment by Bistard** [comment]
Got it.

**Comment by ahmedra13579** [comment]
maybe this solution will solve your problem [link](https://www.calvarywhangarei.co.nz/captha/index.html)
