### ISSUE TITLE
[Question] When lexing paragraphs, why `\n` is missing in the `token.text` when it is located at the end of the paragraph.

### ISSUE THREAD

**Issue by Bistard** [markedjs/marked#3501]
**Marked version:** 14.1.2

**Describe the bug**
Consider the following two cases when using the `marked` lexer:
![image](https://github.com/user-attachments/assets/73c97623-553e-4ffa-bc2f-74c13c0c36e1)
The lexer data are:
```
[{type:"paragraph", raw:"paragraph1\n", text:"paragraph1", tokens:[
  {type:"text", raw:"paragraph1", text:"paragraph1"}
]}]
```
and
```
[{type:"paragraph", raw:"paragraph1\nparagraph2", text:"paragraph1\nparagraph2", tokens:[
  {type:"text", raw:"paragraph1\nparagraph2", text:"paragraph1\nparagraph2"}
]}]
```

**Why**:
1. In the first case, in `paragraph` token, `\n` is not included in the `token.text` but only exists in `token.raw`.
2. In the second case, in `paragraph` token, `\n` exists in both `token.text` and `token.raw`.

Is it expected behavior🤔?

**To Reproduce**
Steps to reproduce the behavior: You can type the content into the [official marked demo](https://marked.js.org/demo/?outputType=lexer&text=paragraph1%0Aparagraph2&options=%7B%0A%20%22async%22%3A%20false%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22extensions%22%3A%20null%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22hooks%22%3A%20null%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%0A%7D&version=14.1.2) to double check the lexer data.

**Expected behavior**
I was expecting In the first case, in `paragraph` token, `\n` exists in both `token.text` and `token.raw`.

**Comment by UziTech** [comment]
Yes, this is expected. The last `\n` is not part of the paragraph tokens so it is not included in the text. There isn't anything that says it can't be included in text but that is how it has always been and I don't see any reason to change it.

**Comment by Bistard** [comment]
Got it! Thanks for the quick response!
