### ISSUE TITLE
A grammar mistake

### ISSUE THREAD

**Issue by yinxiaoli2007** [markedjs/marked#3502]
lib/marked.esm.js   

```
  static passThroughHooks = new Set([
    'preprocess',
    'postprocess'
  ]);
```
should 
` passThroughHooks() {
        return new Set([
            'preprocess',
            'postprocess'
        ]); // 在方法中创建 Set 实例
 }
`
acornjs check mistake

**Comment by yinxiaoli2007** [comment]
const acorn = require('acorn');
const code = `

static passThroughHooks = new Set([
    'preprocess',
    'postprocess'
]);

`;
try {
    acorn.parse(code, {
        sourceType: 'script',
        ecmaVersion: '2020',
        locations: true,
        allowReserved: true
    });
    return true;
} catch (ex) {
    const len = 30;
    console.log('...' + code.substr(ex.pos - len, len * 2) + '...');
    console.log(new Array(len + 3).join('-') + '^');
    console.log(ex.message);
    return false;
}

// please Run the code above，output:Unexpected token,  thanks

**Comment by UziTech** [comment]
looks like it is a bug in acorn
