### ISSUE TITLE
[bug] `CodeBlock` - mismatched end fence behave differently

### ISSUE THREAD

**Issue by Bistard** [markedjs/marked#3514]
**Marked version:** 14.1.2

**Describe the bug**
Consider when lexing the following two texts (both have end fence with length 4):
```js
// "```\nmismatched\n````"
// "```\nmismatched\n~~~~"
```
The following are their tokenized result:
```js
{type:"code", raw:"```\nmismatch\n````", lang:"", text:"mismatch"},
{type:"code", raw:"```\nmismatch\n~~~~", lang:"", text:"mismatch\n~~~~"}
```

**Expected behavior**
🤔I was expecting:
```js
{type:"code", raw:"```\nmismatch\n````", lang:"", text:"mismatch"},
{type:"code", raw:"```\nmismatch\n~~~~", lang:"", text:"mismatch"}
```
or just
```js
{type:"code", raw:"```\nmismatch\n````", lang:"", text:"mismatch\n````"},
{type:"code", raw:"```\nmismatch\n~~~~", lang:"", text:"mismatch\n~~~~"}
```

**Comment by UziTech** [comment]
As you can see in these demos the `text` property is the code that is displayed

[demo 1](https://marked.js.org/demo/?text=%60%60%60%0Amismatched%0A%60%60%60%60&options=%7B%0A%20%22async%22%3A%20false%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22extensions%22%3A%20null%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22hooks%22%3A%20null%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%0A%7D&version=14.1.3)

[demo 2](https://marked.js.org/demo/?text=%60%60%60%0Amismatched%0A~~~~&options=%7B%0A%20%22async%22%3A%20false%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22extensions%22%3A%20null%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22hooks%22%3A%20null%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%0A%7D&version=14.1.3)

**Comment by Bistard** [comment]
I mean, since in both cases the ending fence are mismatched, aren't they should both be (or not be) handled in the `text` property for simplicity and consistency?

**Comment by UziTech** [comment]
This is the same behavior as CommonMark

[demo 1](https://spec.commonmark.org/dingus/?text=%60%60%60%0Amismatched%0A%60%60%60%60)

[demo 2](https://spec.commonmark.org/dingus/?text=%60%60%60%0Amismatched%0A~~~~)

**Comment by Bistard** [comment]
OK. That make sense. I should check common mark first. Thanks for the response.
