### ISSUE TITLE
Ability to provide renderer methods as a plain object

### ISSUE THREAD

**Issue by jasonkarns** [markedjs/marked#352]
I'm considering a pull request that would simplify the overriding of renderer methods. Presently, the `renderer` option is an all-or-nothing approach. Whatever is set as the renderer must implement the entire Renderer interface. So for the common use case where only a couple element renderers actually need customized, one must instantiate the default renderer and override the functions as needed.

I think a more streamlined API would allow the `renderer` option to accept a plain old object such that only the custom render functions need to be provided.

``` coffeescript
marked.setOptions
  renderer:
    heading: ->
    code: ->
```

It would be a minor change, simply instantiating the renderer internally and merging in the custom options.renderer object.

Concerns?

**Comment by Feder1co5oave** [comment]
I kinda like this. Flag it for 0.5.0 @joshbruce ?

**Comment by joshbruce** [comment]
Agreed. Thinking the breakout will be something like:

- lexer
- parser
- renderer

Which each of those hopefully following the open-closed principle. Then we may even consider removing some of the configuration options, which I think technically modify the behavior, which may be awkward for other developers.

**Comment by UziTech** [comment]
ES6 has an even easier way to do this:

```js
marked.setOptions({
    renderer: {
        ...new marked.Renderer(),
        strong: function() { return ''; }
    });
});
```

**Comment by jasonkarns** [comment]
The object spread operator is ES2018

**Comment by UziTech** [comment]
This is possible with [`marked.use`](https://marked.js.org/using_pro#use)
