### ISSUE TITLE
Marked Demo Format Conversion Issue

### ISSUE THREAD

**Issue by tom-style** [markedjs/marked#3525]
**Marked version:**
14.1.3

**Describe the bug**
The format conversion in the Marked Demo (https://marked.js.org/demo) seems to be incorrect. Specifically, when converting a string containing Chinese punctuation, the resulting HTML is not as expected.

**To Reproduce**

1. Go to the [Marked Demo](https://marked.js.org/demo/) page.
2. Enter the following string: `Marked Demo（https://marked.js.org/demo），Marked Demo`.
3. Observe the converted HTML output.

Expected Output:

`html
Marked Demo（<a href="https://marked.js.org/demo">https://marked.js.org/demo</a>），Marked Demo
`

Actual Output:

`html
Marked Demo（<a href="https://marked.js.org/demo%EF%BC%89%EF%BC%8CMarked">https://marked.js.org/demo），Marked</a> Demo
`

**Comment by UziTech** [comment]
As you can see in this [demo](https://marked.js.org/demo/?text=%EF%BC%88https%3A%2F%2Fmarked.js.org%2Fdemo%EF%BC%89%EF%BC%8CMarked%20Demo.&options=%7B%0A%20%22async%22%3A%20false%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22extensions%22%3A%20null%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22hooks%22%3A%20null%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%0A%7D&version=14.1.4)

Does the same thing as GitHub.

```
（https://marked.js.org/demo），Marked Demo.
```

（https://marked.js.org/demo），Marked Demo.

For autolinks we try to follow what GitHub would do. In this case it is working as expected. 

If you would like to change marked to not work like GitHub you can create an [extension](https://marked.js.org/using_pro#tokenizer) that changes the autolink tokenizer.

**Comment by tom-style** [comment]
@UziTech 
Thank you for your explanation. I understand that Marked tries to mimic GitHub's behavior when handling autolinks. However, in my use case, the input strings can come from various sources, including user inputs and external APIs. This leads to unpredictable behavior, especially when dealing with links that contain commas or other special characters.

Is there a way to ensure that Marked works predictably in all scenarios, without variations due to different input sources? For example, can this be achieved through configuration options or extensions?

Additionally, regarding the method of wrapping links in angle brackets, while it can solve some issues, it is not always feasible to manually add angle brackets to user inputs. Are there any more general solutions available?

Thanks!

**Comment by UziTech** [comment]
The problem is that there is no "right" way to do it. Everyone's idea of what is "right" is different. So we have to have a specification that tells us the rules in order for everyone to agree on the right way. For example which punctuation stops an auto link is specified in the [GFM spec](https://github.github.com/gfm/#autolinks-extension-). You don't seem to agree with that spec so you will have to create your own extension with the rules that you want.
