### ISSUE TITLE
Exporting helper functions for extension authors

### ISSUE THREAD

**Issue by caizixian** [markedjs/marked#3534]
**Describe the feature**
Exporting helper functions, such as `escape`, so that extension authors can reuse them.
These functions could be placed under a separate namespace to highlight that the underlying implementation is subject to change.

**Why is this feature necessary?**
In marked v15, escaping is moved from tokenizer to renderer, and there're a bunch places in renderer that one needs to escape the input. A natural way (at least in my experience) to write a custom renderer is to start from the stock version and change certain aspects of it. Writing one from scratch would be error-prone. But this would require accessing some of the helper functions.

**Describe alternatives you've considered**
Extension authors can write their own helper functions, or copy-paste from the marked codebase. But this is error-prone.

**Comment by UziTech** [comment]
These helper functions are part of marked internals. We do not want to have to release a major version every time these change. You can just copy the functions if you want to use them in an extension. That can't be any more error prone than calling the same code from marked codebase.

**Comment by caizixian** [comment]
@UziTech thanks for the response. I managed to work around most of the problems by invoking methods of `this.parser`.
