### ISSUE TITLE
After parsing the content enclosed by xx, the line breaks were lost. How can we preserve the line breaks after parsing

### ISSUE THREAD

**Issue by swanfly** [markedjs/marked#3535]
After parsing the content enclosed by xx, the line breaks were lost. How can we preserve the line breaks after parsing

input:
``
abc
def
``

parsed:
<p><code>abc def</code></p>

<img width="661" alt="image" src="https://github.com/user-attachments/assets/6dc1f5ee-94ae-40ad-8fd0-61626af897ca">

**Comment by UziTech** [comment]
Add a third backtick
````
```
abc
def
```
````

**Comment by swanfly** [comment]
If I want to keep a line break between two backsticks, can I do it？

**Comment by UziTech** [comment]
Ya you can create a custom extension to do it with two backticks

**Comment by swanfly** [comment]
> Ya you can create a custom extension to do it with two backticks

i got it, thank you!
