### ISSUE TITLE
Support Telegram Emoji HTML

### ISSUE THREAD

**Issue by ZephyrPhrost** [markedjs/marked#3536]
Hello, is the emoji part supported when parsing markdown?

https://core.telegram.org/bots/api#html-style

e.g: `![👍](tg://emoji?id=5368324170671202286)` to `<tg-emoji emoji-id="5368324170671202286">👍</tg-emoji>`

**Comment by UziTech** [comment]
You will have to create an [extension](https://marked.js.org/using_pro#extensions) for this. Or check the [known extensions](https://marked.js.org/using_advanced#extensions) to see if someone else made one that will work for you.
