### ISSUE TITLE
Headings not rendering as headers in Astro collections. 

### ISSUE THREAD

**Issue by mpstaton** [markedjs/marked#3542]
**Marked version:**
    "marked": "^14.1.2",

**Describe the bug**
Not rendering headers as headers, rendering them as Paragraph content.  

**To Reproduce**
No idea.  Just doesn't work.  

This is the returned object through a console.log. This is in the section.body returned object, which is called through marked.parse(section.body)
[
  {
    id: 'introduction.md',
    slug: 'introduction',
    body: '\n' +
      '#Introduction\n' +
      '\n' +
      'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Blanditiis ullam iste sequi excepturi explicabo animi sit doloribus nobis quasi? Nemo sunt facilis delectus molestiae aspernatur, porro est debitis commodi voluptatem.\n',
    collection: 'sections',
    data: {
      title: 'Introduction',
      pubDate: 2024-09-16T00:00:00.000Z,
      recentUpdate: 2024-09-16T00:00:00.000Z,
      author: 'Michael Staton',
      tags: [Array]
    },
    render: [AsyncFunction: render]
  },

The hashtag header just renders in the browser as a <p> when it should be an <h1>:
<img width="1173" alt="image" src="https://github.com/user-attachments/assets/da24d654-377f-45bf-9af4-253eaedef167">

**Comment by UziTech** [comment]
You need a space after the hashtag

```
# introduction 
```

**Comment by mpstaton** [comment]
> You need a space after the hashtag
> 
> ```
> # introduction 
> ```

That's hysterical, I just figured that out after doing something totally different.  

No idea what to do with this then...
