### ISSUE TITLE
[Bug] The code is not displayed

### ISSUE THREAD

**Issue by webfullsympathy** [markedjs/marked#3550]
**Marked version:?**

**Describe the bug**
I am Japanese. The syntax might be strange because I am using automatic translation. I wanted to create a blog, so I downloaded JS and applied it to my site. (Applied marked.js in HTML instead of NPM)

However, the code enclosed in ``` becomes "[object Object]". The code is long and complicated, so please see it [here](https://github.com/webfullsympathy/blog.webfullsympathy.com). The page where the error occurs is [here](https://blog.webfullsympathy.com/article/?p=1). It might not be working because I am using other libraries as well.

**To Reproduce**
Use the following code in Markdown.

```
[```]html:all.html
<a href='article/index.html?p=[PageID]'><h1>[Title]</h1></a>
[```]

```

This is part of an article announcing the creation of a blog and explaining the mechanism. This is an HTML template for the article list, which was used in Markdown. Then, the example error occurs.

**Expected behavior**
The code is displayed correctly.

**Comment by UziTech** [comment]
It looks like you are using marked v15 which does not have a `highlight` option (use the [marked-highlight](https://www.npmjs.com/package/marked-highlight) extension instead) and the renderer receives an object as the first parameter instead of multiple parameters (as of v14).

**Comment by webfullsympathy** [comment]
Thank you very much! The code has been properly reflected!
