### ISSUE TITLE
Placeholder row(3 blank line), not be parsed

### ISSUE THREAD

**Issue by fanybook** [markedjs/marked#3551]
**What pain point are you perceiving?.**
placeholder row(3 blank line), should be parsed, or give a switch option

**Describe the solution you'd like**
like typora, not like github, because it looks more pretty.

example：

typora & github: 1p with br
marked: 1p without br
```
> hello1
> world1
```
> hello1
> world1

typora & github & marked: 2p
```
> hello2
>
> world2
```
> hello2
>
> world2

typora: 3p?
github & marked: still 2p
```
> hello3
>
>
>
> world3
```
> hello3
>
>
>
> world3

**Comment by UziTech** [comment]
Marked supports CommonMark, GFM, and original markdown. If you want a behavior that is not one of those standards you can create a [custom extensions](https://marked.js.org/using_pro#extensions) to change or add token types that act how you want.

**Comment by fanybook** [comment]
i know, it can be customized like this https://github.com/markedjs/marked/issues/3543

i know, it can enable GFM supports
```
        marked.setOptions({
            renderer: renderer,
            gfm: true, // enable GFM (GitHub Flavored Markdown)
            breaks: true, // enable GFM breaks
            tables: true, // enable GFM tables
        })
```

but，i hope the Placeholder row(3 blank line) can be parsed like typora, because it looks more pretty.

**Comment by UziTech** [comment]
You can use the space token or you can create your own token for 3 blank lines
