### ISSUE TITLE
 [BUG] marked.parse() deathloops on invalid markdown since 15.0.1

### ISSUE THREAD

**Issue by endlacer** [markedjs/marked#3559]
**Marked version:**
15.0.1

**Description**
When parsing this markdown:
```
XXXX

- - - - - - - - - - - - - - - - - - - - - - - - -
xxxx
```
Marked crashes when parsing markdown containing multiple hyphens as a horizontal rule pattern since version 15.0.1 (worked in 15.0.0) when the `<hr>` feature is deactivated.

Steps to reproduce:
1. Visit https://stackblitz.com/edit/waxomj3x?file=src%2Fmain.ts
2. Click "translate"
3. Browser enters an infinite loop in the hr-tokenizer function

**Comment by UziTech** [comment]
Looks like the list tokenizer is what is looping forever because it tries to skip a list item that looks like an hr. Should be fixed in #3560
