### ISSUE TITLE
输入iframe时会被执行，是设计如此还是问题呢

### ISSUE THREAD

**Issue by CHENFANGC** [markedjs/marked#3565]
**Marked version:**
all
**Describe the bug**
demo https://marked.js.org/demo/?text=%3Ciframe%20src%3D%22javascript%3Aalert(%27Your%20user%20token%20is%3A%20%27%2BlocalStorage.getItem(%27userToken%27)%2B%27%20Cookies%3A%20%27%2Bdocument.cookie)%22%3ETrust%20No%20AI%3C%2Fiframe%3E&options=%7B%0A%20%22async%22%3A%20false%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22extensions%22%3A%20null%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22hooks%22%3A%20null%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%0A%7D&version=15.0.4

输入以下内容
<iframe src="javascript:alert('Your user token is: '+localStorage.getItem('userToken')+' Cookies: '+document.cookie)">Trust No AI</iframe>
输出结果是iframe被执行，期望结果是不被执行，以代码块儿形式展示

![image](https://github.com/user-attachments/assets/8767c07a-2699-4545-90f8-bc080930ad58)

**To Reproduce**

**Expected behavior**

**Comment by UziTech** [comment]
This is expected html is left alone according to the [CommonMark spec ](https://spec.commonmark.org/0.31.2/#html-blocks)
