### ISSUE TITLE
Incorrect Line Recognition

### ISSUE THREAD

**Issue by kpripper** [markedjs/marked#3573]
**Marked version:**

15.0.4

**Describe the bug**

The library transforms the input text:

```
**Jeffrey Carling, PhD**
**Geographer and Cartographer**
**University of Cambridge**

**How many kilometers from Poland to Russia?**
```
into the following output:
```
<p><strong>Jeffrey Carling, PhD</strong> <strong>Geographer and Cartographer</strong> <strong>University of Cambridge</strong></p>  
<p><strong>How many kilometers from Poland to Russia?</strong></p>  
```

As a result, the text "Jeffrey Carling, PhDGeographer and CartographerUniversity of Cambridge" appears merged without proper line separation.

This issue likely stems from incorrect handling of newline characters or spacing during the formatting process.

**Expected behavior**
```
<p><strong>Jeffrey Carling, PhD</strong> </p> 
<p><strong>Geographer and Cartographer</strong></p> 
<p><strong>University of Cambridge</strong></p>  
<br>
<p><strong>How many kilometers from Poland to Russia?</strong></p>  
```

**Comment by UziTech** [comment]
This is how markdown is supposed to work, and this is consistent with with `.md` files in GitHub.

The [CommonMark](https://spec.commonmark.org/0.31.2/#paragraphs) spec states:

> A sequence of non-blank lines that cannot be interpreted as other kinds of blocks forms a [paragraph](https://spec.commonmark.org/0.31.2/#paragraph). The contents of the paragraph are the result of parsing the paragraph’s raw content as inlines. The paragraph’s raw content is formed by concatenating the lines and removing initial and final spaces or tabs.

GitHub changes this for comments which adds `<br>` for newlines. In marked you can do this easily with the `breaks: true` option.

If you would like the lines to each be in their own `<p>` tag you will have to create a [custom extension](https://marked.js.org/using_pro#extensions) for marked.

**Comment by kpripper** [comment]
Yes, indeed. Sorry, I wasn't reading the documentation carefully.
