### ISSUE TITLE
Marked removes non-breaking spaces in the original text

### ISSUE THREAD

**Issue by arturi** [markedjs/marked#363]
Consider, say, a text like this:
`2 125 euro`
I've put a non-breaking space between `2` and `125` so that it would always end up on the same line.

Marked pre-parses the text and completely removes the original non-breaking characters that I've put there:

```
Lexer.prototype.lex = function(src) {
  src = src
    .replace(/\r\n|\r/g, '\n')
    .replace(/\t/g, '    ')
    .replace(/\u00a0/g, ' ')
    .replace(/\u2424/g, '\n');
  return this.token(src, true);
};
```

This is where the devil hides: `.replace(/\u00a0/g, ' ')`

Here is more on why invisible non-breaking space characters are cool: http://destroytoday.com/findings/fix-widows-with-non-breaking-spaces/

**Comment by Lendar** [comment]
@scy suggestion is nice. Let me extend it with an example. It might be helpful for future readers...

```
import marked from 'marked';

// monkey patch for marked 0.3.3 to preserve non-breaking spaces
marked.Lexer.prototype.lex = (src) -> {
  src = src
    .replace(/\r\n|\r/g, '\n')
    .replace(/\t/g, '    ')
    .replace(/\u2424/g, '\n');

  return this.token(src, true);
};
```

**Comment by RichardForrester** [comment]
Is anyone aware of an option or a work around for this issue?

There should definitely be an option to allow non-breaking spaces to pass to the HTML.

**Comment by arturi** [comment]
I’ve solved it by extending lex, as shown here: https://github.com/chjj/marked/issues/363#issuecomment-112853706.

**Comment by deanvaessen** [comment]
Hello everyone,

@Lendar 's suggestion is wonderful and if I edit this in the source code I can fix it this way. However putting it straight into my own code complains about 'this.token' not being a function. What is the best way to implement this?

Cheers!

**Comment by davidchambers** [comment]
I imagine the problem, @deanvaessen, is the arrow function. Try replacing `(src) => { ... }` with `function(src) { ... }`. :)

**Comment by deanvaessen** [comment]
Confirmed. Thank you @davidchambers  :)

**Comment by Lendar** [comment]
@davidchambers @deanvaessen  surprised it's still relevant. Updated the example in commment ⬆️

**Comment by yurikhan** [comment]
I am in the same boat as @scy — working on a Markdown-based presentation tool. I, too, want to control where lines break and where they never break. Please make an option that stops breaking non-breaking spaces.

As for browsers and/or WYSIWYG editors inserting non-breaking spaces where not expicitly requested by the user, that’s their bugs and should be fixed there.

**Comment by ArTiSTiX** [comment]
Up ?
Sometimes, non-breaking spaces are needed by the language (e.g. in French, [https://fr.wikipedia.org/wiki/Espace_ins%C3%A9cable](https://fr.wikipedia.org/wiki/Espace_ins%C3%A9cable), non-breaking spaces are necessary before '?', ':', '!', ';', thousand separators, phone numbers, and i also use then between quotes and where line-breaking should be avoided like brand names).

Thus, there is no reason for removing them (i would say non-breaking spaces should not be interpreted as syntax spaces).

PS: there is also no reason for anyone to monkey-patch marked. But it's a bit annoying to always work with minor-fix forks.

**Comment by oliviertassinari** [comment]
Alright, let's use @Lendar monkey patch :) for replacing
https://github.com/chjj/marked/blob/6b0416d10910702f73da9cb6bb3d4c8dcb7dead7/lib/marked.js#L142-L150

**Comment by joshbruce** [comment]
Closing as having a fix or workaround as the Marked library proper figures its life out. :)

**Comment by oliviertassinari** [comment]
@joshbruce So it's a `won't fix`.

**Comment by joshbruce** [comment]
@oliviertassinari: At this juncture I'm siding with @chjj on this one. See #956 as well:

1. XSS fixes were the focus.
2. Fixing known issues and complying with CommonMark and GFM are next; so, it's on our radar (@Feder1co5oave and @UziTech) as the spec does see it as a part of mixed content: http://spec.commonmark.org/0.28/#example-302 - see also #958 (if requested to be reopened by the primary contributors at this time, it will be)

I guess what I'm saying is, right now we have bigger fish to fry and it seems like there is a viable workaround in the meantime. Does that help?

**Comment by joshbruce** [comment]
Note: This only applies to explicit `&nbsp;` inclusion in the Markdown.

**Comment by oliviertassinari** [comment]
@joshbruce Thanks for the extra details. I wasn't sure what was the implication of the first answer.

**Comment by joshbruce** [comment]
@oliviertassinari: Fair. And sorry for not providing more - was in a rush going through issues. :)

**Comment by Feder1co5oave** [comment]
What wrote Christopher about people getting bit by this is at least debatable.
I also came across an example in commonmark where a non-breaking space changed the interpretation behaviour because it usually isn't allowed to be used in place of a single space. So if we want to comply I think we need to at least consider this.
I never used one but I guess some people use it so I see no point in replacing them altogether with single spaces.
However, if we merge this we must require it to be tested properly.

**Comment by joshbruce** [comment]
@Feder1co5oave: Reopen or no?

Again, I'm not sure if the original ticket was referring to the html encoded `&nbsp;` or a unicode character discovery - not the same thing in my book. As a user, I would expect the `&nbsp;` to be preserved, but not necessarily a special character injection of UTF-8 or something similar...am I wrong there. I concur that Chris's assessment is debatable.

Leave it to you, brother.

**Comment by Feder1co5oave** [comment]
I'm pretty sure `&nbsp;`s pass through without a problem. Whereas the
Unicode character is currently replaced by a single space. It seems it was
set this way because users somehow typed in unwanted non-breaking spaces,
but it seems to me this assumption is flimsy. Also you take away from
others the possibility to consciously use non-breaking spaces and I don't
like that. We certainly need to improve our Unicode support in general (per
commonmark), so I think this will change eventually. We need to make sure
everything works smoothly as usual.

**Comment by joshbruce** [comment]
All right. Leaving closed for now. Flagging with newly minted #1048 for when we're ready to focus there. This could also explain the Chinese character problems with header ids, yeah?

**Comment by Feder1co5oave** [comment]
Yes it's related to that and headings' ids

**Comment by Feder1co5oave** [comment]
Tagging as #1048

**Comment by joshbruce** [comment]
Tagging #1043 as well, just because of the "header ids" comment.

**Comment by UziTech** [comment]
related pr #897
