### ISSUE TITLE
Feature Request:  Process inside <DIV>

### ISSUE THREAD

**Issue by sgbotsford** [markedjs/marked#364]
I'm new here.   If this violates protocol, please instruct me on how FR's should be sumittted. .

One fuss I had with  every implemementation of MD I've used is that by default, it doesn't interpret MD inside of tags.  Most of the time this is what you want.  But with the DIV tag the default should be to interpret the code.  BODY and HTML are similar that way.

Some MD implementations have the construct <div markdown="1"> to enable interpretation inside the tag.  This is clunky.

Some MD implementations ignore tags written in upper case.  So <DIV> will permit interpretation where <div> does not.  However these implementations surround the <DIV> with <p> tags. All modern browsers are ok with this, but it breaks validation.

Since this is a variance from standard markdown (whatever that means...) it should be some form of configuration variable, with default to be the standard behavior, or alternately a command line parameter.

DIVs are container tags with no inherent other action.  I write my webpages in MD.  One thing I can do with interpreted div tags is the following:

```
<div markdown="1" class = picr >

![Young Balsam Fir](/Images/Balsam_Fir.jpg)

A three year old balsam fir that I planted in my poplar forest.  Planting close to an existing tree reduces the chance of being stepped on.

***

</div>

and then in my CSS picr is styled

.pic, .picr {
    width: 37%;
    }

.picr, .picr3, .picr6 {
    margin-left: 21px;
    float: right;
    }

.pic p, .picr p, .pic3 p, .picr3 p, .pic6 p, .picr6 p, .picfull p {
    font-style: italic;
    margin: 10px 0px 0px 0px ;
    }
```

Which means I can have text flow around pictures, a block of caption text that is in an identifyably different font.  One change means a gain of a LOT of flexibility in terms of the output.

**Comment by UziTech** [comment]
This seems to be fixed in v0.4.0
