### ISSUE TITLE
Parse complicated url problem

### ISSUE THREAD

**Issue by lufeihaidao** [markedjs/marked#366]
In github, `[Ajax](http://en.wikipedia.org/wiki/Ajax_(programming))` will be correctly parsed: [Ajax](http://en.wikipedia.org/wiki/Ajax_%28programming%29), but marked will add unnecessary `)`

**Comment by sn3p** [comment]
Encoding URLs is not option :(
This is a show stopper for us, and I have the feeling this won't be fixed any time soon...
Guess it's time to switch library. What would be a good alternative?

**Comment by dedalozzo** [comment]
I'm using [Hoedown](https://github.com/kjdev/php-ext-hoedown), a PHP extension to the Hoedown library.

**Comment by joshbruce** [comment]
#984
