### ISSUE TITLE
Get Markdown out of Lexer

### ISSUE THREAD

**Issue by glassresistor** [markedjs/marked#368]
I'm working on a markdown editor live preview, buttons that kind of [thing](http://glassresistor.github.io/demo-markdown-editor/)

Its much easier for me to walk the lexer and add/remove from it.  Is there a way to generate markdown from a set of tokens.

**Comment by christophe-g** [comment]
@glassresistor 

I am aware this issue is pretty old ... But would you have such a dictionary at hand ?

```
{
  'heading': function(token) {
    return '#'*token.depth + ' ' +token.text;
  },
...
}
```
