### ISSUE TITLE
Allow support for almond.js AMD loading

### ISSUE THREAD

**Issue by mtritschler** [markedjs/marked#372]
almond.js (https://github.com/jrburke/almond/) only loads modules that supply a specific name in `define(name, deps, factory)`. The current implementation just supplies a factory method, without a name or dependencies.

**Comment by iloire** [comment]
It would be awesome to have that PR merged

**Comment by joshbruce** [comment]
Closing as we would like to concentrate on compliance with specifications. See #1106 and #1216
