### ISSUE TITLE
Online Demo

### ISSUE THREAD

**Issue by soaj1664** [markedjs/marked#388]
Hi,

Is there any online demo of marked? I suppose the demo available here is the old version: http://daringfireball.net/projects/markdown/dingus

Is it normal behavior? The attacker can execute JavaScript code via JS URI.

```
      [click](javascript:alert%28location%29 "Title")
```

**Comment by jamiesonbecker** [comment]
Oh, yes, please consider XSS to be at least partially Marked's responsibility. For data that might go to different environments, such as the command line, we can't escape it just for HTML and then unescape it for other locations, so it needs to be safified last.

It can be literally this simple: https://github.com/jamiesonbecker/safify.js/blob/master/safify.js#L20

As long as you're using "simple" tags (no attributes etc), it's easy (no regex needed, just replace). In other words, do something like safify first, and then revert only the safe tags -- i.e., &lt;p&gt; to <p>.

Which leads to a potential workaround: a user could submit to Marked safify'ed text using safify.js. I don't know if that will catch all of the potential flaws, though. I'd be interested in putting together a safify version just for marked or something similar.

BTW, nice work.

**Comment by jamiesonbecker** [comment]
<script>alert(1)</script>
