### ISSUE TITLE
Refactor Tests for Flexibility

### ISSUE THREAD

**Issue by glassresistor** [markedjs/marked#391]
The current method for testing really abstracts the ability to say add the ability to pass in more complex options.
Being able to run actual unittests would allow me to implement the ability to do things like test passing in new rules to the lexer and rendered.

I'm working on this here but don't want to make a bunch of changes that can't be merged back in.

https://github.com/glassresistor/marked/tree/feature/add_rules

the general idea is

```
var renderer = new marked.Renderer();

renderer.newblock = function (text, level) {
  return '$$'
}
renderer.doubledollar = function (text, level) {
  return '$$'
}
var marked = require('marked');
marked.setOptions({
  renderer: new marked.Renderer(),
  extra_block_rules: {
    newblock: /^ {2,}\w(?!\s*$)/
  },
  extra_inline_rules: {
    doubledollar: /$$/
  },
  gfm: true,
  tables: true,
  breaks: false,
  pedantic: false,
  sanitize: true,
  smartLists: true,
  smartypants: false
});

console.log(marked('I am using __markdown__.'));
```

**Comment by joshbruce** [comment]
Closing as covered by latest testing harness.
