### ISSUE TITLE
Surpress wrapping in <p> tag.

### ISSUE THREAD

**Issue by stockholmux** [markedjs/marked#395]
Sometimes I want to write a fragment of markdown and just inject it into template. For example `[Email Example](mailto:mrexample@example.com)`. Marked seems to always wrap it in a `<p>` tag. Is there an existing way to suppress this behaviour? It makes sense if there is no new line character in the string - like this: `marked('[Email Example](mailto:mrexample@example.com)')`. I've tried different options (gfm, breaks) but they don't seem to affect this.

**Comment by davidgilbertson** [comment]
Excellent. IMHO it would be good to have that in the docs. Maybe it's not that common though.

**Comment by Rugal** [comment]
Can we disable the wrapping of `<p>`?

**Comment by Rugal** [comment]
Just notice we can disable wrapping with <p> by overriding

```
Renderer.prototype.paragraph = function(text) {
  return text + '\n';
};
```

**Comment by radiovisual** [comment]
> Just notice we can disable wrapping with <p> by overriding `Renderer.prototype.paragraph`

Won't that override every single paragraph tag? Or will it just override the initial paragraph wrap?

**Comment by Rugal** [comment]
@radiovisual That will override every single paragraph tag.

**Comment by joshbruce** [comment]
Closing as available via advanced usage. If documentation desired, please submit a PR.

**Comment by cameron-raymond** [comment]
Here's what worked for me. It assumes that you know what tags you don't want to wrap.

`// Every new line in markdown is considered a new paragraph, this prevents img tags from being // wrapped in  <p> tags which is helpful for resizing the first img, centering captions, etc.
marked.Renderer.prototype.paragraph = (text) => {
  if (text.startsWith("<img")) {
    return text + "\n";
  }
  return "<p>" + text + "</p>";
};
`

**Comment by illepic** [comment]
@cameron-raymond your solution was perfect for my use-case of trying to pass markedjs output to tiptap (and tiptap exploding on img tags within p tags).

**Comment by drewclifton** [comment]
What does "🎉 This issue has been resolved in version 1.1.2 🎉" mean? Does it mean there is documentation for how to handle this now? I seem to be experiencing this as the default behaviour in 2024 (using marked v14.1.3).

Thanks!

**Comment by UziTech** [comment]
See https://marked.js.org/using_advanced#inline

**Comment by drewclifton** [comment]
Thanks @UziTech.

I was optimistic about this, however I have found that there is one key issue with this approach:

This also seems to remove all line breaks from _inside the content as well_ ...

I just want the superfluous outer wrapping `p`s gone as they are messing with my UI.

Any other ideas/suggestions anyone?

**Comment by UziTech** [comment]
Ass other comments have suggested you can change the `paragraph` renderer to not add the `<p>` tags.

```js
const renderer = {
  paragraph({ tokens }) {
    return this.parser.parseInline(tokens);
  }
};

marked.use({ renderer });
```
