### ISSUE TITLE
async renderer support

### ISSUE THREAD

**Issue by taylorchu** [markedjs/marked#458]
It is helpful if one needs to use http to retrieve rich data for rendering.

**Comment by TiboQc** [comment]
+1 for this, I need some enhanced custom markdown that will fetch data from the server to get the info to render the final HTML.

e.g.
`The head of IT, [function:HEAD_OF_IT], will be in charge of...`
Should render:
`The head of IT, John Smith, will be in charge of...`
This needs to get the person from the server. That will always be accurate when displaying the page, even when the person that's assigned as Head of IT changes.

**Comment by pod4g** [comment]
+1 for this
I define a special markdown syntax for our editor

the syntas like this:
```
\`\`\`sku
 1120
\`\`\`
```

**Comment by janosh** [comment]
Async renderers would be very helpful! My use case is turning a markdown image responsive by fetching multiple `srcset`s as well as the image's width and height (to avoid layout shifts) from a CMS based on its `href`. Something like this:

```js
import marked from 'marked'
import yaml from 'js-yaml'

const renderer = {
  async image(href, title, text) {
    if (href?.includes(`mycms.tld`) && !href.endsWith(`.svg`)) {
      const id = href.split(`myCmsId`)[1]
      const query = `{
        asset(id: "${id}") {
          width
          height
        }
      }`
      const { asset } = await fetchFromCms(query)
      const { width, height } = asset
      title = title ? `title="${title}"` : ``
      return `
      <picture>
        <source media="(min-width: 1000px)" type="image/webp" srcset="${href}?w=1000"&fm=webp"" />
        <source media="(min-width: 800px)" type="image/webp" srcset="${href}?w=800"&fm=webp"" />
        <source media="(min-width: 600px)" type="image/webp" srcset="${href}?w=600"&fm=webp"" />
        <source media="(min-width: 400px)" type="image/webp" srcset="${href}?w=400"&fm=webp"" />
        <img src="${href}?w=1000" alt="${text}" ${title} loading="lazy" width="${width}" height="${height}" style="width: 100%; height: auto;" />
      </picture>`
    }

    return false // delegate to default marked image renderer
  },
}

marked.use({ renderer })
```

**Comment by UziTech** [comment]
This is on the v2 project board but does not have a PR yet. If someone would like to start a PR this would go faster.

**Comment by janosh** [comment]
@UziTech I'm happy to try it if pointed in the right direction.

**Comment by UziTech** [comment]
basically we just need to change [/src/Parser.js](https://github.com/markedjs/marked/blob/master/src/Parser.js) to call the renderers asynchronously without slowing down the parser.

**Comment by janosh** [comment]
So it's just adding `await` to every call to `this.renderer.[whatever]` in `Parser.js` and then `await` `Parser.parse` wherever that gets called?

**Comment by UziTech** [comment]
Just awaiting every render call will probably slow down the parser quite a bit.

**Comment by janosh** [comment]
I see. But what’s the alternative?

**Comment by UziTech** [comment]
Not sure. That is what needs to be figured out to get async renderers working.

**Comment by janosh** [comment]
Would it make sense to have both a sync and an async renderer (the latter being undefined by default) and only using the async one if the user defined it?

```js
import marked from 'marked'

const renderer = {
  async imageAsync(href, title, text) {
    // ...
  },
}

marked.use({ renderer })
```

Similar to how `fs` has `readFile` and `readFileSync`.

**Comment by UziTech** [comment]
That could work. Or maybe have an `async` option and use a different parser that awaits the renderer calls. That way the default renderer doesn't change speed, and have a note in the docs about async being slightly slower.

I don't think it should be a problem with async being slightly slower since any async action (api call, file system call, etc.) will be a much bigger bottleneck for speed than awaiting a synchronous function. I just don't want to slow down the users that don't need it to be async.

**Comment by janosh** [comment]
You mean like this `marked(mdStr, { async: true })`? And then something like

```js
  try {
    // ...
    if (opt.async) return await Parser.parse(tokens, opt);
    else return Parser.parse(tokens, opt);
  } catch (e) { ... }
```

**Comment by UziTech** [comment]
Ya it might work better to create a separate parser so we don't have the conditional logic on each renderer call.

```js
 try {
    // ...
    if (opt.async) return await AsyncParser.parse(tokens, opt);
    else return Parser.parse(tokens, opt);
  } catch (e) { ... }
```

**Comment by OzzyCzech** [comment]
> Is there any case where marked actually needs to perform an async operation during compilation?

It will be very useful have async support in renderer (speaking as an author of [static site generator](https://sphido.org/) that uses Marked)

There is a plenty of examples:

* use [oembed](https://oembed.com/) for generating smart links (with titles, description)
* check existence of URL before made active link (`<del><a href="not existing url">someething</a></del>`)
* resize images - that's a little bit crazy :) 
* syntax highlighters - most of them are async
* API calls during rendering content - eg. IMDB get star rating for movies

**Comment by acarl005** [comment]
I'm also building a static site that uses Marked. My use case is that I'd like to execute code in the code blocks and render the output in my HTML page. I need async capabilities in my renderer to call a child process or remote host.

**Comment by trustedtomato** [comment]
I have made an async renderer extension for markdownit in my project called
decharge, I'll extract it when I have some free time:)

Probably a similar method can be used for marked.

Until I extract it, feel free to take some ideas, it's located at
examples/project-website/src/utils/async-render-markdown.ts

**Comment by UziTech** [comment]
I started implementing a solution for this in #2405

**Comment by jimmywarting** [comment]
I would like to lazy import syntax highlighting library only when needed.
any possibility to turn the callback into promises instead?

looking at this example:
```js
marked.setOptions({
  highlight: function(code, lang, callback) {
    require('pygmentize-bundled') ({ lang: lang, format: 'html' }, code, function (err, result) {
      callback(err, result.toString());
    });
  }
});

marked.parse(markdownString, (err, html) => {
  console.log(html);
});
```
would be nice to do:
```js
marked.setOptions({
  async highlight (code, lang) {
    const xyz = await import('...')
    return xyz(code, lang)
  }
})

await marked.parse(markdownString)
```

**Comment by jimmywarting** [comment]
> Just awaiting every render call will probably slow down the parser quite a bit.

it's also possible to look at the function if it's a async function:
```js
async function f() {}
f.constructor.name === 'AsyncFunction' // true
```
so based on that you could do some if/else logic... but i guess this would be bad for sync functions that return promises or have some thenable function

found this if somebody is intrested:
https://stackoverflow.com/questions/55262996/does-awaiting-a-non-promise-have-any-detectable-effect

**Comment by jimmywarting** [comment]
as part of making it async, i would like to wish for something like a async stream to output data to the user as data flows in, i would like to do this within service worker:
```js
self.onfetch = evt => {  
  evt.respondWith(async () => {
    const res = await fetch('markdown.md')
    const asyncIterable1 = res.body.pipeThrough(new TextDecoderStream())
    const asyncIterable2 = marked.parse(asyncIterable1, {
      async highlight(code, lang) {
        return await xyz()
      }
    })
    const rs = ReadableStream.from(asyncIterable2)
    return new Response(rs, { headers: { 'content-type': 'text/html' } })
  })
}
```
I ask that you do support asyncIterable (Symbol.asyncIterator) as an input parameter so it can work interchangeable between both whatwg and node streams so that it isn't tied to any core features.
(all doe node v17.5 will have whatwg stream exposed globally so that would be suggested over node streams if you where to support it)

**Comment by jimmywarting** [comment]
instead of having a async/sync method you could instead do things with `symbol.asyncIterator` and `symbol.iterator`
```js
// Uses symbol.asyncIterator and promises
for await (const chunk of marked.parse(readable)) { ... }
// Uses symbol.iterator (chunk may return promise if a plugin only supports asyncIterator)
for (const chunk of marked.parse(readable)) { ... }
```
It could maybe also be possible to have something like:
```js
const iterable = marked.parse(something, {
  highlight * (code, lang) {
    yield someSyncTransformation(code, lang)
  }
})
// or 
const iterable = marked.parse(something, {
  async highlight * (code, lang) {
    const transformer = await import(lib)
    yield transformer(code, lang)
  }
})

**Comment by jimmywarting** [comment]
hmm, haven't touched the underlying codebase or investigated the underlying code of this package or anything - just coming up with proposals 😄 
But I can give it a test. see if it is any well written / document
likely going to change the function of markdown to return a value instead of using a callback... but will see what i can cook up. maybe it's even still possible to keep the callback approche
