### ISSUE TITLE
there's no `loose_item_end` token

### ISSUE THREAD

**Issue by slang800** [markedjs/marked#469]
Just wanted to mention that I found this pretty odd since we have a `loose_item_start`. Any particular reason for this?

**Comment by UziTech** [comment]
@slang800 Is there any reason there needs to be a `loose_item_end`? Can you give an example of where it would be helpful to know at the end of a list item whether it was loose or not?

**Comment by slang800** [comment]
It's been awhile since I worked with marked, so I don't remember exactly what I was doing, but I'm pretty sure I had a function that looked for every token that was a `*_start` or `*_end` and matched them together to form a simple syntax tree.

The fact that `loose_item_start` isn't terminated by a `loose_item_end` adds extra complexity to those types of functions. Rather than just looking for `tokenType + "_start"` or `tokenType + "_end"`, I need to add a special case that handles `loose_item_*` tokens differently.
