### ISSUE TITLE
the ast stores links as a property of an array

### ISSUE THREAD

**Issue by slang800** [markedjs/marked#472]
Arrays don't _really_ support non-numeric keys, so using `ast.links` means I loose the list of links whenever I perform an operation on the array like `map` or `concat`. If you want to read more, Andrew Dupont has a short [essay](http://andrewdupont.net/2006/05/18/javascript-associative-arrays-considered-harmful/) on why this is harmful.

So, we should change the format of the AST to something like this:

``` js
{
  'tokens': [<the array of tokens>]
  'links': {<the object that stores all the links>}
}
```

**Comment by UziTech** [comment]
fixed by #1299
