### ISSUE TITLE
Multiple quotes merged into one

### ISSUE THREAD

**Issue by alexeypetrushin** [markedjs/marked#487]
The two quotes from code below will be rendered into single quote.

```
> If there’s a common theme, it is about raising the level of abstraction—to 
create building blocks for programmers who just happen to have lots of data to store.

> This, in a nutshell, is what Hadoop provides: a reliable shared storage and analysis 
system.
```

**Comment by UziTech** [comment]
this seems to be fixed: [marked demo](https://marked.js.org/demo/?outputType=html&text=%3E%20If%20there%E2%80%99s%20a%20common%20theme%2C%20it%20is%20about%20raising%20the%20level%20of%20abstraction%E2%80%94to%20%0Acreate%20building%20blocks%20for%20programmers%20who%20just%20happen%20to%20have%20lots%20of%20data%20to%20store.%0A%0A%3E%20This%2C%20in%20a%20nutshell%2C%20is%20what%20Hadoop%20provides%3A%20a%20reliable%20shared%20storage%20and%20analysis%20%0Asystem.)

If it is not then we can open this issue again.
