### ISSUE TITLE
Add option to render Markdown inside <div> blocks

### ISSUE THREAD

**Issue by asadovsky** [markedjs/marked#488]
Hi,

First: thanks for writing this fantastic library!

My issue: I'm using Markdown in documentation for a project, and would like to use &lt;div> tags inside of the Markdown to specify that certain sections should be hidden (or otherwise stylized).

For example:

```
# Title

This is some text.

<div class="toggle-hide">
## Hidden section

A hidden paragraph.
</div>

This text is visible.
```

Unfortunately, the Markdown content inside the &lt;div> does not get rendered -- it's copied verbatim into the output.

Is there any way to configure marked.js to render Markdown inside of &lt;div> tags? If not: can you point me in the right direction for how to add such an option? Or: can you recommend some alternate strategy for hiding (or toggling visibility of) sections of content? 

Thanks!

**Comment by ivan-kleshnin** [comment]
Markdown parsing inside HTML is a must. But this will require to disable "indented block = code block" "feature" at all, as nested HTML tags are nearly always indented... As GFM style is so much better I think it would be only for good.

**Comment by derberg** [comment]
I love Markdown, but if things like support for markdown in between divs will not be available, markdown will start loosing his position in favour of https://github.com/asciidoctor/asciidoctor.js

**Comment by tombola** [comment]
I know this is a bit of a specific case, but I have been trying to get round this for my (jekyll) github pages.

My requirement was to wrap a markdown-ed paragraph in a div so I could style it as a panel. In the end I just created an empty, classed div in front of the paragraph and used a [sibling selector](http://css-tricks.com/child-and-sibling-selectors/) ``.myclass + p`` to reference (and style) the following paragraph.

I realise this is an unholy and specific workaround, but I thought I would share.

**Comment by sh1989** [comment]
This feels like quite a common use case - it would be nice if there was some built in liquid template that could do this for you, although we'll need to ensure that markdown is subsequently parsed and outputted correctly within that liquid block.

**Comment by franzheidl** [comment]
Some markdown parsers/implementations allow this:

```
<div markdown="1">
    #Heading 1
</div>
```

This would be rendered as

```
<div>
    <h1>Heading 1</h1>
</div>
````

It would be great if marked would support this, too.

**Comment by schlichtanders** [comment]
just stumbled upon this div case 

Interestingly, it seems as the following indeed do render correctly:
- bold and italics using ``**bold**`` and ``*italics`` 
- url syntax ``[link text](https://url.com)``
- maybe more

However others don't do so in my case:
- headings ``#``, ``###``
- lists
    ````
    - ul1
    - ul2

    1. ol1
    1. ol2
    ````
- probably more

**Comment by maxrahder** [comment]
+1
Apparently, within a <div> or other block-level element, inline elements are still processed, but block-level md is ignored. (Here's a fiddle some nice person wrote, to let you experiment: http://www.javascriptoo.com/marked)

I have this situation too. I have some <div>s that I process in a special way -- mostly to add css dynamically. But I'd like the content to be processed like any other md. Proving some kind of flag on the div would work, or I don't mind writing something to help out the lexer if I knew what hooks are in the library.

**Comment by shalkam** [comment]
I don't know if I am doing it the right way, but here is how I got it work:

```javascript
const marked = require('marked');
const renderer = new marked.Renderer();
const cheerio = require('cheerio');

renderer.html = function(html) {
  // marked has to be the first attribute
  if (html.startsWith('<div marked')) {
    const $ = cheerio.load(html);
    const markedDivs = $('div[marked]');
    // loop through all div tags with marked attribute
    for (var i = markedDivs.length; i > 0; i--) {
      marked(markedDivs.eq(i).html(), function(err, html) {
        markedDivs.eq(i).html(html);
      });
    }
    html = $('body').html();
  }
  return html;
};
renderer.paragraph = function(text) {
  let isHtml = /<[a-z][\s\S]*>/i.test(text);
  if (isHtml) return text + '\n';
  else return '<p>' + text + '</p>\n';
};

module.exports = renderer;
```

**Comment by aoloe** [comment]
i don't know if i understand this request correctly, but after having checked parsedown, i've found that this is already supported:

https://github.com/erusev/parsedown-extra/issues/14

i've activated markdown extra in grav and the markdown in a `<div markdown="1">this is a __test__</div> was then correctly parsed.

**Comment by joshbruce** [comment]
#985

**Comment by sbliven** [comment]
@aoloe Your test uses inline style, which was already established to work. Have you tried  a heading or list with parsedown-extra?

@joshbruce I'm confused about the issue consolidation. This remains a limitation in marked, right? Should further discussion happen here or in #985?

**Comment by joshbruce** [comment]
@sbliven: Fair question. See the conversation over here as well. https://github.com/chjj/marked/issues/984

Continue discussion here. I'll reopen as it is, apparently a continuing issue. Still working out the kinks of the community coming back on line. Mind the gap. ;)

**Comment by r0the** [comment]
+1

I'm missing this feature. I think that the CommonMark [HTML Blocks](http://spec.commonmark.org/0.28/#html-blocks) specification woudl be quite easy to implement. A raw HTML block basically starts with an HTML tag and ends with an empty line.

The following Markdown would be parsed as follows:
- raw HTML block `<div>*raw HTML*</div>`
- raw HTML block `<div>`
- Markdown paragraph `<p><b>Markdown</b></p>`
- raw HTML block `</div>`

```
<div>
*raw HTML*
</div>

<div>

*Markdown*

</div>

**Comment by sbliven** [comment]
@r0the I find the whitespace handling in HTML blocks to be surprising. It prevents using newlines to organize the HTML content in longer blocks. You also can't indent naturally:

```
<table>
    <tr><td>

**markdown**

    </td></tr>
</table>
```

Not only must the markdown be left-aligned, but the closing tags get treated as a codeblock due to the indentation.

That said, it's probably easier to implement than the markdown=1 attribute.

**Comment by bennlich** [comment]
FWIW the implemented solution is to insert new lines around the content that you want to get parsed, as in this comment: https://github.com/markedjs/marked/issues/488#issuecomment-359562618

**Comment by Bstar826** [comment]
I have same question
https://github.com/markedjs/marked/issues/488#issue-42954973

I have already read the mentioned content above
but I can't solve it.
please provide the correct answer.
thanks

**Comment by UziTech** [comment]
Put a blank line around the html elements

```md
<div class="hide">

# h1

</div>
```

[demo](https://marked.js.org/demo/?text=%3Cdiv%20class%3D%22hide%22%3E%0A%0A%23%20h1%0A%0A%3C%2Fdiv%3E&options=%7B%0A%20%22async%22%3A%20false%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22extensions%22%3A%20null%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22hooks%22%3A%20null%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%0A%7D&version=11.1.0)
