### ISSUE TITLE
underscore with brace not rendered correctly

### ISSUE THREAD

**Issue by fyears** [markedjs/marked#494]
While `gfm` is enabled:

``` js
k = marked('a_b_c_{s}');
// my expected k : '<p>a_b_c_{s}</p>'
// real k: '<p>a<em>b_c</em>{s}</p>'
```

Is it a bug? Or I missed something in markdown syntax?

**Comment by joshbruce** [comment]
Closing as most likely covered by spec compliance. See #1106 and #1216.
