### ISSUE TITLE
Custom InlineLexer Rule

### ISSUE THREAD

**Issue by elennaro** [markedjs/marked#504]
With Marked I can easily ovverride/add/change lexer rules during implementation, and its great!
For example I can force to use space between hash sign an text to make a header like this:

``` javascript
        var lexer = new marked.Lexer(options);
        console.log(lexer);
        lexer.rules.heading = /^\s*(#{1,6})\s+([^\n]+?) *#* *(?:\n+|$)/

        console.log(marked.parser(lexer.lex('#hashtag?'), options));
        //<p>#hashtag?</p>
        console.log(marked.parser(lexer.lex('# heading?'), options));
        //<h1 id="undefinedheading-">heading?</h1>
```

Cool!
But is there a way, to easily do same for inline lexer?
Like i need to make people be able to add an images with next sequence: `%[My Image](http://example.com/img.jpg)`?
So i modified:

``` javascript
var inlineLexer = marked.InlineLexer;
        inlineLexer.rules.link = /^[!%]{0,1}?\[((?:\[[^\]]*\]|[^\[\]]|\](?=[^\[]*\]))*)\]\(\s*<?([\s\S]*?)>?(?:\s+['"]([\s\S]*?)['"])?\s*\)/;
```

What should I do next?
How to bind a custom inlineLexer to a marked instance?
Please show me an example of how to do this! How can I modify/add custom inline lexer rules?

**Comment by dotcore** [comment]
Actually there is a way, if you overwrite the prototype. (In this example I surpress parsing of em tags). 

```javascript
marked.prototype.constructor.Parser.prototype.parse = function (src) {
    this.inline = new marked.InlineLexer(src.links, this.options, this.renderer);
    this.inline.rules.em = { exec: $.noop }
    this.tokens = src.reverse();

    var out = '';
    while (this.next()) {
        out += this.tok();
    }

    return out;
};
```

**Comment by Rugal** [comment]
@dotcore 's method solved my problem. 
For people coming later, after overriding the constructor, you can also add custom renderer.

**Comment by joshbruce** [comment]
Closing as not part of the current focus. See #1106 and #1216
