### ISSUE TITLE
Hangul(한글) title is no supported.

### ISSUE THREAD

**Issue by vomvoru** [markedjs/marked#508]
# 제목입니다.  >>>>>  <h1 id ="제목입니다.">제목입니다.</h1>      ... ok !

but.. real action ..

# 제목입니다.  >>>>>  <h1 id ="-----.">제목입니다.</h1>      ... fail

**Comment by joshbruce** [comment]
Not sure I'm following. Closing as stale. Please resubmit if this is still an issue and use the updated issue template.
