### ISSUE TITLE
Question about the parser

### ISSUE THREAD

**Issue by eGavr** [markedjs/marked#523]
Hi!

I've got the tokens by this command:

``` js
var tokens = marked.lexer(text, options);
console.log(tokens);
```

Have I the opportunity to get markdown from tokens?

**Comment by joshbruce** [comment]
I don't believe it's possible to pull the original markdown. Believe the lexer applies some regex rules during the tokenization process. Going to close the issue as stale as well but, please feel free to continue discussing.

Tagging @UziTech and @styfle.
