### ISSUE TITLE
Another bug in parsing of headers

### ISSUE THREAD

**Issue by eGavr** [markedjs/marked#526]
I have such md-file

``` md
# ##
```

I've received the tokens of the given markdown by method `marked.lexer`:

``` js
[ { type: 'heading', depth: 1, text: '#' }, links: {} ]
```

But the given markdown does not have any headers.

**Comment by joshbruce** [comment]
See #981

**Comment by joshbruce** [comment]
See Commonmark observation from @Feder1co5oave in #981

**Comment by calculuschild** [comment]
Commonmark Example [49](https://spec.commonmark.org/0.29/#example-49) seems to indicate that emitting an empty header is the correct behavior, and [Example 42](https://spec.commonmark.org/0.29/#example-42) tells us that the number of opening and closing `#` do not need to match.

We pass both of these tests, and correctly emit an empty header now. @UziTech can we close this?
