### ISSUE TITLE
Support Strikethrough?

### ISSUE THREAD

**Issue by KyleAMathews** [markedjs/marked#53]
Any chance you could add support for strikethrough? I know it's not in the official Markdown spec but it's something I need for my application.

**Comment by p00j4** [comment]
Apologies if i'm reporting this at wrong place, not sure if github.io is also using marked.js but this is the most close I have found for my problem [here](https://p00j4.github.io/#contact) The strikethrough doesn't work with the tildes
![image](https://user-images.githubusercontent.com/6470509/92297888-727ecc00-ef61-11ea-8c70-390a5ae8136d.png)

Ideas to fix this?

**Comment by UziTech** [comment]
@p00j4 It looks like you are just using HTML not markdown. If you change `~~me~~` to `<del>me</del>` it should work.

**Comment by sanjeevbeekeeper** [comment]
Does this work on block code?.

# Block
```
~~Iam striked~~
```

**Comment by UziTech** [comment]
@sanjeevbeekeeper yes [demo](https://marked.js.org/demo/?text=~~Iam%20striked~~&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master)

**Comment by sanjeevbeekeeper** [comment]
Help me! where did i go wrong.
It is not working with block of code. - [Demo](https://marked.js.org/demo/?text=%60%60%60%0AThis%20is%20a%20strikethrough%20inside%20a%20block%0A~~Iam%20striked~~%0A%60%60%60&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master)

**Comment by calculuschild** [comment]
No, Markdown code blocks do not process internal formatting.

From the Commonmark specs: 

> The content of a code fence is treated as literal text, not parsed

**Comment by UziTech** [comment]
Sorry I thought you meant does it work on block elements.

**Comment by Monisha-proz** [comment]
sdssda

- [ ] dfsdsfdsf

**Comment by jyj1202** [comment]
~i see~
