### ISSUE TITLE
Marked adding white space after second line in code blocks

### ISSUE THREAD

**Issue by ughitsaaron** [markedjs/marked#533]
My code blocks are being parsed with six preceding spaces before every line following the first in a code block.

So code written in Markdown like this

```
var foo;

foo = function(str) {
  console.log(str);
};

foo("Hello, world!");
```

Becomes parsed like this:

```
var a;

        a = function(str) {
          console.log(str)
        }

        a("Hello, world!");
```

I'm using highlight.js to handle highlighting, but the problem persists when I remove syntax highlighting.  The issue also persists no matter how I mark the codeblock in Markdown, e.g., indents, fenced, etc.

I attached a screenshot of the finished product with the leading whitespace.
![screenshot 2014-12-29 18 08 55](https://cloud.githubusercontent.com/assets/5301535/5574157/1811801e-8f86-11e4-839b-05fbec3a6a57.png)

**Comment by joshlasdin** [comment]
@aptkf I'm running into a very similar issue. Did you figure out what the problem was (despite it not being with marked)?

**Comment by aptkf** [comment]
Hey @joshlasdin, I did figure it out. I was using handlebars for my templates and my expressions were indented which effected the indentation of the preformatted code blocks. Everything was fine once I removed the indentations before my handlebars expressions. Good luck!
