### ISSUE TITLE
[text]:text outputs empty string

### ISSUE THREAD

**Issue by adam-lynch** [markedjs/marked#539]
In the original markdown [spec](http://daringfireball.net/projects/markdown/syntax), `[id]: http://example.com/` is defined as another way to write a link.

The following entries will output an empty string:
- `[abc]: abc`
- `[abc]:abc`
- `[abc]:abc[abc]:abc`
- `[abc]:abc[abc]:abc[abc]:abc`

`[abc]:abc anotherword` doesn't return the empty string, it outputs exactly what was entered; `[abc]:abc anotherword`.

For me, I don't care for this pattern anyway, I'd prefer if it just wasn't supported at all. But either way it shouldn't return nothing.

As a workaround, if marked ever returns the empty string, I'm just going to display the input.

**Comment by danwhite85** [comment]
I believe that syntax is for reference style links. Sort of like variables in programming. You can create the reference link and the use it elsewhere in the document without having to write the full thing out.

```
[foo]:http://example.com

Visit me at [foo]

Renders: 
Visit me at <a href="http://example.com">foo</a>
```

**Comment by joshbruce** [comment]
Closing as stale and I'm not sure how much longer we will be supporting the original Perl. See also #1106
