### ISSUE TITLE
underscores are interpreted incorrectly in GFM

### ISSUE THREAD

**Issue by santhosh-tekuri** [markedjs/marked#544]
on rendering: 
`$A_i, A_{i+1}$`
it produces: 
`<p>$A<em>i, A</em>{i+1}$</p>`
expected: 
`<p>$A_i, A_{i+1}$</p>`

i tried the same in stackedit. it works as expected

**Comment by mkopala** [comment]
This is the same as #343.

**Comment by Feder1co5oave** [comment]
We don't support the `$..$` syntax, so marked doesn't know anything about it, and interprets underscores as emphasis delimiters. In this _particular_ case, the first `_` should not open an emphasis, though.
