### ISSUE TITLE
Recipe how to setup marked to ignore certain sequences

### ISSUE THREAD

**Issue by Mitranim** [markedjs/marked#554]
My use case is such. I have source templates for a static site, which is a mix of `.html` and `.md` files. I use `marked` to preprocess the `.md` files, then pipe everything to the site generator [(1)](https://github.com/Mitranim/statil). The problem is that with default settings, you can't use template directives like `<%= %>`, since they will be escaped by `marked` before reaching the templating engine. The result is that some files need to be duplicated, with markdown parts moved into partials, etc.

There must be a way to set marked to ignore directive delimiters like `<%= %>`, `{{ }}` or whatever a particilar engine uses, but after poking around the source, I haven't found it. It would be nice if we could figure this out and include into the documentation.

**Comment by operatino** [comment]
Having the same issue, can't find a solution.

**Comment by craigshoemaker** [comment]
Interested in this one as well...

**Comment by Mitranim** [comment]
In retrospect, what was I thinking? Run templating before marked = EZ. 🤦‍♀️

Thanks for the awesome library. Best Markdown processor that I'm aware of. Please keep it short, fast, and hackable, that's the killer feature for me.
