### ISSUE TITLE
Option to render only parts of the Markdown syntax

### ISSUE THREAD

**Issue by bennyn** [markedjs/marked#571]
Hello, is there an option to just render **some** Markdown synatx? In my project I just want to render **strong**, **em** and **code** but I don't want to have support for **titles**, **block quotes**, etc.

Can I configure "marked" somehow so that it only checks for specific types (like the ones mentioned)?

**Comment by gbradley** [comment]
I'd also love this feature. At the moment I'm having to override the rendeder for each element I don't want and manually revert back to the original input.

**Comment by DanielZwijnenburg** [comment]
This would be a great addition!
