### ISSUE TITLE
README: Clarify breaks, gfm#newlines link broken

### ISSUE THREAD

**Issue by buob** [markedjs/marked#578]
I'm not really sure what the `breaks` option does, as the link in the readme about [GFM line breaks](https://help.github.com/articles/github-flavored-markdown#newlines) is broken.

**Comment by AdrianoFerrari** [comment]
Here's the updated link:
https://help.github.com/articles/writing-on-github/#newlines

**Comment by amccloud** [comment]
@buob @chjj doesn't appear to do anything currently.

**Comment by joshbruce** [comment]
Docs have been updated. Please submit a new issue if they updated docs do not match your needs.
