### ISSUE TITLE
GFM code with syntax highlighting

### ISSUE THREAD

**Issue by panzi** [markedjs/marked#58]
GitHub flavored markdown supports syntax highlighted code like this:

``` javascript
/* comment */
var s = "string", i = 123;
function foo () {
   for (var x in xs) {
      console.log(x, xs[x]);
   }
}
```

This is not supported by marked. It should either state this or (better) implement it.

**Comment by ricardoquesada** [comment]
+1

**Comment by Fogetti** [comment]
+1

**Comment by egordorichev** [comment]
+1

**Comment by shaaraddalvi** [comment]
+1

**Comment by ELLIOTTCABLE** [comment]
I clearly started this trend, so I'll contribute to stopping it:

GitHub now supports emoji-reactions to Issue comments, which has become the de-facto standard for “voting” on Issues. If you want to `+1` this, I suggest you click the :+1:-react on the OP; as this avoids sending an e-mail to everybody who's ever commented on this Issue (as this reply itself inevitably will! 😰)
