### ISSUE TITLE
URLs with parentheses are not converting properly.

### ISSUE THREAD

**Issue by Pomax** [markedjs/marked#619]
Using the following markup:

```
[青 ("ao")](https://en.wikipedia.org/wiki/Ao_(color))
```

leads to a link that actually looks like `青 ("ao"))` with the link's own parenthesis getting cut off (marked seems to be treating the first `)` it sees as link terminator, instead of taking nesting into account)

**Comment by rgbkrk** [comment]
Definitely an issue, that I see happening across the web from users of marked.

**Comment by bendecoste** [comment]
Is there an ETA for a fix on this ?

**Comment by Pomax** [comment]
I have no expectation that @chjj will ever fix this, but it's most likely the bug stems from a bad assumption in https://github.com/chjj/marked/blob/master/lib/marked.js#L455

I might try to fix it myself, but I kind of work on more projects than I can count already, so it might happen today, or never, or anywhere in between those two moments...

**Comment by Pomax** [comment]
filed https://github.com/chjj/marked/pull/630 as PR to at least make it explicit that this is a pure RegEx parser, with all the limitations that brings with it.

**Comment by joshbruce** [comment]
#984
