### ISSUE TITLE
Apply marked in javascript

### ISSUE THREAD

**Issue by BannedForLife** [markedjs/marked#632]
I have a value attached to an ng-model. I would like this value to be run through marked. Something like this.

JS:
<code>var text = "<script>alert('hello scriptio')</script>"; 
scope.text = marked(text)</code>

HTML:
`<textarea ng-model="text"></textarea>`

Is this possible?

**Comment by robrothedev** [comment]
I'm not sure how the marked function works in the controller, but I'm binding content to my textarea and a div with a marked attribute without any issues:

```javascript
function MarkdownEditorCtrl() {
  var vm = this;
  vm.markdown = '###Hello';
}
```
```html
<div ng-controller="MarkdownEditorCtrl as ctrl">

  <!-- markdown editor -->
  <textarea ng-model="ctrl.markdown"></textarea>

  <!-- output of markdown -->
  <div marked="ctrl.markdown"></div>

</div>
```

**Comment by joshbruce** [comment]
Closing as beyond scope at present. See #1106
