### ISSUE TITLE
Non-breakable spaces don't work in marked

### ISSUE THREAD

**Issue by chillum** [markedjs/marked#640]
If I insert a non-breakable space character, it gets to output as a regular space.

This is terribly wrong, we don't want to convert non-breakable space to a regular one.

As a workaround one could use `&nbsp;`, but that looks ugly in Markdown files.

**Comment by romanpitak** [comment]
https://github.com/romanpitak/pfm

Just a suggestion...

**Comment by UziTech** [comment]
closing in favor of #897
