### ISSUE TITLE
Emphasis syntax regression (?)

### ISSUE THREAD

**Issue by cheesypoof** [markedjs/marked#641]
In v0.3.3 `_**ABC\_DEF**_` generates `<em><strong>ABC_DEF</strong></em>`
In v0.3.4 `_**ABC\_DEF**_` generates `_<strong>ABC_DEF</strong>_`

Regression?

**Comment by ariabuckles** [comment]
I believe this change is from the [em tag's security fix in 0.3.4](https://github.com/chjj/marked/issues/497). I think it's possible to fix this specific case (escaped underscores) without reintroducing that error.

I've fixed this in my marked-derived parser at https://github.com/Khan/simple-markdown/commit/9504ca5f1582f9add845f22b1830e68abd0859da and sent pull request #715 to marked

**Comment by joshbruce** [comment]
Closing as most likely covered by spec compliance. See also #1106 and #1216.
