### ISSUE TITLE
Support for variable replacement?

### ISSUE THREAD

**Issue by danishin** [markedjs/marked#646]
Is there a way to insert dynamic variables into the parser and replace placeholders in `.md`? 

If not, is there a plan for the support in the future?

Thanks.

Great library btw :tada: :tada:

**Comment by joshbruce** [comment]
Closing as stale.

Flagged as a proposal for future consideration once we get beyond fixing known defects. See #1106

**Comment by UziTech** [comment]
@umdstu If you create a new issue with more explanation we would be interested in this. This could most likely be implemented by using an [custom extension](https://marked.js.org/using_pro#extensions).

**Comment by umdstu** [comment]
Roger that, thanks!

**Comment by calculuschild** [comment]
If you plan to make a custom extension, here's some possible inspiration: I think it's been proposed [elsewhere](https://www.brianchildress.co/variables-in-markdown/) on the interwebs to make use of the existing RefLink syntax for simple string replacement. I.e.:

```
My name is [name].

[name] : Bob the builder
```

although you would need some way to identify whether the variable is a URL or just text.  GitHub does a similar thing with [Footnotes](https://github.blog/changelog/2021-09-30-footnotes-now-supported-in-markdown-fields/) although they use a special token `^` to mark the difference between a footnote and a link. `[^1] : Footnote 1`

I have been thinking about a similar extension for my own project, and we've been looking at just using quotes:

```
My name is [name].
This is a [link].

[name] : "Bob the builder"
[link] : www.google.com "Google"
```

I don't know how deep you would want to get into recursive markdown parsing or nested variables or anything:

```
My name is [name].

[name] : "Bob the **builder** of [structure]."
[structure] : "bridges"
```
