### ISSUE TITLE
Strikethrough (~~) does not work with prefix/postfix spaces 

### ISSUE THREAD

**Issue by mnylen** [markedjs/marked#672]
Example says it better:

```
var renderMarkdown = require('marked')
renderMarkdown('~~foo~~')  // <p><del>foo</del></p>
renderMarkdown('~~ foo~~') // <p>~~ foo~~</p>
renderMarkdown('~~foo ~~') // <p>~~foo ~~</p>
```

However, as `renderMarkdown('_ foo_')` produces `<p><em> foo</em></p>`, I'd expect it to work for strikethrough as well.

**Comment by Feder1co5oave** [comment]
I don't think this behaviour would be widely desired... usually you strike through a word or set of words, and leave untouched the space around them.
Notice also that GitHub's markdown doesn't work your way:

~~ text ~~

This behaviour was introduced in https://github.com/chjj/marked/commit/a1080df787d1cfe29ac97e77dc5e263727fa3f20, believing -- I think -- it would adhere better to the standard.

**Comment by Feder1co5oave** [comment]
Does not comply with gfm. @joshbruce

**Comment by joshbruce** [comment]
Agreed - this is more like CriticMarkup - http://criticmarkup.com/spec.php

https://github.com/commonmark/CommonMark/wiki/Markdown-Flavors

We may want to do something with other flavors at some point, just not the focus. Going to leave it open for now just to see what demand there might be for parsing other Markdown flavors.

**Comment by joshbruce** [comment]
Closing as a stale. Also appears Marked does comply with the GFM strikethrough extension.
