### ISSUE TITLE
Marked does not handle links with parentheses

### ISSUE THREAD

**Issue by dend** [markedjs/marked#690]
This is a carbon copy of [this bug](https://github.com/Microsoft/vscode/issues/380#issuecomment-158873568) for _VSCode_.

Here is an example where the preview engine in VSCode mis-renders links with parentheses:
![image3](https://cloud.githubusercontent.com/assets/1389609/11311743/8662bd8e-8f86-11e5-932f-885b5f6d7103.png)

Looks like a Marked issue - any way to fix it?

**Comment by Feder1co5oave** [comment]
There's no way to get around this issue. Just replace closing parentheses with '%29'

**Comment by dend** [comment]
Why not? Out of curiosity, the StackOverflow inline editor, for example, fully supports this scenario.

**Comment by Feder1co5oave** [comment]
Because that would require regexes that count matching opening and closing brackets. And even that is not correct, because URLs are not guaranteed to have balanced brackets in the first place.

**Comment by dend** [comment]
Surely the balanced parentheses case is more common and would cover 99% of the cases here?

**Comment by Feder1co5oave** [comment]
Please consider that this behaviour would also break every existing link with escaped closing parens (and unescaped opening ones).
IMO the best solution is to use references like suggested in the linked issue.

**Comment by hingsir** [comment]
@dend I got the same problem

**Comment by sn3p** [comment]
An option that accepts balanced parentheses matching would be nice.
I don't care if it's false by default.

**Comment by takluyver** [comment]
For reference, the [CommonMark spec](http://spec.commonmark.org/0.27/#links) says that one level of balanced parentheses are allowed in link URLs without being escaped. If there are nested parentheses, or if they're unbalanced, they need to be escaped.

I think this is doable with a regex, but I wouldn't want to be the one writing such a regex.

**Comment by joshbruce** [comment]
#984

**Comment by ax3l** [comment]
Downstream, Jupyter notebooks and Jupyter lab are facing the same issue, e.g. with weird links to DOIs such as:
```
[Esirkepov](https://dx.doi.org/10.1016/S0010-4655(00)00228-9)
```

GitHub renders it correctly:

[Esirkepov](https://dx.doi.org/10.1016/S0010-4655(00)00228-9)

**Comment by joshbruce** [comment]
@ax3l: I’m not sure the example of GitHub doing it properly is actually doing so, I can see the number from the URL after the link text.

Having said that, if it were rendering it probably, I would be curious to know if it’s the GitHub markdown processor doing it, or a post-process of some kind.

We see the issue with Wikipedia URLs as well. Alternatively, one could also hardcode the HTML link, if the output destination is known.

**Comment by ax3l** [comment]
> I’m not sure the example of GitHub doing it properly is actually doing so, I can see the number from the URL after the link text.

@joshbruce The GitHub you see is rendered improperly? This is what I see:

![github_md](https://user-images.githubusercontent.com/1353258/36534662-7d9fcd10-17c7-11e8-9a51-a001d5662970.png)

I guess it's a tricky regex that balances the brackets.


Interestingly, the downstream Jupyter `.md` syntax highlighting get's it right (see red parts on the left), only the preview (right, markedjs) has the glitch:

![lab_md](https://user-images.githubusercontent.com/1353258/36534807-e62d4a88-17c7-11e8-9eeb-337fbb65f0a2.png)

**Comment by ax3l** [comment]
This seems to be the regex used in pygments, maybe it helps:
https://bitbucket.org/birkenfeld/pygments-main/src/7941677dc77d4f2bf0bbd6140ade85a9454b8b80/pygments/lexers/markup.py?at=default&fileviewer=file-view-default#markup.py-585

**Comment by joshbruce** [comment]
@ax3l: It's what I see now, but wasn't what I was seeing. First time I saw:

```
Esirkepov00228-9)
```

So, we'll see what we can do. We're focusing on hitting the CommonMark and GFM specs right now; so, not sure when this will become a priority, if it does. Just to keep you aware of where we are.
