### ISSUE TITLE
Is "footnote" supported in marked.js?

### ISSUE THREAD

**Issue by alston19** [markedjs/marked#714]
It doesn't work when I input :

hello[^hello]
<br/>
[^hello]: hi

**Comment by ariabuckles** [comment]
No, footnotes are a non-standard markdown extension and aren't supported, sorry!

**Comment by AlstonYang** [comment]
Okay, thanks for answering. May be I can implement it myself.

**Comment by SHxKM** [comment]
@alston19 I know it's been long but I'm wondering whether you found a solution to this?

**Comment by alston19** [comment]
@SHxKM sorry but no 😂

**Comment by UziTech** [comment]
@SHxKM check out https://github.com/markedjs/marked/issues/1562#issuecomment-551269829 to find some code that should work to add footnotes.

**Comment by splch** [comment]
Github flavored markdown now supports footnotes (https://github.blog/changelog/2021-09-30-footnotes-now-supported-in-markdown-fields/). Does that mean it's now time to implement this feature?

**Comment by UziTech** [comment]
@splch If you want to implement this it would probably be accepted now. It would be better if GitHub would add it to the [GFM spec](https://github.github.com/gfm/) so we could know the edge cases but it looks like they haven't updated the spec in a while. ☹

**Comment by styfle** [comment]
I just came across this new feature on GitHub too.

I'll reopen the issue so others coming here can find it 👍 

Hopefully GitHub updates the GFM spec soon 🤞

**Comment by UziTech** [comment]
Ya I seems like there are a lot of errors with it since they don't specify what happens in edge cases.

**Comment by dminkovsky** [comment]
Until this is addressed, I've been working around by using HTML inside my markdown:

```
<span class="super">1</span>
```

Where 

```
{
  .super {
    vertical-align: super;
    font-size: 0.8rem;
}
```

Not the greatest, but it works!

**Comment by xieyuheng** [comment]
There is markdown-it-footnote: https://github.com/markdown-it/markdown-it-footnote

You do not have to wait for github to give a spec, to implement a useful support of footnote.

**Comment by RavenColEvol** [comment]
@UziTech is this issue still open ? I would like to contribute this feature.

**Comment by UziTech** [comment]
Ya go ahead. Thanks!

**Comment by RavenColEvol** [comment]
@UziTech I'll try to cover up these cases for foot note which is given in markdown-it-footnote

### Normal Footnote
```
Here is a footnote reference,[^1] and another.[^longnote]

[^1]: Here is the footnote.

[^longnote]: Here's one with multiple blocks.

    Subsequent paragraphs are indented to show that they
belong to the previous footnote.
```

### Inline footnote
```
Here is an inline note.^[Inlines notes are easier to write, since
you don't have to pick an identifier and move down to type the
note.]
```

output for above examples are given in there documentation ([here](https://github.com/markdown-it/markdown-it-footnote))

**Comment by bent10** [comment]
When considering the use of footnotes in your content, it's important to keep in mind the following accessibility and usability factors:

1. **Screen Reader Compatibility**: Screen readers may not effectively convey footnotes. They tend to read the footnote number without indicating that it's a footnote or using superscript. Additionally, they may not identify the link to the footnote text.
2. **Accessibility Challenges**: Footnotes pose challenges for all users on a web page. To access them, one often needs to scroll to the end of the page, read the footnote, and then click back to the main content. Not everyone is aware that they should click on the footnote at the end, potentially causing them to lose their place. Moreover, if the same footnote is repeated multiple times, clicking on the link could lead to the wrong location.

If you find it necessary to use footnotes, feel free to explore the [`marked-footnote`](https://github.com/bent10/marked-extensions/tree/main/packages/footnote) extension.

**Comment by UziTech** [comment]
I'm going to close this since there is an extension created
