### ISSUE TITLE
FR: Option to disable images

### ISSUE THREAD

**Issue by lschad** [markedjs/marked#719]
title.

I want to disable parsing images

```
![enter image description here](... "enter image title here")
```

should **not** be parsed

**Comment by Feder1co5oave** [comment]
See #420

**Comment by sahil290791** [comment]
Any updates on how can we disable parsing images?

**Comment by Feder1co5oave** [comment]
No commits were made since my last comment. That method I linked is still the easiest one to achieve what you need.

**Comment by joshbruce** [comment]
#989

**Comment by styfle** [comment]
I don't believe we need a new feature for this since it can be disabled as discussed in #420 and #1302

```js
const marked = require('marked');
const renderer = new marked.Renderer();

renderer.image = function (text) {
  return text;
};

var html = marked(markdownString, { renderer: renderer });
```
