### ISSUE TITLE
Control render order.

### ISSUE THREAD

**Issue by Steve-Mc** [markedjs/marked#817]
Is it possible to specify the order in which the markdown should be rendered? I am currently trying to find a way to render `paragraph` before `em`.

**Comment by joshbruce** [comment]
I don't believe so; or, more correctly, it already is??

Block elements begin being rendered (this would include `paragraph`). Part of rendering each block level element results in the rendering of inline elements (`em`). Therefore, paragraphs get rendered first but I don't believe there's a way to intercept that output before inline elements get processed.

Tagging @styfle and @UziTech in case I'm off here.
