### ISSUE TITLE
cannot generate ID for CJK characters in headings

### ISSUE THREAD

**Issue by mantou132** [markedjs/marked#838]
```
code: # 标题一
render result: <h1 id="-">标题一</h1>
```

**Comment by ginuim** [comment]
I have the same problem，a lot of id="-"

**Comment by Jiang-Xuan** [comment]
Renderer.prototype.heading = function(text, level, raw) {
		  return '<h'
		    + level
		    + ' id="'
		    + this.options.headerPrefix
		    + raw.toLowerCase().replace(/[^\w]+/g, '-')
		    + '">'
		    + text
		    + '</h'
		    + level
		    + '>\n';
		};

`raw.toLowerCase().replace(/[^\w]+/g, '-').`
this line cause problem.

**Comment by xzysun** [comment]
https://github.com/chjj/marked/issues/919#issuecomment-325099458

**Comment by joshbruce** [comment]
Closing as we are starting to really look at removing header ids from marked and improve ways for extenders to do this themselves.
