### ISSUE TITLE
how to import not require

### ISSUE THREAD

**Issue by sinkcup** [markedjs/marked#840]
```
import marked from 'marked';

return (<div>{ marked('I am using __markdown__.') }</div>);
```

error:

```
TypeError: src.replace is not a function
Please report this to https://github.com/chjj/marked
```

**Comment by sciborrudnicki** [comment]
As i see it works when you add 
`npm install @types/marked`
then
`
import 'marked';

marked('**bold**);
`

**Comment by ondrejsevcik** [comment]
Isn't this valid just for typescript?

**Comment by sciborrudnicki** [comment]
@ondrejsevcik it is, because of @types/marked.

**Comment by ondrejsevcik** [comment]
@chjj Would you accept PR solving this issue? I think it's a good time to start support import syntax.

**Comment by anowell** [comment]
fwiw, I was tripping over this until doing

```
import * as marked from 'marked';
console.log(marked('## foo'));
```

**Comment by ondrejsevcik** [comment]
@anowell unfortunately that doesn't work for me (I'm using it in Ember app).

**Comment by joshbruce** [comment]
@ondrejsevcik: I can say, we would definitely consider it. Having said that, focus right now is still security and fixing known failings we have with markdown specs; so, we may not be triaging tickets as much as you might think necessary.

If the solution can make `import` work without destroying `require`...don't see why we wouldn't at least have a healthy discussion around it.

**Comment by joshbruce** [comment]
See also #1106
