### ISSUE TITLE
Hash links with "&" are not converted the same way as github links

### ISSUE THREAD

**Issue by tannerlinsley** [markedjs/marked#857]
On github markdown, a header like this one:
## This & That Section
will write out an id like this: `this--that-section`

On markdown-loader, it writes out `this-that-section`

This breaks links that adhere to github markdowns syntax:
```
[This & That Section](#this--that-section)
```

Another example:
```javascript
const marked = require("marked");

marked("# This & That Section");
// => '<h1 id="this-that-section">This &amp; That Section</h1>\n'`
```

Filed originally at https://github.com/peerigon/markdown-loader/issues/17

**Comment by joshbruce** [comment]
#984

**Comment by joshbruce** [comment]
#981
