### ISSUE TITLE
A question, how could I insert gist script in markdown ?

### ISSUE THREAD

**Issue by liu0fanyi** [markedjs/marked#864]
I have tried this.
```javascript
renderer.code = function coder(code, lang) {
	if (lang === 'gist') {
		return code;
	}
        return ...
};

```

And I get <script/> in chrome debug mode.
But gist not display on the screen...

**Comment by joshbruce** [comment]
Closing as not part of the current focus, see #1106 and #1216. Also, honestly not sure I'm following what's being attempted. Please resubmit an issue using the provided template.
