### ISSUE TITLE
Remove line break in CJK text.

### ISSUE THREAD

**Issue by thynson** [markedjs/marked#90]
First, sorry for my poor English.
One thing annoying me is 

```
你好！
谢谢
```

will be render to

```
<p>你好！
谢谢</p>
```

In the browser a space will appears between "你好！" and "谢谢" when page are rendered.
This is fine in English and those languages seperate words by space. However for Chinese, Japanese and Korean, the extra line break(which will rendered as a space) is not nessaray.

P.S. I know actually this issue is of markdown specs, but I use marked in my project, so I report this issue here. Ugly workaround exists for me, but I wish to have it as a feature of marked.

**Comment by chirsz-ever** [comment]
This issue did not be resolved.

When the Markdown input is like that (no extra whitespace before newline):

```
你好
谢谢
```

The rendered visual result would be (I use `␣` to replace the invisible whitespace):

```
你好␣谢谢
```

For CJK, the whitespace is not expected. This behavior works fine for writing systems that use spaces to separate words, but not for Chinese or Japanese[^1]. `breaks: true` cannot solve the problem, it just replace newline to `<br/>`.

[^1]: Korean has spaces to separate words.

The current behavior [conforms to CommonMark](https://spec.commonmark.org/0.31.2/#soft-line-breaks). We may solve the problem with an extension or a plugin, like [markdown-it-cjk-breaks](https://github.com/markdown-it/markdown-it-cjk-breaks) and pandoc's [east_asian_line_breaks](https://pandoc.org/MANUAL.html#extension-east_asian_line_breaks).

More discussions:

- https://github.com/commonmark/commonmark-spec/issues/744
- https://talk.commonmark.org/t/soft-line-breaks-should-not-introduce-spaces/285

Could you please reopen this issue?

**Comment by UziTech** [comment]
We use our open issues like a backlog of things we could work on in marked. It sounds like creating an extension is the way to go, so there is nothing to work on in marked.

Once you create the extension you can open a PR to add the extension to our [known extensions](https://marked.js.org/using_advanced#extensions). 😁👍
