### ISSUE TITLE
V0.3.6,<h1>,<h2>,<h3>,<h4>,<h5>,<h6>sometimes id are same

### ISSUE THREAD

**Issue by osoc** [markedjs/marked#919]
# test 01 [ok]

```
//md:

# h1

## h2

//out:
<h1 id="h1">h1</h1>
<h2 id="h2">h2</h1>
```

----

# test 02 [the same id]

```
//md:
# h1
# h1
//out:
<h1 id="h1">h1</h1>
<h1 id="h1">h1</h1>
```

# test 03 [the same id]
```
//md:
# 这行只有汉字
# 这行也是
//out:
<h1 id="-">这行只有汉字</h1>
<h1 id="-">这行也是</h1>
```
---
# test 04 [the same id]
```
//md:
## 这行只有汉字
## 这行也是
//out:
<h2 id="-">这行只有汉字</h1>
<h2 id="-">这行也是</h1>
```

**Comment by tagia0212** [comment]
I have a same problem...

**Comment by tagia0212** [comment]
I solved this by overriding `marked.Renderer#heading` function.

```
const renderer = new marked.Renderer();
renderer.heading = function(text, level) {
    return `<h${level} id="${text}">${text}</h${level}>`;
};

marked(mdString, { renderer: renderer });
```

It seems to be natural to assume the above-mentioned behavior is a specification.

**Comment by osoc** [comment]
I do it：
[ The full code is here ](https://github.com/osoc/osoc_marked.js/blob/0.3.6_osoc-p1/osoc_marked.js)
```
var ID_TABLE = "0123456789ABCDEF";
var AUTOID = 0x0001;
...
Renderer.prototype.heading = function(text, level, raw) {
  var id, tmp;
  tmp = AUTOID++;
  id = ID_TABLE.charAt((tmp >> 12) & 0x0F);
  id += ID_TABLE.charAt((tmp >> 8) & 0x0F);
  id += ID_TABLE.charAt((tmp >> 4) & 0x0F);
  id += ID_TABLE.charAt(tmp & 0x0F);
  return '<h'
    + level
    + ' id="'
    + id
//    + this.options.headerPrefix
//    + raw.toLowerCase().replace(/[^\w]+/g, '-')
    + '">'
    + text
    + '</h'
    + level
    + '>\n';
};
```

**Comment by joshbruce** [comment]
#981

**Comment by Feder1co5oave** [comment]
There's no perfect way to generate IDs. The "naive" way to fix this would be to add a numeric counter to duplicate IDs, but that would require **keeping track of all IDs**.

**Comment by joshbruce** [comment]
I still think the easiest way is to not have Marked do it. This is what I used to do back in the day for scrolling table of contents a la Bootstrap - http://getbootstrap.com/2.3.2/getting-started.html

Step one: Convert Markdown to HTML.
Step two (DOM is ready/loaded): Cycle through the headers to add ID attributes and generate the TOC in shot.

No JS solution = no TOC; therefore, no reason to have the IDs in the first place.

Again, could just be asking Marked to do too much. If a spec has it, we should too but, if a spec has it, it should define the testable rules for implementing the solution, yeah?

**Comment by yzfdjzwl** [comment]
@tagia0212 
if your header includes `()`, it will failure. eg:
```javascript
### do something()
```

**Comment by joshbruce** [comment]
#1048

**Comment by joshbruce** [comment]
Closing as most likely going to be deprecated at a later date.

**Comment by Grawl** [comment]
The problem still exists.

**Comment by styfle** [comment]
Yes, this problem still exists.

Let's consolidate this issue with a similar one here: #1280

**Comment by joshbruce** [comment]
Sidenote: GitHub adding detail popovers on hover...fancy. 😎
