### ISSUE TITLE
Register Click on markdown file

### ISSUE THREAD

**Issue by marc101101** [markedjs/marked#921]
Hello, 

I have an issue with my current project. I render my markdown file and in this markdown file are urls to other markdown documents.
Is it possible to render these documents again in my application, instead of the old markdown file?
My project is based on Angular2.

Do you have any idea - how this can work?

**Comment by Feder1co5oave** [comment]
I can't really understand what this is about. Suggestion: override the link renderer.

**Comment by joshbruce** [comment]
Are you wanting Marked to render the links documents? Are the links going to the Markdown file (.md) and not a page that displays the rendered markdown file?

**Comment by joshbruce** [comment]
Closing as beyond scope.
