### ISSUE TITLE
[Vision alignment]: Comparative benchmarking - high-speed

### ISSUE THREAD

**Issue by joshbruce** [markedjs/marked#963]
What other markdown compilers are there for JS now?

Would be worthwhile to put together a list of compilers (markdown-it, for example) and a complex (but sane) markdown file to do comparative benchmarking. 

If we aren't faster than them, then we aren't achieving the primary purpose of marked...high-speed.

See also #956

**Comment by worker8** [comment]
I found this site jsperf.com for comparing javascript library performance.

Someone wrote a test for comparing the performance for a list of markdown compilers:

https://jsperf.com/showdown-js-vs-marked/10

![screen shot 2018-01-05 at 12 39 29 pm](https://user-images.githubusercontent.com/1988156/34594626-8ddf4b74-f215-11e7-9257-7bedf2245c56.png)

According to the tests, there are a few libraries ranked higher than marked.

**Comment by Feder1co5oave** [comment]
newer version:
https://jsperf.com/showdown-js-vs-marked/19
also:
https://github.com/commonmark/commonmark.js#performance

**Comment by calculuschild** [comment]
First, is there a good online benchmark anymore? The jsperf links above seem to be broken.

Running the Marked bench script on my own machine is showing Commonmark and Marked-It as both faster and more compliant. Can you point to any techniques that used to give you the edge that aren't working anymore, or recent updates that introduced a lot of slowdown? I'd be interested in taking a look.

**Comment by UziTech** [comment]
I don't know of any online benchmarks.

I think #1686 made a bit of a slow down but also markdown-it has been getting faster with recent releases. I don't know of any simple ways to increase the speed.

**Comment by calculuschild** [comment]
> I think #1686 made a bit of a slow down

I'm sure it did, there was a lot going on in there. I wonder if... there's a way to show kind of a benchmark score per release? Run some kind of automated benchmark on all releases up to this point, and collect that info somewhere useful so it could be plotted and compared, maybe as a page on the documentation?

**Comment by UziTech** [comment]
We tried to integrate the benchmarks into our testing but test servers are extremely inconsistent
