### ISSUE TITLE
[Vision alignment]: Comparative benchmarking - low-level

### ISSUE THREAD

**Issue by joshbruce** [markedjs/marked#965]
What other markdown compilers are there for JS now?

Would be worthwhile to put together a list of compilers (markdown-it, for example) and note whether the library is considered low-, medium-, or high-level based on, at a minimum, the following criteria:

Non-dev package dependency count and type: less than 2 that can be opted into, not required = low, everything else is medium or high.

If we are abstracting by extending, then we probably aren't achieving the tertiary purpose of marked...low-level.

See also #956

**Comment by Feder1co5oave** [comment]
I don't think marked ever claimed to be low-level

**Comment by joshbruce** [comment]
@Feder1co5oave: That could be fair. I'm not basing it on a claim made by Marked, but by its design. No dependencies. Usually used *as* a dependency in something else. Like Gulp compared to Angular, for example.

Again, not based on claim - based on architecture. 

In this regard it reminds me of the 8fold UI Kit suite. Component is low-level, wicked fast, and highly flexible (https://github.com/8fold/php-html-component)...Elements is mid-level, still wicked fast, and specifies the entire HTML 5.0 spec, I think (https://github.com/8fold/php-html - haven't gotten around to needing to update to 5.1)...UIKit itself is high-level, still wicked fast, and creates various APIs for generating full elements (https://github.com/8fold/php-uikit). With the speed tests though, I'm most strict on Component, because it's the foundation upon which all the others are built - and slow things down.
